### ISSUE TITLE
Stylus won't update without --no-cache

### ISSUE THREAD

**Issue by AshotN** [parcel-bundler/parcel#4217] opened 2020-02-25 11:23 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel watch index.html --no-cache`

```
{
    "name": "ampache-client",
    "version": "1.0.0",
    "description": "Client side for Ampache server",
    "repository": "https://github.com/ampache/ampache/tree/react-client",
    "author": "Ashot Nazaryan",
    "license": "AGPL-3.0-only",
    "dependencies": {
        "@babel/runtime": "^7.7.4",
        "@types/wicg-mediasession": "^1.0.3",
        "axios": "^0.19.0",
        "images": "^3.0.2",
        "js-cookie": "^2.2.1",
        "react": "^16.12.0",
        "react-audio-player": "https://github.com/justinmc/react-audio-player",
        "react-dom": "npm:@hot-loader/react-dom",
        "react-hotkeys-hook": "^1.5.3",
        "react-input-range": "^1.3.0",
        "react-loading": "^2.0.3",
        "react-router-dom": "^5.1.2",
        "react-toastify": "^5.4.1",
        "react-use-context-menu": "^0.1.3"
    },
    "scripts": {
        "start": "parcel start index.html",
        "build": "parcel build index.html",
        "prod": "rm -rf dist && parcel build index.html --no-source-maps",
        "watch": "parcel watch index.html --no-cache"
    },
    "eslintConfig": {
        "extends": "react-app"
    },
    "default": "dist/index.html",
    "targets": {
        "default": {
            "publicUrl": "/client/dist/"
        }
    },
    "browserslist": {
        "production": [
            "last 1 version",
            "> 1%",
            "not dead"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "postcss": {
        "plugins": {
            "autoprefixer": true
        }
    },
    "devDependencies": {
        "@babel/core": "^7.8.3",
        "@babel/plugin-proposal-class-properties": "^7.8.3",
        "@babel/plugin-transform-runtime": "^7.8.3",
        "@babel/preset-env": "^7.8.3",
        "@babel/preset-react": "^7.8.3",
        "@babel/preset-typescript": "^7.8.3",
        "@parcel/resolver-default": "^2.0.0-alpha.3",
        "@types/node": "^12.12.14",
        "@types/react": "^16.9.11",
        "@types/react-dom": "^16.9.4",
        "@types/react-router-dom": "^5.1.2",
        "@typescript-eslint/eslint-plugin": "^2.10.0",
        "@typescript-eslint/parser": "^2.10.0",
        "autoprefixer": "^9.7.4",
        "eslint": "^6.7.2",
        "eslint-plugin-react": "^7.17.0",
        "eslint-plugin-react-hooks": "^2.3.0",
        "parcel": "^2.0.0-alpha.3.2",
        "postcss-modules": "^1.5.0",
        "prettier": "1.19.1",
        "stylus": "^0.54.7",
        "typescript": "^3.7.2"
    },
    "alias": {
        "components": "./src/components"
    }
}

```

```
{
    "presets": [
        "@babel/preset-typescript",
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime",
        "@babel/plugin-proposal-class-properties"
    ]
}
```

## 🤔 Expected Behavior

A change in the `.styl` file should cause a change.

## 😯 Current Behavior

Parcel detects the change and rebuilds, but nothing changes. Even with a refresh.

## 💁 Possible Solution

I'm going to assume it's something to do with the cache, as using the `--no-cache` flag with `parcel watch` seems to allow Parcel to properly build the `styl` files.
## 💻 Code Sample

https://github.com/ampache/ampache/tree/react-client

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-alpha.3.2
| Node             |13.7.0
| Yarn         | 1.19.2
| Operating System |Ubuntu Budgie

**Comment by dandv** [comment] 2020-04-03 19:51
Thanks for filing this! Mentioning the `--no-cache` switch helped me realize that the source maps were outdated. They were completely off, driving Chrome DevTools into the woods.

**Comment by AshotN** [comment] 2020-04-06 10:26
Well hopefully a solution can be found without to much work :)

Sadly building without cache takes a decent bit longer.

**Comment by devongovett** [comment] 2020-04-06 16:03
Likely due to #3708

**Comment by mischnic** [comment] 2020-08-25 12:02
I'm guessing this is changing styles files that were `@import`ed by other stylus files.

Duplicate of https://github.com/parcel-bundler/parcel/issues/3708

**Closed by mischnic** 2020-08-25 12:02 UTC
Labels: :bug: Bug, ✨ Parcel 2, 💰 Cache, 🔌 Parcel 2 Plugins
