### ISSUE TITLE
hmr-port parameter is ignored if equal to serve port

### ISSUE THREAD

**Issue by fabioimpe** [parcel-bundler/parcel#7640] opened 2022-02-02 09:32 UTC
# 🐛 bug report

Pull request [#6005](https://github.com/parcel-bundler/parcel/pull/6005) avoid to set explicitly provided HMR port when equal to the serve port. This is an issue to me because I'm in a scenario where I need to force that port to enable hot module reloading to a section provided by parcel of my application served by an external host.

## 🤔 Expected Behavior

HMR_PORT should be set when explicitly provided without applying any exotic logic.

## 😯 Current Behavior

HMR_PORT is set to null when equal to the serve port.

## 💁 Possible Solution

Set HMR_PORT when explicitly provided by parameter

## 🔦 Context

Parcel is serving just a section of my application which is served by an external host, setting HMR_PORT to null even if parameter is provided. This makes impossible to use hot module reloading feature in this scenario.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             |  16.13.1
| npm/Yarn         | yarn 1.22.17
| Operating System | macos 11.5.2

**Comment by fabioimpe** [comment] 2022-02-03 11:00
I created this workaround plugin https://www.npmjs.com/package/parcel-transformer-hmr-options-override

**Comment by bjornhanson** [comment] 2022-03-01 21:16
Had the same problem with parcel@2.3.2 and the workaround plugin fixed the issue for me.

**Comment by mischnic** [comment] 2022-03-04 18:12
Duplicate of https://github.com/parcel-bundler/parcel/issues/6061

**Closed as completed by mischnic** 2022-03-04 18:12 UTC
