### ISSUE TITLE
new Worker(new URL(...), { type: "module" }) results in invalid code

### ISSUE THREAD

**Issue by RReverser** [parcel-bundler/parcel#5920] opened 2021-02-24 19:33 UTC
# 🐛 bug report

Trying latest nightly (2.0.0-nightly.607), code like this fails to transpile correctly:

```js
const worker = new Worker(new URL('./workerHelpers.js', import.meta.url), {
  type: 'module'
});
```

## 🤔 Expected Behavior

It results in something like

```js
new Worker('relative-path-after-bundling')
```

with URL transpiled to the bundled worker path and `type: 'module'` removed (because it's no longer an ESM).

## 😯 Current Behavior

It results in (`--no-optimize` for readability):

```js
const worker = new Worker(Promise.resolve($d15010e440eb1ef867c1e32ed9720f14$exports), {
  type: 'module'
});
```

which is obviously wrong, and results in browser trying to stringify the promise and then fetch URLs:

![image](https://user-images.githubusercontent.com/557590/109055325-edd26680-76d6-11eb-82c6-6f96d4a84980.png)

## 🔦 Context

I think this used to work on v2, but perhaps was broken as part of https://github.com/parcel-bundler/parcel/pull/5846 (or maybe earlier, idk). /cc @mischnic

**Comment by mischnic** [comment] 2021-02-24 19:49
> type: 'module' removed (because it's no longer an ESM).

 No, it will be ESM, so this is "per design" at the moment. But it will be fixed by https://github.com/parcel-bundler/parcel/pull/5398

> new Worker(Promise.resolve

I can't reproduce that with just your code snippet.

**Comment by RReverser** [comment] 2021-02-24 20:09
> I can't reproduce that with just your code snippet.

That's... unfortunate. Let me try how to extract more.

**Comment by devongovett** [comment] 2021-02-24 20:13
Is it possible that workerHelpers.js also required synchronously somewhere else? Maybe something with internalization went wrong?

**Comment by RReverser** [comment] 2021-02-24 20:15
> Is it possible that workerHelpers.js also required synchronously somewhere else?

It definitely is. It's simultaneously a code for the Worker and a util to start one. Is that a problem?

**Comment by RReverser** [comment] 2021-02-24 20:20
So yeah here's an oversimplified example that still shows the issue:

**workerHelpers.js**

```js
export async function startWorkers() {
  new Worker(new URL('./workerHelpers.js', import.meta.url));
}
```

**index.js**

```js
import {startWorkers} from './workerHelpers.js';

startWorkers().then(() => console.log('ready'));
```

**output for workerHelpers.js**

```js
(function () {
  function $parcel$export(e, n, v) {
    Object.defineProperty(e, n, {
      get: v,
      enumerable: true
    });
  }
  // ASSET: workerHelpers.js
  var $9c6bee2e915846b2bd927a5588d0646e$exports = {};
  async function startWorkers() {
    new Worker(Promise.resolve($9c6bee2e915846b2bd927a5588d0646e$exports));
  }
  $parcel$export($9c6bee2e915846b2bd927a5588d0646e$exports, "startWorkers", function () {
    return startWorkers;
  });
})();

//# sourceMappingURL=workerHelpers.1fc04b78.js.map
```

**Comment by mischnic** [comment] 2021-02-24 20:26
Ah, the Worker imports itself.

**Comment by devongovett** [comment] 2021-02-24 20:32
Yeah we should not internalize async dependencies across different environment contexts and instead duplicate the module.

**Comment by RReverser** [comment] 2021-03-11 16:30
Just to check - I suppose this issue requires some major refactoring and not a quick fix? (it's fine either way, just want to know whether to document compatibility with Parcel 2 in my lib)

**Comment by mischnic** [comment] 2021-03-11 19:32
This shouldn't be that hard to fix, looks like this section here is responsible for (incorrectly) optimizing away the worker bundle:

https://github.com/parcel-bundler/parcel/blob/7eb2b1630a7de109e26af5f2f2b5091164058d0e/packages/bundlers/default/src/DefaultBundler.js#L188-L233

But bugs involving the bundler logic are often rather tricky

**Closed** 2021-07-12 23:25 UTC
Labels: :bug: Bug, Bundler, ✨ Parcel 2
