### ISSUE TITLE
Live reloading not working with PostCSS / CSS modules

### ISSUE THREAD

**Issue by sergey-pimenov** [parcel-bundler/parcel#7356] opened 2021-11-24 11:59 UTC
Hello! I have some problems with styles live reloading after updating from Parcel 1 to Parcel 2.
Live reloading doesn't work **for styles**. For JS/React everything works fine.

So, my `.postcssrc` config:

```json
{
  "modules": true,
  "syntax": "postcss-scss",
  "plugins": {
      "postcss-nested": {}
  }
}
```

`package.json`:

```json
{
  "name": "verv-stripe-web",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "parcel ./src/index.html",
    "prepare": "husky install"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/runnerredrock/verv-stripe-web.git"
  },
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/runnerredrock/verv-stripe-web#readme",
  "dependencies": {
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@glidejs/glide": "^3.4.1",
    "@parcel/transformer-sass": "^2.0.1",
    "@stripe/react-stripe-js": "^1.1.2",
    "@stripe/stripe-js": "^1.10.0",
    "autoprefixer": "^10.2.5",
    "classnames": "^2.2.6",
    "cli-progress": "^3.9.0",
    "core-js-compat": "^3.4.7",
    "email-validator": "^2.0.4",
    "fs-extra": "^9.1.0",
    "googleapis": "^68.0.0",
    "modern-css-reset": "^1.1.1",
    "parcel": "^2.0.1",
    "postcss": "^8.2.15",
    "postcss-nested": "^5.0.5",
    "postcss-scss": "^3.0.5",
    "react": "^16.14.0",
    "react-countdown": "^2.3.1",
    "react-dom": "^16.14.0",
    "react-fetch-hook": "^1.8.5",
    "react-redux": "^7.2.4",
    "react-tabs": "^3.2.2",
    "sweetalert2": "^11.0.16"
  },
  "devDependencies": {
    "@babel/core": "^7.14.3",
    "@babel/preset-react": "^7.13.13",
    "@playwright/test": "^1.14.0",
    "husky": "^7.0.2"
  }
}

```

Exported styles (`someComponent.js`):
```js
import './index.scss';
```

Styles file (`index.scss`):
```scss
:global {
  .myComponent {
     margin-top: 35px;
  }
}
```

What I already have tried.

Exported styles with this style (`someComponent.js`):
```js
import s from './index.scss';
```

Use css modules like this:
```js
import s from './index.scss';

function someComponent() {
  return (
    <div className={s.myComponent}></div>
  )
}
```

Also I have tried these:
* Update postcss to last version
* Install Parcel 2.0.0 instead of 2.0.1
* Disable caching (`--no-cache`)
* Reinstaling node_modules/clean cache & dist etc.

With all these methods, the styles were applied, but live reloading is not working.
If I totaly remove the `.postcssrc` live reloading works fine. But I need postcss. Mb somebody have ideas how to avoid this? Without live-reloading the speed of development slows down very much :(

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 14.17.6
| npm/Yarn         | 6.14.15
| Operating System | macOS 12.0.1

**Comment by mischnic** [comment] 2021-11-24 12:55
Duplicate of https://github.com/parcel-bundler/parcel/issues/7098

**Closed as completed by mischnic** 2021-11-24 12:55 UTC
