### ISSUE TITLE
How can I ignore the automatic resolution of a image path?

### ISSUE THREAD

**Issue by reebr** [parcel-bundler/parcel#2637] opened 2019-02-12 14:56 UTC
I'm trying to use the [plain text](https://pugjs.org/language/plain-text.html) feature of Pug to define the content of a `<img>` tag based on a variable value. I have a boolean variable that defines when I'm in "development mode". When this value is set to `false` I would like to use a raw string that will be processed by my server (it is a Flask application).

So I've tried this:

```pug
if development
   img#qr-code(src='https://via.placeholder.com/300')
else
   | <img src='{{ qrcode }}' id='qr-code'>
```

I'm expecting on development mode:
```html
<img id='qr-code' src='https://via.placeholder.com/300'>
```

And, for production:
```html
<img src='{{ qrcode }}' id='qr-code'>
```

When I compile it with `- var development = true`, everything works.
But, when I use `- var development = false`, it fails.

> $ parcel src/template/*.pug

> Server running at http://localhost:1234 
×  C:\Users\renan\Desktop\development\parcel-test\src\template\{{ qrcode }}: ENOENT: no such file or directory, open 'C:\Users\renan\Desktop\development\parcel-test\src\template\{{ qrcode }}'

> Error: ENOENT: no such file or directory, open 'C:\Users\renan\Desktop\development\parcel-test\src\template\{{ qrcode }}'

I think that Parcel is trying to resolve the image path in `{{ qrcode  }}`, because the problem [is not in Pug](https://github.com/pugjs/pug/issues/3111). How can I ignore or bypass it? I would like to have the raw string.

**Comment by mischnic** [comment] 2019-02-13 20:19
> How can I ignore or bypass it?

Currently, this is unfortunately not possible.

**Comment by RobertWHurst** [comment] 2019-02-26 04:21
Why is parcel trying to process plain text? It shouldn't be in that part of the AST, should it? If that's the intention, why? I don't see the use case.

**Comment by DeMoorJasper** [comment] 2019-02-26 13:15
There is no way to tell if a url is a url or plain text.
A url can be anything as we don't require it to be preceded by a `./` or `/` or `~/`.
So `{{ qrcode }}`, could in theory just be a file `./{{ qrcode }}`

**Comment by RobertWHurst** [comment] 2019-02-27 07:34
@DeMoorJasper ah, I see. I thought pug HTML escapes plain text, but I can see now it doesn't. I saw this issue and was thinking any URL in plain text was processed, but clearly, this is only an issue if you are embedding HTML into pug which seems like a strange thing to do anyway.

**Comment by mischnic** [comment] 2019-03-05 21:26
Closing as duplicate of #1186

**Closed by mischnic** 2019-03-05 21:26 UTC
Labels: :grey_question:  Question
