### ISSUE TITLE
Parcel 2: React Refresh doesn't work with .jsx or .tsx files

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#3946] opened 2019-12-28 21:41 UTC
# 🐛 bug report

I'm super excited about the Parcel 2, especially the new [react refresh](https://github.com/parcel-bundler/parcel/pull/3654) feature - thanks for putting it out there! I went to kick the tires, and I found that it doesn't seem to work correctly if the files containing the components are `.jsx` or (with a valid typescript config) `.tsx`

## 🎛 Configuration (.babelrc, package.json, cli command)

 - [Working config](https://github.com/astegmaier/parcel2-react-refresh/tree/master) (where the files containing the components are `.js`) - no `.babelrc`, `.tsconfig`, or `.parcelrc`
 - [Broken `jsx` config](https://github.com/astegmaier/parcel2-react-refresh/tree/broken-jsx) - no `.babelrc`, `.tsconfig`, or `.parcelrc`
 - [Broken `tsx` config](https://github.com/astegmaier/parcel2-react-refresh/tree/broken-tsx) - `no `.babelrc` or `.parcelrc`. `.tsconfig` is:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "jsx": "react",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
## 🤔 Expected Behavior

It is possible to...
1. run `parcel serve` and open the project in the browser
2. change react state
3. modify a component
4. have that component refresh in the browser without blowing away state.

## 😯 Current Behavior

The project where the files containing the components are named `.js`, everything works as expected.

For the project where the files containing the components are named `.jsx`, or where I use typescript (with `.tsx` files), the entire page is refreshed at step 4.

## 🔦 Context

Just kicking the tires of the new Alpha release to help find bugs so it can get ready for prime time.

## 💻 Code Sample

 - [Working config](https://github.com/astegmaier/parcel2-react-refresh/tree/master) (where the files containing the components are `.js`)
 - [Broken `jsx` config](https://github.com/astegmaier/parcel2-react-refresh/tree/broken-jsx)
 - [Broken `tsx` config](https://github.com/astegmaier/parcel2-react-refresh/tree/broken-tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-alpha.3.2
| Node             | 10.16.3
| npm/Yarn         | 1.21.1
| Operating System | OSX 10.15.2

**Comment by mischnic** [comment] 2019-12-29 14:27
This is already fixed and will be published in the next release.

Duplicate of https://github.com/parcel-bundler/parcel/issues/3844

**Closed by mischnic** 2019-12-29 14:27 UTC
