### ISSUE TITLE
Restricting files in node_modules getting bundled 

### ISSUE THREAD

**Issue by hhshan** [parcel-bundler/parcel#2953] opened 2019-04-24 06:59 UTC
# ❔ Question

I am developing an npm module using react. In this module I am using an external styling libraray (which I have added as a dependency so that the said library too will be installed when installing my module) and using its fonts and images via an import like so:
```
import icons from 'style-npm-module/dist/icons/icons.svg';
import logo from 'style-npm-module/dist/logos/logo.svg';
```
When bundled, parcel has fetched these files from the npm module, added to the dist folder and changed the imports to relative paths and the folder structure looks like this:
```
dist
  |-index.js
  |-logo.{some-random-number}.svg
  |-font.{some-random-number}.svg
```
and in the index.js these files are referred as `"/logo.{some-random-number}.svg"` or `"/font.{some-random-number}.svg"` instead of referncing it to the npm module.

parcel bundle command is as follows,
```
parcel build ./src/index.js --out-dir ./dist --no-source-maps
```
Is it possible to restrict these kind of imports being changed and force parcel to keep the imports as is referring to the node_modules?

## 🔦 Context

When trying to bundle with parcel, images referred in node_modules too get budled in the dist changing the imports to a relative path.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | 6.4.1
| Operating System | macOS Mojave

**Comment by imadx** [comment] 2019-05-02 08:28
I met with the same problem.
When using Webpack you have control over the files that you output. However, it's not the case with Parcel.

Could there be an option to ignore the assets from being bundled?
Maybe with something like using a `.parcelignore`?

**Comment by mischnic** [comment] 2019-05-04 15:04
Duplicate of #144

**Closed by mischnic** 2019-05-04 15:04 UTC
Labels: :grey_question:  Question
