### ISSUE TITLE
source entry on package.json doesn't accept globs

### ISSUE THREAD

**Issue by salazarr-js** [parcel-bundler/parcel#7327] opened 2021-11-18 20:39 UTC
parcel command fails when try to use a `glob` as source on the `package.json`

![image](https://user-images.githubusercontent.com/9486209/142492502-df2c2f72-a270-4204-9c4a-a0849995f0bd.png)

but works perfectly when is used from CLI

![image](https://user-images.githubusercontent.com/9486209/142493021-c635506a-645d-408d-9a36-c048d84eece0.png)

## Little workaround
i can use the CLI from the scripts using `npx parcel src/index.html 'src/*/*.html'` and works smoothly 
```json
  "scripts": {
    "dev": "npx parcel src/index.html 'src/*/*.html'",
    "build": "npx parcel build src/index.html 'src/*/*.html'"
  },
```
but it'd be nice that we can use globs on `source` entries too

**Comment by mischnic** [comment] 2021-11-19 11:00
Duplicate of https://github.com/parcel-bundler/parcel/issues/3821

**Closed as completed by mischnic** 2021-11-19 11:00 UTC
