### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by bradtraversy** [parcel-bundler/parcel#315] opened 2017-12-17 12:27 UTC
Hello, I am trying to get started with Parcel. I created an index.html file with an index.js and when I run

`parcel index.html`

localhost:1234 opens fine but as soon as I save the file the server stops and I get

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:999:13)
    at TCP.onread (net.js:629:25)
```

**Comment by DeMoorJasper** [comment] 2017-12-17 12:33
Is there any logs on the bundler side?
Or is this the bundler side?
And could u specify in a bit more detail what you did/fill in the bug report form

**Comment by JounQin** [comment] 2017-12-17 13:14
It seems a issue of `ws@3.3.3`, downgrade and lock `ws@3.3.2` works to me.

Related: https://github.com/lc60005457/parcel-plugin-vue/issues/4#issuecomment-352253498

**Comment by DeMoorJasper** [comment] 2017-12-17 13:15
Thanks for looking into this, i'll dive into this a bit and report what i found or do a PR

**Comment by DeMoorJasper** [comment] 2017-12-17 13:47
Pinpointed the situation, it had to do with an error that got added to ws (when user disconnects while sending), This gets triggered every time the websocket triggers a html reload (if u edit a html file)
I'll do a PR with a bugfix in a bit

**Comment by chasegiunta** [comment] 2017-12-17 18:39
Am I wrong or does this bug completely break Parcel in dev at the moment? Wanted to get check out Parcel today but crashes on every change.

**Comment by DeMoorJasper** [comment] 2017-12-17 18:41
It breaks the moment you change html files

**Comment by chasegiunta** [comment] 2017-12-17 18:48
For me, it's breaking just upon reloading a page that is including the output. No html file change needed.

I'm running `parcel src/main.js -d web/dist`, and including only `<script src="/dist/main.js"></script>` on my page.

**Comment by DeMoorJasper** [comment] 2017-12-17 18:53
Than it's affecting more people than expected, i'll do my best to speedup getting the PR through

**Comment by peterpeterparker** [comment] 2017-12-17 19:44
So, I land here because I was googling the same today's error output (ionic project) https://github.com/ionic-team/ionic-cli/issues/2921

@DeMoorJasper  are you facing that issue only with Chrome too?
Did you find any lead to solve it? something linked with websocket?

**Comment by DeMoorJasper** [comment] 2017-12-17 19:47
@peterpeterparker look at PR #320 
It had to do with page reloads disconnecting the client websocket from the server, which resulted in ECONNRESET, it used to be ignored in WS 3.3.2 that's why it just became an error after the update...

**Comment by peterpeterparker** [comment] 2017-12-17 19:49
@DeMoorJasper neat, thx for pointing that out 👍

**Comment by goyney** [comment] 2017-12-17 21:01
I'm hear to report I'm having a very similar issue. I can start the parcel server, but I see this when it is starting...

```
yarn run v1.3.2
$ parcel -p 3000 ./public/index.html
⏳  Building...
Server running at http://localhost:3000 - configured port 3000 could not be used.
```

However, when I go to http://localhost:3000, the app responds. If I change any files, I see the changes happen. The second I refresh the page though, I get...

> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at _errnoException (util.js:1024:11)
>     at TCP.onread (net.js:615:25)
> error Command failed with exit code 1.

**Comment by davidnagli** [comment] 2017-12-17 21:13
@goyney This will be fixed once PR #320 lands

**Comment by JounQin** [comment] 2017-12-17 23:09
@goyney Are you sure you've downgraded ws successfully? Check `package-lock.json` or `yarn.lock` to confirm that.

 And I'm using `resolutions` of yarn to lock ws version, it really works to me.

https://github.com/JounQin/parcel-study/blob/master/package.json

**Comment by SAMYJ1** [comment] 2017-12-18 06:48
I faced the same problem when I reload the web page. I wish the bug will be fixed as soon as possible.

**Comment by wangjian1119** [comment] 2017-12-18 07:55
@JounQin  hello,Can the downgrade ws to @3.3.2 solve the problem？

**Comment by JounQin** [comment] 2017-12-18 08:05
@wangjian1119 I solve this problem by locking `ws@3.3.2` for now with `yarn` `resolutions`

https://github.com/JounQin/parcel-study/blob/master/package.json#L70

You can just try it.

**Comment by DeeJayElly** [comment] 2017-12-18 10:42
Guys this resolved the problem

Just run:

`npm i -D -E ws@3.3.2`

[https://github.com/ionic-team/ionic-cli/issues/2921#issuecomment-352359738](https://github.com/ionic-team/ionic-cli/issues/2921#issuecomment-352359738)

**Comment by carrillocarlosce** [comment] 2017-12-18 11:16
@DeeJayElly your solution work for me thanks;

**Comment by DeMoorJasper** [comment] 2017-12-18 11:37
Not using chrome or disabling hmr should also work btw

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lyyh** [comment] 2017-12-18 11:56
@DeeJayElly thanks!This is a good way of resolution

**Comment by angganegara** [comment] 2017-12-18 18:19
hmmm @DeeJayElly solution is not working for me. Parcel still crashed when I manually reload the page. I'm using the latest Chrome and ws@3.3.2. It's working fine in Safari though.

**Closed** 2017-12-18 20:10 UTC
Labels: #Bug, Confirmed Bug

**Comment by devongovett** [comment] 2017-12-18 20:13
Fix pushed in v1.2.1.

**Comment by angganegara** [comment] 2017-12-19 04:38
@devongovett I can confirm this push fixes the issue for me. Cheers

**Comment by a313008430** [comment] 2017-12-22 03:09
`wss.on('connection', function (ws) {
ws.on('error', function (msg) { //must 
        console.log(msg)
    })
    ws.on('close', function (msg) { //must
        console.log(msg)
    })

})`

**Comment by MatthewSmithwebdesign** [comment] 2018-01-20 18:51
I am getting this error in my dist js file.
  var ws = new WebSocket('ws://' + window.location.hostname + ':50013/');

**Comment by darwinphi** [comment] 2018-04-28 04:28
Try to install parcel locally
