### ISSUE TITLE
Parcel 2: Cache bug

### ISSUE THREAD

**Issue by Drapegnik** [parcel-bundler/parcel#3409] opened 2019-08-15 15:10 UTC
# 🐛 bug report
Parcel 2 returns the cached version, even after cli command re-run:

[![Image from Gyazo](https://i.gyazo.com/d302b03ac07e7cda3c3673378f298e11.gif)](https://gyazo.com/d302b03ac07e7cda3c3673378f298e11)

<img width="1440" alt="Screen Shot 2019-08-15 at 18 00 28" src="https://user-images.githubusercontent.com/11758660/63104557-e382c880-bf87-11e9-9423-cb92908b97c5.png">

## 💻 Code Sample

https://github.com/Drapegnik/parcel2-cache-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |`2.0.0-alpha.1.1`
| Node             | `v10.14.1`
| Yarn         | `1.17.3`
| Operating System | `macOS`

**Comment by DeMoorJasper** [comment] 2019-08-15 15:27
Might be related to https://github.com/parcel-bundler/parcel/pull/3405 ?

**Comment by mischnic** [comment] 2019-08-15 18:28
Might be a duplicate of https://github.com/parcel-bundler/parcel/issues/3393

**Comment by Drapegnik** [comment] 2019-08-15 20:05
@mischnic, yep, `js` bundle changes, filename - no:

<img width="1176" alt="Screen Shot 2019-08-15 at 22 59 27" src="https://user-images.githubusercontent.com/11758660/63122961-9d8e2a80-bfb0-11e9-97db-450576b64b79.png">

**Comment by DeMoorJasper** [comment] 2019-08-16 07:39
Gonna close this as it's a duplicate

**Closed by DeMoorJasper** 2019-08-16 07:39 UTC
Labels: :bug: Bug, ✨ Parcel 2
