### ISSUE TITLE
Failed to resolve module that uses `exports` entry point

### ISSUE THREAD

**Issue by AndrewKvalheim** [parcel-bundler/parcel#8745] opened 2023-01-04 03:34 UTC
# 🐛 bug report

Parcel is unable to resolve a particular module that recently [changed](https://github.com/hybridsjs/hybrids/commit/4b7d1b0c039fa310e1c4ceeaecbd97047fcadf06#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) how it defines its entry point. I suspect this is an issue with Parcel since Node.js has no problem with the change.

## 🎛 Configuration

Example setup:

```console
$ yarn add --dev parcel@2.8.2
$ echo 'import { define } from "hybrids"; console.log("OK");' > index.mjs
```

## 🤔 Expected Behavior

With Hybrids 8.1.9, both Node.js and Parcel successfully resolve the module:

```console
$ yarn add hybrids@8.1.9
$ node index.mjs
OK
$ parcel build index.mjs
✨ Built in 726ms

dist/index.js    53 B    58ms
```

## 😯 Current Behavior

With Hybrids 8.1.10, Node.js successfully resolves the module but Parcel fails:

```console
$ yarn add hybrids@8.1.10
$ node index.mjs
OK
$ parcel build index.mjs
🚨 Build failed.

@parcel/core: Failed to resolve 'hybrids' from './index.mjs'

  /home/user/example/index.mjs:1:24
  > 1 | import { define } from "hybrids"; console.log("OK");
  >   |                        ^^^^^^^^^
    2 | 

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 |
| Node             | 18.12.1 |
| Yarn         | 1.22.19 | 
| Operating System | NixOS 22.11 |

**Comment by devongovett** [comment] 2023-01-04 03:54
Duplicate of #4155.

**Closed as completed by devongovett** 2023-01-04 03:54 UTC
