### ISSUE TITLE
jest not working with parcel generated output, caused "parcelRequire is not defined" error

### ISSUE THREAD

**Issue by ca-pli** [parcel-bundler/parcel#2896] opened 2019-04-06 12:51 UTC
# 🐛 bug report

Module A depends on module B, which is processed by parcel, when running **jest** for module A, **jest** throws following error:

```
 FAIL  test/module-a.test.js
  - Test suite failed to run

    ReferenceError: parcelRequire is not defined

      110 | 
      111 |   // Override the current require with this new one
    > 112 |   parcelRequire = newRequire;
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// babel.config.js, same for both module A and module B
module.exports = {
  env: {
    test: {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              node: 'current',
            },
          },
        ],
      ],
    },
  },
}
```

## 🤔 Expected Behavior

**jest** should pass

## 😯 Current Behavior

**jest** throws an error:

```
  FAIL  test/redisRemoteLock.test.js
   - Test suite failed to run

    ReferenceError: parcelRequire is not defined

      110 | 
      111 |   // Override the current require with this new one
    > 112 |   parcelRequire = newRequire;
          |                ^
      113 | 
      114 |   if (error) {
      115 |     // throw error from earlier, _after updating parcelRequire_

      at Object.<anonymous>.parcelRequire.ZxkV.Object.defineProperty.value (../remote-lock/dist/index.js:112:16)
      at Object.<anonymous> (../remote-lock/dist/index.js:8:17)
      at Object.<anonymous> (src/redisRemoteLock.js:1:1)
      at Object.<anonymous> (test/redisRemoteLock.test.js:1:1)
```

## 💁 Possible Solution

I think **jest** is running in strict mode. Refer to https://github.com/facebook/jest/issues/6522

## 💻 Code Sample

1. remote-lock/package.json (module B)

```json
{
  "name": "remote-lock",
  "version": "1.0.0",
  "main": "dist/index.js",
  "types": "index.d.ts",
  "scripts": {
    "build": "parcel build src/index.js --target node --no-minify --no-source-maps --global remoteLock",
    "test": "tsc && jest"
  }
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.0",
    "parcel-bundler": "^1.12.3",
    "typescript": "^3.4.2"
  }
}
```

2. redis-remote-lock/package.json (module A)

```json
{
  "name": "redis-remote-lock",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "scripts": {
    "build": "parcel build src/index.js --target node --no-minify --no-source-maps --global redisRemoteLock",
    "test": "tsc && jest"
  },
  "keywords": [],
  "author": "Paul Li",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.0",
    "parcel-bundler": "^1.12.3",
    "typescript": "^3.4.2"
  },
  "dependencies": {
    "remote-lock": "^1.0.0"
  }
}
```
3. redis-remote-lock/src/index.js

```js
import { makeRemoteLock } from 'remote-lock'
// . . . 
```

4. redis-remote-lock/test/index.test.js

```js
import { makeRedisRemoteLock } from '../src/index'

test('adds 1 + 2 to equal 3', () => {
  makeRedisRemoteLock()
  // . . .
})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v8.11.2
| npm        | 6.4.1
| jest | 24.7.1
| Operating System | macOS Majove 10.14.4 (18E226)

**Comment by mischnic** [comment] 2019-04-06 12:53
> I think jest is running in strict mode. 

Correct, duplicate of #2213

**Closed by mischnic** 2019-04-06 12:53 UTC

**Comment by conlanpatrek** [comment] 2020-07-20 19:23
@mischnic looks like this might still be an issue, and related issues have been closed without fix because they're being associated with a similar bug that pops up when a script tag with 'type="module"' is used to load a parcel bundle.

There is a PR that looks like it addresses the underlying issue (#2809) but was also closed.

My gut says that there was a blanket decision at some point to not support type="module" script tags, or maybe strict mode in general. Or maybe to kick support to the next major version. But I don't believe it was intended to lose these other use cases in the shuffle. Is there any chance we can revisit this?

Maybe reopen this issue or 2809? I know it's outdated, but I'm willing to update that patch or write a new one to resolve this.

As a workaround I have this little bundle post-processing script in play. I'd like to not use this for obvious reasons, but I'll paste here in case it's helpful for anyone else who ends up on this issue:
```
#!/usr/bin/env node
const fs = require('fs')

// Path to bundle
const BUNDLE_PATH = '/some/path/to/bundle.js'

// Read bundle
const bundle = fs.readFileSync(BUNDLE_PATH, 'utf-8')

// Replace global assign with an isomorphic version
const processed = bundle.replace(
  /^parcelRequire(\s*)=/m,
  '(typeof window === \'undefined\' ? global : window).parcelRequire$1='
)

// Write bundle
fs.writeFileSync(BUNDLE_PATH, processed)
```
