### ISSUE TITLE
🐛 Should be able to use dynamic href in anchor tag and dynamic Src in iFrame

### ISSUE THREAD

**Issue by samithaf** [parcel-bundler/parcel#371] opened 2017-12-21 23:05 UTC
**Choose one:** is this a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015"],
  "env": {
    "test": {
      "plugins": [
        ["istanbul", {
          "exclude": [
            "spec.bundle.js",
            "src/**/*.spec.js"
          ]
        }]
      ]
    }
  }
}
```

### 🤔 Expected Behavior

Should not throw an error when <image> tag src or <a> tag is dynamic

E.g 
`<iframe src="{{$ctrl.iframeUrl}}" id="{{$ctrl.iframeId}}" ></iframe>`

### 😯 Current Behavior

Throwing a run time error

### 💁 Possible Solution

This is a blocker for me to tryout parcel in my current app :(

### 🔦 Context

N/A

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.1
| Node             | 8.9.3
| npm/Yarn         | Yarn
| Operating System | Mac OSx

**Comment by brandon93s** [comment] 2017-12-22 01:38
Do you mind providing more details about your application? Looks like perhaps an Angular app?

**Comment by samithaf** [comment] 2017-12-22 09:29
Hi. Should have mentioned that. It is a Angular 1.5 application. I am keen to do a benchmark with webpack since it is fairly big app with more than 100k LOC. But stuck with this issue and unable to load sass from node modules. Cheers.

**Comment by devongovett** [comment] 2017-12-31 04:27
What is the error you are getting?

**Comment by samithaf** [comment] 2018-01-07 21:37
@devongovett sorry for the late response since I was on for vacation. This is the error I am getting when the href is dynamic.

```
<PATH TO FILE>: Cannot resolve dependency './{{document.path}}'
    at /<PROJECT PATH>/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
```

**Comment by edmorley** [comment] 2018-05-10 18:00
#1153 is a dupe of this, though there is a bit more information there, so perhaps worth forward-duping?

**Comment by samithaf** [comment] 2018-05-10 21:55
Yes. It's a duplicate. Please do fwd dup.

**Closed** 2018-05-19 08:47 UTC
Labels: :clock1: Waiting
