### ISSUE TITLE
Error: mod[method] is not a function when using bundle-inlining feature

### ISSUE THREAD

**Issue by solstice23** [parcel-bundler/parcel#7687] opened 2022-02-10 12:16 UTC
# 🐛 bug report

I'm using the bundle-inlining (copied the original code from [docs](https://parceljs.org/features/bundle-inlining/)) in my project, and when I tried to build it, it threw the error `Error: mod[method] is not a function`.

I created another simplest project to test, and the problem occurred again. You can see it in the following code sample section.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "parcel": "^2.3.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
The simplest project, use `npm init` and set all parameters to default.

## 🤔 Expected Behavior

Successfully built.

## 😯 Current Behavior

`Error: mod[method] is not a function`.

## 🔦 Context

I want to inline CSS and images in js and build a single js file.

## 💻 Code Sample

I created the test project following these steps: 

```
mkdir test
npm init
# press enter constantly until the configuration was complete
npm install --save-dev parcel
```

And create `src/index.js`, this is the content (copied from the document):
```js
import cssText from 'bundle-text:./test.css';

// inject <style> tag
let style = document.createElement('style');
style.textContent = cssText;
shadowRoot.appendChild(style);
```

Then create `src/test.css` and run `npx parcel build src/index.js`, the error occurred.

![image](https://user-images.githubusercontent.com/23134847/153404711-6088ecad-6211-4827-9327-53057f55ec23.png)

I also tried `data-url:`, `fs.readFileSync`, none of them worked.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.0 |
| Node             | 14.11.0 |
| npm/Yarn         |  6.14.8 |
| Operating System | Windows 11

**Comment by W4R37** [comment] 2022-02-10 13:39
Hi, 
try to use this command. 
npm i @parcel/transformer-sass -D

**Comment by solstice23** [comment] 2022-02-10 13:53
I use pure css rather than sass, and neither css nor sass didn't work when I import them like this:
```js
import cssText from 'bundle-text:./style.css';
```

**Comment by devongovett** [comment] 2022-02-10 15:16
Duplicate of #7681

**Closed as completed by devongovett** 2022-02-10 15:16 UTC
