### ISSUE TITLE
🐛 AppVeyor test HTML: should support bundling HTML fails

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#219] opened 2017-12-11 20:10 UTC
🐛 bug report
On AppVeyor i can see this test is lately failing a lot.
```shell
1) html should support bundling HTML:
      AssertionError [ERR_ASSERTION]: 3 == 2
      + expected - actual
      -3
      +2
      
      at assertBundleTree (test\utils.js:117:12)
      at Context.<anonymous> (test\html.js:9:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command exited with code 1
```

### 🎛 Configuration (.babelrc, package.json, cli command)
AppVeyor config of this Repo

### 🤔 Expected Behavior
Should pass

### 😯 Current Behavior
Doesn't pass

**Comment by pomle** [comment] 2017-12-15 10:01
Hello @DeMoorJasper!
Why was this closed? 

I have this problem and seems to be an indeterministic test. 

Here's some output from ~10 runs of `while true; do yarn test -- --grep 'should support bundling HTML'; done`

About half fail.

https://gist.github.com/pomle/283c6f16d0b4e4e5e4947ad58fce1abb#file-parcel-indeterministic-html-test-txt


Also seen problems with `watcher should only re-package bundles that changed` which looks like a drifting timestamp issue.

```
1) watcher should only re-package bundles that changed:

      AssertionError [ERR_ASSERTION]: [ 1513331454, 1513331454 ] deepEqual [ 1513331454, 1513331455 ]
      + expected - actual

       [
         1513331454
      -  1513331454
      +  1513331455
       ]

      at Context.<anonymous> (test/watcher.js:122:12)
      at <anonymous>
```

**Comment by DeMoorJasper** [comment] 2017-12-15 13:08
This was a mistake indeed, (didn’t accure the day i closed it)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pomle** [comment] 2017-12-15 14:54
I've looked into this but need more information.

In https://github.com/parcel-bundler/parcel/commit/fc8ce69e3735550018c0b915df69ff17092da31c#diff-08e28e98a118d512b13f4fc7423da77aR668 the HTML test is introduced, and the integration fixtures looks looks like
```
html
├── index.css
├── index.html
├── index.js
└── other.html
```

Both `index.html` and `other.html` points to both `index.css` and `index.js`, but the comparison fixture for the bundler looks like
```
{
  name: 'index.html',
  assets: ['index.html'],
  childBundles: [
    {
      type: 'css',
      assets: ['index.css'],
      childBundles: []
    },
    {
      type: 'html',
      assets: ['other.html'],
      childBundles: [
        {
          type: 'js',
          assets: ['index.js'],
          childBundles: []
        }
      ]
    }
  ]
}
```
Describing a tree where `index.html` has children `index.css`, `other.html`, and `other.html` has `index.js` as only child. 

This may be correct behavior. However, given this integration fixture structure, the `let b = await bundle(__dirname + '/integration/html/index.html')` call will create indeterministic bundler trees according to my experimentation. 

I have found the following discrepant behaviors to occur frequently (>50% of test runs).

`index.html` having three children.
```
1) html should support bundling HTML:

      AssertionError [ERR_ASSERTION]: 3 == 2
      + expected - actual

      -3
      +2

      at assertBundleTree (test/utils.js:117:12)
      at Context.<anonymous> (test/html.js:9:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

`index.html` having one child.
  html
```
    1) should support bundling HTML


  0 passing (3s)
  1 failing

  1) html should support bundling HTML:

      AssertionError [ERR_ASSERTION]: 1 == 2
      + expected - actual

      -1
      +2

      at assertBundleTree (test/utils.js:119:12)
      at Context.<anonymous> (test/html.js:9:5)
      at <anonymous>
```

js bundle being of `css` type.
```
  html
bundle.name /mnt/c/Users/pom/Development/pom/parcel/test/dist/index.html tree.name index.html
bundle.name /mnt/c/Users/pom/Development/pom/parcel/test/dist/3dd25c636124a624507fecf2d5196e35.js tree.name undefined
    1) should support bundling HTML


  0 passing (3s)
  1 failing

  1) html should support bundling HTML:

      AssertionError [ERR_ASSERTION]: 'js' == 'css'
      + expected - actual

      -js
      +css

      at assertBundleTree (test/utils.js:99:12)
      at tree.childBundles.forEach (test/utils.js:120:41)
      at Array.forEach (<anonymous>)
      at assertBundleTree (test/utils.js:120:23)
      at Context.<anonymous> (test/html.js:9:5)
      at <anonymous>
```

Without me knowing too much about the internals I can't draw any conclusions now.

I believe @devongovett is the original author of this test so should be able to shine some light on it.

**Comment by brandon93s** [comment] 2017-12-16 17:47
I've identified this issue. We'll need to decide:
- Is this actually an issue, or are we OK with nondeterministic? (improve test)
- If we fix it, there is several ways we can do so. Let's discuss options. (improve code)

**Explanation:**

The following block of code is nondeterministic, and is causing the test failures:

https://github.com/parcel-bundler/parcel/blob/c008bb0ac492dbac38e2f13017e3143f40359934/src/Bundler.js#L326-L340

The above code spins up a set of promises, each of which alters the same `Map`(s) as they complete. Since these are promises, they _can_ complete in any order, and therefore interact with the `Map(s)` in any order. The most problematic of these being `asset.dependencies.set(dep.name, dep);`.

When the test passes, `asset.dependencies` contains `./index.css`, `./other.html`, `./index.js` in that order. When the test fails, `asset.dependencies` contains `./index.css`,  `./index.js`, `./other.html` in that order.

Since a `Map` iterates in _insertion order_, when the dependencies are later iterated through to generate the bundle tree, inconsistent ordering results in different trees.

https://github.com/parcel-bundler/parcel/blob/c008bb0ac492dbac38e2f13017e3143f40359934/src/Bundler.js#L393-L396

**Comment by brandon93s** [comment] 2017-12-16 17:53
**Reproduction Steps:**

You can impose an artificial delay in order to consistently reproduce this locally: 

```js
dependencies.map(async dep => { 
   if (~dep.name.indexOf('other')) await new Promise(r => setTimeout(r, 500)); // add
   let assetDep = await this.resolveDep(asset, dep); 
```

This should result in the test in question failing consistently.

**Comment by devongovett** [comment] 2017-12-19 09:06
Should be fixed by https://github.com/parcel-bundler/parcel/commit/539ade1820c3e644586e3161f6b2357a68784142

**Closed by devongovett** 2017-12-19 09:06 UTC
Labels: #Bug, Confirmed Bug
