### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by proto1994** [parcel-bundler/parcel#73] opened 2017-12-07 03:46 UTC
**First, this is a great tool.**
when I use it,  built show was correct, but console prompts **Uncaught ReferenceError: require is not defined** ,

node: 6.10
npm: 5.5.1

**Comment by devongovett** [comment] 2017-12-07 06:20
Can you provide more info so we can reproduce your issue? Thanks!

**Comment by sanketsahusoft** [comment] 2017-12-07 07:15
![image](https://user-images.githubusercontent.com/1733433/33703081-803d0c02-db4c-11e7-8282-ac4d547efed5.png)

Same here!

**Comment by jakoblind** [comment] 2017-12-07 07:39
I had the same issue. I solved it by running node 8. @devongovett is node 8 a requirement for running parcel? If it is, then it should be stated somewhere in the docs.

**Comment by proto1994** [comment] 2017-12-07 08:07
@jakoblind well. As you said, I upgraded node and solved it.Thanks.
node: 9.2.0
npm: 5.5.1

**Comment by thejameskyle** [comment] 2017-12-07 09:51
This is a duplicate of #40, please search through issues before creating new ones

**Closed by thejameskyle** 2017-12-07 09:51 UTC
