### ISSUE TITLE
@parcel/transformer-js: Non-static access of an `import` or `require`. This causes tree shaking to be disabled for the resolved module

### ISSUE THREAD

**Issue by SukkaW** [parcel-bundler/parcel#7165] opened 2021-10-23 07:44 UTC
# 🐛 bug report

A normally tree-shakable static import being treated as non-static,

## 🎛 Configuration (.babelrc, package.json, cli command)

- Default configuration (not a single `.*rc` file).

## 🤔 Expected Behavior

Tree shaking should be enabled.

## 😯 Current Behavior

The entire preact package is being bundled, including tree-shakable parts.

## 🔦 Context

Not applied.

## 💻 Code Sample

Here is minimal production of the issue.

```jsx
// app.jsx
import { render } from 'preact';
import { useState, useCallback } from 'preact/hooks';

function Counter() {
  const [value, setValue] = useState(0);
  const increment = useCallback(() => {
    setValue(value + 1);
  }, [value]);

  return (
    <div>
      Counter: {value}
      <button onClick={increment}>Increment</button>
    </div>
  );
}

render(<Counter />, document.body);
```

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My First Parcel App</title>
    <script type="module" src="app.jsx"></script>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

Log output:

```
  /private/tmp/parcel-demo/app.jsx:1:1
  > 1 | import { render } from "preact";
  >   | ^
    2 |
    3 | function Counter() {

....

@parcel/transformer-js: Non-static access of an `import` or `require`. This causes tree shaking to be disabled for the resolved module.

  /private/tmp/parcel-demo/app.jsx:17:1
    16 |
  > 17 | render(<Counter />, document.body);
  >    | ^^^^^^
    18 |
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.1.0
| npm/Yarn         | npm 7.23.0
| Operating System | macOS 12.0.1 RC1

**Comment by mischnic** [comment] 2021-10-23 08:03
Only the warning is wrong, it should be tree shaken correctly.

Duplicate of https://github.com/parcel-bundler/parcel/issues/7109

**Closed as completed by mischnic** 2021-10-23 08:03 UTC

**Comment by SukkaW** [comment] 2021-10-23 08:09
@mischnic Good to know, thanks!

**Comment by josheppinette** [comment] 2022-05-21 19:23
How can you work around this issue? Why does this pattern break tree shaking?
