### ISSUE TITLE
🐛 Incorrect module resolution when one import name matches along the parent path (only on `build`)

### ISSUE THREAD

**Issue by jsiebern** [parcel-bundler/parcel#793] opened 2018-02-12 14:18 UTC
### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "parcel build src/index.js"
  }
}
```

```js

{
    "presets": [
        [
            "env",
            {
                "modules": false
            }
        ]
    ]
}
```

I have a directory structure of imports like so:
```
index.js
sub/test/index.js
sub/test/tabs.js
sub/test.landscape/index.js
sub/test.landscape/tabs.js
```

The top `index.js` imports both lower `index.js` and each of them have the content:
```js
export { default } from './tabs';
```

### 🤔 Expected Behavior

In the outputted file I expect the ids for `"./sub/test"` and `"./sub/test.landscape"` to be different, wich they even are when *not* using the `build` command.

For example:
```js
{"./sub/test":3,"./sub/test.landscape":4}
```

### 😯 Current Behavior

Using the build command it outputs:
```js
{"./sub/test":2,"./sub/test.landscape":2}
```

So the same id, that causes my code to break in production where in development it runs fine.

### 💁 Possible Solution

I only had a brief glance at the code debugging this, it might have something todo with the common ancestor search? Totally not sure on that one, sorry.

### 🔦 Context

As this is only a "beautification" for filenames (putting the main file of the subfolder as `tabs.tsx` for example instead of `index.tsx`, its not a big deal to work around. I still believe it to be a bug though.

### 💻 Code Sample

I have attached some example code, just run `yarn; yarn build` and check the `dist/index.js` for the faulty result.

[error_example.zip](https://github.com/parcel-bundler/parcel/files/1716549/error_example.zip)

**Comment by jeyj0** [comment] 2018-08-24 20:26
Hi, I was just looking into this, and tried to reproduce it using your given example. 
* Using the Version in the example I can indeed verify that there is the described, buggy behavior. 
* However, using the newest version of parcel-bundler (1.9.7) I got: `{"./sub/test":"C2SW","./sub/test.landscape":"BZFw"}` which seems to be correct as far as I understand the issue.

I would therefore suggest closing this issue as being resolved. :smile:

**Closed** 2018-08-24 20:28 UTC
Labels: :bug: Bug
