### ISSUE TITLE
 Unterminated regular expression (sourceMap) in V1.12.3

### ISSUE THREAD

**Issue by nevf** [parcel-bundler/parcel#2950] opened 2019-04-24 01:39 UTC
# 🐛 bug report

Parcel fails and app won't run with code shown below.

## 🎛 Configuration (.babelrc, package.json, cli command)

Not using babel.

## 💻 Code Sample
````
function updateLink(linkElement, obj) {
    var css = obj.css, sourceMap = obj.sourceMap;
    sourceMap && (css += "/*# sourceMappingURL=data:application/json;base64," + " */");
}
````
## 🤔 Expected Behavior
The above code should be fine. 

## 😯 Current Behavior
````
consola.js:388 [11:24:59][ERROR] [parcel] ??  c:\webapps\play2\clibu_tree\js\tree_app.js:92:33: Unterminated regular expression (92:33)
  90 | function updateLink(linkElement, obj) {
  91 |     var css = obj.css, sourceMap = obj.sourceMap;
> 92 |     sourceMap && (css += " + " */");
     |                                 ^
  93 | }
  94 | 
````

## 💁 Possible Solution

It is caused by a `/*# sourceMappingURL` and also be having `sourceMap && ..` as part of the same statement. Changing the code to `if ( sourceMap ) ...` resolves the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | V1.12.3
| Node             |v10.15.0
| npm/Yarn         |v6.4.1
| Operating System |Win10

This wasn't happening with an older version of Parcel v.111.0

I have looked at: https://github.com/parcel-bundler/parcel/issues/2795 and there may be some relation to that issue.

**Comment by mischnic** [comment] 2019-05-04 15:06
The issue you linked was closed because it's a duplicate of https://github.com/parcel-bundler/parcel/issues/2408 (as is this). There is a PR open but it's not merged yet.

**Closed by mischnic** 2019-05-04 15:06 UTC
Labels: :bug: Bug
