### ISSUE TITLE
Parcel dedupes different files which look similar

### ISSUE THREAD

**Issue by subhero24** [parcel-bundler/parcel#3872] opened 2019-12-04 12:31 UTC
# 🐛 bug report

Building files for production dedupes similar files which should not be deduped.

File: one.js
```js
module.exports = {}
```

File: two.js
```js
module.exports = {}
```

File: index.js
```js
let one = require("./one");
let two = require("./two");

console.log(one === two);
```

Running this file logs `false`, as the objects are not the same object.
Building and running this with `parcel build index.js` and running it logs `true`. 🤔

**Comment by mischnic** [comment] 2019-12-04 20:11
This is a known bug, duplicate of https://github.com/parcel-bundler/parcel/issues/3523.

**Closed by mischnic** 2019-12-04 20:11 UTC
Labels: :bug: Bug
