### ISSUE TITLE
Parcel watch with yarn link not working

### ISSUE THREAD

**Issue by joamag** [parcel-bundler/parcel#8646] opened 2022-11-19 22:56 UTC
# 🐛 bug report

I'm trying to use the dev server with hot reloading (watch) making use of a package that is linked using `yarn link`. But I'm not able to have the server detect the changes in the linked folder. It seems like the linked directory (in Unix it's typically a symbolic link) is not working with the parcel's file-watching mechanism.

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command:

```bash
yarn parcel watch index.html
```

## 🤔 Expected Behavior

Parcel detects file changes in the linked package directory files and runs a new build operation.

## 😯 Current Behavior

Parcel does not detect the changes and no hot re-building happens.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0
| Node             | 16.13.1
| npm/Yarn         | Yarn 1.22.17
| Operating System | Windows 10

**Comment by mischnic** [comment] 2022-11-20 09:34
Duplicate of https://github.com/parcel-bundler/parcel/issues/4332

**Closed as not planned by mischnic** 2022-11-20 09:34 UTC
