### ISSUE TITLE
Parcel 2 Simple React project doesn't work. Build and start failure

### ISSUE THREAD

**Issue by AntonOnyshch** [parcel-bundler/parcel#6169] opened 2021-04-22 19:02 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**
```
{
  "name": "my-project",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "parcel": "next"
  }
}
```
**index.tsx**
```js

import React from "react";
import { render } from "react-dom";

render(<h1>Hello World</h1>, document.getElementById("root"));
```

**index.html**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My Parcel Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./index.tsx"></script>
  </body>
</html>

```

## 😯 Current Behavior

**Bunch of errors(exactly the same as below) occurs per second in VS Code terminal and something going mad with bin.js and workers. Bunch of workers are creating during to build proccess.**

@parcel/workers: Cannot find module '"c:/Users/***/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
Error: Cannot find module '"c:/Users/***/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1260:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:456:5)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:151:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

## 💻 Code Sample

[Your own example on parceljs](https://v2.parceljs.org/getting-started/webapp/)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Next
| Node             | 16.0
| npm/Yarn         | 7.10.0
| Operating System | Windows 10

**Comment by danieltroger** [comment] 2021-04-22 19:17
I think the issue is not parcel but actually that you're using windows, it works fine on macOS.

I'd recommend installing linux or running something like ubuntu in virtualbox if you can't modify your boot drive.

```
daniel@Daniels-MacBook-Pro prcl % cat package.json src/* && npm run build
{
  "name": "my-project",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "parcel": "next"
  }
}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My Parcel Project</title>
  </head>

  <body>
    <div id="root"></div>
    <script type="module" src="./index.tsx"></script>
  </body>
</html>import React from "react";
import { render } from "react-dom";

render(<h1>Hello World</h1>, document.getElementById("root"));
> build
> parcel build ./src/index.html

✨ Built in 232ms

dist/index.90c4c29c.js                                        127.77 KB     45ms
├── node_modules/react-dom/cjs/react-dom.production.min.js    115.12 KB    932ms
├── node_modules/react/cjs/react.production.min.js              6.42 KB    914ms
├── node_modules/scheduler/cjs/scheduler.production.min.js      4.89 KB     56ms
├── node_modules/object-assign/index.js                           969 B     15ms
├── node_modules/react-dom/index.js                               273 B     33ms
├── node_modules/@parcel/scope-hoisting/lib/helpers.js             55 B      0ms
├── Code from unknown sourcefiles                                  43 B      0ms
└── src/index.tsx                                                  34 B    385ms

dist/index.html                                                   188 B     45ms
└── src/index.html                                                234 B    109ms
daniel@Daniels-MacBook-Pro prcl % 
```

**Comment by AntonOnyshch** [comment] 2021-04-22 19:25
I don't think so. It has worked for once on windows.

**Comment by mischnic** [comment] 2021-04-22 20:40
This is a duplicate of https://github.com/parcel-bundler/parcel/issues/6123.

This probably also happens on other platforms if that path from the error contains spaces

**Closed as completed by mischnic** 2021-04-22 20:40 UTC
