### ISSUE TITLE
dynamic import not work

### ISSUE THREAD

**Issue by zalelion** [parcel-bundler/parcel#4201] opened 2020-02-21 21:44 UTC
# 🐛 bug report

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/8503065/75074101-e6add100-5535-11ea-91a5-2470ec19d056.png)

#### index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script src="index.js"></script>
</body>
</html>
```
#### index.js
```js
console.log("index js file");

import("./lib/lib.js").then(()=>{})

function loadModule(path) {
    setTimeout(() => {
    import("./"+path+"/lib.js").then(()=>{});
    }, 200);
}

loadModule("lib");
```

#### lib/lib.js
```js
console.log("2323322332")
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  next
| Node             |  v12.13.1
| npm/Yarn         | yarn
| Operating System | mac

**Comment by DeMoorJasper** [comment] 2020-02-22 09:35
Not entirely sure how you expect this to work?

We need to be able to statically extract which modules to create otherwise we can never create bundles reliably on build. Maybe a regex of bundles to create and we inject an index mapping to the hashes in the js bundles?

This seems more of an RFC thing than an actual bug

**Comment by mischnic** [comment] 2020-02-22 12:02
Duplicate of https://github.com/parcel-bundler/parcel/issues/125

**Closed by mischnic** 2020-02-22 12:02 UTC
Labels: :raising_hand_woman: Feature, ✨ Parcel 2
