### ISSUE TITLE
Third party modules don't get transpiled by preset-env

### ISSUE THREAD

**Issue by fgnass** [parcel-bundler/parcel#3271] opened 2019-07-26 13:49 UTC
# 🐛 bug report

The parcel documentation states that dependencies in `node_modules` get transpiled using `preset-env` but this does not seem to be the case.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here is a minimal repository to reproduce the issue:
https://github.com/fgnass/parcel-issue

## 🤔 Expected Behavior

Parcel should run files imported from `node_modules` through babel with `preset-env`, leaving no ES6 code behind.

## 😯 Current Behavior

The spread operator in `/index.js` gets transpiled, the one in `node_modules/third-party-test/index.js` is left untouched.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11.1.0
| npm              | 6.4.1
| Operating System | MacOS

**Comment by mischnic** [comment] 2019-07-26 15:38
> The parcel documentation states that dependencies in node_modules get transpiled using preset-env

Where? Wasn't able to find that in https://parceljs.org/javascript.html.
This was initially done because running babel over node_modules would be quite slow.

Actually a duplicate of #1655

**Closed by mischnic** 2019-07-26 15:38 UTC
