### ISSUE TITLE
Improve error message when typescript is missing

### ISSUE THREAD

**Issue by steebchen** [parcel-bundler/parcel#977] opened 2018-03-10 12:47 UTC
When referencing a .ts file and running parcel like this:
`parcel index.html`
results in this confusing error:
```
Server running at http://localhost:1234 
🚨  /tmp/parc/index.ts: spawn ENOTDIR
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at spawn (/home/luca/.npm-global/lib/node_modules/parcel-bundler/node_modules/cross-spawn/index.js:12:24)
    at Promise (/home/luca/.npm-global/lib/node_modules/parcel-bundler/src/utils/installPackage.js:19:17)
    at Promise (<anonymous>)
    at install (/home/luca/.npm-global/lib/node_modules/parcel-bundler/src/utils/installPackage.js:10:10)
    at **<anonymous>**
```

It can be solved by simply installing typescript locally:
`npm i typescript -D`

The error message should be something like "Typescript should be installed l locally" or "Typescript binary is missing".

**Comment by davidnagli** [comment] 2018-03-12 19:30
Actually Parcel has a feature that automatically installs dependencies for you. So it actually _should_ install TypeScript for you 100% automatically.

See: #306(merged) and #805(work in progress)

If you look at the error message, notice how at the bottom the error comes from the `install()` method. Which means that Parcel is actually detecting that you don’t have it installed, and automatically installing if for you, but just it’s failing during that install. The issue is not that parcel is not installing it, it’s that it’s running into some problems while installing typescript.

So looks like this is a problem with error handling in autoinstall.
 
---

I tried to reproduce this on my Mac (MacOS High Siera), and I wasn’t able to get the same error. Can you please try to download and run `parcel src/index.html` on [this example I made](https://github.com/davidnagli/parcel-issue-repro/tree/master/977) to see if you get the same error?

Also, can you please fill out the system information table from the issue template.

 Here’s my info:

Software | Version(s)
-- | --
Parcel | 1.6.2
Node | v8.10.0
npm/Yarn | yarn:1.3.2 npm:5.6.0
Operating System | MacOS High Sierra

**Comment by steebchen** [comment] 2018-03-12 20:01
I see. I cloned the example and it works there, even when I remove typescript in the package.json.
Regardless of what I do, I now can't seem to reproduce this issue either in my first repo... I guess you can close the issue for now until someone experiences this too.
parcel: 1.6.2
node: v8.3.0
yarn: 1.5.1
npm: 5.5.1
os: Linux Mint 18.1 Serena

**Comment by DeMoorJasper** [comment] 2018-03-12 20:20
It would be nice to have an obvious error message as the install can still fail.
However this error appears to be a failed spawn for the install script

**Comment by toby3d** [comment] 2018-03-22 11:12
I have this files structure:
```
/dist/va.js        
/examples/grid.html
/src/va.sass                 
```

This is a `/examples/grid.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Examples Grid</title>
    <script src="../dist/va.js"/>
  </head>
  <body>
    ...
  </body>
</html>
```

This is a `/dist/va.js`
```js
require('./../src/va.sass');

module.exports = function () {
  return 2;
};
```

What I get after run `parcel examples/grid.html`:
```bash
$ parcel examples/grid.html 
Server running at http://localhost:1234 
🚨  /home/toby3d/git/va/src/va.sass:undefined:undefined: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at spawn (/home/toby3d/.npm-global/lib/node_modules/parcel-bundler/node_modules/cross-spawn/index.js:12:24)
    at Promise (/home/toby3d/.npm-global/lib/node_modules/parcel-bundler/src/utils/installPackage.js:19:17)
    at new Promise (<anonymous>)
    at install (/home/toby3d/.npm-global/lib/node_modules/parcel-bundler/src/utils/installPackage.js:10:10)
    at <anonymous>
```

Installing `coffeescript` module is not solve this problem.

**Closed** 2018-04-15 17:53 UTC
Labels: :bug: Bug
