### ISSUE TITLE
Elm doesn't seem to be working in 2.x

### ISSUE THREAD

**Issue by smucode** [parcel-bundler/parcel#4620] opened 2020-05-17 22:45 UTC
# 🐛 bug report

Have an elm/ts project that is running ok on 1.x. Some issues with the hot reloading not working after a while, so wanted to try 2.x.

Had a lot of issues with `Error: Name already registered with serializer` initially. Had to delete node_modules and package-lock.json to get that resolved. 

Now i'm getting a strange error: Cannot find `../elm/Main` did you mean `../elm/Main`?

```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/core: Failed to resolve '../elm/Main' from './src/ts/index.ts'
/src/ts/index.ts:1:21
> 1 | import { Elm } from "../elm/Main";
>   |                     ^^^^^^^^^^^^^
  2 | import * as firebase from "firebase/app";
  3 | import "firebase/auth";
@parcel/resolver-default: Cannot load file '../elm/Main' in './src/ts'.
Did you mean ../elm/Main?
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel index.html
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.16.2
| npm/Yarn         | npm 6.14.4
| Operating System | macOS 10.15.4

**Comment by mischnic** [comment] 2020-05-17 23:02
Elm isn't supported yet, there is however a work-in-progress PR: https://github.com/parcel-bundler/parcel/pull/4395

Closing as duplicate of https://github.com/parcel-bundler/parcel/issues/3351

**Closed by mischnic** 2020-05-17 23:02 UTC
