### ISSUE TITLE
🙋 HTML parsing too strict?

### ISSUE THREAD

**Issue by ubershmekel** [parcel-bundler/parcel#439] opened 2017-12-30 09:09 UTC
🙋 Feature Request

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "just using the default out of the box..." }
}
```

### 🤔 Expected Behavior
This is the html source and what I was expecting to be output.

```
    <div id="visual">
        <div id="jet-icon" />
        <div id="runway-icon" />
    </div>
```

### 😯 Current Behavior
This is the output which is nested differently by the browser.

```
<div id="visual">
    <div id="jet-icon">
        <div id="runway-icon">
    </div>
```

**Comment by DeMoorJasper** [comment] 2017-12-30 09:14
This actually is invalid html, i'll label it as a feature not a bug

**Comment by shawwn** [comment] 2017-12-30 09:34
In situations like this, it's best to use `curl` rather than looking at the browser's DOM:

```
$ curl localhost:1234
    <div id="visual">
        <div id="jet-icon" />
        <div id="runway-icon" />
    </div>
```

So, parcel doesn't actually transform the HTML at all – it just passes the HTML straight to the browser.

I experimented with setting different doctypes (html4, xhtml1.0, xhtml1.1) but it seemed to make no difference: chrome simply doesn't support self-closing div tags.

It's tempting to say that parcel should just fix the problem (by turning <div /> into <div></div> automatically), but that's probably a bad idea. There are cases where a user wants to generate invalid HTML, e.g. unit testing.

Vue.js deals with similar issues. If you try to write <table><my-component></table>, the browser automatically inserts <table><tbody><my-component></tbody></table>, which screws up Vue's virtual rendering.

We should probably follow Vue's lead and simply leave the HTML untouched.

**Comment by shawwn** [comment] 2017-12-30 09:37
In situations like this, it's best to use `curl` rather than looking at the browser's DOM:

```
$ curl localhost:1234
    <div id="visual">
        <div id="jet-icon" />
        <div id="runway-icon" />
    </div>
```

So, parcel doesn't actually transform the HTML at all – it just passes the HTML straight to the browser.

I experimented with setting different doctypes (html4, xhtml1.0, xhtml1.1) but it seemed to make no difference: chrome simply doesn't support self-closing div tags.

It's tempting to say that parcel should just fix the problem (by turning `<div />` into `<div></div>` automatically), but that's probably a bad idea. There are cases where a user wants to generate invalid HTML, e.g. unit testing.

Vue.js deals with similar issues. If you try to write `<table><my-component></table>`, the browser automatically inserts `<table><tbody><my-component></tbody></table`>, which screws up Vue's virtual rendering.

We should probably follow Vue's lead and simply leave the HTML untouched.

*edit*: fixed formatting.

**Comment by devongovett** [comment] 2017-12-30 18:50
I don't think parcel should be responsible for fixing your invalid HTML.

**Closed by devongovett** 2017-12-30 18:50 UTC
Labels: #Feature, #Question

**Comment by ubershmekel** [comment] 2017-12-31 09:37
@shawwn - using `curl` I see that parcel removes the `/` from any `<div />` which leaves me with a `<div>` which causes the browser to build the wrong dom. @devongovett I'm not requesting you fix my invalid HTML - I just don't want you to mangle my valid xhtml.

I now noticed that parcel removes the `/`only when I include a `<link>` to a stylesheet if that's interesting. 

If you guys prefer to not support XHTML that's fine. I still don't see a reason to actively remove these slashes but if you guys need that for something else then cool. Here's the code sample I validated at w3c. It exhibits the issue until you remove the `<link>` line:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="./index.css" />
    <title>w3c requires titles</title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  </head>
  <body>
    <div id="top" />
    <div id="bottom" />
    <div />
  </body>
</html>
```

**Comment by shawwn** [comment] 2017-12-31 12:13
Parcel isn't changing your HTML at all. If you run parcel and then run
`curl http://localhost:1234`, you'll see that the HTML parcel is serving to
the browser is identical to the HTML in your source file.

(In other words, the browser is doing the stuff you've been saying. Not
parcel.)

**Comment by ubershmekel** [comment] 2017-12-31 22:06
@shawwn I'm explaining that I did `curl` and still do see parcel serving the removed slashes.

If you're not seeing removed slashes it might be because you don't have a `<link rel="stylesheet" type="text/css" href="./index.css" />` in your `<head>` which I only now discovered is required to get parcel to remove the slashes.
