### ISSUE TITLE
Invalid Version: undefined on SCSS project.

### ISSUE THREAD

**Issue by lilspelunker** [parcel-bundler/parcel#5958] opened 2021-03-03 11:10 UTC
# 🐛 bug report

Using Parcel with SCSS (after following the guide) doesn't work. I get error `Invalid Version: undefined`

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "sass": "^1.32.8"
  }
}
```

## 🤔 Expected Behavior

I should have my dev server up and running.

## 😯 Current Behavior

I get error `Invalid Version: undefined` and my server runs without the CSS

Full Error:
```
🚨  /usr/lib/node_modules/parcel-bundler/src/builtins/css-loader.js: Invalid Version: undefined
```

## 🔦 Context

I'm trying to get an empty project with nothing but an index.html and index.scss up and running. I can't get SCSS working. I tried removing node_modules, package-lock.json and package.json then running `npm init -y` and letting parcel install whatever SCSS version it wants but it didn't work.

## 💻 Code Sample

Project structure:
```
package.json
package-lock.json
node_modules
src
  index.html
  styles
    index.scss
```

index.html
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="styles/index.scss">
</head>

<body>
<p>Hi</p>
</body>
</html>
```

```scss
p {
color: red;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v14.15.5
| npm/Yarn         | npm 6.14.11
| Operating System | Linux Mint 20.1 (Cinnamon)

**Comment by mischnic** [comment] 2021-03-03 11:18
Duplicate of https://github.com/parcel-bundler/parcel/issues/5943

**Closed by mischnic** 2021-03-03 11:18 UTC
