### ISSUE TITLE
Serve index.html when using multiple entries

### ISSUE THREAD

**Issue by MathieuLoutre** [parcel-bundler/parcel#1778] opened 2018-07-23 12:01 UTC
# 🐛 Bug Report

When using Parcel with multiple entry point (such as `parcel src/*.html`), the server doesn't serve index.html even if it exists. That led to some great confusion on my part, expecting this to be the default behaviour since it works like that with a single entry point.

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel src/*.html` with two files `index.html` and `about.html` (with no link between each other)

## 🤔 Expected Behavior

Parcel should serve `index.html` if it's present, even if there are multiple entry points.

## 😯 Current Behavior

Parcel sends a 404, and you have to manually open `/index.html`.

## 💁 Possible Solution

I've replaced the `respond()` function in Server.js in my local version of Parcel with this and changed `sendIndex()` to `findIndex()`. Essentially, if the path is empty, it'll look for index.html in case the bundle is not HTML already. I could PR this if there's interest.

```js
    function respond() {
      let {pathname} = url.parse(req.url);
      if (bundler.error) {
        return send500(bundler.error);
      } else if (
        !pathname.startsWith(bundler.options.publicURL) ||
        path.extname(pathname) === ''
      ) {
        const index = findIndex(pathname)
        if (index) {
          req.url = `/${path.basename(index)}`;
          serve(req, res, send404);
        }
        else {
          send404();
        }
      } else {
        // Otherwise, serve the file from the dist folder
        req.url = pathname.slice(bundler.options.publicURL.length);
        return serve(req, res, send404);
      }
    }

    function findIndex(pathname) {
     // If the bundle is HTML, send that
      if (bundler.mainBundle.type === 'html') {
        return bundler.mainBundle.name;
      }
      else if (pathname === bundler.options.publicURL) {
        // if the pathname is empty, look for files named index.html in the bundle and send back the first one. If there's nothing, return null;
        const indexes = Array.from(bundler.mainBundle.childBundles).filter((asset) => path.basename(asset.name) === 'index.html');
        return indexes[0].name;
      }
      return null;
    }
```

## 🔦 Context

This is to build a really simple static website with independent web pages. Because it worked with one file `parcel src/index.html` I expected `parcel src/*.html` to keep serving the index and I spent 10 min moving code around thinking I was hitting an error somewhere I couldn't see only to realise Parcel was sending 404 on purpose.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 9.4.0
| Yarn         | 1.7.0
| Operating System |MacOS 10.12.6

**Comment by DeMoorJasper** [comment] 2018-07-23 16:31
It serves the html entrypoint not index.html. So in your case this is an autogenerated file.

duplicate of #1315

**Closed by DeMoorJasper** 2018-07-23 16:31 UTC

**Comment by MathieuLoutre** [comment] 2018-07-23 16:38
Hi @DeMoorJasper,

I'm not sure I understand what you mean. I appreciate this might be a duplicate issue (that I could not find, sorry about that) but what is auto generated here?

From what I understood in the code (my knowledge of the code base is limited), it seems like if there's only one entry point, a bundle is created and that asset is made the main asset instead (https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L272). The problem with multiple entry points is that since there are multiple files, the "main" asset can't be found and therefore sends a 404 (https://github.com/parcel-bundler/parcel/blob/master/src/Server.js#L70). 

The solution I'm suggesting and which is working, is for the server to look for a subbundle with an index.html if the main bundle is not already HTML. How is any of this autogenerated?

**Comment by DeMoorJasper** [comment] 2018-07-23 17:15
The main asset is a generated bundle that contains a reference to all the entrypoints. It just doesn't get saved or served, because it doesn't really exist, but that's the real entrypoint or main asset used inside parcel

**Comment by MathieuLoutre** [comment] 2018-07-23 17:20
Thanks for the explanation. I think that clarifies what I was seeing (https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L272) but I struggle to see how this relates to the above mentioned problem. Do you mean that what I'm suggesting is not possible because of that? Did you get a chance to have a look at the code I have under _Possible Solution_?

**Comment by DeMoorJasper** [comment] 2018-07-23 17:36
Ow it is definitely possible, I just closed this because it is a duplicate and wanted to explain why it happens.

**Comment by RayBB** [comment] 2022-01-17 02:07
For anyone finding this a few years later, parcel v2 doesn't seem to have this problem so upgrading should fix it.
