### ISSUE TITLE
Error: No transformers found for [...] wasm

### ISSUE THREAD

**Issue by lgarron** [parcel-bundler/parcel#6284] opened 2021-05-14 00:01 UTC
# 🐛 bug report

WASM support does not work.
https://parceljs.org/webAssembly.html

## 🎛 Configuration (.babelrc, package.json, cli command)

No config.

## 🤔 Expected Behavior

The example from https://parceljs.org/webAssembly.html works out of the box.

## 😯 Current Behavior

```
> npx parcel index.html
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: No transformers found for /Users/lgarron/Desktop/parcel-wasm-test/add.wasm.
Error: No transformers found for /Users/lgarron/Desktop/parcel-wasm-test/add.wasm.
    at ParcelConfig._getTransformerNodes (/Users/lgarron/Desktop/parcel-wasm-test/node_modules/@parcel/core/lib/ParcelConfig.js:185:13)
    at ParcelConfig.getTransformers (/Users/lgarron/Desktop/parcel-wasm-test/node_modules/@parcel/core/lib/ParcelConfig.js:198:34)
    at Transformation.loadPipeline (/Users/lgarron/Desktop/parcel-wasm-test/node_modules/@parcel/core/lib/Transformation.js:657:48)
    at Transformation.run (/Users/lgarron/Desktop/parcel-wasm-test/node_modules/@parcel/core/lib/Transformation.js:315:31)
    at async Child.handleRequest (/Users/lgarron/Desktop/parcel-wasm-test/node_modules/@parcel/workers/lib/child.js:255:9)
```

## 💁 Possible Solution

Not sure.

## 🔦 Context

Trying to check if Parcel WASM support is production-ready.

## 💻 Code Sample

See https://github.com/lgarron/parcel-issue-6284

```
<!-- index.html -->
<script src="index.ts"></script>
```

```
// index.ts
import { add } from "./add.wasm";
console.log(add(2, 3));
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-nightly.660+177f8eec` |
| Node             | `v16.0.0` |
| npm/Yarn         | `7.11.2` |
| Operating System | macOS 10.15.7 |

**Comment by danieltroger** [comment] 2021-05-14 07:09
> Trying to check if Parcel WASM support is production-ready.

They just changed the scope hoisting implementation to SWC to become faster, see https://github.com/parcel-bundler/parcel/pull/6230

And it basically ruined the production readyness. Try downgrading to `2.0.0-nightly.650+dc79abcd` which is slower but much more stable.

**Comment by mischnic** [comment] 2021-05-14 09:03
This has nothing to do with the switch to SWC.

> import { add } from "./add.wasm";

That is the proposed syntax for https://github.com/WebAssembly/esm-integration/tree/master/proposals/esm-integration.

The problem is that wasm imports are essentially equivalent to importing a JS file that has a top level await statement. And we also don't support that yet. (Parcel 1's implementation of that doesn't really work once you start importing from a module that imports wasm.)

What you can do for now is 
```js
import wasmURL from "url:./add.wasm";

const wasmModule = WebAssembly.instantiateStreaming(fetch(wasmURL)).then(obj => obj.instance.exports);

function something(){
	console.log((await wasmModule).add(1,2));
}
```

(or `fetch(new URL("./add.wasm", import.meta.url))` instead of that import.

**Comment by lgarron** [comment] 2021-05-15 06:52
Thanks!

> What you can do for now is
> 
> ```js
> import wasmURL from "url:./add.wasm";
> 
> const wasmModule = WebAssembly.instantiateStreaming(fetch(wasmURL)).then(obj => obj.instance.exports);
> 
> function something(){
> 	console.log((await wasmModule).add(1,2));
> }
> ```
> 
> (or `fetch(new URL("./add.wasm", import.meta.url))` instead of that import.

Would it be worth updating https://parceljs.org/webAssembly.html to reflect this or is the goal to support the documented syntax in the near future?

**Comment by mischnic** [comment] 2021-05-15 08:35
That page is for Parcel 1 anyway. The Parcel 2 docs https://v2.parceljs.org don't mention Webassembly at all.

It would be great to support this, but there are other priorities right now...

**Comment by DoctorNefario** [comment] 2021-05-15 09:55
> The Parcel 2 docs https://v2.parceljs.org don't mention Webassembly at all.

Directly from your link:
> Parcel supports many different languages and file types out of the box, from web technologies like HTML, CSS, and JavaScript, **to lower level languages like Rust, and anything that compiles to WebAssembly (WASM),** to assets like images, fonts, videos, and more.

That line should probably be removed until v2 supports WASM.

**Comment by mischnic** [comment] 2021-05-15 10:05
Good point: https://github.com/parcel-bundler/website/pull/861

**Comment by mischnic** [comment] 2021-10-07 17:19
Closing in favor of https://github.com/parcel-bundler/parcel/issues/1325

In the meantime, you use `new URL("...", import.meta.url)` to get a url to the wasm file to then use fetch and the usual Wasm web API

**Closed as completed by mischnic** 2021-10-07 17:19 UTC
Labels: :raising_hand_woman: Feature, WASM, ✨ Parcel 2
