### ISSUE TITLE
Getting access to the final file names in my ServiceWorkre

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#4315] opened 2020-03-11 16:59 UTC
# 🐛 bug report

It’s common practice to download a bunch (if not all) of the assets and JS files in my project in the `install` handler of the ServiceWorker to put them in the cache.

A simple ServiceWorker like this won’t work because many of the files will have been renamed by Parcel.

```js
addEventListener('install', ev => {
  ev.waitUntil(
    (async () => {
      const cache = await caches.open('assets');
      await cache.addAll(['index.html', 'image.png', 'styles.css', 'index.js']);
    })(),
  );
});
```

## 🤔 Expected Behavior

There should be _a_ way to get access to the output names of files. 

## 😯 Current Behavior

There is not.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.8.0
| npm/Yarn         | 6.12.1
| Operating System | MacOS 10.15.3 (19D76)

**Comment by mischnic** [comment] 2020-03-11 17:03
Indeed. Duplicate of https://github.com/parcel-bundler/parcel/issues/4227, https://github.com/parcel-bundler/parcel/issues/4200, https://github.com/parcel-bundler/parcel/issues/3661, https://github.com/parcel-bundler/parcel/issues/3307

**Closed by mischnic** 2020-03-11 17:03 UTC

**Comment by surma** [comment] 2020-03-11 17:11
Apologies. I tried to not create duplicates, but my searchfoo must have failed me.

**Comment by mischnic** [comment] 2020-03-11 17:11
> ServiceWorkre

theater -> theatre
worker -> workre

🙈 (I'm sorry).

**Comment by surma** [comment] 2020-03-11 17:12
Ahahaha. Sadly, it’s mostly about my MBP keyboard slowly (but surely) dying.
