### ISSUE TITLE
add demo css and js files in index.html

### ISSUE THREAD

**Issue by maxkarkowski** [parcel-bundler/parcel#7388] opened 2021-11-30 13:47 UTC
# 🙋 feature request

I want to build a js lib with some demo styling inside the index.html.

## 🤔 Expected Behavior

Want to have a way to exclude files from compiling. only for development and demo envs

## 😯 Current Behavior

every css and js i set in the index.html go through the paprcel compiler

## 💁 Possible Solution

Maybe some Ignore next statements in index.html

## 💻 Examples

```
<html>
<head>
<!-- should be in the build-->
 <script type="module" src="./index.ts"></script>
 <!-- next line only for development or demo page, not be included in build-->
 <link rel="stylesheet" type="text/css" href="./demo/merged.css" media="all" />
</head>
<body>
<h1> Here is my demo app </h1>

</body>

</html>
```

**Comment by folknor** [comment] 2021-12-04 16:11
This is probably a duplicate of https://github.com/parcel-bundler/parcel/issues/1087

**Comment by folknor** [comment] 2021-12-04 16:15
Or https://github.com/parcel-bundler/parcel/issues/1186 - frankly I can't immediately glance how #1087 and #1186 differ.

**Comment by mischnic** [comment] 2021-12-04 16:19
Indeed. 

Furthermore, I don't understand the usecase here. The whole HTML file is "the demo", so why would you only want to include the stylesheet "only in the demo"?

**Closed as completed by mischnic** 2021-12-04 16:19 UTC
