### ISSUE TITLE
Why parcel doesn't make declaration .d.ts file

### ISSUE THREAD

**Issue by rzkhosroshahi** [parcel-bundler/parcel#2321] opened 2018-11-25 20:45 UTC
# ❔ Question
I used the tsconfig.json in my project and add `"declaration": true"`, but this doesn't generate .d.ts
file. However, when I used typescript CLI for building my typescript(`tsc -p .`), this makes the declaration file.

## 🔦 Context
I just trying to make .d.ts file with the parcel.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 10.6.0
| npm/Yarn         | 6.4.1
| Operating System | mac

**Comment by DeMoorJasper** [comment] 2018-11-30 09:53
Parcels internal typescript support is not as extensive as the typescript compiler.

You could try out the typescript plugin, which includes things like typechecking,... https://github.com/fathyb/parcel-plugin-typescript

**Comment by mischnic** [comment] 2019-06-02 13:27
Duplicate of #1240

**Closed by mischnic** 2019-06-02 13:27 UTC
Labels: :grey_question:  Question
