### ISSUE TITLE
NPM package built with webpack breaking parcel build

### ISSUE THREAD

**Issue by wroughtec** [parcel-bundler/parcel#2745] opened 2019-03-08 09:11 UTC
# 🐛 bug report

This only occured after upgrading to parcel 1.12.0 (may be linked to #2738).

Using a npm library that was build with webpack (eg. https://www.npmjs.com/package/@aeaton/react-prosemirror) I suspect there may be others. Webpack adds the following lines:

```
if (sourceMap) {
  // http://stackoverflow.com/a/26603875
  css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false
      }
    ],
    "@babel/preset-typescript",
    "@babel/react"
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "@babel/plugin-transform-react-jsx",
    [
      "module-resolver",
      {
        "root": [
          "./"
        ],
        "alias": {
          ....
        }
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

Build should not crash and should handle how other bundlers compile

## 😯 Current Behavior

This causes parcel bundler (when sourcemaps are enabled) to crash with the following error:
```
index.js:524:83: Unterminated regular expression (524:83)
  522 | 	if (sourceMap) {
  523 | 		// http://stackoverflow.com/a/26603875
> 524 | 		css += "\n + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
      | 		                                                                                ^
  525 | 	}
```
As can be seen its ignored the first part of the line so the closing expression is seen as the opening.

This was not an issue in 1.11.0 and when switching off sourcemaps it also has not an issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0
| Node             | 10.15.1
| npm/Yarn         | yarn 1.13.0
| Operating System | MacOsX 10.14.3

**Comment by mischnic** [comment] 2019-03-08 10:54
Duplicate of #2408, there's already an open PR for this: #2427

**Closed by mischnic** 2019-03-08 10:54 UTC
Labels: :bug: Bug
