### ISSUE TITLE
thread '<unnamed>' panicked at 'internal error: entered unreachable code

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6273] opened 2021-05-12 20:04 UTC
# 🐛 bug report

I was trying to change the targets of my reproduction repo to a version where SWC or something gets the targets wrong and encountered this strange error:

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see the attached zip. I just zipped it without changing anything. Run `yarn run build`

## 🤔 Expected Behavior

No crash

## 😯 Current Behavior

Reproducible crash

```
daniel@Daniels-MacBook-Pro parcel-misses-targets % yarn run build
yarn run v1.22.10
warning package.json: No license field
$ parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern
⠋ Building main.ts...
thread '<unnamed>' panicked at 'internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_compat-0.16.2/src/es2020/opt_chaining.rs:511:18
🚨 Build failed.
@parcel/transformer-js: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
Error: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
    at Object.transform (/private/tmp/parcel-misses-targets/node_modules/@parcel/transformer-js/lib/JSTransformer.js:316:33)
    at async Transformation.runTransformer (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:811:5)
    at async Transformation.runPipeline (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:567:36)
    at async Transformation.runPipelines (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:416:40)
    at async Transformation.run (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/private/tmp/parcel-misses-targets/node_modules/@parcel/workers/lib/child.js:255:9)
/private/tmp/parcel-misses-targets/src/main.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
daniel@Daniels-MacBook-Pro parcel-misses-targets % yarn run build
yarn run v1.22.10
warning package.json: No license field
$ parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern
⠋ Building main.ts...
thread '<unnamed>' panicked at 'internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_compat-0.16.2/src/es2020/opt_chaining.rs:511:18
🚨 Build failed.
@parcel/transformer-js: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
Error: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
    at Object.transform (/private/tmp/parcel-misses-targets/node_modules/@parcel/transformer-js/lib/JSTransformer.js:316:33)
    at async Transformation.runTransformer (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:811:5)
    at async Transformation.runPipeline (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:567:36)
    at async Transformation.runPipelines (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:416:40)
    at async Transformation.run (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/private/tmp/parcel-misses-targets/node_modules/@parcel/workers/lib/child.js:255:9)
/private/tmp/parcel-misses-targets/src/main.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
daniel@Daniels-MacBook-Pro parcel-misses-targets % yarn run build
yarn run v1.22.10
warning package.json: No license field
$ parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern
⠋ Building main.ts...
thread '<unnamed>' panicked at 'internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_compat-0.16.2/src/es2020/opt_chaining.rs:511:18
🚨 Build failed.
@parcel/transformer-js: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
Error: internal error: entered unreachable code: TsOptChain.expr = Lit(Null(Null { span: Span { lo: BytePos(16), hi: BytePos(20), ctxt: #0 } }))
    at Object.transform (/private/tmp/parcel-misses-targets/node_modules/@parcel/transformer-js/lib/JSTransformer.js:316:33)
    at async Transformation.runTransformer (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:811:5)
    at async Transformation.runPipeline (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:567:36)
    at async Transformation.runPipelines (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:416:40)
    at async Transformation.run (/private/tmp/parcel-misses-targets/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/private/tmp/parcel-misses-targets/node_modules/@parcel/workers/lib/child.js:255:9)
/private/tmp/parcel-misses-targets/src/main.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
daniel@Daniels-MacBook-Pro parcel-misses-targets % 
```

## 💁 Possible Solution

Hard to say. Tbh the previous scope hoister was very solid 😬🙃

## 🔦 Context

Was trying to make repro repo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.660+177f8eec|
| Node             |v16.0.0|
| npm/Yarn         |yarn 1.22.10|
| Operating System |macOS 10.15.7 (19H1030)|

**Comment by danieltroger** [comment] 2021-05-12 20:10
Sorry, had trouble with github's 10MB file limit. Here is the zip split up, please remove one `.zip` from every filename
[parcel-crashes.z01.zip](https://github.com/parcel-bundler/parcel/files/6468809/parcel-crashes.z01.zip)
[parcel-crashes.z02.zip](https://github.com/parcel-bundler/parcel/files/6468812/parcel-crashes.z02.zip)
[parcel-crashes.z03.zip](https://github.com/parcel-bundler/parcel/files/6468815/parcel-crashes.z03.zip)
[parcel-crashes.z04.zip](https://github.com/parcel-bundler/parcel/files/6468816/parcel-crashes.z04.zip)
[parcel-crashes.z05.zip](https://github.com/parcel-bundler/parcel/files/6468819/parcel-crashes.z05.zip)
[parcel-crashes.z06.zip](https://github.com/parcel-bundler/parcel/files/6468820/parcel-crashes.z06.zip)
[parcel-crashes.zip.zip](https://github.com/parcel-bundler/parcel/files/6468822/parcel-crashes.zip.zip)

**Comment by danieltroger** [comment] 2021-05-12 20:13
It seems to also be reproducible after running `yarn install` again, here's a zip without node_modules: 
[parcel-crashes-on-optional-chaining.zip](https://github.com/parcel-bundler/parcel/files/6468833/parcel-crashes-on-optional-chaining.zip)

**Comment by mischnic** [comment] 2021-05-12 20:53
I'm pretty sure this is also caused by https://github.com/swc-project/swc/issues/1688.

**Comment by mischnic** [comment] 2021-05-14 09:59
This should be fixed in the next nightly

**Closed as completed by mischnic** 2021-05-14 09:59 UTC
Labels: :bug: Bug, ✨ Parcel 2, 🐡 JS Codegen
