### ISSUE TITLE
🐛dist/ directory isn't cleaned on repeated builds

### ISSUE THREAD

**Issue by mikefisher84** [parcel-bundler/parcel#1234] opened 2018-04-23 16:26 UTC
I have a very simple package that I'm using parcel to compile. When I run a build I notice that parcel generates new compiled javascript files with new hash numbers, but doesn't clean the old files. I've done extensive searching and can't seem to find a way to fix this. Is this the intended behavior? 

Here's the command I'm running:
```js
"build": "parcel build src/iframe.html"
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 8.9.4
| npm/Yarn         | yarn 1.3.2
| Operating System | Mac OS

**Comment by DeMoorJasper** [comment] 2018-04-23 16:29
This is the intended behaviour. The hashes are content hashes.
These are used for invalidating browser cache, for changed files.
One way to prevent this would be to put a remove command in front of the build command

**Comment by DeMoorJasper** [comment] 2018-04-27 14:41
Closing this, as the plugin should resolve the issue

**Closed by DeMoorJasper** 2018-04-27 14:41 UTC
Labels: :grey_question:  Question

**Comment by helpermethod** [comment] 2018-06-15 16:45
In package.json, add another script named `prebuild`:

    "prebuild": "rm -rf dist"

Only works on Linux/Unix systems but saves you a dependency.

**Comment by tjfwalker** [comment] 2018-09-13 05:36
> Only works on Linux/Unix systems but saves you a dependency.

Then
```
"prebuild": "shx rm -rf dist/*"
```
where
> [`shx`](https://github.com/shelljs/shx) is a wrapper around ShellJS Unix commands, providing an easy solution for simple Unix-like, ***cross-platform*** commands in npm package scripts

Though, then you lose the whole "saves you a dependency" thing `¯\_(ツ)_/¯`

**Comment by tjfwalker** [comment] 2018-09-13 05:43
> Only works on Linux/Unix systems

Then
```
"prebuild": "shx rm -rf dist/*"
```
where
> [`shx`](https://github.com/shelljs/shx) is a wrapper around ShellJS Unix commands, providing an easy solution for simple Unix-like, ***cross-platform*** commands in npm package scripts

Though, then you lose that "saves you a dependency" upshot `¯\_(ツ)_/¯`

**Comment by kiranvj** [comment] 2018-12-13 16:04
In windows I had to use 
`"prebuild": "rmdir dist /s /q"`

to make it work.

**Comment by RadValentin** [comment] 2019-06-08 11:51
The `parcel-plugin-clean-dist` isn't taking PRs or being actively maintained and, at least on my setup, doesn't seem to actually wipe the `/dist` directory. So I made an alternative [`parcel-plugin-nuke-dist`](https://github.com/RadValentin/parcel-plugin-nuke-dist), feel free to give it a shot 😄

**Comment by FynnZW** [comment] 2019-12-02 15:12
To prevent different behaviour on windows/linux, [rimraf](https://www.npmjs.com/package/rimraf) also works great:

`npm install rimraf --save-dev`

in package.json: 
` "prebuild": "rimraf dist",`

**Comment by yoanmalie** [comment] 2020-05-18 19:54
Hey, `"prebuild"` work also on macOS, no need to install plugin 🎉 

Tested on maOS 10.14.6.

**Comment by Grawl** [comment] 2020-06-02 10:30
this should not be solved using a plugin

this is not an optional feature

every Parcel user have a tons of unused files without this

**Comment by hayatbiralem** [comment] 2020-08-02 15:30
> In package.json, add another script named `prebuild`:
> 
> ```
> "prebuild": "rm -rf dist"
> ```
> 
> `prebuild` will run automatically before the `build` script.
> Only works on Linux/Unix systems but saves you a dependency.

I'm using Cmder (Portable console emulator for Windows) and it supports linux based syntax so it works with Cmder too. 

Thanks 👍

**Comment by vitalets** [comment] 2025-04-04 06:53
If I have custom dist dir, I need to write it twice:
```json
"scripts": {
  "dev": "rm -rf dist/dev && parcel watch index.html --dist-dir dist/dev",
  "build": "rm -rf dist/prod && parcel build index.html --dist-dir dist/prod"
}
```
It would be far more convenient if parcel automatically clean the provided dist dir.
