### ISSUE TITLE
🐛 Long error messages gets cut off

### ISSUE THREAD

**Issue by Olian04** [parcel-bundler/parcel#349] opened 2017-12-19 19:22 UTC
### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/5493406/34174408-09f336c8-e4f9-11e7-8b69-3623497fc780.png)
![image](https://user-images.githubusercontent.com/5493406/34174623-e20ea1a0-e4f9-11e7-81d3-b7053d52530e.png)

As you can see in the first image the error message reaches the end of the row and gets cut off instead of wrapping to the next line. And as you can see in the second image the error message gets cut off at a slightly different position when the terminal is smaller.

### 🤔 Expected Behavior

The entire error message should always be displayed.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.0
| Node             | 9.3.0
| Yarn         | 1.3.2
| Operating System | Ubuntu 17.04

**Comment by DeMoorJasper** [comment] 2017-12-19 19:30
Could potentially be fixed when this PR gets merged? #207 
Never had the issue so can't test unfortunately :(

**Comment by Olian04** [comment] 2017-12-19 19:55
@DeMoorJasper When trying to recreate the issue in a new repository it fixed it self.... and not just for the new repo but for the original (the one in the images) as well... i have no idea why....

**Comment by Olian04** [comment] 2017-12-19 20:29
@DeMoorJasper Well i just confirmed it. The original issue just got the bug again. And switching to a different repo and running parcel on that (this time one that doesn't fail) fixes the problem.

**Comment by DeMoorJasper** [comment] 2017-12-19 20:39
So what exactly fixes/causes the issue?

**Comment by Olian04** [comment] 2017-12-19 20:43
@DeMoorJasper That's an excellent question. When i said "confirmed". I meant that i confirmed that running parcel on another repo "fixes" the visual glitch. Sorry :confused:

**Comment by Olian04** [comment] 2017-12-19 20:56
@DeMoorJasper It looks like it has something to do with adding and removing deps.

__Removing a dep:__
I'm removing `lodash` by hand from the `package.json` in between those two start.
![image](https://user-images.githubusercontent.com/5493406/34178148-7794c23e-e506-11e7-976b-024547a98006.png)

__Adding a dep:__
For some reason it is required to run twice before it fails. I redid this process 3 times, same result every time.
![image](https://user-images.githubusercontent.com/5493406/34178239-c537acfe-e506-11e7-9775-d045e0c675b8.png)

**Comment by shawwn** [comment] 2017-12-21 01:07
I get this all the time too, and it's very annoying. I'm not a fan of the fancy colors or handholding the user. I vote to strip out all the highlighting code and just print the error normally.

Other people like it though, so it's up to the rest of the team.

It could also have nothing to do with the colors -- maybe it's a flushing issue?

**Comment by shawwn** [comment] 2017-12-21 01:08
Alternatively, we could strip out `process.cwd()` from error messages and stack traces. (Or rather the project root.)

**Comment by davidnagli** [comment] 2018-01-29 14:29
Many people are still complaining about this issue, and I still have problems with it on a daily basis. This is definitely still an issue (@DeMoorJasper's #207 didn’t fix it 😞)

For anyone who wants to take on this issue, here’s how to reproduce it:

1. Make your terminal window narrow (for example I keep my terminal split screen with my IDE)
2. Run the parcel command in some way that causes an error
3. You should see that the full red error output get’s cut off

For example:
```
parcel notarealfile.html
```

And you should get:
![screen shot 2018-01-29 at 9 27 13 am](https://user-images.githubusercontent.com/6759650/35515250-a3b784a6-04d6-11e8-8a4d-efdfc29ae6e6.png)


But it should instead wrap to the next line, since some crucial information get’s lost if we just arbitrarily cut it off. (Note: there’s no way to scroll or anything to reveal the rest of the error)

**Comment by DeMoorJasper** [comment] 2018-01-29 16:20
I'll look into it @davidnagli

**Comment by davidnagli** [comment] 2018-01-30 02:55
@Olian04 @shawwn @TimNZ Are you guys using Bash or ZSH as your terminal?


@DeMoorJasper I use ZSH, so if you can’t reproduce this issue maybe its possible that this is only an issue on ZSH…

**Comment by TimNZ** [comment] 2018-01-30 03:08
zsh.  

Can confirm word wrap works in bash.

**Comment by Olian04** [comment] 2018-01-30 12:17
@DeMoorJasper @TimNZ I'd hate to be the bearer of bad news, but I'm running bash.

**Comment by davidnagli** [comment] 2018-01-30 17:00
@TimNZ @Olian04 Can you guys please try out the PR (#696)?

I personally still get this same problem even with #696. I’m reasonably certain that the cause is the fact that I’m using iTerm2 as my terminal emulator which (maybe) doesn’t properly support newline characters being written to stdout.

**Comment by TimNZ** [comment] 2018-01-30 17:54
@davidnagli Hacky, but works 😀

This reminded me that running 'ps aux' in terminal on OS X results in the same.
Googling for that situation throws up a lot of discussion on cutoff terminal output.

But I don't recall an issue with output from other node based CLI tools.

**Comment by devongovett** [comment] 2018-01-31 07:16
For me, it does wrap, but the logger tracks the number of lines that it prints so it can overwrite the status line again. Currently, it always assumes that the status is only one line, but when the text wraps, it might be more. We'd need to take that into account so we can move overwrite the correct number of lines.

Ideally we'd leave the wrapping up to the terminal - that way when you resize your window things reflow rather than being hard wrapped to the size they were originally printed. This may be possible - we can compute how many lines the terminal will need using the column size, but not actually print hard newlines.

However, I'm not sure whether different terminals/shells handle wrapping correctly. Would be useful if people could post their terminal + shell, and whether it wraps or not. I'll start:

macOS Terminal + Bash

**Comment by davidnagli** [comment] 2018-01-31 19:54
I use: `iTerm2 + zsh` and it doesn’t work 👎 

I also tested on: `macOS terminal + zsh` and it works perfectly 👍

**Comment by devongovett** [comment] 2018-02-01 07:31
So maybe an iTerm issue?

**Comment by Olian04** [comment] 2018-02-01 14:59
@devongovett I'm on Ubuntu, so I doubt it iterm

**Comment by bloqhead** [comment] 2018-03-20 02:08
I recently ran into this issue with iTerm. Here's my info:

- **OS:** macOS High Sierra
- **CLI:** iTerm 2 + zsh

**Comment by davidnagli** [comment] 2018-03-20 02:24
@bloqhead Can you try PR #696 whenever you get a chance

It didn't work for me, but maybe it'll work for you 🤷‍♂️

**Comment by bloqhead** [comment] 2018-03-20 02:38
@davidnagli I actually saw that after writing my comments and was planning on trying it.

Here is some additional data that may help. I triggered an error intentionally and look at the second line. It wraps fine, but the very first one gets cut off -- https://cl.ly/qHFP

**Comment by geluso** [comment] 2018-04-28 21:31
Can confirm that this is still a problem on MacOS and iTerm. Works fine in MacOS Terminal.

**Closed** 2018-07-07 06:57 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, :pray: Help Wanted
