### ISSUE TITLE
Typescript public param not accessible as local variable inside constructor (parcel2)

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#7169] opened 2021-10-23 21:00 UTC
# 🐛 bug report

With parcel@2.0.0 and default settings, I’m seeing that a public parameter in a class constructor is getting rewritten in a way that local access to the variable no longer works.

I have outlined the issue with a simple sample project in this repo: https://github.com/mrcoles/parcel2-class-constructor-test

## 🎛 Configuration (.babelrc, package.json, cli command)

See the repo, but barebonse package.json with `parce@2.0.0` and `parcel src/index.html`

## 🤔 Expected Behavior

For a class like this:

```
class Test {
  constructor(public name: string) {
    console.log(name);
  }
}
new Test('hello, world');
``

I expect to see 'hello, world' written to the console.

## 😯 Current Behavior

The `name` variable ends up resolving to `window.name` instead of the local variable `name`.

## 💁 Possible Solution

Can work around by just doing `this.name` inside the constructor or by using `@parcel/transformer-typescript-tsc`. I don’t know if this is explicity parcel2 or more specifically https://github.com/swc-project/swc?

Also, works in parcel@1

## 💻 Code Sample

See the test repo up top

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | v14.8.0 |
| Yarn         | 1.22.4 |
| Operating System | macOS 10.15.7 |

**Comment by mischnic** [comment] 2021-10-24 07:22
Duplicate of https://github.com/parcel-bundler/parcel/issues/7142

**Closed as completed by mischnic** 2021-10-24 07:22 UTC
