### ISSUE TITLE
Inconsistent behaviour between dev and built bundles

### ISSUE THREAD

**Issue by bgirschig** [parcel-bundler/parcel#8904] opened 2023-03-21 11:24 UTC
# 🐛 bug report

Parcel works fine in dev mode, but does not warn about an error that breaks the build.

I've made a typo in my code: `for (item in items) {}` instead of `for (const item in items) {}`.
Parcel never warns me about this issue, but the bundled app fails to run because of a runtime error

## 🎛 Configuration
This happens with default config (no configuration file)

## 🤔 Expected Behavior
When the code contains such an issue, I would expect parcel to either
- Warn / raise an error in dev mode about this issue
- Warn / raise an error during production build
- Make a production bundle without runtime errors (like the dev one)

## 😯 Current Behavior
No errors or warnings are ever thrown, but the production bundle fails with runtime errors

## 💻 Code Sample
I've made a minimal example to reproduce the issue [here](https://drive.google.com/file/d/1w9V7192bdmYhxwR9-pUwzNLw9esrjO3Z/view?usp=share_link)
- `npm run start` works fine
- `npm run start-built` has no build errors, but throws an error at runtime

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.8.3
| Node             |  18.14.2
| npm/Yarn         |  9.5.0
| Operating System |  Debian GNU/Linux

**Comment by mischnic** [comment] 2023-03-23 21:13
> Parcel never warns me about this issue

This is totally valid JS syntax. So Parcel can't just throw a warning here.
Your case is similar to doing this:
```js
item = 2;
console.log(item);
```
which works fine in non-strict mode (= dev), but fails in production because then it's loaded via `<script type="module">` so in strict mode.

We do want to unify the behaviour here at some point: https://github.com/parcel-bundler/parcel/pull/8710 
Duplicate of https://github.com/parcel-bundler/parcel/issues/8706

**Closed as not planned by mischnic** 2023-03-23 21:13 UTC
