### ISSUE TITLE
Parcel doesn't seem to support node subpath exports

### ISSUE THREAD

**Issue by tanishqkancharla** [parcel-bundler/parcel#8791] opened 2023-01-24 16:43 UTC
# 🐛 bug report

I'm trying to use another package's [subpath exports](https://nodejs.org/api/packages.html#subpath-exports). The package looks like this: 
```tsx
"exports": {
    ".": {
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    },
    "./locales/en": {
      "import": "./dist/esm/locales/en/index.js",
      "require": "./dist/cjs/locales/en/index.js"
    },
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```json
"scripts": {
	"dev": "parcel index.html",
}
```

index.html: 
```html
<script src="./src/index.tsx" type="module" defer />
```

index.tsx
```tsx
import fake from "minifaker"
import "minifaker/locales/en"
```
No extra babel or parcel configuration

## 🤔 Expected Behavior

The english locale should be imported.

## 😯 Current Behavior

I receive this error on build:

```sh
🚨 Build failed.

@parcel/core: Failed to resolve 
'minifaker/locales/en' from 
'./src/index.tsx'

  /Users/tanishqkancharla/Documents/Projects/wisp/src/index.tsx:2:8
    1 | import fake from "minifaker"
  > 2 | import "minifaker/locales/en"
  >   |        ^^^^^^^^^^^^^^^^^^^^^^
    3 | import { useState } from "react"
    4 | import ReactDOM from "react-dom/cli
```

## 🔦 Context

I am unable to use the package's export.

## 💻 Code Sample

https://replit.com/@moonrise-tk/Parcel-Subpath-Export-Demo#index.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 18.4.0
| npm/Yarn         | 8.12.1 (npm)
| Operating System | MacOS, arm64

**Comment by devongovett** [comment] 2023-01-24 16:52
Duplicate of #4155

**Closed as completed by devongovett** 2023-01-24 16:52 UTC
