### ISSUE TITLE
npmjs.com upset because of missing readme

### ISSUE THREAD

**Issue by insuusvenerati** [parcel-bundler/parcel#4763] opened 2020-06-19 05:16 UTC
Sorry if this is the wrong place for this. 

It seems since README.md is linked to the v2 branch, [npmjs.com](https://www.npmjs.com/package/parcel-bundler) is upset about a missing readme file.

**Comment by mischnic** [comment] 2020-06-20 13:26
Duplicate of https://github.com/parcel-bundler/parcel/issues/2446

(And the `parcel-bundler` package isn't published from the v2 branch)

**Closed by mischnic** 2020-06-20 13:26 UTC
