### ISSUE TITLE
Parcel seems to mess up requirejs (sourceMappingURL)

### ISSUE THREAD

**Issue by lennart-k** [parcel-bundler/parcel#3456] opened 2019-08-23 11:04 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`npm install requirejs`
`parcel build script.js`

`script.js`
```js
import requirejs from 'requirejs'
```

## 🤔 Expected Behavior

Nothing spectacular, requirejs should be imported

## 😯 Current Behavior

```
⚠️  Could not load existing sourcemap of "node_modules/requirejs/bin/r.js".
🚨  /media/storage/tmp/node_modules/requirejs/bin/r.js:24807:27: Unterminated string constant (24807:27)
  24805 |     }
  24806 | 
> 24807 |     var mappingUrlPrefix = "\n
        |                           ^
  24808 |     if (options.sourceMapInline) {
  24809 |         stream += mappingUrlPrefix + "data:application/json;charset=utf-8;base64," + new Buffer(source_map).toString("base64");
  24810 |     } else if (options.outSourceMap && typeof options.outSourceMap === "string" && options.sourceMapUrl !== false) {
```

Although the actual content of r.js is
24807 | `var mappingUrlPrefix = "\n//# sourceMappingURL=";`

## 💁 Possible Solution

Without knowing much about how exactly parcel does things I think parcel removes the sourceMappingURL with following Regex
https://github.com/parcel-bundler/parcel/blob/8deb85d95e19ab39a5143489eabfbca13cc59663/packages/core/parcel-bundler/src/utils/loadSourceMap.js#L5
which does not seem to care about its context.

I don't really know if the spec for sourceMappingURL allows quotes in the URL but if not we could just change the line to

```js
 const SOURCEMAP_RE = /(?:\/\*|\/\/)\s*[@#]\s*sourceMappingURL\s*=\s*([^\s"'*]+)(?:\s*\*\/)?$/; 
```

## 🔦 Context

I'd like to use RequireJS in my parcel project which currently is not really that easy.

## 💻 Code Sample

Just create a file `script.js` with content
```js
import requirejs from 'requirejs'
```
Run `npm install requirejs`
and the try `parcel build script.js`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3     |
| Node             | 11.9.0     |
| npm/Yarn         | 6.9.0      |
| Operating System | Ubuntu 19.04 |

**Comment by mischnic** [comment] 2019-08-23 11:54
Yes, this is a known bug. Duplicate of #2408

**Closed by mischnic** 2019-08-23 11:54 UTC
