### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded at getParents

### ISSUE THREAD

**Issue by FaBeyyy** [parcel-bundler/parcel#2063] opened 2018-09-26 13:43 UTC
# 🐛 bug report

getting 

> Uncaught RangeError: Maximum call stack size exceeded
    at getParents (bootstrap.min.7942d6f1.js:265)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at getParents (bootstrap.min.7942d6f1.js:284)
    at hmrAccept (bootstrap.min.7942d6f1.js:338)
    at bootstrap.min.7942d6f1.js:339
    at Array.some (<anonymous>)

when js file is being hot reloaded.

function of failure: 
```javascript
function getParents(bundle, id) {
  var modules = bundle.modules;
  if (!modules) {
    return [];
  }

  var parents = [];
  var k, d, dep;

  for (k in modules) {
    for (d in modules[k][1]) {
      dep = modules[k][1][d];
      if (dep === id || Array.isArray(dep) && dep[dep.length - 1] === id) {
        parents.push(k);
      }
    }
  }

  if (bundle.parent) {
    parents = parents.concat(getParents(bundle.parent, id));
  }

  return parents;
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Using command line, babelrc:

```js
{
    "plugins": [
        ["dynamic-import-node"],
        ["transform-runtime",
        {
            "polyfill": false,
            "regenerator": true
        }],
        ["transform-object-rest-spread"]
    ],
    "presets": [
        ["env", {
          "targets": {
            "browsers": ["last 2 Firefox versions"]
          } 
        }]
      ]
} 
```

## 🌍 Your Environment
| Parcel           | Latest
| Node             | 10.9.0
| npm/Yarn         | 6.2.0
| Operating System | Windows 10, Firefox/Chrome

**Comment by DeMoorJasper** [comment] 2018-09-27 04:49
This is a known bug, pretty sure there's already an issue report for this.

Found it, duplicate of #1192

**Closed by DeMoorJasper** 2018-09-27 04:49 UTC
Labels: :bug: Bug
