### ISSUE TITLE
specify minimum node and npm version required to use parcel

### ISSUE THREAD

**Issue by bardiainjast** [parcel-bundler/parcel#231] opened 2017-12-12 09:36 UTC
I started playing with parcel by a very basic example (running node 6.10.2 and yarn 0.18.1) but i got error saying: 
`
parcel index.html
/home/bardia/.config/yarn/global/node_modules/parcel-bundler/bin/cli.js:84
async function bundle(main, command) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
`

then i installed latest stable node (8.9.3) and installed parcel by npm it self and everything started working correctly. 
i think it's a good idea to specify minimum node and npm (or yarn) version required to use parcel in Readme.

**Comment by Mohamed3on** [comment] 2017-12-12 15:31
Why does it need node 8 to run? isn't the code transpiled by Babel?

**Comment by bardiainjast** [comment] 2017-12-12 15:48
@Mohamed3on it's displaying syntax error so i guess probably you're right, @devongovett is it possible to transform code to es5 and then publish to npm ?!

**Comment by albinotonnina** [comment] 2017-12-12 16:35
Duplicate of #40 I'm gonna close this issue.
If you think I've done so in error, please don't hesitate to re-open the issue, comment, or send me a message on slack.

**Closed by albinotonnina** 2017-12-12 16:35 UTC
