### ISSUE TITLE
in v2: 	"browserslist": [ "> 5% in US", "supports es6-module" ] - both work in dev, but only first in build.

### ISSUE THREAD

**Issue by cekvenich2** [parcel-bundler/parcel#6799] opened 2021-08-29 06:47 UTC
Using v2.

This works in dev:
	"browserslist": [ "> 5% in US", "supports es6-module" ],

But in build 	"supports es6-module"  gives error:

> npx parcel build './src/**/index.pug' --dist-dir public --public-url / --log-level error   --detailed-report --no-source-maps --no-scope-hoist --no-content-hash --no-optimize

🚨 Build failed.

@parcel/transformer-js: Invalid Version: TP.0.0

  TypeError: Invalid Version: TP.0.0
  at new SemVer (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/semver/semver.js:323:11)
  at compare (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/semver/semver.js:614:39)
  at Function.gt (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/semver/semver.js:643:10)
  at Object.transform
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/transformer-js/lib/JSTransformer.js:312:58)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Transformation.runTransformer
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:604:5)
  at async Transformation.runPipeline
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:357:36)
  at async Transformation.runPipelines
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:241:40)
  at async Transformation.runPipelines
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:278:34)
  at async Transformation.runPipelines
  (/Users/vic1/.nvm/versions/node/v16.8.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:278:34)

**Comment by cekvenich2** [comment] 2021-08-29 06:48
Of course I only want to support browsers that support modules.

**Comment by mischnic** [comment] 2021-08-29 12:02
Duplicate of https://github.com/parcel-bundler/parcel/issues/6749

**Closed as completed by mischnic** 2021-08-29 12:02 UTC
