### ISSUE TITLE
Error using SASS on 1.12.4 parcel version

### ISSUE THREAD

**Issue by wendroandy** [parcel-bundler/parcel#5994] opened 2021-03-13 05:59 UTC
# 🐛 bug report
When i try to include SCSS file on HTML. This error showing
\node_modules\parcel-bundler\src\builtins\css-loader.js: Invalid Version: undefined

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "testing-parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "devDependencies": {
    "sass": "^1.32.8"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel index.html",
    "build": "parcel build index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

## 🤔 Expected Behavior
including SCSS in HTML file should be easy

## 💁 Possible Solution
if i install 1.12.3 parcel version the error is gone 

## 🔦 Context
development progress stoped

## 💻 Code Sample

as simple as including `<link rel="stylesheet" href="./scss/style.scss" >` in my HTML file.
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.15.0
| npm/Yarn         | 6.14.6
| Operating System | Windows 10 64-bit

**Comment by DeMoorJasper** [comment] 2021-03-13 10:08
Duplicate of https://github.com/parcel-bundler/parcel/issues/5943 ?

**Comment by wendroandy** [comment] 2021-03-13 14:18
@DeMoorJasper 
The error message different because my error is in css-loader.js and #5943 error is in index.js, but if i read some line below the error code the source looks similar with my case. Babel, Semver etc. 
Oh , hope this information can help : couple weeks ago,  i was using 1.12.4 parcel and run normal/fine. Just today im using same step but with different result.

**Comment by DeMoorJasper** [comment] 2021-03-13 14:19
@wendroandy the file doesn't really matter both files are being compiled with babel. So it's probably the same error, you can go through that issue and find a couple fixes for it, or upgrade to parcel 2 which does not have these issues.

**Closed by DeMoorJasper** 2021-03-13 14:19 UTC
Labels: :clock1: Waiting

**Comment by wendroandy** [comment] 2021-03-13 14:34
@DeMoorJasper 
Yes using parcel: ^2.0.0-beta.1 solve the issue. Thanks a lot for your help.
