### ISSUE TITLE
Faulty Code-splitting in a monorepo

### ISSUE THREAD

**Issue by chin2km** [parcel-bundler/parcel#8266] opened 2022-06-29 23:16 UTC
# 🐛 bug report

In a monorepo for a react application, the code splitting doesn't efficiently put modules in desired code-splitted page chunks.
Instead of adding modules in lazyloaded chunks, all modules get added to the main (index.js) bundle.

Example:
In a monorepo like this:
 
📦parcel-monorepo-codesplitting-bug
 ┣ 📂packages
 ┃ ┣ 📂application
 ┃ ┃ ┣ 📂src
 ┃ ┃ ┃ ┣ 📂pages
 ┃ ┃ ┃ ┃ ┣ 📜Blue.tsx
 ┃ ┃ ┃ ┃ ┣ 📜Green.tsx
 ┃ ┃ ┃ ┃ ┗ 📜Red.tsx
 ┃ ┃ ┃ ┣ 📜App.tsx
 ┃ ┃ ┃ ┣ 📜client.tsx
 ┃ ┃ ┃ ┗ 📜index.html
 ┃ ┃ ┣ 📜.parcelrc
 ┃ ┃ ┣ 📜package.json
 ┃ ┃ ┣ 📜tsconfig.json
 ┃ ┗ 📂ui-components
 ┃ ┃ ┣ 📂components
 ┃ ┃ ┃ ┣ 📜BlueComponent.tsx
 ┃ ┃ ┃ ┣ 📜GreenComponent.tsx
 ┃ ┃ ┃ ┣ 📜Header.tsx
 ┃ ┃ ┃ ┗ 📜RedComponent.tsx
 ┃ ┃ ┣ 📜index.ts
 ┃ ┃ ┗ 📜package.json
 ┣ 📜package.json

`BlueComponent` is used only in lazy loaded `Blue` page
`RedComponent` is used only in lazy loaded `Red` page
`GreenComponent` is used only in lazy loaded `Green` page

But `BlueComponent`, `RedComponent`, `GreenComponent` all gets added to `index.js` instead of `Blue.js`, `Red.js`, `Green.js` respectively.

Recreation repo: https://github.com/chin2km/parcel-monorepo-codesplitting-bug

## 🤔 Expected Behavior

`BlueComponent` gets added to `Blue.js` chunk
`RedComponent` gets added to `Red.js` chunk
`GreenComponent` gets added to `Green.js` chunk

## 😯 Current Behavior

`BlueComponent`, `RedComponent`, `GreenComponent` all gets added to `index.js` instead of `Blue.js`, `Red.js`, `Green.js` respectively.

<img width="1728" alt="Screenshot 2022-06-30 at 12 49 51 AM" src="https://user-images.githubusercontent.com/10056971/176560875-9839ec18-4ac8-45ea-8b7d-3e728449f28c.png">

## 💁 Possible Solution

The problems seems related to imports from `index.ts` files. If we import the components from its full path the chunks seems to be code-splitted correctly.
But its a major inconvenience to take so much care about how components are imported or what import path should be used. 

## 💻 Code Sample

https://github.com/chin2km/parcel-monorepo-codesplitting-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | v16.14.2
| npm/Yarn         | yarn 1.22.18
| Operating System | macOS

**Comment by devongovett** [comment] 2022-07-03 20:58
I believe this is a duplicate of #7392

**Closed as completed** 2022-07-03 21:06 UTC
Labels: :raising_hand_woman: Feature, :heavy_multiplication_x:  Duplicate, 🌳 Scope Hoisting, Bundler
