### ISSUE TITLE
v2: "Got unexpected null" when building TypeScript project

### ISSUE THREAD

**Issue by magcius** [parcel-bundler/parcel#3690] opened 2019-10-27 19:50 UTC
# 🐛 bug report

When trying to upgrade my project to Parcel V2, I got the error message:

```
$ D:\Development\NITRO_BMD\node_modules\.bin\parcel build src/index.html
× Got unexpected null
    at nullthrows (D:\Development\NITRO_BMD\node_modules\nullthrows\nullthrows.js:7:15)
    at BundleGraph.resolveSymbol (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\BundleGraph.js:368:53)
    at BundleGraph.resolveSymbol (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\public\BundleGraph.js:116:51)
    at markUsed (D:\Development\NITRO_BMD\node_modules\@parcel\scope-hoisting\lib\concat.js:201:32)
    at enter (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\Graph.js:475:16)
    at enter (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\Graph.js:475:16)
    at enter (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\Graph.js:475:16)
    at walk (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\Graph.js:331:22)
⠹ Optimizing index.19203168.css...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

The project is available here: https://github.com/magcius/noclip.website/tree/parcel-v2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1
| Node             | v10.16.3
| npm/Yarn         | Yarn version 1.19.0
| Operating System | Windows 10

**Comment by mischnic** [comment] 2019-10-27 20:01
Very likely the same issues as https://github.com/parcel-bundler/parcel/issues/3640. (Also using `@sentry/browser`)

**Comment by magcius** [comment] 2019-10-27 20:16
Thanks. I removed the sentry package for now. I am now hitting another error:

```
PS D:\Development\NITRO_BMD> yarn parcel build src\index.html
yarn run v1.19.0
$ D:\Development\NITRO_BMD\node_modules\.bin\parcel build src\index.html
× src\gfx\platform\GfxPlatformImpl.ts does not export 'GfxBindings'
    at replaceExportNode (D:\Development\NITRO_BMD\node_modules\@parcel\scope-hoisting\lib\link.js:149:13)
    at ReferencedIdentifier (D:\Development\NITRO_BMD\node_modules\@parcel\scope-hoisting\lib\link.js:511:20)
    at newFn (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\visitors.js:216:17)
    at NodePath._call (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\context.js:140:19)
    at Function.traverse.node (D:\Development\NITRO_BMD\node_modules\@babel\traverse\lib\index.js:80:17)
⠧ Optimizing index.ee239b95.js...
error Command failed with exit code 1.
```

I don't know why it thinks that GfxBindings is not exported, when it clearly is.

Is there a way to turn scope hoisting off for now? All I could find was this, which implies it should be off by default: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/Bundler.js#L110-L111

**Comment by mischnic** [comment] 2019-10-27 20:26
> Is there a way to turn scope hoisting off for now? All I could find was this, which implies it should be off by default: /packages/core/parcel-bundler/src/Bundler.js@v2#L110-L111 

`--no-scope-hoist`

(Even in the v2 branch, `packages/core/parcel-bundler` is the v1 version)

**Comment by magcius** [comment] 2019-10-27 20:37
Thank you, I've disabled scope hoisting for now, which seems to have solved my problem. If you intend to look into the scope hoisting issues, please let me know if you need any help setting up the repo for a repro case.

**Comment by mischnic** [comment] 2019-10-27 22:59
> × src\gfx\platform\GfxPlatformImpl.ts does not export 'GfxBindings'

Actually, the output from typescript for 
```ts
export enum _T { Buffer, Texture, ColorAttachment, DepthStencilAttachment, Sampler, Program, Bindings, InputLayout, InputState, RenderPipeline };

interface GfxResourceBase { ResourceName?: string, ResourceUniqueId: number };
export interface GfxBuffer extends GfxResourceBase { _T: _T.Buffer };
export interface GfxTexture extends GfxResourceBase { _T: _T.Texture };
// ...
export type GfxResource =
    GfxBuffer | GfxTexture | GfxColorAttachment | GfxDepthStencilAttachment | GfxSampler | GfxProgram | GfxBindings | GfxInputLayout | GfxInputState | GfxRenderPipeline;

```

is

```js
export var _T;
(function (_T) {
    _T[_T["Buffer"] = 0] = "Buffer";
    _T[_T["Texture"] = 1] = "Texture";
// ...
})(_T || (_T = {}));
```

Not even sure what the expected output is here (what is needed at runtime). But from Parcel's perspective, there *is* no `GfxBindings` ES6 named export.

[TS playground](http://www.typescriptlang.org/play/?target=99#code/FAehAIBUAsEsDsDmBncAXaBDN5nQPYCuANgCbj7zECe4ARgKbgBODAjobK+XbQA7FsAM3zMAtuFhiBDMQ3hpssSsgB0wUBAASmAMYBrdPnCIGOePjEJMxdNT4JE6hgA8+onPMISA+pHAA3uAAQoRCQgzMADRQrmiErDEAwvjEogCCaIq60HIKMQAiDHwYAMpo8rqwxJnZufJoMaWY0sSRMQAKzPiIzC0xwQikjsgxAJLwfIRoADKY1ESN4BNTaOXYDDEASvKkkR2wfAzECEwAvgDcGggVzEJ6TADiQi47yETMugzBmMhMQW8Pl8AHItBgAfgAXLg0MxHNsGO8El8AKrwWAcBhjUjQ+DeRjMcCXYCudzMHA3SL3L7gZ4uULhSLgOK7VB0wHI76-f7gPzQvyqBkRQnE0keSQKKkPWkvSBxBJMFnwUhsl4cz5cv6BXmQfmQVRylzxVhEq5i8kS27Up4vFJpZi1PT1BTMo2smWvRFAzU8vk61R2jJZJ15HCitziyl3aV0oolaDlSrVR05UOuirK1WepEan5aoJ+gVxsoZqo1YOphqmkkRi1R60e5qtJlKlUe9VfPO+3X+psyEVm2sUyXRml0ro9PoSVtZjs+7WF-UT3otavm4dWmMvQbKkbp93sr2crsLnsCnfDJCocNkjdSscvFbTOYLab7zPto+57mnvWqJ+zPMixrkOlr3jaLgAesFTvm2h45p2P4Fme+pQYoME3pGI4Noeyr7IcxynLBs5foh+Y6n+Ox4cwBxHCc8DnFcNa3nYRyfghTAALzAOAvEekKTIAD4eoaxpMMJdKBg6FbOjgEkvMWCalsmMlpvJLh9m0hLqcuU7gOpF57upAEvsBxmTNM0HiZ+1G0YRDFXEAA)

And Babel doesn't support this at all? [REPL](https://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=FAehAIBUAsEsDsDmBncAXaBDN5nQPYCuANgCbj7zECe4ARgKbgBODAjobK-XbQA7FsAM3zMAtuFhiBDMQ3hpssSsgB0wUBAASmAMYBrdPnCIGOePjEJMxdNT4JE6hgA8-onPMISA-pHAA3uAAQoRCQgzMADRQrmiErDEAwvjEogCCaIq60HIKMQAiDHwYAMpo8rqwxJnZufJoMaWY0sSRMQAKzPiIzC0xwQikjsgxAJLwfIRoADKY1ESN4BNTaOXYDDEASvKkkR2wfAzECEwAvgDcGggVzEJ6TADiQi47yETMugzBmMhMQW8Pl8AHItBgAfgAXLg0MxHNsGO8El8AKrwWAcBhjUjQ-DeRjMcCXYCudzMHA3SL3L7gZ4uULhSLgOK7VB0wHI76_f7gPzQvyqBkRQnE0keSQKKkPWkvSBxBJMFnwUhsl4cz5cv6BXmQfmQVRylzxVhEq5i8kS27Up4vFJpZi1PT1BTMo2smWvRFAzU8vk61R2jJZJ15HCitziyl3aV0oolaDlSrVR05UOuirK1WepEan5aoJ-gVxsoZqo1YOphqmkkRi1R60e5qtJlKlUe9VfPO-3X-psyEVm2sUyXRml0ro9PoSVtZjs-7WF_UT3otavm4dWmMvQbKkbp93sr2crsLnsCnfDJCocNkjdSscvFbTOYLab7zPto-57mnvWqJ-zPMixrkOlr3jaLgAesFTvm2h45p2P4Fme-pQYoME3pGI4Noeyr7IcxynLBs5foh-Y6n-Ox4cwBxHCc8DnFcNa3nYRyfghTAALzAOAvEekKTIAD4eoaxpMMJdKBg6FbOjgEkvMWCalsmMlpvJLh9m0hLqcuU7gOpF57upAEvsBxmTNM0HiZ-1G0YRDFXEAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript%2Cenv&prettier=false&targets=&version=7.6.4&externalPlugins=%40babel%2Fplugin-proposal-export-default-from%407.5.2)

**Comment by magcius** [comment] 2019-10-27 23:06
Interfaces are not a thing that have any runtime output. They're strictly a typechecking convenience.

**Comment by mischnic** [comment] 2019-10-27 23:11
I see, but Typescript can't know that
```js
import { GfxDevice, GfxBufferUsage, GfxBuffer, GfxInputState, GfxFormat, GfxInputLayout, GfxProgram, GfxBindingLayoutDescriptor, GfxRenderPass, GfxBindings, GfxHostAccessPass, GfxVertexAttributeFrequency } from '../gfx/platform/GfxPlatform';
```
need to be completely removed with the `typescript.transpileModule` api (which processes every asset individually).

Flow has `import type {...}` for something like that. I don't know how Typescript solves this issue (related: https://github.com/parcel-bundler/parcel/issues/3624).

**Comment by magcius** [comment] 2019-10-27 23:33
I don't know why babel REPL has issues with enums: https://babeljs.io/repl#?babili=false&browsers=IE%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYOwrgtgBAolDeUCGAaKAjNBjKBfA3AFBA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript%2Cenv&prettier=false&targets=&version=7.6.4&externalPlugins=%40babel%2Fplugin-proposal-export-default-from%407.5.2

But offline, it can compile it just fine. I assume it just can't parse TypeScript online.

I don't know what exactly transpileModule does, but I assume it just ignores interfaces and doesn't emit them in the output, since it doesn't need to do any work to verify them. Note how it doesn't bother emitting the interfaces here: https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=5&pc=1#code/JYWwDg9gTgLgBAbzgJQKYEMDGMByEAmqAglFOgJ5wC+cAZlBCHAORQbbMDcAUN7QK4A7bMAiC4RABS0IEAFwp2uAsVIUAlAoBuEYPkTcq3IA

Why my code is different, I don't know.

**Comment by mischnic** [comment] 2019-10-28 17:14
> I don't know what exactly transpileModule does, but I assume it just ignores interfaces and doesn't emit them in the output, since it doesn't need to do any work to verify them.

They aren't needed at runtime. But the issue here is that Typescript doesn't know if an import is importing a "real" value or an interface (where the export won't exist at runtime).

**Comment by magcius** [comment] 2019-10-28 18:15
Is the TypeScript output here generating an import for GfxBindings? That sounds like a TSC bug if it is.

**Comment by mischnic** [comment] 2019-10-28 18:18
> Is the TypeScript output here generating an import for GfxBindings?

Yes (which is understandable because every file is transpiled individually and TS can't know if GfxBindings will exist at runtime. They'd have to remove an import if it's only used as a type annotation.)

**Comment by magcius** [comment] 2019-10-28 18:21
I'll have to investigate later. If you can send me the TSC output or tell me where to find it, that would be a huge help. Not quite sure how to navigate the Parcel cache myself.

**Comment by magcius** [comment] 2019-10-28 18:22
> They'd have to remove an import if it's only used as a type annotation

TSC should be doing this already. See the example I posted above: https://www.typescriptlang.org/play/index.html#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAaOAJSwEMBjGAOQgBMsBBKKEgTzgF84AzKNOAciikK-ANwAocWQA2JAM5y4AMQgQ4WAB4wcNRanTZcicXFNwwAVwBG04GTgQrAKywU5ALiLCqtBk1YA2gC6cAC8cMES7OJAA

**Comment by mischnic** [comment] 2019-10-28 18:46
Interesting, now the question is where the import isn't removed.

**Comment by devongovett** [comment] 2019-10-28 18:50
does babel do the same thing (remove type imports)? v2 uses babel to compile typescript by default, not tsc.

**Comment by mischnic** [comment] 2019-10-28 18:51
@devongovett 
```json
{
    "extends": "@parcel/config-default",
    "transforms": {
        "*.ts": [ "@parcel/transformer-typescript-tsc", "@parcel/transformer-js" ]
    }
}
```

**Comment by magcius** [comment] 2019-10-28 19:02
Yes, Babel's TypeScript support chokes on my project currently, so I cannot use it.

**Comment by Banou26** [comment] 2019-11-15 23:40
Did anyone find a workaround for this error ?
I'm randomly getting it so i have to find ways to dev around it by not using certain features, which is quite annoying lol.

**Comment by astegmaier** [comment] 2020-02-28 03:07
I was able to solve this issue by removing two lines:

https://github.com/magcius/noclip.website/blob/c9f19e2206b035b957b63710577948bbb9ea2fb2/src/gfx/platform/GfxPlatform.ts#L324

https://github.com/magcius/noclip.website/blob/c9f19e2206b035b957b63710577948bbb9ea2fb2/src/viewer.ts#L247

(There are additional build errors that appeared after I solved this one, but they appear unrelated - I might be able to fully peal the onion if I have a bit more time).

The problem is that if you re-export types, you thwart typescript's ability to do "import elision" (i.e. detect whether an imported type is just used as a type (and can be removed by the transpiler) or not (and therefore should remain). This is a problem if you're compiling using `transpileModules` (like `@parcel/transformer-typescript-tsc` does). Typescript 3.8 [added a new feature to allow you to explicitly say that you want to import a thing as a type](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#type-only-imports-exports), which can help work around this.

**Comment by magcius** [comment] 2020-02-28 03:25
Ah, thank you, that makes sense. Re-exporting a type is a grammar position where types are allowed and can't be elided.

**Comment by astegmaier** [comment] 2020-02-28 19:48
@DeMoorJasper - I think you can close this because we found the root cause was by-design behavior. I opened #4240 to track the idea of providing more helpful error messages in this case.

**Closed** 2020-02-28 20:09 UTC
Labels: :bug: Bug, TypeScript, ✨ Parcel 2

**Comment by Richicratos** [comment] 2021-04-22 20:47
I deleted the .parcel-cache folder and it works!

**Comment by LukasBombach** [comment] 2021-11-12 09:49
You will also get this error in an isolated module, ie one that does neither import nor export anything
