### ISSUE TITLE
Serve with Parcel 2 throw error "Cannot read property 'env' of undefined"

### ISSUE THREAD

**Issue by michaelbrylevskii** [parcel-bundler/parcel#7267] opened 2021-11-08 14:14 UTC
# 🐛 bug report
When I run `npx parcel serve --target frontend`, I get the error "Cannot read property 'env' of undefined". But `watch` or `build` works fine.

```
PS D:\Projects\_TEST\TsFullStack> npx parcel serve --target frontend
Server running at http://localhost:1234
× Build failed.

Error: Cannot read property 'env' of undefined

  TypeError: Cannot read property 'env' of undefined
  at TargetResolver.resolve (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\core\lib\requests\TargetRequest.js:281:56)
  at async Object.run (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\core\lib\requests\TargetRequest.js:145:17)
  at async RequestTracker.runRequest (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\core\lib\RequestTracker.js:721:20)
  at async AssetGraphBuilder.runTargetRequest (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:751:19)
  at async PromiseQueue._runFn (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (D:\Projects\_TEST\TsFullStack\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

## 🎛 Configuration

Command: `npx parcel serve --target frontend`

Project Structure:
```
- dist
- - ...
- node_modules
- - ...
- packages
- - backend
- - - src
- - - - index.ts
- - common
- - - src
- - - - index.ts
- - frontend
- - - src
- - - - index.html
- - - - index.ts
- package.json
- package-lock.json
- tsconfig.json
```

package.json
```json
{
  "name": "ts-full-stack",
  "version": "1.0.0",
  "description": "TypeScript full-stack application",
  "author": "chop",
  "dependencies": {
    "express": "^4.17.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^16.9.3",
    "concurrently": "^6.2.1",
    "parcel": "^2.0.0",
    "typescript": "^4.4.3"
  },
  "targets": {
    "frontend": {
      "source": "packages/frontend/src/index.html",
      "distDir": "dist/frontend",
      "context": "browser",
      "engines": {
        "browsers": "> 5%, last 2 versions, not dead"
      },
      "includeNodeModules": true
    },
    "backend": {
      "source": "packages/backend/src/index.ts",
      "distDir": "dist/backend",
      "context": "node",
      "engines": {
        "node": ">= 14"
      },
      "includeNodeModules": true
    }
  },
  "scripts": {
    "watch:frontend": "parcel watch --target frontend",
    "watch:backend": "parcel watch --target backend",
    "build": "npm run build:backend & npm run build:frontend",
    "build:frontend": "parcel build --target frontend",
    "build:backend": "parcel build --target backend"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "isolatedModules": true
  }
}
```

index.html in frontend
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="module" src="index.ts"></script>
</head>
<body>
    <h2>Hello World</h2>
</body>
</html>
```

index.ts in frontend
```ts
import { sayHi } from '../../common/src/index';

console.log("Frontend Module Loaded");
sayHi("Loki");

export {};
```

index.ts in common
```ts
console.log("Common Module Loaded");

export function sayHi(user) {
  alert(`Hello, ${user}!`);
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel | 2.0.0 |
| Node | 14.17.6 |
| npm | 7.5.4 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment] 2021-11-08 14:28
Duplicate of https://github.com/parcel-bundler/parcel/issues/6905. Will be fixed in the next release: https://github.com/parcel-bundler/parcel/pull/7187

**Closed as completed by mischnic** 2021-11-08 14:28 UTC
