### ISSUE TITLE
🙋watch bundle add "poll" option

### ISSUE THREAD

**Issue by yalishizhude** [parcel-bundler/parcel#564] opened 2018-01-16 03:27 UTC
In Docker container on Windows, it cannot rebuild when files changed, so I need poll files to know whether they are changed. It is similar to webpack watch's option "poll".

refrence: https://webpack.js.org/configuration/watch/#watchoptions-poll

### 🤔 Expected Behavior

Just like webpack, I can config a param named "poll",which is a millisecond.
### 😯 Current Behavior

Now there is no option.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  0.0.1
| Node             | 8.9.3
| npm/Yarn         | 5.5.1
| Operating System | windows 10

**Comment by devongovett** [comment] 2018-01-20 20:40
Can we automatically detect the need to poll somehow? I would prefer not adding a million options if we can choose the right default automatically.

**Comment by jchv** [comment] 2018-01-22 16:11
Without getting pretty deep into the weeds, it may be hard to detect the conditions where you would need to use polling. The problem is that inotify WILL work, but it will only see local changes. So for example, if you exec into the container and touch a file, it will catch it, but if you change it externally nothing will happen.

The best solution I can imagine would be UNIX specific and would basically consist of the following:
- When watching a file, detect the mount point it is nearest.
- Detect the filesystem of the mountpoint.
- If the filesystem is known to have broken inotify support, punt back to polling for that file. Examples: `cifs`, `nfs`, `vboxsf` will all have trouble with inotify.

This may actually be worth an option though...

**Comment by marcklei** [comment] 2018-02-07 21:57
It is possible to set polling for chokidar via environment variables. I am in a similiar situation where I need to work on a windows machine with a docker development setup.

An example for setting polling via docker-compose.yml:
```
version: '2'
services:
  web:
    build: .
    command: yarn start
    ports:
     - "1234:1234"
     - "49359:49359"
    volumes:
    - .:/code
    environment:
    - CHOKIDAR_USEPOLLING=1
```
see [chokidar docs](https://github.com/paulmillr/chokidar#performance)

Even if this solves my issues, if a poll option should be added anyway I'd like to start working on this issue.

**Comment by brandon93s** [comment] 2018-02-07 22:36
@marcklei - that's a great find, thanks for sharing! Parcel also supports `dotenv` if you'd rather define the environment variable alongside you project as opposed to your machine configuration.

**Comment by jchv** [comment] 2018-02-08 03:40
Wow, I looked at the Chokidar source code and 100% missed this even though I was looking for it. Thanks for the tip, this is hugely useful for me!

**Comment by brandon93s** [comment] 2018-02-09 02:31
Closing in favor of using CHOKIDAR_USEPOLLING=1 which seems favorable to the flag anyways since it can be set in a config file.

**Closed by brandon93s** 2018-02-09 02:31 UTC
Labels: #Feature, Help Wanted

**Comment by rodoabad** [comment] 2018-08-17 01:45
@brandon93s even with CHOKIDAR_USEPOLLING though, hot reloading does not work. Does anyone have any solution to that?

**Comment by quochuytlbk** [comment] 2019-03-04 01:11
> @brandon93s even with CHOKIDAR_USEPOLLING though, hot reloading does not work. Does anyone have any solution to that?

Maybe [this](https://github.com/parcel-bundler/parcel/issues/2539#issuecomment-469086091) can work for you.
