### ISSUE TITLE
Page not reloading if my index.html has no one scripts

### ISSUE THREAD

**Issue by MegaJSDeveloper** [parcel-bundler/parcel#3869] opened 2019-12-03 17:20 UTC
# 🐛 bug report
Page not reloading if my index.html has no one scripts

## 🤔 Expected Behavior

`index.html`

```html
<div>ololo</div>
```

i change to:

```html
<div>trololo</div>
```
browser http://localhost:1234 must autoreload page

## 😯 Current Behavior
browser not autoreload page

## 💁 Possible Solution

if page has no one scripts, you must automatically add reload helper script like:

```html
<script id="__parcel__helper__">
  /* code */
  /* code */
  /* code */

  // clear html from helper script tag, just in case
  var helperScriptElement = document.body.getElementById('__parcel__helper__')
  helperScriptElement.parentNode.removeChild(helperScriptElement);
</script>
```

**Comment by mischnic** [comment] 2019-12-03 17:28
This is a known issue, duplicate of https://github.com/parcel-bundler/parcel/issues/943.

**Closed by mischnic** 2019-12-03 17:28 UTC
