### ISSUE TITLE
[Question] How can I build a simple static HTML site with ParcelJS?

### ISSUE THREAD

**Issue by debajit** [parcel-bundler/parcel#625] opened 2018-01-23 08:34 UTC
I have a simple static web site (assume that there are only HTML files for now)

### Input

```
app
├── my-first-article
│  └── index.html
├── my-second-article
│  └── index.html
└── yet-another-article
   └── index.html
```

### Expected Built Website

```
dist
├── my-first-article
│  └── index.html (minified)
├── my-second-article
│  └── index.html (minified)
└── yet-another-article
   └── index.html (minified)
```

**I simply need to minify the HTML for now** (and compress it to gz later). **How can I do this with Parcel?**

I can build a single file with

```
parcel build app/my-first-article/index.html
```

Is there a way I can do this for the entire root folder?

**Comment by DeMoorJasper** [comment] 2018-01-23 10:28
Related / duplicate of #189

**Closed by DeMoorJasper** 2018-01-23 10:28 UTC

**Comment by CharlesKumar** [comment] 2018-02-28 06:52
As far as static sites, webpack can multiple html files with single entry point by using either file-loader, html-loader or multiple HtmlWebpackPlugin instance

paracel may have cli option to include all `*.html` files in a dir, also `**/*.html` to include all subdir

or 

simply a parcel-plugin-html to do this copying of html to output dir internally

read [this](https://parceljs.org/assets.html) - At last html files can also be loaded as assets which means if you include a nav link to the entry ( index.html ), those files will be included with the caveat of filenames being messy (hashes)
