### ISSUE TITLE
naming problem: imports from parent directories are placed in "__/"

### ISSUE THREAD

**Issue by lhk** [parcel-bundler/parcel#2074] opened 2018-09-28 12:57 UTC
# 🐛 bug report

I'm using parcel to package a web extension. Since I want to target both chrome and firefox, I need a [polyfill](https://github.com/mozilla/webextension-polyfill) script.

This can be installed as a node package. I have added it to the manifest.json.
Parcel works fine. But the path that is automatically produced in the `dist/` folder is` __/node_modules/...`.
This is incompatible with Chrome. Web extensions must not have folders of name `__`.

## 🎛 Configuration (.babelrc, package.json, cli command)
I'm using a manifest.json. The relevant section looks like this:

```json
"content_scripts": [
    {
        "matches": ["<all_urls>"],
        "js": ["./content/index.ts", "../node_modules/webextension-polyfill/dist/browser-polyfill.min.js"]
    }
```

The parcel [plugin](https://www.npmjs.com/package/parcel-plugin-web-extension) reads this and produces:
```json
    "content_scripts": [
        {
            "matches": ["<all_urls>"],
            "js": [
                "content/index.js",
                "__/node_modules/webextension-polyfill/dist/browser-polyfill.min.js"
            ]
        }
```

## 🤔 Expected Behavior

The filename should be mapped to something different.

## 😯 Current Behavior

Imports from parent directories are mapped to a folder with name `__`

## 💻 Code Sample
I have set up a repository that reproduces the problem: https://github.com/lhk/webextension_typescript_webpack/tree/parcel_parent_import

Just use
 - npm install
 - parcel build src/manifest.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.1
| Node             | v8.12.0
| npm/Yarn         | 6.4.1
| Operating System | ubuntu 16.04 (64bit)

**Comment by 9oelM** [comment] 2018-10-15 04:16
I believe this is a [duplicate of issue #20 from parcel-plugin-web-extension repo](https://github.com/kevincharm/parcel-plugin-web-extension/issues/20)

**Closed** 2018-11-01 07:46 UTC
Labels: :bug: Bug
