### ISSUE TITLE
Parcel v2 package manager fails to install dependencies in Yarn workspace root

### ISSUE THREAD

**Issue by smrq** [parcel-bundler/parcel#6009] opened 2021-03-17 17:02 UTC
# 🐛 bug report

Attempting to run `yarn add` in a workspace root requires the `-W` flag to be passed in order to confirm that yes, you are trying to add a package to the root rather than an individual package.  `@parcel/package-manager` does not do this, and therefore errors out whenever it tries to install packages into a Yarn workspace root.

## 🎛 Configuration (.babelrc, package.json, cli command)

Minimal repro is below.  The only interesting configuration is setting up a Yarn workspace.

## 🤔 Expected Behavior

Packages should be installed successfully.

## 😯 Current Behavior

Yields these errors:

```
@parcel/package-manager: yarn: Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).

[...]

🚨 Build failed.
Error: Failed to install @parcel/transformer-typescript-types: Yarn failed to install modules:Child process failed
Error: Failed to install @parcel/transformer-typescript-types: Yarn failed to install modules:Child process failed
    at install (/Users/gregsm/code/dsx-react/node_modules/@parcel/package-manager/lib/installPackage.js:171:11)
    at async PromiseQueue._runFn (/Users/gregsm/code/dsx-react/node_modules/@parcel/utils/lib/PromiseQueue.js:108:7)
    at async PromiseQueue._next (/Users/gregsm/code/dsx-react/node_modules/@parcel/utils/lib/PromiseQueue.js:95:5)
```

## 💁 Possible Solution

Add `-W` to the args to `yarn add` when in a Yarn workspace root (i.e. there is a `workspaces` key in the `package.json`).

## 🔦 Context

Right now I have to wait for Parcel's install to fail, install the attempted package manually, [install again because I forgot to install `thing@next` instead of just `thing`,] and attempt to run build again in order to find out the next required package.

## 💻 Code Sample

Minimal repro here: https://gist.github.com/smrq/e4bba166d689765a126734649730699d

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 14.15.1
| npm/Yarn         | Yarn 1.22.5
| Operating System | MacOS High Sierra 10.13.6

**Comment by mischnic** [comment] 2021-03-17 17:03
Duplicate of https://github.com/parcel-bundler/parcel/issues/5854

**Closed as completed by mischnic** 2021-03-17 17:03 UTC

**Comment by smrq** [comment] 2021-03-17 17:12
My bad, I promise I searched first and didn't spot that :)
