### ISSUE TITLE
Identical files being merged which causes problems with React Context

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#3520] opened 2019-09-15 15:48 UTC
# 🐛 bug report

I have two React Contexts being used at the same time. They are created in an identical way, and this results in identical file content:

```js
import { createContext } from 'react';

export default createContext(null);
```

In development environment, Parcel recognizes two React Contexts as separate files and everything works as expected. In production environment, the files are being merged into one!

```js
{"react":"1n8/","./ContextA":"kuk5","./ContextB":"kuk5"}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Let the newest stable parcel-bundler install everything, including Babel.

## 🤔 Expected Behavior

Both in development and production mode:

<img src="https://user-images.githubusercontent.com/5426427/64924013-42826a00-d7e0-11e9-95da-259d79343c3c.png" width="250" />

## 😯 Current Behavior

In development mode:

<img src="https://user-images.githubusercontent.com/5426427/64924013-42826a00-d7e0-11e9-95da-259d79343c3c.png" width="250" />

In production mode:

<img src="https://user-images.githubusercontent.com/5426427/64924045-85dcd880-d7e0-11e9-8c5a-933c54a917dc.png" width="250" />

## 💻 Code Sample

https://github.com/wojtekmaj/parcel-file-merge-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | Yarn 1.17.3
| Operating System | Windows 10

**Comment by mischnic** [comment] 2019-09-15 19:17
Duplicate of https://github.com/parcel-bundler/parcel/issues/3368:

> The hash is based on the files contents, so this is actually not surprising (but obviously wrong).
> 
> This works correctly in Parcel 2 (alpha 1 was just published) and also with Parcel 1 and `--experimental-scope-hoisting`

**Closed by mischnic** 2019-09-15 19:17 UTC
Labels: :bug: Bug
