### ISSUE TITLE
Cannot compile worker which constructor has options

### ISSUE THREAD

**Issue by XGHeaven** [parcel-bundler/parcel#4351] opened 2020-03-20 11:00 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
`.babelrc`
```json
{
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "regenerator": true
    }]
  ]
}
```

`app.js`
```js
const w1 = new Worker('./worker1.js')
const w2 = new Worker('./worker2.js', { name: 'foo' })
```
worker1.js and worker2.js are exist.

`index.html`
```html
....
<script src="./app.js"></script>
....
```

Then build `index.html`.

## 🤔 Expected Behavior

Should be generate four files, `index.html`/`app.hash.js`/`worker1.hash.js`/`worker2.hash.js`.

## 😯 Current Behavior

But only three files generated. `index.html`/`app.hash.js`/`worker1.hash.js`.
No `worker2.hash.js` file generate. The source of `app.hash.js` only replace `worker1` url.
It's not replace `worker2`.

## 💁 Possible Solution

I think parcel only search `new Worker('file-name')` not `new Worker('file-name', options?)`.
When I remove `worker2` options, It's generate correctly with four files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.14.2 |
| Node             | 10.15.3 |
| npm/Yarn         | 6.4.1 |
| Operating System | Macos 10.15.3 |

**Comment by mischnic** [comment] 2020-03-20 11:02
Duplicate of https://github.com/parcel-bundler/parcel/issues/4350.

This is already fixed in Parcel 2.

**Closed by mischnic** 2020-03-20 11:02 UTC

**Comment by ahmed-musallam** [comment] 2020-03-21 02:20
@XGHeaven I guess we ran in the same issue around the same time?
Let me know if you find a fix.

I tried setting the `contentHash: false` but that only impacts the generated main bundle and not the generated webworker bundles... unfortunately.

I'm looking into writing a plugin to fix this issue, if that's even possible with a plugin..

In my opinion this issue should be fixed in V1 as well, but I do not have the knowledge to know where it needs to be fixed...

**Comment by XGHeaven** [comment] 2020-03-23 13:06
@ahmed-musallam  You can use follow command.

```
parcel build ./src/index.html ./src/worker.js
```

Open `localhost:1234/index.html` to develop. It's works with `new Worker('worker.js', options)`.
But It cannot auto add hash for generated worker file.

**Comment by ahmed-musallam** [comment] 2020-03-23 18:08
@XGHeaven yeah, that's still an issue regardless. I'm trying to figure out where in the parcel v1 code this is happening so I can understand how it works and maybe contribute a fix.

**Comment by mischnic** [comment] 2020-03-23 18:21
> where in the parcel v1 code this is happening  

Parcel 1 (contains the bug)
https://github.com/parcel-bundler/parcel/blob/76c5ac6c8dad3158dd0bd6f2a7879a73a80b1979/packages/core/parcel-bundler/src/visitors/dependencies.js#L86

Parcel 2 (fixed)
https://github.com/parcel-bundler/parcel/blob/76c5ac6c8dad3158dd0bd6f2a7879a73a80b1979/packages/transformers/js/src/visitors/dependencies.js#L136

But there will not be a new Parcel 1 release unless something dramatically breaks.
