### ISSUE TITLE
Running parcel in development mode crashes intermittently

### ISSUE THREAD

**Issue by quintonn** [parcel-bundler/parcel#8718] opened 2022-12-26 19:52 UTC
# 🐛 bug report

I run `npm run start` where the start script is as follows:  
`"start": "parcel src/index.html"`  

And then I frequently get the following error after making a seemingly random change in one of the TypeScript files:
```
Server running at http://localhost:1234
- Building dialogService.ts...
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink 'c:\Projects\Tests\parcel-test\dist\index.html.17308.2'
    at Object.unlinkSync (node:fs:1718:3)
    at WriteStream.<anonymous> (c:\Projects\Tests\parcel-test\node_modules\@parcel\fs\lib\index.js:1019:83)
    at Object.onceWrapper (node:events:510:26)
    at WriteStream.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'c:\\Projects\\Tests\\parcel-test\\dist\\index.html.17308.2'
}
```  

I will note that I've set up my project with a lot of inlining as I'm testing some things, but this was also happening before setting all the in-line configuration. Although, it might have happened less often.

## 🎛 Configuration (.babelrc, package.json, cli command)

Pretty much default parcel config, but I have TypeScript and TailwindCSS configured.  
Here is my entire project:
[parcel-test.zip](https://github.com/parcel-bundler/parcel/files/10304646/parcel-test.zip)

## 🤔 Expected Behavior

To be able to work on my project, make changes and see those changes in the browser without having to re-run `npm run start`

## 😯 Current Behavior

After only 2 or 3 changes (edit and save any of the .ts files) the command line crashes and I have to re-run the npm command.

## 💁 Possible Solution

🤷‍♂️

## 🔦 Context

I'm just testing Parcel as a potential bundler tool as it seemed the easiest to set up and get going, which it has been.

## 💻 Code Sample

[parcel-test.zip](https://github.com/parcel-bundler/parcel/files/10304646/parcel-test.zip)

## 🌍 Your Environment

Windows 10, pretty much up-to-date

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 |
| Node             |  v16.13.0. |
| npm/~Yarn~         | 8.10.0 |
| Operating System | Win 10 - 19045.2364 |

**Comment by devongovett** [comment] 2022-12-27 03:25
Duplicate of #8615

**Closed as completed by devongovett** 2022-12-27 03:25 UTC
