### ISSUE TITLE
You can specify a domain name for HTTPS or open the browser address

### ISSUE THREAD

**Issue by mj520** [parcel-bundler/parcel#1525] opened 2018-06-12 06:24 UTC
You can specify a domain name for HTTPS or open the browser address --open is default localhost, HTTPS needs to specify a domain name or a domain name solution that requires a domain name to solve cross domain problems, and an option --hostname specifies domain --host to specify IP.

**Comment by DeMoorJasper** [comment] 2018-07-11 18:03
Duplicate of #1412

**Closed by DeMoorJasper** 2018-07-11 18:03 UTC
