### ISSUE TITLE
Dynamic import seems to be broken

### ISSUE THREAD

**Issue by Richard87** [parcel-bundler/parcel#8712] opened 2022-12-22 09:54 UTC
# 🐛 bug report

Unable to dynamically import exceljs in Parcel (works in Vitejs among others).

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration, but a PoC is here:

```js
git clone https://github.com/Richard87/d2ebun
cd d2ebun
npm install
 ./node_modules/.bin/parcel public/index.html
```

## 🤔 Expected Behavior

Should work like the other bundlers?

## 😯 Current Behavior

Please take a look at this comment for the different results: https://github.com/mui/mui-x/issues/7273#issuecomment-1361384858

## 🔦 Context

Seems other have had the same issue: https://github.com/parcel-bundler/parcel/issues/112#issuecomment-1056869249

## 💻 Code Sample

https://github.com/Richard87/d2ebun

*Works* fine in Codesandbox's bundler
https://codesandbox.io/s/blazing-field-02vr0h?file=/demo.tsx 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |. 2.8.2
| Node             |  v19.3.0
| npm/Yarn         | npm 9.2.0
| Operating System | MacOS 13.0.1

**Comment by devongovett** [comment] 2022-12-27 03:29
This is a difference in ES module / CJS interop between bundlers. Looks like a previous PR to that library changed it to use the `default` export, but Parcel returns the namespace instead. Duplicate of #5459.

**Closed as completed by devongovett** 2022-12-27 03:29 UTC

**Comment by Richard87** [comment] 2022-12-27 19:39
thanks for responding :) Happy holidays! 🥇
