### ISSUE TITLE
file for node_modules not working when using postcss-pxtorem

### ISSUE THREAD

**Issue by yujingwyh** [parcel-bundler/parcel#8192] opened 2022-06-07 10:23 UTC
Can you add configuration items? I'm using postcss-pxtorem and found it doesn't work for node_module's files

_Originally posted by @yujingwyh in https://github.com/parcel-bundler/parcel/issues/7088#issuecomment-1148362017_

**Comment by mischnic** [comment] 2022-06-07 10:26
Duplicate of https://github.com/parcel-bundler/parcel/issues/5551

**Closed as not planned by mischnic** 2022-06-07 10:26 UTC

**Comment by yujingwyh** [comment] 2022-06-07 10:45
Hope to deal with it soon，file for node_modules not working when using postcss-pxtorem
