### ISSUE TITLE
Parcel doesn't serve assets it hasnt generated

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5972] opened 2021-03-06 19:03 UTC
# 🐛 bug report

Parcel doesn't serve assets/files that it hasn't generated.
For example, I tried to serve a WASM file from the `/dist` folder, but it served the `index.html` file instead.

bug happened for me on `2.0.0-nightly.618`, reverting back to `2.0.0-nightly.500` fixed the problem and correctly served the WASM file.

**Comment by mischnic** [comment] 2021-03-06 19:20
Probably a regression from https://github.com/parcel-bundler/parcel/pull/5835

https://github.com/parcel-bundler/parcel/blob/98c5902cefe1bba6c890da56f111e4b31b487c64/packages/reporters/dev-server/src/Server.js#L194

**Comment by andreyrd** [comment] 2021-03-16 20:28
This is completely breaking most of our assets, seems to happen with assets in bundles outside of the main one.

**Comment by devongovett** [comment] 2021-03-17 13:24
You generally shouldn't mess with the dist folder manually. In the future, Parcel may also clear out files that weren't generated by the current build as well.

A better solution is to make all files you depend on actual dependencies in your code that Parcel can discover. For example, importing URLs. This may also be possible using a custom plugin. This way Parcel is aware of these files, which means they can be watched for changes, content hashed for cacheability, etc.

If you're trying to simulate files hosted on an external server, I would suggest actually doing that using a separate file server locally as well.

**Comment by mischnic** [comment] 2021-03-17 13:45
But it looks like this also currently prevents sourcemaps from being served (`<` because that's the index.html):
```
DevTools failed to load SourceMap: Could not parse content for http://localhost:1234/index.fd532818.js.map: Unexpected token < in JSON at position 0
```

https://github.com/parcel-bundler/parcel/issues/5966

Another workaround is also https://v2.parceljs.org/features/api-proxy/:

```js
const path = require("path");
const serveStatic = require("serve-static");

module.exports = function (app) {
	app.use("/static", serveStatic(path.join(__dirname, "static")));
};
```

**Comment by devongovett** [comment] 2021-03-17 13:52
Ah. Source maps issue is definitely a bug. I guess it's because source maps aren't in the graph. Maybe we should track that somehow.

**Comment by andreyrd** [comment] 2021-03-17 15:00
Yeah, I'm not actually modifying my dist folder. I think the assets that are failing to load are required from modules that are themselves required asynchronously (so in their own bundle), but I have not been able to confirm exactly what causes it.

**Comment by mischnic** [comment] 2021-03-23 16:35
This should also be fixed by https://github.com/parcel-bundler/parcel/pull/6024

**Closed by mischnic** 2021-03-23 16:35 UTC
Labels: :bug: Bug, ✨ Parcel 2
