### ISSUE TITLE
@parcel/core: Failed to resolve '@libp2p/logger'

### ISSUE THREAD

**Issue by PhillyWebGuy** [parcel-bundler/parcel#8386] opened 2022-08-09 23:28 UTC
I know very little about Parcel nor libp2p. My apologies for only giving the error I get when trying to build a React app:

@parcel/core: Failed to resolve '@libp2p/logger' from './node_modules/ipfs-core/src/components/index.js'

What other info can I provide to help troubleshoot?

**Comment by pointlesscore** [comment] 2022-08-10 20:56
Hi!

It's due to the fact that Parcel can't find a [package entry](https://parceljs.org/features/dependency-resolution/#package-entries) without a `source`, a `module` or a `main` fields in `package.json` of the module you need to resolve. `@libp2p/logger` has only the `exports` field, hence Parcel can't resolve it

For a temp fix, you can add an [alias](https://parceljs.org/features/dependency-resolution/#package-aliases) in your `package.json` to tell Parcel how to resolve `@libp2p/logger`:

```json
{
  "alias": {
      "@libp2p/logger": "/node_modules/@libp2p/logger/dist/src/index.js"
  }
}
```

**Comment by mischnic** [comment] 2022-08-11 07:58
Unfortunately a duplicate of https://github.com/parcel-bundler/parcel/issues/4155

**Closed as not planned by mischnic** 2022-08-11 07:58 UTC
