### ISSUE TITLE
suggestion: add alias support 

### ISSUE THREAD

**Issue by KloveML** [parcel-bundler/parcel#538] opened 2018-01-11 06:04 UTC
###  Sorry, my English is very poor, so I suppose I only express my mind simply with English.
>
### 💻 Code Sample

```js
import  comA from '@/components/comA'
```
###Owing to the lack of alias  support , then run the code and get back the error message that don't import comA (vue component)

**Comment by DeMoorJasper** [comment] 2018-01-11 10:35
Duplicate of #25

**Closed by DeMoorJasper** 2018-01-11 10:35 UTC
