### ISSUE TITLE
How to observe the changes in HTML and CSS, and then automatically refresh the browser ?

### ISSUE THREAD

**Issue by lian-xiao-xi** [parcel-bundler/parcel#215] opened 2017-12-11 15:24 UTC
#### How to observe HTML and CSS changes, and then automatically refresh the browser. Now only by observing the changes in JS to automatically refresh the browser

**Comment by DeMoorJasper** [comment] 2017-12-11 15:27
HTML updating should be inside the current github version, CSS updating is in an open PR here #128

**Comment by DeMoorJasper** [comment] 2017-12-11 15:49
duplicate of #57 duplicate of #90

**Closed by DeMoorJasper** 2017-12-11 15:49 UTC
