### ISSUE TITLE
@parcel/transformer-svg-react doesn't work with @parcel/config-webextension and a named pipeline

### ISSUE THREAD

**Issue by everdimension** [parcel-bundler/parcel#8538] opened 2022-10-13 08:55 UTC
In short, this config produces an error:

```
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "jsx:*.svg": ["...", "@parcel/transformer-svg-react"]
  }
}
```

The error occurs when I have an import in my code:
```
import SomeIcon from 'jsx:../../assets/some-icon.svg';
```

The error is during the build:

```
 Build failed.

@parcel/core: No transformers found for
src/ui/assets/some-icon.jsx with pipeline: 'jsx'.

  /Users/everdimension/web/my-extension-project/.parcelrc:3:3
    2 |   "extends": "@parcel/config-webextension",
  > 3 |   "transformers": {
  >   |   ^^^^^^^^^^^^^^^^^
  > 4 |     "jsx:*.svg": ["...", "@parcel/transformer-svg-react
  >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 5 |   }
  >   | ^^^
    6 | }
    7 |

  /Users/everdimension/web/my-extension-project/node_modules/@parcel/config-webextension/index.json:3:3
    2 |   "extends": "@parcel/config-default",
  > 3 |   "transformers": {
  >   |   ^^^^^^^^^^^^^^^^^
  > 4 |     "manifest.json": ["@parcel/transformer-webextension
  >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 5 |     "raw:*": ["@parcel/transformer-raw"]
  >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 6 |   },
  >   | ^^^
    7 |   "runtimes": ["...", "@parcel/runtime-webextension"],
    8 |   "packagers": {
```
    
    
---

If I remove the named-pipeline part from the config, it works:
```
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "*.svg": ["...", "@parcel/transformer-svg-react"]
  }
}
```

This way I can import svgs as react components without writing the "jsx:" prefix in the import.

But the problem is that this way all SVGs turn into react components and I have no way to import them as assets, meaning I cannot get a URL to the static file to apply svg as a background-image, for example.

### My env
Node: v16.14.0
Npm: 8.3.1
Macos: 11.5.1
#### Parcel packages:
```
    "@parcel/config-webextension": "^2.6.0",
    "@parcel/transformer-inline-string": "^2.6.0",
    "@parcel/transformer-svg-react": "^2.6.0",
    "parcel": "^2.6.0",
```

**Comment by mischnic** [comment] 2022-10-14 14:11
Duplicate of https://github.com/parcel-bundler/parcel/issues/7587

**Closed as not planned by mischnic** 2022-10-14 14:11 UTC
