### ISSUE TITLE
Auto-rebuild doesn't work with certain directory name

### ISSUE THREAD

**Issue by ParkSB** [parcel-bundler/parcel#2093] opened 2018-10-02 08:44 UTC
# 🐛 bug report

Auto-rebuild(Hot reload) doesn't work on the local development server opened by `parcel serve` command in some directory named like 'parksb.github.io'.

## 🎛 Configuration (.babelrc, package.json, cli command)

**parksb.github.io/package.json**
```js
{
  ...
  "scripts": {
    "serve": "parcel ./index.html",
    "build": "parcel build ./index.html",
  },
  ...
}
```

## 🤔 Expected Behavior

After opening the web server using `parcel ./public/index.html -d ./`, Parcel should rebuild the development server automatically when I change files.

## 😯 Current Behavior

Parcel only opens the server and does not rebuild automatically.

## 💁 Possible Solution

I found that this issue related to the directory name. It occurred when the directory name was  `parksb.github.io` and `test.github.io`, but it doesn't occur when the directory name was `test`, `a.b.c` and `test.test.com`.

## 💻 Code Sample

**parksb.github.io/index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Document</title>
</head>
<body>
  <h1>Hello, world!</h1>
  <script src="./index.js"></script>
</body>
</html>
```
**parksb.github.io/index.js**
```js
console.log('test');
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 8.11.3
| npm/Yarn         | 6.4.1
| Operating System | WSL(Ubuntu 16.04 LTS) on Windows 10

**Comment by jasonsturges** [comment] 2018-10-06 06:19
It seems like the issue is periods in the name.

As in: username.github.com doesn't work.

**Comment by ParkSB** [comment] 2018-10-06 07:05
@jasonsturges Thank you :) May I know why parcel doesn't work with github domain?

**Comment by benavern** [comment] 2018-10-07 16:18
Hi! I have the same issue. Is there a fix planned for that ? This is a very disapointing probem :(

**Comment by RustyRaptor** [comment] 2018-11-08 19:01
I just realized this is a duplicate of my issue as well was not aware the folder name was the cause. This happens with parent folders as well so I assume any time there is this periods in the path name this happens. #2231

**Comment by RustyRaptor** [comment] 2018-11-08 19:04
can I please point out that the likely reason you guys think parcel is broken on ubuntu is that people reporting the issue on ubuntu are probably just building a github site...

**Comment by ChristophP** [comment] 2018-11-09 23:47
I have a similar configuration and the same problem but even without a github folder name:
- Ubuntu 18.04.01 LTS
- node 10.13.0 LTS
- parcel 1.10.3

My folder path is: `~/projects/professional-website` but I also tried `~/projects/test`

The command that is run is `parcel src/index.html`. It builds once but never again even when index.html or any of its sub depencies are changed.

Very annoying and frustrating. :-/
Running `chokidar src -c "echo Hello"` works, so it must be something with parcel itself.

**Comment by RustyRaptor** [comment] 2018-11-15 22:04
@ChristophP  have you tried the usual fix of increasing max file watch limit?

**Comment by RustyRaptor** [comment] 2018-11-15 22:05
@ChristophP  if you have already tried that you should make a new issue.

**Comment by carlosrberto** [comment] 2019-02-08 19:49
This issue is still happening

**Comment by DeMoorJasper** [comment] 2019-02-08 19:59
The fix for this has been merged so i'll close this it hasn't been released yet though

**Closed by DeMoorJasper** 2019-02-08 19:59 UTC
Labels: :bug: Bug

**Comment by wispyco** [comment] 2020-01-29 22:09
@RustyRaptor Where do you chage the max file watch limit? Parcel shows a build in terminal but the page doesn't autorefresh. Im in ubuntu here.
