### ISSUE TITLE
'build' command total time seems wrong

### ISSUE THREAD

**Issue by windware** [parcel-bundler/parcel#859] opened 2018-02-20 06:54 UTC
Below, it says the real time is "49.12s" which is accurate but it says "bundle.js" took "463.09s".
I wonder how this number was calculated or is it just off by 10 fold?
I was thinking if this was the addition of all bundling processes for each files under multi core but the server I'm using only has a single core.

> ✨  Built in 49.12s
> dist/bundle.js                  |              514.41 KB  |  463.09s
> dist/3ac13c0a6d5f627f150ad131535e13c8.svg  |     433.96 KB |      478ms
> dist/bundle.css                               |  202.3 KB |    120.04s
> dist/08a6235b494705fc54df603e3f1f60de.eot |      161.86 KB |      468ms
> .
> .
> .

### 💻 Code Sample

> parcel build bundle.ts

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.9.4
| npm/Yarn         | 5.6.0
| Operating System | Ubuntu 16.04

**Comment by DeMoorJasper** [comment] 2018-02-20 07:39
duplicate of #845

**Closed by DeMoorJasper** 2018-02-20 07:39 UTC
