### ISSUE TITLE
[Parcel v2] Error: Got unexpected null when using inline styles

### ISSUE THREAD

**Issue by songhn233** [parcel-bundler/parcel#6068] opened 2021-03-31 15:41 UTC
# 🐛 bug report

When I tried to use parcel@nightly I got an error `Error: Got unexpected null when using inline styles`

After debugging I made a minimal demo that reproduces the problem

only a `index.html` and run `parcel index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div style="color: red"></div>
  </body>
</html>
```
Then when I visit the page it reports an error
```
Error: Got unexpected null
    at nullthrows (demo/node_modules/nullthrows/nullthrows.js:7:15)
    at PackagedBundle.get filePath [as filePath] (demo/node_modules/@parcel/core/lib/public/Bundle.js:367:38)
    at demo/node_modules/@parcel/reporter-dev-server/lib/Server.js:272:104
    at Array.find (<anonymous>)
    at Server.serveBundle (demo/node_modules/@parcel/reporter-dev-server/lib/Server.js:272:45)
    at Server.respond (demo/node_modules/@parcel/reporter-dev-server/lib/Server.js:219:19)
    at demo/node_modules/@parcel/reporter-dev-server/lib/Server.js:441:14
    at call (demo/node_modules/connect/index.js:239:7)
    at next (demo/node_modules/connect/index.js:183:5)
    at Function.handle (demo/node_modules/connect/index.js:186:3) {
  framesToPop: 1
```
If I change the inline style to an external css file it works fine, which I think is strange

## 🎛 Configuration

```json
"devDependencies": {
    "@parcel/config-default": "^2.0.0-nightly.634",
    "@parcel/transformer-sass": "^2.0.0-nightly.634",
    "@parcel/transformer-typescript-tsc": "^2.0.0-nightly.634",
    "parcel": "^2.0.0-nightly.632",
  },
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.632
| Node             | v15.5.0
| npm/Yarn         | yarn@1.22.5

**Comment by mischnic** [comment] 2021-03-31 15:45
Duplicate of https://github.com/parcel-bundler/parcel/issues/6043, open PR: https://github.com/parcel-bundler/parcel/pull/6067

**Closed as completed by mischnic** 2021-03-31 15:45 UTC
