### ISSUE TITLE
Peer dependencies unmet

### ISSUE THREAD

**Issue by oliversalzburg** [parcel-bundler/parcel#6877] opened 2021-09-03 13:23 UTC
# 🐛 bug report

When installing parcel, it results in unmet peer dependency warnings.

## 🎛 Configuration (.babelrc, package.json, cli command)

not relevant

## 🤔 Expected Behavior

All internal peer dependencies are provided by parcel.

## 😯 Current Behavior

```shell
➤ YN0002: │ @parcel/types@npm:2.0.0-rc.0 doesn't provide @parcel/core (p7e272), requested by @parcel/workers
➤ YN0002: │ @parcel/types@npm:2.0.0-rc.0 doesn't provide @parcel/core (p46e35), requested by @parcel/fs
➤ YN0002: │ @parcel/types@npm:2.0.0-rc.0 doesn't provide @parcel/core (p16c36), requested by @parcel/cache
➤ YN0002: │ @parcel/types@npm:2.0.0-rc.0 doesn't provide @parcel/core (p347b3), requested by @parcel/package-manager
```

## 💁 Possible Solution

Add the dependencies.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 16
| npm/Yarn         | 3.0.2
| Operating System | WSL

**Comment by mischnic** [comment] 2021-09-03 13:30
Duplicate of https://github.com/parcel-bundler/parcel/issues/6727

**Closed as completed by mischnic** 2021-09-03 13:30 UTC
