### ISSUE TITLE
Parcel cannot handle scripts with type="plain/text"

### ISSUE THREAD

**Issue by azan-n** [parcel-bundler/parcel#7696] opened 2022-02-11 11:02 UTC
# 🐛 bug report

When using a cookie consent dialog, I encountered this bug where parcel refuses to build with the following log:

> @parcel/core: No transformers found for index.plain.
> 
>   /home/apollo/parcel-bug/node_modules/@parcel/config-default/index.json:3:3
>      2 |   "bundler": "@parcel/bundler-default",
>   >  3 |   "transformers": {
>   >    |   ^^^^^^^^^^^^^^^^^
>   >  4 |     "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   >  5 |     "bundle-text:*": ["...", "@parcel/transformer-inline-string"],
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   >  6 |     "data-url:*": ["...", "@parcel/transformer-inline-string"],
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   >  7 |     "worklet:*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   >  8 |       "@parcel/transformer-worklet",
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   >  9 |       "..."
>   >    | ^^^^^^^^^^^
>   > 10 |     ],
>   >    | ^^^^^^
>   > 11 |     "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   > 12 |       "@parcel/transformer-babel",
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   > 13 |       "@parcel/transformer-js",
>   >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 

## 🎛 Configuration (.babelrc, package.json, cli command)

Reproduction can be found here: https://github.com/azan-n/parcel-bug-plain-text

## 🤔 Expected Behavior

Scripts of type plain/text should be left as is. 

## 😯 Current Behavior

As above.

## 💁 Possible Solution

This would probably mean having a "transformer" (pardon my usage of the word, I may be wrong but I assume it is the correct entity to refer to in this case) for scripts with type "plain/text" that essentially do nothing to the contents.

## 🔦 Context

Most cookie-consent dialogs tutorials and ones on GH ready to use, set the script type to "plain/text" so it is ignored by the browser till the user chooses to accept cookies.

## 💻 Code Sample

https://github.com/azan-n/parcel-bug-plain-text

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 16.13.0
| npm/Yarn         | 8.1.4
| Operating System | Ubuntu 20.04.3 LTS

**Comment by azan-n** [comment] 2022-02-11 11:43
I did a little digging around and tried to create a package of my own which essentially wastes a cycle of execution (not the best implementation I am aware but should work in practice).
```js
import {Transformer} from '@parcel/plugin';

export default new Transformer({
  async transform({asset}) {
    return [asset];
  }
});
```
.parcelrc
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.plain": [
			"parcel-transformer-plaintext", "..."
		]
	}
}
```
I am however hit by a different error this time around:
> Build failed.
> Error: require() of ES Module /home/apollo/Desktop/Projects/cryptlex-website2/packages/parcel-transformer-plaintext/index.js not supported.
> Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules. 

There is no require used in the module but I'm sure I'll need to dig around a little more to be able to make this 'hack' work. However, I got this idea that there will always be new and weird ways of using the `type` attribute specific to applications, some that might not even be a MIME type, all the while being perfectly valid HTML. 
In such situations, and other such situations, it would be good to have a 'parcel-transformer-do-nothing' or similar functionality.

**Comment by JustinWallace-MOM** [comment] 2022-03-22 17:47
I'm getting this error too, with probably the same cookie consent plugin!

It would be great if there were an attribute we could add to a script to have Parcel ignore trying to transform it.

**Comment by mischnic** [comment] 2022-03-22 17:58
Duplicate of https://github.com/parcel-bundler/parcel/issues/357 / https://github.com/parcel-bundler/parcel/issues/1087

**Closed as completed by mischnic** 2022-03-22 17:58 UTC

**Comment by stilliard** [comment] 2022-04-02 16:42
In case it helps anyone else running into this, I've created a package to help with this: https://www.npmjs.com/package/parcel-transformer-plaintext similar to the code by @azan-n :)
