### ISSUE TITLE
@parcel/ts-utils does not work on node without es module support

### ISSUE THREAD

**Issue by xfoxfu** [parcel-bundler/parcel#3931] opened 2019-12-19 09:46 UTC
# 🐛 bug report

`@parcel/ts-utils` does not work on node without es module support.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`

```json
{
  "extends": [
    "@parcel/config-default"
  ],
  "transforms": {
    "*.ts": [
      "@parcel/transformer-typescript-tsc"
    ],
    "*.tsx": [
      "@parcel/transformer-typescript-tsc"
    ]
  }
}

```

## 🤔 Expected Behavior

The project compiles successfully.

## 😯 Current Behavior

Node emits an error in script of `@parcel/ts-utils`.

## 💁 Possible Solution

Emit code with commonjs modules on package `@parcel/ts-utils`.

## 🔦 Context

Node emits the following error:

```console
 Error: Unexpected token 'export'
~/node_modules/@parcel/ts-utils/src/index.js:2
export * from './FSHost';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1043:16)
    at Module._compile (internal/modules/cjs/loader.js:1091:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at NodePackageManager.load (~/node_modules/@parcel/package-manager/lib/NodePackageManager.js:106:9)
    at NodePackageManager.requireSync (~/node_modules/@parcel/package-manager/lib/NodePackageManager.js:72:17)
    at Module.m.require (~/node_modules/@parcel/package-manager/lib/NodePackageManager.js:93:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (~/node_modules/@parcel/transformer-typescript-tsc/lib/TSCTransformer.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "incremental": true,
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "rootDir": "./src",

    "strict": true,

    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,

    "esModuleInterop": true,

    "forceConsistentCasingInFileNames": true,

    "baseUrl": "./src",
    "paths": {
      "~*": ["./*"]
    }
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}

```

## 💻 Code Sample

<https://github.com/xfoxfu/parcel-issue-3931>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | 13.4.0 |
| npm/Yarn         | 1.19.2 |
| Operating System | macOS 10.15.2 |

**Comment by mischnic** [comment] 2019-12-19 10:39
This is already fixed by https://github.com/parcel-bundler/parcel/pull/3831 and will (hopefully) be released soon.

**Comment by DeMoorJasper** [comment] 2019-12-19 12:05
As this is fixed we can close this

**Closed by DeMoorJasper** 2019-12-19 12:05 UTC
Labels: :bug: Bug

**Comment by levrik** [comment] 2020-01-02 14:15
Can this please be released? I wanted to give Parcel v2 a try for some new toy project but I can't move forward.

**Comment by DaniGuardiola** [comment] 2021-04-05 10:31
Sorry for leaving a "+1" comment but... +1 :P

I can't move forward either with a project, please release it :)

**Comment by mischnic** [comment] 2021-04-05 10:41
This is long fixed in beta 2

**Comment by lukejagodzinski** [comment] 2021-06-20 13:30
It's not fixed in beta 3. Error still appears... I can't build my node app.

```
external-api: $ parcel build src/index.ts --cache-dir .cache --target app
external-api: Building...
external-api: 🚨 Build failed.
external-api: Error: Unexpected token 'export'
external-api: /Users/lukejagodzinski/workspace/web/node_modules/@parcel/ts-utils/src/index.js:2
external-api: export * from './FSHost';
external-api: ^^^^^^
external-api: SyntaxError: Unexpected token 'export'
external-api:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
external-api:     at Module._compile (internal/modules/cjs/loader.js:963:27)
external-api:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
external-api:     at Module.load (internal/modules/cjs/loader.js:863:32)
external-api:     at NodePackageManager.load (/Users/lukejagodzinski/workspace/web/node_modules/@parcel/package-manager/lib/NodePackageManager.js:212:9)
external-api:     at NodePackageManager.requireSync (/Users/lukejagodzinski/workspace/web/node_modules/@parcel/package-manager/lib/NodePackageManager.js:178:17)
external-api:     at Module.m.require (/Users/lukejagodzinski/workspace/web/node_modules/@parcel/package-manager/lib/NodePackageManager.js:198:19)
external-api:     at require (internal/modules/cjs/helpers.js:74:18)
external-api:     at Object.<anonymous> (/Users/lukejagodzinski/workspace/web/node_modules/@parcel/transformer-typescript-tsc/lib/TSCTransformer.js:10:16)
external-api:     at Module._compile (internal/modules/cjs/loader.js:999:30)
external-api: error Command failed with exit code 1.
external-api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in 'external-api'
error Command failed with exit code 1.
```

I will try to reproduce this problem but so far with the simple node + express app it works. I don't know which part of the app is causing issue in Parcel. Btw. it's a monorepo

**Comment by lukejagodzinski** [comment] 2021-06-20 13:38
Ok the problem was that it used alpha version of the `@parcel/transformer-typescript-tsc` package instead of `^2.0.0-beta.3.1`. Just leaving it here if someone have similar problem.

**Comment by jubbers** [comment] 2021-08-17 15:43
> Ok the problem was that it used alpha version of the `@parcel/transformer-typescript-tsc` package instead of `^2.0.0-beta.3.1`. Just leaving it here if someone have similar problem.

Had the same issue as @lukejagodzinski, the command below solved the problem for me too for anyone else running into this. Make sure this is the right version for you if you're a person from the future.

`npm i --save-dev @parcel/transformer-typescript-tsc@^2.0.0-beta.3.1`
