### ISSUE TITLE
Browserslist parsing logic incorrect for Safari Technology Preview

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#7516] opened 2022-01-02 23:27 UTC
# 🐛 bug report

The browserslist parsing logic in JSTransformer.js breaks on Safari TP.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```js
{
  "browserslist": ["supports wasm"]
}
```
Most `supports` queries fail, `wasm` is just what I was using when I found this issue.

## 🤔 Expected Behavior

Build should succeed.

## 😯 Current Behavior

```
@parcel/transformer-js: Invalid Version: TP.0.0
  TypeError: Invalid Version: TP.0.0
  at new SemVer (node_modules/semver/semver.js:323:11)
  at compare (node_modules/semver/semver.js:614:39)
  at Function.gt (node_modules/semver/semver.js:643:10)
  at Object.transform (node_modules/@parcel/transformer-js/lib/JSTransformer.js:312:58)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Transformation.runTransformer (node_modules/@parcel/core/lib/Transformation.js:617:5)
  at async Transformation.runPipeline (node_modules/@parcel/core/lib/Transformation.js:366:36)
  at async Transformation.runPipelines (node_modules/@parcel/core/lib/Transformation.js:244:40)
  at async Transformation.run (node_modules/@parcel/core/lib/Transformation.js:170:19)
  at async Child.handleRequest (node_modules/@parcel/workers/lib/child.js:217:9)
```

## 💁 Possible Solution

JSTransformer.js appears to attempt to parse the output of browserslist with SemVer by removing the browser name before the space and removing any version ranges by slicing anything after a dash. This works fine for stuff like `chrome 72` and `samsung 11.1-11.2`, but it breaks on `safari TP`.

## 💻 Code Sample

`index.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // Just need JS in the project to reproduce
        console.log('hi')
    </script>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | v16.6.2
| npm/Yarn         | 1.22.15
| Operating System | Ubuntu 20.04 (WSL)

**Comment by mischnic** [comment] 2022-01-03 09:16
Duplicate of https://github.com/parcel-bundler/parcel/issues/6749#issuecomment-903551321

**Closed as completed by mischnic** 2022-01-03 09:16 UTC
