### ISSUE TITLE
WebExtension manifestV3 doesn't work as expected

### ISSUE THREAD

**Issue by sergey-shpak** [parcel-bundler/parcel#7997] opened 2022-04-23 09:16 UTC
# 🐛 bug report

Using parcel to build webextension with manifest v3 causing few issues:
1. web_accessible_resources are not storing initial resource name if it is already used as an action source
2. all the sources bundled into root dir without any dir paths
3. manifest schema doesn't allow any additional props ([like `key` for example](https://developer.chrome.com/docs/extensions/mv2/manifest/key/))

## 🎛 Configuration (.babelrc, package.json, cli command)
default configuration

no babel config

## 🤔 Expected Behavior

1. Storing initial web_accessible_resources names to make them accessible
2. Preserving paths to sources in resulting bundle
3. Adding key prop, or allowing additional props in manifest schema

## 💻 WebExtension Manifest Sample
```json
{
  "name": "Test",
  "version": "0.0.0",
  "description": "Test manifest",
  "manifest_version": 3,
  "action": {
    "default_popup": "action.html"
  },
  "web_accessible_resources": [{
    "resources": ["action.html"],
    "matches": ["<all_urls>"]
  }]
}
```
results in 
```json
{
  "name":"Test",
  "version":"0.0.0",
  "description":"Test manifest",
  "manifest_version":3,
  "action":{
    "default_popup":"action.e0bbec54.html"
  },
  "web_accessible_resources":[{
    "resources":["action.e0bbec54.html"],
    "matches":["<all_urls>"]
  }]}
```
reusing compiled resource without preserving it's initial name is wrong for web_accessible_resources

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0.
| Node             | 16
| npm/Yarn         |
| Operating System |

**Comment by 101arrowz** [comment] 2022-04-23 18:04
3 is expected behavior because the schema does not allow manifest keys that are particularly unusual or marked as deprecated. 1 and 2 seem to be issues with `needsStableName` not changing asset's cache key. I'll try to investigate this soon.

**Comment by sergey-shpak** [comment] 2022-04-23 19:55
@101arrowz thanks, the `key` prop is not deprecated and used in development(to preserve extension id), also there are other props that are not in manifest scheme yet, for [example `optional_host_permissions`](https://github.com/w3c/webextensions/issues/119), so it would be great to allow passing additional properties(at least for commonProps)

**Closed as completed** 2022-05-23 14:20 UTC
Labels: :bug: Bug, Web Extensions
