### ISSUE TITLE
I don't want to bundle the images referenced in the scss file.

### ISSUE THREAD

**Issue by hand2441** [parcel-bundler/parcel#4457] opened 2020-04-10 05:39 UTC
# 🐛 bug report

I want not dist dir creat image

Even the image is not in src.

my Dir 
root
  |--- src
  |--- dist
  |--- images

main.scss
![이미지 1](https://user-images.githubusercontent.com/38928298/78965617-7c2e1000-7b38-11ea-98a3-630f89514efc.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "dependencies": {
        "parcel-bundler": "^1.12.4"
    },
    "devDependencies": {
        "@babel/polyfill": "^7.8.7",
        "axios": "^0.19.2",
        "blueimp-load-image": "^2.30.0",
        "dom4": "^2.1.5",
        "gsap": "^3.2.6",
        "intersection-observer": "^0.7.0",
        "jquery": "^3.4.1",
        "lodash": "^4.17.15",
        "pikaday": "^1.8.0",
        "sass": "^1.26.3",
        "sortablejs": "^1.10.2",
        "whatwg-fetch": "^3.0.0"
    },
}
```

## 🤔 Expected Behavior

not dist dir creat image

../../image/common/icon.png ==> ../../image/common/icon.png

## 😯 Current Behavior

../../image/common/icon.png ===> dist/icon.22b88bb8.png

![이미지 2](https://user-images.githubusercontent.com/38928298/78965867-3faee400-7b39-11ea-843b-b053d6c7f0e7.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |     1.12.4
| Node             |  12.13
| npm/Yarn         | 6.12
| Operating System | win10

**Comment by mischnic** [comment] 2020-04-22 21:09
Duplicate of https://github.com/parcel-bundler/parcel/issues/1186, https://github.com/parcel-bundler/parcel/issues/1087 (A solution for those would work for any URL)

**Closed by mischnic** 2020-04-22 21:09 UTC
Labels: :grey_question:  Question
