### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by bdunklau** [parcel-bundler/parcel#6822] opened 2021-08-30 14:47 UTC
https://medium.com/@vic850c/preview-of-parcel-version-2-eb986f6d4d67

**Comment by devongovett** [comment] 2021-08-30 15:39
IE11 first is definitely NOT the philosophy. In fact, unless you configure a browserslist, Parcel does not transpile at all.

This isn't really an actionable issue, closing.

**Closed as completed by devongovett** 2021-08-30 15:39 UTC

**Comment by cekvenich2** [comment] 2021-08-30 16:12
I wrote that article. Why was this closed just with a comment? Every commit indicates that Parcel v2 does not support modules: for the sake of supporting ie11.

As per thread: https://github.com/parcel-bundler/parcel/discussions/6801 with no answers so that we can only speculate.

Why are those decisions made if not for ie11? Modern browsers don't need any of these features. 
The article points out module based builder even with example. Is there a point in the article you refute, there are 5 pro ie11 points?

**Comment by cekvenich2** [comment] 2021-08-30 16:17
Cut/paste from the article re ie11 first - what points are not correct: 
1- Support for module only browsers is buggy: http://github.com/parcel-bundler/parcel/issues/6749. Also, if you set package json to type: module, the Pug plugin can no longer read pug.config.js to set pretty: true and breaks pug support.
2- It can’t load modules via a CDN, such as the popular jsDeliver ( http://jsdelivr.com/esm ). Also, if you say https in script tag, it errors out. If an imported module is used by two different scripts, it does not leverage browsers built in module imports, thus increasing the download size.
3- When it builds, it randomly renames .js and css files. This is good for people that don’t use a CDN, but if you want to reduce the # of downloaded files, it makes it hard to share and block the browser from de-duplicating natively.
4- It randomly renames variables inside your .js, making it hard to maintain large scale production apps. It mangles your code, presumably to make it ie11 complaint.
5- ie11 supports http v1.x vs Chrome and friends supporting http v3.x. So many small imports that are smaller are faster. In ie11 you get more by one large file download.

**Comment by cekvenich2** [comment] 2021-08-30 16:18
Further, the article, that is mostly positive, gives an example of a module based builder:
- http://github.com/ficusjs/ficusjs-snowpack-starter

Would you argue that module support of Parcel 2 is better than Snowpack above?

**Comment by devongovett** [comment] 2021-08-30 17:09
I closed this because the feedback wasn't actionable. If you have specific requests to improve Parcel, please feel free to open individual issues for them. But just linking to articles that complain isn't very constructive.

That said, here are some replies to your points.

1. That's a bug, which we will fix.
2. Shared modules will be deduplicated if they are over a size threshold. See https://v2.parceljs.org/features/code-splitting/#shared-bundles. This is because the HTTP request overhead of many tiny modules and reduction in gzip/brotli compression effectiveness of small files reduces performance, even with http2. This is based on research done by the Google Chrome team. See https://web.dev/granular-chunking-nextjs/.
3. I think you're talking about content hashing? This is definitely not random. This is very helpful to improve cache performance at both the browser and server/CDN level. See more about that in the docs: https://v2.parceljs.org/features/production/#content-hashing. It is also possible to change the way bundles are named via Namer plugins: https://v2.parceljs.org/plugin-system/namer/. I'm not sure I understand your specific problem here.
4. Again, not quite sure what you're referring to. Minification? This is a production optimization to reduce download size and it significantly improves performance. This has nothing to do with IE 11. I'm not sure why that would affect the maintainability of your source code.
5. See the research from the Chrome team linked in (2) for details on why this isn't true. Keeping the HTTP request count lower has performance benefits, which is why people use bundlers instead of just shipping their source code directly to prod.

**Comment by cekvenich2** [comment] 2021-08-30 22:43
Yeah, it be great if the team here helps out, and I'd be happy to help out myself as I have done open source and know what it is to be a contributor. Here it is the points:
1. Has a second sentence. As per docs https://v2.parceljs.org/getting-started/library/ where it says "The "type": "module" field can also be set in package.json to treat the main field as an ES module". I set that, as my note said it breaks pug support. (IMO "module" should be a default ). I opened a ticket 6830 as per request.
2. People used to say that sun revolves around the earth since they can see it move. But then you do the math. It is MUCH larger download, lets say 10 times larger if you don't do modules. You can measure it. I'll even make a project for you to show you that Parcel v2 is 10 times larger download than Snowpack. You can open browser developer tool to see it. At worst - you should give us an option to disable this 'improvement'. (to be sure, in ie 11 it is an improvement, but not on modern browser that support modules.). Lets say I have 3 entry points, but a large app will have many landing pages for A/B testing, SEO and more. A user loads page 1. That loads a module a. Module a loads modules b, c, d, e, f. Most pages have many many modules. When I build w/ Snowpack and Vite, they are left alone as imports. 
The user then goes to page 2. The page 2 has module z. Module z loads modules b, c, d, e and f. But because snowpack and vite can and do leave it as modules: it only loads z. It does not reload b, c, d, and e. So 5 times smaller, if they are all same size, but likely supporting modules are larger. Then user opens page 3 that has module k. Module k imports b, c, d and e. In Snowpack and vite, it only loads module k. It does not load b, c, d and e. It uses browser's native module load. Now compare to parcel v2. A use goes to same 3 pages. And each time b, c, d and e are loaded. 10 times larger than snowpack and vite. So please allow us to use native module loader and not force a combined load. I opened a feature request: 6831
3. 'Content hashing' renames files. The problem is illustrated here: https://github.com/parcel-bundler/parcel/discussions/6801
Should I make a feature request?  When I make a web-component for reuse by others on other projects: I need the name to be consistent. CDN has no problem with this, no need to force cache busting. Please allow us to disable this 'feature' (again ie 11 has problems cache busting, that is for sure). Both snowpack and vite and maybe others do this by default.
4. 'Mimification' should be an option and not forced. This point I did not say has anything to do with ie 11, I think you added that. If I have an app in production I need to know what I wrote. Mimification should be a plugin, just like javascript obfuscation is a plug in(I checked, you have it) and at best you should allow us to disable it so that I can reduce the maintenance costs. Both Vite and Snowpack and others have this, I should not be forced.
5. I did not say code should be shipped to prod, we need the imports from npm to work. I agree it is same point as 2, and should be same feature request to turn of: 6831.

It is said that generals fight the last war, and I can see how v2 is better. But modern browsers have moved on, import module works, and we are building larger apps where 80% of the cost is maintenance and only 20% is development. 

Ideally please enable full module and make mimification a flag, or even just default to all these things and if people need 'ie 11' mode they have to flip flags. This way you test for modules and not find out that a plug in like pug does not support modules, since it is not tested for that.

I'd be more than happy to code, test, etc. I more than admire and support open source. I hate trolls and and I hate that I had to do this to get a reaction. (I'll take down the flamey article after a few days, I need it for now for my notes).
Let me know how I can help you best. Because I have tested all the bundlers and this one is the best, and I'm already using it on 3 projects, one with 25 devs on it(at Maestro). I just need a few tweeks please, modules and maintenance are important to me. So please suggest how I can help you and open source best.
Cheers and pardon the dust up.

**Comment by cekvenich2** [comment] 2021-08-30 22:47
Also, am I using 'esmodules' right, as per this: https://github.com/parcel-bundler/parcel/discussions/6833?
