### ISSUE TITLE
Simple tilde resolution not working for me

### ISSUE THREAD

**Issue by Kurren123** [parcel-bundler/parcel#2813] opened 2019-03-18 10:03 UTC
# 🐛 bug report

Simple tilde paths as described under [getting started](https://parceljs.org/module_resolution.html#~-tilde-paths) don't seem to be resolving.

## 🤔 Expected Behavior

A [repo of the error](https://github.com/Kurren123/parcel-js-bug). My folder structure:

```
node_modules
  xhook
    dist
      xhook.js
folder1
  index.html
index.html
package.json
```

And both `index.html` files have:

```html
<html>
  <body>
    <script src="~/node_modules/xhook/dist/xhook.js"></script>
  </body>
</html>
```

When I run `parcel folder1/index.html` it should build.

## 😯 Current Behavior

`parcel index.html` works fine but  `parcel folder1/index.html` returns:

```
D:\dev\parcel-test\folder1\node_modules\xhook\dist\xhook.js: ENOENT: no such file or directory, open 'D:\dev\parcel-test\folder1\node_modules\xhook\dist\xhook.js'
```

It seems to be treating the tilde as a relative path rather than looking for the folder containing `node_modules`.

## 💻 Code Sample

[Repository of the bug](https://github.com/Kurren123/parcel-js-bug).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.2 |
| Node             | 11.12.0 |
| npm/Yarn         | npm 6.7.0 |
| Operating System | Windows 10 |

**Comment by lustoykov** [comment] 2019-03-19 15:25
What is the expected behaviour here? Do we want `~` to work same as in webpack? Means that a lookup is performed against node_modules to resolve the path? If yes, then the path should have been 
`<script src="~xhook/dist/xhook.js"></script>`. However, even in this case, parcel does not work as expected, but I could try to fix that if the specification is to be compliant with other bundlers? 

Think the relevant code is here 

https://github.com/parcel-bundler/parcel/blob/32f332782e830036c775dc7ad2631b5801719dc3/packages/core/parcel-bundler/src/Asset.js#L95-L105

**Comment by mischnic** [comment] 2019-03-19 16:48
`~/node_modules/...` is actually correct: https://parceljs.org/module_resolution.html#~-tilde-paths

> that if the specification is to be compliant with other bundlers?

That difference isn't ideal though

**Comment by lustoykov** [comment] 2019-03-21 12:05
I've looked a bit more into it and looks like the behavior is expected?

`parcel folder1/index.html` would mean that `this.options.rootDir` would be `path/to/folder1`, therefore parcel tries to resolve the resource relative to `path/to/folder1/` - the **entry root**.

https://github.com/parcel-bundler/parcel/blob/c3921cb93368c3e0d4c24f2966931279e7fd1ae4/packages/core/parcel-bundler/src/Resolver.js#L128-L135 

> **entry root:** the directory of the entrypoint specified to Parcel, or the shared root (common parent directory) when multiple entrypoints are specified.


On an unrelated note, line 133 seems suspicous to me that it could result in another issue (in a much more obscure case though where package root has priority, but I haven't verified this).

**Comment by bbugh** [comment] 2019-03-28 12:13
The code does appear like it's set up how it's supposed to be, but `~` is also not working for me as described in the above issue report. 

`~` should resolve to the package root (closest node_modules), but it is resolving to the entry point, not the package location. As soon as I changed my entry point from `./index.html` to `./src/index.html`, my `~` references broke, and I had to change them to relative folders with `..`.

**Comment by Qayou** [comment] 2019-03-28 13:33
Just to add to the above comments, I find myself building modules that are nested in several folders like `myapp/path/to/my/module/module.js`.

Now if I import `~/utils/anotherModule.js` in my module, I would expect **Parcel** to resolve `myapp/utils/anotherModule.js`

But it resolves to `myapp/path/to/my/module/~/utils/anotherModule.js` and fails.

The doc states:

> ~/foo resolves foo relative to the nearest package root or, if not found, the entry root.

But the code states:

> Tilde path. Resolve relative to nearest node_modules directory, or the project root - whichever comes first.

They are both very different behaviors. I wonder what is the use case for the latter...

**Comment by devniel** [comment] 2019-04-16 05:45
Hello, just to mention that I also had to use `~/../node_modules/..` when having the entry file in `src/index.html`. I'm using `parcel-bundler` as middleware with express.

`@import url('../node_modules/...');` also works.

```
node_modules
 carbon-components
src
  App.jsx
  App.scss <-- @import '~/../node_modules/carbon-components/css/carbon-components.css'
  index.html
server.js
package.json
```

**Comment by devniel** [comment] 2019-04-16 16:58
That was for that simple structure, now in other complex project structure I'm struggling with importing some css in a scss.

```
node_modules
client
  node_modules
    carbon-components
  public
    index.html
  src
    index.js
    index.scss <-- @import '~/../node_modules/carbon-components/css/carbon-components.css'
server.js <-- const bundler = new Bundler(...); // etc.
package.json
```
The entry file is located in `/Users/devniel/dev/da/project/client/public/index.html`

and the import is resolving to `/Users/devniel/dev/da/project/client/public/Users/devniel/dev/da/project/client/node_modules/carbon-components/css/carbon-components.css` in the `Resolver.js` 😕

I think that it should be  `/Users/devniel/dev/da/project/client/public/node_modules/carbon-components/css/carbon-components.css`, the thing is that the shown error is in the parcel building is reporting this path as `cannot resolve...`, but inside it's using the mentioned above.

**Comment by savovs** [comment] 2019-05-31 00:49
This is such an annoying bug it's making me consider moving back to webpack

**Comment by YassienW** [comment] 2019-06-05 13:15
Same issue, ~ seems to be resolving to the entry root, rendering it pretty much useless.

**Comment by savovs** [comment] 2019-06-16 17:03
Hey y'all, here's a reproduction repo for anyone who wants to quickly see this bug in action:
https://github.com/savovs/parcel-tilde-bug

**Comment by alexerhardt** [comment] 2019-07-17 09:06
In my case (MacOS) tilde resolves to... nothing really. It's just taken literally:

`Cannot resolve module [...] at '/project-root/src/styles/~/normalize.css/normalize.css'`ñ~

Adding `~/node_modules/...` does nothing.

I've resorted to using the full relative path:

`@import "../../node_modules/normalize.css/normalize.css";`

**Comment by mjgerace** [comment] 2020-01-09 02:31
This is still broken.

**Comment by kahurangitama** [comment] 2020-01-09 12:02
```
/Users/loyi/nm-frontend/src/components/App/App.tsx:48:39: Cannot resolve dependency '~/routes' at '/Users/loyi/nm-frontend/src/components/App/~/routes'
    at Resolver.resolve (/Users/loyi/nm-frontend/node_modules/parcel-bundler/src/Resolver.js:71:17)
```

**Comment by YassienW** [comment] 2020-01-10 13:14
I don't think this is getting fixed since all the focus is on Parcel 2.

**Comment by mjgerace** [comment] 2020-01-12 22:07
@YassienW this is broken in Parcel 2

**Comment by DeMoorJasper** [comment] 2020-01-13 09:41
@mjgerace pretty sure this works perfectly in Parcel 2. What exactly is broken about it?

**Comment by mjgerace** [comment] 2020-01-13 14:37
@DeMoorJasper it resolves to entry-pont directory as root instead of true root. I can upload an example project/provide more details when out of work, if you'd like.

**Comment by DeMoorJasper** [comment] 2020-01-13 16:27
Pretty sure #3141 fixed that

**Comment by mjgerace** [comment] 2020-01-13 19:02
@DeMoorJasper I am on the absolute latest version, but I can see when I get home and give you more information.

**Comment by Cristy94** [comment] 2020-03-20 01:03
Still not working for me in latest version (alpha 2.3). TS compiles fine, Visual Studio autocompletes fine, parcel says path doesn't exist.

tsconfig:
```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "./src/*"
            ]
        },
        ....
    },
    "include": [
        "./src/**/*"
    ]
}
```

Folder structure:
```
root
 - package.json
 --src
 ---index.html
```

Command: `parcel src/index.html` or `parcel ./src/index.html`.

Error:
`@parcel/resolver-default: Cannot find module '~/config/Config' from 'C:\project-root\src\components\sidebar'.`

**Comment by TimMensch** [comment] 2020-05-11 23:39
Parcel 2 is broken with respect to TypeScript tilde paths.

In the Parcel docs it tells us to use `~` to refer to files relative to the `src` folder. See this `tsconfig.json` from the example:

```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "~/*": ["./*"]
    },
    "typeRoots": ["node_modules/@types"]
  },
  "include": ["src/**/*"]
}
```

And this from the [gist](https://gist.github.com/croaky/e3394e78d419475efc79c1e418c243ed):

`import { Reset } from '~/ui/shared/Reset'`

No `src` path in the example -- and in Parcel 1 it worked. 

Apparently Parcel 2 is using `~` as a relative path to the `package.json` folder? That profoundly breaks all TypeScript code which depends on the original example. The original approach is frankly a _more sane_ assumption, too; otherwise you're adding `src` redundantly to all imports.

**Comment by mischnic** [comment] 2020-05-12 16:21
> The original approach is frankly a more sane assumption, too; otherwise you're adding src redundantly to all imports.

The problem with Parcel 1's `~` is that was never really was `src` but rather the nearest parent folder of all entries:
```
├── package.json
└── src
	├── index.html (entry)  with `<script src=./index.ts`
	└── index.ts

-> ~ = root/src
```
```
├── package.json
├── index.html (entry)  with `<script src=./src/index.ts`
└── src
	└── index.ts

-> ~ = root
```

**Comment by TimMensch** [comment] 2020-05-12 20:08
Understood. But the _sane_ approach includes _let us define what the root folder should be_. Don't just pick one arbitrarily; let us have a say in it.

And let us pick `src` in the second example, even though `index.html` is outside of `src`. In fact, the _best_ case would be to let us pick an array of root folders, and just search for every `~` file sequentially in each root.

Don't break hundreds of lines of existing code because of some arbitrary new rule you'd like to add. Make the feature actually _useful_.

Even better: Respect the `paths` entry from the TypeScript file instead of relying on a hack.

**Comment by mischnic** [comment] 2020-05-12 20:45
> Understood. But the sane approach includes let us define what the root folder should be. Don't just pick one arbitrarily; let us have a say in it.

Parcel 2 has support for custom resolver plugins, so even a non-core userland plugin could resolve `~` however it wants.
(Not that we don't *want* to support this, but we also have other priorities at the moment)

**Comment by devongovett** [comment] 2020-05-12 20:46
All of that is typescript specific. Parcel has supported tilde resolution for literally years, and it applies the same way across all file types. TS doesn't get to dictate how all of Parcel works.

As @mischnic said, Parcel 2 supports custom resolver plugins, and these can be chained. So we could easily support a `@parcel/resolver-typescript` package for better TS support, which could override the default resolver for TypeScript files.

**Comment by TimMensch** [comment] 2020-05-12 20:53
A TypeScript resolver sounds perfect, so that would address my immediate request. Something that is linked from the TypeScript docs would be even better.

Any documentation on how a resolver should work?

**Comment by mischnic** [comment] 2020-05-12 20:58
WIP docs: https://parcel2-docs.now.sh/plugin-system/resolver/

default resolver plugin: https://github.com/parcel-bundler/parcel/blob/f65aa4c53ab130debfc88f4628eb001f52fb5f63/packages/resolvers/default/src/DefaultResolver.js

default resolver implementation: https://github.com/parcel-bundler/parcel/blob/f65aa4c53ab130debfc88f4628eb001f52fb5f63/packages/utils/node-resolver-core/src/NodeResolver.js

**Comment by mischnic** [comment] 2020-05-12 21:01
Merging this into https://github.com/parcel-bundler/parcel/issues/202.

<br>

The original issue post and the most +1'ed comment say
> ~ should resolve to the package root (closest node_modules),

which is already the case in Parcel 2.

**Closed by mischnic** 2020-05-12 21:01 UTC
Labels: :bug: Bug, ✨ Parcel 2

**Comment by NicolasReibnitz** [comment] 2021-04-08 21:55
For me the probem were assets. I managed to resolve the issue by adding a symlink to the static folder.

Take this (simplified) structure for example:

```
├── src
│   └── project_1
│       └── en
│           └── index.html
└── static
    └── media
        └── video
            └── video.mp4
```
In index.html I had the option to do this:
```html
<source src="../../../static/media/videos/video.mp4" type="video/mp4" />
```
which I didn't like much. So I added a symlink to the static folder inside the `en` folder (which holds the index.html file).
Like so:
```bash
$ ln -sfn ../../../static static
```

Now the structure is:

```
├── src
│   └── project_1
│       └── en
│           ├── index.html
│           └── static -> ../../../static
└── static
    └── media
        └── video
            └── video.mp4
```

and I can use:

```html
<source src="~static/media/videos/video.mp4" type="video/mp4" />
```

Not ideal but a lot closer to the intended use of the ~. At least the way I initially understood it.

Note: the tilde isn't really necessary of course, but it reminds me of the special status of the symlinked `static` folder.

**Comment by mischnic** [comment] 2021-04-09 09:47
An alternative to that symlink is using `alias`.

Like the `local-module` entry here: https://v2.parceljs.org/features/module-resolution#aliases

In your case, `"alias": {"static": "./static"}` should work (in a package.json next to `src`)

**Comment by NicolasReibnitz** [comment] 2021-04-09 14:00
Oh! Gotta try that! That's of course a lot more elegant.

Thanks!

**Comment by warrenday** [comment] 2021-11-10 17:12
Was this issue resolved? If code is within `./src` I am now stuck needing to add the word `src` to all imports.

`import { Layout } from "~/src/components/Layout";`

It works but is kind of ugly.

**Comment by TimMensch** [comment] 2021-11-10 19:05
Needing to add `./src` was pretty much the _nature_ of the bug/missing feature.

It should take the root from the TypeScript config `paths` field. Not sure if they finally fixed this; due to this and a few other problems I had with Parcel I gave up and switched to `vite`: https://vitejs.dev/

With Vite it all works if you import the `vite-tsconfig-paths` plugin. Vite is also crazy faster than Parcel because it uses `esbuild`. But some TypeScript features aren't supported. YMMV.

**Comment by warrenday** [comment] 2021-11-11 08:55
Thanks I'll check out vite!
