### ISSUE TITLE
FontAwesome 5 and tree-shaking

### ISSUE THREAD

**Issue by robinvdvleuten** [parcel-bundler/parcel#1664] opened 2018-07-04 10:18 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "env"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    ["styled-components", {
      "displayName": true
    }],
    "polished"
  ]
}
```

## 🤔 Expected Behavior

I've followed the [latest instructions](https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking) for tree-shaking in the FontAwesome docs. So my icon component looks something like this;

```js
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArchive,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faEllipsisH,
  faPencil,
  faPlus,
  faSearchMinus,
  faSearchPlus,
  faTrash
} from '@fortawesome/pro-solid-svg-icons'
import styled from 'styled-components'

library.add(
  faArchive,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faEllipsisH,
  faPencil,
  faPlus,
  faSearchMinus,
  faSearchPlus,
  faTrash
)

const Icon = styled(FontAwesomeIcon)``

export default Icon
```

## 😯 Current Behavior

When I inspect the generated bundle with the analyzer, I see that FontAwesome takes most of the size. A further look into the minified output, I see a lot of references to icons I haven't imported. The command I run to build is `parcel build src/index.html --experimental-scope-hoisting`.

## 🔦 Context

The bundle size is very large as the FontAwesome pro import takes roughly 518kb. It would decrease significantly when shaken correctly.

## 💻 Code Sample

See above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 8.9.4
| npm/Yarn         | 1.6.0
| Operating System | MacOS 10.13.5

**Comment by buronnie** [comment] 2018-07-08 05:36
This issue is really strange. I notice that by enabling `--no-minify`, the tree shake works properly and get rid of unused icons away from the final package. But by default when we enable `minify`, the tree shake fails to shake unused icons. I try to figure out what's going on here, and below are my findings:

1. When enabling `minify`, we call `terser(this)` in `JSAsset.js`. 
2. In `shake.js`, the binding of unused icons are referenced (`binding.referenced === true`), so `isPure()` returns `false`. Therefore, tree shake does not remove the binding of those unused icons. If we comment out `terse(this)` in (1), the bindings are not referenced. So I believe `terser` must be the culprit. But I have no idea how it impacts. 

My other question is: do we even need to call `terser` in tree shake mode? Because at the end of `concat.js` we will minify the code anyway. @fathyb Do you have any thoughts 😄 ?

**Comment by fathyb** [comment] 2018-07-08 06:03
Good catch @buronnie, thanks! This wasn't intended and probably a merge error, I tested and FontAwesome icons should be trimmed with #1685

**Comment by buronnie** [comment] 2018-07-08 06:05
Thanks @fathyb for your fix 👍

**Comment by alflennik** [comment] 2019-03-19 13:47
Here is a minimal repro repo: https://github.com/alflennik/parcel-fontawesome-tree-shaking-repro

All you need to do to reproduce is import an icon and run build. It happens with default settings, any settings I tried.

**Comment by devongovett** [comment] 2019-05-06 04:27
This bug appears to be fixed in the current version of Parcel.

@alflennik your repo does not have the `--experimental-scope-hoisting` flag enabled, so tree shaking is not running. When I ran it with that flag, the build was 39kb instead of 1.38mb.

**Closed by devongovett** 2019-05-06 04:27 UTC
Labels: 🌳 Tree Shaking
