### ISSUE TITLE
Require statements with simple template literal does not get detected

### ISSUE THREAD

**Issue by wardpeet** [parcel-bundler/parcel#7368] opened 2021-11-26 13:48 UTC
# 🐛 bug report

Require statements with template literal does not get detected by Parcel. With regular quotes it does work.

```js
const x = require(`my-package`);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
}
```

## 🤔 Expected Behavior

It should detect the dependency and add it to the bundle.

## 😯 Current Behavior

Require statement stays untouched and thus cannot be found when running the code.

## 💁 Possible Solution

Converts template literals without any arguments inside of it to regular string

## 🔦 Context

Trying to bundle a library that has node_modules which contains require statements with template literals.

## 💻 Code Sample

```
/*
 * This module is a side-effect filled module to load in the proper logger.
 */

export const startLogger = () => {
  // if (!process.env.GATSBY_LOGGER) {
  //   if (
  //     semver.satisfies(process.version, `>=8`) &&
  //     !isCI() &&
  //     typeof jest === `undefined`
  //   ) {
  //     process.env.GATSBY_LOGGER = `ink`
  //   } else {
  //     process.env.GATSBY_LOGGER = `yurnalist`
  //   }
  // }
  // // if child process - use ipc logger
  // if (process.send && !process.env.GATSBY_WORKER_POOL_WORKER) {
  //   // FIXME: disable IPC logger when inside worker. IPC messages crash jest-worker.
  //   // This is just workaround to not crash process when reporter is used in worker context.
  //   // process.env.FORCE_COLOR = `0`
  //   // TODO move to dynamic imports
  //   require(`./loggers/ipc`).initializeIPCLogger()
  // }
  if (process.env.GATSBY_LOGGER.includes(`json`)) {
    // TODO move to dynamic imports
    require(`./logger/test.js`).initializeJSONLogger();
  } else if (process.env.GATSBY_LOGGER.includes(`yurnalist`)) {
    // TODO move to dynamic imports
    require(`./logger/test.js`).initializeYurnalistLogger();
  } else {
    // TODO move to dynamic imports
    require(`./logger/test.js`).initializeINKLogger();
  }
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.1
| Node             | 14.17.5
| npm/Yarn         | 1.22.5
| Operating System | Windows 10

**Comment by mischnic** [comment] 2021-11-26 14:25
Duplicate of https://github.com/parcel-bundler/parcel/issues/5492

**Closed as completed by mischnic** 2021-11-26 14:25 UTC

**Comment by wardpeet** [comment] 2021-11-26 15:41
Oh searched for it but couldn't find it. Thanks!
