### ISSUE TITLE
Error recovery from Sass errors

### ISSUE THREAD

**Issue by slavanga** [parcel-bundler/parcel#8003] opened 2022-04-24 15:03 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default"
}
```

Using `@parcel/transformer-sass` v2.5.0

## 🤔 Expected Behavior

1. Sass error shown on console
2. Error in Sass file fixed and saved
3. Parcel process keeps running and compiling Sass

## 😯 Current Behavior

Once a Sass error is shown on the console, the build process does not recover.
Fixing the error in the Sass file does not help. The parcel process has to be restarted.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.14.0
| npm | 8.7.0
| Operating System | Windows 10

**Comment by mischnic** [comment] 2022-04-24 15:13
Are you using @import/@use ? Do only errors in these imported files not go away or also the "root" Sass file that is imported from HTML/JS?

**Comment by slavanga** [comment] 2022-04-24 16:08
@mischnic that's right, errors in the "root" Sass file are recovered correctly. But errors in imported files result in the parcel process being stuck.

**Comment by mischnic** [comment] 2022-04-25 09:48
Duplicate of #7374, see https://github.com/parcel-bundler/parcel/issues/7374#issuecomment-1002948172

**Closed as completed by mischnic** 2022-04-25 09:48 UTC
