### ISSUE TITLE
Parcel always do transform async functions regardless .babelrc when targeting browser

### ISSUE THREAD

**Issue by hackwaly** [parcel-bundler/parcel#1214] opened 2018-04-18 12:54 UTC
```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "chrome": 66
        }
      }
    ]
  ]
}
```

I just want to keep async functions as-is to debug more conveniently.

**Comment by DeMoorJasper** [comment] 2018-04-18 13:09
Duplicate of #1207

**Closed by DeMoorJasper** 2018-04-18 13:09 UTC
Labels: :grey_question:  Question, :heavy_multiplication_x:  Duplicate

**Comment by TPReal** [comment] 2019-11-21 22:54
I see this and the duplicate is closed, but I somehow still cannot figure out what is the workaround even. Someone mentioned `.browserlistrc` with `last 1 Chrome version` but doesn't seem to work for me, I still get the errors. Is the only workaround to actually install all these babel things I'd rather forget about?
