### ISSUE TITLE
Parcel v2.beta2 server serves assets but does not serve sourcemap files

### ISSUE THREAD

**Issue by doomleika** [parcel-bundler/parcel#6023] opened 2021-03-19 08:16 UTC
# 🐛 bug report

As title.  stuff like `index.[hash].js.map` will not be served and will serve index file instead 

## 🤔 Expected Behavior

parcel dev server should serve all in file in `dist` folder

## 😯 Current Behavior

Parcel dev server will serve all the files except `*.map` files

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  v2..0.0.beta.2
| Node             | v14.16.0
| npm/Yarn         |  v.1.22.0
| Operating System |  Windows 10 20H2/WSL ubuntu 20.04

**Comment by katzmo** [comment] 2021-03-19 09:00
Sounds like beta.2 still has the same issue as beta.1 https://github.com/parcel-bundler/parcel/issues/5966?

**Comment by mischnic** [comment] 2021-03-19 10:04
Yeah, duplicate of https://github.com/parcel-bundler/parcel/issues/5966

**Closed as completed by mischnic** 2021-03-19 10:04 UTC
