### ISSUE TITLE
Parcel hot module reload doesn't work in a Chrome extension background script unless  you force the ports to be different.

### ISSUE THREAD

**Issue by ashleydavis** [parcel-bundler/parcel#7454] opened 2021-12-15 23:48 UTC
# 🐛 bug report

Parcel hot module reload doesn't work in a Chrome extension background script _unless_  you force the ports to be different.

## 🎛 Configuration 

Here's an example repo that demonstrates the problem:

https://github.com/optio-labs/chrome-ext-parcel-issue-example

In this repo you can run `npm start` and HMR works (because we use CLI args to force the ports to be different).

You can try both `npm run broken1` and `npm run broken2` to see how it is broken when the ports set to the same value or when the ports are left to their default values.

## 🤔 Expected Behavior

It would be nice if HMR worked automatically in the background script of a Chrome extension.

Note that I have followed the official instructions here and it doesn't result in an extension with working HMR in the background script:
https://parceljs.org/recipes/web-extension/

## 😯 Current Behavior

When you run `parcel src/manifest.json --host localhost` as specified in [the official instructions](https://parceljs.org/recipes/web-extension/) the background script in the Chrome extension loses it's connection to the HMR server with a message like this:

```
background.js:276 WebSocket connection to 'ws://localhost/' failed: 
kOvud @ background.js:276
background.js:327 undefined
ws.onerror @ background.js:327
background.js:330 [parcel] 🚨 Connection to the HMR server was lost
ws.onclose @ background.js:330
DevTools failed to load source map: Could not load content for chrome-extension://lknebadpahphkpibecckmamekepfncgd/background/background.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

## 💁 Possible Solution

My current workaround for this issue it set a separate dev server port and HMR port like this:

```bash
parcel src/manifest.json --host localhost --port 5000 --hmr-port 5001
```

This forces the HMR runtime to have the `HMR_PORT` variable set to 5001 and HMR works then.

The problem seems to that the `HMR_PORT` variable is set to `null` when the dev server port and the HMR port have the same values. This defaults the HMR runtime to using the port from `location`, but when running in a Chrome extension background script this yields an empty string! So the HMR runtime doesn't know which port to use and loses it connection.

## 🔦 Context

I just wanted to get HMR working in the background script for my Chrome extension.

## 💻 Code Sample

[
](https://github.com/optio-labs/chrome-ext-parcel-issue-example)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.1
| Node             |14.16.0
| npm/Yarn         |6.14.11
| Operating System |Windows 10

**Comment by zouloux** [comment] 2021-12-16 15:37
Same as #7150 ?

**Comment by ashleydavis** [comment] 2021-12-16 21:14
@zouloux it's possible the same issue yes, but I'm not certain.

**Comment by ashleydavis** [comment] 2021-12-16 21:15
If #7150 is fixed I'll be happy to revisit this issue and let you know if it is also fixed.

**Comment by zouloux** [comment] 2021-12-17 10:28
You can try to monkey patch this way.
Open `node_modules/@parcel/runtime-browser-hmr/lib/HMRRuntime.js`
Replace
```
        `var HMR_PORT = ${JSON.stringify(
          port != null &&
            // Default to the HTTP port in the browser, only override
            // in watch mode or if hmr port != serve port
            (!options.serveOptions || options.serveOptions.port !== port)
            ? port
            : null,
        )};`
```
with : 
```
    `var HMR_PORT = ${JSON.stringify(port)};`
```
If it works, we can be pretty confident that if #7150 is patched, it can patch this issue too.

**Comment by 101arrowz** [comment] 2022-03-24 05:51
The problem is that the default behavior (leaving it null when the serve and HMR are the same) is really useful for stuff like ngrok for normal web apps (I'm guessing that's why it's there in the first place). I would recommend `parcel watch` instead of `parcel serve` for web extensions; not only does it solve this problem, it's also probably a better solution since you don't really need to serve those files for web extensions.

**Comment by avalanche1** [comment] 2022-04-13 14:26
@devongovett @DeMoorJasper pls note, that this issue affects content scripts as well (not only background scripts):
<img width="654" alt="image" src="https://user-images.githubusercontent.com/10534563/163202760-29aaa8f6-ab9a-4ae4-b6f1-215253d09128.png">
setting hmr port explicitly in `parcel` command fixes it

**Comment by michaelschufi** [comment] 2022-04-16 15:31
BTW, the same is true for Firefox. I get
`Firefox can't establish a connection to the server at ws://localhost/`.

Firefox version 100.0 (Dev Edition)

Using it together with:
```
"@parcel/config-webextension": "^2.4.1",
"parcel": "^2.4.1",
"parcel-reporter-web-ext": "^0.3.2",
"web-ext": "^6.8.0"
```

**Comment by 101arrowz** [comment] 2022-04-16 18:52
Just use `parcel watch` instead of `parcel serve`. The conflict is because unlike normal webpages, chrome extensions are hosted on a static file protocol rather than HTTP. This issue cannot be solved without breaking HTTP proxies like Ngrok.

**Comment by michaelschufi** [comment] 2022-04-16 19:34
In that case at least the [docs](https://parceljs.org/recipes/web-extension/#hmr) and the examples should be updated accordingly.

**Comment by 101arrowz** [comment] 2022-04-16 19:39
A PR is already open: https://github.com/parcel-bundler/website/pull/1014

**Comment by 101arrowz** [comment] 2022-05-26 15:58
The documentation PR has been merged, so I think this issue is probably resolved just by following the instructions to use `parcel watch` over `parcel serve`.

**Closed as not planned by 101arrowz** 2022-05-26 15:58 UTC
Labels: HMR, Web Extensions

**Comment by avalanche1** [comment] 2022-06-08 19:05
@101arrowz the documentation doesnt state it explicitly, that `watch` should be used in place of `serve`. Only an example configuration is present, with no explanations as to _**why**_
