### ISSUE TITLE
Unmet peer dependency svgo 3 in optimizer-htmlnano

### ISSUE THREAD

**Issue by CxRes** [parcel-bundler/parcel#8948] opened 2023-04-18 12:57 UTC
It seems htmlnano 2.0.4 used by optimizer-htmlnano wants svgo ^3.0.2 as a peer dep. optimizer-htmlnano loads svgo 2.8.0 instead. Please update accordingly.

**Comment by mischnic** [comment] 2023-04-29 07:47
Looks like we'll have to restrict the version to <=2.0.3 though, upgrading svgo might break existing config files. https://github.com/svg/svgo/releases/tag/v3.0.0

**Comment by imbdb** [comment] 2023-05-17 06:18
Is there any workaround that I can do before this can be solved?

**Comment by munkacsimark** [comment] 2023-05-18 13:42
You can skip peer dependency check, but make sure everything is working correctly if you doing it. I encountered this using pnpm, here is the related documentation: https://pnpm.io/npmrc#strict-peer-dependencies

Put `strict-peer-dependencies=false` into `.npmrc` file.

**Comment by aiktb** [comment] 2023-11-05 13:59
`strict-peer-dependencies=false` doesn't work, add the following configuration to package.json:
```json
"pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "svgo": "2.8.0",
      }
    }
  },
```

**Comment by shallker** [comment] 2024-04-10 02:40
Another option is to tell `pnpm` to ignore `svgo@^3.0.2` in `package.json`

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "svgo@^3.0.2"
      ]
    }
  }
}
```

**Comment by Lazerbeak12345** [comment] 2024-07-10 23:32
related #9660 (the other issue may be a duplicate of this one)

**Closed as completed** 2024-11-04 05:18 UTC
