### ISSUE TITLE
Wrong detection of a sourcemap entry when it's just a string

### ISSUE THREAD

**Issue by Symbiatch** [parcel-bundler/parcel#3670] opened 2019-10-24 10:45 UTC
# 🐛 bug report

Parcel detects sourcemaps in JS files when they're inside JS code strings and aren't actually sourcemaps. 

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel 1.12.4, vue-notification 1.3.16, no configurations otherwise

## 🤔 Expected Behavior

Parcel correctly bundles the code included in vue-notification like Webpack etc do

## 😯 Current Behavior

vue-notification has the following line in dist/index.js (don't know if it's normal that Parcel loads a dist/js file instead of going to the source, this line is from some dependency of vue-notification):

`css += '\n/*# sourceMappingURL=data:application/json;base64,' + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'`

This causes Parcel to assume it's a sourcemap while it's actually just text inside a string in code that outputs sourcemaps. Error goes away if I break it up, for example

`css += '\n/*# sourceMap'+'pingURL=data:application/json;base64,' + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'`

error message:

> ‼  Could not load existing sourcemap of "../../node_modules/vue-notification/dist/index.js".
> ‼  Could not load existing sourcemap of "../../node_modules/vue-notification/dist/index.js".
> ×  ...\node_modules\vue-notification\dist\index.js:1070:83: Unterminated regular expression (1070:83)
>   1068 |     css += '\n/*# sourceURL=' + sourceMap.sources[0] + ' */'
>   1069 |     // http://stackoverflow.com/a/26603875
> > 1070 |                css += '\n + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + ' */'
>        |                                                                                                ^
>   1071 |   }
>   1072 |
>   1073 |   if (styleElement.styleSheet) {
> 

## 💻 Code Sample

import vue-notification in a project, run Parcel on it

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.6.0
| npm/Yarn         | npm 6.10.2
| Operating System | Windows 10 Pro

**Comment by DeMoorJasper** [comment] 2019-10-24 11:57
This has been fixed for Parcel 2, not entirely sure if we'll fix it for Parcel 1

**Comment by mischnic** [comment] 2019-10-24 14:23
(Duplicate of https://github.com/parcel-bundler/parcel/issues/2408)

**Closed by mischnic** 2019-10-24 14:23 UTC
Labels: :bug: Bug

**Comment by TimMensch** [comment] 2019-10-28 22:49
On this one -- is there a workaround for the time until Parcel 2 is released? I just ran into this in another project (@json-editor/json-editor) where Parcel is choking on a source map string.

I'd try bumping my project to Parcel 2, but there doesn't appear to be a Parcel 2 release available on `npm` yet?

**Comment by devongovett** [comment] 2019-10-29 02:35
@TimMensch it's under the `parcel` name instead of `parcel-bundler` now. `parcel@next` should install it for you.

**Comment by TimMensch** [comment] 2019-10-29 20:35
Great, thanks!
