### ISSUE TITLE
Unterminated regular expression (sourcemap)

### ISSUE THREAD

**Issue by Nisthar** [parcel-bundler/parcel#2795] opened 2019-03-14 17:12 UTC
# 🐛 bug report

I am trying to compile vue components using parcel. The build is not working correctly. I am getting the error mentioned below.

## 🎛 Configuration (.babelrc, package.json, cli command)
no configs

## 🤔 Expected Behavior

Build without any errors

## 😯 Current Behavior

Getting the following error

```
Could not load existing sourcemap of "../node_modules/vue-runtime-helpers/dist/inject-style/browser.js".
×  \node_modules\vue-runtime-helpers\dist\inject-style\browser.js:28:86: Unterminated regular expression (28:86)
  26 |       code += '\n/*# sourceURL=' + css.map.sources[0] + ' */'; // http://stackoverflow.com/a/26603875
  27 |
> 28 |       code += '\n + btoa(unescape(encodeURIComponent(JSON.stringify(css.map)))) + ' */';
     |                                                                                      ^
  29 |     }
  30 |
  31 |     if (!style.element) {
```

## 💁 Possible Solution
If i comment the code causing the error, it works without any problems. But it affects the source maps.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.2 (global mode)
| Node             |  v10.14.2
| npm/Yarn         |  v6.4.1
| Operating System | Windows 10

**Comment by mischnic** [comment] 2019-03-14 17:16
This is a known issue, duplicate of https://github.com/parcel-bundler/parcel/issues/2408

**Closed by mischnic** 2019-03-14 17:16 UTC

**Comment by Nisthar** [comment] 2019-03-14 17:18
@mischnic Is there a solution for this yet?

**Comment by mischnic** [comment] 2019-03-14 17:19
> Is there a solution for this yet?

That PR will solve this, I don't know of any workarounds apart from the one you mentioned already.

**Comment by Nisthar** [comment] 2019-03-14 17:26
@mischnic Thanks. It works without source maps. Hope you will fix the source map issues soon.

**Comment by arnoson** [comment] 2020-03-03 20:45
Is there any news on this? The same problem happens when using paper.js

**Comment by lastnigtic** [comment] 2020-04-02 03:49
same issue here
