### ISSUE TITLE
Dev server not working on multiple entries

### ISSUE THREAD

**Issue by pldg** [parcel-bundler/parcel#3236] opened 2019-07-15 00:07 UTC
# 🐛 bug report

## 🎛 Configuration

**package.json**

```js
{
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  },
  "scripts": {
    "dev": "parcel src/index.html src/about.html"
  }
}
```

## 🤔 Expected Behavior

`npm run dev` should spawn a live server at `http://localhost:1234`.

## 😯 Current Behavior

- `npm run dev`
- Parcel correctly build all development files inside `dist` folder
- The CLI say `Server running at http://localhost:1234`
- In the browser I see `No webpage was found for the web address: http://localhost:1234/`

## 🔦 Context

The same bug occur if using glob `parcel src/*.html`.

If I set only one entry `parcel src/index.html` the development server works fine.

Not sure if this is related to #2657.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm         | 6.10.1
| Operating System | Windows Subsystem For Linux

**Comment by mischnic** [comment] 2019-07-17 11:59
This is a duplicate of https://github.com/parcel-bundler/parcel/issues/1315

**Closed by mischnic** 2019-07-17 11:59 UTC
Labels: :bug: Bug
