### ISSUE TITLE
Target not found when providing "source"

### ISSUE THREAD

**Issue by stevenle** [parcel-bundler/parcel#6359] opened 2021-05-26 12:20 UTC
# 🐛 bug report

When adding `"source"` to a custom target, parcel seems to always throw an error that says cannot find target with that name. Removing the `"source"` config value fixes it.

I have an isolated example here:
https://github.com/stevenle/parcel-test

commands:

```
git clone https://github.com/stevenle/parcel-test
cd parcel-test
npm install
npm run build
```

Output:

![Screen Shot 2021-05-26 at 5 12 31 AM](https://user-images.githubusercontent.com/387282/119658323-dd1eb300-bde1-11eb-975a-2e1e78d6628c.jpg)

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json:

```js
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "browser": "dist/index.js",
  "module": "dist/index.esm.js",
  "app": "dist/app.js",
  "targets": {
    "browser": {
      "source": "src/browser/main.ts"
    },
    "app": {
      "source": "src/app/main.ts"
    }
  },
  "scripts": {
    "build": "parcel build --target app src/app/main.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel": "^2.0.0-beta.3.1"
  }
}
```

**Comment by mischnic** [comment] 2021-05-26 12:32
This is a bug, duplicate of https://github.com/parcel-bundler/parcel/issues/6199

**Closed as completed by mischnic** 2021-05-26 12:32 UTC
