### ISSUE TITLE
Something causes memory leak and excessive CPU usage

### ISSUE THREAD

**Issue by terry90** [parcel-bundler/parcel#5178] opened 2020-09-24 16:01 UTC
I started a small project today (with Parcel V2), after adding some code I noticed my VM was lagging as hell.
~~It seems the HMR is causing this.~~

~~When I use the option ` --no-hmr`  my app is compiling without trouble.~~

I think this is linked to #5002 

Reproduction repo: https://github.com/terry90/parcel-hmr-leak

Edit:
After writing more code, I felt my VM slow again.
More than 13Gb is allocated for parcel (no HMR).

`console: (node:5513) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 17 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit` is appearing for a very short time.

**Comment by mischnic** [comment] 2020-09-25 09:02
> my VM

I tried this on macOS 10.15 ("native"), ran `yarn start`, but don't experience any memory/CPU problems.

Which guest OS are you using and which VM software?

**Comment by terry90** [comment] 2020-09-25 11:47
I'm using Manjaro 20 on VMWare.
My IDE is VSCode.

**Comment by mischnic** [comment] 2020-10-19 21:40
Closing this as a duplicate of https://github.com/parcel-bundler/parcel/issues/5002

**Closed by mischnic** 2020-10-19 21:40 UTC
