### ISSUE TITLE
Build fails when compiling a module that includes a module web worker

### ISSUE THREAD

**Issue by kageurufu** [parcel-bundler/parcel#8182] opened 2022-06-01 23:10 UTC
# 🐛 bug report

When trying to `serve` a app that includes a Web Worker loaded with `{type: "module}`, the build fails

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
const worker = new Worker(new URL("./worker.js", import.meta.url), {
  type: "module",
});
```

## 🤔 Expected Behavior

Parcel should serve the webapp

## 😯 Current Behavior

```
yarn run parcel serve index.html
yarn run v1.22.18
warning package.json: No license field
$ C:\Users\kageu\Source\klippylyzer\repro\node_modules\.bin\parcel serve index.html
Server running at http://localhost:1234
🚨 Build failed.
[Error: ENOENT: no such file or directory, open 'C:\Users\kageu\Source\klippylyzer\repro\node_modules\@parcel\runtime-browser-hmr\lib\runtime-642ea7f16077a3d7.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\kageu\\Source\\klippylyzer\\repro\\node_modules\\@parcel\\runtime-browser-hmr\\lib\\runtime-642ea7f16077a3d7.js'
}
[Error: ENOENT: no such file or directory, open 'C:\Users\kageu\Source\klippylyzer\repro\node_modules\@parcel\runtime-browser-hmr\lib\runtime-642ea7f16077a3d7.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\kageu\\Source\\klippylyzer\\repro\\node_modules\\@parcel\\runtime-browser-hmr\\lib\\runtime-642ea7f16077a3d7.js
```

## 💻 Code Sample

Here is a full minimal reproduction

[repro.zip](https://github.com/parcel-bundler/parcel/files/8819282/repro.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0 |
| Node             | v18.0.0 |
| Yarn         | 1.22.18 |
| Operating System | Windows 11 |

**Comment by simoncoudeville** [comment] 2022-06-02 07:10
That looks a lot like my issue #8181

**Comment by mischnic** [comment] 2022-06-02 07:45
Duplicate of https://github.com/parcel-bundler/parcel/issues/8181

**Closed as not planned by mischnic** 2022-06-02 07:45 UTC

**Comment by kageurufu** [comment] 2022-06-02 22:06
I'm highly amused that I hit this issue, searched for it and found nothing, and then by the time I got around to writing a repro and issue it had just been reported.
