### ISSUE TITLE
CSS hot reloading stopped working between 2.0.0-rc.0 and 2.0.0

### ISSUE THREAD

**Issue by magnusdahlstrand** [parcel-bundler/parcel#7203] opened 2021-10-27 14:52 UTC
# 🐛 Bug report

Update: [This commit](https://github.com/parcel-bundler/parcel/commit/7468864f5ef8404309f4c681a2aa104d400cf5fc#diff-22c35695bb7c1fbe23a0513c385f1a5778516fcd2b740c170e9a884c4e9157fd), in particular the block starting around line 103, seems to cause the bug.

I have been using Parcel 2.0.0-rc.0 with postcss & react and automatic CSS stylesheet reloads have been working well until yesterday when I updated to version 2.0.0.

When I check messages on the HMR websocket connection rc.0 outputs two updates when I change a css file - one with type `js` and one with type `css`, version 2.0.0 only outputs one update, with type `js`.

I have [created a repository](https://github.com/magnusdahlstrand/parcel-2.0.0-bug-no-css-reload) that shows the issue. `main` branch is working (running `2.0.0-rc.0`), `broken` branch is not (`2.0.0`).

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```json
{
  "name": "parcel-2.0.0-bug-no-css-reload",
  "version": "0.0.1-dev",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "author": "Magnus Dahlstrand <magnus@slightly.limited> (https://slightly.limited/)",
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "^10.3.7",
    "parcel": "2.0.0-rc.0",
    "postcss": "^8.3.11"
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

.postcssrc:
```json
{
	"modules": true,
	"plugins": {
		"autoprefixer": {
			"grid": true
		}
	}
}
```
No other config.

## 🤔 Expected Behavior

When I have an active WS live reload connection and change CSS I expect the page to show changes as soon as they're built, like `2.0.0-rc.0` does.

## 😯 Current Behavior

Currently when changing CSS the changes are not sent as updates to the page. The exported CSS classes seem to come across, but no CSS content changes.

## 💁 Possible Solution

This seems to be the offending commit: https://github.com/parcel-bundler/parcel/commit/7468864f5ef8404309f4c681a2aa104d400cf5fc#diff-22c35695bb7c1fbe23a0513c385f1a5778516fcd2b740c170e9a884c4e9157fd

If I change [line 103 in the HMRServer.js file](https://github.com/parcel-bundler/parcel/blob/v2/packages/reporters/dev-server/src/HMRServer.js#L103) to say `if (false) {` automatic reloading of CSS works again. I'm sure this code is there for a reason and something else breaks when I do so, but CSS reload is back.

## 🔦 Context

Speedy development with frequent css changes.

## 💻 Code Sample

https://github.com/magnusdahlstrand/parcel-2.0.0-bug-no-css-reload

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0 & 2.0.0
| Node             | v16.6.1
| npm/Yarn         | 7.20.3
| Operating System | MacOS 10.14.6

**Comment by mischnic** [comment] 2021-10-28 19:16
Your analysis is correct. That code was added to fix HMR updates of files that import assets (e.g. `new URL(import.meta, "my-image.jpg")`)

Closing as duplicate of https://github.com/parcel-bundler/parcel/issues/7098

**Closed as completed by mischnic** 2021-10-28 19:16 UTC
