### ISSUE TITLE
Circular Dependency Issue

### ISSUE THREAD

**Issue by scrossan-crown** [parcel-bundler/parcel#1629] opened 2018-06-27 10:44 UTC
# 🐛 bug report

The issue I am having is when there are circular dependencies in my app and I am using `npx parcel index.html` command to run a dev server. The file is executed multiple times untill the maximum call stack size is exceeded.

```js
{
  "presets": ["env", "react"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

## 🤔 Expected Behavior

Parcel rebuilds the javascript and the file is only executed once

## 😯 Current Behavior

The file is executed multiple times untill the maximum call stack size is exceeded.

![image](https://user-images.githubusercontent.com/30405149/41969324-f4d8a372-79fe-11e8-9157-1f22df78471d.png)

## 🔦 Context

I am having to change the file structure of my app to avoid this issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.9.0
| Node             |  10.0.0
| npm/Yarn         | 6.1.0
| Operating System | Debian GNU/Linux 9 (stretch)

**Comment by DeMoorJasper** [comment] 2018-06-27 10:57
I think this bug has already been reported, but it's definitely something that needs to be fixed.

I'll leave this open as I'm not sure if this is a duplicate.

**Comment by scrossan-crown** [comment] 2018-06-27 11:40
Is there any idea on a time frame or is there a work around to not hot reload certain files  and then on page refresh it would reload the file?

**Comment by lili21** [comment] 2018-08-22 03:34
ran into this today. same issue.

**Comment by Penagwin** [comment] 2018-10-04 18:12
I ran into this today as well.

**Comment by brookback** [comment] 2018-10-25 09:19
I've got the same with Parcel 1.10.3 and with Typescript (external compile).

1. Run `tsc -w`
2. Run `parcel index.html`
3. Save .ts file in editor
4. Get error

```
build.06da9ca9.js:54 Uncaught RangeError: Maximum call stack size exceeded
    at localRequire (build.06da9ca9.js:54)
    at Object.parcelRequire.build/view/Header.js.react (Header.tsx:1)
    at newRequire (build.06da9ca9.js:49)
    at hmrAccept (index.tsx:7)
    at index.tsx:7
    at Array.some (<anonymous>)
    at hmrAccept (index.tsx:7)
    at index.tsx:7
    at Array.some (<anonymous>)
    at hmrAccept (index.tsx:7)
```

**Comment by droooney** [comment] 2018-10-31 13:41
Yep, same here. Circular dependency along with hot reload causes this issue.

**Comment by wjustice** [comment] 2018-11-02 19:01
Having the same issue.

**Comment by emadabdulrahim** [comment] 2018-11-21 02:05
Having the same issue here. Is there any workaround for now?

**Comment by mischnic** [comment] 2019-02-25 14:59
Duplicate of #1192

**Closed by mischnic** 2019-02-25 15:00 UTC
Labels: :bug: Bug, HMR
