### ISSUE TITLE
Emotion breaks build

### ISSUE THREAD

**Issue by mrignacio1231** [parcel-bundler/parcel#7867] opened 2022-03-26 12:31 UTC
# 🐛 bug report

When running in dev mode it works fine but when I try to build the process it fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "my-project",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "scripts": {
    "start": "parcel frontend/index.html",
    "build": "parcel build frontend/index.html --dist-dir static/dist"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.3.2",
    "parcel": "^2.3.2"
  },
  "dependencies": {
    "classnames": "^2.3.1",
    "http-proxy-middleware": "^2.0.4",
    "preact": "^10.6.6",
    "preact-router": "^4.0.1",
    "react-hook-form": "^7.28.1",
    "react-select": "^5.2.2",
    "react-select-async-paginate": "^0.6.1"
  },
  "alias": {
    "react": "preact/compat",
    "react-dom/test-utils": "preact/test-utils",
    "react-dom": "preact/compat",
    "react/jsx-runtime": "preact/jsx-runtime"
  }
}
```

## 🤔 Expected Behavior

It should work the same in production as in development

## 😯 Current Behavior

```shell
➜  npm run build

> build
> parcel build frontend/index.html --dist-dir static/dist

🚨 Build failed.

@parcel/core: node_modules/preact/compat/dist/compat.module.js does not export
'useInsertionEffect'

  /path/to/repo/node_modules/@emotion/react/dist/emotion-react.browser.esm.js:111:61
    110 |
  > 111 | '] ? React['useInsertion' + 'Effect'] : useLayoutEffect;
  >     |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    112 | var warnedAboutCssPropForGlobal = false; // maintain place over rerend
    113 | // initial render from browser, insertBefore context.sheet.tags[0] or

@parcel/core: node_modules/preact/compat/dist/compat.module.js does not export
'useInsertionEffect'

  /path/to/repo/node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:144:61
    143 |
  > 144 | '] ? React['useInsertion' + 'Effect'] : function useInsertionEffect(cr
  >     |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    145 |   create();
    146 | };
```

## 🔦 Context

I am trying to use `react-select` which depends on `Emotion` with `preact`. 

## 💻 Code Sample

```jsx
import { h, render, Component } from "preact";
import Select from "react-select";

const options = [
  { value: 1, label: "First" },
  { value: 2, label: "Second" },
];

class App extends Component {
  render() {
    return (
      <div>
        Example
        <Select options={options} />
      </div>
    );
  }
}

render(<App />, document.body);

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.2
| Node             | 16.14.2
| npm/Yarn         | 8.5.0
| Operating System | macOS Catalina

**Comment by Superoryco** [comment] 2022-04-10 06:20
What is your react and react-dom version? For me, update react-dom version to 18.0.0 fixed the problem (I was using react 18.0.0 and react-dom 17.0.2).

**Comment by krizka** [comment] 2022-05-14 20:22
Still not working with preact

**Comment by mischnic** [comment] 2022-08-22 12:26
Duplicate of https://github.com/parcel-bundler/parcel/issues/8407 (is newer but contains an explanation)

**Closed as not planned by mischnic** 2022-08-22 12:26 UTC
