### ISSUE TITLE
Heavy memory usage

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5072] opened 2020-08-25 21:20 UTC
# 🐛 bug report/question

Trying to import `ffmpeg.js` results in a process taking up 5GBs+ of RAM in a few seconds.
The imported file is 10mb so i can understand it taking up a lot of ram but that much ?

This is something that has been recurring over my projects, parcel processes taking up a lot of ram.
Do you guys have any plans on reducing the memory footprint ?

**Comment by DeMoorJasper** [comment] 2020-08-26 06:23
We're definitely working on addressing this, it's currently one of our top priorities together with stability

**Comment by download13** [comment] 2020-09-06 04:35
I've been able to mitigate this problem by passing `PARCEL_WORKERS=1` to it. It seems like the memory usage has something to do with how many worker threads it's trying to run. Maybe they're duplicating work?

**Comment by roman-petrov** [comment] 2020-09-12 06:39
I have (it seems) exactly the same issue with `ffmpeg.js` and `Parcel 1.12.4`: it runs out of memory when I import `ffmpeg` and start `parcel serve`. Is there any existing workaround, maybe some Parcel CLI arguments?

**Comment by Banou26** [comment] 2020-09-13 12:02
@roman-petrov You should try using Parcel 2 with the workaround literally on top of your comment.
> I've been able to mitigate this problem by passing PARCEL_WORKERS=1 to it.

**Comment by roman-petrov** [comment] 2020-09-13 13:51
@Banou26 , thank you. I will try to upgrade to Parcel 2  and use `PARCEL_WORKERS=1`

**Comment by aminya** [comment] 2021-01-09 03:55
I think Parcel should set the default number of Workers to 1 until the issue is fixed. Using workers is **SLOWER** than just 1 thread! 

Running Parcel on a laptop with a modern processor with 16 threads (AMD Ryzen 7 4800H) and 16GB of RAM:

First setting  the number of workers to 1, the build takes 618 ms.
```
❯ $env:PARCEL_WORKERS=1
❯ ( Measure-Command -Expression { npm run build }  ).Milliseconds
618
```

Then unsetting the number of workers, the build now takes 710 ms and I hit the #4628 issue. So there is no benefit in using the workers.
```
❯ $env:PARCEL_WORKERS=""
❯ ( Measure-Command -Expression { npm run build }  ).Milliseconds
console: (node:19400) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 17 error listeners added to [Socket]. Use emitter.set
MaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
console: (node:19400) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 17 close listeners added to [Socket]. Use emitter.set
MaxListeners() to increase limit
710
```

I haven't looked into the implementation, but if the workers are implemented using "processes", I have no doubt that they would be slower because each process starts a new Node process. If it uses WorkerThreads, then the overhead would be much less.

**Comment by mischnic** [comment] 2021-01-09 09:56
> if the workers are implemented using "processes"

They aren't. Node's WorkerThreads are used when available (you could set `PARCEL_WORKER_BACKEND=process` to force using processes).

Could you check what  https://github.com/parcel-bundler/parcel/blob/e183e32c811f066310fff0610aa856ca73a2fcb6/packages/core/workers/src/cpuCount.js#L49-L52 returns on your machine? That is used as the default `PARCEL_WORKERS` value on Windows.

I think we should cap that count to 4.

**Comment by mischnic** [comment] 2021-01-09 13:54
Also, could you test this with a bigger project (that takes something like 30s) to determine whether this is the overhead from starting the workers itself.

**Comment by aminya** [comment] 2021-01-09 18:36
> 
> Could you check what
> 
> https://github.com/parcel-bundler/parcel/blob/e183e32c811f066310fff0610aa856ca73a2fcb6/packages/core/workers/src/cpuCount.js#L49-L52
> 
> returns on your machine? That is used as the default `PARCEL_WORKERS` value on Windows.
> I think we should cap that count to 4.

It returns 16 which is correct, but I don't think you should spawn all the 16 threads due to its overhead. 

I need to do more testing, but it seems that more than 4 is destructive.

**Comment by mischnic** [comment] 2021-01-09 18:38
> It returns 16 which is correct

(It should return 8 because that function is supposed to determine the number of real cores and not threads.)

**Comment by aminya** [comment] 2021-01-09 19:02
> > It returns 16 which is correct
> 
> (It should return 8 because that function is supposed to determine the number of real cores and not threads.)

I fixed it in #5617

**Comment by devongovett** [comment] 2021-01-09 19:08
I don't think hard coding to 4 is a good idea. It doesn't make sense to me that there is a limit regardless of hardware. We currently base it on the number of available cores, which seems to make sense in regards to the amount of parallelism that is possible. If it slows down after a certain number, there must be a bottleneck somewhere that we can potentially solve. I had looked into this somewhat before but couldn't determine what the problem was. Maybe someone will have better luck.

**Comment by aminya** [comment] 2021-01-09 19:29
Running the benchmark using Parcel 2.0.0-nightly.520 gives another result. Using workers is slower altogether! No matter how many.

```
1 worker: 384ms
2 workers: 450ms
4 workers: 698ms
8 workers: 746ms
```
Ran on [solid-simple-table](https://github.com/aminya/solid-simple-table)


> I don't think hard coding to 4 is a good idea. It doesn't make sense to me that there is a limit regardless of hardware. We currently base it on the number of available cores, which seems to make sense in regards to the amount of parallelism that is possible. If it slows down after a certain number, there must be a bottleneck somewhere that we can potentially solve. I had looked into this somewhat before but couldn't determine what the problem was. Maybe someone will have better luck.

Parallelism is only helpful when the overhead is low. That's when parallelism can have performance benefits.
https://youtu.be/9hJkWwHDDxs?t=1080

**Comment by mischnic** [comment] 2021-01-09 19:35
In your 300ms example, no workers might be faster (btw you can also do `PARCEL_WORKERS=0` to actually use 0 workers).

But if you build takes more than a few seconds, it is beneficial.

**Comment by aminya** [comment] 2021-01-09 19:40
Sorry! I did a mistake in this benchmark. I thought `.Milliseconds` converts the whole time to milliseconds, but it just returns the milliseconds part (without seconds)! 😥 

I will run the benchmarks again

**Comment by aminya** [comment] 2021-01-09 21:40
OK, here is the correct benchmark. Still, increasing the number of workers has no effect.

<table>
<tr>
	<td>
		Worker number
	<td>
		Time (s)
<tr>
	<td> 0
	<td> 9.72
<tr>
	<td> 1
	<td> 10.63
<tr>
	<td> 2
	<td> 10.18	
<tr>
	<td> 4
	<td> 10.42
<tr>
	<td> 6
	<td> 10.37
<tr>
	<td> 8
	<td> 10.36
</table>

Ran on [solid-simple-table](https://github.com/aminya/solid-simple-table). The command was `npm run build` with `&& npm run style` deleted from the end.

**Comment by devongovett** [comment] 2021-01-09 22:01
Interesting. That indicates that there is some kind of bug to me. More workers definitely shouldn't be slower. Can you run with the `--profile` flag and upload the results? You can open the profile in Chrome dev tools to view the benchmark results yourself.

**Comment by aminya** [comment] 2021-01-09 22:16
Here is the profile:
[profile-20210109-161111.zip](https://github.com/parcel-bundler/parcel/files/5791916/profile-20210109-161111.zip)

![image](https://user-images.githubusercontent.com/16418197/104109677-0c4ee080-5296-11eb-9d5c-7956fa22e775.png)



BTW, the profiler seems to have issues in writing the files to the disk. I have to run the profiler a couple of times (with clean in between) to get one working. It exits with a crash code.
```
@parcel/core: Starting profiling...
/ Optimizing SimpleTable.js...
npm ERR! code 3221225477
```

**Comment by devongovett** [comment] 2021-01-09 22:41
Based on the profile I see a couple things:

1. Was this profile done without workers? I only see the "Master" thread.
2. It looks like a majority of the time (58%) was spent in cssnano, specifically loading (requiring) a preset. This seems extremely excessive to me. It seems it spent a ton of time waiting for I/O, as you can see based on the time spent in `open`, `lstat`, and `realpathSync`. Not sure what would explain that.

That said, one thing that could explain workers not being faster for some cases is if a majority of the build time is spent in minification of one large bundle, for example. This is not parallelizable, so we'd expect the times to be similar in this case. In your profile, transformation only accounts for 1.4s of the total build time, whereas minification accounts for 11s. During that time, only a single thread will be active.

**Comment by mischnic** [comment] 2021-01-09 22:44
Results I get with your project:

macOS (4 core i5), last number is wall time
```
PARCEL_WORKERS=0: 6.74s user, 0.72s system, 150% cpu, 4.948 total
PARCEL_WORKERS=1: 6.88s user, 0.72s system, 155% cpu, 4.893 total
PARCEL_WORKERS=2: 8.42s user, 1.04s system, 188% cpu, 5.011 total
PARCEL_WORKERS=3: 7.58s user, 0.95s system, 190% cpu, 4.467 total
PARCEL_WORKERS=4: 7.75s user, 0.98s system, 191% cpu, 4.571 total
```

Windows 10 (much older 4 core i5):
```
PARCEL_WORKERS=0: 6.78s
PARCEL_WORKERS=1: 6.56s
PARCEL_WORKERS=2: 6.78s
PARCEL_WORKERS=3: 6.68s
PARCEL_WORKERS=4: 6.82s
```
not sure why it's slower in your case. Tested with Yarn & pnpm on macOS and Yarn on Windows.

**Comment by aminya** [comment] 2021-01-09 22:47
> Based on the profile I see a couple things:
> 
> 1. Was this profile done without workers? I only see the "Master" thread.

No. The worker number was set to 8. 

> 2. It looks like a majority of the time (58%) was spent in cssnano, specifically loading (requiring) a preset. This seems extremely excessive to me. 

I have only one small less file! I am not sure what modification it is doing there!
https://github.com/aminya/solid-simple-table/blob/master/src/SimpleTable.less


> It seems it spent a ton of time waiting for I/O, as you can see based on the time spent in `open`, `lstat`, and `realpathSync`. Not sure what would explain that.
> 

Yes. The Disk IO seems the bottleneck here. It is irrelevant to the CPU.

**Comment by aminya** [comment] 2021-01-09 22:50
> not sure why it's slower in your case. Tested with Yarn & pnpm on macOS and Yarn on Windows.

I used Powershell for timing. Parcel itself reports almost 5 seconds less!
```
√ Built in 6.07s
```

**Comment by ranisalt** [comment] 2021-01-15 14:16
Just to add some extra data, on my Ryzen 7 4800H with 16 GB of RAM, running parcel@2.0.0-nightly.535 on node v15.6.0 takes:

- 1 worker: 50.56s, 1994M resident memory
- 2 workers: 33.80s, 1926M
- 3 workers: 30.80s, 2723M
- 4: 31.88s, 2915M
- 8: 34.88s, 4426M
- 16: fills up my RAM, proceeds to fill up my swap and annihilate my computer

I did the 3 workers test after testing with 2, 4 and 8 just to check for any potential sweet spot.

I noticed that rebuilding with a non-empty dist folder (that is, serve, kill, then serve again without cleaning) is slower: 35.56s, with 2383M resident memory. However, parcel memory usage is as inconsistent as it gets, so I attribute it to sheer luck.

**Comment by devongovett** [comment] 2021-01-15 15:14
One interesting thing we haven't explored yet is whether this is specific to worker threads or whether it also applies to processes. Is there a single memory limit across all threads or is it per thread? This could affect the frequency of garbage collection. Could people in this thread also run it with the `PARCEL_WORKER_BACKEND=process` environment variable and compare the results with different worker counts?

**Comment by ranisalt** [comment] 2021-01-15 16:45
@devongovett with 4 workers, using process backend, it takes 35.73s (albeit I have more software running simultaneously) but the resident memory usage dropped to 834M

**Comment by devongovett** [comment] 2021-01-15 16:54
Sure, it may be slower in the absolute sense than threads. I'm more interested in whether it still slows down as much after 4 workers as it does with threads.

**Comment by aminya** [comment] 2021-01-15 20:02
Even if you write lock-free parallel code, you should not always spawn all the threads. Parcel spawns all the threads even for small builds and that's why there is no speed benefit. As I showed before, the performance bottleneck is disk I/O and not CPU.

For example, The number of threads should be proportionate to the data size. For Parcel, a similar approach should be used.
https://github.com/atom-community/zadeh/blob/97548782ae3b7dac66a087ad5afdad9c8fb7e770/src/common.h#L74

**Comment by devongovett** [comment] 2021-01-15 20:21
I'm curious if you've tried setting the `UV_THREADPOOL_SIZE` environment variable. This adjusts the libuv (node) thread pool size which is what handles disk IO. By default it's 4. Is it possible that this is the bottleneck? More than 4 parcel workers might be bottlenecked by IO thread pool. Raising this may allow more parallel IO to occur.

**Comment by aminya** [comment] 2021-01-15 20:32
Here is a new profile I ran on [solid-simple-table](https://github.com/aminya/solid-simple-table/) with the #5642 patch applied (in which it changes one of realPathSyncs with an async version)

[profile-20210115-142429.zip](https://github.com/parcel-bundler/parcel/files/5822781/profile-20210115-142429.zip)

**Comment by mischnic** [comment] 2021-01-15 21:11
> This resolve preset is very suspicious. 3s to find a preset

That wasn't the case for me, neither macOS nor Windows.

**Comment by aminya** [comment] 2021-01-15 21:31
Another interesting result. Using pnpm or yarn makes a difference in the build time. I think this is because pnpm uses symlinks instead of copying the files.

<table>
<tr>
	<td> pnpm
	<td> yarn
<tr>
	<td> 10.5 s
	<td> 7 s
</table>

Here is the profile for yarn bootstrapped package.

[profile-20210115-152126.zip](https://github.com/parcel-bundler/parcel/files/5822975/profile-20210115-152126.zip)

This comment was for pnpm:
https://github.com/parcel-bundler/parcel/issues/5072#issuecomment-761182466

**Comment by mischnic** [comment] 2021-01-15 21:33
On Windows, we don't use Node's [`fs.readlpath.native`](https://nodejs.org/api/fs.html#fs_fs_realpath_native_path_options_callback) because it's apparently buggy on Windows.

**Comment by aminya** [comment] 2021-01-15 22:09
> > This resolve preset is very suspicious. 3s to find a preset
> 
> That wasn't the case for me, neither macOS nor Windows.

Well, building CSSNano using Parcel generates a 3.7 MB of JavaScript. Imagine how long it takes for Node to find all these files and load them. Producing a single file reduces this I/O load.

See my PR:
https://github.com/cssnano/cssnano/pull/985

**Comment by mischnic** [comment] 2021-01-15 22:17
Have you tried doing `require("cssnano")` wihtout Parcel in a JS script and timing the require call? To make sure this is due to Node on Windows and not caused by Parcel itself.

**Comment by aminya** [comment] 2021-01-15 22:21
> Have you tried doing `require("cssnano")` wihtout Parcel in a JS script and timing the require call? To make sure this is due to Node on Windows and not caused by Parcel itself.

Requiring cssnano itself is not an issue. This line is the slow part:
https://github.com/cssnano/cssnano/blob/40b82dca7f53ac02cd4fe62846dec79b898ccb49/packages/cssnano/src/index.js#L34

**Comment by aminya** [comment] 2021-01-15 23:32
Using [my cssnano PR here](https://github.com/cssnano/cssnano/pull/985/files/8248004c801d7370d79e5b4151353e522588dc98..946504ad999cd41403ad2353ef5aa76bc8df4308?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE0ODYxODkyNzE6MTY0MTgxOTc%3D) the build time speeds up 2 seconds!

**Comment by devongovett** [comment] 2021-01-17 14:27
@aminya have you looked into why disk access on your machine is so slow? I don't think anyone else has been able to reproduce the cssnano issue. Are you running off a network drive by chance?

**Comment by aminya** [comment] 2021-01-17 21:27
> @aminya have you looked into why disk access on your machine is so slow? I don't think anyone else has been able to reproduce the cssnano issue. Are you running off a network drive by chance?

My drive is a fast SSD with fast bandwidth. The issue is not my hardware. 

![image](https://user-images.githubusercontent.com/16418197/104856257-47c15e80-58d7-11eb-9081-c639ac75a920.png)

`require` is slow and the more you have it, the more it punishes the user. CSSNano requires many files and Parcel's decision not to limit `require` calls by making a single file out of this huge library makes things worse.
https://github.com/parcel-bundler/parcel/pull/5671#issuecomment-761820545

There is also the problem with not using `realpath.native` which makes some of the package managers like pnpm slower.

**Comment by devongovett** [comment] 2021-01-17 21:57
Sure, I agree re require being slow. But there still exists the question why it takes 3s on your machine and milliseconds on other machines so trying to get to the bottom of it...

**Comment by AndyOGo** [comment] 2022-02-14 13:29
@devongovett @mischnic 

Is there any update on this?
We observe high memory consumption too in contrast to parcel 1.

**Comment by mischnic** [comment] 2022-02-14 15:13
@AndyOGo Could you share more details about your situation (and ideally a reproduction)? Do you also have many cores like some of the other commenters above? Does setting `PARCEL_WORKERS=4 yarn parcel build`  help?

**Comment by Lazerbeak12345** [comment] 2022-02-24 18:48
can confirm **heavy** memory usage. A basic 200 line typescript file (32K in file-size according to `du`) that compiles in 2 seconds in tsc takes 15+ minutes and at least 4 GB Ram plus 8 GB swap. I've never once gotten parcel to compile this simple file as my computer all but crashes once all of its memory (swap plus hardware) becomes completely filled.

No special settings, config or anything. Exactly the getting-started demo, but with different typescript (typescript that tsc handles just fine). (Running fedora linux if that matters. I'm not using windows.)

(It's also really hard to kill. Spawns like 20-30 node processes. Note that my system is a meager 4 core Intel Core I5 mobile. Not some sorta threadripper. No reason to have that many workers for 200 lines of typescript on such low-grade hardware)

**Comment by mischnic** [comment] 2022-02-28 13:45
@Lazerbeak12345 Can you share your project (or some version of that typescript file which still causes this problem)?

**Comment by Lazerbeak12345** [comment] 2022-03-01 00:13
Sure https://github.com/Lazerbeak12345/pixelmanipulator/tree/v5-alpha is the closest thing - but you're going to have to remove these files (and replace them with the appropriate matching files from the getting started guide):

- `package.json`
- `yarn.lock`
- `tsconfig.json`
- `gulpfile.ts`

Another note is that you _might_ need to remove `src/demo` as recent changes to that branch have now included further typescript files that should not be included in the library build itself.

Sorry - I had actually planned on making a separate branch to recreate this easier, but I don't have much time on my hands these days.

Alternatively, as the typescript file is (currently) completely standalone, copying the content of `src/lib/pixelmanipulator.ts` into the demo project (with typescript adjustments) should recreate it just fine as well.

I suspect that this might not actually be easy to recreate without hardware as old as mine though (more-or-less factory Lenovo ThinkPad T420 but with a more-or-less factory Fedora Linux 35 WS).

**Comment by mischnic** [comment] 2022-03-01 08:46
Yeah, it works for me on macOS (also 4 core i5). But I'm also not sure if this is because I didn't modify your repo correctly or if it's actually caused by some hardware/OS difference.

**Comment by Lazerbeak12345** [comment] 2022-03-01 18:14
I'll make a branch with the specific changes made then and link it here. This might take some time.

**Comment by Lazerbeak12345** [comment] 2022-03-17 03:17
I'm actively working on this right now, and here's an interesting finding: If I provide `yarn parcel build` an entry point, this issue does not happen, but if i run it without (yet with entry points provided in the `package.json`) the issue still happens. I'll post further information later.

**Comment by mischnic** [comment] 2022-03-17 09:12
I'm guessing this is caused by a bad entry root/project root calculation then: https://github.com/parcel-bundler/parcel/blob/e294eafd9a49c056fb4b223c5ace5c0653428ede/packages/core/core/src/resolveOptions.js#L52-L53 (so that root is too high up in your FS and it does some unnecessary stuff then causing the memory usage)

Which should get fixed by https://github.com/parcel-bundler/parcel/pull/7537

**Comment by Lazerbeak12345** [comment] 2022-03-18 01:35
Alright, I've figured it out. (I actually solved it half an hour from my last post, but was offline so couldn't post this).

@mischnic Your hunch was correct.

Parcel seems to search for the "root" from `/` to `$(pwd)`, looking for a file to indicate what package manager to use when auto-installing things. The problem was because this file was present: `~/yarn.lock`. For my purposes, I don't need a lockfile of any sort in my `~` so I removed it, and since then, parcel has worked for me.

I don't really like that that was the problem - I expected parcel to use a depth-first search for the "root," as this is the behavior of `node` when searching for a package in a `node_modules` folder. (If `node_modules` isn't in the current folder or if the package is not present, try `../` until `../` is the same as `./`).

**Comment by Lazerbeak12345** [comment] 2022-03-18 01:45
It is also interesting to note, however, that while this is resolved for me - it still used a ton of threads and ran out of memory. 

This implies that parcel might fail on huge projects.

Running `parcel build` in such a large directory should still build (even if, as in my case, that wasn't the intended result). I suspect that each thread (or group of threads) is associated with one or more files. In the case of my light hardware, it'd be better to use a queue system and postpone files when the maximum threads have been reached.

Also unexpected, was that `--log-level verbose` didn't say what directory it believed the root to be. I learned that from an odd error message that I eventually triggered by accident. (this verbosity thing perhaps warrants its own issue, if one doesn't exist for it yet)

**Comment by jpcaparas** [comment] 2022-07-18 22:56
The `PARCEL_WORKERS=1` directive did wonders for me on my Macbook M1. I am currently running Parcel v1 and my machine would stutter to the point of being unusable whenever the `serve` process started bundling my changes.

**Comment by lorenzogrv** [comment] 2023-02-08 11:04
On our case, parcel was failing to build for ARM64 on a Graviton2 instance due to insane memory usage.

- We did not test the `PARCEL_WORKERS=1` workaround. We want parcel to do parallel work if it can
- We did not test the ` PARCEL_WORKER_BACKEND=process` mitigation
- Specifying the entry point within the build command (`parcel build src/index.html` instead of  `parcel build`) worked like a charm. It also builds way faster (about 50 seconds)

> NOTE: We had to disable image optimization as it's currently broken on ARM, but see #8790 and #7402

**Comment by lorenzogrv** [comment] 2023-02-10 14:44
We have again the problem with memory usage, even specifying the entry point.

We tried `PARCEL_WORKERS=1` without luck.

Still researching a workaround, can't build on arm64 (`aarch65`) natively now

**Comment by mischnic** [comment] 2023-02-10 15:48
Does really fail only on ARM64 and other archs build fine with lower memory usage?

**Comment by lorenzogrv** [comment] 2023-02-10 16:28
Our build works fine on `amd64`, abnormal memory usage happens under `arm64` (native build using an AWS EC2 Graviton2-based instance)

>

**Closed** 2023-10-09 23:27 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2, :bullettrain_side: Performance
