### ISSUE TITLE
Error when using Yarn PnP mode

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#4977] opened 2020-08-05 20:38 UTC
# 🐛 bug report

> `Error: @parcel/runtime-browser-hmr tried to access @babel/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

## 🎛 Configuration (.babelrc, package.json, cli command)

All defaults. Not even React or something, just Yarn 2, `yarn init`, installed Parcel 2.0.0-beta, added index.html.

## 🤔 Expected Behavior

No error :P

## 😯 Current Behavior

```
ℹ️ Server running at http://localhost:1234
console: (node:75178) [MODULE_NOT_FOUND] Error: @parcel/runtime-browser-hmr tried to access @babel/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
✨ Built in 6.16s
```

When adding React to the party, same error appears:

```
console: (node:75408) [MODULE_NOT_FOUND] Error: @parcel/runtime-react-refresh tried to access @babel/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

## 💁 Possible Solution

Add necessary dependencies in `@parcel/runtime-browser-hmr`'s and `@parcel/runtime-react-refresh`'s package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.5.0
| Yarn         | 2.1.1
| Operating System | Catalina

**Comment by mischnic** [comment] 2020-08-05 21:22
I think this is a duplicate of https://github.com/parcel-bundler/parcel/issues/4729?

> Add necessary dependencies in @parcel/runtime-browser-hmr's and @parcel/runtime-react-refresh's package.json

That would be more of a band-aid solution

**Comment by wojtekmaj** [comment] 2020-08-05 22:03
Looks like so - didn't find it because the error message changed 🤦 

Although this ticket mentions 1 more case.

**Comment by mischnic** [comment] 2020-08-06 08:06
> Although this ticket mentions 1 more case.

You mean the react refresh runtime? This applies to all runtimes.

Closing as duplicate

**Closed by mischnic** 2020-08-06 08:06 UTC
Labels: :clock1: Waiting
