### ISSUE TITLE
Wrong path to source files in sourcemap with --public-url Cli Parameter

### ISSUE THREAD

**Issue by duncansultan** [parcel-bundler/parcel#1832] opened 2018-08-01 15:14 UTC
# 🐛 bug report

### Project Structure

WebApp (Asp.net) /
├── _head.html
├── _head.js (import js files here)
├── dist/
│ ├── _head.html
│ ├── _head{randomsuffix}.css
│ ├── _head{randomsuffix}.js
│ └── _head{randomsuffix}.map
└── Views/
└── Shared/
└── _Layout.cshtml (reference ~/dist/_head.html)

```js
//Pacakage.json
{
	"scripts": {
		"build": "parcel build _head.html --public-url ./dist/",
	}
}
```

## 🤔 Expected Behavior

Build should use the correct path for the SourceMap.  `./dist/`

## 😯 Current Behavior

Build uses an invalid path for the SourceMap. `./dist/dist/`

If I build the file without the --public-url parameter, the SourceMap path is correct (although I have to manually adjust the html output file to include ./dist/ in the url).

```js
"build": "parcel build _head.html",
```

``` html
<link rel="stylesheet" href="dist/_head.8a9f9522.css"><script src="dist/_head.fc5e9d6c.js"></script>
```

In the JavaScript console.
`DevTools failed to parse SourceMap: https://localhost:44309/dist/dist/_head.496e4826.map`

## 💁 Possible Solution

Fix the path resolution when providing a `--public-url parameter`y.

## 🔦 Context

We are trying to integrate Parcel into an existing Asp.Net project.

Since razor is not a supported Asset we are trying to create a standalone HTML file that can be imported as a Partial view in the _Layout.cshtml file.

Also see issue #1180 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v8.11.3
| npm/Yarn         | 5.6.0 / 1.7.0
| Operating System | Windows 10
| IDE | Visual Studio 2017

**Comment by duncansultan** [comment] 2018-08-01 15:38
I installed Parcel globally (instead of just at the project level) and now the build works fine.  Would this still be considered a bug or is that expected behavior?

**Comment by DeMoorJasper** [comment] 2018-08-01 16:29
This is still considered a bug @duncansultan

**Comment by duncansultan** [comment] 2018-08-01 20:18
I'm able to successfully build JS and SourceMaps by changing the --public-url path from "./dist/" to "/dist/" (notice the "." prefix was removed).

`"parcel build _head.html --public-url /dist/",`

**Comment by DeMoorJasper** [comment] 2018-08-01 20:24
Ow than this is a duplicate of another issue, but this isn't a bug, as that's just how relative paths work

**Closed by DeMoorJasper** 2018-08-01 20:24 UTC
Labels: :bug: Bug
