### ISSUE TITLE
[Source maps] Parcel2 not creating source files, works fine in Parcel1 (reproducible)

### ISSUE THREAD

**Issue by jgentes** [parcel-bundler/parcel#6040] opened 2021-03-22 16:17 UTC
# 🐛 bug report

When running `yarn parcel src/index.html`, Parcel2 bundle does not include source files.

If I attempt to use `yarn parcel src/index.html --public-url ./`, all file requests result in a 404 (and not using `--public-url` works fine with Parcel 1).

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`
```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

The other configuration options can be viewed here:

Parcel2 (broken): https://github.com/jgentes/djseteditor/tree/parcel2
Parcel1 (working): https://github.com/jgentes/djseteditor/tree/parcel1

## 🤔 Expected Behavior

Parcel 2 should properly create source files, as Parcel 1 does:

![image](https://user-images.githubusercontent.com/1149470/112018300-abd8ec80-8aeb-11eb-8efd-214ea7caf61b.png)

And errors should be properly linked to source:

![image](https://user-images.githubusercontent.com/1149470/112018505-dc208b00-8aeb-11eb-8d31-6efc0d969ceb.png)

## 😯 Current Behavior

Source files are not created:

![image](https://user-images.githubusercontent.com/1149470/112020309-76cd9980-8aed-11eb-9dcf-147a60bc2216.png)

And errors point to the bundled file:

![image](https://user-images.githubusercontent.com/1149470/112020391-86e57900-8aed-11eb-8940-e3d46dfe7ed0.png)

Source map is created properly:

![image](https://user-images.githubusercontent.com/1149470/112020517-a54b7480-8aed-11eb-8948-f0fb6e214696.png)

But it cannot load because when the file is referenced (`http://localhost:1234/index.3fafb3e2.js.map`) it returns the `index.html` file.

## 💻 Code Sample

Feel free to fork these branches to reproduce the issue:

Parcel2 (broken): https://github.com/jgentes/djseteditor/tree/parcel2
Parcel1 (working): https://github.com/jgentes/djseteditor/tree/parcel1

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel               | 2.0.0-beta.2 |
| Node               |  12.20.2    |
| npm/Yarn         | 1.22.10
| OS                   | Windows 10 |
| IDE                 | VSCode |

**Comment by mischnic** [comment] 2021-03-22 16:18
Duplicate of #5966

**Closed as completed by mischnic** 2021-03-22 16:18 UTC
