### ISSUE TITLE
Less Inline Javascript is not enabled

### ISSUE THREAD

**Issue by XavierLeTohic** [parcel-bundler/parcel#1195] opened 2018-04-16 15:49 UTC
**Choose one:** is this a 🐛 bug

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-class-properties",
    "transform-decorators-legacy",
    ["import", { "libraryName": "antd", "style": true }]
  ]
}
```

### 🤔 Expected Behavior

We should be able to import Antd less file : 
```import 'antd/dist/antd.less'```

### 😯 Current Behavior

Build failed with error :  
```/node_modules/antd/dist/antd.less: Inline JavaScript is not enabled. Is it set in your options?```

I didn't find a way to provide this options using Parcel 😔

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 9.4.0
| npm/Yarn         | 5.7.1
| Operating System | OSX

**Comment by DeMoorJasper** [comment] 2018-04-17 11:41
This is a duplicate of #907, plz move discussion there

**Closed by DeMoorJasper** 2018-04-17 11:41 UTC
Labels: :grey_question:  Question
