### ISSUE TITLE
Need updates on dependencies for @parcel/transformer-mdx

### ISSUE THREAD

**Issue by sandro-pasquali** [parcel-bundler/parcel#9453] opened 2023-12-26 20:39 UTC
# 🐛 bug report

Hi!

It seems this package is out-of-sync with some peer dependencies.

```
// ❯ npm i parcel @parcel/transformer-mdx

npm ERR! Could not resolve dependency:
npm ERR! peer @mdx-js/react@"^1.6.22" from @parcel/transformer-mdx@2.10.3
npm ERR! node_modules/@parcel/transformer-mdx
npm ERR!   @parcel/transformer-mdx@"*" from the root project

```

`@mdx-js/react` is currently at `3.0.0`.

I think at least these two dependency versions need to be updated to `3.0.0`:

- https://github.com/parcel-bundler/parcel/blob/cf5e1293009fbbb812eca8bc607fee7906de2da3/packages/transformers/mdx/package.json#L23

- https://github.com/parcel-bundler/parcel/blob/cf5e1293009fbbb812eca8bc607fee7906de2da3/packages/transformers/mdx/package.json#L27

Thanks!

**Comment by mischnic** [comment] 2023-12-27 13:16
Duplicate of https://github.com/parcel-bundler/parcel/issues/7934

**Closed as not planned by mischnic** 2023-12-27 13:16 UTC

**Comment by TechQuery** [comment] 2024-02-11 13:27
You can use my plugin for MDX 3: https://github.com/EasyWebApp/Parcel-transformer-MDX
