### ISSUE TITLE
Parcel does not reload when file is saved

### ISSUE THREAD

**Issue by arthurvasconcelos** [parcel-bundler/parcel#1780] opened 2018-07-23 22:06 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.cli command
```sh
npm start
parcel src/index.html
```

.babelrc
```json
{
    "presets": [
        "env"
    ]
}
```

package.json
```js
{
  "name": "arthurvasconcelos.github.io",
  "version": "3.0.0",
  "description": ":metal: My personal site.",
  "main": "src/index.html",
  "scripts": {
    "start": "parcel src/index.html",
    "watch": "parcel watch src/index.html",
    "build": "parcel build src/index.html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/arthurvasconcelos/arthurvasconcelos.github.io.git"
  },
  "keywords": [
    "personal",
    "portifolio",
    "website"
  ],
  "author": "Arthur Vasconcelos <vasconcelos.arthur@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/arthurvasconcelos/arthurvasconcelos.github.io/issues"
  },
  "homepage": "https://github.com/arthurvasconcelos/arthurvasconcelos.github.io#readme",
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.1.0",
    "babel-preset-env": "^1.7.0",
    "node-sass": "^4.9.2",
    "parcel-bundler": "^1.9.7",
    "vue-template-compiler": "^2.5.16"
  }
}
```

## 🤔 Expected Behavior

It should reload the server when files are saved.

## 😯 Current Behavior

I have to stop and restart the server everytime I want to check my changes in the browser.

## 💻 Code Sample

src/index.html
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        <div id="app"></div>
        <script src="index.js"></script>
    </body>
</html>
```

src/index.js
```js
import Vue from 'vue';
import App from './components/App.vue';

new Vue({
    el: '#app',
    render: h => h(App)
});
```

src/components/App.vue
```vue
<template>
    <div id="app">
        <h1>{{ msg }}</h1>
        <div class="teste">testing <span class="bold">SCSS nest class</span></div>
    </div>
</template>

<script>
    export default {
        name: 'app',
        data () {
            return {
                msg: 'Hey Therea'
            }
        }
    }
</script>

<style lang="scss">
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    .teste {
        color: #323234;

        .bold {
            font-weight: bold;
            color: #f00;
        }
    }
</style>
```

Also this code in available in my repo [arthurvasconcelos/arthurvasconcelos.github.io](https://github.com/arthurvasconcelos/arthurvasconcelos.github.io)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v8.11.3
| npm/Yarn         | 5.6.0
| Operating System | Windows 10 Pro v. 1803 b. 17134.165

**Comment by DeMoorJasper** [comment] 2018-07-23 22:17
Thought the windows issues were resolved in the latest parcel version. 

Probably duplicate of #1743

**Closed by DeMoorJasper** 2018-07-23 22:17 UTC
Labels: :bug: Bug
