### ISSUE TITLE
Invalid TypeScript declaration files (.d.ts) emitted when mono-repo modules are being referred.

### ISSUE THREAD

**Issue by SayBGM** [parcel-bundler/parcel#7400] opened 2021-12-03 07:17 UTC
# 🐛 bug report
It seems Parcel fails to emit valid TypeScript declaration files (.d.ts) when the input source is importing any of its mono-repo related modules.

https://github.com/Mint-SayBGM/parcel-typescript-interface-error 

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json
```json
{
  "name": "root",
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/preset-env": "^7.16.0",
    "@parcel/packager-ts": "^2.0.1",
    "@parcel/transformer-typescript-types": "^2.0.1",
    "@parcel/config-default": "^2.0.1",
    "@parcel/transformer-typescript-tsc": "^2.0.1",
    "@swc/helpers": "^0.2.13",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "eslint": "^7.11.0",
    "eslint-plugin-react": "^7.26.1",
    "lerna": "^4.0.0",
    "parcel": "^2.0.1",
    "typescript": "^4.4.4"
  },
  "scripts": {
    "prepare": "lerna run prepare",
    "dev": "lerna run dev --stream",
    "build": "yarn & lerna run build --stream",
    "bootstrap": "lerna bootstrap --use-workspaces"
  },
  "workspaces": [
    "packages/*"
  ]
}

```
packages/sdk/package.json
```json
{
  "name": "@modules/sdk",
  "version": "0.0.1",
  "license": "ISC",
  "baseUrl": "./src",
  "types": "dist/index.d.ts",
  "main": "dist/index.js",
  "targets": {
    "main": {
      "optimize": true
    }
  },
  "scripts": {
    "prepublishOnly": "yarn build",
    "dev": "yarn build",
    "build": "yarn parcel build src/index.ts",
    "start": "yarn parcel src/index.ts"
  }
}
```
packages/types/package.json
```json
{
  "name": "@modules/types",
  "version": "1.0.0",
  "private": true,
  "description": "> TODO: description",
  "homepage": "",
  "license": "ISC",
  "types": "dist/index.d.ts",
  "main": "dist/index.js",
  "scripts": {
    "prepare": "yarn build",
    "build": "yarn parcel build index.ts"
  }
}
```

## 🤔 Expected Behavior
packages/sdk/dist/index.d.ts
```ts
import { AddressItem } from "@modules/types";
export const getZoneCode: (address: AddressItem) => Promise<string>;

//# sourceMappingURL=index.d.ts.map
```

## 😯 Current Behavior
packages/sdk/dist/index.d.ts
```ts
import { AddressItem as  } from "@modules/types";
export const getZoneCode: (address: AddressItem) => Promise<string>;

//# sourceMappingURL=index.d.ts.map
```

## 💁 Possible Solution
Note that I could not reproduce this behavior with TSC so seems like it’s somewhat relates to Parcel’s own build pipeline.
## 💻 Code Sample
https://github.com/Mint-SayBGM/parcel-typescript-interface-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.1
| Node             |  v14.18.2
| npm/Yarn         | yarn v1.22.17
| Operating System | Mac BigSur (11.4)
| typescript | ^4.4.4

**Comment by benpigchu** [comment] 2021-12-08 06:30
Maybe this is a duplicate of #7325 ?

**Comment by astegmaier** [comment] 2021-12-10 20:19
I think that #7426 _might_ fix this. However, in the repro steps above, show typescript `^4.4.4` as the dependency (which is somewhat ambiguous, because npm/yarn might install a higher version). @Mint-SayBGM - can you confirm the exact version of typescript that is installed when you get the repro? And see if downgrading to version `4.4.x` or earlier fixes the problem?

**Comment by benpigchu** [comment] 2021-12-13 08:34
@astegmaier In the yarn.lock from the code sample repo:

https://github.com/Mint-SayBGM/parcel-typescript-interface-error/blob/2c02afa69f121976c0a16fcddabe6107a3f63dd9/yarn.lock#L8616-L8619

The actual installed version of typescript should be 4.5.2

**Comment by SayBGM** [comment] 2021-12-13 09:06
I confirmed that downgrading the typescript version solved it.

Thanks so much! @benpigchu

**Closed as completed** 2021-12-21 07:15 UTC
Labels: :bug: Bug, TypeScript, ✨ Parcel 2
