### ISSUE TITLE
"cannot read property 'type' of undefined" on any change in an Elm project

### ISSUE THREAD

**Issue by magopian** [parcel-bundler/parcel#2778] opened 2019-03-12 20:11 UTC
# 🐛 bug report

On a fresh Elm project following the exact steps provided in the [documentation](https://parceljs.org/elm.html), any change to the index.js or Main.elm files results in an error.

## 🎛 Configuration

Here is the content of the package.json created by running `parcel index.html`:

```js
{
  "devDependencies": {
    "elm-hot": "^1.0.1",
    "node-elm-compiler": "^5.0.3"
  }
}
```

## 🤔 Expected Behavior

I expect the files to be rebuilt.

## 😯 Current Behavior

Instead of rebuilding, the following errors are logged:

```$ parcel index.html --log-level 4
[21:07:36]: Server running at http://localhost:1234 
[21:07:36]: Building...
[21:07:36]: Building index.html...
[21:07:37]: Building index.js...
[21:07:37]: Building Main.elm...
[21:07:39]: Built Main.elm...
[21:07:39]: Built index.js...
[21:07:39]: Built index.html...
[21:07:39]: Producing bundles...
[21:07:39]: Packaging...
[21:07:39]: Building hmr-runtime.js...
[21:07:39]: Built ../../../.npm-global/lib/node_modules/parcel-bundler/src/builtins/hmr-runtime.js...
[21:07:39]: ✨  Built in 2.88s.
[21:07:43]: Building...
[21:07:43]: Producing bundles...
[21:07:43]: 🚨  Cannot read property 'type' of undefined
[21:07:43]:     at Bundler.createBundleTree (/home/mathieu/.npm-global/lib/node_modules/parcel-bundler/src/Bundler.js:654:54)
    at Bundler.createBundleTree (/home/mathieu/.npm-global/lib/node_modules/parcel-bundler/src/Bundler.js:721:12)
    at Bundler.createBundleTree (/home/mathieu/.npm-global/lib/node_modules/parcel-bundler/src/Bundler.js:721:12)
    at Bundler.bundle (/home/mathieu/.npm-global/lib/node_modules/parcel-bundler/src/Bundler.js:298:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## 💻 Code Sample

The code is the exact same content as shown in the [documentation](https://parceljs.org/elm.html), no more, no less.

## 🌍 Your Environment

I've tried with parcel 1.12.0 and the issue was the same.

I also tried with 1.11.0 and in that case it sometimes doesn't rebuild either, but at least it's not spewing out those errors. I didn't manage to understand why it would sometimes not detect the changes and rebuild at all, it seems to be a random bug.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.1 |
| Node             | v8.10.0 |
| npm        | 6.8.0 |
| Operating System | Linux Mint 19.1 Tessa |
| elm | 0.19.0 |

**Comment by llorenspujol** [comment] 2019-03-25 12:32
duplicate of https://github.com/parcel-bundler/parcel/issues/2749

**Comment by domenkozar** [comment] 2019-04-05 04:48
Can be closed, I also hit it and it's indeed a duplicate

**Closed** 2019-04-05 07:19 UTC
Labels: :bug: Bug
