### ISSUE TITLE
Incompatible with typescript v4

### ISSUE THREAD

**Issue by deebov** [parcel-bundler/parcel#5997] opened 2021-03-15 07:47 UTC
# 🐛 bug report

Cannot build a project that uses typescript v4

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/28673719/111119505-0920eb00-858c-11eb-8480-0dde837b899a.png)

## 🔦 Context

We're trying to add parcel to our react component library. It not a monorepo. We have all our components under `packages/` and want to bundle everything in root directory.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.626
| @parcel/transformer-typescript-tsc | ^2.0.0-nightly.628
| @parcel/transformer-typescript-types | 2.0.0-nightly.628
| Node             | v12.20.1
| Yarn         | 1.22.10
| Operating System | macOS 11.1

**Comment by mischnic** [comment] 2021-03-15 09:18
Duplicate of #5978

**Closed by mischnic** 2021-03-15 09:18 UTC
Labels: :raising_hand_woman: Feature, ✨ Parcel 2, 🔌 Parcel 2 Plugins
