### ISSUE TITLE
HTML bundles must only contain one asset

### ISSUE THREAD

**Issue by edenprojectde** [parcel-bundler/parcel#3875] opened 2019-12-05 03:54 UTC
# ❔ Question

Has there been any changes to parcel from 1->2 which disable usage of different kind of file extensions in one file?
Maybe somebody know what exactly this message wants to tell me so i can change it? unsure if this is a bug or just me. 

## 🔦 Context

My Project uses pug and ES6 imports.
I would get you more info but "--log-level verbose" gives me the same error using this:
`parcel index.pug --log-level verbose`

V1 compiled fine, i changed to V2 to get ES6 imports working because `script(defer='', type="module", src='/js/main.js')` seem to not be loaded correctly in broswer because of pracelRequire.

I tried streamlining so i only use one kind of asset per type (sass => scss for ex.) didnt change the error for me.

## 💻 Code Sample

```
ben@EdenTheFourthVII:~/Projekte/Kunde/Heimatvoll/Server2/frontend$ parcel index.pug 
Server running at http://localhost:1234
🚨 @parcel/packager-html: HTML bundles must only contain one asset
AssertionError [ERR_ASSERTION]: HTML bundles must only contain one asset
    at Object.package (/home/ben/.nvm/versions/node/v12.10.0/lib/node_modules/parcel/node_modules/@parcel/packager-html/lib/H
TMLPackager.js:34:21)
    at PackagerRunner.package (/home/ben/.nvm/versions/node/v12.10.0/lib/node_modules/parcel/node_modules/@parcel/core/lib/Pa
ckagerRunner.js:214:36)
    at async PackagerRunner.getBundleResult (/home/ben/.nvm/versions/node/v12.10.0/lib/node_modules/parcel/node_modules/@parc
el/core/lib/PackagerRunner.js:182:20)
    at async PackagerRunner.packageAndWriteBundle (/home/ben/.nvm/versions/node/v12.10.0/lib/node_modules/parcel/node_modules
/@parcel/core/lib/PackagerRunner.js:151:9)
    at async Child.handleRequest (/home/ben/.nvm/versions/node/v12.10.0/lib/node_modules/parcel/node_modules/@parcel/workers/
lib/child.js:162:9)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 12.10.0
| npm/Yarn         | npm@6.10.3
| Operating System | KDE Neon (User:18)

**Comment by mischnic** [comment] 2019-12-05 16:49
Can you post your complete pug file?

**Comment by edenprojectde** [comment] 2019-12-06 02:12
layout/index.pug (default layout)
```meta(charset='utf-8')
meta(name="viewport" content="width=device-width, initial-scale=1")
meta(http-equiv='X-UA-Compatible', content='IE=edge')
link(rel='manifest' href='manifest.webmanifest')
title Heimatvoll
link(rel='preload', href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css' as="stylesheet")
link(rel='stylesheet', href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css')
link(rel='stylesheet', href='/css/main.sass')
link(href='https://fonts.googleapis.com/css?family=Open+Sans', rel='stylesheet')
link(rel='icon', type='image/png', sizes='32x32', href='./img/icons/icon-ldpi.png')
script(defer='',src='/js/localforage.js')
script(defer='', type="module", src='/js/main.js')
base(href="/")
- var ssr = rendering=="ssr"
- var mobile = !!!mobile
- var debug = false
if !ssr
    script(defer='', type="module", src='/js/router.js')```
index.pug
```
extends ./layout/index.pug

block content
  if !ssr
    #newest.container(limit="6")

  section.section
    if ssr
      #newest.container!=newest

    br
    .container
      if ssr
        #categories(start="0", columnwidth="4", limit="9")!=categories
      else 
        #categories(start="0", columnwidth="4", limit="9")
```

**Comment by mischnic** [comment] 2019-12-07 17:16
Please provide a full reproduction

**Comment by edenprojectde** [comment] 2019-12-09 09:25
Can you specify what a complete reproduction is?

**Comment by mischnic** [comment] 2019-12-09 10:12
All files that are needed to make Parcel throw the error you specified.

In this case, using the files you posted results in an error by pug, because there is no `block content` in layout/index.pug. After resolving that, Parcel build successfully.

**Comment by edenprojectde** [comment] 2019-12-09 16:42
[frontend.zip](https://github.com/parcel-bundler/parcel/files/3940789/frontend.zip)
Here is a Snapshot of the current frontend

**Comment by mischnic** [comment] 2020-01-28 22:17
Interesting, I think this is somehow caused by the circluar dependency from index.pug to navbar to index.pug.

Minimal example:
```pug
//- index.pug
html
  body
    include nav-top.pug
    div(style="min-height:60px;")

//- nav-top.pug
a.navbar-item(href="/index.pug")
  b Startseite
```

Bundle Graph:
![BundleGraph](https://user-images.githubusercontent.com/4586894/73310286-49a49480-4224-11ea-8cfa-2bb57fd15a15.png)

**Comment by andrei-dumitrescu** [comment] 2020-04-09 09:18
I'm getting the same error with the default scenario:

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="./index.css" />
  </head>
  <body>
    <div id="react-root"></div>
    <script src="./index.jsx"></script>
  </body>
</html>
```

If I remove the css from `index.html` and import it in `index.jsx` with `import "./index.css"`, it works as intended.

## Env

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 12.13.1
| npm/Yarn         | npm@6.14.2
| Operating System | Arch Linux x86_64

**Comment by jelleklaver** [comment] 2021-03-31 16:17
We stumbled upon the same `AssertionError [ERR_ASSERTION]: HTML bundles must only contain one asset` and found that I imported `.svg.html` files, which was a [workaround](https://github.com/parcel-bundler/parcel/issues/1622#issuecomment-460037698) for parcel 1 and doesn't work for parcel 2 anymore.

I ended up using the `@parcel/transformer-inline-string` to import `*.svg` files as string to be able to inline them.

**Comment by drachehavoc** [comment] 2021-06-19 23:33
# same issue here...

### package.json
```json
{
  "name": "client-example",
  "version": "0.0.1",
  "description": "",
  "scripts": {
    "build": "parcel build ./src/index.html --dist-dir ./dist",
    "dev": "parcel ./src/index.html --dist-dir ./dist-dev",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Varela",
  "license": "Apache-2.0",
  "devDependencies": {
    "@parcel/transformer-inline-string": "^2.0.0-beta.2",
    "@parcel/transformer-sass": "^2.0.0-beta.2",
    "parcel": "^2.0.0-beta.2"
  }
}
```

----

### run command:
```bash
npm run dev
```

----

### ./src/index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <script src="./main.js"></script>
</body>
</html>
```

----

### ./src/main.js
```javascript
import otherHTML from "./other.html"
```
----
### ./src/other.html
```html
<div>no no no no no</div>
```
----

### Error:
```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/packager-html: HTML bundles must only contain one asset
AssertionError [ERR_ASSERTION]: HTML bundles must only contain one asset
    at Object.package (/home/varela/Caldo-de-Code/.../node_modules/@parcel/packager-html/lib/HTMLPackager.js:85:23)
    at PackagerRunner.package (/home/varela/Caldo-de-Code/.../node_modules/@parcel/core/lib/PackagerRunner.js:365:27)
    at async PackagerRunner.getBundleResult (/home/varela/Caldo-de-Code/.../node_modules/@parcel/core/lib/PackagerRunner.js:326:20)
    at async PackagerRunner.getBundleInfo (/home/varela/Caldo-de-Code/.../node_modules/@parcel/core/lib/PackagerRunner.js:318:9)
    at async Child.handleRequest (/home/varela/Caldo-de-Code/.../node_modules/@parcel/workers/lib/child.js:255:9)

```

-----
### Env
| Software                     | Version(s)                             |
| ------------------------------|----------------------------------------|
| Parcel                        | 2.0.0-beta.2                        |
| Node                          | v14.17.0                               |
| npm/Yarn                      | npm7.18.1                             |
| Operating  System             | Fedora 34 (Thirty Four) x86_64                      |

**Comment by devongovett** [comment] 2021-06-20 01:43
What are you expecting to happen when importing an HTML file into JS?

**Comment by drachehavoc** [comment] 2021-06-20 04:52
In the previous version of parcel, it returns parsed HTML as a string, I expected the same in Parcel 2. Am I wrong?

**Comment by drachehavoc** [comment] 2021-06-20 05:31
I just revert to version 1.12.3 and made the test below:

---
### ./src/index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <script src="./main.js"></script>
</body>
</html>
```

---
### ./src/main.js
```javascript
import otherHTML from "./other.html"
console.log(otherHTML)
```

---
### ./src/other.html
```html
<link rel="stylesheet" href="./x.scss">
<div>no no no no no</div>
```

---
### ./src/x.scss
```scss
div {
    background-color: red;
}
```
---
### RESULT:: console.log prints
```html
<link rel="stylesheet" href="/x.3e5b4745.css">
<script src="/x.3e5b4745.js"></script><div>no no no no no</div>
```

**Comment by devongovett** [comment] 2021-06-20 06:12
I don't get this error in the latest nightly, but it also doesn't do what you want. In Parcel 2, you can use the `bundle-text:` prefix on an import to inline the contents of a bundle into your JavaScript rather than creating a separate file.

```js
import otherHTML from 'bundle-text:./other.html';
```

However, a bug was preventing this from working. I've opened a PR to fix it. #6486

**Comment by drachehavoc** [comment] 2021-06-20 07:15
Using the prefix `blundle-text:` in `Parcel 2.0.0-beta.2`  I got this strange HTML:

```html
<link rel="stylesheet" href="/index.d1a4d2be.css">
<div>no no no no no</div><script src="// modules are defined as an array
// [ module function, map of requires ]
//
// map of requires is short require name -> numeric require
//
// anything defined in a previous bundle is accessed via the
// orig method which is the require for previous bundles

(function(modules, entry, mainEntry, parcelRequireName, globalName) {
  /* eslint-disable no-undef */
  var globalObject =
    typeof globalThis !== 'undefined'
      ? globalThis
      : typeof self !== 'undefined'
      ? self
      : typeof window !== 'undefined'
      ? window
      : typeof global !== 'undefined'
      ? global
      : {};
  /* eslint-enable no-undef */

  // Save the require from previous bundle to this closure if any
  var previousRequire =
    typeof globalObject[parcelRequireName] === 'function' &&
    globalObject[parcelRequireName];

  var cache = previousRequire.cache || {};
  // Do not use `require` to prevent Webpack from trying to bundle this call
  var nodeRequire =
    typeof module !== 'undefined' &&
    typeof module.require === 'function' &&
    module.require.bind(module);

  function newRequire(name, jumped) {
    if (!cache[name]) {
      if (!modules[name]) {
        // if we cannot find the module within our internal map or
        // cache jump to the current global require ie. the last bundle
        // that was added to the page.
        var currentRequire =
          typeof globalObject[parcelRequireName] === 'function' &&
          globalObject[parcelRequireName];
        if (!jumped && currentRequire) {
          return currentRequire(name, true);
        }

        // If there are other bundles on this page the require from the
        // previous one is saved to 'previousRequire'. Repeat this as
        // many times as there are bundles until the module is found or
        // we exhaust the require chain.
        if (previousRequire) {
          return previousRequire(name, true);
        }

        // Try the node require function if it exists.
        if (nodeRequire && typeof name === 'string') {
          return nodeRequire(name);
        }

        var err = new Error("Cannot find module '" + name + "'");
        err.code = 'MODULE_NOT_FOUND';
        throw err;
      }

      localRequire.resolve = resolve;
      localRequire.cache = {};

      var module = (cache[name] = new newRequire.Module(name));

      modules[name][0].call(
        module.exports,
        localRequire,
        module,
        module.exports,
        this
      );
    }

    return cache[name].exports;

    function localRequire(x) {
      return newRequire(localRequire.resolve(x));
    }

    function resolve(x) {
      return modules[name][1][x] || x;
    }
  }

  function Module(moduleName) {
    this.id = moduleName;
    this.bundle = newRequire;
    this.exports = {};
  }

  newRequire.isParcelRequire = true;
  newRequire.Module = Module;
  newRequire.modules = modules;
  newRequire.cache = cache;
  newRequire.parent = previousRequire;
  newRequire.register = function(id, exports) {
    modules[id] = [
      function(require, module) {
        module.exports = exports;
      },
      {},
    ];
  };

  Object.defineProperty(newRequire, 'root', {
    get: function() {
      return globalObject[parcelRequireName];
    },
  });

  globalObject[parcelRequireName] = newRequire;

  for (var i = 0; i < entry.length; i++) {
    newRequire(entry[i]);
  }

  if (mainEntry) {
    // Expose entry point to Node, AMD or browser globals
    // Based on https://github.com/ForbesLindesay/umd/blob/master/template.js
    var mainExports = newRequire(mainEntry);

    // CommonJS
    if (typeof exports === 'object' && typeof module !== 'undefined') {
      module.exports = mainExports;

      // RequireJS
    } else if (typeof define === 'function' && define.amd) {
      define(function() {
        return mainExports;
      });

      // <script>
    } else if (globalName) {
      this[globalName] = mainExports;
    }
  }
})({"6Suh7":[function(require,module,exports) {
var HMR_HOST = null;
var HMR_PORT = 1234;
var HMR_SECURE = false;
var HMR_ENV_HASH = "d751713988987e9331980363e24189ce";
module.bundle.HMR_BUNDLE_ID = "e0f09344d75dccacf80342bf53600df1";
// @flow
/*global HMR_HOST, HMR_PORT, HMR_ENV_HASH, HMR_SECURE*/
/*::
import type {
HMRAsset,
HMRMessage,
} from '@parcel/reporter-dev-server/src/HMRServer.js';
interface ParcelRequire {
(string): mixed;
cache: {|[string]: ParcelModule|};
hotData: mixed;
Module: any;
parent: ?ParcelRequire;
isParcelRequire: true;
modules: {|[string]: [Function, {|[string]: string|}]|};
HMR_BUNDLE_ID: string;
root: ParcelRequire;
}
interface ParcelModule {
hot: {|
data: mixed,
accept(cb: (Function) => void): void,
dispose(cb: (mixed) => void): void,
// accept(deps: Array<string> | string, cb: (Function) => void): void,
// decline(): void,
_acceptCallbacks: Array<(Function) => void>,
_disposeCallbacks: Array<(mixed) => void>,
|};
}
declare var module: {bundle: ParcelRequire, ...};
declare var HMR_HOST: string;
declare var HMR_PORT: string;
declare var HMR_ENV_HASH: string;
declare var HMR_SECURE: boolean;
*/
var OVERLAY_ID = '__parcel__error__overlay__';
var OldModule = module.bundle.Module;
function Module(moduleName) {
  OldModule.call(this, moduleName);
  this.hot = {
    data: module.bundle.hotData,
    _acceptCallbacks: [],
    _disposeCallbacks: [],
    accept: function (fn) {
      this._acceptCallbacks.push(fn || (function () {}));
    },
    dispose: function (fn) {
      this._disposeCallbacks.push(fn);
    }
  };
  module.bundle.hotData = undefined;
}
module.bundle.Module = Module;
var checkedAssets, /*: {|[string]: boolean|}*/
acceptedAssets, /*: {|[string]: boolean|}*/
/*: {|[string]: boolean|}*/
assetsToAccept;
function getHostname() {
  return HMR_HOST || (location.protocol.indexOf('http') === 0 ? location.hostname : 'localhost');
}
function getPort() {
  return HMR_PORT || location.port;
}
// eslint-disable-next-line no-redeclare
var parent = module.bundle.parent;
if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
  var hostname = getHostname();
  var port = getPort();
  var protocol = HMR_SECURE || location.protocol == 'https:' && !(/localhost|127.0.0.1|0.0.0.0/).test(hostname) ? 'wss' : 'ws';
  var ws = new WebSocket(protocol + '://' + hostname + (port ? ':' + port : '') + '/');
  // $FlowFixMe
  ws.onmessage = function (event) /*: {data: string, ...}*/
  {
    checkedAssets = {
      /*: {|[string]: boolean|}*/
    };
    acceptedAssets = {
      /*: {|[string]: boolean|}*/
    };
    assetsToAccept = [];
    var data = /*: HMRMessage*/
    JSON.parse(event.data);
    if (data.type === 'update') {
      // Remove error overlay if there is one
      removeErrorOverlay();
      let assets = data.assets.filter(asset => asset.envHash === HMR_ENV_HASH);
      // Handle HMR Update
      var handled = false;
      assets.forEach(asset => {
        var didAccept = asset.type === 'css' || asset.type === 'js' && hmrAcceptCheck(module.bundle.root, asset.id, asset.depsByBundle);
        if (didAccept) {
          handled = true;
        }
      });
      if (handled) {
        console.clear();
        assets.forEach(function (asset) {
          hmrApply(module.bundle.root, asset);
        });
        for (var i = 0; i < assetsToAccept.length; i++) {
          var id = assetsToAccept[i][1];
          if (!acceptedAssets[id]) {
            hmrAcceptRun(assetsToAccept[i][0], id);
          }
        }
      } else {
        window.location.reload();
      }
    }
    if (data.type === 'error') {
      // Log parcel errors to console
      for (let ansiDiagnostic of data.diagnostics.ansi) {
        let stack = ansiDiagnostic.codeframe ? ansiDiagnostic.codeframe : ansiDiagnostic.stack;
        console.error('🚨 [parcel]: ' + ansiDiagnostic.message + '\n' + stack + '\n\n' + ansiDiagnostic.hints.join('\n'));
      }
      // Render the fancy html overlay
      removeErrorOverlay();
      var overlay = createErrorOverlay(data.diagnostics.html);
      // $FlowFixMe
      document.body.appendChild(overlay);
    }
  };
  ws.onerror = function (e) {
    console.error(e.message);
  };
  ws.onclose = function (e) {
    if (undefined !== 'test') {
      console.warn('[parcel] 🚨 Connection to the HMR server was lost');
    }
  };
}
function removeErrorOverlay() {
  var overlay = document.getElementById(OVERLAY_ID);
  if (overlay) {
    overlay.remove();
    console.log('[parcel] ✨ Error resolved');
  }
}
function createErrorOverlay(diagnostics) {
  var overlay = document.createElement('div');
  overlay.id = OVERLAY_ID;
  let errorHTML = '<div style="background: black; opacity: 0.85; font-size: 16px; color: white; position: fixed; height: 100%; width: 100%; top: 0px; left: 0px; padding: 30px; font-family: Menlo, Consolas, monospace; z-index: 9999;">';
  for (let diagnostic of diagnostics) {
    let stack = diagnostic.codeframe ? diagnostic.codeframe : diagnostic.stack;
    errorHTML += `
      <div>
        <div style="font-size: 18px; font-weight: bold; margin-top: 20px;">
          🚨 ${diagnostic.message}
        </div>
        <pre>
          ${stack}
        </pre>
        <div>
          ${diagnostic.hints.map(hint => '<div>' + hint + '</div>').join('')}
        </div>
      </div>
    `;
  }
  errorHTML += '</div>';
  overlay.innerHTML = errorHTML;
  return overlay;
}
function getParents(bundle, id) /*: Array<[ParcelRequire, string]>*/
{
  var modules = bundle.modules;
  if (!modules) {
    return [];
  }
  var parents = [];
  var k, d, dep;
  for (k in modules) {
    for (d in modules[k][1]) {
      dep = modules[k][1][d];
      if (dep === id || Array.isArray(dep) && dep[dep.length - 1] === id) {
        parents.push([bundle, k]);
      }
    }
  }
  if (bundle.parent) {
    parents = parents.concat(getParents(bundle.parent, id));
  }
  return parents;
}
function updateLink(link) {
  var newLink = link.cloneNode();
  newLink.onload = function () {
    if (link.parentNode !== null) {
      // $FlowFixMe
      link.parentNode.removeChild(link);
    }
  };
  newLink.setAttribute('href', // $FlowFixMe
  link.getAttribute('href').split('?')[0] + '?' + Date.now());
  // $FlowFixMe
  link.parentNode.insertBefore(newLink, link.nextSibling);
}
var cssTimeout = null;
function reloadCSS() {
  if (cssTimeout) {
    return;
  }
  cssTimeout = setTimeout(function () {
    var links = document.querySelectorAll('link[rel="stylesheet"]');
    for (var i = 0; i < links.length; i++) {
      // $FlowFixMe[incompatible-type]
      var href = /*: string*/
      links[i].getAttribute('href');
      var hostname = getHostname();
      var servedFromHMRServer = hostname === 'localhost' ? new RegExp('^(https?:\\/\\/(0.0.0.0|127.0.0.1)|localhost):' + getPort()).test(href) : href.indexOf(hostname + ':' + getPort());
      var absolute = (/^https?:\/\//i).test(href) && href.indexOf(window.location.origin) !== 0 && !servedFromHMRServer;
      if (!absolute) {
        updateLink(links[i]);
      }
    }
    cssTimeout = null;
  }, 50);
}
function hmrApply(bundle, /*: ParcelRequire*/
asset) /*:  HMRAsset*/
{
  var modules = bundle.modules;
  if (!modules) {
    return;
  }
  if (asset.type === 'css') {
    reloadCSS();
    return;
  }
  let deps = asset.depsByBundle[bundle.HMR_BUNDLE_ID];
  if (deps) {
    var fn = new Function('require', 'module', 'exports', asset.output);
    modules[asset.id] = [fn, deps];
  } else if (bundle.parent) {
    hmrApply(bundle.parent, asset);
  }
}
function hmrAcceptCheck(bundle, /*: ParcelRequire*/
id, /*: ParcelRequire*/
/*: string*/
depsByBundle) /*: ?{ [string]: { [string]: string } }*/
{
  var modules = bundle.modules;
  if (!modules) {
    return;
  }
  if (depsByBundle && !depsByBundle[bundle.HMR_BUNDLE_ID]) {
    // If we reached the root bundle without finding where the asset should go,
    // there's nothing to do. Mark as "accepted" so we don't reload the page.
    if (!bundle.parent) {
      return true;
    }
    return hmrAcceptCheck(bundle.parent, id, depsByBundle);
  }
  if (checkedAssets[id]) {
    return;
  }
  checkedAssets[id] = true;
  var cached = bundle.cache[id];
  assetsToAccept.push([bundle, id]);
  if (cached && cached.hot && cached.hot._acceptCallbacks.length) {
    return true;
  }
  return getParents(module.bundle.root, id).some(function (v) {
    return hmrAcceptCheck(v[0], v[1], null);
  });
}
function hmrAcceptRun(bundle, /*: ParcelRequire*/
id) /*: string*/
{
  var cached = bundle.cache[id];
  bundle.hotData = {};
  if (cached && cached.hot) {
    cached.hot.data = bundle.hotData;
  }
  if (cached && cached.hot && cached.hot._disposeCallbacks.length) {
    cached.hot._disposeCallbacks.forEach(function (cb) {
      cb(bundle.hotData);
    });
  }
  delete bundle.cache[id];
  bundle(id);
  cached = bundle.cache[id];
  if (cached && cached.hot && cached.hot._acceptCallbacks.length) {
    cached.hot._acceptCallbacks.forEach(function (cb) {
      var assetsToAlsoAccept = cb(function () {
        return getParents(module.bundle.root, id);
      });
      if (assetsToAlsoAccept && assetsToAccept.length) {
        assetsToAccept.push.apply(assetsToAccept, assetsToAlsoAccept);
      }
    });
  }
  acceptedAssets[id] = true;
}

},{}],"tyOZh":[function(require,module,exports) {

},{}]},["6Suh7","tyOZh"], "tyOZh", "parcelRequire2b0d")

"></script>
```

**Comment by drachehavoc** [comment] 2021-06-20 08:04
I update to version `2.0.0-nightly.728` to check if issue is gone, but in this version the console.log prints

```html
http://127.0.0.1:1234/other.1055093d.html
```
---
### code to import HTML
```javascript
import otherHTML from "bundle-text:./other.html"

console.log(otherHTML)
```

**Comment by devongovett** [comment] 2021-06-20 08:15
Yes, it will be fixed when my pr is merged and released in the next nightly.

**Comment by drachehavoc** [comment] 2021-06-22 02:37
I just update to `2.0.0-nightly.729`, and now Parcel throws:

```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

    at /home/varela/.../node_modules/@parcel/packager-js/lib/DevPackager.js:123:33
    at /home/varela/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at /home/varela/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:403:26)
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at ContentGraph.dfs (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:451:12)
    at BundleGraph.traverseBundle (/home/varela/.../node_modules/@parcel/core/lib/BundleGraph.js:773:24)
    at NamedBundle.traverse (/home/varela/.../node_modules/@parcel/core/lib/public/Bundle.js:241:54)
    at DevPackager.package (/home/varela/.../node_modules/@parcel/packager-js/lib/DevPackager.js:114:17)
```

**Comment by drachehavoc** [comment] 2021-06-22 17:49
@devongovett  I just tested a build and it works well, but in serve mode the error persists: 

```bash
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

    at /home/varela/.../node_modules/@parcel/packager-js/lib/DevPackager.js:123:33
    at /home/varela/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at /home/varela/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:403:26)
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at walk (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at ContentGraph.dfs (/home/varela/.../node_modules/@parcel/core/lib/Graph.js:451:12)
    at BundleGraph.traverseBundle (/home/varela/.../node_modules/@parcel/core/lib/BundleGraph.js:773:24)
    at NamedBundle.traverse (/home/varela/.../node_modules/@parcel/core/lib/public/Bundle.js:241:54)
    at DevPackager.package (/home/varela/.../node_modules/@parcel/packager-js/lib/DevPackager.js:114:17)

```

**Comment by mischnic** [comment] 2021-06-23 09:41
> this.bundle.hasAsset

-> https://github.com/parcel-bundler/parcel/issues/6508

**Comment by drachehavoc** [comment] 2021-07-06 00:46
Will this problem be fixed soon?

**Comment by devongovett** [comment] 2021-07-10 07:49
Going to close this since #6508 tracks the remaining issue.

**Closed by devongovett** 2021-07-10 07:49 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, Bundler, HTML Preprocessing, ✨ Parcel 2

**Comment by andregs** [comment] 2021-07-26 03:25
Hi, @devongovett! I know https://github.com/parcel-bundler/parcel/pull/6574 fixed this issue, but why does Parcel add that inline `<script>` to the html, as mentioned here in https://github.com/parcel-bundler/parcel/issues/3875#issuecomment-864510847?

> 
> 
> Using the prefix `blundle-text:` in `Parcel 2.0.0-beta.2` I got this strange HTML:
> 
> ```
> <link rel="stylesheet" href="/index.d1a4d2be.css">
> <div>no no no no no</div><script src="// modules are defined as an array
> // [ module function, map of requires ]
> //
> // map of requires is short require name -> numeric require
> //
> // anything defined in a previous bundle is accessed via the
> // orig method which is the require for previous bundles
> 
> (function(modules, entry, mainEntry, parcelRequireName, globalName) {...
> ```
