### ISSUE TITLE
🙋Reload when html file change (without dependencies)

### ISSUE THREAD

**Issue by zeakd** [parcel-bundler/parcel#558] opened 2018-01-14 06:18 UTC
🙋 feature request.

### 🤔 Expected Behavior

It would be helpful browser reload page after editing html. 

### 😯 Current Behavior

Reloading only works when assets change (#83).

### 🔦 Context

Hi. I'm working on html file. I have trouble because I should refresh browser every time when I change my html text. It would be very helpful if browser automatically reload whenever change html file. browser-sync works, but it is little heavy and create-react-app have this feature. thanks!

appendix [create-react-app issue](https://github.com/facebookincubator/create-react-app/issues/656)

**Comment by DeMoorJasper** [comment] 2018-01-14 09:27
Can u test if this works in the current github version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zeakd** [comment] 2018-01-14 09:52
Nice. It works, but it have little bugs. Reload is not working in case html have no child bundle, so commenting all child broke hmr.

**Comment by DeMoorJasper** [comment] 2018-01-14 10:25
Ow, alright thought it always inserted hmr in latest master, i'll flag this as a feature

**Comment by okyantoro** [comment] 2018-01-19 01:49
I think this problem occurs because https://github.com/parcel-bundler/parcel/blob/072d799d48bb3639c628687937f3641fe2cff74d/src/packagers/JSPackager.js#L159-L166 is not called. Maybe we need to move the code somewhere to make ```builtins/hmr-runtime.js``` always included as dependency when the ```options.hmr``` enabled. I am not familiar with the source code and still learning about it. I hope I can help

**Comment by breadadams** [comment] 2018-01-20 14:04
I'm facing a similar issue. Using `vue`, with `<template src="./path/file.html"/>`. I have to save the `.vue` file where this html file is loaded for it to reload/recompile, parcel doesn't pick up on any changes in the `.html` file just on saving the html file.

**Comment by DeMoorJasper** [comment] 2018-01-20 15:27
@breadadams this should be fixed in the latest version and otherwise this is probably an issue with the vue plugin not with parcel core

**Comment by shawwn** [comment] 2018-01-20 15:31
@breadadams Try this: https://github.com/parcel-bundler/parcel/issues/5#issuecomment-359168173

Hot reloading works properly in that.

**Comment by breadadams** [comment] 2018-01-20 21:42
@DeMoorJasper Yeah I think this is down to the `parcel-plugin-vue` plugin, created an issue there https://github.com/BoltDoggy/parcel-plugin-vue/issues/18

@shawwn nice going, I've done a Vue + Parcel setup recently and it's _very_ similar 🙂 . However I just gave _my_ issue (see above link) a test run there and I can't seem to get [_separation_](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns) working at all there.

**Comment by mischnic** [comment] 2019-01-07 22:30
> Reload is not working in case html have no child bundle, so commenting all child broke hmr.

Refer to / duplicate of #943

**Closed by mischnic** 2019-01-07 22:30 UTC
Labels: :raising_hand_woman: Feature
