### ISSUE TITLE
Can't resolve background image url in .less file

### ISSUE THREAD

**Issue by xg4** [parcel-bundler/parcel#2744] opened 2019-03-08 09:03 UTC
# 🐛 bug report

Can't resolve background image url in .less file

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
// package.json
"devDependencies": {
  "less": "^3.9.0",
  "parcel-bundler": "1.11.0",
}
```

## 🤔 Expected Behavior

display background image

## 😯 Current Behavior

Can't resolve background image url

## 💁 Possible Solution

It can work in parcel-bundler@1.11.0

## 💻 Code Sample

> index.html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="./css/index.less" />
  </head>
  <body>
    <div class="img"></div>
  </body>
</html>
```

> css/index.less

```css
.img {
  width: 100px;
  height: 100px;
  background: url('../images/icon.png');
}
```

## 🌍 Your Environment

| Software         | Version(s)            |
| ---------------- | --------------------- |
| Parcel           | parcel-bundler@1.12.0 |
| Node             | 10.15.1               |
| npm/Yarn         | 1.13.0                |
| Operating System | Windows 10            |

**Comment by mischnic** [comment] 2019-03-08 10:43
Yes, duplicate of #2736

**Closed by mischnic** 2019-03-08 10:43 UTC
