### ISSUE TITLE
Pug file with no linked CSS will not hot reload

### ISSUE THREAD

**Issue by megalon** [parcel-bundler/parcel#4601] opened 2020-05-11 08:44 UTC
# 🐛 bug report

Parcel v1.12.4 will not hot reload a basic Pug file if that file doesn't link any CSS files.

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel index.pug`

## 🤔 Expected Behavior

After Parcel has built the webpage from the Pug file, modifying the pug file and saving it should cause Parcel to update the webpage it's serving.

## 😯 Current Behavior

Parcel seems to build the new version, but the page doesn't reload or update after the file changes.
There are no errors in the console that is running parcel, and there are no errors in the browser console.

## 💁 Possible Solution

Simply including any CSS file using Pug's "link" seems to fix this issue.

## 🔦 Context

I'm new to Parcel and I was trying to test it's ability to render and serve Pug files.
I made a very simple Pug file and noticed that hot reloading wasn't working.

## 💻 Code Sample

`index.pug` that will not hot reload
```pug
doctype html
html
	head
		title Test
	body
		p Testing 1234
```

`index.pug` that will hot reload
```
doctype html
html
	head
		title Test
		link(rel="stylesheet" type="text/css" href="./main.css")
	body
		p Testing 1234
```
`main.css` simply has to exist. It can be a blank file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4|
| Node             |v12.13.1|
| npm/Yarn         | yarn 1.21.1|
| Operating System | Windows 10

**Comment by mischnic** [comment] 2020-05-11 17:45
Duplicate of https://github.com/parcel-bundler/parcel/issues/943

**Closed by mischnic** 2020-05-11 17:45 UTC
