### ISSUE TITLE
[RFC] Config files of dependencies/node_modules are used causing unexpected bugs

### ISSUE THREAD

**Issue by kennetpostigo** [parcel-bundler/parcel#311] opened 2017-12-16 19:48 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛
### 🎛 Configuration (.babelrc, package.json, cli command)

No configuration

### 🤔 Expected Behavior
Parcel should not care about a dependencies build step configuration files. For example, throwing errors like [this](https://github.com/rexxars/react-markdown/issues/128). These build step files like `.babelrc`, etc. that are from a dependency are out of our control, all parcel should care about here is the module being exported from the package.

### 😯 Current Behavior
Parcel errors and refuses to compile over the `.babelrc` from a dependency I am using in my app. However this code is not under my control and should be irrelevant. Heres the error:
```
🚨  /Users/kennetpostigo/Projects/reasontraining/node_modules/react-markdown/lib/react-markdown.js: [BABEL] /Users/kennetpostigo/Projects/reasontraining/node_modules/react-markdown/lib/react-markdown.js: Unknown option: /Users/kennetpostigo/Projects/reasontraining/node_modules/react/index.js.Children. Check out http://babeljs.io/do
cs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options. (While processing preset: "/Users/kennetpostigo/Projects/reasontraining/node_modules/react/index.js")
A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`
```

### 💁 Possible Solution
Ignore project dependencies build files.

### 🔦 Context
I'm just using the library, don't need validation errors about their `.babelrc`. App refuses to bundle 😔

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.9.1
| npm/Yarn         | Yarn 1.3.2
| Operating System | osx

**Comment by DeMoorJasper** [comment] 2017-12-17 13:02
Probably a good idea to stick to the top-level config files and ignore dependencies config, i think this is more a RFC than a bug tbh

**Comment by nouh** [comment] 2017-12-19 10:23
I have the same problems here

**Comment by DeMoorJasper** [comment] 2018-01-09 09:16
Duplicate of #13

**Closed by DeMoorJasper** 2018-01-09 09:16 UTC
Labels: #RFC
