### ISSUE TITLE
tries to import datauri as a file if it is in quotes

### ISSUE THREAD

**Issue by chee** [parcel-bundler/parcel#43] opened 2017-12-06 09:47 UTC
```html
<!--index.html-->
<!doctype html>
<link rel="stylesheet" href="./lol.css">
```

works!:
```css
/* lol.css */
body {
  background: url(data:image/gif;base64,something);
}
```

error:
```css
/* lol.css */
body {
  background: url("data:image/gif;base64,something");
}
```

(`🚨  /Users/chee/projects/nothing/lol.css:2:3: Cannot resolve dependency './data:image/gif;base64,something'`)

**Comment by thejameskyle** [comment] 2017-12-06 12:32
[Relevant code is here](https://github.com/parcel-bundler/parcel/blob/ad5135adfda84e7bf49a9aee477deae7d83a3588/src/assets/CSSAsset.js#L61)

**Comment by ssuman** [comment] 2017-12-06 14:09
I'll work on this.

**Comment by devongovett** [comment] 2017-12-06 20:31
Fixed by #50.

**Closed by devongovett** 2017-12-06 20:31 UTC
Labels: good first issue, help wanted

**Comment by nijikokun** [comment] 2017-12-06 21:08
Awaiting release of this fix :+1:

**Comment by nijikokun** [comment] 2017-12-06 21:19
I tried using master since I couldn't wait and I am still encountering this issue:

```
/Users/nijikokun/ui.css:1:21599: Cannot resolve dependency './data:image/svg+xml;charset=utf-8,%3Csvg width='10' height='8' vie
>
```

The line in question is (notice the url inside, maybe that is triggering it):

```
background:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cpath d='M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z'/%3E%3C/svg%3E")
```

Here is me checking the contents of `is-url.js` to confirm that the code I am using has the changes which it does:

```
global/node_modules/parcel-bundler
▶ cat src/utils/is-url.js
const isURL = require('is-url');

// Matches anchor (ie: #raptors)
const ANCHOR_REGEXP = /^#/;

// Matches scheme (ie: tel:, mailto:, data:)
const SCHEME_REGEXP = /^[a-z]*\:/i;

module.exports = function (url) {
  return isURL(url) || ANCHOR_REGEXP.test(url) || SCHEME_REGEXP.test(url);
};

global/node_modules/parcel-bundler
▶
```

**Comment by nijikokun** [comment] 2017-12-06 21:28
I have found the issue, there was a `.cache` directory that needs to be blown away first. It works as intended.

**Comment by chee** [comment] 2017-12-07 09:49
thank you, everyone.

perhaps the whole cache should be invalidated when parcel updates

**Comment by thejameskyle** [comment] 2017-12-07 10:09
> perhaps the whole cache should be invalidated when parcel updates

That was added in #67
