### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by chong0808** [parcel-bundler/parcel#79] opened 2017-12-07 09:26 UTC
parcel version  is 1.0.3 
index.html
```
<html>

<body>
    <script src="./index.js"></script>
    <h1>test</h1>
</body>

</html>
```
index.js
```
console.log('test')
```
```
$ parcel index.html 
```

bundled file
dist/parcel.js
```
"use strict";

// modules are defined as an array
// [ module function, map of requires ]
//
// map of requires is short require name -> numeric require
//
// anything defined in a previous bundle is accessed via the
// orig method which is the require for previous bundles

require = function (_require) {
  function require(_x, _x2, _x3) {
    return _require.apply(this, arguments);
  }

  require.toString = function () {
    return _require.toString();
  };

  return require;
}(function (modules, cache, entry) {
  // Save the require from previous bundle to this closure if any
  var previousRequire = typeof require === "function" && require;
.........
```
![q](https://user-images.githubusercontent.com/16454649/33707836-b9be6878-db73-11e7-9122-190ebeb6bc87.png)

**Comment by thejameskyle** [comment] 2017-12-07 09:50
Duplicate of #40. Please search through issues before opening a new one as it reduces work a lot

**Closed by thejameskyle** 2017-12-07 09:50 UTC
