### ISSUE TITLE
Babel JSX Transform not working in Monorepo Subpackage

### ISSUE THREAD

**Issue by Dangoo** [parcel-bundler/parcel#7075] opened 2021-10-14 10:34 UTC
# 🐛 bug report

## 🔦 Context

We are maintaining a library that provides an `examples/` folder with different bundler setups to demonstrate usage and to test our library in these environments. The Repo is structured as a monorepo using lerna with yarn workspaces and hoisted `node_modules`:
```
package.json
babel.config.js
node_modules/
packages/
  library/
  ...
examples/
  parcel/
    package.json
    src/
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`babel.config.js` in project root
```js
module.exports = {
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    "@babel/preset-typescript",
    "@babel/preset-react",
  ],
  plugins: [
    "const-enum",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-private-methods",
  ],
};

```

## 🤔 Expected Behavior

Well, the app should build without errors.

## 😯 Current Behavior

Using the files from [React recipe](https://parceljs.org/recipes/react/) and running `parcel build` task within `examples/parcel` yields the following error:
```
$ parcel build
🚨 Build failed.

@parcel/transformer-babel: Unexpected token, expected "," (5:21)

  SyntaxError: Unexpected token, expected "," (5:21)
  at Object._raise
  (<root>/node_modules/@babel/parser/lib/index.js:541:17)
  at Object.raiseWithData
  (<root>/node_modules/@babel/parser/lib/index.js:534:17)
  at Object.raise
  (<root>/node_modules/@babel/parser/lib/index.js:495:17)
  at Object.unexpected
  (<root>/node_modules/@babel/parser/lib/index.js:3550:16)
  at Object.expect
  (<root>/node_modules/@babel/parser/lib/index.js:3524:28)
  at Object.tsParseDelimitedListWorker
  (<root>/node_modules/@babel/parser/lib/index.js:7859:14)
  at Object.tsParseDelimitedList
  (<root>/node_modules/@babel/parser/lib/index.js:7831:25)
  at Object.tsParseBracketedList
  (<root>/node_modules/@babel/parser/lib/index.js:7877:25)
  at Object.tsParseTypeParameters
  (<root>/node_modules/@babel/parser/lib/index.js:7986:24)
  at <root>/node_modules/@babel/parser/lib/index.js:9818:29
  <root>/examples/parcel/src/index.jsx:5:21
    4 | 
  > 5 | ReactDOM.render(<App />, document.getElementById('app'))
  >   |                     ^
```

## 💁 Possible Solution

Interestingly removing the `babel.config.js` in project root makes the example work.
So I read through babels ["monorepo" guide](https://babeljs.io/docs/en/config-files#subpackage-babelrcjson-files) where it states:
> The first issue you'll likely run into is that by default, Babel expects to load babel.config.json files from the directory set as its "root", which means that if you create a babel.config.json, but run Babel inside an individual package,
the "root" Babel is using in that context is not your monorepo root, **and it won't be able to find the babel.config.json file**.

But why does it seem to interfere with the `examples/parcel` babel default configuration while according to the docs babel should not be able to find it?

As well I tried "overriding" the root `babel.config.js` using `babelrcRoots` configured to respect `.babelrc` files inside `examples/*` and using [these parcel babel default presets](https://parceljs.org/languages/javascript/#default-presets). The error output was still the same.

Is there a way to tell parcel to ignore "parent" babel configs?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0
| Node             | 14.17
| npm/Yarn         | yarn
| Operating System | OSX

**Comment by astegmaier** [comment] 2021-10-26 18:55
Some background: I implemented parcel's current behavior for detecting ``.babelrc` and `babel.config.json` files in [this PR](https://github.com/parcel-bundler/parcel/pull/4132) with the goal of getting the behavior set out in [this scenario matrix](https://astegmaier.github.io/parcel2-monorepo-babel-bug/parcel-goals) - see the "Proposed fixes to parcel" column - that's what I intended to achieve.

There are three possibilities (1) The behavior I intended to implement leaves your scenario blocked, and we should think about the right way to fix it (2) There's a bug in the implementation that we should fix or (3) once you understand parcel's current behavior, you can get your scenario working.

This is the line from that scenario matrix that I think applies to your case:

| Config at root      | Config in sub-project | `babel-cli` result (running from root) | `babel-cli` result (running from sub-project)  | [Intended Parcel Behavior](https://github.com/parcel-bundler/parcel/pull/4132)                                                 | Notes                                                                                                                                                                                                                                                                                                                                                                                       |
| ------------------- | --------------------- | -------------------------------------- | --------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `babel.config.json` | `.babelrc`\*          | root respected, sub-project ignored    | root ignored, sub-project respected           | both root and sub-project **respected** (i.e. merged, as if you had correctly specified `babelrcRoot` and `rootMode` in babel cli options) | Babel documentation [recommends](https://babeljs.io/docs/en/config-files#subpackage-babelrcjson-files) setting [`babelrcRoots`](https://babeljs.io/docs/en/options#babelrcroots) _and_ `--rootMode upward` to enable detection in both cases. Parcel should accomplish a similar result on the users behalf without any extra parameters.                                          |

So I think we handle `babelrcRoots` behind the scenes for you, and your job is to put a `.babelrc` file in your `examples/parcel` folder that adds whatever presets are necessary to get the code in that folder transpiling correctly.

Let me know if that helps - if it doesn't, maybe you could provide a simplified repro?

**Comment by Dangoo** [comment] 2021-10-27 12:25
Hey @astegmaier,

thanks for giving the context!
I was able to reproduce the above behavior in a minimal example in a test repo:
https://github.com/Dangoo/parcel-babel-test/tree/main

So setting it up from scratch for a minimal scenario brought to light, that [our configuration of `babel-plugin-const-enum` was wrong](https://github.com/Dangoo/parcel-babel-test/pull/1/files) and caused parcel to attempt to use it on JSX files as well, see [here](https://github.com/dosentmatter/babel-plugin-const-enum#troubleshooting).

Taking the learnings to our main project (where we can't remove `@babel/preset-typescript`) the build now works (🥳 ) but we're getting this warning still:

```bash
@parcel/transformer-babel: Parcel includes transpilation by default. Babel config ../../babel.config.json includes
the following redundant presets: @babel/preset-env, @babel/preset-typescript, @babel/preset-react. Removing these
may improve build performance.

  /Users/me/Projects/my-project/babel.config.json:1:1
  > 1 | {
  >   | ^
    2 |   presets: [
    3 |     ["@babel/preset-env", { targets: { node: "current" } }],

  💡 Remove the above presets from ../../babel.config.json
  📝 Learn more: https://parceljs.org/languages/javascript/#default-presets

@parcel/transformer-babel: @babel/preset-env does not support Parcel's targets, which will likely result in
unnecessary transpilation and larger bundle sizes.
```

Since "merging" configs appears like a parcel special treatment (as compared to above mentioned babel native behavior), could you recommend a way on how to "overwrite" the plugins from `babel.config.json` in the workspaces `.babelrc`?

**Comment by astegmaier** [comment] 2021-10-27 15:11
Glad you got it building, at least :-)

Re: the warning you're seeing in production, I think that's actually something that's not caused by config merging directly. In `2.0.0-beta-3`, parcel [moved to using `swc` instead of babel by default for transpilation](https://parceljs.org/blog/beta3/#transpilation-performance), mainly because it's an order of magnitude faster than babel. We still support babel plugins to cover those cases that swc doesn't yet support, but:

>This does open up the possibility to improve the performance of your build even further, however. You can now remove @babel/preset-env, @babel/preset-react, and @babel/preset-typescript from your .babelrc and they will be automatically handled by SWC instead. This can significantly improve your build performance. If you have additional custom Babel plugins, you can leave them in your Babel config. If not, you can delete your Babel config entirely. We will likely add a warning in the future to assist with this migration.

So maybe try removing `@babel/preset-env`, `@babel/preset-typescript`, and `@babel/preset-react`, from `babel.config.json` and see what happens? If it still builds, I bet it'll be faster. If it doesn't build, that might be a sign of another bug.

**Comment by Dangoo** [comment] 2021-10-27 15:55
@astegmaier it's not about the parcel project at all, but in our repo structure we have a couple of other packages that benefit from that centralized babel configuration. Sure we could move the plugin to each of their local `.babelrc`, but that would increase the number of places to look for in case of changes.
For 8 of our 10 packages in that monorepo we are using babel, while for the 2 example packages section we explicitly would like to eliminate side effects from the root repo.
So is there - or could you think of - a solution to opt-out of babel config resolution?

**Comment by astegmaier** [comment] 2021-10-27 16:29
Hmm... this is a tough case. We arrived at the current behavior in part because we were trying to reconcile two goals that are in tension (1) align with babel behavior as much as possible and (2) align with parcel's general behavior of not changing behavior depending on `cwd` and not introducing plugin-specific CLI flags.

For example:
```
> my-monorepo > parcel build ./packages/my-package/src/index.html
```
...generally works the same as...
```
> my-monorepo > packages > my-package > parcel build ./src/index.html
```
But with the `babel-cli`, doing something similar might yield different results depending on the `cwd` and whether you passed the `--root-mode upward` flag.

So I'm not sure there's a perfect solution here (although I'm open to ideas).

An idea for a workaround while we try to think of a solution on our side: If the other projects are not using parcel, would it be possible to rename `babel.config.json` to something else (so parcel doesn't see it), and then using [a custom config path with the babel cli](https://babeljs.io/docs/en/babel-cli#custom-config-path) in the non-parcel projects to point them there?

**Comment by desfero** [comment] 2021-11-09 07:51
@astegmaier so the proper way to have support for package level `.baberc` would be to create a root `babel.config.json` with `babelrcRoots`?
https://github.com/desfero/parcel-workspace-support/blob/91441dfff43bc2dfd0fdfefa4f9824baea7f7a94/babel.config.json#L1-L7

What's the side effect of changing the parcel `projectRoot` based on the `cwd` or `.parcelrc` path.
Would be quite good to have an ability narrowing the root just to the exact package in a monorepo setup.

Another option would be to introduce a new key to `.parcelrc`, for e.g. `root: boolean` which when found would set the project root to the location of `.parcelrc` where `root: true`.

**Comment by LiahMartens** [comment] 2021-12-11 13:16
This issue also affects other plugins using projectRoot in a monorepo - eg [this file copy reporter](https://github.com/jvidalv/parcel-reporter-multiple-static-file-copier/)

**Closed as completed** 2022-06-24 12:03 UTC
Labels: Babel

**Comment by sldavidson** [comment] 2022-09-13 20:17
I am experience similar issues in a mono repo. One of the packages was going to use Parcel with a file copy reporter to copy static template files. When I build, no files are copied. It is because the report plugin is getting the mono repo's root `package.json` instead of the current package's `package.json`. This is because the `projectRoot` path passed to the plugin does not reflect the correct/expected path. 

I am curious of the response to the proposal from @desfero.
