### ISSUE TITLE
Is there a way to prohibit to resolve images?

### ISSUE THREAD

**Issue by jt3k** [parcel-bundler/parcel#1709] opened 2018-07-11 19:54 UTC
# ❔ Question

Is there a way to prohibit to resolve images?
![](https://i.imgur.com/8YszWjN.png)

## 🔦 Context
in pug-file i use custom text-variables
```pug
img(src="${myVariable}")
```

## 💻 Code Sample

i use variables  `${likeThis}` and want to leave it without resolve

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.9.4
| Node             | v10.1.0
| npm        |6.1.0
| Operating System | osx 10.12...

**Comment by mischnic** [comment] 2019-03-05 21:26
Closing as duplicate of #1186

**Closed by mischnic** 2019-03-05 21:26 UTC
Labels: :grey_question:  Question
