### ISSUE TITLE
Cannot find module 3emQt ('react-refresh/runtime')

### ISSUE THREAD

**Issue by dyatko** [parcel-bundler/parcel#4858] opened 2020-07-07 16:35 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "@parcel/core": "^2.0.0-nightly.325",
    "@parcel/runtime-react-refresh": "^2.0.0-nightly.327",
    "@parcel/transformer-react-refresh-babel": "^2.0.0-nightly.327",
    "@parcel/transformer-react-refresh-wrap": "^2.0.0-nightly.327",
    "parcel": "^2.0.0-nightly.325"
  },
  "targets": {
    "browser": {
      "context": "browser",
      "distDir": "dist",
      "engines": {
        "browsers": [
          "> 2%",
          "not dead"
        ]
      }
    }
  }
}
```

## 🤔 Expected Behavior

React-refresh works

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/31615495/86812371-3d4c1f80-c07f-11ea-8b5b-333547379c4a.png)

## 🔦 Context

At some nightly build, HMR with React fast refresh stopped working.

## 💻 Code Sample

Basic React 16 project

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.325 |
| Node             | 12.17.0 |
| Yarn         | 1.22.4 |
| Operating System | MacOS 10.15.5 |

**Comment by vazra** [comment] 2020-07-10 08:31
@dyatko is this related to https://github.com/parcel-bundler/parcel/issues/4825 ?

**Comment by mischnic** [comment] 2020-07-11 20:51
Please provide a reproduction. There is nothing I can do with the information you provided.

**Comment by dyatko** [comment] 2020-07-14 19:04
@mischnic well, it's a very basic React project.
I've created demo repo https://github.com/dyatko/parcel-react-refresh-bug

Run `yarn install && yarn start` and check console:

![image](https://user-images.githubusercontent.com/31615495/87465823-8ff48100-c615-11ea-82b2-6b79cc06fbe6.png)

**Comment by dyatko** [comment] 2020-07-14 19:09
Okay, I've found the root cause in this line https://github.com/dyatko/parcel-react-refresh-bug/blob/3fc453b7407bc370ceee407fec530c0fbf856dfb/src/index.html#L12

Apparently, I'm using some old library and had to implement this hack to make it work and I didn't expect that parcel defines `window.require`. Is it possible for parcel to use another variable name to avoid such collisions?

**Comment by mischnic** [comment] 2020-07-14 19:16
Parcel sets `windows.parcelRequire`: https://github.com/parcel-bundler/parcel/blob/8d64328859b787164e596a2140cccfa320e3a799/packages/packagers/js/src/prelude.js#L108

**Comment by dyatko** [comment] 2020-07-14 19:16
Wait, even empty script tag in index.html results in some pile of code that breaks react-refresh.

https://github.com/dyatko/parcel-react-refresh-bug/blob/master/src/index.html#L11-L12

![image](https://user-images.githubusercontent.com/31615495/87466733-1198de80-c617-11ea-9087-6fe8bc3b896c.png)

**Comment by dyatko** [comment] 2020-07-14 19:21
@mischnic Can I mark the `script` tag to not be processed by parcel?
I really need to inject my hack before any other code loaded.

**Comment by bhagn** [comment] 2020-11-20 11:54
Is there any work-around for this issue? Looks like disabling HMR is the only option.

**Comment by mischnic** [comment] 2020-11-20 17:41
@bhagn Do you also have another script (tag) in your HTML file?

**Comment by mischnic** [comment] 2020-11-20 18:08
Reproduction (index.js is empty, `package.json#dependencies` lists `react`):
```html
<script>
  /* asdsd */
</script>
<script src="index.js"></script>
```

---

This is actually a bundler problem

Runtime asset dependency graph:

![Bildschirmfoto 2020-11-20 um 19 04 25](https://user-images.githubusercontent.com/4586894/99834019-36700600-2b63-11eb-94a2-aefccb0cfb5b.png)

Bundle graph (black being "imports & contains" and red being "import from a different bundle"):

![Bildschirmfoto 2020-11-20 um 19 04 49](https://user-images.githubusercontent.com/4586894/99834066-4556b880-2b63-11eb-8f23-2cea7f9b9e8e.png)

"inline bundle" is executed first but it imports an asset from the other non-inline bundle.

**Comment by bhagn** [comment] 2020-11-20 18:21
@mischnic I have script tags that import JS files, but I don't have any inline scripts.

**Comment by jillesme** [comment] 2021-01-11 08:26
This is happening for me too in index.html (Parcel 2, 2.0.0-nightly.524)

```html
<script>window.INITIAL_DATA = {...}</script>
<script src="./entry.js"></script>
``` 

This gives me an error with React Refresh runtime like OP said. The following "fixes" it.

```html
<!-- <script>window.INITIAL_DATA = {...}</script> -->
<script src="./entry.js"></script>
```

**Comment by kyleslight** [comment] 2021-01-27 17:37
Facing the same issue, what I can do to prevent HMR being broken?

**Comment by mischnic** [comment] 2021-01-27 18:30
In case you can't remove the inline scripts, this .parcelrc completely disables React fast refresh:
```json
{
    "extends": "@parcel/config-default",
    "transformers": {
      "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
        "@parcel/transformer-babel",
        "@parcel/transformer-js"
      ]
    },
    "runtimes": {
      "browser": [
        "@parcel/runtime-js",
        "@parcel/runtime-browser-hmr"
      ]
    }
}
```

**Comment by aminya** [comment] 2021-02-08 07:53
I don't use React in my project, but I still get a similar error:
```js
> cross-env NODE_ENV=production parcel build --target main lib/autocomplete-paths.js

× Build failed.
@parcel/core: Cannot find parcel plugin "@parcel/transformer-react-refresh-babel"
C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\autocomplete-paths\node_modules\.pnpm\@parcel\config-default@2.0.0-nightly.576_@parcel+core@2.0.0-nightly.574\node_modules\@parcel\config-default\index.json:8:7
   7 |     "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
>  8 |       "@parcel/transformer-react-refresh-babel",
>    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/transformer-react-refresh-babel", did you mean "@parcel/transformer-react-refresh-babel"?
   9 |       "@parcel/transformer-babel",
  10 |       "@parcel/transformer-js",
```

**Comment by skipjack** [comment] 2021-03-03 21:55
Same for me as @jillesme. A script in the `<head>` tag was causing the `react-refresh/runtime` related error to be thrown. Commenting it out fixed the issue, though now I gotta re-integrate it somehow 😁

**Comment by aminya** [comment] 2021-03-03 23:26
@skipjack 

`"parcel": "2.0.0-nightly.476"` seems to be the only version that works for me without throwing this error. If you want, try that.

**Comment by devongovett** [comment] 2021-07-12 03:46
Appears to already work in the latest nightlies if the inline script has `type="module"`, but I found some other issues with non-module scripts fixed in #6584.

**Closed** 2021-07-17 23:23 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, Bundler, HMR, React Fast Refresh, ✨ Parcel 2

**Comment by kedar-pethe** [comment] 2023-03-31 12:08
> In case you can't remove the inline scripts, this .parcelrc completely disables React fast refresh:
> 
> ```json
> {
>     "extends": "@parcel/config-default",
>     "transformers": {
>       "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
>         "@parcel/transformer-babel",
>         "@parcel/transformer-js"
>       ]
>     },
>     "runtimes": {
>       "browser": [
>         "@parcel/runtime-js",
>         "@parcel/runtime-browser-hmr"
>       ]
>     }
> }
> ```

This doesnt work @devongovett @mischnic  and you get an error like `@parcel/core: Invalid Parcel Config ` in parcel 2.8.0.
Pls share solution...

**Comment by kedar-pethe** [comment] 2023-03-31 15:06
This solution worked on my machine -

- Upgrade to latest Parcel version 2.8.0
- Delete ._parcel-cache_ folder
- Set key FAST_REFRESH=false in _.env_ file and start app again.
You shouldn't see this runtime error in DEVTOOLS console.
@mischnic
