### ISSUE TITLE
Code splitting is not working

### ISSUE THREAD

**Issue by maxirozay** [parcel-bundler/parcel#905] opened 2018-02-27 17:06 UTC
🐛 bug report

### Code splitting

```js
{
  "presets": [
    "env",
    "stage-2"
  ],
  "plugins": [
    "transform-runtime",
    "dynamic-import-node"
  ]
}
```

### 🤔 Expected Behavior

The build should contain one javascript file per page since I import them asynchronously.

### 😯 Current Behavior

There's only one javascript file.

### 🔦 Context

I have a Vue application with webpack and I'm trying to migrate to parcel. My application has 5 pages that are lazy-loaded with `const TheHome = () => import('../components/TheHome')`.

### 💻 Code Sample

I made an example that reproduce my problem. To try you can execute `yarn dev` or `yarn build`.
https://github.com/maxirozay/test-parcel

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.9.4
| npm/Yarn         | 1.3.2
| Operating System | linux (Solus)

**Comment by jeanfortheweb** [comment] 2018-02-28 00:34
Just to be sure: AFAIK you have to handle the promise from import(), so `import(....).then(...)` could already do the trick.

**Comment by maxirozay** [comment] 2018-02-28 08:47
I tried it too and it's not working either. The way I'm importing is the way indicated on the vue-router documentation and the way it's working fine with webpack.

I also tried `component: async () => await import('./a')` which is not working either.

**Comment by jeanfortheweb** [comment] 2018-02-28 14:59
If your files getting imported and they work but the actual split does not work, it could be a duplicate of #790 which I'm trying to fix with PR #895 .

If you like, you can try the branch im my fork at #895 and check if the splitting works there for you. I would appreciate you feedback!

**Comment by maxirozay** [comment] 2018-02-28 15:07
Ok I'll do that!

**Comment by maxirozay** [comment] 2018-03-01 09:38
@jeanfortheweb with your branch I get the error 
```
(node:3568) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/path/node_modules/parcel-bundler/src/builtins/prelude.min.js'
(node:3568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'll try to learn more about the code splitting part of parcel to see if I can do something.

**Comment by jeanfortheweb** [comment] 2018-03-02 17:32
Okay, thats for that, I'll have a look

**Comment by lifeiscontent** [comment] 2018-03-18 13:13
I'm also running into this issue.

**Comment by gilbert** [comment] 2018-03-19 19:16
I'm also running into this issue. It's a small open source project so one can inspect for themselves:

- Here's the [main script tag](https://github.com/gilbert/keydash/blob/master/index.html#L9)
- Here's the [dynamic import](https://github.com/gilbert/keydash/blob/master/index.js#L6)
- [Building](https://github.com/gilbert/keydash/blob/master/publish.sh#L2) only yields [one js file](https://github.com/gilbert/keydash/tree/gh-pages) (the other is from the codemirror.js script)

**Comment by glomotion** [comment] 2018-04-04 00:04
On a slightly related note:
I've just checked out the repo posted by @maxirozay - and noticed that none of the vue components seem to be getting the usual postcss transform (i've noticed the same thing in my own work when vue code splitting is enabled - [demo repo here](https://github.com/glomotion/test-parcel)). 

Could this be something todo with `babel-plugin-dynamic-import-node`?

**Comment by alidcastano** [comment] 2018-07-01 17:54
I just ran into this as well. I'm using Parcel with React and [loadable-components](https://github.com/smooth-code/loadable-components) and none of the routes are being split, only a single bundle file is generated.

**Comment by machycek** [comment] 2018-07-05 17:09
Same issue here. I'm using react-loadable. Once it's fixed I can finally migrate to parcel ✨

**Comment by John0x** [comment] 2018-07-06 14:23
Experiencing the same issue with react-router 4 and react-loadable

**Comment by ewyler** [comment] 2018-07-08 02:54
Ditto the above, this seems broken - only one bundle file is ever generated. Using Parcel 1.8.1 and tried both with react-loadable as well as a very vanilla `import()` usage

**Comment by neculaesei** [comment] 2018-07-20 22:42
Also running into the exact same scenario with Vue.

**Comment by maxirozay** [comment] 2018-08-23 14:30
@neculaesei I tried to update parcel to 1.9.7 and parcel-bundler to 1.9.7 and use your babelrc config and I get the error `Cannot read property 'add' of undefined at JSPackager.addAsset...JSPackager.js:57:32`.

**Comment by antoniopuero** [comment] 2018-10-20 16:16
so it seems to be the issue with those plugins. If I remove transform-runtime - everything works as expected

**Comment by devongovett** [comment] 2018-11-04 22:34
Closing. I believe this is because you have `dynamic-import-node` in your babelrc. This means babel will compile away the `import()` syntax before parcel sees it, and therefore no code splitting occurs. That babel plugin just compiles `import()` to `require()` which means it will be in a single bundle.

**Closed by devongovett** 2018-11-04 22:34 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, :pray: Help Wanted

**Comment by davibe** [comment] 2019-09-03 07:49
Same issue, i don't even have a babelrc

**Comment by shenjo** [comment] 2020-01-07 02:24
@davibe check this issue , https://github.com/parcel-bundler/parcel/issues/1547
