### ISSUE TITLE
Including files from node_modules in index.html causes export issues.

### ISSUE THREAD

**Issue by dumptyd** [parcel-bundler/parcel#1483] opened 2018-06-03 15:11 UTC
# 🐛 bug report

In my index.html if I do

```html
<script src="./node_modules/some_package/some_file_that_exposes_myModule.js">
<script>
  myModule();
</script>
```
It compiles fine but in the browser I get `myModule is not defined`.

## 🤔 Expected Behavior

Included file should expose the instance/object correctly.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 8.0.0
| Yarn         | 0.21.3
| Operating System | Ubuntu Xenial

**Comment by Tom-Julux** [comment] 2018-06-04 10:36
Does your file in node_modules exposes `myModule` as a global variable? Most modules don't do that.
To solve this you could put the calling script in an extra file and require the module there.

**Comment by dumptyd** [comment] 2018-06-06 15:03
That works in some cases, but I can't even get something as simple as this to work. 
```js
require('jquery/dist/jquery.js');
require('bootstrap/dist/js/bootstrap.min.js');
```
because `bootstrap` can't find `jquery`.

**Comment by mischnic** [comment] 2019-01-06 21:41
The issue with jQuery is that it detects that `module.exports` is available, so it doesn't set `window.jQuery`:
node_modules/jquery/dist/jquery.js:
```js
	if ( typeof module === "object" && typeof module.exports === "object" ) {

		// For CommonJS and CommonJS-like environments where a proper `window`
		// is present, execute the factory and get jQuery.
		// For environments that do not have a `window` with a `document`
		// (such as Node.js), expose a factory as module.exports.
		// This accentuates the need for the creation of a real `window`.
		// e.g. var jQuery = require("jquery")(window);
		// See ticket #14549 for more info.
		module.exports = global.document ?
			factory( global, true )/* runs in node & parcel*/ :
			function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
	} else {
		factory( global ); /* runs in browser */
	}
```

**Comment by mischnic** [comment] 2019-01-07 21:35
Duplicate of #333

**Closed by mischnic** 2019-01-07 21:35 UTC
Labels: :bug: Bug
