### ISSUE TITLE
transformer-webextension, v3 is not supported

### ISSUE THREAD

**Issue by lecepin** [parcel-bundler/parcel#7857] opened 2022-03-24 07:51 UTC
https://github.com/parcel-bundler/parcel/blob/d3ea25517e26242b5bf237dd1fad339dde37d3ec/packages/transformers/webextension/src/schema.js#L46

<img width="898" alt="image" src="https://user-images.githubusercontent.com/11046969/159867619-59193989-ada9-4881-982b-c4a433eac5cc.png">

![image](https://user-images.githubusercontent.com/11046969/159867829-43d33a36-23d1-490d-a867-ebd6f9076ba1.png)

Refer doc [Welcome to Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/)

**Comment by mischnic** [comment] 2022-03-24 07:59
Duplicate of https://github.com/parcel-bundler/parcel/issues/6079

**Closed as completed by mischnic** 2022-03-24 07:59 UTC
