### ISSUE TITLE
How to remove `.html` from transformed links?

### ISSUE THREAD

**Issue by qm3ster** [parcel-bundler/parcel#2121] opened 2018-10-10 21:27 UTC
# ❔ Question

Is there a way to not append `.html` to for example `.pug` files bundled due to being `<a href="other.pug">` linked to?

## 🔦 Context

Trying to move the bundling of an old static site to parcel

## 💻 Code Sample

```pug
//- index.pug
a(href="other.pug")
```
```pug
//- other.pug
span Hello
```
```sh
yarn parcel index.pug
```
:thinking: 
outputs:
```html
<a href="other.html"/>
```
instead of
```html
<a href="other"/>
```

**Comment by DeMoorJasper** [comment] 2018-10-11 07:28
That’s currently not possible

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qm3ster** [comment] 2018-10-11 10:00
Thank you.
Is there a feature request for this anywhere?
Would this be a worthwhile feature request?

**Comment by DeMoorJasper** [comment] 2018-10-11 10:07
There’s already a couple feature requests on ignoring transforming of certain assets we haven’t figured out how to approach it though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qm3ster** [comment] 2018-10-14 16:16
Oh, I do want it transformed. It's crucial it be included, the pug transformed, the resources referenced by the resulting html walked, etc.
I only want the output to be clean links vs `.html` links.

**Comment by DeMoorJasper** [comment] 2018-10-14 17:28
In that case this is a duplicate of #1400 and likely some other issues as well

**Closed by DeMoorJasper** 2018-10-14 17:28 UTC
