### ISSUE TITLE
NW.js support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [parcel-bundler/parcel#819] opened 2018-02-15 21:29 UTC
**Choose one:** feature request

Can we get support for [NW.js](http://nwjs.io), in a similar manner to how Electron is supported.

**Comment by lbguilherme** [comment] 2018-02-15 23:30
Using `--target=electron` doesn't work with NW.js? What fails?

**Comment by TheJaredWilcurt** [comment] 2018-02-18 00:55
It doesn't work at all. The two are used for the same purpose (to create Cross-Platform Desktop Apps), but they are different projects. I think the primary difference in this case is that the entry point for most NW.js apps is an html file, though you can also point to a local server or remote url, which is not uncommon, though the majority just point directly to an html file. It is also possible, but much less common, to have a JS file as the entry point.

Also, it's kind of offensive to suggest that, being that NW.js is more powerful and predates Electron by like 5 years.

**Comment by lbguilherme** [comment] 2018-02-18 12:04
I just installed NW.js, created a base project, added this to my `package.json`: `"main": "http://localhost:1234/`. Then started `parcel src/index.html --target=electron`, and launched `nw`.

It all worked flawlessly. Editing files triggered hot reloading as expected. The only possible improvement would be to add `--target=nw` as a synonym of `--target=electron`.

Closing this.

**Closed by lbguilherme** 2018-02-18 12:04 UTC

**Comment by Mxkkxa** [comment] 2018-08-06 11:07
@lbguilherme I did as exactly you said and nw shows:

> This site can’t be reached
> localhost refused to connect.

**Comment by TheJaredWilcurt** [comment] 2018-08-07 13:41
Yeah I've never been able to get Parcel to work with NW.js, I gave up and moved away from it.

**Comment by TheJaredWilcurt** [comment] 2018-08-07 15:32
This is as far as I got. PR's to make it work are welcome:

* https://github.com/TheJaredWilcurt/parcel-nw

**Comment by Hammster** [comment] 2018-08-09 12:40
Change your main entry point. The issue is not parcel related it is a simple configuration error.

`"main": "dist/index.html"`

**Comment by TheJaredWilcurt** [comment] 2018-08-10 19:01
@Hammster 

That loads the static `index.html` file. And it works, but if you modify the source index.html file and save it, the app does not refresh to show the change. The only way for it to work properly is to point it to a local host. Now, once it is built and ready for production, then sure, point it at the static file, but during development, you want the `"main": "http://localhost:1234"`, it's just that parcel doesn't work.

**Comment by TheJaredWilcurt** [comment] 2018-08-10 20:19
An alternative approach is to use the [Parcel API](https://parceljs.org/api.html), rather than the CLI.

In the NW.js world, we have a `"main"` which points to a `.html` file or a url, but we also have a `"node-main"` which is pointed to a `.js` file. The `"node-main"` js file is ran first in the node-context prior to a window loading. It is commonly used to have a node script run to launch a local webserver prior to the window launching.

**Comment by Hammster** [comment] 2018-08-11 11:07
@TheJaredWilcurt I extended your example, it is still a bit hacky since you need to start the script twice and to close it you need to sigterm kill the programm with `CTRL + C`.

https://github.com/Hammster/parcel-nw

**Comment by TheJaredWilcurt** [comment] 2018-08-14 13:15
@Hammster 

NW.js is much simpler/easier than Electron for file system hosted apps. More NW.js apps are hosted directly off of the drive than Electron apps simply because all you need to do is `"main": "index.html"`, versus Electron's complicated JS entry point.

There are actually a lot of valid reasons to run a local webserver and host your app from that, primarily around security and auth. Though it is dependent upon the goal of your application as to whether that is a good fit or not. I agree that most people do not need a webserver for their desktop apps.

However the issue you are having is not due to NW.js, but Chromium.

* https://stackoverflow.com/a/45151563/1058262

For security purposes, Chromium does not allow access to websockets via `file://` or `http://localhost`. 

Also, Parcel decides to use `ws` or `wss` based on `https`.

* https://github.com/parcel-bundler/parcel/blob/master/src/builtins/hmr-runtime.js#L27

**Comment by Hammster** [comment] 2018-08-14 15:04
I think a discussion on what is better for someone or not does not help anyone in this issue. I'll remove the on phrase where I expressed my disliking about nw.js.

Generally NW.js is fully functional with parcel, and the issue in this case is mainly from a user standpoint, as said HMR works fine out of the box if the sockets is properly used by the underlying framework, or in case of NW.js you will need to provide it yourself either by adding handlers or by going the route via express middleware.

**Comment by TheJaredWilcurt** [comment] 2018-10-03 14:37
Just an update on this, I am working on a project that uses NW.js and Webpack. It runs development with HMR with no problems (`npm start`), and it builds to a filesystem based deployment (`npm run build`). It was not that difficult to set up, spent about a quarter the amount of time setting it up as I did trying to get Parcel to work before giving up. Though that time save is mostly chocked up to using the Vue CLI 3 service which handles all the Webpack configuration for you.

* https://github.com/TheJaredWilcurt/karngdarbo

I'd still like to find a way to generate 3 separate theme files from Sass while still having HMR. Right now I am just bundling the 3 themes into one file, which works but feels over complicated and clunky.

**Comment by djmisterjon** [comment] 2020-07-08 06:23
Given that Google brings us to this page and that it does not give any solution!, 
I take this opportunity to share my boilerplate with solution.
https://github.com/djmisterjon/nw-Parcel-hmr-boilerplate
