### ISSUE TITLE
Support index.html directory indexes when using Serve with multiple entry points

### ISSUE THREAD

**Issue by JoshuaWalsh** [parcel-bundler/parcel#3778] opened 2019-11-14 14:04 UTC
# 🙋 Feature Request

I'm using Parcel for my open source project [lyrsync](https://github.com/JoshuaWalsh/lyrsync). Locally, I use the CLI's serve functionality a lot while I'm developing the project.

If I serve a single entry point (`parcel src/index.hbs`) then I can visit `http://localhost:1234` in my browser and it works perfectly.

But if I serve multiple entry points (`parcel src/index.hbs src/songs/**/*.hbs`) then navigating to that same URL returns a completely blank document, the response body has no contents. The status code will be 404. To view the page, I instead need to navigate to `http://localhost:1234/index.html`.

This also happens for any other paths. `/songs/komm-susser-tod/` is a blank 404, I have to load `/songs/komm-susser-tod/index.html` instead.

This is a mild annoyance, I can add the index.html to the URL myself. But it would be nice if it just worked, the way that everything else in Parcel does. :)

## 🤔 Expected Behavior

If serve receives a request for a file that doesn't exist, but there is a directory at that path with an index.html file in it, serve the index.html file.

## 😯 Current Behavior

If Parcel is serving a single entry point, any request for a file that doesn't exist will serve that entry point. For example, even `http://localhost:1234/notreal.css` serves `index.html`. This is a bit surprising, I'd expect it to 404, but I'm guessing this behaviour is done so that SPAs that use HTML5's history API will work as expected.

If Parcel is serving multiple entry points, any request for a file that doesn't exist will serve a blank 404 page.

## 🔦 Context

This issue is a minor annoyance, but it means when I'm testing my site none of the links work correctly. I always have to edit the URL to add `index.html`.

## 💻 Examples

As mentioned earlier, these issues can be seen in my project [lyrsync](https://github.com/JoshuaWalsh/lyrsync). After installing dependencies you can run `npm run-script dev` to run the correct Parcel serve command.

**Comment by mischnic** [comment] 2019-11-15 21:57
Duplicate of https://github.com/parcel-bundler/parcel/issues/1315 😬

**Closed by mischnic** 2019-11-15 21:57 UTC

**Comment by JoshuaWalsh** [comment] 2019-11-16 07:01
Ah, I did search for it but didn't see that one, sorry.
