### ISSUE TITLE
error: unknown option `--no-source-maps'

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1047] opened 2018-03-22 17:24 UTC
If I run `parcel build src/index.html --public-url ./ --no-source-maps`
I get error
```
error: unknown option `--no-source-maps'
```

In my case I don't need to have source maps in production

parcel: 1.6.2

**Comment by davidnagli** [comment] 2018-03-22 17:26
Exact duplicate of #1041 😂

**Comment by davidnagli** [comment] 2018-03-22 17:28
To quote the mighty @DeMoorJasper:
> --no-source-maps flag hasn't been released yet (for the build command) only for the watch command. Simply removing the flag should build without sourcemaps (keep in mind the next release will have this flag and make sourcemaps as a default)

**Closed by davidnagli** 2018-03-22 17:28 UTC
Labels: :heavy_multiplication_x:  Duplicate
