### ISSUE TITLE
Cache prevents Parcel to output files

### ISSUE THREAD

**Issue by fetis** [parcel-bundler/parcel#8698] opened 2022-12-16 11:17 UTC
# 🐛 bug report

I have Parcel setup as part of a bigger project where output provided by Parcel is served by Express.js
When I do 2 consequent builds, Parcel doesn't generate output because it's already cached

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

package.json
```
  "browserslist": [
    "> 0.5%",
    "last 2 versions",
    "Firefox ESR",
    "not dead"
  ],
```

## 🤔 Expected Behavior

Parcel produces files every time when I run `parcel build`

## 😯 Current Behavior

Here are the illustration steps
```
➜ parcel build src/ts/sign-in.ts  --dist-dir ../dist/client-app
✨ Built in 2.34s

../dist/client-app/sign-in.js    96.14 KB    771ms

➜ ls ../dist/client-app
sign-in.js     sign-in.js.map

➜ rm -rf ../dist

➜ parcel build src/ts/sign-in.ts  --dist-dir ../dist/client-app
✨ Built in 158ms

../dist/client-app/sign-in.js    96.14 KB    771ms

➜ ls ../dist/client-app
ls: ../dist/client-app: No such file or directory
```

If I delete `.parcel-cache` and run the build again I will have output in the `dist` directory

## 💁 Possible Solution

Output files every time.

A possible workaround is to use `--no-cache` but why have cache then?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 16
| npm/Yarn         | 8
| Operating System | MacOs

**Comment by mischnic** [comment] 2022-12-18 11:30
Duplicate of https://github.com/parcel-bundler/parcel/issues/7186

The reason behind this is that for very large projects, we don't want to write every bundle to disk if it hasn't changed since the last build.

**Closed as not planned by mischnic** 2022-12-18 11:30 UTC

**Comment by fetis** [comment] 2022-12-18 11:33
hey @mischnic 
This behavior is counter intuitive, you expect to have a build result every time you do a build.  Producing result shouldn't take much time having result in a cache already

**Comment by mischnic** [comment] 2022-12-18 11:43
So I'd say that the current behaviour is a bug, a dist dir outside the project root should still work fine (see that issue).

It does take quite some time if there are >500 bundles and you're in development mode where a code change should be reflected as quickly as possible.

**Comment by fetis** [comment] 2022-12-18 11:46
@mischnic 
I'm doing `build`, so it's not development and I'm ok to wait. Currently, I had to disable cache completely to workaround the bug
