### ISSUE TITLE
ES Module type=module cause "parcelRequire is not defined" error

### ISSUE THREAD

**Issue by tarepan** [parcel-bundler/parcel#1401] opened 2018-05-20 13:58 UTC
# 🐛 bug report
Using ES Module in main HTML cause "parcelRequire is not defined" error.  
If we use **type="module"**, minimal code in [Getting Started (Parcel official)](https://parceljs.org/getting_started.html) make this error.  

## 🎛 Configuration (.babelrc, package.json, cli command)
zero configuration.  

## 🤔 Expected Behavior
If we write super simple code with ES Module like below,  

```html
<!-- index.html -->
<html>
<body>
<script src="./index.js" type="module"></script>
</body>
</html>
```
```javascript
// index.js
console.log("hello parcel");
```
I hope it is bundled properly and get "hello parcel" in console without error.

## 😯 Current Behavior
In console,  
```
hello parcel.   index.js 1
Uncaught ReferenceError: parcelRequire is not defined at test.904c6489.js:10
```
## 💁 Possible Solution
Apparently ES Module cause this error.  
When I removed **type="module"** from script element, no error observed.  

It suggest that we can avoid error by avoiding **type="module"** for parcel.  
But I think this approach is not good.  
ES Module (type="module") is generally available (now 2018-05, all popular browsers supported!!), so ES module is straight forward way to import module.  

## 🔦 Context
I do not know what problem is caused by this error.  

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  parcel-bundler@1.8.1 |
| Node             | (problem happen both) 8.9.3 & 9.11.1 |
| npm/Yarn         | |
| Operating System | Windows10 Pro, build 17134 |

##
Thank you good library, I hope this project become better and better.

**Comment by itshizhan** [comment] 2018-05-21 03:44
since you use type="module",why use parcel?

**Comment by tarepan** [comment] 2018-05-21 03:49
Mainly for **module resolution.**  
And for old browser users (ES module not supported, need Bundle.)

**Comment by Schubidu** [comment] 2018-05-25 06:28
A good point to use Parcel in this case is the minification and files with hashes

**Comment by emirotin** [comment] 2018-06-06 12:58
I have the same problem in different context. I'm trying to consume parcel-bundled module from my webpack-bundled app. Since ES6 modules (my app) run in strict context an attempt to consume the module results in assignment to undefined variable and crashes my app.

**Comment by alexeyraspopov** [comment] 2018-07-03 15:45
Seems like this is no longer reproducible in v1.9.4.

**Comment by alexeyraspopov** [comment] 2018-07-03 15:51
Maybe it makes sense for Parcel to remove `type="module"` for an entry that is being built?

**Comment by davidnagli** [comment] 2018-07-10 17:20
This is an issue with the way `parcelRequire` is defined in Strict Mode. ES6 modules are by default executed in strict mode (AFIK), which prohibits implicit variable declerations.

Here's what Parcel's output looks like:

```javascript
parcelRequire = (function (modules, cache, entry, globalName) {
  // Save the require from previous bundle to this closure if any
  var previousRequire = typeof parcelRequire === 'function' && parcelRequire;
  var nodeRequire = typeof require === 'function' && require;

  function newRequire(name, jumped) {
```

Notice how the global parcelRequire is implicitly declared without let/var!

By editing the output file and naively adding `let` before `parcelRequire` I was able to eliminate the issue. However, adding let can affect scoping...

An alternative that works is changing it to `window.parcelRequire`, but that would break in Node; which probably doesn't really matter since we can avoid doing that in `--target node`.

I ran into this in the wild in a slightly separate case when attempting to require a library I bundled with Parcel in a Webpack project. The Webpack project had a top level `"use strict"` pragma automatically injected which is what broke everything in the same way as this issue.

**Comment by cameron-martin** [comment] 2018-07-26 18:53
Looks like a duplicate of https://github.com/parcel-bundler/parcel/issues/864

**Comment by GrosSacASac** [comment] 2018-09-08 19:41
it should not be hard to add `var` or `let` or `const`

**Comment by outkine** [comment] 2018-09-19 03:58
(duplicate of https://github.com/parcel-bundler/parcel/issues/864#issuecomment-422642478)
Since require may be used inside of the modules, defining it with let/const/var causes a `ReferenceError: require is not defined`

**Comment by dfkaye** [comment] 2018-09-25 21:05
temporary fix for your work environment or localhost - https://twitter.com/dfkaye/status/1044693110700171264

**Comment by idanilt** [comment] 2018-11-11 07:36
nicer work around:
`yarn add parcel-plugin-wrapper --dev`

.assetWarpper.js
```javascript
const path = require('path')

const CWD = process.cwd()
const PACKAGE = require(path.join(CWD, 'package.json'))

const varRequire = async ({name, bundler}) => {
    // name = app.ere76r5e76r5e76r.js
    if (name.split('.').pop() === 'js' && bundler.options.production) {
        return {
            header: `var parcelRequire = undefined;`,
            footer: ``
        }
    }
}

module.exports = varRequire;
```

**Comment by kirillgroshkov** [comment] 2018-11-16 15:03
We're having same issue!

**Comment by dandv** [comment] 2018-12-11 07:43
Note that simply removing `type="module"` didn't work, even after re-launching parcel. I had to also delete the `.cache` directory.

**Comment by Draccoz** [comment] 2018-12-12 21:44
Sooo, am I reading this correctly? Parcel does not allow for a standard ES Module output?

**Comment by lvalencia** [comment] 2019-01-16 01:31
yeah I'm having this issue when I use a raw .ts file as my input and I bundle my node_modules with it into a single file e.g.

`parcel build ./src/index.ts --target node --bundle-node-modules`

when i run it in node I'll get an error like 

`ReferenceError: parcelRequire is not defined`

when I look at the non-minified version I can see 

```
// eslint-disable-next-line no-global-assign
parcelRequire = (function (modules, cache, entry, globalName) {
```

so my guess is the assumption was that it would globally assign. it appears that it doesn't.

Obviously if I add `var` in front of it the lexical scoping lookup of JavaScript assigns it to global. but from what I can gather that would break things for other environments i.e. not `--target node`

I came up with a workaround 

`parcel build ./src/index.ts --target node --bundle-node-modules --out-dir ./dist --no-minify --out-file main.js && sed -i '' '1s;^;var ;' ./dist/main.js`

obviously the bummer here is I can't use `watch` because how would I append it for my needs.

anyway is there an ETA for this fix? the set-up (or lack thereof) is super convenient so I'd like to use Parcel for a recommended way of doing something except this is kind of a blocker.

**Comment by dfkaye** [comment] 2019-01-21 18:51
We ran into another issue specific to our app, so we had to come up with a post-bundling process file that uses the parcel-bundler API directly (see https://parceljs.org/api.html) in order to solve that as well as the "parcelRequire is not defined" issue. 

https://gist.github.com/dfkaye/f43dbdfbcdee427dbe4339870ed979d0

**Comment by heldrida** [comment] 2019-02-05 16:06
Have the same issue here! 

"ReferenceError: parcelRequire is not defined"

While working in:
index.js, imports fileA
fileA.js, imports fileB
fileB.js

Command:
parcel build ./src/index.js --target browser

Can fix if manually add let,const before parcelRequire=

**Comment by twome** [comment] 2019-02-20 11:29
A workaround for Gulp / stream-based build system users, using [gulp-insert](https://github.com/rschmukler/gulp-insert/) to prepend the `parcelRequire` global declaration. Thanks for the idea @idanilt!

```javascript
const gInsert = require('gulp-insert')

let parcelPatchTask = ()=>{
	return gulp.src(p(paths.dist, '**/*.js'))
		.pipe(gInsert.prepend(';var parcelRequire;\n'))
		.pipe(gulp.dest(paths.dist))
}
```

**Comment by twome** [comment] 2019-03-16 05:49
Please see my PR above. It's pretty disappointing that there was no fix or PR for this show-stopper bug that requires literally a 4-character fix, for a 30k star project used by so many people :/

**Comment by devongovett** [comment] 2019-03-29 05:08
This is not a bug. Don't use <script type="module"> with parcel. Parcel expects its generated scripts not to run in strict mode so it can assign to the global object and such. I don't see a reason to use <script type="module"> with Parcel since Parcel already compiles modules to ES5.

In order to work around this error when users mistakenly specify `<script type="module">` in their HTML, we could strip the `type` attribute in the HTML packager when we write the output bundle.

**Comment by tarepan** [comment] 2019-03-29 06:02
Thanks for clarifying the situation.  
I understand this is not bug, but in design.  

I think that instruction of “not to use type=Module” in README.md make this behavior clear for future users, and it will reduce further duplicated issues (type=Module will become common day by day.)

**Comment by philkunz** [comment] 2019-03-29 13:23
Yeah no. Check out https://central.eu It is a site I built using parcel and lit-element. The moment I remove type=module I get weird errors all over the place.

**Comment by devongovett** [comment] 2019-03-30 03:26
@philkunz what errors? what things? We need details if we are to help you.

**Comment by daniellacosse** [comment] 2019-03-31 00:51
@devongovett ava appears to load tests as esmodules. see https://github.com/parcel-bundler/parcel/issues/2213 - any idea how I can work around this?

**Comment by a-p-f** [comment] 2019-04-03 17:37
@devongovett I think stripping `type="module"` from the output script tag is a good solution.

My usage of parcel is not quite as intended. I prefer to write completely valid js/css that runs in modern browsers, and dev using a simple static server and modern browser (with no build step). I want to use parcel only for producing production builds (both to compile to ES5 for older browsers, and to concatenate small scripts). 

Since parcel doesn't concatenate multiple script tags from a single html page, you have to `import` them from another js file. But the only way to get that to work in development without a build step is to use `type="module"` (alternatively, if parcel would bundle consecutive `<script>` tags in an html file, that would also work - but it seems like a bigger change).

I know my use case isn't as intended, but I think it has a lot of merit, and parcel very nearly supports it.

**Comment by twome** [comment] 2019-04-03 18:17
@a-p-f Yep, auto-stripping `type="module"` is ready in PR #2872; just waiting for an unrelated fix #2842 which will stop the CI giving (probably) false negatives for all current PRs. 

In the long term I still think it'd be handy for future-proofing to let Parcel's output `require` scaffolding execute in an ES6 / ES module context [#2809], especially for your use-case where the source code should be totally valid/correct *before* introducing Parcel for production, but at least this should kick the can pretty far down the road.

**Comment by emilsedgh** [comment] 2019-09-09 11:12
This basically means that bundles created from parcel cannot be loaded using browser or Systemjs and somehow cripples the usage. Right?

My usecase is that I have a bunch of _plugins_ which I have bundled using Parcel and I want to import them dynamically on-demans.

Doing that using browser's `import()` or Systemjs fails due to this error.

**Comment by nestarz** [comment] 2019-10-12 13:09
How should I pack my library using Parcel for an ESM compatible loading ?
I want to do: 
`parcel index.js`
then from an other project that is build-step-less do:
```<script type="module>
import { Foo } from 'libraryBuildWithParcel.js';
</script>```
without having this error ?
`Uncaught ReferenceError: parcelRequire is not defined` or `Uncaught SyntaxError: The requested module '/libraryBuildWithParcel.js' does not provide an export named 'Foo'`

**Comment by mischnic** [comment] 2019-10-12 16:34
@nestarz This will be possible with Parcel 2 (and it's already implemented).

**Comment by nestarz** [comment] 2019-10-13 11:05
Thanks, but what is the command then using parcel@v2 to build to an esm format ?

**Comment by mischnic** [comment] 2019-10-13 11:10
With alpha 2 (which should be released in the next couple of days), you can do
```html
<script type="module" src="index.js">
```
and `index.js` will automatically be emitted as an ES module.

Or if you want to build a library, specify it via `package.json#targets.name.outputFormat`:
package.json
```json
{
	"main": "dist/index.js",
	"targets": {
		"main": {
			"outputFormat": "esmodule"
		}
	}
}
```
(and running something like `parcel build src/index.js`)

**Comment by nestarz** [comment] 2019-11-04 20:56
Do you know why when I use the new alpha version to buld my module using the exact configuration you gave above and running `parcel build src/index.js` I only get this into my index.es.js file :

```js
function e(e){return e&&e.__esModule?e.default:e}e("/ComposableMap.b82f9cb5.vue"),e("/Geographies.14547339.vue"),e("/Geography.e35469fc.vue"),e("/Graticule.0838882e.vue"),e("/Sphere.d770e515.vue"),e("/Marker.d965d479.vue"),e("/Line.328080d5.vue"),e("/Annotation.01188279.vue");
```

**Comment by mischnic** [comment] 2019-11-04 21:25
@nestarz Vue support wasn't yet ported to Parcel 2 yet: https://github.com/parcel-bundler/parcel/issues/3364

**Comment by jluisgarcia** [comment] 2020-05-02 21:31
Can this issue and issue #4389 be merged?

**Comment by SteveALee** [comment] 2020-07-09 14:43
OK so I commiting the sin of commenting on a closed issue - but...

My use is to use native ES modules for dev and then bundler for production for older browsers. I also happen to be using snowpack.

If you say Parcel will not work in this case without rewriting the script include structure between dev and deploy it cannot be used. :(

While I get the error everyhting seems to work. So does the error matter?

**Comment by SteveALee** [comment] 2020-07-09 14:45
if you strip <script type="module">  you need to add `defer` to get the same behaviour

**Comment by talentlessguy** [comment] 2020-08-14 00:14
> With alpha 2 (which should be released in the next couple of days), you can do
> 
> ```
> <script type="module" src="index.js">
> ```
> 
> and `index.js` will automatically be emitted as an ES module.
> 
> Or if you want to build a library, specify it via `package.json#targets.name.outputFormat`:
> package.json
> 
> ```json
> {
> 	"main": "dist/index.js",
> 	"targets": {
> 		"main": {
> 			"outputFormat": "esmodule"
> 		}
> 	}
> }
> ```
> 
> (and running something like `parcel build src/index.js`)

doesn't work with TypeScript :thinking: 

```html
   <!-- This script tag will get a reference to the bundle with targetting your defined browser target -->
      <script nomodule src="src/main.ts"></script>
      <!-- This script tag will get a reference to the esmodule bundle -->
      <script type="module" src="src/main.ts""></script>
```

error:

```
Uncaught ReferenceError: assignment to undeclared variable parcelRequire
    parcelRequire http://localhost:3000/main.b0a109ad.js:112
    <anonymous> http://localhost:3000/main.b0a109ad.js:120
```

**Comment by sippeangelo** [comment] 2020-09-22 17:10
I'm not using `type="module"` anywhere yet I'm getting this error. wtf am I doing wrong?!

**Comment by psytron** [comment] 2020-09-26 15:58
Observation: This issue can be hackishly solved by inserting any regular script tag ( not type=module ) before your ES6 style type=module index file script tag.  This will enable you to keep the primary entry point file as a type=module without getting these errors. Without it Parcel still generates these errors.

**Comment by einarpersson** [comment] 2020-09-26 18:17
I get this error whether I use `type="module"` or not. And the weird thing is that it only appears when I deploy it to [vercel](https://vercel.com/). But it works with `npm start` locally. And it only happens if `index.js` includes an import statement.

**Comment by TimDaub** [comment] 2020-10-30 12:58
For me, this error also happens when I put a `defer` tag on my `<script>`. I used to just add the `var parcelRequire` trick, but it seems not to work anymore. Does anyone have an idea how to reliably fix this?

**Comment by EmranMR** [comment] 2020-11-28 13:10
Ok so I am new to parcel. This is how I got into trouble like many of you.... it's quite an annoying bug!🤦‍♂️

- I initiated the parcel on my html file with **type="module"** in my script tag, as you would do. Now that would **mess everything up!** do NOT do this. Once that happens you need to follow these steps to reverse:

 do **NOT** do `<script type="module" src="./main.js"></script>`

**How to Fix/Reverse?**

1.  You need to **stop parcel** in your CLI
2. **Delete** _.parcel-cache_ folder in your directory which was created when you ran the `parcel start| parcel serve...`
☝️ - **THIS IS VERY IMPORTANT OR _DEFER_ AND _ASYNC_ attributes won't WORK** ☝️
3. **Delete** _type="module"_ from your index.html
4. replace with either
- `<script defer src="./main.js"></script>`
- `<script async src="./main.js"></script>`
- or just dump the tag old fashion way, to the bottom of your html
5. run the parcel serve again and you are all good to go, auto refresh for everything back on! 👍

Since this is a bug that has been haunting people since 2018, and the index.html in the _dist_ folder is dynamically produced, why dont we somehow make parcel to remove **type="module"** in the html file when it encounters. Also another bug is when it generates the script tag in the dynamically generated html file in _dist_ folder, Parcel adds an **empty string** to the _async_ or _defer_ attribute.... img below👇

<img width="113" alt="image" src="https://user-images.githubusercontent.com/11975985/100516209-3e8aff80-317a-11eb-9592-26a2f389017c.png">🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️


- MacOS BigSur
- Editor VSCode
- Parcel v.2.0.0 beta1

**Comment by OxiBo** [comment] 2020-11-29 02:35
When I remove type="module", github pages does not show any styles on my page

**Comment by mellonis** [comment] 2020-11-29 10:27
> 3. **Delete** _type="module"_ from your index.html

One does not simply delete _type="module"_ from the code. Especially if you want to use native ES modules.

I have strong believe that _defer_ and _async_ attributes do not give us that — they do not provide module isolation, that's why it's impossible to use imports there. 

When you delete _type="module"_, you loose power of native ES modules.

I think that it's good if some web app can work in modern browsers "as is", without a preprocessing. When I use ES modules, modern browsers understand how to process them.

The problem is: when I add the parcel bundler, all goes wrong.

**Comment by mellonis** [comment] 2020-11-29 10:31
I used [this workaround](https://github.com/parcel-bundler/parcel/issues/1401#issuecomment-424501260).

**Comment by EmranMR** [comment] 2020-11-29 10:45
> I used [this workaround](https://github.com/parcel-bundler/parcel/issues/1401#issuecomment-424501260).

Thank you so much for pointing this out by @dfkaye from this thread.  Much better and more elegant fix, without losing the power of type module! 

If only this was magically fixed in V2..

**Comment by kungfooman** [comment] 2021-03-08 14:41
Will Parcel ever support ES6? Issue open since 2018, *check clock*, it's three years by now

**Comment by talentlessguy** [comment] 2021-03-08 15:03
@kungfooman parcel v2 supports type=module

**Comment by kungfooman** [comment] 2021-03-08 16:01
@talentlessguy Did you try that yourself? I just installed `parcel@next` now with this command line:

```parcel watch --public-url . ./src/examples_pc/hokusai.ts --no-hmr --dist-dir build --target es6```

But it still produces same error as in this issue

**Comment by DeMoorJasper** [comment] 2021-03-11 09:24
@kungfooman there's an example in this thread on how to do this https://github.com/parcel-bundler/parcel/issues/1401#issuecomment-541409113

**Closed by DeMoorJasper** 2021-03-11 09:24 UTC
Labels: :pray: Help Wanted, :raising_hand_woman: Feature, ✨ Parcel 2

**Comment by doggy8088** [comment] 2022-03-12 14:31
Add a `<script>var parcelRequire;</script>` to the `<head>` solve this issue for me. I have to use `type="module"` with Parcel because I'm using TypeScript.

**Comment by mukaofssn** [comment] 2022-06-28 13:02
> Add a `<script>var parcelRequire;</script>` to the `<head>` solve this issue for me. I have to use `type="module"` with Parcel because I'm using TypeScript.

@doggy8088 which version are you using this fix for?

**Comment by doggy8088** [comment] 2022-06-28 16:52
@mukaofssn `1.12.5`
