### ISSUE TITLE
Dynamic import of protocol-less resource fails

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/parcel#2357] opened 2018-12-04 19:28 UTC
# 🐛 bug report

Having a dynamic `import('//use.fontawesome.com/releases/v5.5.0/css/all.css');` fails with
> Cannot resolve dependency '//use.fontawesome.com/releases/v5.5.0/css/all.css' at '/use.fontawesome.com/releases/v5.5.0/css/all.css'

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero config, everything at the latest versions.

## 💁 Workaround

Force-add `https:`.

**Comment by DeMoorJasper** [comment] 2018-12-06 10:11
Seems like a duplicate of https://github.com/parcel-bundler/parcel/issues/2358

**Closed by DeMoorJasper** 2018-12-06 10:11 UTC

**Comment by dandv** [comment] 2018-12-11 07:58
Confirming [the fix](https://github.com/parcel-bundler/parcel/commit/7a540fc4cc2511f749f3a687ce342000953cfcec) for protocol-less JS dynamic importing works. Thanks!
