### ISSUE TITLE
@babel/preset-env options ignored

### ISSUE THREAD

**Issue by hackedd** [parcel-bundler/parcel#5125] opened 2020-09-10 16:17 UTC
# 🐛 bug report

I'm trying to compile some code and automatically add polyfills for IE11. To do this, I'd like to use `@babel/preset-env` with the `useBuiltIns` option set to `usage`, so I don't have to manually specify which polyfills to load. However, this option (and others) are never passed to Babel when I run Parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

src/test-endswith.js:
```js
console.log(String.prototype.endsWith)
console.log("something".endsWith("thing"))
```

.babelrc:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "debug": true,
        "useBuiltIns": "usage",
        "corejs": 3
      }
    ]
  ]
}
```

package.json:
```json
  "browserslist": [
    "last 2 versions",
    "> 0.25%",
    "not dead",
    "ie >= 11"
  ],
```

## 🤔 Expected Behavior

I expect to see debug output from `@babel/preset-env`, and I expect a polyfill for `String.endsWith`.

```
...
Using polyfills with `usage` option:

[.../src/test-endswith.js] Added following core-js polyfill:
  es.string.ends-with { "chrome":"49", "edge":"17", "ie":"11", "safari":"5.1" }

...
```

## 😯 Current Behavior

The debug output is not displayed, and the polyfill is not included.

## 💁 Possible Solution

It looks like env presets are [removed completely](https://github.com/parcel-bundler/parcel/blob/d2dc7c96331f015bdf67ff8286dbb95de2dd6c9b/src/transforms/babel/config.js#L39) from the loaded config, maybe the options could be merged instead?

## 💻 Code Sample

https://gist.github.com/hackedd/c4aa9368d542e75ea9186a59b2d2a1d9

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 12.18.2 |
| npm/Yarn         | 6.14.8 |
| Operating System | |

**Comment by mischnic** [comment] 2020-09-25 08:56
Duplicate of https://github.com/parcel-bundler/parcel/issues/3216

**Closed by mischnic** 2020-09-25 08:56 UTC
