### ISSUE TITLE
Sharp cannot be installed

### ISSUE THREAD

**Issue by Jelenkee** [parcel-bundler/parcel#8239] opened 2022-06-21 17:01 UTC
# 🐛 bug report

When sharp is installed by parcel after adding an image with a width (like "image?width=200"), it fails.
```
Installing sharp...
⠇ Building index.html...
undefined:0


[Error: std::bad_alloc]
```

Additionally my package.json is overwritten.

```json
{
  "devDependencies": {
    "sharp": "^0.29.3"
  }
}

```

## 🎛 Configuration (.babelrc, package.json, cli command)

Before it looked like this

```json
{
  "name": "pa",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@parcel/transformer-less": "^2.6.1",
    "parcel": "^2.6.1"
  }
}

```

## 🤔 Expected Behavior

Sharp is installed correctly and the image is modified.

## 😯 Current Behavior

An error is shown and the program exits.

## 💻 Code Sample

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./ole.less">
    <script src="./lol.ts"></script>
</head>
<body>
    <h2>Bold</h2>
    <div>
        <img src="../../Bilder/P1910624.jpg?width=200" alt="Malz">
    </div>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.1
| Node             | v16.13
| npm/Yarn         | 8.7.0
| Operating System | Linux

**Comment by mischnic** [comment] 2022-06-21 17:23
Duplicate of https://github.com/parcel-bundler/parcel/issues/7126

**Closed as not planned by mischnic** 2022-06-21 17:23 UTC
