### ISSUE TITLE
Parcel keeps rewriting / destroying package.json file

### ISSUE THREAD

**Issue by Annakan** [parcel-bundler/parcel#2978] opened 2019-05-05 14:46 UTC
# 🐛 bug report

In my configuration, parcel rewrite its package.json even though it is told not to ... and since parcel is installed locally (no -g, global is evil) it removes itself from the node module directory, some kind of suicide ...

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json:
```json
{
  "name": "MicroCaps",
  "version": "1.0.0",
  "scripts": {
    "watch": "NODE_ENV=development parcel --out-dir=../assets/static/gen --out-file=main.js --public-url=./assets/ main.js",
    "build": "NODE_ENV=production parcel build --out-dir=../assets/static/gen --out-file=main.js --public-url=./assets/ main.js"
  },
  "private": true,
  "dependencies": {
    "babel-preset-env": "^1.7.0",
    "materialize-css": "^1.0.0",
    "node-gyp": "^4.0.0",
    "node-sass": "^4.12.0",
    "parcel-bundler": "^1.12.3",
    "tar": "^4.4.8",
    "uglify-js": "^3.5.10",
    "uglifycss": "0.0.29"
  }
}
babelrc:
```{
  "presets": ["env"]
}
```
I have very simple main.js
```js
import '../assets/scss/resume.scss'
```
The config files above are in a directory "parcel" 
To reproduce : 
 ```bash
> cd parcel
> npm install
> NODE_ENV=development node_modules/.bin/parcel watch --no-autoinstall --out-dir=../assets/static/gen --out-file=main.js --public-url=./assets/ main.js
```
After a while the package . json will contain

```json
{
  "devDependencies": {
    "sass": "^1.20.1"
  }
}
```
and the build fail because parcel will have killed himself by removing itself from node-modules/.bin ...

and this "sass" dependency is wrong because my package.json already contains     "node-sass": "^4.12.0"

And parcel does that even though --no-autoinstall is set !!!! (even tough this should not be necessary ...)

## 🤔 Expected Behavior

building the dependencies and NOT touching the package.json file.

## 😯 Current Behavior

Parcel self destuct itself after wrongly changing the package.json file into the aformentionned file..

On the other hand I can clearly see a step "building package.json file" so ... parcel really intend to misbehave ...

```
(microcaps_site) ~/.../microcaps/parcel >>> NODE_ENV=development node_modules/.bin/parcel watch --no-autoinstall --out-dir=../assets/static/gen --out-file=main.js --public-url=./assets/ main.js           ±[●●●][master]
🚨  Cannot find module '../builtins/hmr-runtime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.require.resolve (/home/gryom/Projects/microcap_site/MicroCaps/themes/microcaps/parcel/node_modules/v8-compile-cache/v8-compile-cache.js:162:23)
    at JSPackager.end (/home/gryom/Projects/microcap_site/MicroCaps/themes/microcaps/parcel/node_modules/parcel-bundler/src/packagers/JSPackager.js:215:17)
    at Bundle._package (/home/gryom/Projects/microcap_site/MicroCaps/themes/microcaps/parcel/node_modules/parcel-bundler/src/Bundle.js:222:20)
```

## 💁 Possible Solution

None I can see

## 🔦 Context

Tryng to build a theme for the Lektor static cms engine

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.13.0
| npm/Yarn         |6.9.0
| Operating System | linux manjaro

**Comment by devongovett** [comment] 2019-05-05 17:09
Parcel falls back to `sass instead of `node-sass` if an error occurs while requiring it. See https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/assets/SASSAsset.js#L105. So it seems like either node-sass is not installed, or there is some error while requiring it, e.g. it was built for a different node version maybe. You could put a debugger or console log on that line to see the error.

Then it will try to install sass if it is not already installed. `—no-auto-install` only affects code dependencies, things you import or require, not dev dependencies.

**Comment by Annakan** [comment] 2019-05-05 19:38
Thanks for your answer I will check and rebuild the whole node-module and verify version consistency.
Still for me the main problem is that parcel takes great liberties with the package.json file to the point of destroying it. Why does it do that ?

**Comment by devongovett** [comment] 2019-05-06 01:15
I'm not sure what's going on there. Parcel certainly doesn't write to package.json, but it does call yarn or npm to install packages, which may write to package.json. Unsure why it would overwrite the whole thing rather than adding the new package... I've never seen that happen before.

**Comment by Wassasin** [comment] 2019-05-07 09:14
Same here, but I'm using yarn+typescript and the only dependency left afterwards is typescript. Weirdly enough the debug log shows npm working, and afterwards a package-lock.json is created. Even though I'm exclusively using yarn and only have a yarn.lock file.

[parcel-debug-2019-05-07T09:09:00.390Z.log](https://github.com/parcel-bundler/parcel/files/3151773/parcel-debug-2019-05-07T09.09.00.390Z.log)

**Comment by Wassasin** [comment] 2019-05-07 09:37
Just bisected what causes this, and I'm importing and using a function from a folder with cross-project code that lies above the package.json scope. I typically do this only for typescript types, to share them between frontend and backend. Apparently parcel breaks when I do this for actual code that is emitted into a bundle. Note that when I only import the function and not use it, this problem does not occur.

**Comment by bertfreudenberg** [comment] 2019-05-14 18:16
I've seen my package.json being repeatedly destroyed too (overwritten by an empty one with just a single dependency in it). This happened when importing out-of-project JS files using ../../.. (as I thought was the recommended way for mono-repos).

My workaround is to use npm-level package links (`npm i ../package`) so the import statements do not have ../../.. paths. (However, this triggers bug #1838)

**Comment by inad9300** [comment] 2019-05-16 11:27
I'm also experiencing this kind of Parcel's *suicide*... The `package.json` is completely wrecked after running it. Extremely annoying.

**Comment by inad9300** [comment] 2019-05-16 11:38
My case seems to be the same as @Wassasin's (good catch!), that is, the problem starts occurring once I import a a file from a folder holding code common to server and client. Are we supposed to do something special to achieve this? (Regardless, the outcome of this setup should not be a complete destruction of your dependencies.)

**Comment by mischnic** [comment] 2019-05-16 14:45
@inad9300 it's `--no-autoinstall`: https://parceljs.org/cli.html#disable-autoinstall

**Comment by inad9300** [comment] 2019-05-16 14:53
@mischnic I know.

**Comment by inad9300** [comment] 2019-06-07 07:27
Any progress on this front? Destroying people's files at random seems quite a priority to me.

I'm lucky to be using version control, which allows me to "only" lose my local changes, but I cannot imagine someone who hasn't set up one yet losing absolutely everything, or someone having made extensive changes such as preparing some scripts.

**Comment by mischnic** [comment] 2019-06-07 07:50
The first issue here is that Parcel's `localRequire` is passed the asset path to search for the module (e.g. `node-sass`), but with `../style.scss`, the node_modules of your current package is never searched.
The way the package root to install the new package is derived seems strange to me:
```js
  let packageLocation = await config.resolve(filepath, ['package.json']);
  let cwd = packageLocation ? path.dirname(packageLocation) : process.cwd();
```
Furthermore, the npm/yarn detection doesn't work.
```js
packageManager = await determinePackageManager(cwd);
```
And finally, here the package.json is cleared:
```js
  // npm doesn't auto-create a package.json when installing,
  // so create an empty one if needed.
  if (packageManager === 'npm' && !packageLocation) {
    await fs.writeFile(path.join(cwd, 'package.json'), '{}');
  }
```

https://github.com/parcel-bundler/parcel/blob/7ad25fd0958cb39c8595a0d667e9bc0f4c0250f4/packages/core/parcel-bundler/src/utils/installPackage.js#L22-L42

**Comment by dgreensp** [comment] 2019-06-29 04:16
`--no-autoinstall` should definitely disable all messing with package.json.  I just wasted a bunch of time figuring out that it doesn't! :O  For a build tool to mess with my package.json without consulting me is madness, IMHO.

**Comment by YassienW** [comment] 2019-11-18 12:42
`--no-autoinstall` doesn't seem to stop the destruction of package.json.
How can i possibly import files from outside the project?

**Comment by chadmott** [comment] 2020-01-06 23:13
similar to  @bertfreudenberg, when I refactored some API code from the UI, creating a common folder, and then importing from ../../../ I get erratic behavior with parcel

For me, it was very odd typescript behavior (Array.entries() was not working??) No browser error reported. Some stuff was working, parcel reported no error. 

tried to resolve by moving the UI folder outside of my larger "project" folder to isolate, and that's when my package.json started getting deleted. 

I fixed it in my setup by just symlinking the ../../../ to the UI folder as one would typically expect, but this was a very odd bug, hopefully this helps others.

**Comment by lorissikora** [comment] 2020-02-08 20:11
My situation is similar to the ones described above:
- Typescript
- Files outside of directory other than root
- Files being imported with relative paths (`import x from '../../..'`)

When running parcel my `package.json` first goes empty (`{}`) and then results in a file only containing a single dev-dependency (typescript).
Managed to temporarily fix it by using a symlink, however would definitely prefer a solution without.

Is there any news to this bug?

**Comment by lewislbr** [comment] 2020-03-29 10:54
Related to this, could the autoinstall instead of `yarn install` be `yarn install --frozen-lockfile`?

**Comment by theaceofthespade** [comment] 2020-07-16 22:37
This is an absurd bug - on my system running watch seems to send it into some sort of building-death-spiral.

**Comment by DeMoorJasper** [comment] 2020-07-18 11:30
gonna close this as this no longer really happens in Parcel 2, also opened up a PR to make the autoinstall behaviour even less extreme

**Closed by DeMoorJasper** 2020-07-18 11:30 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, Autoinstall

**Comment by neXorianus** [comment] 2021-01-13 12:47
> gonna close this as this no longer really happens in Parcel 2, also opened up a PR to make the autoinstall behaviour even less extreme

Is it save to upgrade to Parcel 2?
As far as i see, there is no stable build, only the `@next` install.

**Comment by winrid** [comment] 2021-07-22 21:45
Also running into this... not able to upgrade to Parcel 2 yet. As of now the project in question is just broken....

**Comment by winrid** [comment] 2021-07-22 21:53
Okay, the cause for us is:

- Importing a file from outside the project. We are bundling a project that uses a common "core" set of utilities across extensions

To reproduce:

Clone at this comment: https://github.com/FastComments/fastcomments-debug/commit/fb4a550483de3c588acd0a1a72ba6eac5b152b34

Install dependencies and `npm run build`.

**Workaround:**

- Create a new package.json in the "common" folder with the typescript etc dependencies...

I know this is a closed issue, and maybe upgrading to Parcel 2 fixes it, but upgrading caused random errors. Hope this helps someone!

**Comment by michaelpumo** [comment] 2021-12-20 19:15
For what it's worth, I'm getting this exact same issue.

I can run `npm run dev` but not `npm run build`. See my `package.json` below:
```
{
  "name": "prosperly",
  "version": "1.0.0",
  "author": "Michael Pumo",
  "source": "./src/index.pug",
  "scripts": {
    "watch-css": "parcel watch src/assets/css/app.css --dist-dir dist/css --public-url /css",
    "dev": "npm run serve & npm run tailwindUI",
    "serve": "parcel serve ./src/index.pug --no-cache",
    "build": "parcel build",
    "tailwindUI": "tailwind-config-viewer"
  },
  "dependencies": {
    "gsap": "^3.9.0",
    "tailwindcss": "^3.0.7"
  },
  "devDependencies": {
    "@parcel/transformer-pug": "^2.0.1",
    "autoprefixer": "^10.4.0",
    "parcel": "^2.0.1",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0.2",
    "postcss-nested": "^5.0.6",
    "postcss-url": "^10.1.3",
    "prettier": "2.5.1",
    "tailwind-config-viewer": "^1.6.3"
  }
}
```

If I run the build command, Parcel absolutely nukes the `package.json` file and leaves the Pug transformer there. It's also malformed to invalid JSON.

No idea how to solve this!

**UPDATE**:
This seems to solve the issue: https://github.com/parcel-bundler/parcel/issues/7271#issuecomment-964324908
