### ISSUE TITLE
Watcher stops watching dependant scss files after syntax error

### ISSUE THREAD

**Issue by bdukes** [parcel-bundler/parcel#9292] opened 2023-10-04 21:45 UTC
# 🐛 bug report

When using `parcel watch ./src/styles.scss` and introducing a syntax error in an `scss` file imported by `styles.scss`, the watcher will no longer see changes to the imported file.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
{
  "name": "parcel-demo",
  "scripts": {
    "start": "parcel watch ./src/index.scss"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.9.3",
    "parcel": "^2.9.3"
  }
}
```

## 🤔 Expected Behavior

Changes to imported file trigger a rebuild.

## 😯 Current Behavior

Changes to imported file trigger a rebuild until there's a syntax error, and then no longer trigger a rebuild.

## 💻 Code Sample

1. Clone https://github.com/bdukes/parcel-issue-9292
2. `npm install`
3. `npm start`
4. Add an extra `}` character to `src/another.scss`
5. Save `src/another.scss`, notice error output
6. Remove extra `}` character
7. Save `src/another.scss`, notice error output does not change
8. Save `src/index.scss`, notice output now changes to show success

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3 |
| Node             |  18.18.0 |
| npm         |  9.8.1 |
| Operating System | Windows 11 (also reproduced on MacOS Sonoma 14.0) |

**Comment by mischnic** [comment] 2023-10-06 08:37
Unfortunately a duplicate of https://github.com/parcel-bundler/parcel/issues/7374 . There's not much Parcel can do here without more support from the Sass compiler

**Closed as not planned by mischnic** 2023-10-06 08:37 UTC
