### ISSUE TITLE
Got unexpected undefined - when passing an empty <img> source

### ISSUE THREAD

**Issue by flppv** [parcel-bundler/parcel#7354] opened 2021-11-23 22:46 UTC
![image](https://user-images.githubusercontent.com/6984143/143140607-7e8e49b1-f686-436a-b741-8c349d8cd216.png)

When I pass an image with an empty src attribute like `<img src="" alt="" />` this error is thrown. 
It was unclear why it happened until I figured it out by manual blocks deletion. I think that bundler either should throw that error happened because of an empty attribute, or work with it (AFAIK it's not restricted by HTML to have an empty src).

**Comment by mischnic** [comment] 2021-11-24 09:10
Duplicate of https://github.com/parcel-bundler/parcel/issues/7076

The spec says

> The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces

(https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-src)

**Closed as completed by mischnic** 2021-11-24 09:10 UTC
