### ISSUE TITLE
virtual-modules need real file on filePath

### ISSUE THREAD

**Issue by pYr0x** [parcel-bundler/parcel#7107] opened 2021-10-16 11:25 UTC
# 🐛 bug report

tried to create a virtual module like descripted here: https://parceljs.org/plugin-system/resolver/#virtual-modules
as the documentation said, i have to return a `filePath`.  so i did and the file does not exists, because it is a virtual module.

parcel complaining, that the file does not exists:
```
× Build failed.

Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\foo.js'
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.stache": ["parcel-transformer-stache"]
  },
  "resolvers": ["parcel-resolver-stache-import-module", "..."]
}
```

## 🤔 Expected Behavior

the virtual module does not need a real file on the filesystem

## 😯 Current Behavior

`Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\foo.js'`

## 💻 Code Sample

```
import {Resolver} from '@parcel/plugin';
import path from 'path';

export default new Resolver({
  async resolve({specifier}) {
    if (specifier === 'parcel-stache-import-module') {
      return {
        filePath: path.join(__dirname, 'foo.js'),
        // language=JavaScript
        code: `export default "This is a special module!";`
      };
    }
    return null;
  }
});

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2
| Node             | v12.16.3
| npm/Yarn         | 8.1.0
| Operating System | Windows 10

**Comment by mischnic** [comment] 2021-10-18 19:41
This error only happens (at least for me, and I have run into this in past) if there is some error in the returned code. Then the logic to generate the codeframe tries to read from disk. E.g. with a syntax error
```js
	code: `export default "This is a special module!`,
```

<br>

Duplicate of https://github.com/parcel-bundler/parcel/issues/6874

**Closed as completed by mischnic** 2021-10-18 19:41 UTC
