### ISSUE TITLE
Unicode variable names don't build

### ISSUE THREAD

**Issue by GeorchW** [parcel-bundler/parcel#9695] opened 2024-05-04 15:43 UTC
# 🐛 bug report

We have [this library](https://github.com/plotly/d3/blob/f9a7ecc9756b74946f9ce04a842a1e174bd4d5d6/src/math/random.js#L2) as a transitive dependency, and it won't build with parcel since it uses Unicode variable names. I can reduce the example to this:

```js
let ü = "ü";
alert(ü);
```

Building this with `parcel build example.js` fails with this error code:

```
@parcel/optimizer-swc: Expected unicode escape
```

When starting with `parcel example.js`, the output in the `dist` folder contains these relevant lines:

```js
let \xfc = "\xfc";
alert(\xfc);
```

The unicode is converted to escape sequences regardless of where it occurs in the source, which is not correct.

The bug prevents us from using Plotly with Parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

Clean reproduction in bash:

```bash
mkdir 2024-05-04-parcel-unicode-repro
cd 2024-05-04-parcel-unicode-repro
echo 'let ü = "ü"; alert(ü)' > repro.js
yarn add parcel
yarn run parcel build repro.js
```

The error message here is slightly different:

```
@parcel/optimizer-swc: `let` cannot be used as an identifier in strict mode
```

It goes away when renaming the `ü` to `u` though.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node | 18.20.2
| Yarn | 1.22.19
| OS | Linux

**Comment by mischnic** [comment] 2024-05-05 07:12
Duplicate of https://github.com/parcel-bundler/parcel/issues/9607, this will be fixed with #9574

**Closed as not planned by mischnic** 2024-05-05 07:12 UTC
