### ISSUE TITLE
Should async await work out of the box?

### ISSUE THREAD

**Issue by vvo** [parcel-bundler/parcel#2442] opened 2018-12-20 09:04 UTC
# 🙋 feature request

I would like to be able to use async await without having to configure anything. Just like the parceljs website says it: Blazing fast, **zero configuration web application bundler**.

I understand the "zero configuration" part is marketing-ish and that ultimately you always endup configuring parcel a bit in case of exotic usage. Though a lot less than webpack in my experience for sure!

When I first tried to use parcel yesterday, out of three hours of setup I spent 80% of my time struggling with making async/await expressions work. While I believe they are nowadays the "new" norm (and so, not exotic) on how to write asynchronous code and even what we teach to new JavaScript developers. Thus I believe async/await should work out of the box using parcel and that's not the case today.

## 🤔 Expected Behavior

**index.js**
```js
const test = async () => {
  await Promise.resolve();
}

test();
```

This should work without any error.

## 😯 Current Behavior

This triggers an error in console.

```txt
Uncaught ReferenceError: regeneratorRuntime is not defined
    at parcel-example.e31bb0bc.js:117
    at Object.parcelRequire.index.js (parcel-example.e31bb0bc.js:136)
    at newRequire (parcel-example.e31bb0bc.js:49)
    at parcel-example.e31bb0bc.js:81
    at parcel-example.e31bb0bc.js:107
```

## 💁 Possible Solution

**.babelrc**
```json
{
  "plugins": ["@babel/plugin-transform-runtime"]
}

```

## 🔦 Context

(Read description)

## 💻 Examples

Here's a repository reproducing the error: https://github.com/vvo/parcel-async-await-test

**Comment by mischnic** [comment] 2018-12-20 12:53
A duplicate of #1762. But *zero configuration* is a good point. Can't babel determine by itself if the runtime is needed? (If not, there should at least be a more helpful warning.)

**Closed** 2018-12-21 19:22 UTC

**Comment by DeMoorJasper** [comment] 2018-12-21 19:23
There have been a couple issues about this.
Any help with adding a more helpfull error message for this (or automatically including babel-polyfill [note this is an experimental feature in babel currently so not sure if we should even bother to work on this]) is very welcome :)

**Comment by crisleo94** [comment] 2020-02-11 20:21
Having the same trouble, if you get here for the same reason, just go here [https://babeljs.io/docs/en/babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) you'll be able to solve this issue!
