### ISSUE TITLE
css models a bit strange

### ISSUE THREAD

**Issue by programmer-yang** [parcel-bundler/parcel#1529] opened 2018-06-13 09:33 UTC
i used less and turned on the CSS models
i installed the `postcss-modules`
this is my configuration
```
{
  "modules": true
}

```
now the question is：
after modifying the less file, the style fails

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.2
| Node             |8.11.1
| Yarn         |1.6.0
| Operating System |

**Comment by QAQLiuCong** [comment] 2018-06-13 10:39
Me too.Delete "modules": true this is no problem.My configuration
{
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}

**Comment by DeMoorJasper** [comment] 2018-07-24 20:38
Duplicate of #513 ?

**Closed by DeMoorJasper** 2018-07-24 20:38 UTC
Labels: :grey_question:  Question
