### ISSUE TITLE
Incorrect Module Not found. Possible Quick Fix.

### ISSUE THREAD

**Issue by abjfdi** [parcel-bundler/parcel#8683] opened 2022-12-08 14:20 UTC
# 🐛 bug report
According to NodeJS Docs when describing a module, type = module and main/exports = "./dist/index" etc. Parcel does not look for the exports field in the modules package.json if there is no main field. This results in a module not found error.

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json
```json
{
     "dependencies": {
 			"@sindresorhus/is" : "5.3.0"
    },
    "scripts": {
        "start": "parcel --no-hmr ./public/index.html",
        "build": "parcel build --no-scope-hoist --no-content-hash ./public/index.html",
    },
    "browserslist": "> 0.5%, last 2 years, not dead",
    "alias": {
        "react/jsx-runtime": "react/jsx-runtime.js"
    }
}
```

## 🤔 Expected Behavior
The module should be found as the exports field exists. And my build should execute.

## 😯 Current Behavior
Does not build.

## 💁 Possible Solution
When looking for the main field in a package.json if it doesn't exist use the exports field.

## 🔦 Context
I'm trying to use a module that has a valid Package.json according to these [NodeJS docs](https://nodejs.org/docs/latest-v17.x/api/packages.html#nodejs-packagejson-field-definitions). But Parcel doesn't recognize it as valid.

The package uses the exports field.
Parcel uses the main field.
NodeJS says both are valid.

## Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.1, 2.8.0, 2.7.2
| Node             |  16.6.0
| npm/Yarn         |  PNPM
| Operating System | Windows 11

**Comment by abjfdi** [comment] 2022-12-08 14:23
For extra context, this is not a major issue for me atm. Because I wrote a postinstall script to add the main field to that modules package.json.

```javascript
const path = require("path");
const fs = require("fs");

const isDir = path.join(__dirname, "./node_modules/@sindresorhus/is/");
const packagePath = path.join(isDir, "./package.json");

const packageJSON = JSON.parse(fs.readFileSync(packagePath, { encoding: "utf8" }));
packageJSON.main = "./dist/index.js";
fs.writeFileSync(packagePath, JSON.stringify(packageJSON, null, 4), { encoding: "utf8" });
console.log("Finished adding the main tag to @sindresoruhs/is");
```

**Comment by devongovett** [comment] 2022-12-08 14:46
Duplicate of #4155

**Closed as completed** 2022-12-08 14:47 UTC
