### ISSUE TITLE
The generated code is not set let, causing an error

### ISSUE THREAD

**Issue by maskletter** [parcel-bundler/parcel#3231] opened 2019-07-14 11:26 UTC
![image](https://user-images.githubusercontent.com/15777183/61182910-99e34d00-a66c-11e9-9cae-9b988506319a.png)

I am writing a conversion tool, the project is calling js directly, so I can't set the default value for parcelRequire.

# 🙋 Feature request

I want to add a let for parcelRequire in the conversion project.

## 🤔 Expected Behavior

Is there any way to achieve it?
![image](https://user-images.githubusercontent.com/15777183/61182952-3ad20800-a66d-11e9-826d-114d5afeef36.png)

## 😯 Current Behavior
This converted js is a total entry, not a web project, so I can't set let parcelRequire = undefined;, nor can I use globalThis

**Comment by mischnic** [comment] 2019-07-14 20:10
I think this is a duplicate of https://github.com/parcel-bundler/parcel/issues/1401, though I don't understand the context in this case (how the current behaviour is causing a problem).

**Comment by maskletter** [comment] 2019-07-15 00:55
> I think this is a duplicate of #1401, though I don't understand the context in this case (how the current behaviour is causing a problem).

I am not compiling a web, node, or electron environment.Is a unique environment,

![image](https://user-images.githubusercontent.com/15777183/61191520-2da13180-a6de-11e9-9ccd-1892c3a7ade5.png)
Current code

**Closed** 2019-07-16 12:53 UTC
Labels: :clock1: Waiting, :grey_question:  Question
