### ISSUE TITLE
Module CSS + HMR bug

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1066] opened 2018-03-25 09:24 UTC
On each css update the class names are not updated in js file

https://github.com/FDiskas/parcel-scss-bug

**Comment by joakin** [comment] 2018-03-27 08:13
Could be a duplicate of #809

**Comment by vyteniskuciauskas-home24** [comment] 2018-11-08 14:14
It could be possible to solve this, by triggering another process if some style was changed.
And that process would search for files where that style was imported and touch them to trigger the rebuild

**Closed** 2024-07-01 03:00 UTC
Labels: :raising_hand_woman: Feature, HMR
