### ISSUE TITLE
Uncaught TypeError: (xxxx) is not a function

### ISSUE THREAD

**Issue by makmm** [parcel-bundler/parcel#1656] opened 2018-07-03 10:53 UTC
# 🐛 bug report

When I start the parcel dev server after a night or something, and open up my browser, randomly I get a "Uncaught TypeError: **** is not a function". It happend with 3 different things the past days, and it's getting annoying. Workaround `rm -rf .cache dist`

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": ["stage-0", "env", "react"],
  "plugins": ["transform-class-properties"]
}
```

package.json
```js
{
  "name": "frontend-graphql",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "apollo-cache-inmemory": "^1.2.2",
    "apollo-client": "^2.3.2",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.8",
    "apollo-link-error": "^1.1.0",
    "apollo-link-http": "^1.5.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "react": "^16.4.0",
    "react-apollo": "^2.1.4",
    "react-dom": "^16.4.0",
    "react-router-dom": "^4.3.1"
  },
  "scripts": {
    "start": "parcel public/index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.9.4"
  }
}
```

## 🤔 Expected Behavior

__not__ error and work correctly

## 😯 Current Behavior

read the report ^^

![image](https://user-images.githubusercontent.com/7550995/42215796-fbd823a0-7e95-11e8-9311-8ce4329e660e.png)

## 💻 Code Sample

https://gitlab.com/homework-manager/hwm-frontend

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4 |
| Node             | 10.5.0 |
| npm/Yarn         | Yarn 1.7.0 |
| Operating System | Arch Linux // kernel 4.17.2-1-ARCH |

**Comment by makmm** [comment] 2018-07-03 10:54
Also, in an (probably?) unrelated issue, most source maps are broken (showing other files, etc)

**Comment by buronnie** [comment] 2018-07-03 15:04
@makmm Do you have to leave the dev server running for a few hours in order to reproduce the issue? I tried it on my side and cannot reproduce it.

**Comment by makmm** [comment] 2018-07-03 20:10
@buronnie It's weird, it mostly happends when I come back other day, turn on my pc and start parcel.

**Comment by makmm** [comment] 2018-07-03 22:41
@buronnie What the heck? I'm sorry, I wrote a comment explaining and it didn't get sent. It doesn't seem to need to wait a few hours. It just happend again but while I was coding, with this error this time (it's like a variant?)
![image](https://user-images.githubusercontent.com/7550995/42247851-0f8f8fb0-7ef9-11e8-99da-163b77414387.png)

**Comment by RobertWHurst** [comment] 2018-07-04 07:01
I've also encountered this quite often. I'm using vue, with pug and scss.

**Comment by alexander-travov** [comment] 2018-07-04 13:06
I run into the same problem:

After removing `.cache` I build my app and everything is working just fine. Then I touch one of the modules (`product.js` in that case), changing nothing in the source, and build output gives me an error.

Diff between builds shows that with cache parcel uses same ids for different modules:

```
without cache < },{... ,"./product":8,"./locator":9}]},{},[1], null)
---
with cache    > },{... ,"./product":9,"./locator":9}]},{},[1], null)
```

Building with `--no-cache` gives correct bundle every time.

@emilniklas in #1596 tells about the same behaviour.

parcel 1.9.4
node 8.11.2
npm 6.1.0
Ubuntu linux

**Comment by agentcooper** [comment] 2018-07-05 08:03
Had the same issue. Downgrading to 1.8.1 helps.

**Comment by safareli** [comment] 2018-07-06 16:39
after downgrading to 1.8.1  and with no cache flag still have such issues

**Comment by RobertWHurst** [comment] 2018-07-06 17:08
@devongovett, I thought I'd ping you here to bring this one to your attention if you haven't seen it yet. Looking at the commit log, it seems like you've done a lot of work in this area.

**Comment by makmm** [comment] 2018-07-07 17:53
Can this be related to the sourcemap issue I'm having?

**Comment by safareli** [comment] 2018-07-09 13:15
On version 1.8.1 If I'm using:
`parcel build --no-minify --no-source-maps --no-cache index.html`

Then output is fine.
But if you remove `--no-minify`:
`parcel build --no-source-maps --no-cache index.html`
Then I see `ReferenceError: e is not defined 551a5bcc-5069-e44a-90de-563f1fa674eb:1:60755`

But on  1.7.1
`parcel build --no-source-maps --no-cache index.html` 

results in similar error:
`ReferenceError: t is not defined 3f5c2c76-cd87-aa43-b9df-72208890eb7b:1:60755`

**Comment by devongovett** [comment] 2018-07-10 07:04
I believe this is related to storing asset ids in the cache. Should be fixed by https://github.com/parcel-bundler/parcel/pull/1694. Would be great if someone could help verify!

**Comment by makmm** [comment] 2018-07-10 20:13
hey @devongovett That's great, how can I help verifying?

**Closed** 2018-07-11 17:12 UTC
Labels: :bug: Bug

**Comment by devongovett** [comment] 2018-07-11 18:17
Released in v1.9.5.

**Comment by azizali** [comment] 2018-07-13 00:39
@devongovett This fixed it for me.

**Comment by joseluisq** [comment] 2020-09-03 08:52
I'm facing a similar issue with Parcel build `v1.12.4` and latest React `v16.13.1`.

```sh
parcel build \
    --no-source-maps \
    --no-autoinstall \
    --no-cache \
        public/index.html
```

```json
  "dependencies": {
    "@ant-design/icons": "^4.1.0",
    "antd": "^4.6.2",
    "classcat": "^4.0.2",
    "geojson": "^0.5.0",
    "identity-obj-proxy": "^3.0.0",
    "leaflet": "^1.6.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-leaflet": "^2.7.0",
    "react-router-dom": "^5.2.0"
  }
```

![image](https://user-images.githubusercontent.com/1700322/92093035-20a83b80-edd3-11ea-98de-bbeea9b732d8.png)

**Comment by kykungz** [comment] 2020-10-13 19:34
@joseluisq Have you solved this problem? I'm using the same version of Parcel and React as yours, and using `antd` too. My errors are on the same line as yours too (`h is not a function`).

**Comment by joseluisq** [comment] 2020-10-13 20:06
@kykungz basically this issue was not addressed properly and should be re-opened.

My "workaround" was just skipping the minify process using the `--no-minify` flag and then invoking Terser directly.

```sh
~> parcel build \
        --no-minify \
        --no-source-maps \
        --no-autoinstall \
        --no-cache \
                public/index.html

~> terser \
        --compress \
        --mangle \
        --toplevel \
        -- dist/app.*.js > dist/app.js
```

It seems like something weird is happening during minify process on Parcel side.

**Comment by garritfra** [comment] 2020-11-02 20:09
@joseluisq how did you manage to embed the script generated by terser into the document?

**Comment by joseluisq** [comment] 2020-11-02 22:00
@garritfra just using a "simple" command to search and replace something like:

```sh
sed -i -E 's/<script src=\"\/app\.(.+)\"><\/script>/<script src=\"app\.js\"><\/script>/g' \
        dist/index.html
```

**Comment by garritfra** [comment] 2020-11-04 20:24
I had some other issues (e.g. seds `-i` flag has a different use on macos), but here's my final workaround:

```bash
parcel build \
    --no-minify \
    --no-source-maps \
    --no-autoinstall \
    --no-cache \
        public/index.html

terser \
    --compress \
    --mangle \
    --toplevel \
    -- dist/src.*.js > dist/app.js

cat dist/index.html

sed -E 's/<script src=\"[\.\/]?\/src\.(.+)\"><\/script>/<script src=\"app\.js\"><\/script>/g' dist/index.html | tee dist/index.html
```

It's unfortunate that this is necessary though.

**Comment by chienniman** [comment] 2023-07-22 10:35
I spent nearly five hours debugging to find the error "C.fontStyle is not defined" in the React src code, but unfortunately, I couldn't find any clues. The issue seems to be related to Parcel encountering an error during code minification. In the 2023 version, you must use `--no-optimize` to disable the optimization in building process.
[parceljs.org/features/cli](https://parceljs.org/features/cli/)
