### ISSUE TITLE
Parcel 2: @parcel/transformer-raw problems

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4174] opened 2020-02-19 11:28 UTC
# 🐛 bug report
*https://github.com/Banou26/parcel-bug-4174*

When using this configuration as per https://github.com/parcel-bundler/parcel/issues/1080#issuecomment-557240449 and https://github.com/parcel-bundler/parcel/issues/501#issuecomment-557240714
`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```

The end build isn't transpiled at all, for example in the repro, the `index.html` imports `index.ts` which contains 

```ts
import './foo.ts'

console.log('foo')
```
and the output build Parcel serves is

`/parcel-test.d7ebec59.ts`

```ts
import './foo.ts'

console.log('foo')
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
`package.json`
```json
{
  "name": "parcel-raw-transform",
  "version": "0.0.1",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.0.0-nightly.116"
  },
  "scripts": {
    "dev": "parcel src/index.html"
  }
}
```

I tried with both the `2.0.0-alpha.3.2` and `2.0.0-nightly.116`

**Comment by mischnic** [comment] 2020-02-19 11:43
`"main": "index.js",` disables node_modules bundling

**Comment by Banou26** [comment] 2020-02-19 12:34
The result is exactly the same with `"main": "src/index.ts"`

**Comment by mischnic** [comment] 2020-02-19 13:19
Use any name for the target except main, browser or module.

**Comment by Banou26** [comment] 2020-02-19 13:39
I've tried again using this config
```json
{
  "name": "parcel-raw-transform",
  "version": "0.0.1",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.0.0-nightly.116"
  },
  "scripts": {
    "dev": "parcel src/index.html --target=appModern"
  },
  "appModern": "dist/browserModern/index.html",
  "targets": {
    "appModern": {
      "engines": {
        "browsers": ["last 1 chrome version"]
      }
    }
  }
}

```
the build in `/dist/browserModern` still only contains
```ts
import './foo.ts'

console.log('foo')
```
and now in addition, even though the logs says `Server running at http://localhost:1234` i'm getting 
```
Request URL: http://localhost:1234/
Request Method: GET
Status Code: 403 Forbidden
```

If i remove `--target=appModern`, then the serving server responds correctly, but i'm still getting the same original problem, which is having this error
```diff
Refused to execute script from 'http://localhost:1234/parcel-test.d7ebec59.ts' because its MIME type ('video/mp2t') is not executable.
```
because the served html file points to a `.ts` file which is not transpiled
`/parcel-test.d7ebec59.ts`
```ts
import './foo.ts'

console.log('foo')
```

**Comment by Banou26** [comment] 2020-02-20 13:08
The problem only happens when there's a  `*` in a `transforms` object property name.
```diff
{
  "extends": "@parcel/config-default",
  "transforms": {
-    "url:*": ["@parcel/transformer-raw"]
+    "url:": ["@parcel/transformer-raw"]
  }
}
```

**Comment by mischnic** [comment] 2020-02-20 13:23
Indeed, it seems like the ts import is matched with `url:*` and therefore runs through the raw transformer only.

**Comment by Banou26** [comment] 2020-02-20 14:08
The problem also happens on normal js files but differently, with js files the bundle actually gets built, but the JS asset is still raw
```js
})({"238cc7072f28c30752fc1f1e9056221e":[function(require,module,exports) {
import './foo.js'

console.log('foo')

},{}],"d347dc37b6ca23899ffbbc32fd87b43f":[function(require,module,exports) {
```

**Comment by Banou26** [comment] 2020-02-20 17:16
Any starting points/guidance on how to try to fix it ?

**Comment by mischnic** [comment] 2020-02-20 17:27
Quite sure the bug is in here:
https://github.com/parcel-bundler/parcel/blob/706a7e647f90c65724f6b3560376c9ffab80eb5e/packages/core/core/src/ResolverRunner.js#L64-L100

At the end `pipeline` should be undefined, but I don't think it is.

**Comment by Banou26** [comment] 2020-02-20 18:58
I tried fixing it, made a PR, but all tests are failing and i can't even run `yarn test` without it throwing instantly either, any idea how i can fix that ?
I posted the error in the PR.

**Comment by mischnic** [comment] 2020-02-20 20:36
Actually, the error seems to be somewhere else, because
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
should really do nothing (this is already specified in the default config).

**Comment by Banou26** [comment] 2020-02-20 20:55
I mean, the PR i made fixed the build & properly transpiled the `url:` into the path value, but it also broke some other tests.
So i don't think i was too far off from the problem there.

**Comment by awvalenti** [comment] 2020-03-08 14:22
My issue is probably the same. Here's a script to reproduce. It happened on Windows and Linux.
```bash
mkdir test
cd test
echo 'contents' > file.txt
echo '<html><body><script src="show.js"></script></body></html>' > index.html
echo 'import content from "./file.txt"; alert(content);' > show.js
npm init -y
npm i -D parcel-bundler
npx parcel index.html --open
```

Should alert contents, but alerts this:
![image](https://user-images.githubusercontent.com/834921/76164610-0f85b700-612f-11ea-95c5-e3da7e78c508.png)

**Comment by mischnic** [comment] 2020-03-08 14:26
@aweary You're using Parcel 1 (where this is correct behaviour). This is about Parcel 2

**Comment by devongovett** [comment] 2021-06-23 06:28
I think this should be fixed by https://github.com/parcel-bundler/parcel/pull/6495 which runs transformers from the next matching pipeline before the url transformer.

**Closed** 2021-06-24 06:25 UTC
Labels: :baby: Good First Issue, :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2
