### ISSUE TITLE
Bad code smell into my appcache manifest plugin

### ISSUE THREAD

**Issue by pierredavidbelanger** [parcel-bundler/parcel#308] opened 2017-12-16 17:07 UTC
This is a kind of 🙋 feature request I guess.

I made, for my own use, a [plugin to generate an appcache manifest](https://github.com/pierredavidbelanger/parcel-plugin-appcache).

This maybe due to the fact that I am a complete Node.js newbe, but I did not find a better way to mess with the final HTML than to [read it from the fs after everything is bundled](https://github.com/pierredavidbelanger/parcel-plugin-appcache/blob/master/index.js#L19) and [write it again after transformation](https://github.com/pierredavidbelanger/parcel-plugin-appcache/blob/master/index.js#L21).

It feels like a hack, and I guess that the next time I add a plugin that also mess with the generated HTML I will encounter a problem.

My question is: is there a better way of doing this ?

Thank you!

**Comment by DeMoorJasper** [comment] 2017-12-16 18:01
I think this should probably be asked in the slack chat
Seems like a duplicate of #251, this is a question to improve the API?

**Comment by pierredavidbelanger** [comment] 2017-12-16 23:05
Honestly, I think I was looking for advice (since my guess is that the plugin API is fine, and I should instead improve my own code). But you are right, the chat would be a better place for this kind of question.

And, if the plugin API could be improved in a way one can intercept (with stream transformation for example) the builtin assets generation, than indeed, my question can feels like a duplicate of #251.

Anyways, since my plugin is good enough for me right now, you can close this issue if you want.

I will follow this project and see if I will be able to improve things in the future.

**Comment by DeMoorJasper** [comment] 2017-12-16 23:11
Alright, i'll close it for now, the api will definitely improve in the future.

**Closed by DeMoorJasper** 2017-12-16 23:11 UTC
Labels: #Question
