### ISSUE TITLE
build compile wrong

### ISSUE THREAD

**Issue by suhaotian** [parcel-bundler/parcel#7213] opened 2021-10-29 11:04 UTC
# 🐛 bug report

```
🚨 Build failed.

@parcel/optimizer-terser: Unexpected token
punc «.», expected punc «(»
```
![2021-10-29 at 7 00 PM](https://user-images.githubusercontent.com/6512574/139423603-234b846c-e99f-4ffb-b35f-a564337ee53b.png)

![2021-10-29 at 6 59 PM](https://user-images.githubusercontent.com/6512574/139423537-8a626df0-dd6c-4ab8-b4d6-85e2d419bd1f.png)

## 💁 Possible Solution

If I change `function exports` the `exports` to other name build pass:

![2021-10-29 at 7 01 PM](https://user-images.githubusercontent.com/6512574/139423697-426906bd-c83e-4d7f-a9a1-d4adf4b350f4.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2
| Node             | 14.0.0
| npm/Yarn         | yarn
| Operating System | MacOS

**Comment by mischnic** [comment] 2021-10-29 11:31
Duplicate of https://github.com/parcel-bundler/parcel/issues/7090

**Closed as completed by mischnic** 2021-10-29 11:31 UTC
