### ISSUE TITLE
Scope hoisting breaks with d3-scale

### ISSUE THREAD

**Issue by jsonkao** [parcel-bundler/parcel#4554] opened 2020-04-30 20:41 UTC
# 🐛 bug report

Building with experimental hoisting enabled breaks when importing [`d3-scale`](https://github.com/d3/d3-scale).

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "parcel build script.js",
    "build-experimental": "parcel build script.js --experimental-scope-hoisting"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "d3-scale": "^3.2.1"
  }
}
```

## 🤔 Expected Behavior

`npm run build` (building without tree shaking) runs fine. Enabling tree shaking should run normally as well.

## 😯 Current Behavior

Enabling tree shaking results in this error:

```
$ npm run build-experimental

> @ build-experimental /Users/jasonkao/test
> parcel build script.js --experimental-scope-hoisting

🚨  node_modules/d3-format/src/locale.js does not export 'default'
    at replaceExportNode (/Users/jasonkao/test/node_modules/parcel-bundler/src/scope-hoisting/concat.js:55:13)
    at ReferencedIdentifier (/Users/jasonkao/test/node_modules/parcel-bundler/src/scope-hoisting/concat.js:342:20)
    at newFn (/Users/jasonkao/test/node_modules/@babel/traverse/lib/visitors.js:220:17)
    at NodePath._call (/Users/jasonkao/test/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/jasonkao/test/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/jasonkao/test/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/jasonkao/test/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/jasonkao/test/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/jasonkao/test/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/jasonkao/test/node_modules/@babel/traverse/lib/index.js:84:17)
```

## 💻 Code Sample

A project with two files in the directory:

1. The same `package.json` as above.
2. A `script.js` with these contents:
```js
import 'd3-scale';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | 10.16.3
| npm/Yarn         | 6.14.4
| Operating System | Mac OSX

**Comment by mischnic** [comment] 2020-05-04 09:56
Duplicate of https://github.com/parcel-bundler/parcel/issues/3780

**Closed by mischnic** 2020-05-04 09:56 UTC
Labels: :bug: Bug
