### ISSUE TITLE
Parcel 2 - asset not found

### ISSUE THREAD

**Issue by treshugart** [parcel-bundler/parcel#3876] opened 2019-12-05 19:01 UTC
# 🐛 bug report

With a cold build, everything completes fine. Rerunning with a warm cache causes Parcel to fail with "asset not found" during the bundling phase. These assets do exist at their `asset.filePath`, so the path is correct.

```
Error: Asset not found
    at BundleGraph.getDependencies (@parcel/core/lib/BundleGraph.js:257:13)
    at BundleGraph.getDependencies (@parcel/core/lib/public/BundleGraph.js:91:48)
    at @parcel/reporter-hmr-server/lib/HMRServer.js:98:44
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (@parcel/reporter-hmr-server/lib/HMRServer.js:97:50)
```

## 🎛 babel.config.js

```js
module.exports = function(api) {
  api.cache(true)
  const babelConfig = {
    presets: [
      [
        '@babel/env',
        {
          targets: { chrome: '58', ie: '11' },
          modules: 'commonjs',
          useBuiltIns: 'usage',
          corejs: 3,
        },
      ],
      '@babel/preset-typescript',
    ],
    plugins: [
      'babel-plugin-add-module-exports',
      'babel-plugin-transform-dynamic-import',
      'angularjs-annotate',
      'dynamic-import-node',
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-transform-async-to-generator',
      ['@babel/plugin-transform-runtime', { regenerator: false }],
    ],
    compact: false,
    inputSourceMap: true,
    sourceMaps: true,
  }
  return babelConfig
}
```

## 💁 Possible Solution

I haven't dug this far yet. I need to check the `nodes` `Map` in `Graph` to see if they exist there which might tell me if the `asset.id` is incorrect.

**Comment by mischnic** [comment] 2019-12-06 08:48
Can you provide a reproduction? Strange that the hmr server causes this...

**Comment by treshugart** [comment] 2019-12-06 22:38
Yeah, I'll give it a go. Wasn't sure if this is something anyone has seen yet.

**Comment by mischnic** [comment] 2020-01-13 09:35
Closing because of missing reproduction

**Closed by mischnic** 2020-01-13 09:35 UTC
Labels: :bug: Bug, :clock1: Waiting, ✨ Parcel 2

**Comment by Cristy94** [comment] 2020-03-21 17:49
Related: https://github.com/parcel-bundler/parcel/issues/4356
I get the same error now after updating some packages and reinstalling node_modules.

```
Error: Asset not found
    at BundleGraph.getDependencies (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\core\lib\BundleGraph.js:184:13)
    at BundleGraph.getDependencies (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\core\lib\public\BundleGraph.js:115:48)
    at Promise.all.changedAssets.map (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:79:44)
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:78:50)
    at Object.report (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\reporter-dev-server\lib\ServerReporter.js:105:21)
    at ReporterRunner.report (C:\Users\XCS\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\core\lib\ReporterRunner.js:77:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by SA1MAANKHAN** [comment] 2021-01-31 06:02
Error: Asset not found
    at BundleGraph.getDependencies (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/core/lib/BundleGraph.js:254:13)
    at BundleGraph.getDependencies (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/core/lib/public/BundleGraph.js:112:48)
    at /home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:84:44
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:83:50)
    at Object.report (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:125:21)
    at ReporterRunner.report (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/core/lib/ReporterRunner.js:73:31)
    at async Parcel.build (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/core/lib/Parcel.js:383:7)
    at async Parcel.startNextBuild (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/core/lib/Parcel.js:272:21)
    at async PromiseQueue._runFn (/home/salmaan/Documents/GitHub/JavaScript/17-forkify-project/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)### Parcel ran fine after installation, but is showing this error when I started it the other day. Any Help Appreciated.
