### ISSUE TITLE
Parcel doesn't check for SourceMap option in tsconfig.json

### ISSUE THREAD

**Issue by senese** [parcel-bundler/parcel#8967] opened 2023-04-28 02:57 UTC
# 🐛 bug report

I am building a Web Extension and Parcel keeps emitting inline Source Maps even if tsconfig.json explicitly tells to not emit or to emit separately in .map.js files.

## 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig.json

```js
{
  "compilerOptions": {
      ...
      "sourceMap": false,                                /* Create source map files for emitted JavaScript files. */
      //"inlineSourceMap": false,                          /* Include sourcemap files inside the emitted JavaScript. */
      //"inlineSources": false,                            /* Include source code in the sourcemaps inside the emitted JavaScript. */
      ...
}
```

.parcelrc
```js
{
   "extends": "@parcel/config-webextension"
}
```

.parcelrc (with typescript plugin installed)
```js
{
   "extends": "@parcel/config-webextension",
      "transformers": {
        "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
      }
}
```
manifest.json
```js
{
    "manifest_version": 3,
    "name": "",
    "version": "1.0.0",
    "description": "",
    "action": {
        "default_popup": "popup/popup.html"
    },
    "permissions": ["activeTab", "alarms", "storage", "notifications", "windows"],
    "background": {
        "service_worker": "background.ts",
        "type": "module"
    }
}
```

background.js or any other script
```js
"use strict";   // my code...
//# sourceMappingURL=data:application/json....
```

## 🤔 Expected Behavior

Parcel should be able to read `sourceMap`,  `inlineSourceMap` and `inlineSources` to correctly emit JS files.

## 😯 Current Behavior

My original source code is currently being emitted in the output JS files and even if I try to bypass this by setting `sourceMap` option to true and `inlineSourceMap` and `inlineSources` to false the result is the same above: Source Maps aren't emitted in .map.js neither exclude the source code.

I've already tried to exclude `.parcel-cache` folder and install the `@parcel/transformer-typescript-tsc` but the problem continues.

## 💁 Possible Solution

Fix/add support for  `sourceMap`,  `inlineSourceMap` and `inlineSources` options of tsconfig.json. If Parcel currently doesn't support these options, the docs should clearly explain what tsconfig.json options are and aren't supported by Parcel.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.8.3
| Node             | v.19.5.0
| npm/Yarn         | v9.3.1
| Operating System | Windows 11

**Comment by mischnic** [comment] 2023-04-28 05:41
Duplicate of https://github.com/parcel-bundler/parcel/issues/8530

**Closed as completed by mischnic** 2023-04-28 05:41 UTC
