### ISSUE TITLE
v2 - Error: Got unexpected undefined

### ISSUE THREAD

**Issue by uragecz** [parcel-bundler/parcel#8372] opened 2022-08-06 14:10 UTC
# 🐛 bug report

Trying to update parcel to v2 in our big project, however seems that building performance went noticeably down and mostly important that we get random errors that doesn't tell us anything, these error disappears after removing cache but appears after some time of running.. We are using Parcel API

```
const bundler = new Parcel({
    entries: Path.resolve(root, `./frontend/${appName}/src/index.html`),
    defaultConfig: '@parcel/config-default',
    defaultTargetOptions: {
      distDir: Path.join(root, `./dist/${appName}`),
    },
  })

  new Promise((resolve, reject) => {
    bundler.watch((err, event) => {
      if (err) {
        // fatal error
        throw err
      }
  
      if (event && event.type === 'buildSuccess') {
        const bundles = event.bundleGraph.getBundles();
        console.log(`✨ Built ${bundles.length} bundles in ${event.buildTime}ms!`);
        resolve(true)
      } else if (event && event.type === 'buildFailure') {  
        reject(event);
      }
    })
  }).then(() => {
    console.log('start server');
    startServe(options)
  }, (err) => {
    console.log('fail to build', err);
  })
```
Error :
```
node_modules/nullthrows/nullthrows.js:7
  var error = new Error(message !== undefined ? message : 'Got unexpected ' + x);
              ^
Error: Got unexpected undefined
    at nullthrows (../node_modules/nullthrows/nullthrows.js:7:15)
    at Object.run (../node_modules/@parcel/core/lib/requests/DevDepRequest.js:133:54)
    at RequestTracker.runRequest (../node_modules/@parcel/core/lib/RequestTracker.js:725:34)
    at Object.runRequest (../node_modules/@parcel/core/lib/RequestTracker.js:777:23)
    at runDevDepRequest (../node_modules/@parcel/core/lib/requests/DevDepRequest.js:127:13)
    at runCompressor (../node_modules/@parcel/core/lib/requests/WriteBundleRequest.js:237:47)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at writeFiles (../node_modules/@parcel/core/lib/requests/WriteBundleRequest.js:207:3)
    at Object.run (../node_modules/@parcel/core/lib/requests/WriteBundleRequest.js:179:3)
    at RequestTracker.runRequest (../node_modules/@parcel/core/lib/RequestTracker.js:725:20)
```

## 🎛 Configuration (.babelrc, package.json, cli command)
We use default parcel configuration + adding @babel/plugin-transform-react-jsx and babel-plugin-module-resolver
relative libraries versions -
```js
{
  "parcel": "^2.7.0",
  "@parcel/packager-raw-url": "^2.7.0",
  "@parcel/transformer-sass": "^2.7.0",
  "@parcel/transformer-webmanifest": "^2.7.0",
  "typescript": "^4.7.4",
}
```

## 🤔 Expected Behavior

If there is some error, it should tell us where is the problem.

## 😯 Current Behavior

Really hard to debug since there is no clue of possible cause

## 🔦 Context

Trying to migrate to v2

## 💻 Code Sample

Since we are migrating big project, there is hard to find the cause so there is no any code sample what is causing the error. On v1 everything went good so far.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.7.0
| Node             |  16.16.0
| npm/Yarn         | 8.1.2
| Operating System | macOS Monterey 12.4

**Comment by HcroakerDev** [comment] 2022-11-28 00:17
Still getting this issue on parcel v2.8.0. Anyone have any idea how to fix?

**Comment by mischnic** [comment] 2022-12-07 12:47
Looks like a duplicate of https://github.com/parcel-bundler/parcel/issues/8375

**Closed as not planned by mischnic** 2022-12-07 12:47 UTC

**Comment by Aneeshaik** [comment] 2024-06-09 16:59
> Still getting this issue on parcel v2.8.0. Anyone have any idea how to fix?

Did you fix it?
