### ISSUE TITLE
"could not load the image" error when loading external image in html using parcel live server

### ISSUE THREAD

**Issue by abhijitbcob** [parcel-bundler/parcel#6707] opened 2021-08-11 04:40 UTC
**Unable to load external image when using parcel server.
But image loading when using other server like live-server**

# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parceltesting",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@parcel/transformer-sass": "2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0",
    "sass": "^1.37.5"
  }
}

```

## 🤔 Expected Behavior
![Screenshot 2021-08-11 095849](https://user-images.githubusercontent.com/49182619/128969838-aa29671c-fdab-49d5-b577-089ab59e4a22.png)

## 😯 Current Behavior
![Screenshot 2021-08-11 095921](https://user-images.githubusercontent.com/49182619/128969823-0a582b4d-6996-477a-9f09-a2874e8080ac.png)

## 💻 Code Sample

``` 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning parceljs bundler</title>
    <link rel="stylesheet" href="./sass/main.scss">
    <script type="module" defer src="./js/script.js"></script>
</head>

<body>
    <img src="https://www.unsplash.it/200/200" alt="image">
</body>

</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-rc.0
| Node             | v16.1.0
| npm/Yarn         | 7.11.2
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment] 2021-08-11 07:51
Looks like a duplicate of #6503 gonna close this one

**Closed as completed by DeMoorJasper** 2021-08-11 07:51 UTC
