### ISSUE TITLE
parcel modify script tag with async attribute

### ISSUE THREAD

**Issue by HabelFoc** [parcel-bundler/parcel#2955] opened 2019-04-25 02:06 UTC
# ❔ Question

## 🔦 Context
occurred confusion.

## 💻 Code Sample

before build:
`<script type="text/javascript" async src="/src.js"></script>`

after build:
`<script type="text/javascript" async="" src="/src.8a21a8b5.js"></script>`

desc:
after build process parcel modify async attribute to have value of empty string.
supposed it just leave it as it is.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.3
| Node             | v8.12.0
| npm/Yarn         | yarn: 1.10.1
| Operating System | imac

**Comment by DeMoorJasper** [comment] 2019-04-26 07:29
More information please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Austaras** [comment] 2019-05-01 05:13
@DeMoorJasper it did happen if minify is not enabled however it's the behavior of posthtml and I don't think that matters anyway

**Comment by mischnic** [comment] 2019-05-01 12:27
This seems to indeed be posthtml bug (which only happens with minification disabled because htmlnano seems to fix it again?):

```js
var posthtml = require("posthtml")

const html = `<script async src="./index.js"></script>`

const result = posthtml()
  .process(html, { sync: true })
  .html

console.log(result) // <script async="" src="./index.js"></script>
```

**Comment by mischnic** [comment] 2019-05-03 19:57
Actually a duplicate of #2354, I knew there was an issue already

**Closed by mischnic** 2019-05-03 19:57 UTC
Labels: ✖️ Non-Parcel bug
