### ISSUE TITLE
Nightly builds no longer work

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#7153] opened 2021-10-22 08:19 UTC
# 🐛 bug report

Since the release (?) the nightly version no longer works.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file.

## 🤔 Expected Behavior

Output file containing `console.log("test");`

## 😯 Current Behavior

```
daniel@Daniels-MacBook-Pro cant_run_repro % yarn build
[ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
[ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
[ThrowableDiagnostic [Error]: The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-cli" is not compatible with the current version of Parcel. Requires "^2.0.0" but the current version is "2.0.0-nightly.889+daed0c3f".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
```

## 💁 Possible Solution

Define somewhere that `2.0.0-nightly.889+daed0c3f` is > than `2.0.0`

## 🔦 Context

Coworker insisted on pinning parcel, had an issue and thought I'd update before I'd open an issue, now actually pinning wasn't that stupid because I can easily go back.

## 💻 Code Sample

Run `yarn install` and then `yarn build`

[cant_run_repro.zip](https://github.com/parcel-bundler/parcel/files/7395482/cant_run_repro.zip)
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.889+daed0c3f|
| Node             |v16.11.1|
| npm/Yarn         |3.0.2|
| Operating System |macOS 10.15.7 (19H1419)|

**Comment by devongovett** [comment] 2021-10-26 03:11
Perhaps we should change the publish script to overwrite the engines.parcel field to match the nightly version that's being published.

**Comment by folknor** [comment] 2021-11-01 07:00
This is a duplicate of https://github.com/parcel-bundler/parcel/issues/6854

**Comment by mischnic** [comment] 2021-11-01 08:33
👍 

Duplicate of #6854

**Closed as completed by mischnic** 2021-11-01 08:33 UTC
Labels: :bug: Bug
