### ISSUE TITLE
stylus @font-face urls in dependency aren't preprocessed

### ISSUE THREAD

**Issue by wryk** [parcel-bundler/parcel#1010] opened 2018-03-16 17:09 UTC
**Choose one:** 🐛 bug report

### 🎛 Configuration and 💻 Code Sample (.babelrc, package.json, cli command)

Repository with lockfile : https://gist.github.com/wryk/3818ac52e2b9e665e083ddae71ab50ff#file-package-json

I implemented this case with css and stylus :
* `npm run serve:css` is working fine
* `npm run serve:stylus` doesn't work

### 🤔 Expected Behavior

`@font-face` urls should be resolved and associated font files copied to build folder.

### 😯 Current Behavior

`@font-face` urls aren't processed and font files aren't available in build folder.

### 💁 Possible Solution

I don't know, maybe I misused or misconfigured something but my configuration is really simple.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 9.7.1
| npm/Yarn         | 5.7.1
| Operating System | Win 10 Family, version 1709, build 16299.309

**Comment by davidnagli** [comment] 2018-03-19 19:23
Looks like a duplicate of #1009

**Closed** 2018-04-27 14:48 UTC
Labels: :heavy_multiplication_x:  Duplicate
