### ISSUE TITLE
🐛 Failed to construct 'WebSocket': The URL is invalid (HMR mode only)

### ISSUE THREAD

**Issue by jbreckmckye** [parcel-bundler/parcel#913] opened 2018-02-28 11:34 UTC
I have started seeing a curious issue with the Parcel HMR mode in my Electron/React app. The bundle crashes immediately with a WebSocket exception:

```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://:57942/' is invalid.
    at Object.require.17 (file:///C:/Users/Jimmy/Documents/GitHub/the-app/build/96200bc3b2ae206b197918b9e92b57d5.js:311:12)
    at newRequire (file:///C:/Users/Jimmy/Documents/GitHub/the-app/build/96200bc3b2ae206b197918b9e92b57d5.js:42:24)
    at require.13 (file:///C:/Users/Jimmy/Documents/GitHub/the-app/build/96200bc3b2ae206b197918b9e92b57d5.js:69:5)
    at file:///C:/Users/Jimmy/Documents/GitHub/the-app/build/96200bc3b2ae206b197918b9e92b57d5.js:74:3
```

Weirdly, this issue appeared all of a sudden yesterday afternoon. I hadn't updated Parcel or any other NPM dependency, and it became consistent across multiple devices and platforms.

It affects all versions of Parcel from at least 1.6.0 upwards (I couldn't test 1.5.x as it doesn't support an Electron target).

The only way to disable it is to pass the flag `--no-hmr`. (Side note: is there anywhere these CLI flags are documented?)

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "the-app",
  "version": "1.0.0",
  "description": "The App",
  "main": "./src/main/index.js",
  "scripts": {
    "clean": "rimraf ./dist ./build",
    "start": "concurrently \"npm run start-compile\" \"npm run start-go\"",
    "start-compile": "npm run clean && parcel watch ./src/renderer/index.html -d build/ --public-url ./ --target=electron --no-hmr",
    "start-go": "wait-on ./build/index.html && cross-env NODE_ENV=development electron .",
    "package": "npm run clean && npm run package-compile && electron-builder",
    "package-test": "npm run clean && npm run package-compile && cross-env ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true electron-builder --dir",
    "package-compile": "cross-env NODE_ENV=production parcel build ./src/renderer/index.html -d build/ --public-url ./ --target=electron && cp -r ./icons/* ./build",
    "postinstall": "cross-env ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true electron-builder install-app-deps"
  },
  "author": "me",
  "build": {
    "appId": "the.app",
    "productName": "theapp",
    "mac": {
      "category": "productivity"
    },
    "files": [
      "src/main/index.js",
      "build/*"
    ],
    "extends": null
  },
  "license": "UNLICENSED",
  "devDependencies": {
    "babel-preset-env": "1.6.1",
    "concurrently": "3.5.1",
    "cross-env": "5.1.3",
    "css-loader": "0.28.10",
    "electron": "1.8.2",
    "electron-builder": "20.2.0",
    "electron-reload": "1.2.2",
    "node-sass": "4.7.2",
    "parcel-bundler": "1.6.2",
    "wait-on": "2.1.0"
  },
  "dependencies": {
    "aframe": "0.7.1",
    "aframe-react": "4.4.0",
    "bootstrap": "4.0.0",
    "bootswatch": "4.0.0",
    "electron-debug": "1.5.0",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "rimraf": "2.6.2",
    "three": "0.90.0",
    "unstated": "1.0.3"
  }
}
```

### 💁 Possible Solution

Something weird is going on with HMR, but I'm not sure what or why it failed quite suddenly.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.0 - 1.6.2
| Node             | 6.10.3, 8.1.0
| npm/Yarn         | 4.2.0
| Operating System | Mac OS High Sierra, Windows 10

**Comment by DeMoorJasper** [comment] 2018-02-28 12:21
duplicate of #856

**Closed by DeMoorJasper** 2018-02-28 12:21 UTC
