### ISSUE TITLE
Parcel doesn't pick up changes in sibling NPM package dependency, when using a relative path

### ISSUE THREAD

**Issue by jaredkrinke** [parcel-bundler/parcel#8638] opened 2022-11-16 21:59 UTC
# 🐛 bug report

In a monorepo where a package depends on another package that is *not* a child (in the file system), Parcel doesn't pick up changes to the dependency and I have to either delete `.parcel-cache` or use `--no-cache`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Example package that references a file system sibling as a dependency (changes to this dependency aren't picked up by Parcel).

```json
{
  "name": "parcel-cache-repro",
...
  "devDependencies": {
    "parcel": "^2.8.0"
  },
  "dependencies": {
    "parcel-cache-repro-shared": "file:../shared"
  }
}
```

## 🤔 Expected Behavior

Updates to the sibling should get picked up.

## 😯 Current Behavior

Updates are not picked up. Note that `npm update parcel-cache-repro-shared` in `client/` doesn't help, nor does restarting Parcel. Also note that if the dependency is a child of the test package (in the file system), then I don't see this problem (as opposed to a sibling, as in this repro).

## 💁 Possible Solution

Work-around: `--no-cache` or deleted `.parcel-cache`.

## 🔦 Context

I'm working in a monorepo and I have a "shared" package that includes code shared across client and server. I use Parcel for packaging the client, and I noticed while fixing issues that sometimes changes wouldn't get picked up, even when re-running Parcel. I recently tracked this down to the repro above.

This is annoying because I had been trusting Parcel to properly rebuild, but now I always delete the cache and rebuild whenever something doesn't work as expected.

## 💻 Code Sample

https://github.com/jaredkrinke/parcel-cache-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0 |
| Node             | 14.17.0 |
| npm/Yarn         | NPM 8.8.0 |
| Operating System | Windows 10 21H2 (64-bit) |

**Comment by mischnic** [comment] 2022-11-16 22:19
AFAIK `file:../shared` copies over the folder into node_modules, so changes won't be reflected without somehow telling npm to copy the change over. (Or at least that's what Yarn does)

If you mean `link:../shared` (which does a symlink), then that's indeed not supported right now: https://github.com/parcel-bundler/parcel/issues/4332

**Comment by jaredkrinke** [comment] 2022-11-16 23:04
Thanks! I did mean `file:` (just as in the provided snippet), but it looks like even in the case of `file:`, NPM creates a link instead of copying. I'll defer to you on whether or not this is the same root cause, but my reading of the other bug (which indicates only the current folder root is monitored) is that the root cause is indeed the same.

**Comment by mischnic** [comment] 2022-11-17 09:13
Yeah, I'm afraid this is a duplicate of https://github.com/parcel-bundler/parcel/issues/4332

**Closed as not planned by mischnic** 2022-11-17 09:13 UTC
