### ISSUE TITLE
postcss-preset-env feature custom properties only working on one file

### ISSUE THREAD

**Issue by applesandarrows** [parcel-bundler/parcel#3978] opened 2020-01-10 23:14 UTC
# ❔ Question

I'm using postcss-preset-env and it seems to only be working on the css file that contains my :root. All other css files are ignored. I tried importing the css file that contains the variables but that didn't nothing. How do I set postcss-preset-env globally so it works with all css files?

## 💻 Code Sample

{
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-preset-env": {
      browsers: 'last 12 versions',
      stage: 3,
      features: {
        'custom-properties': true,
        'gap-properties': true,
        'place-properties': true
      }
    }
  }
}

## 🌍 Your Environment

I'm using VS Code and NPM.

**Comment by mischnic** [comment] 2020-01-26 13:05
Duplicate of https://github.com/parcel-bundler/parcel/issues/1165, is fixed in Parcel 2.

**Closed** 2020-01-26 13:07 UTC
