### ISSUE TITLE
 Error: Cannot read property 'hashReferences' of undefined

### ISSUE THREAD

**Issue by kevincox** [parcel-bundler/parcel#4145] opened 2020-02-16 11:17 UTC
# 🐛 bug report

When adding a synchronous dependency I get the following error:

```
 🚨 Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (/builds/kevincox/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:455:47)
    at getBundlesIncludedInHash (/builds/kevincox/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:459:24)
    at getBundlesIncludedInHash (/builds/kevincox/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:459:24)
    at assignComplexNameHashes (/builds/kevincox/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:447:27)
    at PackagerRunner.writeBundles (/builds/kevincox/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:101:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

All the state can be see in https://gitlab.com/kevincox/playerone/-/merge_requests/1.

In that PR I attempt to remove the workaround (using async imports) and you can see that it fails to build.

## 🤔 Expected Behavior

The build should work as intended.

## 💁 Possible Solution

This may be related to the fact that this library is imported from two places. The current graph looks like this (when experiencing the bug).

- main.js
  - sync ga.js
  - async options.js
- options.js
  - sync ga.js 

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.113
| Node             | v13.8.0
| npm         | 6.13.6
| Operating System | Linux

**Comment by mischnic** [comment] 2020-02-16 11:57
Could you try again with the latest `parcel@nightly` release? The hashing system was recently overhauled.

**Comment by kevincox** [comment] 2020-02-16 12:10
Same issue.

```
% npx parcel --version
2.0.0-nightly.113
% npx parcel build --no-cache -- src/index.pug
🚨 Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:455:47)
    at getBundlesIncludedInHash (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:459:7)
    at getBundlesIncludedInHash (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:459:7)
    at assignComplexNameHashes (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:447:31)
    at PackagerRunner.writeBundles (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/PackagerRunner.js:101:5)
    at async Parcel.build (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/Parcel.js:376:7)
    at async Parcel.run (/home/kevincox/p/playerone/node_modules/@parcel/core/lib/Parcel.js:253:18)
    at async Command.run (/home/kevincox/p/playerone/node_modules/parcel/lib/cli.js:190:7)
```

**Comment by Banou26** [comment] 2020-02-19 13:57
This error happens practically if not every time you change a configuration property from the package.json or elsewhere.
To fix it most of the time just deleting the cache folder seems to fix it for me.
Not sure why it's doing that for you because you have the `--no-cache` flag

**Comment by kevincox** [comment] 2020-02-19 14:07
To be honest I've been in the habit of removing the cache after every built as it seems to cause a lot of issues. So cache definitely isn't the problem here.

**Comment by padmaia** [comment] 2020-02-20 02:16
Thanks for having an easily reproducible example @kevincox! I've opened a PR that I believe should solve this issue. Temporarily, it looks like building with `--no-scope-hoist` resolves the issue until a fix is merged.

**Comment by padmaia** [comment] 2020-02-20 03:21
@Banou26 I think what you are referring to may be fixed by #4189, so keep an eye out on that one.

**Comment by ubershmekel** [comment] 2020-06-02 11:24
I think I'm getting this error when my `package.json` has an invalid "main" field. Though I'm not sure what parcel considers valid. I'm just pointing my main at `"main": "dist/index.html"` which doesn't work while `"main": "index.html"` which unfortunately overwrites my real main file does complete a build.

```
× Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\PackagerRunner.js:490:47)
    at getBundlesIncludedInHash (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\PackagerRunner.js:494:7)
    at getBundlesIncludedInHash (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\PackagerRunner.js:494:7)
    at assignComplexNameHashes (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\PackagerRunner.js:482:31)
    at PackagerRunner.writeBundles (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\PackagerRunner.js:110:5)
    at async Parcel.build (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\Parcel.js:375:7)
    at async Parcel.run (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\@parcel\core\lib\Parcel.js:250:18)
    at async Command.run (C:\Users\yuv\Downloads\gfloyd-backup\gh-website\node_modules\parcel\lib\cli.js:155:7)
```

**Comment by brettinternet** [comment] 2020-07-05 19:25
I was getting this error on `parcel@next` with `parcel build ./src/index.html --dist-dir=build`, but not on `parcel@nightly` (`2.0.0-nightly.322`)

**Comment by mischnic** [comment] 2020-07-06 08:42
Can someone else confirm this is fixed?

**Comment by ross-pfahler** [comment] 2020-07-08 17:34
I'm receiving the error when when two builds in a monorepo share the default cache -- in this case the cache dir is at the root of the repository.

If add `--cache-dir=./.parcel-cache` to the builds, I can work around the issue.

**Comment by schlagi123** [comment] 2020-08-06 16:06
> Can someone else confirm that this is fixed?

In the beta I have the same problem. In the version `2.0.0-nightly.358` it works fine.

**Comment by RPDeshaies** [comment] 2020-08-06 17:49
I'm on `2.0.0-beta.1` and just encountered the issue in my bitbucket pipeline build 

I have a similar structure as @ross-pfahler (monorepo with two packages build built by parcel at the same time)

Haven't tried 2.0.0-nigthly.3658 though

**Comment by cifkao** [comment] 2020-08-15 17:18
I'm getting this error with `2.0.0-nightly.366`, even with `--no-scope-hoist`. However, `--no-content-hash` solves the problem for me.

**Comment by cifkao** [comment] 2020-08-15 17:39
It would be great to at least display a more informative error message (showing which bundle is referenced that is not found).

**Comment by mischnic** [comment] 2020-08-15 19:21
> In my case it happens when I try to import a file using a named pipeline, e.g. import css from 'bundle-text:./style.css', and only when I try to build a JS target. When referencing the JS file from HTML, the error does not occur.

Can you reproduce this consistently? Could you provide a full code sample? 

> It would be great to at least display a more informative error message (showing which bundle is referenced that is not found).

We should rather fix the bug itself....

**Comment by cifkao** [comment] 2020-08-15 20:59
> Can you reproduce this consistently? Could you provide a full code sample?

Sure: https://gist.github.com/cifkao/badeda38164e362a147b571053920520

`parcel serve index.html` works fine (the CSS file contents get printed onto the console), but `parcel build index.js` fails with this error.

**Comment by mischnic** [comment] 2020-08-17 10:49
At least in @cifkao's example, this is caused by inline bundles not being processed (as they shouldn't)
https://github.com/parcel-bundler/parcel/blob/64ebc3757a7c36432d55ee4d791e96e30dab242f/packages/core/core/src/PackagerRunner.js#L116
so `bundleInfoMap[someInlineBundle.id]` is undefiend.
But they are still listed in the hashReferences of their parent bundles: https://github.com/parcel-bundler/parcel/blob/64ebc3757a7c36432d55ee4d791e96e30dab242f/packages/core/core/src/PackagerRunner.js#L658
and then `bundleInfoMap[someInlineBundle.id].hashReferences` fails

**Comment by dgkimpton** [comment] 2020-08-20 21:29
I also get this error now too, but with JS instead of CSS.  

What seems to have triggered it for me is using ES6 static imports from inside an ES6 dynamic import which I had *also* imported in the document itself.

The following minimal example reproduces:

**package.json**
```
{
 "name": "parcel-test",
 "version": "1.0.0",
 "scripts": {
  "assemble": "parcel build index.html"
 },
 "devDependencies": {
  "parcel": "^2.0.0-nightly.372"
 }
}

```

**index.html**
```
<!DOCTYPE html>
<html>
<body>
	<script type="module">
		import { something } from './othermodule.mjs';
		document.addEventListener('load', () => {
			something();
			import('./module.mjs').then((m) => m.doStuff());
		});
	</script>
</body>
</html>
```

**module.mjs**
```
import { something } from './othermodule.mjs';

export function doStuff() {
	something();
}
```

**othermodule.mjs**
```
export function something() {
	console.warn('hmmm');
}
```

|Software | Version(s)|
|-- | --|
|Parcel | parcel@2.0.0-nightly.372|
|Node | v14.4.0|
|npm |6.14.5|
|Operating System | Windows 10/git bash|


```npm run assemble```
```
� Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:529:47)
    at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:533:7)
    at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:533:7)
    at assignComplexNameHashes (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:521:31)
    at PackagerRunner.writeBundles (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:112:5)
    at async Parcel.build (E:\code\web\parcel-error\node_modules\@parcel\core\lib\Parcel.js:398:7)
    at async Parcel.run (E:\code\web\parcel-error\node_modules\@parcel\core\lib\Parcel.js:273:18)
    at async Command.run (E:\code\web\parcel-error\node_modules\parcel\lib\cli.js:234:7)
```

**Comment by MeloncholyShiro** [comment] 2020-08-25 08:03
> 
> 
> I also get this error now too, but with JS instead of CSS.
> 
> What seems to have triggered it for me is using ES6 static imports from inside an ES6 dynamic import which I had _also_ imported in the document itself.
> 
> The following minimal example reproduces:
> 
> {edit} as a gist: https://gist.github.com/dgkimpton/278657a777eb898075b9551ff38606c2
> 
> **package.json**
> 
> ```
> {
>  "name": "parcel-test",
>  "version": "1.0.0",
>  "scripts": {
>   "assemble": "parcel build index.html"
>  },
>  "devDependencies": {
>   "parcel": "^2.0.0-nightly.372"
>  }
> }
> ```
> 
> **index.html**
> 
> ```
> <!DOCTYPE html>
> <html>
> <body>
> 	<script type="module">
> 		import { something } from './othermodule.mjs';
> 		document.addEventListener('load', () => {
> 			something();
> 			import('./module.mjs').then((m) => m.doStuff());
> 		});
> 	</script>
> </body>
> </html>
> ```
> 
> **module.mjs**
> 
> ```
> import { something } from './othermodule.mjs';
> 
> export function doStuff() {
> 	something();
> }
> ```
> 
> **othermodule.mjs**
> 
> ```
> export function something() {
> 	console.warn('hmmm');
> }
> ```
> 
> Software 	Version(s)
> Parcel 	parcel@2.0.0-nightly.372
> Node 	v14.4.0
> npm 	6.14.5
> Operating System 	Windows 10/git bash
> 
> `npm run assemble`
> 
> ```
> � Build failed.
> Error: Cannot read property 'hashReferences' of undefined
> TypeError: Cannot read property 'hashReferences' of undefined
>     at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:529:47)
>     at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:533:7)
>     at getBundlesIncludedInHash (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:533:7)
>     at assignComplexNameHashes (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:521:31)
>     at PackagerRunner.writeBundles (E:\code\web\parcel-error\node_modules\@parcel\core\lib\PackagerRunner.js:112:5)
>     at async Parcel.build (E:\code\web\parcel-error\node_modules\@parcel\core\lib\Parcel.js:398:7)
>     at async Parcel.run (E:\code\web\parcel-error\node_modules\@parcel\core\lib\Parcel.js:273:18)
>     at async Command.run (E:\code\web\parcel-error\node_modules\parcel\lib\cli.js:234:7)
> ```

Yep this my problem too, i think we can't use ES6 Export/Import in Parcel. Feels Bad. Do you have any solution for this stuff?

**Comment by 1saf** [comment] 2020-08-30 10:21
Also bumping this as an issue I am experiencing. Seems to be when main is unset in package.json?

**Comment by ittaibaratz** [comment] 2020-10-23 14:13
I got this issue as well with the latest nightly.

```
parcel build src/index.html --dist-dir ./dist --public-url=$PUBLIC_PATH --cache-dir ./.parcel-cache --detailed-report
🚨 Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/PackagerRunner.js:671:47)
    at getBundlesIncludedInHash (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/PackagerRunner.js:675:7)
    at assignComplexNameHashes (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/PackagerRunner.js:663:31)
    at PackagerRunner.writeBundles (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/PackagerRunner.js:224:5)
    at async Parcel.build (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/Parcel.js:584:7)
    at async Parcel.run (/Users/ibaratz/GitHub2/unified-shell/node_modules/@parcel/core/lib/Parcel.js:459:18)
    at async Command.run (/Users/ibaratz/GitHub2/unified-shell/node_modules/parcel/lib/cli.js:352:7)
```

cc @ross-pfahler

**Comment by mischnic** [comment] 2020-10-23 14:25
@ittaibaratz Are you using `import foo from 'bundle-text:./something';` or `import foo from 'data-url:./something';` (like [here](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-674446661))? Or [inline script tags with imports](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-677915812)? Just trying to verify that there are not even more situations where this occurs...

**Comment by ittaibaratz** [comment] 2020-10-23 14:35
> @ittaibaratz Are you using `import foo from 'bundle-text:./something';` or `import foo from 'data-url:./something';` (like [here](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-674446661))? Or [inline script tags with imports](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-677915812)? Just trying to verify that there are not even more situations where this occurs...

We have `import SomeSV from 'url:/path/to/image.svg';`

Note the issue is very intermittent, and clearing the cache folder and re-running the build gets rid of it.

**Comment by OzzyCzech** [comment] 2020-11-10 20:21
I have exact same error with lates nightly build (`2.0.0-nightly.443`)

```
$ parcel build src/index.html --dist-dir=public/dist --public-url=/dist/ --log-level=verbose
🚨 Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/PackagerRunner.js:671:47)
    at getBundlesIncludedInHash (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/PackagerRunner.js:675:7)
    at assignComplexNameHashes (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/PackagerRunner.js:663:31)
    at PackagerRunner.writeBundles (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/PackagerRunner.js:224:5)
    at async Parcel._build (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/Parcel.js:617:7)
    at async Parcel.run (/Volumes/Work/testomato.com/node_modules/@parcel/core/lib/Parcel.js:487:18)
    at async Command.run (/Volumes/Work/testomato.com/node_modules/parcel/lib/cli.js:361:7)
```

solved with solved with `--no-scope-hoist` param build works well.

**Comment by ross-pfahler** [comment] 2020-11-16 17:37
hey @mischnic -- in case you want another example, here is an easy repro of a similar problem: https://github.com/ross-pfahler/parcel-2-demos/pull/5. Steps are in PR body.

**Comment by toastal** [comment] 2020-11-30 07:30
I personally get this bug every time I recompile the stylesheets (PostCSS + SugarSS). Clearing the cache after every change has been the only thing that works, but this isn't ideal.

**Comment by spro** [comment] 2020-12-12 06:57
Also seeing this specifically with PostCSS + SugarSS

**Comment by jeffpeck10x** [comment] 2021-02-11 01:02
I just encountered this (on `2.0.0-nightly.573+31f431d9`) and the `--no-scope-hoist` suggestion fixed it, although I am not clear what introduced it. I am importing svg's, which is possibly related? 🤷

**Comment by mischnic** [comment] 2021-02-25 19:40
Another reproduction:

```html
<script type="module">
  import * as b from "./b.js";
  console.log(b);
</script>
<script src="./a.js" type="module"></script>
```

```js
// a.js
import * as b from "./b.js";
console.log(b);

// b.js
export const a = 1;
```

**Comment by artemjackson** [comment] 2021-02-26 15:14
If building for ESM there is no solution or workaround :(
Meanwhile the issue got one year old 🎉

**Comment by ghost** [comment] 2021-06-16 01:22
I have a build where `src/navbar.tsx` is the entry point. This gets compiled to `dist/navbar.js`. I was getting the hashReferences error.

I had in my `package.json`:

```
{
  "main": "./dist/navbar.js",
}
```

When I remove the `main:` property from my `package.json`, the error goes away and my bundle works correctly (without --no-cache and --no-scope-hoist). Same error when using `module:` Hopefully this information might be of use.

**Comment by devongovett** [comment] 2021-07-09 06:12
I can't reproduce with @mischnic's case in the latest nightly anymore. @GrantAtStreamba what version of Parcel are you using and do you have any more details on what could reproduce it?

**Comment by devongovett** [comment] 2021-07-25 22:06
Going to close this since it seems to be working now. If you manage to reproduce it still, please let us know.

**Closed by devongovett** 2021-07-25 22:06 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2, 💰 Cache

**Comment by kevincox** [comment] 2021-10-14 12:16
The original case is still present https://gitlab.com/kevincox/playerone/-/merge_requests/1. I have rebased the example against Parcel 2.0.0.

I have also found a new case on Parcel 2.0.0 that worked previously. https://gitlab.com/kevincox/playerone/-/merge_requests/65 which appears to be triggered by this import https://gitlab.com/kevincox/playerone/-/blob/72879318ae5db83cb3174871e50b281c297a5b95/src/a/options.ts#L1

**Comment by danieltroger** [comment] 2022-01-31 16:38
Also experiencing this issue when trying to workaround https://github.com/parcel-bundler/parcel/issues/7609 by using `bundle-text:` instead :(

```
🚨 Build failed.

Error: Cannot read properties of undefined (reading 'hashReferences')

  TypeError: Cannot read properties of undefined (reading 'hashReferences')
  at getBundlesIncludedInHash ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:147:47)
  at getBundlesIncludedInHash ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:151:7)
  at assignComplexNameHashes ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:140:105)
  at Object.run ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:115:5)
  at async RequestTracker.runRequest ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
  at async Object.run ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:74:20)
  at async RequestTracker.runRequest ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
  at async Parcel._build ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/Parcel.js:397:11)
  at async Parcel.run ([project_dir]/.yarn/cache/@parcel-core-npm-2.2.1-62c0c81716-f06b61c184.zip/node_modules/@parcel/core/lib/Parcel.js:276:18)
  at async run ([project_dir]/.yarn/cache/parcel-npm-2.2.1-088c07d8bf-081fdc011a.zip/node_modules/parcel/lib/cli.js:374:7)
```

**Comment by danieltroger** [comment] 2022-01-31 16:41
For me, falling back to `fs.readFileSync` worked as an ugly workaround :)

**Comment by Stvad** [comment] 2022-04-29 01:31
Another confirmation for `bundle-text:` causing the problem. It used to work for me in 2.3.2, but upon upgrading to 2.5.0 I'm hitting this issue

**Comment by Stvad** [comment] 2022-04-29 02:08
For me falling back on fs does not work, as I actually want Parcel to process imports in the CSS first =\  
https://github.com/shoonia/parcel-transformer-css-to-string/issues/6 does not work for similar reasons =\

**Comment by Stvad** [comment] 2022-04-29 02:26
Ah interestingly - it only happens in `watch` mode but not for build, with following configurations. will check what is causing the difference:
```
	"build": "parcel build source/manifest.json --no-content-hash --no-source-maps --dist-dir distribution --no-cache --detailed-report 0",
	"watch": "parcel watch source/manifest.json --dist-dir distribution --no-cache --no-hmr",

```

**Comment by Stvad** [comment] 2022-04-29 02:29
so removing `--no-hmr` seems to have resolved this for me 🤷‍♂️

**Comment by Stvad** [comment] 2022-05-08 22:38
But if I were to remove `--no-content-hash` from the build command, I start hitting this issue in the build command 🙈

**Comment by calclavia** [comment] 2022-05-20 16:06
Running into the same issue during `parcel build`. `--no-content-hash` fixes it.

**Comment by everdimension** [comment] 2022-07-04 11:16
Same issue
`parcel watch` works fine, `parcel build` fails.

* I'm using the [web-extension](https://parceljs.org/recipes/web-extension/) config
* I am using `'bundle-text:'` import at one place

`--no-content-hash` helped.

---

[Jul 11, 2022] Update:

The above doesn't really work. It makes the `build` command finish execution without errors, but the resulting build turns out to be broken.
The issue is with the code surrounding the `bundle-text:` import. The other (normal) import in the file doesn't seem to work and I get a runtime error:  
_Cannot find module '81IKK'_
(The latter I guess is just a hashed name of a module from node_modules)

**Comment by avalanche1** [comment] 2022-07-19 18:26
Has anyone been able to circumvent the issue?
Because the `--no-content-hash ` solution, as stated by @everdimension , doesn't really work.

**Comment by Stvad** [comment] 2022-07-19 18:32
@everdimension @avalanche1 I think you may be hitting another bug - see #8071

**Comment by mark-monteiro** [comment] 2022-08-29 21:47
> @everdimension @avalanche1 I think you may be hitting another bug - see #8071

For reference, a workaround in the linked issue can be found in [this comment](https://github.com/parcel-bundler/parcel/issues/8071#issuecomment-1133549719). I've also outlines that solution below.

As mentioned in [everdimension's comment](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-1173695345), adding `--no-content-hash` removes the build error but introduces a runtime error `Cannot find module '#####'`. The solution is to specify `--no-content-hash` and then also disable code splitting by adding the following to your `package.json` file:

```json
  "@parcel/bundler-default": {
    "minBundles": 10000000,
    "minBundleSize": 3000,
    "maxParallelRequests": 20
  }
```

Keep in mind that this solution removes code-splitting so you will end up with larger individual files. If you're developing a web extension this is generally not an issue since the files are loaded locally anyways. However, Firefox does have a hard limit of 4MB per file ([[1]](https://discourse.mozilla.org/t/bug-with-uploading-large-files-in-addon/85407), [[2]](https://discourse.mozilla.org/t/firefox-web-extension-background-script-to-bundle-or-not-to-bundle/82805)), which could prevent this solution from working on the Firefox Addons site.

**Comment by mark-monteiro** [comment] 2022-08-29 21:53
> @everdimension @avalanche1 I think you may be hitting another bug - see #8071

For reference, a workaround in the linked issue can be found in [this comment](https://github.com/parcel-bundler/parcel/issues/8071#issuecomment-1133549719). I've also outlined that solution below.

As mentioned in [everdimension's comment](https://github.com/parcel-bundler/parcel/issues/4145#issuecomment-1173695345), adding `--no-content-hash` removes the build error but introduces a runtime error `Cannot find module '#####'`. The solution is to specify `--no-content-hash` and then also disable code splitting by adding the following to your `package.json` file:

```json
  "@parcel/bundler-default": {
    "minBundles": 10000000,
    "minBundleSize": 3000,
    "maxParallelRequests": 20
  }
```

Keep in mind that this solution removes code-splitting so you will end up with larger individual files. If you're developing a web extension this is generally not an issue since the files are loaded locally anyways. However, Firefox does have a hard limit of 4MB per file ([[1]](https://discourse.mozilla.org/t/bug-with-uploading-large-files-in-addon/85407), [[2]](https://discourse.mozilla.org/t/firefox-web-extension-background-script-to-bundle-or-not-to-bundle/82805)), which could prevent this solution from working on the Firefox Addons site.

Again, this is all outlined in various comments in the linked issue (#8071), which may the better place to track progress on a fix for this problem.

**Comment by avalanche1** [comment] 2022-09-04 13:14
@mischnic Will this get priority?
Jumping through the hoops just to make the basic f-nality work is distressing.
