### ISSUE TITLE
Error: Cannot find module './lib/fs'

### ISSUE THREAD

**Issue by debasissahu** [parcel-bundler/parcel#2961] opened 2019-04-26 08:52 UTC
See the yellow mark error, when I am using parcel in a simple test app: 

![Error](https://user-images.githubusercontent.com/46349396/56795632-86bf9e80-682e-11e9-8607-81ad03122f62.PNG)

**Comment by DeMoorJasper** [comment] 2019-04-26 14:34
Use Node 8 as a workaround

**Comment by mischnic** [comment] 2019-05-04 15:14
Duplicate of https://github.com/parcel-bundler/parcel/issues/2533

**Closed by mischnic** 2019-05-04 15:14 UTC
Labels: :bug: Bug
