### ISSUE TITLE
Parcel.js Command Line Interface error when “watch” is invoked

### ISSUE THREAD

**Issue by DoubleCouponDay** [parcel-bundler/parcel#1450] opened 2018-05-28 06:22 UTC
# ❔ Question
How do I fix this error when invoking `parcel watch` on the command line?
`URI malformed`

## 🔦 Context
I am in a development environment with its own web server. I only want parcel js for watching for changes to the source
## 💻 Code Sample
authorizedcontrols.html
```
{%load static %}
<script src="/static/scripts/custom/AuthorizedControls.js"></script>
```
cli stack trace

```
C:\Users\sjsui\Desktop\git_workshop\MoonMachineOpenSource\MoonMachine\MoonMachine2\Front\templates>parcel

 watch authorizedcontrols.html
×  C:\Users\sjsui\Desktop\git_workshop\MoonMachineOpenSource\MoonMachine\MoonMachine2\Front\templates\authorizedcontrols.html: URI malformed
    at decodeURIComponent (<anonymous>)
    at HTMLAsset.addURLDependency (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\src\Asset.js:93:7)
    at HTMLAsset.processSingleDependency (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\src\assets\HTMLAsset.js:90:26)
    at ast.walk.node (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\src\assets\HTMLAsset.js:139:43)
    at traverse (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:105:26)
    at traverse (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:111:5)
    at traverse (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:105:17)
    at traverse (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:111:5)
    at traverse (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:105:17)
    at Array.walk (C:\Users\sjsui\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\posthtml\lib\api.js:39:10)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel            |
| django          |
| npm, pip       |
| Windows 10  |

**Comment by DeMoorJasper** [comment] 2018-05-28 06:34
This is strange, could you perhaps try to log what causes this error?

What gets set as an input to decodeurl on `node_modules\parcel-bundler\src\Asset.js:93:7`

Might be just some weird template stuff or something

**Comment by DoubleCouponDay** [comment] 2018-05-28 23:54
I'm having trouble finding the decodeurl parameter in Asset.js. 

Logging is a little bit beyond my skill level as I would have to use a new program for attaching to the parcel-bundler process. I've set the log level parameter for `watch` and noticed that the error is different beyond the first invoke of the day: When running watch with the default logging level, it returns the error `cannot read property "html" of null`. However, when I run it again with `--log-level 3`, the error is `URI malformed`. any subsequent runs of `watch` with the default log level return `URI malformed`. My conclusion is there is some internal state which is hiding the true error; which one I cant say.

I think the best course of action would be to find the error message literal in the source code / dependency which provides the source of these particular messages. Then, We must work back from there to determine how to avoid their occurrence.

**Comment by DeMoorJasper** [comment] 2018-05-29 05:32
The default log level is 3.

With logging I just mean open up node_modules search for parcel and add some console logs as you actually have the source code, js is not a compiled language.

If you use yarn you could also clone this repo, run `yarn` and `yarn link` and than inside your project do `yarn link "parcel-bundler"` and you should be using your local version of parcel

**Comment by DeMoorJasper** [comment] 2018-06-02 06:27
It's exactly what the error says, the uri is not valid utf-8, I'll dig a lil deeper into how this can happen

**Comment by DeMoorJasper** [comment] 2018-06-02 06:50
Duplicate of #1153

**Closed by DeMoorJasper** 2018-06-02 06:50 UTC
Labels: :grey_question:  Question
