### ISSUE TITLE
🙋 Allow logger to be configured about appending vs. cleaning console 

### ISSUE THREAD

**Issue by mohsen1** [parcel-bundler/parcel#1527] opened 2018-06-12 18:00 UTC
# 🙋 Development Logging without cleaning console
Currently when running Parcel in development mode, logger will clean up console on each build. It's usually desired to have a clean console but when integrating with other tools such as VSCode, it's desired to have output of logger concatenated to previous logs instead of clearing the console. VSCode uses output of a program in "tasks" to determine if a task is ready or not. With current setup VSCode is not capable of doing that. 

## 🤔 Expected Behavior
Have a config for logger (maybe level 4) where all logs persist 

## 😯 Current Behavior
Logger clears the console

## 🔦 Context
https://github.com/Microsoft/vscode/issues/6209#issuecomment-350814733
https://github.com/mohsen1/parcel-react-typescript-vscode

**Comment by Morgul** [comment] 2018-06-17 23:13
You could, technically, do `process.env['FORCE_COLOR'] = 0;` before importing parcel, and that should turn off the clearing behavior. It's an ugly hack, but I think it should work.

**Comment by DeMoorJasper** [comment] 2018-07-11 17:56
Duplicate of #993

**Closed by DeMoorJasper** 2018-07-11 17:56 UTC
Labels: :raising_hand_woman: Feature
