### ISSUE TITLE
v2: can't import modules from a CDN: 🚨 @parcel/core: Unknown pipeline: https.

### ISSUE THREAD

**Issue by cekvenich2** [parcel-bundler/parcel#6814] opened 2021-08-29 22:51 UTC
eg. `import { createCustomElement } from 'https://cdn.skypack.dev/ficusjs@3/custom-element'`

gives error: can't import modules from a CDN: `🚨 @parcel/core: Unknown pipeline: https`

We have to be able to import modules from a CDN (eg https://www.jsdelivr.com/esm )

**Comment by DeMoorJasper** [comment] 2021-08-30 18:29
We currently do not support this, this is a feature we're definitely planning to support at some point post-rc.

You can probably already start working on this by modifying the resolver

**Comment by mischnic** [comment] 2021-11-12 11:02
Duplicate of https://github.com/parcel-bundler/parcel/issues/4148

**Closed as completed by mischnic** 2021-11-12 11:02 UTC
Labels: :raising_hand_woman: Feature, ✨ Parcel 2, Resolver
