### ISSUE TITLE
Changes to source files do not trigger rebuild when working in symlinked directory

### ISSUE THREAD

**Issue by Systemcluster** [parcel-bundler/parcel#7518] opened 2022-01-03 19:46 UTC
# 🐛 bug report

When running `parcel serve` or `parcel watch`, changes to source files do not trigger a rebuild but are ignored.
No console output is printed in verbose mode when changing source files; and with `parcel serve` the page served to the browser is not updated, even when quitting and restarting the process, unless `.parcel-cache` is deleted.

Changes to other files in the project directory, for example `package.json` or `.parcelrc`, are recognized and do trigger a rebuild.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have uploaded a minimal reproduction project here: https://github.com/Systemcluster/parcel-serve-issue-repro

Running `npm run start` and changing any file in `app/` has no effect.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-nightly.961` or `2.0.1`
| Node             | `17.3.0`
| npm/Yarn         | `npm 8.3.0` or `pnpm 6.24.4`
| Operating System | Windows 10 21H2

**Comment by mischnic** [comment] 2022-01-03 20:13
It is rebuilding for me (macOS though).

**Comment by Systemcluster** [comment] 2022-01-03 20:29
After trying to pinpoint this for a few hours I had a sudden suspicion what the reason might be - my development environment directory is symlinked to another drive; my `C:/Users/User/Development` is symlinked to `K:/Development` and I work with a terminal session in the former. Running the terminal session, and the `parcel` process, in the latter does not have this issue.

To reproduce, create a symlink (e.g. with Powershell: `ni C:\a\b -i SymbolicLink -ta K:\b`) and `cd` to `C:\a\b` to install and run the parcel project. Any change to source files then will be ignored. Running parcel in `K:\b` however works fine.

I haven't had this issue with NextJS based projects, and subscribing to file changes manually with `@parcel/watcher` does detect the changes (reporting the un-resolved symlinked path); could it be possible that there's a mismatch between resolved and unresolved paths somewhere?

**Comment by devongovett** [comment] 2022-01-06 02:16
Duplicate of #4332

**Closed as completed by devongovett** 2022-01-06 02:16 UTC
