### ISSUE TITLE
Parse comment incorrectly

### ISSUE THREAD

**Issue by JounQin** [parcel-bundler/parcel#3263] opened 2019-07-25 16:50 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
no config

## 🤔 Expected Behavior

No Error

## 😯 Current Behavior

```sh
🚨  /Users/JounQin/Workspaces/GitHub/Slides/node_modules/vue-mark-display/dist/vue-mark-display.js:2096:12: Unterminated string constant (2096:12)
  2094 |           // http://stackoverflow.com/a/26603875
  2095 |           code +=
> 2096 |             '\n +
       |            ^
  2097 |             btoa(unescape(encodeURIComponent(JSON.stringify(css.map)))) +
  2098 |             ' */';
  2099 |         }
```

## 💻 Code Sample

https://unpkg.com/vue-mark-display@0.1.3/dist/vue-mark-display.js

```js
code +=
  '\n/*# sourceMappingURL=data:application/json;base64,' +
  btoa(unescape(encodeURIComponent(JSON.stringify(css.map)))) +
  ' */';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |v12.7.0
| npm/Yarn         |yarn 1.17.3
| Operating System |Darwin Kernel Version 19.0.0: Thu Jul 11 18:37:36 PDT 2019; root:xnu-6153.0.59.141.4~1/RELEASE_X86_64

**Comment by mischnic** [comment] 2019-07-25 19:20
Yes, this is a known bug. Duplicate of https://github.com/parcel-bundler/parcel/issues/2408

**Closed by mischnic** 2019-07-25 19:20 UTC
