### ISSUE TITLE
HTML import support?

### ISSUE THREAD

**Issue by zeakd** [parcel-bundler/parcel#1358] opened 2018-05-13 09:02 UTC
# 🙋 feature request

Hi. 
I just think about it, How about [HTML import](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports) support for parcel? it would be better `import` way for `html` assets

## 💻 Examples

``` html
<link rel='import' src='./partial.html' />
<link rel='import' src='./Button.vue' />
```

**Comment by mohsen1** [comment] 2018-05-13 21:10
I'm curious why you need this? AFAIK Polymer was the only user of HTML Imports but they are moving away from it.

**Comment by zeakd** [comment] 2018-05-13 23:10
@mohsen1 It comes from when considering [markdown support problem](https://github.com/parcel-bundler/parcel/pull/1160). I agree markdown should be transpiled to html, but to parse markdown to html, MarkdownAsset should consider `layout`(html, head, body, meta..) and `renderer`. Parcel doesn't have a way to pass these options, and there are no `.markdownrc` spec. 

IMO, lack of `importing and manipulating way of html` caused these problems. `posthtml-include` can do kinks of things but this can't make `ast` of assets. I thought `<link rel='import>` can give flexibility to parcel in bundling time. for example

main.html
``` html
...
  <div>
    <link rel='import href='./hello.html' />
  </div>
...
```

hello.html
``` html
<div class='md'>
  <link rel='import' href='./hello.md' />
</div>
...
<script>
  const marked = require('marked');
  const link = document.querySelector('link[rel="import"]');
  const mdWrapper = document.querySelector('.md');
  mdWrapper.innerHTML = marked(link.innerHTML);
  ...
</script>
```

result main.html
``` html
<div>
  <div class='md'>
     <!-- some parsed markdown contents-->
  </div>
</div>
```

Well, this is just rough sketch and should be developed more. main idea is inside `<script>` would be excuted in bundling time then user can manipulate html easily without magic. This can be used to inject some parameters to `template engines`, import `.vue` as web-component, etc.

**Comment by jluisgarcia** [comment] 2018-05-14 23:14
I was just thinking the same.
Having a separate piece of html for a header, for example. And being able to import it, is a feature that Parcel fans will love.

**Comment by jdanyow** [comment] 2018-05-15 02:26
Duplicate of #178?

I think polymer abandoned HTML imports and the spec died https://caniuse.com/#feat=imports

Here's a way to import markdown with posthtml:

```html
<article class="markdown-body" md>
  <include src="./README.md"></include>
</article>
```
[source](https://github.com/utterance/utterances/blob/f003c8a955dd2387eb2593d928fea720c404156c/src/index.html#L44-L46), [.posthtmlrc.js](https://github.com/utterance/utterances/blob/master/.posthtmlrc.js)

PR to make parcel's watcher observe posthtml included files: #1355

**Comment by buckle2000** [comment] 2018-05-20 12:46
Maybe you need [pug](https://pugjs.org/language/includes.html)?

**Comment by jluisgarcia** [comment] 2018-05-20 22:03
Pug is an option. But it involves learning a new syntax.
Best option is being able to include Html fragments "out of the box" with parcel.
It would be so nice for navigation, etc.

**Comment by GrosSacASac** [comment] 2018-06-09 22:54
[Hi, several authors from the webcomponents spec are considering html modules instead of html imports (120+ comments discussion)](https://github.com/w3c/webcomponents/issues/645)

The good news is that html modules would be very close to es modules, so the same algorithms that resolve imports and exports for es modules could be reused.

Another benefit of html modules over html imports is that , in the code , the import is not split across two different places.

**Comment by devongovett** [comment] 2019-01-06 02:11
Going to close this since the HTML import spec is obsolete. See @jdanyow's post above for how to do this with PostHTML.

**Closed by devongovett** 2019-01-06 02:11 UTC
Labels: :pray: Help Wanted, :raising_hand_woman: Feature

**Comment by jluisgarcia** [comment] 2019-01-06 10:31
that´s ok.
I will be using php includes. Definitely not going to use posthtml in any case.
it would've been a feature on parcel's side to stand out of the crowd
pity

**Comment by rhildred** [comment] 2019-07-04 02:04
@jdanyow's comment about postHtml worked a treat!
