### ISSUE TITLE
Application not reloading when changing a package stored locally in a parent directory

### ISSUE THREAD

**Issue by betabandido** [parcel-bundler/parcel#7244] opened 2021-11-03 18:25 UTC
# 🐛 bug report

I am using Rollup to bundle a library, and then using Parcel to bundle the library into an example application (in a similar way to what TSDX does). The example app is located in a subdirectory named example and it imports the library from the parent directory (see code sample below).

TSDX uses Parcel v1 and changes made to any source file in the library code result in reloading the example application. Thus, changes are immediately visible on the browser. Yet, after moving to Parcel v2, I cannot get Parcel to automatically reload the example application whenever a change in the library takes place.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```json
{
  "name": "example",
  "version": "0.1.0",
  "license": "UNLICENSED",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "devDependencies": {
    "@types/react": "^16",
    "@types/react-dom": "^16",
    "@types/react-helmet": "^6",
    "@types/sass": "^1",
    "parcel": "^2",
    "postcss": "^8",
    "sass": "^1",
    "tslib": "^2",
    "typescript": "~4.2.0"
  },
  "dependencies": {
    "react": "^16",
    "react-dom": "^16"
  }
}
```

## 🤔 Expected Behavior

I would expect Parcel to behave the same as with v1 -- that is, to automatically reload the example application whenever a change is made to the library contained in the parent directory.

## 😯 Current Behavior

Parcel does not automatically reload the example application. Currently I need to stop Parcel on the example application directory, delete **both** `.parcel-cache` and `dist` folders, and then run Parcel again.

## 💻 Code Sample

https://github.com/betabandido/parcel-reloading-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.17.6 |
| npm/Yarn         | 1.22.11 |
| Operating System | MacOS 10.15.7 |

**Comment by mischnic** [comment] 2021-11-07 17:44
Duplicate of https://github.com/parcel-bundler/parcel/issues/4332. Parcel only watches inside the project root (= the nearest parent folder containing a lockfile or a `.git` directory). So if you are inside `example` and also ran `yarn` in there, the project root is `example`.

A (common) workaround here is setting the repo up as a yarn monorepo. Then the folder containing `README.md` would be the project root and watching would work correctly.

**Closed as completed by mischnic** 2021-11-07 17:44 UTC
