### ISSUE TITLE
🐛  Cannot resolve dependency bootstrap.scss

### ISSUE THREAD

**Issue by lowski** [parcel-bundler/parcel#291] opened 2017-12-15 16:24 UTC
Hi!
I'm trying parcel with react and boostrap setup but I'm getting error when I try to import Boostrap 4.0.0 beta 2.

When I run node-sass directly: `node-sass --include-path node_modules src/styles.scss` it works fine.

### 🎛 Configuration (.babelrc, package.json, cli command)
Here are my `.babelrc` and `.sassrc` files:

```js
{
  "presets": [
    "env", "react"
  ]
}
```

```js
{
  "includePaths": [
    "node_modules"
  ]
}
```

Here is a [repo](https://github.com/lowski/react-parceled) with my app where I encountered this issue.

### 🤔 Expected Behavior
App successfully built and bundled.

### 😯 Current Behavior
`Cannot resolve dependency 'node_modules/bootstrap/scss/bootstrap.scss'` error.

### 🔦 Context
I'm trying to include Bootstrap 4 to my app.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0 |
| Node             |  8.7.0 |
| npm/Yarn         | npm 5.5.1 |
| Operating System | macOS Sierra |

**Comment by DanielRuf** [comment] 2017-12-16 16:07
Same with foundation-sites and motion-ui.

**Comment by DeMoorJasper** [comment] 2017-12-17 13:58
duplicate of #39 closing this off

**Closed by DeMoorJasper** 2017-12-17 13:58 UTC
Labels: #Bug
