### ISSUE TITLE
Strange error when building from cache (Dom web socket when not using web socket at all)

### ISSUE THREAD

**Issue by ogomez92** [parcel-bundler/parcel#920] opened 2018-03-01 04:46 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

I didn't change my babel configuration.

```js
{
  "your": { "config": "here" }
}
```

### 🤔 Expected Behavior
It should build normally, like when I do build. It only fails on watch or server.

### 😯 Current Behavior
The following error is displayed on the console:
main.js:2249 UncaughtDOMException: Failed to construct 'WebSocket': The URL 'ws://:51191/' is invalid.
    at Object.require.19 (file:///Users/uri/git/beat/client/main.js:2249:12)
    at newRequire (file:///Users/uri/git/beat/client/main.js:42:24)
    at require.10 (file:///Users/uri/git/beat/client/main.js:69:5)
    at file:///Users/uri/git/beat/client/main.js:74:3

### 💁 Possible Solution

The command I am running is:
    "watch": "parcel watch ./client/js/main.js -d ./client --target=electron",
It might have something to do with it being a node app I don't know, but apparently some URL is failing where as it never happens without watch.

### 🔦 Context
It affects me slightly because I can't benefit from the watch function or the server function if the file changes.

### 💻 Code Sample

You can grab my repository and test http://oriolgomez.com:9900/ogomez92/beatjs

### 🌍 Your Environment

It happened on both Mac and Windows with the same error.
I was using parcel 1.6.2, latest npm and electron.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment] 2018-03-01 08:47
duplicate of #856

**Closed by DeMoorJasper** 2018-03-01 08:47 UTC
