### ISSUE TITLE
Dynamic imports do not work with non-default imports in the dynamic module

### ISSUE THREAD

**Issue by lukejagodzinski** [parcel-bundler/parcel#6300] opened 2021-05-17 23:11 UTC
# 🐛 bug report

**Bug only happens after creating production build**

There is a weird bug in Parcel 2 (`2.0.0-nightly.671`) when trying to use dynamic imports. So in theory it does correct code splitting with dynamic imports. But when in the imported module I use import like `import { makeStyles } from "@material-ui/styles";` then it crashes application but only after building production version. It works in development. The error says that it can't find module when importing `makeStyles`.

The problem goes away if I don't use dynamic imports, so it doesn't look like an issue with material-ui. Also possible solution is to not use named import but default import in the dynamic module. So instead of writing
```import { makeStyles } from "@material-ui/styles";```
I have to write
```import makeStyles from "@material-ui/styles/makeStyles";```
and then it works.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration. Just default Parcel 2 project with TypeScript + React

package.json

```json
{
  "name": "parcel2-bug",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "@loadable/component": "^5.15.0",
    "@material-ui/core": "^4.11.4",
    "@material-ui/styles": "^4.11.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2"
  },
  "devDependencies": {
    "@types/loadable__component": "^5.13.3",
    "@types/react": "^17.0.5",
    "@types/react-dom": "^17.0.5",
    "@types/react-router": "^5.1.14",
    "@types/react-router-dom": "^5.1.7",
    "parcel": "2.0.0-nightly.671",
    "typescript": "^4.2.4"
  },
  "scripts": {
    "build": "parcel build src/index.html --detailed-report --cache-dir .cache --no-cache",
    "start": "yarn build; npx http-serve -p 3000 ./dist/"
  }
}
```

## 🤔 Expected Behavior

Working dynamic imports with non-default imports in the imported module.

## 😯 Current Behavior

Error throw in the browser console:

```
index.b0a2e93c.js:1 Uncaught Error: Cannot find module '5Pkhs'
    at a (index.b0a2e93c.js:1)
    at Object.<anonymous> (clsx.m.js:39)
    at a (index.b0a2e93c.js:1)
    at getThemeProps.js:22
    at index.tsx:9
```

## 💁 Possible Solution

As I mentioned there is a way to write workaround for it but I would have to change named imports to default imports in the entire project.

## 🔦 Context

Dynamic module imports should just work no matter what I'm importing in the dynamic module. It looks like there is some problem with tree shaking, I guess?

## 💻 Code Sample

Reproduction repository: https://github.com/lukejagodzinski/parcel2-bug
```
yarn
yarn start
```
It will create production build and run local sever

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.671
| Node             | 12 and 14
| npm/Yarn         | Yarn 1.22.10
| Operating System | MacOS Catalina 10.15.7

**Comment by mischnic** [comment] 2021-05-18 09:16
I've just tested https://github.com/parcel-bundler/parcel/pull/6283 on this and it seems to fix it

Minimal reproduction:
```html
<!DOCTYPE html>
<script src="./index.js"></script>
```

```js
/* index.js */
import { Typography } from "@material-ui/core";
console.log(Typography);
import("./home");
```

```js
/* home.js */

import { makeStyles } from "@material-ui/styles";
// Dynamic import will work when dynamically imported file uses default imports.
// import makeStyles from "@material-ui/styles/makeStyles";
console.log(makeStyles);
```

**Comment by lukejagodzinski** [comment] 2021-05-18 11:21
@mischnic nice, so might it be release with the next nightly build?

**Comment by mischnic** [comment] 2021-05-18 11:24
No, https://github.com/parcel-bundler/parcel/pull/6265 and https://github.com/parcel-bundler/parcel/pull/6283 aren't merged yet, it will be in the nightly after that has happened.

**Comment by bay-jacewhitten** [comment] 2021-05-28 16:53
I concur this is an issue after v2.0.0-beta.2 . I downgraded this morning, and now react-select library is bundling properly. 

When I upgrade to v2.0.0-beta.3 , I get a 'ReferenceError: MenuPlacer is not defined'. error 

I was using version next in my package json, but have locked it at beta.2 for now.

Should note , this only happens in build outputs, here are my flags =>   `parcel build --no-source-maps`  not, ENV specific either.

During a normal watch build this library functions as expected.

**Closed as completed** 2021-05-29 05:11 UTC
Labels: :bug: Bug, 🌳 Scope Hoisting, ✨ Parcel 2

**Comment by bay-jacewhitten** [comment] 2021-06-01 14:41
@devongovett Thanks for the merge. Excited to try it out later today and will report back if there is any errors.

EDIT: Never mind, I spoke too soon. Looks like its not released yet. Looking forward to the next iteration.
