### ISSUE TITLE
Parcel2 build command outputs bundles in my src folder instead of dist folder.

### ISSUE THREAD

**Issue by ajm113** [parcel-bundler/parcel#5281] opened 2020-10-26 17:48 UTC
# 🐛 Parcel2 build command outputs bundles in my src folder instead of dist folder.

When I run the `parcel build ./src/index.html --dist-dir ./dist` the bundle will get outputted to my `src` directory instead of the `dist` directory. Running `parcel serve ./src/index.html` works as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "my app",
  "version": "1.0.0",
  "description": "This is a app",
  "main": "src/index.html",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html --dist-dir ./dist",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Andrew",
  "license": "ISC",
  "alias": {
    "components": "./src/components",
    "containers": "./src/containers",
    "style": "./src/style",
    "assets": "./src/assets",
    "libs": "./src/libs",
    "workers": "./src/workers",
    "db": "./src/db"
  },
  "devDependencies": {
    "parcel": "next",
    "sass": "^1.26.11"
  },
  "dependencies": {
    "bulma": "^0.9.1",
    "lunr": "^2.3.9",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0"
  }
}
```

## 🤔 Expected Behavior

It should build to `./dist` even without the additional flag.

## 😯 Current Behavior

Throws all bundle files and replaces my `index.html` with the bundle version.

## 🔦 Context

I'm building a very basic app using React to try out Parcel v2. I never experienced this issue using Parcel v1. Was really hoping to migrate the team to v2. :cry: 

## 💻 Code Sample

N/A

## 🌍 Your Environment

Arch Linux 64x

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.1
| Node             | v12.19.0
| npm/Yarn         |  6.14.7/1.22.10
| Operating System | Arch Linux

**Comment by mischnic** [comment] 2020-10-26 17:55
Remove this line:
```
	"main": "src/index.html",
```

Duplicate of https://github.com/parcel-bundler/parcel/issues/4255 (because the src folder should never be overwritten because of a configuration error).

(Also, `--dist-dir ./dist` isn't needed, that's the default already).

**Comment by ajm113** [comment] 2020-10-26 18:17
@mischnic Thanks for taking the time to reply! I'll give it a shot here in a little while. -- I know at some point it was recommending that I set the main to my `src/index.html` in parcel. So maybe that message is depricated or we should change the context of the message?

> (Also, --dist-dir ./dist isn't needed, that's the default already).

I added it just to be on the safe side. Assumed it was changed for some reason, but wasn't documented.

Again, thank you and I'll reply if that worked or not.

**Comment by mischnic** [comment] 2020-10-26 18:19
> I know at some point it was recommending that I set the main to my src/index.html in parcel.

Which message was that?

`"main"` / `"module"` / `"browser"` is the **output** path.

`"source"` or the CLI arguments are the **input**.

**Comment by ajm113** [comment] 2020-10-26 19:58
I get this error message:
```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/core: Failed to resolve '/home/andrew/Projects/app/src/index.html' 
@parcel/resolver-default: Cannot load file './src/index.html' in './'.
Did you mean ./src/index.jsx?
Did you mean ./dist/index.html?
```

Even if I remove that line I get the same error and changing to `dist/index.html` outputs the same error.

**Comment by mischnic** [comment] 2020-10-26 22:45
But the file "/home/andrew/Projects/app/src/index.html" does exist?

Does deleting the `.parcel-cache` folder fix it?

> EDIT: I added this just to be safe, but no luck:

Again, that is wrong.

**Comment by ajm113** [comment] 2020-10-26 23:31
> But the file "/home/andrew/Projects/app/src/index.html" does exist?

Odd my index.html was removed for some reason... Maybe I deleted it by accident and didn't notice.

Seems like it builds now, but still in the wrong directory sadly.
```
parcel build ./src/index.html --dist-dir ./dist

✨ Built in 17.18s

src/index.html                               657 B     3.58s
src/style.daba710d.css                   197.39 KB     8.73s
src/meggle.139383d9.js                   162.55 KB    10.75s
src/Home.db1b06bc.js                       4.95 KB    10.73s
src/logo.44333a9f.png                      4.78 KB     673ms
src/motivational-mike.01bdba4d.mp4    ⚠️  21.16 MB    10.93s
src/ImageHome.94d4f645.js                   2.5 KB    10.73s
src/WebResults.13983019.js                   39 KB     8.73s
src/WebResults.53888458.js                    2 KB     8.73s
src/wtf.decd9f7b.png                      66.46 KB     672ms
src/ImageResults.d72d1aa1.js               3.72 KB     8.73s
```

**Closed** 2020-10-26 23:34 UTC

**Comment by RichardJECooke** [comment] 2021-07-16 15:46
Why is this closed?  It's still happening in version `^2.0.0-nightly.548`.

`parcel build` dumps output files in my src folder. If I remove the `"main": "src/index.html"` line from my package.json then I get build errors instead.

**Comment by devongovett** [comment] 2021-07-16 18:24
Main can't point to an html file. You'll get an error about that in recent nightly builds.

**Comment by RichardJECooke** [comment] 2021-07-16 18:31
ok thanks. What should it point to please?  My html file is the root of my build
