### ISSUE TITLE
Dynamic import does not work with dynamic strings

### ISSUE THREAD

**Issue by dennishall** [parcel-bundler/parcel#7584] opened 2022-01-20 19:12 UTC
# 🐛 bug report

Attempting to use a template string with interpolation breaks code-splitting/dynamic imports.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
pages/index.js:

async function load () {
  const page = await import(`./pages${window.location.pathname}`);
  // Render page
  page.render();
}
load();


pages/about.js:

export function render() {
  // Render the page
}
```

## 🤔 Expected Behavior
When browsing localhost:1234/about, the about 'page' loads & renders.

## 😯 Current Behavior
When browsing localhost:1234/about, Parcel throws an error, saying it cannot find module './pages/about' .. even though it is there.

## 🔦 Context

I'm trying to make a single-page app with dynamic routes.

## 💻 Code Sample
see above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1
| Node             | 16.11.1
| npm/Yarn         | npm 8.0.0
| Operating System | Windows 10

**Comment by mischnic** [comment] 2022-01-20 19:46
This isn't supported, duplicate of https://github.com/parcel-bundler/parcel/issues/125

What might work for you is using a glob like in this example from https://parceljs.org/features/dependency-resolution/#glob-specifiers
```js
let files = import('./files/*.js');

async function doSomething() {
  let foo = await files.foo();
  let bar = await files.bar();
  return foo + bar;
}
```

**Closed as completed by mischnic** 2022-01-20 19:46 UTC
