### ISSUE TITLE
Attempts to resolve unrelated string

### ISSUE THREAD

**Issue by wlib** [parcel-bundler/parcel#592] opened 2018-01-20 01:59 UTC
# 🐛 bug report - Attempts to resolve unrelated string

### 🎛 Configuration (cli command)

```bash
$ parcel build ./src/index.js
```

### 🤔 Expected Behavior

Parcel should not attempt to resolve random JS strings just because they look like paths.

### 😯  Current Behavior

File Structure:
```
/xyz/project/
  service-worker.js
  src/
    index.js
```

src/index.js:
```js
if ("serviceWorker" in navigator) {
  addEventListener("load", () =>
    navigator.serviceWorker.register("/service-worker.js")
  );
}
```

Error:
```
$ parcel build ./src/index.js
🚨  /xyz/project/src/index.js: Cannot resolve dependency './../../../service-worker.js' at '/service-worker.js'
    at /xyz/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/xyz/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/xyz/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /xyz/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
```

### 💁 Possible Solution

I have no idea, in another project with the same setup, this bug never hit me.

### 🌍  My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel             | 1.4.1       |
| Node              | 9.2.1       |
| Yarn               | 1.3.2       |
| OS                  | OS X Yosemite 10.10.5|

**Comment by DeMoorJasper** [comment] 2018-01-20 09:11
U can use a relative path, or you could wait untill absolute paths get supported (It's not unrelated as the worker.js's code should end up in the dist folder like anything else...)
Duplicate of #86 and #336

**Closed by DeMoorJasper** 2018-01-20 09:11 UTC

**Comment by maksimsemenov** [comment] 2018-07-22 04:53
I don't think this is a duplicate. The core issue is that parcel tries to resolve string that looks like file path when it shouldn't do it. It should leave this string as is
