### ISSUE TITLE
async instance methods result in `ReferenceError: this hasn't been initialised - super() hasn't been called`

### ISSUE THREAD

**Issue by mmcgahan** [parcel-bundler/parcel#7480] opened 2021-12-24 00:28 UTC
# 🐛 bug report

Kind of a specific problem but possibly somewhat common: when bundling a React application that needs to support IE 11, async class instance methods that access their instance with `this` result in a runtime error `ReferenceError: this hasn't been initialised - super() hasn't been called`

## 🎛 Configuration (.babelrc, package.json, cli command)

targeting IE 11 from `package.json#targets`:

```json
  "targets": {
    "default": {
      "engines": {
        "browsers": [
          "ie 11"
        ]
      }
    }
  }
```

build a JS file with `parcel build src/index.tsx`

serve from an HTML document with basic `<script src="dist/index.js"></script>`

## 🤔 Expected Behavior

Normal React rendering

## 😯 Current Behavior

When mounting a class-based React component that includes an async instance method, e.g.

```js
class MyComponent extends React.Component {
  fooInstanceMethod = async () => {
    console.log(this.props)
  }
  render() {
    this.fooInstanceMethod()
    return <p>Hi</p>
  }
}
```

The app crashes (nothing is rendered) and the browser console displays an error:

```
Uncaught ReferenceError: this hasn't been initialised - super() hasn't been called
    at i (_assert_this_initialized.js:3)
    at new n (App.tsx:3)
    at Oa (react-dom.production.min.js:135)
    at ru (react-dom.production.min.js:181)
    at oi (react-dom.production.min.js:269)
    at Bi (react-dom.production.min.js:250)
    at Ai (react-dom.production.min.js:250)
    at ji (react-dom.production.min.js:250)
    at Oi (react-dom.production.min.js:243)
    at Ci (react-dom.production.min.js:237)
```

## 💁 Possible Solution

There's something with building for IE 11 (or older browsers), so I'll probably just drop IE11 support, but it is included with a `>0.5%` browserslist target

You can also convert the instance methods to avoid `async/await` and just use regular Promises. In my case, I have a large codebase that I'm migrating to Parcel, so that would be a lot of work.

## 🔦 Context

Migrating a large existing application with a lot of class-based React components, some of which use instance methods to get the 'automatic binding' that is useful for event handlers in React. Our current browser target is > 0.5% usage, which still includes IE 11 (0.75%), so this problem appeared.

Not a huge deal because we can likely drop IE11 support without too much pushback.

## 💻 Code Sample

Full MVP reproduction of the issue with build & run instructions here https://github.com/mmcgahan/parcel-react-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2
| Node             | 16
| Yarn         | 1.22
| Operating System | macOS 12.0 (M1 Pro)

**Comment by mischnic** [comment] 2021-12-24 10:59
Duplicate of https://github.com/parcel-bundler/parcel/issues/7235

**Closed as completed by mischnic** 2021-12-24 10:59 UTC
