### ISSUE TITLE
Generated TypeScript declaration file (.d.ts) includes type imports with tilde specifiers (`import(~folder/file).TypeName`)

### ISSUE THREAD

**Issue by maxburs** [parcel-bundler/parcel#8434] opened 2022-09-01 22:56 UTC
# 🐛 bug report

Generated TypeScript declaration file (.d.ts) file includes inline type imports with tilde specifiers.  For example: `import("~component/wizard").WizardProps`.

I'm seeing it happen 16 times with 3 different type references in a 889 line .d.ts file. All three types are referenced without the erroneous `import()` other places in the `.d.ts` file. Some of the import paths would resolve to folder, and some files.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm assuming this isn't relevant? I'm happy to update if it is.

Here's our tsconfig
```json
{
    "extends": "../../tsconfig.json",
    "exclude": ["node_modules", "./dist", "./config", "./src/test", "**/__tests__/*", "**/__mocks__/*", "**/*.spec.*"],
    "include": ["src/**/*"],
    "types": ["jest"],
    "compilerOptions": {
        "typeRoots": ["./src/@types", "node_modules/@types"],
        "rootDir": "./src",
        "baseUrl": ".",
        "module": "CommonJS",
        "target": "ESNext",
        "paths": {
            "~*": ["./*"]
        }
    }
}
```
Base tsconfig
```json
{
    "compilerOptions": {
        "esModuleInterop": true,
        "moduleResolution": "node",
        "jsx": "react",
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "resolveJsonModule": true,
        "target": "ESNext",
        "skipLibCheck": true,
        "isolatedModules": true,
        "module": "ESNext"
    },
    "ts-node": {
        "transpileOnly": true,
        "compilerOptions": {
            "module": "CommonJS"
        }
    }
}
```
## 🤔 Expected Behavior

The `WizardProps` type is already in the .d.ts bundle. I'd expect it to omit the import.

## 😯 Current Behavior

 `import("~component/wizard").WizardProps`

## 🔦 Context

Trying to convert React library packages to Parcel.

## 💻 Code Sample

Haven't been able to get a minimal repo. Types that are producing this error are very deep.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0 |
| Node             | 16.15.1 |
| npm/Yarn         | yarn 3.2.1
| Operating System | macos |

**Comment by danieltroger** [comment] 2022-12-07 12:53
Also suffering from this/a similar issue - for some reason the generated .d.ts file references to many types that are contained within the file itself by these `import()` statements, which obviously don't resolve.

So basically there's `export const track_a2c: (tenant: Tenant, selector: string, validator?: ((e: Event) => boolean) | undefined) => import("packages/utilishared/src/element-observer").Disconnector;` in the output file while `export const track_a2c: (tenant: Tenant, selector: string, validator?: ((e: Event) => boolean) | undefined) => Disconnector;` would be correct. I made a script that removes those import statements with a regex for now but would appreciate a better fix. I can provide more reproductions for my case if needed.

(Also the paths of `import` statements that _would_ work are not updated to the new location of the index.d.ts file)

**Comment by maxburs** [comment] 2022-12-08 22:32
I was hoping the typescript changes in 2.8.1 would fix it, but it appears to be unchanged.

The imports fall into two categories, package local imports (`import("~common/lib")`) and relative imports to other packages in our monorepo (`import("~../client/dist")`)

**Comment by danieltroger** [comment] 2023-06-07 06:30
Does this need a better reproduction?

**Comment by mischnic** [comment] 2023-06-07 07:58
Yes, but this is actually a duplicate of #7951. So if you have one, please post it there.

**Closed as not planned by mischnic** 2023-06-07 07:58 UTC
Labels: :bug: Bug, TypeScript
