### ISSUE TITLE
🐛parcel lays a brick when trying to build with error: "template is not a function"

### ISSUE THREAD

**Issue by ogwh** [parcel-bundler/parcel#561] opened 2018-01-15 17:01 UTC
index.html:
```
<!DOCTYPE html>
<html lang="en">
    <head>
    </head>

    <body>
        <script src="./index.tsx"></script>
    </body>
</html>
```
index.tsx contains proprietary code that compiles and runs fine with webpack.

Relevant error message in totality (with index.html directory stripped just because):
```
index.html: template is not a function
    at Object.<anonymous> (C:\Users\Oliver\AppData\Local\Yarn\config\global\node_modules\parcel-bundler\src\visitors\dependencies.js:7:25)
    at Module._compile (C:\Users\Oliver\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (C:\Users\Oliver\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Oliver\AppData\Local\Yarn\config\global\node_modules\parcel-bundler\src\assets\JSAsset.js:4:29)
    at Module._compile (C:\Users\Oliver\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             | 8.9.4
| npm/Yarn         | yarn 1.3.2
| Operating System | Windows 10

**Comment by craftytrickster** [comment] 2018-01-25 14:35
I am also unable to build a project with a root .tsx file, with the exact same setup as ogwh. 

```
∞  Building index.html...
∞  Building index.tsx...
×  C:\dev\projects\X\src\index.tsx: Cannot read property 'line' of undefined
    at extension.eachMapping.mapping (C:\dev\projects\X\node_modules\parcel-bundler\src\SourceMap.js:127:32)
    at Array.forEach (<anonymous>)
    at SourceMap.eachMapping (C:\dev\projects\X\node_modules\parcel-bundler\src\SourceMap.js:93:19)
    at SourceMap.extendSourceMap (C:\dev\projects\X\node_modules\parcel-bundler\src\SourceMap.js:125:15)
    at <anonymous>
(node:292832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'line' of undefined
(node:292832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


|  Software |  Version(s) |
| ------------- |-------------|
|  Parcel | 1.5.0  | 
| Node | 8.9.0 |
| npm     |  4.4.1  |
| OS | Windows 7 |

**Comment by craftytrickster** [comment] 2018-01-25 14:36
@ogwh can you rename the issue to specifically mention the fact this is when .tsx files are involved?

**Comment by DeMoorJasper** [comment] 2018-01-25 15:12
@craftytrickster this seems more like #634 in your case, could u try with `--no-source-maps` to make sure?

**Comment by craftytrickster** [comment] 2018-01-25 17:33
@DeMoorJasper , does eliminate the error I was getting. Unfortunately now, it says `Building random-file.js` for about 40 files and then it begins to hang with no further output/work.

**Comment by DeMoorJasper** [comment] 2018-01-25 17:36
@craftytrickster Ow alright, so that was only one part of the problem is there anyway u could provide us with a test repo to reproduce this issue?

**Comment by ogwh** [comment] 2018-01-25 17:51
@craftytrickster re renaming I’m not entirely sure we’re experiencing the same issue. After filing this issue I gave up and went back to webpack. I’ll have another go this evening with 1.5 to see if it’s still a problem and report back with any findings.

**Comment by craftytrickster** [comment] 2018-01-25 17:57
@DeMoorJasper Hmm, interesting. The following repo was hanging in (git-bash) cygwin - https://github.com/craftytrickster/parcel-debug-issue-repo, but it seems to work in windos cmd. Hope that is helpful.

**Comment by craftytrickster** [comment] 2018-01-25 18:06
It's worth noting that when I use the windows cmd to build the real project (which is much larger than the test repo I posted), windows hangs as well after a certain point. I cannot paste the real repo for IP purposes.

**Comment by termhn** [comment] 2018-02-02 08:16
I am experiencing the exact same issue as OP with just a regular JS file (direct copy of getting started), also on windows 10.

```
Gray@Rocket MINGW64 ~/Code/test
$ parcel index.html
Server running at http://localhost:1234 
🚨  C:\Users\Gray\Code\test\index.html: template is not a function
    at Object.<anonymous> (C:\Users\Gray\AppData\Local\Yarn\config\global\node_modules\parcel-bundler\src\visitors\dependencies.js:7:25)
    at Module._compile (C:\Users\Gray\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (C:\Users\Gray\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Gray\AppData\Local\Yarn\config\global\node_modules\parcel-bundler\src\assets\JSAsset.js:4:29)
    at Module._compile (C:\Users\Gray\AppData\Local\Yarn\config\global\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
```

**Comment by termhn** [comment] 2018-02-02 08:39
Fixed on my machine by adding `babel-template` and `babel-types` to parcel's `package.json`. Not sure if this is indicative of some other larger issue, but submitted a PR that can be reviewed as far as that goes. For a temporary fix, you can try just editing your local copy like I did.

**Closed** 2018-02-05 03:55 UTC
