### ISSUE TITLE
Can't not import static file like png jpeg gif

### ISSUE THREAD

**Issue by jimmycarry** [parcel-bundler/parcel#186] opened 2017-12-10 06:51 UTC
I import a png as my logo but output can't show png  and the output png http://localhost:3300/1091208349dfcfeef178c6131cc02486.png  is redirect to my index.html!

**Comment by RakanNimer** [comment] 2017-12-10 07:05
This is related to #96. And should be fixed by https://github.com/parcel-bundler/parcel/pull/160 

in the meantime, does http://localhost:3300/dist/1091208349dfcfeef178c6131cc02486.png point to your image ?

**Comment by jimmycarry** [comment] 2017-12-10 07:34
yes! and I don't know why? It should be parcel's bugs?

**Comment by jimmycarry** [comment] 2017-12-10 07:46
When I add "./dist"+logo  The image is showed ,but that is not I want

**Comment by RakanNimer** [comment] 2017-12-10 08:05
Yes this is currently an issue with Parcel. You can follow its status here :  #96 or #160.  

Cheers !

**Comment by jimmycarry** [comment] 2017-12-10 08:14
Thx! I'll pay close attention to parcel

**Comment by davidnagli** [comment] 2017-12-11 00:53
Thanks for reporting this 😀 

I'm currently trying to organize all of our open issues. Since this issue seems to be a duplicate of #, I'm gonna go ahead and close this issue.

If you think I've done so in error, please don't hesitate to re-open the issue or send me a message on slack.

**Closed by davidnagli** 2017-12-11 00:53 UTC
