### ISSUE TITLE
Hot reloading fails for nested components

### ISSUE THREAD

**Issue by saadq** [parcel-bundler/parcel#177] opened 2017-12-09 21:04 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

This is a bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

Full example in a minimal repo available here: https://github.com/saadq/misc
Steps to reproduce are listed in the **readme.md** of that repo.

### 🤔 Expected Behavior
Hot reloading should work (without any need to refresh)

### 😯 Current Behavior
Hot reloading works for some components, fails for other components

### 💁 Possible Solution
I think the issue may be related to the the fact that components aren't used directly, but instead I import components from an **index.js** file which happen to import the desired components and reexport them.

### 🔦 Context
I love everything about Parcel, but hot reloading is kinda crucial to workflow nowadays.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           | 1.1.0
| Node             | v8.3.0
| npm/Yarn         | 5.5.1
| Operating System | macOS Sierra 10.12.6

**Comment by Raathigesh** [comment] 2017-12-10 03:49
I'll look into this!

**Comment by Raathigesh** [comment] 2017-12-10 08:42
I was doing a bit of investigation and these are the findings. Following code seems to be the culprit.

https://github.com/parcel-bundler/parcel/blob/cf6902a30a4acc49a5b4572be42781ebf3ed356a/src/builtins/hmr-runtime.js#L100-L106

The file that is not being hot reloaded got two parents, so the following `getParent()` call would return two parent modules and those two modules should be executed for the change to take effect. And note that we are using a `.some` here so as soon as it gets a `true` value, it would stop iterating.

https://github.com/parcel-bundler/parcel/blob/cf6902a30a4acc49a5b4572be42781ebf3ed356a/src/builtins/hmr-runtime.js#L106

But if the following snippet returns `true`, the second parent module would not get executed  (or hot module accepted) because of the above mentioned `.some`.

https://github.com/parcel-bundler/parcel/blob/cf6902a30a4acc49a5b4572be42781ebf3ed356a/src/builtins/hmr-runtime.js#L100-L104

I'm yet to figure out why we are returning `true` if there is a `cached.hot._acceptCallback` available on the module.

Two things would fix the issue but have to dig more into to figure out the right way.
- Make the `.some` into a `.forEach`
- Remove the `return true` from  the following block
https://github.com/parcel-bundler/parcel/blob/cf6902a30a4acc49a5b4572be42781ebf3ed356a/src/builtins/hmr-runtime.js#L100-L104

Maybe @devongovett  can point me in the right direction?

**Comment by maciej-ka** [comment] 2017-12-10 16:04
Hi, I looked at this yesterday too. I used https://github.com/saadq/misc to reproduce. Components tree is like this:

```
<App>
  <Home>
    <Content>
```

`App` and `Home` are ok but `Content` doesn't get hot reloaded.

I haven't found the reason for the problem. Here are my debug sessions, @Raathigesh.

<details>
  <summary>debug of events incomming to WebSocket listener</summary>

```js
if (!module.bundle.parent) {
  var ws = new WebSocket('ws://localhost:{{HMR_PORT}}/');
  ws.onmessage = (e) => {
    var data = JSON.parse(e.data);
    debugger;
```

```js
// Edit in App
// data
{
  type: "update",
  generated: { js: "..." },
  assets: [
    {
      id: 3,
      generated: { js: "..." },
      deps: { react: 5, "./pages": 4 }
    }
  ]
};

// data.generated.js
Object.defineProperty(exports, "__esModule", { value: true });
var _react = require("react");
var _react2 = _interopRequireDefault(_react);
var _pages = require("./pages");
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
function App() {
  return _react2.default.createElement(
    "div",
    null,
    "edit in App",
    _react2.default.createElement(_pages.Home, null)
  );
}
exports.default = App;



// Edit in Home
// data
{
  type: "update",
  generated: { js: "..." },
  assets: [
    {
      id: 12,
      deps: { react: 5, "./Content": 13, "./Footer": 14 }
    }
  ]
};

// data.generated.js
Object.defineProperty(exports, "__esModule", { value: true });
var _react = require("react");
var _react2 = _interopRequireDefault(_react);
var _Content = require("./Content");
var _Content2 = _interopRequireDefault(_Content);
var _Footer = require("./Footer");
var _Footer2 = _interopRequireDefault(_Footer);
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
function Home() {
  return _react2.default.createElement(
    "div",
    null,
    "edit in Home",
    _react2.default.createElement(_Content2.default, null),
    _react2.default.createElement(_Footer2.default, null)
  );
}
exports.default = Home;



// Content
// data
{
  type: "update",
  generated: { js: "..." },
  assets: [
    {
      id: 13,
      deps: { react: 5 }
    }
  ]
};

// data.generated.js
Object.defineProperty(exports, "__esModule", { value: true });
var _react = require("react");
var _react2 = _interopRequireDefault(_react);
function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : { default: obj };
}
function Content() {
  return _react2.default.createElement(
    "main",
    null,
    "edit in Content"
  );
}
exports.default = Content;
```

</details>

<details>
  <summary>debug of `hmrAccept` calls</summary>

```js
function hmrAccept(bundle, id) {
  debugger;
```

Looking at what `id` is passed to. When change is in:
- App: first call with 3, then 2
- Home: 13, 11, 4, 3, 2
- Content: 12, 11, 4, 3, 2

I thought that maybe there is a pattern, that every child should have id's of parent, so
App: 3, 2
Home: 13, 11, 4, (App)
Content: ?

For content (which is breaking) it's slightly different. 
</details>

**Comment by maciej-ka** [comment] 2017-12-10 18:01
@Raathigesh your suggested `forEach` makes sense to me, looks good and works 🎉. Would you create a PR?

**Comment by Raathigesh** [comment] 2017-12-10 22:21
Sure. I'll do.

**Comment by marcioj** [comment] 2017-12-10 22:38
I did some debugging and this is what I think it could be:
When the Content.js file is changed I think this is how the dependency tree looks like:

```
             index.js
                /\
                ||
        components/App.js
                /\
                ||
       components/pages/index.js
                /\
                ||
components/pages/home/index.js <== components/pages/home/Home.js
                        /\           /\
                        ||           ||
                        ||           ||
                 components/pages/home/Content.js
```

The hot reload is updating just the left side, because `getParents` goes all the way up updating the components and then when it hits index.js it stops because the `module.hot.accept()`. This probably leaves the Home.js, where the Content component is rendered, pointing to the old Content version. So the update is not performed for this specific component.

I believe the `some` method is used to abort the updates once the module which calls`module.hot.accept()` is hit.
For this reason removing the `module.hot.accept()` from the code make the updates work. But I imagine it exists for some reason.

**Comment by Raathigesh** [comment] 2017-12-10 23:03
@marcioj You summarized it very well. That's my conclusion as well. I guess @devongovett would be able to shed some light on why we are returning `true` after `cached.hot._acceptCallback();`

**Comment by devongovett** [comment] 2017-12-11 16:37
moving to #204.

**Closed by devongovett** 2017-12-11 16:37 UTC
Labels: #Bug, HMR
