### ISSUE TITLE
No Source Maps when using import in <script type="module">

### ISSUE THREAD

**Issue by Kuinox** [parcel-bundler/parcel#8533] opened 2022-10-11 18:35 UTC
# 🐛 bug report

When I reference a ts file in this fashion:
```html
<script type="module">
  import { startPage } from "./";
  startPage();
</script>
```
sourcemaps are not included/doesn't works.

## 🎛 Configuration (.babelrc, package.json, cli command)

No config.

## 🤔 Expected Behavior
Browser pick up sourcemaps and I can debug my code directly.

## 😯 Current Behavior
With
```html
<script type="module">
  import { startPage } from "./index.ts";
  startPage();
</script>
```
Chrome debuggers shows sources like this: 
![image](https://user-images.githubusercontent.com/18743295/195171507-ff7baea6-a7ef-4712-b75d-1e8eb94d5bb8.png)

When using this more common fashion:
```html
<script type="module" src="./index.ts">
</script>
```
![image](https://user-images.githubusercontent.com/18743295/195171793-44e22185-c0ca-4e47-aaa1-83300fa8454e.png)
The sourcemaps correctly works.
## 💁 Possible Solution

Using more common fashion.

## 🔦 Context

Not very good with browser js, was trying to execute my ts code, found this way, liked it.

## 💻 Code Sample

TODO

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | N/A
| Yarn             | 3.2.4
| Operating System | Windows 11

**Comment by mischnic** [comment] 2022-10-14 14:26
Duplicate of https://github.com/parcel-bundler/parcel/issues/6225

**Closed as not planned by mischnic** 2022-10-14 14:26 UTC

**Comment by Kuinox** [comment] 2022-10-14 14:33
While the bug is the same, the linked issue doesn't exactly ask for the same thing.  
Linked issue ask for inline sourcemaps to work.  
I am simply asking that sourcemaps works in my scenerio. It's parcel that decide, out of the box, to inline the bundle in this scenario.  

If you do not plan to support sourcemaps for inlined bundles, as I see in the other issue, could parcel change it's behavior then, so in dev builds, it doesn't inline the bundle by default ?

**Comment by mischnic** [comment] 2022-10-14 14:38
> It's parcel that decide, out of the box, to inline the bundle in this scenario.

No, Parcel's logic here is that any script/style that is inline in HTML will also be inlined in the build output. https://parceljs.org/languages/html/#inline-scripts-and-styles

So this will result in an inline script:
```html
<script type="module">
  import { startPage } from "./index.ts";
  startPage();
</script>
```
this in a separate JS bundle
```html
<script type="module" src="entry.ts"></script>
```
