### ISSUE TITLE
ENOENT error after changing the html file

### ISSUE THREAD

**Issue by filipcodes** [parcel-bundler/parcel#8571] opened 2022-10-23 11:14 UTC
# 🐛 bug report
Hey there people, first time using Parcel. There is this weird thing happening, where I can create the live server, but after changing the HTML, it shows up ENOENT error instead of automatically changing the dist/index.html and the content of the website.

## 🎛 Configuration (.babelrc, package.json, cli command)

This is my package.json. I am using `npm start` to get the server running.
```js
{
  "name": "calculator_project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.7.0",
    "parcel": "^2.7.0",
    "sass": "^1.55.0"
  }
}

```

## 🤔 Expected Behavior

Parcel should edit the `dist/index.html` and change the content on the live server

## 😯 Current Behavior

Parcel allows me to change the html once, and save it, but after that, saving the file results in the following error:

```
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\w\Desktop\projects\calculator_project\dist\index.html.9808.6'
    at Object.unlinkSync (node:fs:1735:3)
    at WriteStream.<anonymous> (C:\Users\w\Desktop\projects\calculator_project\node_modules\@parcel\fs\lib\index.js:1030:83)
    at Object.onceWrapper (node:events:642:26)
    at WriteStream.emit (node:events:539:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'C:\\Users\\w\\Desktop\\projects\\calculator_project\\dist\\index.html.9808.6'
}
```

## 🔦 Context

I am trying to learn using sass and parcel, as it is a real world technology being used by companies. I decided to do just a simple calculator.

## 💻 Code Sample

My HTML:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scientific Calculator</title>
    <link rel="stylesheet" href="scss/main.scss" />
  </head>
  <body>
    <h1>Hello world</h1>
  </body>
</html>
```

my folder set up
![obrázok](https://user-images.githubusercontent.com/112976056/197386149-4a40fbad-73c8-4626-87c6-e81e8575a263.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | Node.js v16.16.0.
| npm/Yarn         | npm 8.11.0
| Operating System | Windows

**Comment by Josep1992** [comment] 2022-10-26 01:36
Hey @filipcodes , I think you're missing the `"source"` property on the `package.json` file.

It should look like this 
```json
 "source": "src/index.html"
```

**Comment by mischnic** [comment] 2023-01-07 11:38
Duplicate of https://github.com/parcel-bundler/parcel/issues/8615

**Closed as not planned by mischnic** 2023-01-07 11:38 UTC
Labels: Windows

**Comment by andrew-rinato** [comment] 2023-02-06 11:17
Dropbox file sync appeared to be the culprit for me.

**Comment by sung92** [comment] 2023-11-23 14:59
I have been experiencing this same issue for the last 2 weeks, which never happened before. As soon as I change something in HTML, I got "ENOENT: no such file or directory" error.

**Comment by lllleao** [comment] 2024-03-07 17:05
It happens the same with me. I can't modified the HTML, cause every single time parcel brokes

**Comment by filipcodes** [comment] 2024-03-07 17:16
Hey, my guy, just use Vite if you can. Gonna make it much easier.

**Comment by sung92** [comment] 2024-03-07 17:17
Yeah, I happened to switch to Vite a couple of weeks and working fine.

**Comment by lllleao** [comment] 2024-03-08 18:50
Thank guys. I realized what was wrong. There's a conflict with the autosave from VS code.

**Comment by vkthakur98** [comment] 2024-09-29 01:43
How can I resolve this?

**Comment by abdallahmansour6** [comment] 2024-11-12 04:31
> Thank guys. I realized what was wrong. There's a conflict with the autosave from VS code.

Can you please elaborate what was the issue or the solution?
