### ISSUE TITLE
Unclear `extendDefaultPlugins` message during build

### ISSUE THREAD

**Issue by oliversalzburg** [parcel-bundler/parcel#6870] opened 2021-09-02 11:18 UTC
# 🐛 bug report

When I build a project, I get a message regarding `extendDefaultPlugins`, which I do not understand and I don't know what it is in relation to.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

Trying to build https://github.com/graphql/graphiql/tree/main/examples/graphiql-parcel

## 🤔 Expected Behavior

A built version of GraphiQL appears in the output folder without complaints.

## 😯 Current Behavior

This is printed in the console:
```console
console: 
"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}
```

## 💁 Possible Solution

No idea.

## 🔦 Context

I don't understand where this message is coming from or what the call to action is.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 16.8.0
| npm/Yarn         | 3.0.1
| Operating System | WSL

**Comment by mischnic** [comment] 2021-09-02 11:38
Duplicate of https://github.com/parcel-bundler/parcel/issues/6744. We have to wait for the next htmlnano release

**Closed as completed by mischnic** 2021-09-02 11:38 UTC
