### ISSUE TITLE
File hash won't change if lazy imports change

### ISSUE THREAD

**Issue by christophgysin** [parcel-bundler/parcel#2783] opened 2019-03-13 12:03 UTC
# 🐛 bug report

When the hash of a bundle A changes, the hash of a bundle B that includes bundle A should also change.

## 🎛 Configuration (.babelrc, package.json, cli command)

`$ cat package.json`
```
{
  "dependencies": {
    "parcel": "^1.12.1",
    "react": "^16.8.4"
  }
}
```

`$ cat src/index.html`
```
<!DOCTYPE html>
<html lang="en">
<body>
  <div id="app"></div>
</body>
<script src="../src/index.jsx"></script>
</html>
```

`$ cat src/index.jsx`
```
import React from 'react';

const App = React.lazy(() => import('./app'));

ReactDOM.render(
  <App/>,
  document.getElementById('app'),
);

```
`$ cat src/app.jsx`
```
import React from 'react';

class App extends React.Component {
  render() {
    return <div/>;
  }
}

export default App;
```

## 🤔 Expected Behavior

When changing `src/app.jsx`, a new `dist/app.<hash>.js`is generated. The contents of `dist/src.<hash>.js` changes (it includes the newly generated app.<hash>.js), so I would expect its hash to change as well.

## 😯 Current Behavior

The contents of `dist/src.<hash>.js` changes, but the hash stays the same:

`$ yarn parcel build --no-source-maps src/index.html`
```
yarn run v1.13.0
warning package.json: No license field
$ /home/chris/projects/tso/parcel-hash-import-bug/node_modules/.bin/parcel build --no-source-maps src/index.html
✨  Built in 186ms.

dist/src.2f41f0fd.js    10.83 KB    49ms
dist/app.94adb5d7.js     2.63 KB     9ms
dist/index.html            113 B     5ms
Done in 0.83s.

```
`grep -o "app\.........\.js" dist/src.*.js`
```
app.94adb5d7.js
```
`echo "console.log();" >> src/app.jsx`
```
yarn parcel build --no-source-maps src/index.html
yarn run v1.13.0
warning package.json: No license field
$ /home/chris/projects/tso/parcel-hash-import-bug/node_modules/.bin/parcel build --no-source-maps src/index.html
✨  Built in 546ms.

dist/src.2f41f0fd.js    10.83 KB    405ms
dist/app.928a6dd3.js     2.65 KB    383ms
dist/index.html            113 B      4ms
Done in 1.33s.
```
`grep -o "app\.........\.js" dist/src.*.js`
```
app.928a6dd3.js
```

## 🔦 Context

This breaks caching, since a file with the same name can contain different content.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.1
| Node             |  11.11.0
| npm/Yarn         | 1.13.0
| Operating System | linux

**Comment by mischnic** [comment] 2019-03-13 17:06
Yes, closing as duplicate of #1481

**Closed by mischnic** 2019-03-13 17:06 UTC
