### ISSUE TITLE
problems when using with `ant-design` / `rc-table`

### ISSUE THREAD

**Issue by Tommos0** [parcel-bundler/parcel#4483] opened 2020-04-16 09:02 UTC
Related issue: https://github.com/react-component/table/issues/458

Live demo: https://tommos0.github.io/parcel-typescript-antd/dist
Source: https://github.com/Tommos0/parcel-typescript-antd

Problem with `rc-table` occurs when using a minified `parcel build`. Everything is fine using `parcel build --no-minify`. I thought the problem was in `terser`, but disabling most of terser doesn't seem to help (I put `mangle: false` in .terserrc, but it seems this setting is not respected, or there is another mangler running). Is there another minification step used? Some pointers might help me in debugging.

Creating a bundle using `parcel build --no-minify` and then manually running `terser --compress --mangle` on it produces a bundle that works fine.

**Comment by Tommos0** [comment] 2020-04-16 10:40
I found that indeed each asset is individually mangled first, not respecting the options in terserrc.

Actually it seems things are fixed when using parcel@next.

**Comment by mischnic** [comment] 2020-04-19 21:55
According to the linked issue this is a duplicate of https://github.com/parcel-bundler/parcel/issues/3523.

Closing this especially since it seems to be working with Parcel 2.

**Closed by mischnic** 2020-04-19 21:55 UTC
