### ISSUE TITLE
Importing electron-log causes "Uncaught TypeError: Arguments to path.join must be strings"

### ISSUE THREAD

**Issue by nyxynyx** [parcel-bundler/parcel#4564] opened 2020-05-04 02:47 UTC
# 🐛 bug report

Importing `electron-log` in a single line

    import log from 'electron-log'

causes an error in the Devtools JS console

> Uncaught TypeError: Arguments to path.join must be strings

![image](https://user-images.githubusercontent.com/8941374/80933005-d5800c80-8d8f-11ea-9057-0140d76fa544.png)

and causes an error in the terminal where we run `yarn start`:

> Cannot statically evaluate fs argument

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**

```js
{
  "name": "electron-react-parcel",
  "version": "1.0.0",
  "description": "Electron app build using ReactJS and Parcel web application bundler",
  "main": "src/electron.js",
  "scripts": {
    "react-start": "parcel -p 3000 index.html --out-dir build",
    "react-build": "parcel build index.html --out-dir build --public-url ./",
    "electron-build": "electron-builder -mwl",
    "clean-build": "rm -rf build/ .cache dist/",
    "build": "yarn clean-build && yarn react-build && yarn electron-build",
    "start": "concurrently \"cross-env BROWSER=none yarn react-start\" \"wait-on http://localhost:3000 && electron . \"",
    "test-bundle": "bundlesize"
  },
  "bundlesize": [
    {
      "path": "./build/src.*.js",
      "maxSize": "250 kB"
    },
    {
      "path": "./build/src.*.css",
      "maxSize": "100 kB"
    }
  ],
  "keywords": [
    "boskysoft",
    "electron",
    "react",
    "parcel",
    "electron-react-parcel",
    "electron react parcel"
  ],
  "author": "Yogesh Kumar <yogesh@boskysoft.com>",
  "license": "MIT",
  "build": {
    "appId": "com.boskysoft",
    "files": [
      "src/electron.js",
      "src/assets/*",
      "build/**/*"
    ],
    "mac": {
      "target": "dmg",
      "icon": "src/assets/logo.png"
    },
    "win": {
      "target": "nsis",
      "icon": "src/assets/logo.png"
    },
    "linux": {
      "target": "deb",
      "icon": "src/assets/logo.png",
      "category": "Development"
    }
  },
  "homepage": "./",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "autoscroll-react": "^3.2.0",
    "axios": "^0.19.2",
    "bootstrap": "^4.4.1",
    "connected-react-router": "^6.8.0",
    "electron-google-analytics": "^0.2.2",
    "electron-is-dev": "1.2.0",
    "electron-log": "^4.1.2",
    "history": "^4.10.1",
    "immutable": "^3.8.1 || ^4.0.0-rc.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "react": "^15.6.0 || ^16.0.0",
    "react-bootstrap": "^1.0.0",
    "react-country-region-selector": "^2.1.0",
    "react-dom": "^16.13.1",
    "react-identicons": "^1.2.4",
    "react-infinite-scroller": "^1.2.4",
    "react-loader-spinner": "^3.1.14",
    "react-moment": "^0.9.7",
    "react-redux": "^7.2.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-localstorage": "^0.4.1",
    "redux-thunk": "^2.3.0",
    "reset-css": "^5.0.1",
    "seamless-immutable": "^7.1.3",
    "semantic-ui-css": "2.4.1",
    "socket.io-client": "^2.3.0",
    "uuid": "^7.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-transform-react-jsx": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "bundlesize": "^0.18.0",
    "concurrently": "^5.0.2",
    "cross-env": "7.0.2",
    "electron": "^8.2.3",
    "electron-builder": "^22.5.1",
    "electron-devtools-installer": "^3.0.0",
    "parcel-bundler": "^1.12.4",
    "wait-on": "4.0.2"
  }
}
```

**.babelrc**
```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ]
}

```

## 🤔 Expected Behavior

No error should appear on importing `electron-log`.

## 😯 Current Behavior

After adding the line

    import log from 'electron-log'

we get the following error in the JS console:

```js
[0] ⚠️  /Users/nyxynyx/electron-log-parcel-problem/node_modules/electron/index.js:8:41: Cannot statically evaluate fs argument
[0]    6 | function getElectronPath () {
[0]    7 |   if (fs.existsSync(pathFile)) {
[0] >  8 |     var executablePath = fs.readFileSync(pathFile, 'utf-8')
[0]      |                                         ^
[0]    9 |     if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
[0]   10 |       return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
[0]   11 |     }
[0] ⚠️  /Users/nyxynyx/electron-log-parcel-problem/node_modules/electron-log/src/transports/file/packageJson.js:35:42: Cannot statically evaluate fs argument
[0]   33 |     }
[0]   34 | 
[0] > 35 |     var json = JSON.parse(fs.readFileSync(fileName, 'utf8'));
[0]      |                                          ^
[0]   36 |     var name = json.productName || json.name;
[0]   37 |     if (!name || name.toLowerCase() === 'electron') {
[0]   38 |       return null;
```

and the following error in the Electron devtools JS console:

```js
Uncaught TypeError: Arguments to path.join must be strings
    at index.js:117
    at Array.filter (<anonymous>)
    at filter (index.js:287)
    at Object.exports.join (index.js:115)
    at getUserData (variables.js:104)
    at getLibraryDefaultDir (variables.js:49)
    at Object.getPathVariables (variables.js:95)
    at fileTransportFactory (index.js:16)
    at create (index.js:47)
    at Object.parcelRequire.node_modules/electron-log/src/index.js../catchErrors (index.js:12)
```

**(index.js:12) highlighted**

![image](https://user-images.githubusercontent.com/8941374/80932904-79b58380-8d8f-11ea-9685-abfae69dc77a.png)

## 💻 Code Sample

👉 **Github Repo: https://github.com/nyxynyx/electron-log-parcel-problem**

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v14.0.0
| Yarn             | 1.22.4
| Operating System | Mac OS X Catalina 10.15.3

**Comment by mischnic** [comment] 2020-05-04 09:55
This is also because without `--target electron` or `--target node`, `fs` isn't really available.
Duplicate of https://github.com/parcel-bundler/parcel/issues/4539.

**Closed by mischnic** 2020-05-04 09:55 UTC
