### ISSUE TITLE
SCSS file importing a CSS file throws Uncaught (in promise) Error: Cannot find module

### ISSUE THREAD

**Issue by angushtlam** [parcel-bundler/parcel#1403] opened 2018-05-21 21:15 UTC
# 🐛 Bug report

When a SCSS file imports a CSS file, an error shows up in the browser console, saying `Uncaught (in promise) Error: Cannot find module`. The CSS file in question still works and is still built.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see the minimal project setup located here [https://github.com/angushtlam/angus/tree/parcel-bug](https://github.com/angushtlam/angus/tree/parcel-bug).

There is no `.babelrc` file. The `package.json` configuration is minimal, and with the two relevant installed dependencies `"node-sass": "^4.9.0"` and `"parcel-bundler": "^1.8.1"`. The command to build the project is `yarn dev`, which is mapped to `parcel src/index.html`.

## 🤔 Expected Behavior

There should be no errors in the browser console.

## 😯 Current Behavior

The CSS file in question looks like it gets built correctly and included in the website, but there is an error that shows up in the browser console relating to the CSS I'm importing (`normalize.css`).

Other issues for Parcel that had the same error message looks like it has to do with importing the same resource twice, but in the code example the CSS file is only imported once in the `index.scss` file.

Error message:
<img width="448" alt="screen shot 2018-05-21 at 5 00 35 pm" src="https://user-images.githubusercontent.com/8825042/40329822-def91756-5d18-11e8-9187-cd6f9232cac5.png">

## 💁 Possible Solution

Changing the extension of the importing CSS file to SCSS will prevent the error message from showing up.

## 🔦 Context

I was originally trying to import `normalize.css` from `node_modules`, but I kept running into this error, where the CSS file is imported and loaded correctly, but kept throwing this error. Thinking that this is an issue with `node_modules`, I then tried to get rid of the error by making a copy of the `normalize.css` into my project and import it (which is not ideal, since I want to keep the dependency updated through npm).

The error still persisted, but it looks like it has to do with trying to import a CSS file through a SCSS file.

## 💻 Code Sample

Please see the minimal project setup located here [https://github.com/angushtlam/angus/tree/parcel-bug](https://github.com/angushtlam/angus/tree/parcel-bug).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | v8.11.0 | 
| Yarn         | 1.5.1 |
| Operating System | Mac OS X |

**Comment by evanleck** [comment] 2018-12-17 23:06
@DeMoorJasper or @angushtlam have y'all got any ideas on this one? I'm hitting the same issue trying to import normalize.css into a SCSS file using any of the following approaches:

```
@import 'normalize.css';
@import '~/node_modules/normalize.css';
@import '~/node_modules/normalize.css/normalize.css';
@import '../../node_modules/normalize.css';
@import '../../node_modules/normalize.css/normalize.css';
```

**Comment by DeMoorJasper** [comment] 2018-12-18 08:53
@evanleck strange, I've been using this on various project and never had any issues with it. Could anyone create a minimal repro repo.

Note the original issue is using a very outdated version of Parcel. If this is fixed in the latest version let me know, so I can close this.

**Comment by evanleck** [comment] 2018-12-18 15:38
@DeMoorJasper it looks like it's related to node-sass and doesn't happen when using the sass package. I created [a simple reproduction repository](https://github.com/evanleck/parcel-1403-reproduction) if you'd like to try it out. Switching from node-sass to sass apparently fixes the issue.

**Comment by evanleck** [comment] 2018-12-18 15:50
@DeMoorJasper while pulling normalize in works using sass with that first test repository, it seems to break imports of other local stylesheets e.g. `@import '/styles/_variables.scss';`. I've made [another small repository](https://github.com/evanleck/parcel-1403-reproduction-sass) to show what I mean. Running `npm run serve` throws an error but the path is using the [absolute path](https://parceljs.org/module_resolution.html) approach defined in the module resolution docs.

**Comment by evanleck** [comment] 2018-12-18 16:05
I've also confirmed locally that attempting to import a `.css` file into a `.scss` file using node-sass still fails in the same way, as the original author of this issue pointed out.

**Comment by DeMoorJasper** [comment] 2018-12-18 16:19
Well, we just support node-sass for backwards compatibility but no longer recommend it due to the lot's of known issues it has especially when running it in parallel like parcel does.

I assume this issue can be closed?

**Closed** 2018-12-18 16:20 UTC
Labels: :bug: Bug

**Comment by evanleck** [comment] 2018-12-18 16:22
@DeMoorJasper fair enough on the node-sass compatibility. It still appears that using sass and absolute paths e.g. `@import '/styles/_variables.scss';` is broken, however. The reproduction repository is at https://github.com/evanleck/parcel-1403-reproduction-sass if you're curious to look at it.
