### ISSUE TITLE
Styles are not included if used on multiple pages

### ISSUE THREAD

**Issue by uNmAnNeR** [parcel-bundler/parcel#3447] opened 2019-08-21 13:32 UTC
# 🐛 bug report

Hi!
When incluide same javascript which imports styles, then after compilation styles appears only on one page.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "flashrepair-fe",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel serve --log-level=4 ./src/html/index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3",
    "sass": "^1.22.10"
  }
}
```

## 🤔 Expected Behavior

styles are on all pages

## 😯 Current Behavior

styles only on one page

## 💻 Code Sample

here is source code:
https://github.com/chocolateboy/flashrepair-fe/tree/strip-nunjucks

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.8
| npm/Yarn         | 6.10.1
| Operating System | win10x64

**Comment by mischnic** [comment] 2019-08-26 16:59
Your issue description is very minimal, but I suspect this is a duplicate of this bug: https://github.com/parcel-bundler/parcel/issues/2340, which is fixed in Parcel 2.

Please provide a reproduction if you think this is not the same bug.

**Closed by mischnic** 2019-08-26 16:59 UTC
Labels: :bug: Bug
