### ISSUE TITLE
Parcel 2: Browser is not updated when the source changes

### ISSUE THREAD

**Issue by mahdix** [parcel-bundler/parcel#7409] opened 2021-12-05 15:33 UTC
Summary: When I start Parcel dev server via `parcel serve src/pages/*.html` it works fine for the very first time.
But when I make a change in the .tsx file, the browser is not updated.
Things that I have tried:
1. Force refresh browser
2. Change the file using another editor (Sublime, vim)
3. Stop and restart Parcel
4. `rm -rf dist` and `.parcel-cache`

After several tries, it just starts working fine (but for one time, later changes are again not shown).

My package.json:
```
{
  "name": "socialmonitr-front-end",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "private": true,
  "scripts": {
    "build": "parcel build src/pages/*.html --no-source-maps --no-scope-hoist",
    "serve": "parcel serve src/pages/*.html"
  },
  "keywords": [],
  "author": "",
  "license": "Commercial",
  "packageManager": "yarn@3.1.1",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "@types/react": "17.0.34",
    "@types/react-dom": "17.0.11",
    "parcel": "2.0.1",
    "typescript": "4.4.3"
  },
  "dependencies": {
    "@emotion/react": "^11.7.0",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.2.0",
    "@mui/material": "^5.2.1",
    "@mui/x-data-grid": "^5.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  }
}

```

The source file can be any simple tsx:
```
export const Index = () => {
    return <>
        this is a test
    </>

}
```

index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>My Parcel App</title>
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    />
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />

</head>
<body>
<div id="app"></div>
<script type="module" src="index.js"></script>
</body>
</html>
```

index.js:
```
import ReactDOM from "react-dom"
import { Index } from "../components"

ReactDOM.render(<Index />, document.getElementById("app"));
```

Parcel: 2.0.1
Yarn: 3.1.1
Node: 16.11.0

I use IntelliJ to edit files but as I mentioned, even editing the TSX source using other browsers does not fix the issue.

P.S: Somehow I suspect this is related to Yarn 3 (PnP) because I downgraded to yarn v1 and (at least for now) it is working fine.

**Comment by folknor** [comment] 2021-12-14 15:14
This is probably a duplicate of #6685 or one of the other 10+ HMR open tickets. I have the same problem using html+js, but there's enough open tickets.

**Closed as completed** 2022-01-02 23:04 UTC
Labels: HMR
