### ISSUE TITLE
 @parcel/core: Failed to resolve 'process' from './node_modules/@firebase/database/dist/index.esm2017.js'

### ISSUE THREAD

**Issue by jimhortons** [parcel-bundler/parcel#7704] opened 2022-02-13 17:35 UTC
# Firebase Parcel Error
REPO  https://github.com/jimhortons/firebase-parcel-error
You will need a firebase project setup to reproduce error. 

## Started
Error started on Thursday February 10th 2022 up until that point I was installing firebase@9.6.6  with parcel@2.2.1 with no issues. However on Thursday the following error started to occur. I checked with several colleagues who use firebase on Window and Mac we all got the same error. It happened to them at the same time sometime between Wednesday February 9th, 2022 and Thursday February 10th 2022. Prior to this there were no issues. We are not in the same office this error happened on different machines in different locations.

 

### THURSDAY FEBRUARY 10th ERROR FIREBASE/PARCEL
- Download the repo and run npm install.
- Then run ```parcel index.html```
- Open the console you should see the firebase app logged in the console.
- Go to the index.html uncomment lines two and three.
- Run ```parcel index.html``` again
- generates error output is showen below.

### GENERATED ERROR
Here is the output of the error that I see as others see on there 

```pre
    firebase-error $ parcel index.html
    Server running at http://localhost:1234
    [Error: ENOENT: no such file or directory, open 'node_modules/@firebase/database/src/realtime/WebSocketConnection.ts'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: 'node_modules/@firebase/database/src/realtime/WebSocketConnection.ts'
    Server running at http://localhost:1234
    🚨 Build failed.


    @parcel/core: Failed to resolve 'process' from './node_modules/@firebase/database/dist/index.esm2017.js'

    node_modules/@firebase/database/dist/index.esm2017.js:164:74

    163 |  * Unless required by applicable law or agreed to in writing, software
  > 164 |  * distributed under the License is distributed on an "AS IS" BASIS,
  >     |    ^
    165 |  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    166 |  * See the License for the specific language governing permissions and

```

###  What I Tried 
- I install several versions of firebase and parcel that had worked previously.
- Each of the different combinations of parcel and firebase I tried produced the same error.
- I had friends and colleagues try to configure there own firebase projects with parcel and they all got the same error.
- Used snowpack to see if it was firebase but I could connect to firebase realtime database with no errors.

 # WORKAROUND
- REPO  https://github.com/jimhortons/firebase-parcel-error
- __WEDNESDAY FEBRUARY 9th PACAGE-LOCK.JSON__
- Uncomment the package.json and the package-lock.json files
- Rename feb-package.json and feb-package-lock.json.
- Run ```npm install```
- Run ```parcel index.html```
- Should start and connect to real time database.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1, 2.2.1, 2.0.1
| Node             |. 16+
| npm/Yarn         | v16.14.0 (npm v8.3.1)
| Operating System | MAC OS 10 11.4

**Comment by krivcikfilip** [comment] 2022-02-14 09:07
I am installed this package: https://www.npmjs.com/package/process and now it works :D

**Comment by spointecker** [comment] 2022-02-14 09:19
See https://github.com/parcel-bundler/parcel/issues/7697 (I just updated the title of the issue so it is more obvious for everyone else)

**Comment by mischnic** [comment] 2022-02-14 09:58
Duplicate of https://github.com/parcel-bundler/parcel/issues/7697

**Closed as completed by mischnic** 2022-02-14 09:58 UTC

**Comment by jimhortons** [comment] 2022-02-16 04:39
thanks spointecker 
Jim
