### ISSUE TITLE
@parcel/resolver-default: Error parsing JSON - expected value at line 1 column 1

### ISSUE THREAD

**Issue by ProVega** [parcel-bundler/parcel#9223] opened 2023-08-31 23:58 UTC
# 🐛 bug report

Vannilla install of Parcel 2, Vue 3, and TypeScript 4.9.x

## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
	"name": "aspnetcore-vuecomponents",
	"version": "1.0.0",
	"devDependencies": {
		"@parcel/transformer-typescript-tsc": "2.8.3",
		"@parcel/transformer-vue": "2.8.3",
		"@vue/component-compiler-utils": "^3.3.0",
		"@vue/web-component-wrapper": "^1.3.0",
		"@tsconfig/recommended": "^1.0.2",
		"eslint": "^8.48.0",
		"parcel": "2.8.3",
		"typescript": "^4.9.4",
		"vue": "^3.3.4"
	},
	"scripts": {
		"build": "parcel build ./wwwroot/js/site.ts --dist-dir ./wwwroot/js/dist"
	},

	"@parcel/resolver-default": {
		"packageExports": true
	}
}
```

No matter what I have in my tsconfig.json  file, I get this generic error saying it can't parse the JSON file. Looking at the error, it doesn't even try to parse the JSON as it doesn't like the open { character.

![image](https://github.com/parcel-bundler/parcel/assets/1735840/34ba0e29-e133-4ded-a792-118b2e1b1e74)

Rolling back 2.8.3 works - so I am assuming this bug?

## 🤔 Expected Behavior

The tsconfig.json file should be loaded, parsed and used without issue.

## 😯 Current Behavior

JSON Parsing error

```
@parcel/resolver-default: Error parsing JSON

  C:\Source\Trunk_2023a\Crelate.Web.AppStore\tsconfig.json:1:1
  > 1 | ﻿{
  >   | ^ expected value at line 1 column 1
    2 |   "compilerOptions": {
    3 |     "baseUrl": ".",
```

## 💁 Possible Solution

Roll back 2.8.3

## 🔦 Context

I am new to Parcel, but this seems pretty straight forward as rolling back just works.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 18
| npm/Yarn         | NPM 9.6.7
| Operating System | Windows 11

**Comment by mischnic** [comment] 2023-09-19 16:07
There is a unicode BOM in the tsconfig: 
<img width="419" alt="Bildschirm­foto 2023-09-19 um 18 05 54" src="https://github.com/parcel-bundler/parcel/assets/4586894/145e2511-d612-4ca0-b8ab-b581a7ed9f79">

It works if you remove that.

Duplicate of https://github.com/parcel-bundler/parcel/issues/8378#issuecomment-1596636855

**Closed as completed by mischnic** 2023-09-19 16:07 UTC
Labels: Resolver
