### ISSUE TITLE
scss - import not removed from bundle

### ISSUE THREAD

**Issue by DaveO-Home** [parcel-bundler/parcel#3052] opened 2019-05-17 15:52 UTC
# ❔ Question

Using import "./scss/index.scss"; bundle has require("./scss/index.scss"); and when the bundle is loaded expects the file to exist on the server.  The css has already been produced and is loaded properly. So, why does the ".scss" file have to be visible?
## 🔦 Context
Using gulp to build -
const options = {
        production: isProduction,
        outDir: '../' + dist,
        contentHash: false,
        outFile: isProduction ? 'index.html' : 'index_dev.html',
        publicUrl: watch ? '' : './',
        watch: watch,
        cache: !isProduction,
        cacheDir: '.cache',
        minify: isProduction,
        target: 'browser',
        https: false,
        logLevel: 3,
        sourceMaps: !isProduction,
        detailedReport: isProduction
    };

Must provide .scss file on production server

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |10.15.3
| npm/Yarn         | 6.9
| Operating System | Fedora 30

**Comment by mischnic** [comment] 2019-05-28 14:55
The JS bundle says `require("./scss/index.scss");` but it really only loads the css file and if I read your post correctly, that works correctly.

Your issue is that the JS bundle still contains `.scss`? Why is this a problem?

**Comment by DaveO-Home** [comment] 2019-05-28 16:57
It also attempts to load the .scss file, that is the problem. I have to deploy an empty index.scss to the server.

**Comment by mischnic** [comment] 2019-05-28 17:00
> It also attempts to load the .scss file, that is the problem.

Could you create a minimal example when this happens?

**Comment by DaveO-Home** [comment] 2019-05-28 18:46
@mischnic  Ok, it does work.  However, I'm using parceljs to build a library. Then in an app I use Browserify to build.  Apparently, browserify interprets the 'require' as commonjs?.... Close if parcel does not support something like this.

**Comment by mischnic** [comment] 2019-05-28 18:52
> Apparently, browserify interprets the 'require' as commonjs?.... Close if parcel does not support something like this.

Webpack and browserify both think the `require` that. Here's a similar issue: https://github.com/parcel-bundler/parcel/issues/2883

The library you built with parcel contains a line like this (for a non minified bundle `parcel build --no-minify src/index.js`:
```js
var nodeRequire = typeof require === 'function' && require;
```
Could you try replacing that with
```js
var nodeRequire = null;
```
and testing how browserify behaves then?

**Comment by DaveO-Home** [comment] 2019-05-28 20:08
@mischnic  - var nodeRequire = null does not work.  However, if I delete the line;
require("../scss/index.scss");
it works perfectly.

**Comment by mischnic** [comment] 2019-05-28 20:12
Ok, I'll have to investigate how we can make webpack and browserify ignore the `require`s emitted by parcel...

I'll close this issue because it's caused by the same underlying problem as https://github.com/parcel-bundler/parcel/issues/2883

**Closed by mischnic** 2019-05-28 20:12 UTC
Labels: :bug: Bug

**Comment by mischnic** [comment] 2019-06-02 19:15
Note, I strongly advise not using Parcel's feature of importing style in a library. Reasons:
1. The bundler of the end user doesn't know that the style file is needed at runtime
2. (more importantly) Might be surprising to see a css file being loaded all of the sudden

**Comment by DaveO-Home** [comment] 2019-06-03 16:46
@mischnic - Yes I did that as my work around. Works fine.  There is one other issue with using Parcel to build a library.  The bundle scopes ```parcelRequire=function``` to window.  This does not work with "Rollup".  I changed it to ```var parcelRequiere=function``` without any side effects.  Works in all tested bundlers.
