### ISSUE TITLE
Html script tags failing

### ISSUE THREAD

**Issue by kkuchta** [parcel-bundler/parcel#5373] opened 2020-11-21 00:11 UTC
# 🐛 bug report

Given a minimal index.html file like this:

```
<html>
  <script>
    console.log("1");
  </script>
  <script>
    console.log("2");
  </script>
  <script src="./foo.js"></script>
</html>
```
And foo.js like this:
```
console.log("3");
```

Using parcel 2's serve (`yarn run parcel serve index.html -p 4567 --no-cache`).

**The js in `foo.js` will run, but neither of the other two script tags will**.  Instead, I get a pair of errors like:
```
(index):60 Uncaught Error: Cannot find module '2mVuO'
    at newRequire ((index):60)
    at newRequire ((index):44)
    at localRequire ((index):82)
    at Object.5Sjuw.react-refresh/runtime ((index):143)
    at newRequire ((index):70)
    at (index):119
    at (index):142
```

## 🎛 Configuration (.babelrc, package.json, cli command)

There's almost no configuration - I got this down to what seems like a minimal reproduction case here: https://github.com/kkuchta/parcel_repro

The package.json (the result of `yarn add parcel@next` and `yarn add react` as of 2020-11-20) is:

```
{
  "name": "parcel_test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "parcel": "^2.0.0-beta.1",
    "react": "^17.0.1"
  }
}
```

## 🤔 Expected Behavior

I'd expect code in those script tags to run (and so see the console.log output in my js console).

## 😯 Current Behavior

I do not see those console.log statements in my js console.

<img width="438" alt="Screen Shot 2020-11-20 at 4 10 07 PM" src="https://user-images.githubusercontent.com/820965/99861445-e6854500-2b4a-11eb-994f-db700aaaf453.png">

## 🔦 Context

For context, in case it's helpful: my actual use case here is pasting in a js snippet for exception monitoring from rollbar.com.  I want it in a <script> tag before any of my other frontend code, so I tried to put it in a separate script tag to no avail.

## 💻 Code Sample

https://github.com/kkuchta/parcel_repro

## 🌍 Your Environment

Parcel@next (^2.0.0-beta.1)
Node 12.18.4
Yarn 1.22.4
Mac OS 10.15.7

**Comment by mischnic** [comment] 2020-11-21 11:24
Duplicate of https://github.com/parcel-bundler/parcel/issues/4858

**Closed by mischnic** 2020-11-21 11:24 UTC
