### ISSUE TITLE
Error while rendering map with mapbox-gl:  "_typeof is not defined"

### ISSUE THREAD

**Issue by dolbyzerr** [parcel-bundler/parcel#1128] opened 2018-04-03 05:27 UTC
This a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "dependencies": {
    "mapbox-gl": "^0.44.1",
    "parcel-bundler": "^1.7.0"
  }
}
```

```bash
npx parcel index.html
```

### 🤔 Expected Behavior

A map should be rendered.

### 😯 Current Behavior

Grey area is rendered:
<img width="401" alt="screenshot 2018-04-03 12 11 57" src="https://user-images.githubusercontent.com/664335/38230471-3fe3d27e-3738-11e8-919f-89e867513392.png">

The error in console:
`Uncaught ReferenceError: _typeof is not defined`

<img width="534" alt="screenshot 2018-04-03 12 20 10" src="https://user-images.githubusercontent.com/664335/38230723-813c9cfa-3739-11e8-854b-0b2af4cfb96e.png">

### 💁 Possible Solution

As far as I understood from the error and this issue from mapbox https://github.com/mapbox/mapbox-gl-js/issues/3422 it happens because parcel transpiling mapbox file that already being transpiled. Is there any way to alter that behaviour?

### 💻 Code Sample

```html
<html>
<head>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet' />
</head>
<body>
  <div id='map' style='width: 400px; height: 300px;'></div>
  <script src="./index.js"></script>
</body>
</html>
```

```js
import mapboxgl from 'mapbox-gl'

mapboxgl.accessToken = 'pk.eyJ1IjoiZG9sYnl6ZXJyIiwiYSI6InhIS25oN0EifQ.QQrwwFUZu6trJNjGsrpTFQ'
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9'
});

```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | v8.6.0
| npm         | 5.6.0
| Operating System | macOS 10.13.4

**Comment by dcposch** [comment] 2018-04-29 12:39
i'm running into the same problem.

my guess is that it's related to Web Workers. the `_typeof is not defined` errors all occur in Web Worker contexts, which are loaded from blob URIs. the blobs reference `_typeof` but do not define it.

btw @dolbyzerr you probably don't want to include your mapbox key :)

**Comment by safareli** [comment] 2018-05-03 20:25
you might wanna just "disable" babel see https://github.com/parcel-bundler/parcel/issues/509#issuecomment-355892214

**Comment by tobinbradley** [comment] 2018-07-04 23:14
Here's my "fun with Babel" contribution. 

Fiddling with my .babelrc I discovered limiting it to modern browsers worked. 

```javascript .babelrc
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 Firefox versions, last 2 Chrome versions, last 2 Edge versions, last 2 Safari versions"
      }
    }]
  ]
}
```

After a bunch of fiddling, it seems Babel's transformation for IE and Android Browser are causing the problem. If I use the browser string ["defaults, not ie <999, not Android < 999"](http://browserl.ist/?q=defaults%2C+not+ie+%3C999%2C+not+Android+%3C+999) to exclude those browsers, Bob's your uncle. Put *either* of those two browsers back in the pool, `_typeof is not defined` error.

But, if I run the Mapbox GL JS library through the Babel command line (Babel CLI 6.26.0, adds 2kb to the file) and then link to it directly in the example at the top, it works fine (note no `import` is going on here). 

```html
<script src="mapbox-babeled.js"></script>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiZG9sYnl6ZXJyIiwiYSI6InhIS25oN0EifQ.QQrwwFUZu6trJNjGsrpTFQ'
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9'
    });
  </script>
```

So, it looks like it's something with Babel combined with the import bundler, but only when Babel is correcting for those browsers. I guess.

**Comment by jkhedani** [comment] 2018-11-20 00:36
To expand upon @tobinbradley's temporary fix, here is another temporary alternative that works for me:

index.html:
```
...
    <div id="root"></div>
    <script src ="./index.tsx"></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
...
```

map.js (whatever your component file name is):
```
constructor(props) {
  super(props)
  this.mapboxgl = window.mapboxgl
}

componentDidMount() {
  window.addEventListener('load', this.setup());
}

// Sets map as a stored object that can be enhanced and ref
setup() {
  this.mapboxgl.accessToken = "your-access-token"
  const m = new this.mapboxgl.Map({
    container: "map", // #map
    style: "mapbox://styles/mapbox/streets-v9",
    center: [-74.50, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
  })
}

render() {
  return (
    <div id="map"></div>
  )
}
```

**Comment by jotasolano** [comment] 2019-03-10 18:19
I tried @tobinbradley's solution (changing the .babelrc browsers, not the second option) and it did not work for me. Maybe something has changed between there and now, but I get the same error as in the original bug. Any other ideas about how to deal with this?

**Comment by MoritzStefaner** [comment] 2019-03-22 12:27
I can confirm I have the same issue here using
```
"devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.12.3"
  },
  "dependencies": {
    "mapbox-gl": "^0.51.0",
    "react-mapbox-gl": "^4.2.0"
  }
```

Any suggestions, ideas, …?

**Comment by jotasolano** [comment] 2019-03-22 13:25
I ran out of ideas. I ended up using another bundler/boilerplate solution much to my chagrin. It looks to me like this won't be fixed until Parcel 2 arrives

**Comment by cyrilchapon** [comment] 2019-04-03 09:19
Confirmed same issue with `react-map-gl` and even raw `mapbox-gl`...

**Comment by AwesomeChap** [comment] 2019-05-30 08:32
> Here's my "fun with Babel" contribution.
> 
> Fiddling with my .babelrc I discovered limiting it to modern browsers worked.
> 
> ```js
> {
>   "presets": [
>     ["env", {
>       "targets": {
>         "browsers": "last 2 Firefox versions, last 2 Chrome versions, last 2 Edge versions, last 2 Safari versions"
>       }
>     }]
>   ]
> }
> ```
> 
> After a bunch of fiddling, it seems Babel's transformation for IE and Android Browser are causing the problem. If I use the browser string ["defaults, not ie <999, not Android < 999"](http://browserl.ist/?q=defaults%2C+not+ie+%3C999%2C+not+Android+%3C+999) to exclude those browsers, Bob's your uncle. Put _either_ of those two browsers back in the pool, `_typeof is not defined` error.
> 
> But, if I run the Mapbox GL JS library through the Babel command line (Babel CLI 6.26.0, adds 2kb to the file) and then link to it directly in the example at the top, it works fine (note no `import` is going on here).
> 
> ```
> <script src="mapbox-babeled.js"></script>
>   <script>
>     mapboxgl.accessToken = 'pk.eyJ1IjoiZG9sYnl6ZXJyIiwiYSI6InhIS25oN0EifQ.QQrwwFUZu6trJNjGsrpTFQ'
>     var map = new mapboxgl.Map({
>       container: 'map',
>       style: 'mapbox://styles/mapbox/streets-v9'
>     });
>   </script>
> ```
> 
> So, it looks like it's something with Babel combined with the import bundler, but only when Babel is correcting for those browsers. I guess.

May be you try excluding /mapbox-gl from transpiling. It worked for me. My final .babelrc looks like this
``{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": "last 2 Firefox versions, last 2 Chrome versions, last 2 Edge versions, last 2 Safari versions"
        },
        "exclude" : ["/mapbox-gl"]
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}``

**Comment by lrjbrual** [comment] 2019-06-18 06:41
I have the same issue, still can't find any good solution.

**Comment by vemundeldegard** [comment] 2019-11-16 11:16
I cannot find a fix for this. I have tried all of the above in .babelrc and nothing works.

**Comment by KatherineGraham2019** [comment] 2019-12-05 23:38
I have a similar issue with parcel and react mapbox-gl but I am not using babel. I am getting the exact same error and grey box instead of the map. Does anyone have a solution that doesn't require some babel configuration?

**Comment by cyrilchapon** [comment] 2019-12-06 06:30
Please for god sake. "Just don't transpile the module lol" is not an answer at all. Some are actually using it in production with facing customers.

Everything about Babel here is not about fixing the issue; but avoiding the issue, making somehow Babel avoid mapbox transpilation in some context.

We need an answer. Doesn't mapbox work in certain browser contexts because of webworkers ? Fine, please we figure it out and spell it, list it. Shouldn't we ?

**Comment by jotasolano** [comment] 2019-12-06 15:33
@cyrilchapon while I understand your frustration, this is not the right tone. This is open source software, you're not paying a dime for Parcel and the root issue has been identified and open. I'm sure the core devs would welcome your contribution (https://github.com/parcel-bundler/parcel/issues/670) but otherwise I think you should be more respectful of all the work they have done.

**Comment by cyrilchapon** [comment] 2019-12-11 06:49
@jotasolano was I revendicative on my previous answer ? Or disrespectful against contributors ? Or even acting like a "customer" ? I don't agree actually. I'm pretty aware this is open source software, and I did not even mention the fact this issue not being tackled.

I was complaining about bad issue triaging and commenting. "Just don't transpile" is not a clever answer, and that's all I'm saying.

Everyone coming to this issue will now know this issue is being tackled, thanks to the link you posted. Please notice no-one could guess that before your answer. In that sense, this issue moved on a little bit; and that's my way of contributing.

**Comment by niceone** [comment] 2019-12-20 16:12
> I cannot find a fix for this. I have tried all of the above in .babelrc and nothing works.

Excluding mapbox-gl in .babelrc did the trick for me as suggested above, but only after forcing Parcel to rebuild everything. Try --no-cache on parcel.

**Comment by jotasolano** [comment] 2019-12-20 17:29
> @jotasolano was I revendicative on my previous answer ? Or disrespectful against contributors ? Or even acting like a "customer" ? I don't agree actually. I'm pretty aware this is open source software, and I did not even mention the fact this issue not being tackled.
> 
> I was complaining about bad issue triaging and commenting. "Just don't transpile" is not a clever answer, and that's all I'm saying.
> 
> Everyone coming to this issue will now know this issue is being tackled, thanks to the link you posted. Please notice no-one could guess that before your answer. In that sense, this issue moved on a little bit; and that's my way of contributing.

@cyrilchapon If you scroll up you'll see that the issue I referenced was posted pretty early (comment #4) https://github.com/parcel-bundler/parcel/issues/1128#issuecomment-401892765 I just re-referenced for you.

**Comment by raxod502** [comment] 2020-02-15 18:52
Is there a workaround to this issue that doesn't involve dropping support for most browsers? The solution suggested https://github.com/parcel-bundler/parcel/issues/1128#issuecomment-497251288 works but not if I set the browser list to `defaults`.

Is Parcel ignoring the excludes list? If so, why?

**Comment by jordymeow** [comment] 2020-04-29 14:54
I am encountering the same issue but using Babel 7 (@babel/...). The solutions mentioned above, therefore, don't work for me. It seems the options for _env_ have changed. I spent a lot of time trying to find a solution and understanding the extremely obscure Babel documentation, but to be honest, I failed. And can't wait to be able to code again. Surely there is a better way than switching back to Webpack? :(

Would love to have your ideas. I can't be the only one using Babel 7, Parcel, and MapBox.

**Comment by agustinmulet** [comment] 2020-06-07 02:14
I got to fix this error using Babel 7, and `react-map-gl`
What I did was install Babel 7 with `yarn add -D @babel/core @babel/cli` and then add a `.babelrc` file with this:
```
{
    "presets": [
        ["@babel/env", {
        "targets": {
            "browsers": [
            ">2%",
            "last 1 Edge version",
            "last 2 Safari version",
            "last 1 Firefox version"
            ]
        },
        "loose": true
        }]
    ]
}
```

According to the [Babel docs](https://babeljs.io/docs/en/v7-migration#babel-preset-env), the `"loose": true` does the trick, excluding `typeof-symbol` which seems to be causing this issue.

**Comment by willbarkoff** [comment] 2020-11-07 02:00
Has anyone been able to solve this with TypeScript (no babel)?

**Comment by babak-bekhrad** [comment] 2020-11-07 18:38
I have the same issue. but for fixing this bug, I used the **Mapbox CDN** instead of module bundler and finally the map area is rendered without Grey area .

**Comment by markusand** [comment] 2020-12-13 11:09
> ```js
> {
>   "presets": [
>     ["env", {
>       "targets": {
>         "browsers": "last 2 Firefox versions, last 2 Chrome versions, last 2 Edge versions, last 2 Safari versions"
>       }
>     }]
>   ]
> }
> ```

Following @tobinbradley solution, I found that just creating a `.browserslist` and completely excluding IE works for me.
```
defaults
not IE > 0
```
I'm using new mapbox-gl 2.0.0

**Comment by devongovett** [comment] 2021-07-12 04:11
Appears to work correctly in Parcel 2 nightly.

**Closed by devongovett** 2021-07-12 04:11 UTC
Labels: :bug: Bug, ✨ Parcel 2
