### ISSUE TITLE
Constantly loosing HMR connection

### ISSUE THREAD

**Issue by ckissi** [parcel-bundler/parcel#6026] opened 2021-03-19 14:25 UTC
![image](https://user-images.githubusercontent.com/5107590/111794685-c7af7900-88c6-11eb-959a-d520f2548336.png)

If I close npm run dev command and rerun it the problem persists.
It's also browser-independent. Tried Chrome, FF, Safari with the same result. 

Parcel: 2.0.0-nightly.489
Node: 14.15.4
npm 6.14.4
OS: MacOS 11.2.3

**Comment by DeMoorJasper** [comment] 2021-03-19 15:16
is there any way you can provide a minimal reproduction case for this? Not sure what causes this without any additional steps to reproduce this.

**Comment by ckissi** [comment] 2021-03-30 08:53
Unfortunately, I have no idea. It works and then it stops working for some reason. Actually, nothing helps then. I mean if I restart the process it's the same. After I restart my iMac it works for a few minutes and then stops again.

**Comment by mdobroggg** [comment] 2021-04-14 21:24
I'm having the same thing happening to me on Ubuntu after upgrading to 2.0.0-beta.2 from v1.

**Comment by mdobroggg** [comment] 2021-04-15 15:45
#5660 seems to be related

**Comment by Bcdo** [comment] 2021-04-22 20:56
I get the same error. When I change something in index.html and save, nothing changes and the console shows console was cleared.

If I then save the index.js file, I get the connection to the HMR was lost, but the page does refresh with the html edits.

**Comment by mdobroggg** [comment] 2021-04-22 21:04
I was able to resolve the issue by switching to webpack

**Comment by Bcdo** [comment] 2021-04-23 15:04
> I was able to resolve the issue by switching to webpack

Yeah, I am not sure if I would consider that a solution. I do not need webpack for most of my projects, and Parcel is just to easy and quick to setup with tailwind, I would prefer to be able to use it properly.

**Comment by mdobroggg** [comment] 2021-04-23 16:37
I agree. I use tailwind as well and was really enjoying the simple setup of parcel, but switching to v2 was a nightmare. I had build issue pop up in CI/CD and dev server issue with HMR not working as well as other project specific issues. I spent longer trying to fix parcel and browse the issue threads with no support than it took me to fully convert my app to webpack. Its not a perfect solution, but when there is a lack of support on major issues I can't just wait around for them to be fixed with the project I'm working on. I'd be happy to revisit parcel when all of these issues are fixed as I thought it was pretty great otherwise.

If you want to consider webpack, let me know and I can share my config with you for tailwind.

**Comment by Bcdo** [comment] 2021-04-23 17:56
> If you want to consider webpack, let me know and I can share my config with you for tailwind.

Yeah, I will take you up on that! Tried a few variants, and to make one myself, but I just cant get it to work right.

**Comment by Bcdo** [comment] 2021-04-30 12:21
I ended up transferring the project to snowpack for now.

**Comment by mischnic** [comment] 2021-04-30 12:23
There's not much we can do without more details:

> is there any way you can provide a minimal reproduction case for this? Not sure what causes this without any additional steps to reproduce this.

**Closed as completed** 2021-09-01 10:13 UTC
Labels: :bug: Bug, :clock1: Waiting

**Comment by Offirmo** [comment] 2023-08-09 03:13
> is there any way you can provide a minimal reproduction case for this? Not sure what causes this without any additional steps to reproduce this.

I know this issue is closed, but could the devs also consider making the "HMR connexion lost" a bit more verbose so that we know what’s going wrong?

**Comment by sekedus** [comment] 2025-06-17 01:47
Try disconnect and exit/close your VPN.
