### ISSUE TITLE
Certain function is lost in production builds

### ISSUE THREAD

**Issue by ci7lus** [parcel-bundler/parcel#5553] opened 2020-12-31 06:18 UTC
# 🐛 bug report

In serve mode, I was able to use [chakra-ui](https://chakra-ui.com/docs/getting-started) with parcel working fine, but in production build, chakra-ui is broken.
This is because the required function has been transform to `{}` in the production build.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
  "name": "curly-tribble",
  "version": "1.0.0",
  "license": "MIT",
  "main": "dist/index.html",
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html --no-source-maps",
    "lint": "prettier --check './src/**/*.{js,ts,tsx}'",
    "format": "prettier --write './src/**/*.{js,ts,tsx}'"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "prettier": "^2.2.1",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@chakra-ui/react": "^1.1.0",
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
    "framer-motion": "^3.1.1",
    "parcel": "^2.0.0-nightly.496",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

## 🤔 Expected Behavior

Works the same way as serve mode.

## 😯 Current Behavior

```
TypeError: {} is not a function
    at Pb (use-style-config.js:29)
    at heading.js:9
    at Hs (react-dom.production.min.js:157)
    at hc (react-dom.production.min.js:176)
    at di (react-dom.production.min.js:271)
    at bd (react-dom.production.min.js:250)
    at md (react-dom.production.min.js:250)
    at hd (react-dom.production.min.js:250)
    at id (react-dom.production.min.js:243)
    at td (react-dom.production.min.js:237)
```
```js
  var mergedProps = mergeWith({
    theme,
    colorMode
  }, (_styleConfig$defaultP = styleConfig == null ? void 0 : styleConfig.defaultProps) != null ? _styleConfig$defaultP : {}, filterUndefined(omit(rest, ["children"])));
```
`--no-source-maps`
```
TypeError: {} is not a function
    at Pb (index.9496bcd0.js:1)
    at index.9496bcd0.js:1
    at Hs (index.9496bcd0.js:1)
    at hc (index.9496bcd0.js:1)
    at di (index.9496bcd0.js:1)
    at bd (index.9496bcd0.js:1)
    at md (index.9496bcd0.js:1)
    at hd (index.9496bcd0.js:1)
    at id (index.9496bcd0.js:1)
    at td (index.9496bcd0.js:1)
```
```js
          , d = {}({
            theme: l,
            colorMode: u
        }, null != (r = null == c ? void 0 : c.defaultProps) ? r : {}, em(Xh(i, ["children"]), (e=>null != e)))
```

The function `mergeWith` has disappeared, which is exported from lodash in the form of `default as`.
https://github.com/chakra-ui/chakra-ui/blob/085891be806b855af90b86367f5b26e8151c3ff5/packages/utils/src/object.ts#L3

## 💁 Possible Solution

~~Maybe it has something to do with https://github.com/parcel-bundler/parcel/issues/5459.~~
Build with `--no-scope-hoist`, I noticed this after I submitted the Issue...

## 🔦 Context

Want to use chakra-ui with parcel.

## 💻 Code Sample

https://github.com/vivid-lapin/curly-tribble

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.496 |
| Node             | v14.15.0 |
| npm/Yarn         | yarn 1.22.5 |
| Operating System | macOS 10.15.7 |

**Comment by mischnic** [comment] 2020-12-31 20:57
This has the same root cause as https://github.com/parcel-bundler/parcel/issues/5531

Minimal reproduction: https://github.com/mischnic/parcel-issue-5553

**Comment by tpck** [comment] 2021-01-26 15:14
@ci7lus 
Adding `--no-scope-hoist` fixes it for me as well, but the output file is 857 KB (even when using only a Button module from Chakra).
Are you experiencing the same issue?

**Comment by mischnic** [comment] 2021-01-26 15:26
Is this still broken with the latest nightly?

**Comment by tpck** [comment] 2021-01-26 16:47
> Is this still broken with the latest nightly?

Just tested it... it's fixed. 👍

**Comment by mischnic** [comment] 2021-01-26 16:51
Great, this was fixed with https://github.com/parcel-bundler/parcel/pull/4815

**Closed by mischnic** 2021-01-26 16:51 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2, 🌳 Tree Shaking
