### ISSUE TITLE
multi plugin for same file only execute one 

### ISSUE THREAD

**Issue by 466023746** [parcel-bundler/parcel#902] opened 2018-02-27 13:25 UTC
when multi plugin with same file, eg: parcel-plugin-vue & parcel-plugin-url-loader
both add packager for js, but only one is execute, is this the correct behavior?

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2

**Comment by DeMoorJasper** [comment] 2018-02-27 13:33
This is sort of not a bug, but just how the plugin architecture in parcel works.
Perhaps we should open up an RFC to discuss a more extendable architecture for plugins, but this would probably be a major breaking change and require every plugin to update.

**Comment by 466023746** [comment] 2018-02-28 01:59
now the url-loader not working, its a big problem i think

**Comment by davidnagli** [comment] 2018-03-01 01:29
@466023746 you brought up a really important point, so I went ahead and wrote up a little RFC proposal so we could investigate how/if we can implement a better plugin system that would solve this issue. This is a pretty big change, and likely won’t be implemented for a while even if we do decide to go ahead and do it.

I’m gonna close this issue for now, essentially moving it to #918. But feel free to comment if you have any other questions / comments.

**Closed by davidnagli** 2018-03-01 01:29 UTC
Labels: :grey_question:  Question
