### ISSUE TITLE
Dynamic imports not working on parcel v1 and v2

### ISSUE THREAD

**Issue by polRk** [parcel-bundler/parcel#4413] opened 2020-04-01 09:37 UTC
```js
  const html = await import(`../includes/${name}.${lang}.pug`)
```

```
Uncaught (in promise) Error: Cannot find module '../includes/confirm.ru.pug
```

**Comment by mischnic** [comment] 2020-04-01 09:38
Duplicate of https://github.com/parcel-bundler/parcel/issues/125

**Closed by mischnic** 2020-04-01 09:38 UTC

**Comment by polRk** [comment] 2020-04-01 09:39
@mischnic How can i solve the problem ?

**Comment by mischnic** [comment] 2020-04-01 09:42
As described in that issue, dynamic imports with an argument that is not a static string are currently not supported.
