### ISSUE TITLE
Unhandled promise rejection: TypeError: this.reject is not a function

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1050] opened 2018-03-23 08:20 UTC
On a bigger project got the folowing error then parcel is running.
Nothing special, just allot react components in a project. Used scss and css modules
```
Unhandled promise rejection: TypeError: this.reject is not a function
    at PromiseQueue._runJob (/mnt/SSD/Projects/***/node_modules/parcel-bundler/src/utils/PromiseQueue.js:50:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unhandled promise rejection: TypeError: this.reject is not a function
    at PromiseQueue._runJob (/mnt/SSD/Projects/***/node_modules/parcel-bundler/src/utils/PromiseQueue.js:50:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unhandled promise rejection: TypeError: this.reject is not a function
    at PromiseQueue._runJob (/mnt/SSD/Projects/***/node_modules/parcel-bundler/src/utils/PromiseQueue.js:50:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
parcel: 1.6.2

**Comment by FDiskas** [comment] 2018-03-23 08:31
Usual it happens then I install additional npm module to project while parcel is running :pray:

**Comment by FDiskas** [comment] 2018-03-23 16:02
Can you suggest me how todo so?

**Comment by mischnic** [comment] 2018-03-23 21:05
in your package.json:
```json
{
  "devDependencies": {
    "parcel-bundler": "parcel-bundler/parcel"
  }
}

```

Then reinstall your dependencies.

**Comment by gnijuohz** [comment] 2018-03-24 05:14
@FDiskas You can clone this project and build it yourself by running: `git clone git@github.com:parcel-bundler/parcel.git && cd parcel && yarn install && yarn build` and then you can use `yarn link` as described in the second option [here](git@github.com:parcel-bundler/parcel.git)

**Comment by FDiskas** [comment] 2018-03-24 13:53
Looks like it's fixed. 
Just keep in mind feels like project build time is 2x slower :stuck_out_tongue_closed_eyes:

**Comment by fathyb** [comment] 2018-03-24 17:05
@FDiskas it should be slower the first time because we are fetching dev dependencies, the next build (even without cache) should be sustainably faster.

@davidnagli any idea for the `uglify-es` error above?

**Comment by davidnagli** [comment] 2018-03-24 17:19
@fathyb No clue

@FDiskas Can you please provide an example repo so I can try to reproduce?

**Comment by FDiskas** [comment] 2018-03-24 17:27
Sorry repo is private and it's not easy reproducible. I will create another issue if it will popup next time. :smile:

**Comment by fathyb** [comment] 2018-04-02 00:34
Fixed in `1.7.0`, feel free to reopen if needed.

**Closed by fathyb** 2018-04-02 00:34 UTC
Labels: :bug: Bug
