### ISSUE TITLE
Convert `global` to window for browser targets.

### ISSUE THREAD

**Issue by gdborton** [parcel-bundler/parcel#1747] opened 2018-07-17 19:56 UTC
# 🐛 bug report
I'm working on prototyping our build in parcel to measure performance. One of the things that I noticed different between webpack and parcel through my work is that webpack will wrap calls to `global` in a function that exposes the `global` variable as `window`.  Parcel bundles just fail when run in the browser with `global is undefined`.

## 🤔 Expected Behavior
In a compiled bundle targeting the browser, `console.log(global);` should behave the same as `console.log(window);`

## 😯 Current Behavior
`console.log(global);` throws with `global is undefined`

## 💁 Possible Solution
One solution is to follow webpack's solution. For any file that includes a reference to `global` wrap the contents of the file with:

```js
(
  function (global) {
    // body of original module.
  }.call(this, require('parcels-global-shim')
)
```

**Comment by gdborton** [comment] 2018-07-17 20:01
Closing this for now as I couldn't repro in a smaller repository. It may be something specific to our build. I'll reopen if I find more on this.

**Comment by gdborton** [comment] 2018-07-18 00:25
Re-opened as I was able to track this down to using `type="module"` in my script tags. We don't actually need this, so we can work around, but figured I'd leave this open for tracking purposes.

**Comment by lazylazyllama** [comment] 2019-03-24 15:29
#2833 

I have the same problem with global by trying to build a website based on web components in which case ``ype="module` is necessary.

**Comment by mischnic** [comment] 2019-10-16 16:10
Ideally, something babel based could polyfill `globalThis`. But strangely enough `@babel/preset-env` doesn't do this.

**Comment by ljharb** [comment] 2020-08-26 05:03
Hi! If Parcel is trying to be a bundler for _node_ modules, why is it not correctly providing all browser-compatible node globals, in this case, `global`?

**Comment by mischnic** [comment] 2020-08-26 07:20
With Parcel 2, `console.log(global)` is turned into 
```js
var $parcel$global =
	typeof globalThis !== "undefined"
		? globalThis
		: typeof self !== "undefined"
		? self
		: typeof window !== "undefined"
		? window
		: typeof global !== "undefined"
		? global
		: {};
console.log($parcel$global);
```
for both Node and Browser targets (though it's not really necessary for Node...)

**Comment by ljharb** [comment] 2020-08-26 14:47
@mischnic it's necessary for packages that support node/browser versions that predate `globalThis`. Sounds like this issue may be fixed in Parcel 2, then?

**Comment by JakeChampion** [comment] 2020-08-26 14:47
It's not fixed in parcel 2 as that is what I was using when I came across this issue

**Comment by mischnic** [comment] 2020-08-26 14:49
Could someone please give a code sample that doesn't work as expected?

**Comment by JakeChampion** [comment] 2020-08-26 14:50
I'll make it now 👍

**Comment by JakeChampion** [comment] 2020-08-26 15:36
I came across the issue by using `@formatjs/intl-numberformat/polyfill` package which depends upon the `has-symbols` which is what was throwing the error due to `global` not being defined.

I can no longer recreate this issue in parcel 2 😅 Here is my code sample which does now work -- https://codesandbox.io/s/quirky-microservice-0gnm9

I'm pretty sure I hit this issue only 3 days ago but I never committed that work to my repo because it wasn't working, instead I raised an issue on [has-symbols[(https://github.com/inspect-js/has-symbols/pull/18).

I guess I could have been using parcel 1 by mistake 🤔 .

**Comment by mischnic** [comment] 2020-08-26 15:38
Is it possible that `yarn build` works but `yarn build --no-scope-hoist` (which is more similar to dev serve mode) doesn't?

**Comment by JakeChampion** [comment] 2020-08-26 15:40
> Is it possible that `parcel build` works but `parcel build --no-scope-hoist` (which is more similar to dev serve mode) doesn't?

I guess it is possible but I only used `parcel serve` when I hit the issue

**Comment by mischnic** [comment] 2020-08-26 17:01
I couldn't come up with a situation where it isn't replaced correctly with Parcel 2. If you do come across a case where it isn't, please open a new issue with a code sample.

**Comment by Porges** [comment] 2020-09-06 21:33
I’m seeing this not work with a dependency of `semantic-ui-react`. [Here’s a sample](https://codesandbox.io/s/winter-brook-nh2z2). It works okay in CodeSandbox but if you download it and `npm install; npm start` it should fail with:

```
Uncaught TypeError: Cannot read property 'Symbol' of undefined
```

There’s a related issue here (https://github.com/inspect-js/has-symbols/issues/4) but AFAICT parcel should be rewriting this?

**Comment by Porges** [comment] 2020-09-07 08:41
On the project I’m working on (and probably the previous example) `build` does work and `build --no-scope-hoist` does not work.

**Comment by Akash187** [comment] 2021-07-04 19:16
Hi @mischnic I am still facing the issue while trying to add Google Maps to my project. I am using the latest version of the parcel(v2.0.0-beta.3.1). I have created a repo to demonstrate the problem https://github.com/Akash187/typescript-project.

Basically, the Google Maps script runs a function name **initMap** as a callback which needs to be in global scope but unfortunately, it is not there and I am getting an error "initMap is not a function". But once I explicitly add the function **initMap** on the window object it works fine. I want it to work fine without explicitly adding a function to the window.

**Comment by Akash187** [comment] 2021-07-04 19:20
> @mischnic it's necessary for packages that support node/browser versions that predate `globalThis`. Sounds like this issue may be fixed in Parcel 2, then?



> Could someone please give a code sample that doesn't work as expected?

Hi @mischnic I am still facing the issue while trying to add Google Maps to my project. I am using the latest version of the parcel(v2.0.0-beta.3.1). I have created a repo to demonstrate the problem https://github.com/Akash187/typescript-project.

Basically, the Google Maps script runs a function name initMap as a callback which needs to be in global scope but unfortunately, it is not there and I am getting an error "initMap is not a function". But once I explicitly add the function initMap on the window object it works fine. I want it to work fine without explicitly adding a function to the window.

**Comment by bminer** [comment] 2021-07-26 19:40
The issue here is subtle. As far as I can tell, this is an issue with `dev-prelude.js`:

https://github.com/parcel-bundler/parcel/blob/20f2f14a806cc2fcba4d33979add2ac11dce78eb/packages/packagers/js/src/dev-prelude.js#L71-L77

Note that `this` is being used on line 76 as the 4th argument to the module.  Within modules using `global`, I have found that they are prefixed with the line `let global = arguments[3];`.  In other words, `this` (on line 76) becomes `global` within each module.

Generally, `this` defaults to `window` within the browser's context; however, in [strict mode, `this` will be `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#securing_javascript). `<script>` tags with `type="module"` [are in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules)!  I believe this is why users only experience this problem with `<script type="module" src="...">` tags. 

One possible solution is to use `globalObject` instead of `this` on line 76. `globalObject` is defined here:

https://github.com/parcel-bundler/parcel/blob/20f2f14a806cc2fcba4d33979add2ac11dce78eb/packages/packagers/js/src/dev-prelude.js#L10-L20

Thoughts?

**Comment by devongovett** [comment] 2021-07-26 19:54
In the nightly releases this shouldn't be the case anymore. `type="module"` gets removed now when not actually targeting ES modules.

**Comment by bminer** [comment] 2021-07-26 20:13
@devongovett What about when targeting ES modules?

**Comment by devongovett** [comment] 2021-07-26 20:37
When building for production, the dev-prelude is not used. Instead, `global` is replaced by `$parcel$global` which maps to: https://github.com/parcel-bundler/parcel/blob/b29f288670b4692c4bcb38f80eb857d7a5b90fa2/packages/packagers/js/src/helpers.js#L60-L69

**Comment by QiYuTechDev** [comment] 2021-07-28 02:41
parcel is boken(in browser env) with package: https://github.com/inspect-js/available-typed-arrays/pull/11

```
`global` is not defined
```

**Comment by bminer** [comment] 2021-08-19 14:58
As far as I can tell, this is now working in parcel@2.0.0-rc.0

Can others confirm?

**Comment by jeffpeck10x** [comment] 2021-08-20 01:22
This is not working for me in `parcel@2.0.0-rc.0`

When I `parcel serve`, it builds perfectly for the browser. When I `parcel build`, it produces code that has `global` in it and fails.

**Comment by mischnic** [comment] 2021-08-20 08:01
> When I parcel build, it produces code that has global in it and fails.

Can you share a code sample for that? Building a file just containing `console.log(global);` does perform this replacement for me: https://github.com/parcel-bundler/parcel/issues/1747#issuecomment-887010146

**Comment by jeffpeck10x** [comment] 2021-08-20 17:58
I don't think I can make a reasonable sample. I will note that my project is a monorepo that imports other packages from inside the project. One of those packages imports from deck.gl, which uses luma. The error that I was getting was from lumg.gl and when I inspected the line, it was looking for `global.luma`.

Also, I found that if I build with `--no-scope-hoist` it builds something that does not throw that error, except that the css imports appear to be broken.

Again, this is something that works perfectly with `parcel serve`. In fact, if I do `parcel serve` and then manually kill that process, I can then take the contents of `dist/` and serve those, and that works. (Although, I'm not sure how I could easily automate that.)

---

I wish that there was a way to make `parcel build` produce the exact same output in `dist` as `parcel serve`. While the outputted javascript is huge, it would help to establish a baseline of what works and what doesn't. @mischnic If you have a way to do that, it would definitely help, not only for my particular use-case, but for debugging issues like this in general.

**Comment by jeffpeck10x** [comment] 2021-08-20 18:07
If it helps, this is my package.json:
```
{
  "name": "..."
  "version": "0.0.0",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "start": "parcel serve src/index.html --open $BROWSER --no-cache",
    "build": "parcel build src/index.html --no-cache --no-scope-hoist"
  },
  "browserslist": "> 0.2%",
  "dependencies": {
...
  },
  "devDependencies": {
...
  }
}
```

Note, the `--no-scope-hoist`.

If I remove `private: true`, parcel complains:
```
@parcel/resolver-default: External dependency "@babel/runtime" is not declared in package.json.
```

I'm not sure if that is related?

**Comment by jeffpeck10x** [comment] 2021-08-20 18:22
Trying once more with `--no-optimize` and scope hoisting ON, I get:
```
init.js:31 Uncaught TypeError: Cannot read property 'luma' of undefined
```

The line referred to from the luma source on init.js:31 is:
```
if (global.luma && global.luma.VERSION !== VERSION) {
  throw new Error(`luma.gl - multiple VERSIONs detected: ${global.luma.VERSION} vs ${VERSION}`);
}
```

That line appears to correspond to:
```
if ($a8abb625118bbfa0$exports.global.luma && $a8abb625118bbfa0$exports.global.luma.VERSION !== $daf23e938e432229$var$VERSION) throw new Error("luma.gl - multiple VERSIONs detected: ".concat($a8abb625118bbfa0$exports.global.luma.VERSION, " vs ").concat($daf23e938e432229$var$VERSION));
```

in the javascript file created in the `dist` directory.

where:
```
$a8abb625118bbfa0$exports = (parcelRequire("dz9qQ"));
```

I see that `var $parcel$global = ...` in there.


_I am wondering if the problem is that `parcelRequire` is not attaching `.global` to the requires?_

**Comment by jeffpeck10x** [comment] 2021-08-20 18:30
Aha! yes, the `parcel serve` output produces this:
```
if (_env.global.luma && _env.global.luma.VERSION !== VERSION) throw new Error("luma.gl - multiple VERSIONs detected: ".concat(_env.global.luma.VERSION, " vs ").concat(VERSION));
```
as opposed to the line that I pasted above with `$a8abb625118bbfa0$exports.global.luma`.

I apologize for the multiple replies. I think this might have something to do with it though.

**Comment by jeffpeck10x** [comment] 2021-08-27 17:53
@mischnic I tried to recreate the issue by making a small generic repo that has a similar structure to my actual project:
https://github.com/jeffpeck10x/parcel-test

I was not able to recreate the exact same error, but I am running into a similar issue where the demo runs perfectly, yet the `parcel build` produces code that will not run.

```sh
git clone https://github.com/jeffpeck10x/parcel-test.git
cd parcel-test
yarn install

yarn dev
# go to http://localhost:5000/, everything works, yay!

yarn build
yarn serve-static-demo
# go to http://localhost:5000/, View console: "Uncaught ReferenceError: Log is not defined"
```

If you'd like, I can make a new issue and describe this there, although I think it falls under the same general issue. Here, it fails when it tries to do:
```
class $85d5d0e08a5e1191$export$9099ad97b570f7c {
  ...
}

Log.VERSION = $ekQcv.VERSION;
```

It should be doing:
```
$85d5d0e08a5e1191$export$9099ad97b570f7c.VERSION = ...
```

**Comment by mischnic** [comment] 2021-08-28 13:14
@jeffpeck10x See https://github.com/parcel-bundler/parcel/issues/6790

Regarding https://github.com/parcel-bundler/parcel/issues/1747#issuecomment-887965385: I've just tested Parcel 2 with and without scope-hoisting: `global` is replaced in both cases.

**Closed by mischnic** 2021-08-28 13:14 UTC
Labels: :bug: Bug, :raising_hand_woman: Feature
