### ISSUE TITLE
Cannot import multiple files using wildcard in parcel v2-beta1

### ISSUE THREAD

**Issue by marc2332** [parcel-bundler/parcel#4831] opened 2020-07-01 21:21 UTC
# 🐛 bug report

I cannot import multiple files from a folder using the wildcard:

Code:
```js
import Languages from '../../../languages/*.json'
```

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command: 

```shell
parcel serve src/index.html --dist-dir dist_parcel
```

.parcelrc:
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.{json,svg}": ["@parcel/transformer-inline-string", "..."]
	}
}
```

## 🤔 Expected Behavior

`Languages` should contain all JSON files content as objects.

**Note**: This was working perfectly fine on Parcel v1.12.4

## 😯 Current Behavior

The CLI throws me an error saying it cannot resolve:

![imagen](https://user-images.githubusercontent.com/38158676/86291864-f6c67300-bbef-11ea-9d3b-c03ca07880e5.png)

**IMPORTANT**: The path is correct.

## 💁 Possible Solution

I don't know

## 🔦 Context

I am just trying to import some languages stored in JSON files.

## 💻 Code Sample

This is simple as having a `index.js` in / (root of the project) and two .json under /stuff. 

index.js:

```js
import stuff from './stuff/*.json'

console.log(stuff)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 12.18.0
| npm/Yarn         | 6.14.4
| Operating System | Windows 10

**Comment by mischnic** [comment] 2020-07-01 21:34
Duplicate of #4683

**Closed by mischnic** 2020-07-01 21:34 UTC
