### ISSUE TITLE
[TypeScript] `baseUrl` inside tsconfig.json not supporting.

### ISSUE THREAD

**Issue by shunia** [parcel-bundler/parcel#202] opened 2017-12-11 10:00 UTC
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command) 
`tsconfig.json`:
```js
{
    "compilerOptions": {
        "outDir": "./dist/",
        "baseUrl": "./src",
        "sourceMap": true,
        "module": "commonjs",
        "target": "es5", 
        "removeComments": true
    }
}
```

### 🤔 Expected Behavior 
structure: 
```js
- project
   - src
      - component
         Custom.ts
      Main.ts
   index.html
   tsconfig.json
```
component/Custom.ts:
```typescript
export default function hello() {
    console.log('Hello!');
};
```
Main.ts:
```typescript
import hello from 'component/Custom';

hello();
```
console should show 'Hello!'

### 😯 Current Behavior 
Running from shell:
```shell
$ parcel index.html
/Users/shunia/Documents/parcel-test/src/Main.ts:3:23: Cannot resolve dependency 'components/Custom'
  1 | import hello from "components/Custom";
  2 |
> 3 | hello();
```

### 💁 Possible Solution 
  The compiler should read `tsconfig.json` file right, and understands that `baseUrl` has made the `from` part of `import ... from ...` no need to be the actual relative path from the current file.

  In my case, because of `baseUrl` set to `./src`, the original `import hello from '../componet/Custom' can be replaced as `import hello from 'component/Custom'`. 

  This might because of the way typescript compiles the `import` part just as what is written in the codes:
```typescript
import hello from "components/Custom";
```
is just compiled to:
```js
var Custom_1 = require("components/Custom");
```
  And then, parcel-require can not recognize the path and throws error.

### 🔦 Context
  Our actual project are full of relative paths based on `baseUrl`, which we omitted the `../` parts when using relative import. With `webpack` and `awesome-typescript-loader` it works as expected. So when we are trying to get our hands on parcel, this problem really blocks us from going further.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.1.0
| Node             |  v8.9.3
| npm/Yarn         |  Yarn 1.3.2
| Operating System |  macOS Sierra 10.12.6

Sorry for my poor english.

**Comment by emanuel-lundman** [comment] 2017-12-11 11:50
Also, related, paths in tsconfig does not seem be resolving correctly..
Did a quick test run with a current project: 
Result `index.tsx:15:24: Cannot resolve dependency '@client/store'` 
tsconfig paths example:
```javascript
"paths": {
    "@store/*": [
        "src/client/app/store/*"
    ],
    "@shared/*": [
        "src/client/shared/*"
    ],
    "@client/*": [
        "src/client/*"
    ],
    "*": [
        "*"
    ]
},
```

**Comment by fathyb** [comment] 2017-12-11 13:38
Can someone make a simple reproduction repo triggering the error?

**Comment by Ty3uK** [comment] 2017-12-12 05:43
Yep, here we go:
https://github.com/Ty3uK/parcel-tsconfig-issue

**Comment by kingdaro** [comment] 2017-12-12 06:25
Note that this shouldn't be considered a bug, but a feature or enhancement, since the baseUrl and paths options in the tsconfig are only meant to affect type checking. Actual path resolution is the job of the bundler/module loader.

With that said, as a possible solution, maybe we could make use of [this](https://github.com/tleunen/babel-plugin-module-resolver), by translating the options from the tsconfig into the babel plugin's config accordingly. Unless anyone else has a better idea, I could try making a solution out of that.

**Comment by Ty3uK** [comment] 2017-12-12 07:01
> since the baseUrl and paths options in the tsconfig are only meant to affect type checking

Not right. If you run `tsc` without any files, it reads `tsconfig.json` and builds project, resolving paths according to `baseUrl` and `paths` sections.

**Comment by Ty3uK** [comment] 2017-12-12 07:05
That's what I'm talking about. If you run `tsc` or `tsc -p tsconfig.json` modules are resolved.  

```bash
$ tsc src/Main.ts
src/Main.ts(1,19): error TS2307: Cannot find module '@components/Custom'.
src/Main.ts(2,21): error TS2307: Cannot find module 'components/NewCustom'.
$ tsc
$
```

**Comment by kingdaro** [comment] 2017-12-12 07:50
Huh, I must be mistaken then, since it's never outputted the resolved module paths for me in the past unless I configured it separately outside of the tsconfig. I'll look into it some more later.

**Comment by kingdaro** [comment] 2017-12-12 08:29
No, I tested to make sure, and I'm not mistaken. What I meant was that typescript itself will _not_ edit the import paths in the compiled output. All `baseUrl` and `paths` do is make your code pass the typecheck, and allows TS to find the modules and give them the appropriate typings. It does nothing in compilation. Sorry if I wasn't clear.

**Comment by shunia** [comment] 2017-12-12 08:46
@kingdaro Yes, the typescript compiler will not handle the path. That's why I mentioned `webpack` and `awesome-typescript-loader` in my post. So I think it is a problem that *parcel* could handle, to make everything right when compiling.

I tried to point this out in my post, but maybe not so clear:
**`parcel` should makes things right just as `webpack`+`awesome-typescript-loader` do, because I take `parcel` as a replacement of `webpack`+`awesome-typescript-loader`**.

**Comment by kingdaro** [comment] 2017-12-12 08:50
Yes, and I fully agree! Just wanted to mention that it'd be a feature instead of a bug as an aside, but I suppose that's somewhat pedantic, so ignore that part of my comment I suppose 😅

**Comment by fathyb** [comment] 2017-12-12 11:14
@shunia I just finished implementing it on [`parcel-plugin-typescript#ast/path-mappings`](https://github.com/fathyb/parcel-plugin-typescript/tree/ast/paths-mapping) using AST transforms (so it's totally transparent to Parcel). It's highly experimental but feel free to try. When stable I will try to merge it here in the core.

**Comment by shunia** [comment] 2017-12-12 11:40
@fathyb Sorry, but since I'm new to parcel, I may need a `how to` to get your code to test.

**Comment by fathyb** [comment] 2017-12-12 11:47
@shunia `yarn add parcel-plugin-typescript@0.2.0-astmap.0` or `npm install parcel-plugin-typescript@0.2.0-astmap.0` should be enough.

Just be sure you are using the latest git version of Parcel (eg. `yarn add https://github.com/parcel-bundler/parcel` or using `yarn link`)

**Comment by shunia** [comment] 2017-12-13 07:39
![image](https://user-images.githubusercontent.com/779430/33927078-b95f0214-e01b-11e7-9f98-2711cb44a3b2.png)
What's wrong here?

**Comment by shunia** [comment] 2017-12-13 07:44
![image](https://user-images.githubusercontent.com/779430/33927235-6f45584e-e01c-11e7-98f0-c7c18977360c.png)
install without `global` and run by `yarn run build`

**Comment by fathyb** [comment] 2017-12-13 09:04
@shunia you are using the test version I have built for Angular AOT compilation (I'm not good with npm tags, sorry). Can you use the 0.2.0 version? (`"parcel-plugin-typescript": "0.2.0"`, with no `^` or `~`, check the version with `npm ls parcel-plugin-typescript`).

Also let's keep this issue about Parcel support of this feature and not my plugin bugs, please continue [on the plugin issue tracker](https://github.com/fathyb/parcel-plugin-typescript/issues), or in [Slack](https://slack.parceljs.org/).

**Comment by atilkan** [comment] 2018-02-26 14:20
Is there  a solution currently?

**Comment by shunia** [comment] 2018-02-27 07:35
@atilkan Just install the right version of the plugin (mostly the latest) and it's done.

**Comment by dlee** [comment] 2018-03-11 01:39
Hi @fathyb, the example given by @Ty3uK still doesn't work with the latest `parcel-plugin-typescript`.

**Comment by fathyb** [comment] 2018-03-11 02:13
@dlee did you try to remove the `.cache` directory or launch `parcel` using `--no-cache`?

**Comment by dlee** [comment] 2018-03-12 16:49
@fathyb This worked. Thank you!

**Comment by joseluisq** [comment] 2018-11-12 22:01
Any progress?
Due to `baseUrl`, It is not possible to use custom `paths`.

__Parcel:__ v1.10.3

```sh
app.tsx:3:31: Failed to install @app/store
node_modules/parcel-bundler/src/utils/installPackage.js:46:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Reference: https://github.com/fathyb/parcel-plugin-typescript/issues/59

**Comment by jeffshaver** [comment] 2018-12-13 16:07
my team wants to use parcel, but this is preventing us from switching away from webpack.... We have a bunch of paths in our tsconfig and they can't be resolved:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@my-path%2factions: Not found".
```

**Comment by croaky** [comment] 2018-12-18 19:03
The combination that worked for us:
https://gist.github.com/croaky/e3394e78d419475efc79c1e418c243ed

**Comment by juliuskovac** [comment] 2019-11-18 15:29
Please is there any progress on this?

**Comment by uglycoyote** [comment] 2020-01-19 06:41
I opened a separate issue #4014 but later closed it because it was basically a duplicate of this one.   I thought I would mention here though that my newer issue included a link to a repro case that I created:

https://github.com/uglycoyote/parcel-import-problem

This might make it easier for Parcel developers to test that the `baseUrl` in `tsconfig` is respected once the fix is made.

**Comment by 7Pass** [comment] 2020-03-21 21:51
We can make use of Typescript's internal module resolve, especially now that Parcel 2 supports customization of resolve.

The following code successfully resolves the target component:
```
const path = require("path");
const ts = require("typescript");

const root = "/test";
const config = require(path.resolve(root, "tsconfig.json"));
const compilerOptions = config.compilerOptions;

if (compilerOptions.baseUrl) {
    compilerOptions.baseUrl = path.resolve(root, compilerOptions.baseUrl);
}

const host = ts.createCompilerHost(compilerOptions);
const cache = ts.createModuleResolutionCache(root, path => path, compilerOptions);
const resolved = ts.resolveModuleName("component/Custom", "Main", compilerOptions, host, cache);
console.log(JSON.stringify(resolved));
```

The output is:
```
{"resolvedModule":{"resolvedFileName":"/test/src/component/Custom.ts","extension":".ts","isExternalLibraryImport":false},"failedLookupLocations":[]}
```

I think TypeScript's built-in resolver would also handle `paths` mapping as well.

I'll be happy to take up implementing this as a resolver for parcel 2, but will need someone to help guiding me since I'm not familiar with parcel yet. I'm looking into moving my project from webpack to parcel 2 for performance and missing `paths` support is a huge obstacle that I hope can help to solve.

**Comment by chiefGui** [comment] 2020-05-01 05:20
Simple solution:

```shell
$ yarn add --dev babel-plugin-module-resolver
```

Then create (or modify) a `.babelrc` (for total newcomers: in your root folder, where your `package.json` is):

```json
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "~components": "./src/components",
          "~features": "./src/features"
        }
      }
    ]
  ]
}
```

**Comment by mbrowne** [comment] 2020-05-31 19:58
Note that in Parcel 2 (currently in alpha), `~` will point to the root of the project rather than wherever your `index.html` file is. So that means you'll have to change your imports to `~/src/...`. See https://github.com/parcel-bundler/parcel/issues/2813

**Comment by chiefGui** [comment] 2020-06-03 23:44
@mbrowne Hey, thanks for point that out. I'll edit my comment accordingly, but pretty much that was just a personal token choice. We can exchange `~` for something like @ with no problem.

**Comment by joseluisq** [comment] 2020-06-10 10:34
The "simple" setup by @chiefGui worked for me:

**parcel-bundler:** `^1.12.4`

**.babelrc**

```js
{
    "plugins": [
        [
            "module-resolver",
            {
                "root": [
                    "./src"
                ],
                "alias": {
                    "~": "./src",
                    "~/assets": "./src/assets",
                    "~/core": "./src/core",
                    "~/shared": "./src/shared"
                }
            }
        ]
    ]
}
```

**tsconfig.json**

```js
{
    // .......

    "compilerOptions": {
        // .......

        "baseUrl": "./",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "~/assets/*": [
                "src/assets/*"
            ],
            "~/core/*": [
                "src/core/*"
            ],
            "~/shared/*": [
                "src/shared/*"
            ]
        }
    }
}
```

A React/Typescript component example:

```tsx
import * as React from "react"
import * as ReactDOM from "react-dom"

import { WorldMap } from "~/core/worldmap"
import "~/assets/main.css"

export class App extends React.Component<{}, {}> {
    constructor (props: {}) {
        super(props)
    }

    render () {
        return (
            <div>
                <WorldMap />
            </div>
        )
    }
}

ReactDOM.render(<App />, document.getElementById("root"))
```

**Comment by mbrowne** [comment] 2020-06-10 11:58
@joseluisq It should work with just
"~/*", without the "~/assets/*", etc. (At least for tsconfig.json; I'm less sure about .babelrc.)

**Comment by alexeychikk** [comment] 2020-10-10 13:44
I am here because `--experimental-scope-hoisting` has a bug, which prevents me from using certain library. I was advised to switch to Parcel v2, but it broke paths resolution which is working in Parcel v1.
So I am stuck.

**Comment by alexeychikk** [comment] 2020-10-10 13:52
@chiefGui Doesn't your solution add an additional overhead of processing ts files with Babel? I guess by default ts files are only processed with TypeScript compiler.

**Comment by EsaNuurtamo** [comment] 2021-04-17 20:34
I just moved to monorepos with typescript and after spending countless hours with Parcel2 (also downgraded to 1) I just can't get moduel resolution working with all the guides there is. Only thing that works is using relative imports. Worked relatively fine before monorepo. In submodules I need tsconfig options alot. If someone has working example of monorepo with working path resolution I would like to see it. (Feel free to suggest better place for this comment)

**Tried fuse-box bundler now that has build in typescript support and based on small testing works like a charm with small monorepo I put up.**  Also the bundle times were much faster and no caching issues (with parcel I need to destroy my cache many times a day)

**Comment by zachbryant** [comment] 2021-04-27 22:41
I see a fair amount of quick solutions here, but I spent a lot of time on my tsconfig and just do not want to switch away. It kind of irked me that there wasn't a good path forward and seems like there won't be, so I created `parcel-resolver-tspaths` that reads your `tsconfig.json` for aliases. V2 users can find it on [npm](https://www.npmjs.com/package/parcel-resolver-tspaths). I'd love feedback or to hear if this helps anyone. In the meantime I'll finally continue to use my `@components/`, `@styles/`, etc ;)

**Comment by MylesWardell** [comment] 2022-01-21 01:46
Is their any way to have endpoints point to folders without the / in ~/. E.G ~types over ~/types. 

This is my current setup so `~/types` resolves to `./src/types`
what I want to achieve `~types` resolves to `./src/types`

babelrc
```json
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "~": "./src"
        }
      }
    ]
  ]
}

```

tsconfig
```json
{
  "compilerOptions": {
    ...
    "rootDir": ".",
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
    }
  }
}

```

```typescript
import { type } from '~/types'
```

I have tried removing the / (ie ` "~/*": ["src/*"]` -> ` "~*": ["src/*"]`) in the tsconfig and while that removed typescript errors the parcel did not compile throwing a similar error as this issues error. Any assistance? The reason this is relevant is I am trying to avoid ~60 thousand line changes on my Git Repo

**Comment by jacekkopecky** [comment] 2022-01-31 16:48
@zachbryant are you planning to release 1.0.0 of `parcel-resolver-tspaths` please? 8-)

**Closed** 2023-02-19 23:52 UTC
Labels: :raising_hand_woman: Feature, :pray: Help Wanted, TypeScript, ✨ Parcel 2, 🔌 Parcel 2 Plugins

**Comment by devongovett** [comment] 2023-02-20 03:07
`baseUrl` support is added in #8807, along with some other TypeScript resolver features - See https://github.com/parcel-bundler/parcel/issues/4936#issuecomment-1436248945

This is now released in nightly if anyone wants to try it and report back.

**Comment by maxhaton** [comment] 2024-04-03 14:54
> `baseUrl` support is added in #8807, along with some other TypeScript resolver features - See [#4936 (comment)](https://github.com/parcel-bundler/parcel/issues/4936#issuecomment-1436248945)
> 
> This is now released in nightly if anyone wants to try it and report back.

Should this work in parcel 2.12? I can't seem to get any absolute imports working using any baseUrl-isms so curious if its actually "turned on"?

**Comment by mischnic** [comment] 2024-04-03 15:16
> > `baseUrl` support is added in #8807, along with some other TypeScript resolver features - See [#4936 (comment)](https://github.com/parcel-bundler/parcel/issues/4936#issuecomment-1436248945)
> > This is now released in nightly if anyone wants to try it and report back.
> 
> Should this work in parcel 2.12? I can't seem to get any absolute imports working using any baseUrl-isms so curious if its actually "turned on"?

It should work automatically: https://parceljs.org/features/dependency-resolution/#tsconfig

Otherwise, please open a new issue with a reproduction and I can take a look

**Comment by maxhaton** [comment] 2024-04-03 15:54
> > > `baseUrl` support is added in #8807, along with some other TypeScript resolver features - See [#4936 (comment)](https://github.com/parcel-bundler/parcel/issues/4936#issuecomment-1436248945)
> > > This is now released in nightly if anyone wants to try it and report back.
> > 
> > 
> > Should this work in parcel 2.12? I can't seem to get any absolute imports working using any baseUrl-isms so curious if its actually "turned on"?
> 
> It should work automatically: https://parceljs.org/features/dependency-resolution/#tsconfig
> 
> Otherwise, please open a new issue with a reproduction and I can take a look

It doesn't seeeem to. I am just redacting an strace to post, you can clearly see it going through the right directory but it doesn't actually look for source files rather than directories.

**Comment by maxhaton** [comment] 2024-04-03 16:17
Here trying to resolve `import 'ui'"!
```
openat(AT_FDCWD, "/REDACTED/web/frontend/src/ui/package.json", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/REDACTED/web/frontend/src/ui/", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc3b67b280) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/REDACTED/web/frontend/src/startupreact.ts/node_modules/ui", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc3b67b580) = -1 ENOTDIR (Not a directory)
statx(AT_FDCWD, "/REDACTED/web/frontend/src/node_modules/ui", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc3b67b580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/REDACTED/web/frontend/node_modules/ui", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc3b67b580) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/REDACTED/web/node_modules/ui", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc3b67b580) = -1 ENOENT (No such file or directory)
```

**Comment by maxhaton** [comment] 2024-04-03 16:22
Is there something to copy in the testsuite?
