### ISSUE TITLE
Dynamic import doesn't work?

### ISSUE THREAD

**Issue by devcati** [parcel-bundler/parcel#112] opened 2017-12-08 03:41 UTC
when i try code splitting, get a error:
```
  Uncaught Error: Cannot find module '7'
```
index.js:
```js
import('./m').then(fn => {
    console.log(fn(1,2));
});
```
m.js:
```js
export default (a, b) => a + b;
```
no more config...

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.0.3
| Node             |  9.2.0
| npm/Yarn         | npm
| Operating System | macOS 10.12.6

**Comment by thejameskyle** [comment] 2017-12-08 04:22
Weird, could you put up an example repo?

**Comment by TheLarkInn** [comment] 2017-12-08 05:07
https://github.com/TheLarkInn/repro-parcel-112 Here's a repo to model after if needed, I wasn't able to repro myself but I'm on different OS so *shrug*. Anyways, maybe this will help expedite @devcati's reporting or help you James <3.

**Comment by ckken** [comment] 2017-12-08 05:59
```
export const loadComponent = function (defaultKey = false) {
  return function (location, cb) {
    let key = defaultKey
    if (!key) {
      key = `${location.params.module}/${location.params.controller}`
      if (location.params.action) {
        key = `${key}/${location.params.action}`
      }
    }
    import(`src/pages/${key}/index.js`).then(loadRoute(location, cb, key)).catch(errorLoading(cb))
  }
}
export default function createRoutes() {
  return {
    path: '/',
    // component: main,

    // onEnter:oauth,

    indexRoute: {
      getComponent: loadComponent('home')
    },
    childRoutes: [
      {
        path: ':module/:controller',
        getComponent: loadComponent()
      },
      // 独立子页面

      {
        path: ':module/:controller/:action',
        getComponent: loadComponent()
      },
      {path: '*', component: Notfound}
    ]
  }
}
```

like webpack require.ensure or import(val)

**Comment by ckken** [comment] 2017-12-08 07:03
like : `babel-plugin-syntax-dynamic-import`

**Comment by TheLarkInn** [comment] 2017-12-08 07:21
I'm not sure if Parcel has (haven't gotten through entire codebase yet) support for what webpack call's ContextModules. I'm happy to help team understand how it works if they want to RFC/Propose implementing it.

**Comment by evenfrost** [comment] 2017-12-08 07:48
That's weird, because on my one machine (running Ubuntu 16.10), I've got this very error `Cannot find module 'X'` when trying to use dynamic import or importing images. And on the other machine (Ubuntu 17.10) everything works seamlessly so far. Got Node.js v9.2 and Parcel v1.0.3 on both.

**Comment by devcati** [comment] 2017-12-08 09:25
thanks @TheLarkInn reply.  I found the problem in css. I use `postcss-inline-svg` in the css:
```
    h1 {
        background: svg-load('../pics/arrow_up.svg') no-repeat right;
    }
```
maybe `svg-load` disturbs bundle tree. remove css, all is ok.

**Comment by evenfrost** [comment] 2017-12-08 10:06
Minimal reproducible example is [here](https://github.com/evenfrost/parcel-demo). It starts happening when I include CSS file in index.html and have dynamic imports in my root JS file.

**Comment by wzrdtales** [comment] 2018-03-09 12:40
any news?

**Comment by ranfdev** [comment] 2018-03-21 17:18
I get the same error, but only when i'm building. When i run `parcel index.html` everything works, but if i run `parcel build index.html` i get that error message in some of the splitted chunks.
I'm using parcel 1.6.2 on elementary os (based on ubuntu)

**Comment by little-white** [comment] 2018-05-17 08:09
@ranfdev my parcel version is 1.8.1 on mac pro,it works as you say that remove the css file. 
```
// Demo.jsx
import React from 'react';

function Demo() {
  return <div className="name">Hello qiqi</div>;
}

export default Demo;
```

```
// Home.jsx
...
import Loadable from 'react-loadable';
const LoadableComponent = Loadable({
  loader: () => import('../Box/Demo'),
  loading: () => <div>Loading...</div>,
})
...
```
Interesting +1 👍

**Comment by dantesolis** [comment] 2018-05-20 09:53
Hey guys,  getting sort of the same problem, the built passes, but I get the following error on the web console:  `Uncaught Error: Cannot find module 'Loader.844c947a.js,7,Loader.844c947a.map,7'  at newRequire (loader.1eaab585.js:39)`

Using:
`"react-loadable": "5.4.0"`
`"babel-plugin-syntax-dynamic-import": "6.18.0",`
`"parcel-bundler": "^1.8.1"`
`"babel-plugin-syntax-dynamic-import": "6.18.0",`

Maybe I should name my imports  with `react-loadable` somehow? or  change my `babel-plugin`

*Code*

```js
// Loader.js

import React from 'react';

const Loader = () => {
  return (
    <div>LOADER LOADER</div>
  )
};

export default Loader;
```

```js
// App.js

import React from 'react';
import Loadable from 'react-loadable';
import Loader from './components/Loader/Loader';

const LoadableComponent = Loadable({
  loader: () => import('./components/Loader/Loader'),
  loading: () => <div>Loading...</div>,
  delay: 300,
});

const App = () => {
  return (
    <div>
      <p>This is the App view</p>
      <LoadableComponent />
    </div>
  )
}

export default App;
```

**Comment by ranfdev** [comment] 2018-05-21 16:32
The problem is even worse in the latest version (1.8.1). I can build my app using 1.7.1, but with 1.8.1 i get the error `Cannot find module '16'`. This time i don't have any css file. I don't know how to reproduce this, i'm not doing anything strange, it's just a normal app using code splitting

**Comment by shunia** [comment] 2018-05-22 02:39
@ranfdev Same here. So we go back to 1.7.1.
Though it's hard to choose, but we are switching to webpack for code splitting. :(

**Comment by danielbrodin** [comment] 2018-05-23 11:58
Have the same problem using 1.8.1 with react, TypeScript and react-loadable.
Currently we have changed typescript to use commonjs modules which disables code-splitting :(

Really wanted to use parceljs, but if it doesn't get fixed soon we will have to go back to using webpack as well again.

**Comment by tors** [comment] 2018-05-29 13:03
Can confirm the bug. Getting `Cannot find module '...'`

**Comment by machycek** [comment] 2018-05-31 13:05
Same issue with `Cannot find module '...'`. I'm not able to use codesplitting. Guess I'll need to move to webpack for time being :/

**Comment by dobesv** [comment] 2018-06-01 05:39
I seem to be having the same problem here, it happens with `1.8.1`.  But if I try to create a new small project to reproduce it, dynamic imports seem to work OK.

**Comment by raja** [comment] 2018-06-18 14:41
Any resolution as of yet? 1.9.1 still has issues with dynamic imports (for react-loadable)

**Comment by Vandell63** [comment] 2018-06-21 13:07
+ 1

**Comment by ravilution** [comment] 2018-07-14 00:10
I just tried below code. Works without any issue.

```javascript
import('@material-ui/core/styles/createMuiTheme').then(
  ({ default: createMuiTheme }) => {
    console.log(createMuiTheme)
  },
)
```

**Comment by stevefan1999** [comment] 2018-07-17 13:42
🤔It seems like Parcel just `require` the imported file and don't give a damn afterward, that means module resolution will not be applied after all.

Using @ravilution code, try this:
```js
function resolve (maybeMod: Promise<any>): Promise<any> {
  return maybeMod.then(mod => mod['default'] || mod)
}
...
(async function () {
  const App = await resolve(import('./components/App'))
  ...
})()

```
Still it doesn't work with `loadable-component` (or `react-loadable` presumably).

**Comment by ThaddeusJiang** [comment] 2018-08-15 01:10
I have a same problem.

![test](https://user-images.githubusercontent.com/17308201/44126467-702b90ee-a073-11e8-852e-731db4c9810c.png)

**Comment by devongovett** [comment] 2018-11-04 23:13
Bug (at least in @dantesolis case) appears to be related to the async imported module also being included in the bundle synchronously. There is both `import Loader from './components/Loader/Loader';` and `import('./components/Loader/Loader')` in the example. Does this match up with other people's issues?

**Comment by amok** [comment] 2018-11-20 15:00
@devongovett yes, confirmed in my case

but also I'm not able to import an svg file
it says something like 

```
// index.js
import('./icon.svg').then(v => console.log(v))

==>

Uncaught (in promise) Error: Cannot find module 'icon.svg'
```

**Comment by mischnic** [comment] 2019-01-12 18:51
The first three example repos I've tried don't work because they didn't respect the default export syntax:
```js
export default function() { return "test"; }

// ---

import("./module.js").then(res => {
	console.log(
		res() // res is not a function, it's {default: function(){return "test";} }
	);
});

**Comment by JosiahWitt** [comment] 2019-02-22 01:53
Here is a basic reproduction of the bug with React: https://github.com/JosiahWitt/parcel-dynamic-import-bug
It breaks if the app is reloaded on Page 2.

The interesting thing is if the image is removed from both pages (and the corresponding imports are removed), then the dynamic import works fine.

I was hoping to add an image to two pages in a larger app I'm building, but I guess I'll only add it to one page for now, since I've spend the better part of a day trying to get this to work. It doesn't even work to have a copy of the image for each page. 

Other than this, I am really liking Parcel! Good work! :+1:

**Comment by QuackMartins** [comment] 2019-03-12 00:30
I was having the same problem...
By adding the babel plugin `dynamic-import-node` it worked!

My .babelrc
```
{
  "presets": [
    ["react-app", { "absoluteRuntime": false }]
  ],
  "plugins": [
    "dynamic-import-node",
    "@babel/plugin-proposal-class-properties"
  ]
}
```

**Comment by QuackMartins** [comment] 2019-03-12 03:55
My build doesn't work with dynamic import and `--experimental-scope-hoisting` option... it shows this error

![image](https://user-images.githubusercontent.com/8419829/54172577-562dcc00-445d-11e9-85c1-531ca2ec0d90.png)

I started digging around and added some logs on `parcel-bundler/src/builtins/bundle-loader.js`, I found it's being inited twice after bundled with my application... in the first run it's setup correctly, but the second run is messing things up

![image](https://user-images.githubusercontent.com/8419829/54173194-ae65cd80-445f-11e9-939e-7b7ef3c79517.png)

A simple workaround I did was to ensure the var `bundleLoaders` on `parcel-bundler/src/builtins/bundle-loader.js` would not get reset... By doing

```js
var bundleLoaders = bundleLoaders || {};
```

My app started working again

![image](https://user-images.githubusercontent.com/8419829/54173414-9478ba80-4460-11e9-996a-a8a437b05856.png)
![image](https://user-images.githubusercontent.com/8419829/54173434-b6723d00-4460-11e9-8da2-c26ee03cb52b.png)

The problem is that my approach is not a fix :disappointed:, despite I think this workaround can help some people in the wild

**Comment by QuackMartins** [comment] 2019-03-12 13:28
@devongovett I think I'll dig a bit more today at night, do you have any suggestion where I should look in the tree shake process?

**Comment by zfrisch** [comment] 2019-04-04 15:54
> My build doesn't work with dynamic import and `--experimental-scope-hoisting` option... it shows this error
> 
> ![image](https://user-images.githubusercontent.com/8419829/54172577-562dcc00-445d-11e9-85c1-531ca2ec0d90.png)
> 
> I started digging around and added some logs on `parcel-bundler/src/builtins/bundle-loader.js`, I found it's being inited twice after bundled with my application... in the first run it's setup correctly, but the second run is messing things up
> 
> ![image](https://user-images.githubusercontent.com/8419829/54173194-ae65cd80-445f-11e9-939e-7b7ef3c79517.png)
> 
> A simple workaround I did was to ensure the var `bundleLoaders` on `parcel-bundler/src/builtins/bundle-loader.js` would not get reset... By doing
> 
> ```js
> var bundleLoaders = bundleLoaders || {};
> ```
> 
> My app started working again
> 
> ![image](https://user-images.githubusercontent.com/8419829/54173414-9478ba80-4460-11e9-996a-a8a437b05856.png)
> ![image](https://user-images.githubusercontent.com/8419829/54173434-b6723d00-4460-11e9-8da2-c26ee03cb52b.png)
> 
> The problem is that my approach is not a fix , despite I think this workaround can help some people in the wild

I'm having this exact same problem.  Where did you put your "fix" ?  

I'm not familiar with the code base as I just discovered parcel while trying to find an alternative to vueify that wasn't webpack, but I'm really concerned by this issue. I really just wanted a plug-and-play vue transpiler, but parcel replaced 90% of my build script(which is great), but now that I finished demoing a base example and am trying to hook it into my large application, the relative paths that `require` uses are giving it trouble.

 I am a bit miffed that dynamic module loading is still an issue from so far back. It's confusing. Even if you had to point out your initial entry point with an absolute path - unfortunate, but okay just use `__dirname` or something - if you have an entry point and your loading assets file-to-file, a relative directory to an absolute path shouldn't be so hard for it to manage, right? I know Node has its inconsistencies but this seems like a really debilitating thing with an otherwise great Builder.

**Comment by zfrisch** [comment] 2019-04-04 16:12
It seems like if I keep it to one folder away from root it'll compile without an issue? Very strange.

**Comment by ArtemZag** [comment] 2019-04-24 14:07
I've also faced this bug.
Looks like it happens when you try to import the same static file in 2 dynamically loaded modules.
The asset is added to dependencies only for the first module. So, if you skip loading of the first module and just load the second one then you get this error.
Here is my example:
https://github.com/ArtemZag/parcel-dynamic-import-bug
There are 2 scripts:
"yarn try-ok" & "yarn try-bug"

**Comment by hmmhmmhm** [comment] 2019-11-22 01:10
still no fiix about this error?
It's almost 2020 year and I'm going through this error again today.

**Comment by dobesv** [comment] 2019-11-22 01:25
@hmmhmmhm it would be more helpful if you included a reproduction step, detailed errors, etc.  Otherwise you might as well add an emoji to the issue description to vote for the issue.

**Comment by hmmhmmhm** [comment] 2019-11-22 01:27
Sorry. I forgot to share my experience. I approached it in the same way as the above reproductions.
I solved the problem in a temporary way as follows.

"This error occurs only with asynchronously imported static files, Create a central path management js file that has all of your static file paths.Never asynchronously import manager files that have all those path information, but manage to access them through those manager files when writing static files."

**Comment by hmmhmmhm** [comment] 2019-11-22 01:43
@dobesv 
Is it ok to request a pull request after modifying the code so that all path information of static resource collected by Parcel is left behind in the initial chunk?

**Comment by dobesv** [comment] 2019-11-22 01:51
@hmmhmmhm I don't know what's OK specifically, I'm not a project maintainer or anything.  If you do have a fix for the issue you can open a PR.  No guarantee they will accept it, of course, but it's worth a try.

**Comment by hmmhmmhm** [comment] 2019-11-22 01:57
OK I should try it, It's definitely worth it.
Thanks for answer to me..!

**Comment by jeremyong** [comment] 2019-12-07 14:37
Yikes I just found this issue after attempting to migrate a project to `parceljs`. I'll echo the concerns of others here, but I'd like to ask, is this something that is addressed in the upcoming parceljs 2?

**Comment by mischnic** [comment] 2019-12-07 14:42
If this describes your situation, then yes it's fixed in Parcel 2 already:

> Looks like it happens when you try to import the same file in 2 dynamically loaded modules.

**Comment by justin-hackin** [comment] 2020-01-05 14:38
For me, dynamic import works as expected when the parameter is an inlined string.  However, using a string variable in the import statement seems to prevent the loaders from working properly.  I get an error `Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`  Here's a reproduction of the issue: https://github.com/justin-hackin/react-minimal-starter-parcel .  In this case I used json, but I also experienced the same bug using the svgr plugin.    I even tried inlining a template string like `${file}.json` in hopes it would help the loader, didn't work.  I also upgraded to parcel@2.0.0-alpha.3.2, removed JSX because it broke the build, and  the bug was still present there.  Is there any way to force a particular loader to be used?

**Comment by mischnic** [comment] 2020-01-05 16:34
@justin-hackin 

Using a dynamic expression in an dynamic import makes Parcel ignore that call. The dev server is designed for SPA and therefore serves the index html file for unknown files, this is why you get that html error.

There are no "loaders" in Parcel. Using `import("bundle-text:./myfile.json")` with Parcel 2 should work in your case.

**Comment by devongovett** [comment] 2020-10-12 03:21
Going to close this as it's fixed in v2.

**Closed by devongovett** 2020-10-12 03:21 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2

**Comment by RashiqAzhan** [comment] 2022-03-02 12:22
I doubt this issue is completely fixed. Even on parcel v2 (using v2.3.2).

Here is my error message.
```js
TypeError: Cannot read properties of undefined (reading 'schema')
    at /server/dist/server.generated.js:4608:91
```
I have a peice of code doing something like this. Esentially, it's importing a model file that has a mongoose schema defined depending on the type of request.
```js
const importModel = async (modelName) => {
  try {
    let model;
    console.log(modelName);
    if (modelName) {
      model = await import(`../models/${modelName}.model`);
    } else {
      model = await import(`../models/user.model`);
    }
    return await model;
  } catch (err) {
    return err;
  }
};
```

But when I import all my models beforehand at the top of the file. It works just as expected.
```
import(`../models/user.model`);
import(`../models/post.model`);
import(`../models/comment.model`);
```

This leads me to believe dynamic imports are still not fixed 100%. Please correct me if I'm wrong.
The app also works fine when I use babel `nodemon --exec babel-node server.js;`
