### ISSUE TITLE
Electron: "require" is transpiled to "undefined"

### ISSUE THREAD

**Issue by elliottkember** [parcel-bundler/parcel#6323] opened 2021-05-21 00:41 UTC
# 🐛 bug report

I've been using Parcel 2.0.0.beta-2 in my Electron app and it's been great. Saw the announcement today and upgraded, but something seems to have changed: my `require` calls are being replaced with `undefined` in my Electron dev build.

I think it's being tree-shaken? Works fine in the browser. I haven't had time to investigate yet, but I'm flagging it in case it's something obvious that I need to change between beta 2 and 3. 

![image](https://user-images.githubusercontent.com/42827/119065934-81909780-b993-11eb-969d-490f3a2c2241.png)

<img width="605" alt="Screen Shot 2021-05-20 at 5 35 53 PM" src="https://user-images.githubusercontent.com/42827/119065392-46419900-b992-11eb-991d-752a5a86cd8e.png">

I'm still trying alternatives, just wanted to see whether there's something obvious I've missed. I've tried replacing `window.require` with `require`, basically everything obvious. The code as written originally works fine in the console: 

![image](https://user-images.githubusercontent.com/42827/119065971-90774a00-b993-11eb-8549-e202b74d8e11.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel: Just upgraded from 2.0.0.beta-2
.babelrc: Still present

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true
        }
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "@react-icons",
        "camel2DashComponentName": false,
        "transformToDefaultImport": false,
        "customName": "../../..//react-icons.js"
      },
      "@react-icons"
    ],
    [
      "babel-plugin-root-import",
      {
        "rootPathSuffix": "./src/main",
        "rootPathPrefix": "~/"
      }
    ],
    "@babel/plugin-proposal-optional-chaining",
    [
      "auto-import",
      {
        "declarations": [
          {
            "default": "React",
            "path": "react",
            "members": ["useState", "useEffect", "useContext", "useRef"]
          },
          {
            "default": "PropTypes",
            "path": "prop-types"
          },
          {
            "default": "classnames",
            "path": "classnames"
          }
        ]
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "react-hot-loader/babel",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

Should be able to import Electron modules from the front-end code!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0.beta-3
| Node             | 15
| npm/Yarn         | 
| Operating System | macOS

**Comment by mischnic** [comment] 2021-05-21 10:23
This was probably caused by https://github.com/parcel-bundler/parcel/pull/6260

Can you share the sourcecode that produces the code in the screenshot?

**Comment by elliottkember** [comment] 2021-05-21 12:54
> This was probably caused by https://github.com/parcel-bundler/parcel/pull/6260
> 
> 
> 
> Can you share the sourcecode that produces the code in the screenshot? 

There's two screenshots - the source and compiled code. Did one not show up for you?

**Comment by elliottkember** [comment] 2021-05-21 16:04
It's quite interesting - even `electron.remote.require` is compiled as `electron.remote.undefined`.

I'm happy to change my code here, or change configuration - but this does seem like an unintentional change. What is the intent behind replacing free requires with undefined? I'm not sure I get it.

![image](https://user-images.githubusercontent.com/42827/119166522-91e85700-ba13-11eb-9350-f75496dd039e.png)

**Comment by mischnic** [comment] 2021-05-21 16:26
There's a bug. The intention is that it is replaced with undefined in cases like `let x = typeof require !== "function" && require`.

The replacement should never happen if it's inside a member expression like `window.require`.

**Comment by elliottkember** [comment] 2021-05-21 16:28
@mischnic Got it, okay. Thank you. Let me know what you need from me to help test this. My app is [here](https://github.com/Soulmate-Lights/soulmate-ide/tree/elliott/parcel-b3) 

One thing I've noticed, and it may be related, is that the `nodeIntegration` functionality in Electron is also not working in this branch: The `fs` import is coming through as `{}` instead of the expected library. I'm sure it's tied in to `require` changes somehow. I'll keep investigating.

![image](https://user-images.githubusercontent.com/42827/119169452-e2ad7f00-ba16-11eb-98ec-ec2811543204.png)

**Comment by mischnic** [comment] 2021-05-21 16:34
That's not related (and shouldn't have changed recently).

In `"context": "browser"`, the builtin Node modules are polyfilled according to https://github.com/parcel-bundler/parcel/blob/v2/packages/utils/node-libs-browser/index.js

---

You should choose a different different name for the `browser` target. That one is meant for libraries (because of it's default behaviour)

**Comment by elliottkember** [comment] 2021-05-21 16:41
@mischnic I suspect I'm not doing something right when building for them, though in `master` / beta2 it works. 

I'm running `parcel -p 3000 index.html --target browser` to run in Electron. I bet this is somehow caused by overriding `window.require` when running in Electron, which will now be not happening because `require` is undefined.

I'm guessing somewhere there's something like `if (window.require) window.require = electronRequire` that now isn't happening because it's `if (undefined)...`

**Comment by elliottkember** [comment] 2021-05-21 16:45
If anybody else sees this thread and needs a workaround for this bug in the meantime, `window['req'+'uire']` sneaks past the transpiler and works fine.

**Comment by kdy1** [comment] 2021-05-24 09:30
I left a comment on #6260 which seems to cause this issue.

**Comment by mischnic** [comment] 2021-05-24 09:47
@kdy1 I think something like this would solve it (so that "require" in a member expression like `x.require` is never visited), but Rust complains 😄 

```rust
  fn fold_member_expr(&mut self, node: ast::MemberExpr) -> ast::MemberExpr {
    node.obj.fold_children_with(self);

    if node.computed {
      node.prop.fold_children_with(self);
    }

    node
  }
```

**Comment by kdy1** [comment] 2021-05-24 09:50
Rust will be happy with

```rust
 fn fold_member_expr(&mut self, mut node: ast::MemberExpr) -> ast::MemberExpr { // mut is added
    node.obj = node.obj.fold_children_with(self);

    if node.computed {
      node.prop = node.prop.fold_children_with(self);
    }

    node
  }
```

With `VisitMut`, you can modify fields without assigning again, but with `Fold`, you have to assign to the field manually.

**Comment by mischnic** [comment] 2021-05-24 09:58
Thanks, I didn't try to add `mut` 👍

**Closed as completed** 2021-05-24 17:43 UTC
Labels: :bug: Bug, ✨ Parcel 2, 🐡 JS Codegen

**Comment by elliottkember** [comment] 2021-07-13 00:23
@devongovett @mischnic I updated from beta.2 to 3.1 and it seems I have this problem again in `2.0.0-beta.3.1`: my `window.require` has become `window.undefined`. 

Can we please reopen this issue?

Source:

```
if (isElectron()) {
  ipcRenderer
    .invoke("get-password", window.require("os").userInfo().username)
```

Compiled:
```
if (_isElectron.default()) ipcRenderer.invoke("get-password", window.undefined("os").userInfo().username).then((key)=>{
```

Same is true for `electron.remote.require` -> `electron.remote.undefined`

```
const os = electron.remote.require("os");
```

```
var os = electron.remote.undefined("os");
```

**Comment by mischnic** [comment] 2021-07-13 09:00
This was fixed 4 days after beta.3.1 so you need to use a nightly version for now.
