### ISSUE TITLE
Is there a way to import json as a static file?

### ISSUE THREAD

**Issue by mcfarljw** [parcel-bundler/parcel#501] opened 2018-01-06 13:34 UTC
I'm using a few libraries that want to load json from a path. Is there a way to serve static files (similar to what the `copy-webpack-plugin` does)?

**Comment by DeMoorJasper** [comment] 2018-01-06 13:43
requiring or fs.readFileSync will both include the json file into the bundle

**Comment by mcfarljw** [comment] 2018-01-06 13:48
Hmm, @DeMoorJasper can you clarify a bit? I just tried using `require` for my json file but it still gives me an object rather than a static file path.

**Comment by DeMoorJasper** [comment] 2018-01-06 13:52
That's the point, it resolves the json file as an object

**Comment by mcfarljw** [comment] 2018-01-06 13:56
Sorry, I read that as use require.... import and fs.readFileSync will all include the json file into the bundle. The doesn't really help answer my question, but rather just confirms what I already know. Does that mean there is no way to import a json file as a static file rather than having it included in the bundle?

**Comment by DeMoorJasper** [comment] 2018-01-06 13:56
The only way i can think of resolving json as a raw asset is to overwrite the asset type by writing a plugin

**Comment by mcfarljw** [comment] 2018-01-06 14:04
Hmm, I wouldn't really want to overwrite an asset type. I guess what I'm looking for is a way to use parcel in development that works like the `static-serve` middleware for express.

**Comment by devongovett** [comment] 2018-01-06 15:42
Why do you need to copy the JSON file instead of bundling it into your code? Just trying to understand the usecase.

**Comment by mcfarljw** [comment] 2018-01-06 16:10
@devongovett I use a few 3rd party libraries that only support passing a path to load json files via xhr. The example I ran into today was with phaser 2 sprite atlases:

```js
game.load.atlas('items', 'assets/sprites/items.png', 'assets/sprites/items.json')
```

It's probably not too common, but I can recall using a few other libraries that have their own preload systems that treat json assets the same as images.

**Comment by sunnylqm** [comment] 2018-01-09 06:29
@devongovett For example, I want to lazy load some (or a lot) json data.

**Comment by shunia** [comment] 2018-01-10 02:27
@sunnylqm Fair point.
We run into this problem too as we have a bunch of assets(images,json files,etc.) to be loaded.

require & import does most the way we wanted, except with json files, it bundles json into javascript instead of return the path map. But what we wanted is the return the path way as other files do.

The reason is, we are building a loading sequence for all the assets other than javascript files, to show a loading bar to users, which will indicates the loading progress.

Webpack actually offers a extended require function `WebpackRequire` for us to make this happen, by mapping file path before bundle and after (`WebpackRequire.context`), we can dynamically replace path used inside javascript codes into hashed path, to make a successful load (by xhr) action.

**Comment by devongovett** [comment] 2018-01-16 08:10
See here for some potential strategies to allowing multiple import formats: https://github.com/facebookincubator/create-react-app/issues/3722

**Comment by FDiskas** [comment] 2018-03-25 10:30
you can try [parcel-plugin-json](https://www.npmjs.com/package/parcel-plugin-json) or [babel-plugin-inline-json-import](https://www.npmjs.com/package/babel-plugin-inline-json-import)

**Comment by RELNO** [comment] 2018-04-15 01:40
To extend @shunia & @mcfarljw point, THREE - `THREE.ObjectLoader()` API is XHR JSON loader which fails in parcel dev. server:
<img width="501" alt="screen shot 2018-04-14 at 21 34 02" src="https://user-images.githubusercontent.com/14296774/38774039-d31a2902-402b-11e8-8694-7b3daa823806.png">

**Comment by FDiskas** [comment] 2018-04-15 17:30
https://github.com/parcel-bundler/parcel/pull/536

**Comment by michaeljota** [comment] 2018-05-26 20:47
Just to say this is needed if you are using something like `pixi.js`. I understand not a huge user base, but is something. I guess I have to go back and use Webpack, and waste 4 hours of my life.

**Comment by shunia** [comment] 2018-05-28 03:12
@michaeljota Change file type from `.json` to something like `.data`, then let `pixi.js` to load them as `json` type. Problem solved.
But you may lose type check(json format validation) from your ide.

**Comment by michaeljota** [comment] 2018-05-28 04:55
I just try that and I does not work. 

- If I load an image by `require`ing it, and use the name that require function resolves, it does work. 

The problem now, is exactly about the json atlas files. But not quite because is a json file or not. 

1) `pixi` seems to validate the kind of file that you are trying to load, and I don't quite know how to tell `pixi` this is a json file with another name
2) The atlas file has a property that should resolve to the name of the atlas file. Because Parcel will always add a hash to whatever resource I need to load, the name in atlas will never match. (Again, if this is possible, please tell me how, because I really don't know how). 

Having a bundler tool with zero config is great, but I guess you need to consider what are the main use cases you want to cover, and at the end, I think is real hard to cover them all.

**Comment by shunia** [comment] 2018-05-28 07:02
@michaeljota It's not so straight forward to use neither `parcel` nor `webpack`, to work with `pixi.js`. Some extra work need to be done when using `parcel`, same as `webpack`.

If you want to get the real path after `parcel` builds your `.json` file(after changing your file type to `.data` for example), this would just works:
```
  let jsonURL = require('path/to/your/json/file');
```

If you want to load any file as json format file(of course they need to be parsed correctly by `JSON.parse`), just provide a proper loaderType/XHRType to `pixi.js`'s loader, something like:
```
  PIXI.loader.add({
    url: jsonURL, 
    loader: 'json loader type defined by pixi.js', 
    xhrType: 'json xhrType defined by pixi.js'
  });
```

If you want to patch json data to atlas resolver, you have to understand how `pixi.js`'s resource loader is working, and write some hack code to make it working, I can not provide example here.

**Comment by michaeljota** [comment] 2018-05-28 14:07
> If you want to get the real path after parcel builds your .json file(after changing your file type to .data for example), this would just works:
> ```
>  let jsonURL = require('path/to/your/json/file');
>```

I do it that way, and this is the way I use to load things that are not a `json` file. This is the main issue with this approach. The JSON file have a property that points to the path out the atlas image. As I understand there is not currently a way to tell parcel to move a file without renaming it, so there is no way for the JSON atlas describer to know where the atlas image will be after the build.

> If you want to load any file as json format file(of course they need to be parsed correctly by JSON.parse), just provide a proper loaderType/XHRType to pixi.js's loader, something like:

I don't know much about `pixi` but I did lookup for something like this, and the `loader`, and `xhrType` options seems to be related more to something like `xrh`, `audio`, `video`, and `image`. But I did not found something like `json`.

**Comment by JedHastwell** [comment] 2018-05-29 12:00
This is not strictly answering the question, but for those of you just looking to load a PIXI sprite sheet, you can bypass the PIXI loader and manually create the sprite sheet from the raw data:
```
  const data = require('../assets/atlas.json');
  PIXI.loader.add('atlas', require('../assets/atlas.png'), (resource) => {
    if(resource.error) {
      console.error(resource.error);
    } else {
      const texture = resource.texture.baseTexture;
      const sheet = new PIXI.Spritesheet(texture, data);
      sheet.parse((textures) => {});
    }
  });
```

**Comment by michaeljota** [comment] 2018-05-29 13:44
@JedHastwell This will create an `atlas` key in the `TextureCache` with the data from the atlas descriptor or something like that? I'm sorry, I just don't understand Pixi that well.

**Comment by JedHastwell** [comment] 2018-05-30 08:47
@michaeljota It's the same as if you'd just used the loader to load the atlas file directly from a JSON file. It will add all the textures defined in the atlas file to the TextureCache. Then you can just create sprites using the names defined in the atlas like:
`let ball = Sprite.fromImage('ball.png');`

**Comment by michaeljota** [comment] 2018-05-30 11:03
Oh! OK, OK... Will try that. Thanks you.

**Comment by skozin** [comment] 2018-06-05 14:57
To extend the point: I'm using some proprietary third-party library that expects me to pass URL to a static directory provided with the library. This directory contains about two hundreds of files, something that looks like this:

![image](https://user-images.githubusercontent.com/1699593/40983616-b717b874-68e8-11e8-91d9-2edcd5d5b926.png)

These files are JS/CSS/HTML files, as well as images, cursors and fonts. I cannot require every single file, and even if I could it won't help as the library expects to get each of these files using specific, compiled-in name. I can only change shared URL prefix.

As far as I can see, in order to make this setup under Parcel, I need two things:

1. When building production bundle: ability to copy a bunch of files and folders to the destination directory without any parsing and modification.
2. When developing: ability to serve static contents from a local directory under specific URL prefix.

Please let me know if this can be accomplished in some other way.

**Comment by shunia** [comment] 2018-06-06 03:17
@skozin Just try `const assets = require('relative/path/to/assets/folder/*')`. Notice the `*` in the url.
The object `assets` should have everything you need.

**Comment by michaeljota** [comment] 2018-06-06 11:16
As I understand, the problem is not loading those files, but letting those files load themselves.

**Comment by skozin** [comment] 2018-06-06 19:09
@shunia, the problem is not loading those files, as @michaeljota correctly said. I don't need them; the library I'm using needs them, and it wants to load them using XHR, and expects them to have pre-defined file names which are compiled into the library code. It does this to avoid loading unnecessary stuff: the total size of all these files is something like 20Mb, and most of them are not needed in every case. I suppose that `.js` bundles were actually generated using `webpack`'s code splitting mechanism and are being loaded using dynamic imports or `require.ensure`. Note that I have no access to the library sources, I can only use already bundled and minified code.

**Comment by shunia** [comment] 2018-06-08 07:26
Try [parcel-plugin-json-url-loader](https://github.com/shunia/parcel-plugin-json-url-loader)

**Comment by kpollich** [comment] 2018-06-27 20:41
+1 for the aforementioned three.js use cases here. Looking into migrating a WebGL project away from Webpack, but we need to be able to load object files and other WebGL assets via XHR.

**Comment by skozin** [comment] 2018-06-28 23:15
@shunia thanks! we'll try this :)

**Comment by mikedpad** [comment] 2018-07-31 00:25
Just started using Parcel recently (❤️it, btw) and ran into this issue recently myself. My use case was much simpler... I just wanted to include (copy) some static HTML files over to the `dist` folder.

I eventually just used an anchor in my `index.html` entry to include the file:
```
<body>
  <noscript>You must enable JavaScript to use this app.</noscript>
  <div id="root"></div>
  <a href="myStaticFile.html"></a>
  <script src="./index.js"></script>
</body>

</html>
```
... which is incredibly hacky. I don't want to link from the page, but this is how I got them to be included without bundling them.

Like @stevage mentioned, it'd be great if there was a simple `/static` subfolder where assets aren't processed or bundled.

**Comment by thejohnfreeman** [comment] 2018-09-04 05:57
My use case is I want a separate JSON configuration file that my administrator can tweak in the deployment. (I would love to use continuous integration, but I have to fit my solution into the problem's constraints.)

**Comment by kleinfreund** [comment] 2019-02-25 15:58
How do I get Parcel to resolve a path like this and add the JSON to the output?

```js
xhr. open('GET', '../data/some.json', true);
```

This flat out doesn’t do anything expected. For some reason, the result is not even a 404 error, but my HTML entry point file. This is extremely confusing.

**Comment by bsides** [comment] 2019-06-21 12:05
Just wanted to leave my use case here.

I'm developing a Chrome Extensions and it is required in the final build folder to have a `manifest.json` file there. Right now I'm just `cp manifest.json ./dist/` but I wish I could just put it as an entry file with an option to just copy it.

**Comment by connorjclark** [comment] 2019-07-14 02:59
A use case for bundling JSON as a string and deferring parsing to runtime: it can actually be [faster](https://twitter.com/mathias/status/1143551692732030979).

**Comment by Gaspacchio** [comment] 2019-08-23 12:03
For all of you who just need to copy a file from a static directory to the bundled one, I would recommend giving a shot at [parcel-plugin-static-files-copy](https://github.com/elwin013/parcel-plugin-static-files-copy#readme).
I don't know how it handles the paths though.

**Comment by bmmpt** [comment] 2019-10-26 02:21
Seems like everybody is adding their usage case here, so why not? :)

I am beginning to use the amazing react-i18next library and it's ability to asynchronously load new translations and add them to the application context. It supports plugins for xhr and fetch, but in both cases I get the HTML entry point file.

Both plugins try to fetch:
http://localhost:3005/locales/en-CA/translation.json

I don't even have to tell i18next where to get the files from as long as I put them in the default path it looks for translation files (public/locales/...). I also have no say on how it's getting the translations, neither I would want to. That's the beauty of the plugin. That being said, I can't even use the "weird workaround" with require mentioned above.

There will be dozens of use cases for stuff like this. Can Parcel be awesome at this too?

**Comment by mischnic** [comment] 2019-11-21 19:40
With Parcel 2 alpha 3 and this parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
you can import files which will then be copied to the dist folder:
```js
import file from "url:./static.json"
fetch(file)...
```

**Comment by deepred5** [comment] 2019-12-07 12:37
use `pixi.js` and load a ` json file ` . Thanks @jedhastwell 
```javascript
import { Application,  Sprite, Loader, Spritesheet } from 'pixi.js';

import myjosn from './assets/treasureHunter.json';
import mypng from './assets/treasureHunter.png';

const loader = Loader.shared;

const app = new Application({
  width: 300,
  height: 300,
  antialias: true,
  transparent: false,
  resolution: 1,
  backgroundColor: 0x1d9ce0
});

document.body.appendChild(app.view);

loader
.add('mypng', mypng)
.load(setup)

function setup() {
 
  const texture = loader.resources["mypng"].texture.baseTexture;
  const sheet = new Spritesheet(texture, myjosn);
  sheet.parse((textures) => {
    const treasure = new Sprite(textures["treasure.png"]);
    treasure.position.set(100, 100);
    app.stage.addChild(treasure);
  });
}

```

**Comment by danmarshall** [comment] 2020-01-28 22:16
> Try [parcel-plugin-json-url-loader](https://github.com/shunia/parcel-plugin-json-url-loader)

This worked for me, thanks @shunia ! 🥇

**Closed** 2020-01-29 07:14 UTC
Labels: :raising_hand_woman: Feature, static

**Comment by n8isjack** [comment] 2020-04-01 15:21
So I am using Parcel... love it and don't want to go back to webpack. 

I have been dealing with this and my use case is for Pixi.js with spritesheets. I can't get it to work without a static file name. (I have done d3 maps before and see how it would be the same problem)

I also have cases where I want the JSON loaded as an object, so I can't just over-ride JSON imports.

In the end I was able to get PIXI to work with a data url. 

I suppose if it was a huge file I'd have to learn about Parcel's [Code Splitting](https://parceljs.org/code_splitting.html) for lazy loading.

```javascript
import sprite_png from "../sprites/sprites.png";
import sprite_data from "../sprites/sprites.json";

sprite_data.meta.image = sprite_png;

let data64 = btoa(JSON.stringify(sprite_data));
let dataURL = `data:text/json;base64,${data64}`;

const theGame = new PIXI.Application({
  resizeTo: window
});

theGame.loader.add("sprites", dataURL);
```

**Comment by wyozi** [comment] 2020-04-09 14:42
For playcanvas users struggling with .json model imports, you can rename model .json files to .modeljson and add a custom loader:
```ts
(app.loader.getHandler("model") as pc.ModelHandler).addParser(
  new (pc as any).JsonModelParser(app.graphicsDevice),
  function (url, data) {
    return pc.path.getExtension(url) === ".modeljson";
  }
);
```

**Comment by opyate** [comment] 2020-10-22 22:05
Just leaving my workaround here for Phaser 3 + Parcel for the simple case where there's one spritesheet, in case it helps anyone.

```bash
ls -1 assets
other.png
spritesheet.json
spritesheet.png

```

```typescript

import Phaser from 'phaser'
// @ts-ignore
import images from '../assets/*.png'
import spritesheetJson from "../assets/spritesheet.json"

export default class BootScene extends Phaser.Scene {
  constructor () {
    super({ key: 'boot' })
  }

  preload () {

    console.table(images)

    this.load.image('other', images.other)

    spritesheetJson.textures[0].image = images.spritesheet.substring(1)
    this.load.multiatlas('spritesheet', spritesheetJson)
  }

  update () {
    this.scene.start('next-scene')
  }
}


```

**Comment by TimDaub** [comment] 2021-03-12 15:36
> With Parcel 2 alpha 3 and this parcelrc
> 
> ```json
> {
>   "extends": "@parcel/config-default",
>   "transforms": {
>     "url:*": ["@parcel/transformer-raw"]
>   }
> }
> ```
> 
> you can import files which will then be copied to the dist folder:
> 
> ```js
> import file from "url:./static.json"
> fetch(file)...
> ```

It seems `transforms` was renamed to `transformers`: https://v2.parceljs.org/configuration/plugin-configuration/

**Comment by TimDaub** [comment] 2021-03-16 16:26
A few days ago, I tried importing a `.json` file in the source code that I manage using parcel. My assumption is that anything that I use in an `import ... from ...` from statement gets bundled into my regular bundle.
I'm aware that *.json imports are not yet stable in the current ES specification. That's OK.

I then discovered this thread and saw that different from my expectation, many people want to lazy load *.json files to optimize for their user experience. Here's a few of those:

- https://github.com/parcel-bundler/parcel/issues/501#issuecomment-397953572
- https://github.com/parcel-bundler/parcel/issues/501#issuecomment-356192709

However, the problem is that I think the `import ... from ...` statement was never intended to lazy load anything. That's what `import(...)` is for. Hence, I find it to be a regression that we now can define import paths starting with `url:...` for `import ... from "url:..."` to code split and lazy load ([as I pointed that out in my last comment](https://github.com/parcel-bundler/parcel/issues/501#issuecomment-797567590)).

From parcel, what I'd expect when inputting `import ... from "*.json"` is that it bundles the `*.json` file in the main bundle once the ES standard on `*.json*  imports has matured.

To import JSON with `import ... from ...`, I recommend using [babel-plugin-inline-json-import](https://www.npmjs.com/package/babel-plugin-inline-json-import). You can find instructions on how to integrate on the npm page.

**Comment by jaredkrinke** [comment] 2024-01-14 22:28
> With Parcel 2 alpha 3 and this parcelrc
> 
> ```json
> {
>   "extends": "@parcel/config-default",
>   "transforms": {
>     "url:*": ["@parcel/transformer-raw"]
>   }
> }
> ```
> 
> you can import files which will then be copied to the dist folder:
> 
> ```js
> import file from "url:./static.json"
> fetch(file)...
> ```

Thanks for this! The only tweak I would suggest is to use `URL` since it's more obvious that it's producing a URL (or string). I was able to use this for lazy loading translations for react-intl:

```javascript
const urlToFetchForJson = new URL("url:../content/messages-compiled/zh-CN.json", import.meta.url);
```
