### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by tinchoz49** [parcel-bundler/parcel#1286] opened 2018-05-04 00:55 UTC
### 🎛 Configuration (.babelrc, package.json, cli command)

```
{
  "name": "parcel-worker-error",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html --no-cache"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-custom-asset": "file:parcel-plugin-custom-asset"
  },
  "dependencies": {}
}
```

### 🤔 Expected Behavior

Start the server app without errors.

### 😯 Current Behavior

Parcel compile without problems but when I enter on `localhost:1234` I'm seeing the error:

```
Uncaught ReferenceError: process is not defined
    at Object.parcelRequire.4 (parcel-worker-error.e898f6f3.js:133)
    at newRequire (parcel-worker-error.e898f6f3.js:48)
    at parcelRequire.2 (parcel-worker-error.e898f6f3.js:75)
    at parcel-worker-error.e898f6f3.js:101
```

### 💁 Possible Solution

Is not a solution but I think this kind of errors start with the new feature of custom workerfarm in 1.7.1 and maybe the solution is the PR #1235 

### 🔦 Context

So, this issue is happening when we use some plugin that is extending a custom asset from JSAsset. In the code sample, you can see a simple test.

### 💻 Code Sample

https://github.com/tinchoz49/parcel-worker-error

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10
| npm/Yarn         | npm 6
| Operating System | Manjaro xfce

**Comment by DeMoorJasper** [comment] 2018-05-04 07:28
Why are you extending JSAsset?
This is not really a recommended way of handling assets as it might break in updates (due to not being part of the public api).
I just wrote a recent write-up of how I wrote parcel-plugin-svelte which utilises the newest functions parcel offers to go around requiring JSAsset, might be intresting https://medium.com/@jasperdemoor/writing-a-parcel-plugin-3936271cbaaa

**Comment by tinchoz49** [comment] 2018-05-04 12:59
Hi @DeMoorJasper how are you?

Thanks for sharing the post, it's really good and something necessary to understand better how we can create plugins.

The thing is that I use JSAsset which extends from Asset to override the extension '.js' and to add more features or maybe we can call it other `transforms` on top of the already JSAsset. 

How can I apply the same idea of transforming a JS file (like browserify) without losing what JSAsset gives us?

**Comment by tinchoz49** [comment] 2018-05-04 13:46
For example with [surplus](https://github.com/adamhaile/surplus) you have to compile your jsx templates that are inside of JS files. There are already a loader for webpack, a transform for browserify and since I really like parcel I try to create a plugin for them: https://github.com/tinchoz49/parcel-plugin-surplus

**Comment by DeMoorJasper** [comment] 2018-05-04 14:47
Ow right, I haven't thought about that.
Yeah this will have to use extends JSAsset I guess.

But like i said I'm not able to reproduce it. Would be nice if you could debug it and pinpoint where this happens exactly, I don't really understand why process would ever be undefined though. (is this an in-browser error or one from the parcel cli?)

**Comment by tinchoz49** [comment] 2018-05-04 15:51
Yes, me too I don't understand why the process is undefined. At the begin, I thought it was the surplus compiler but then I test it to just extending from JSAsset without adding custom things and it didn't work.

I don't know if this can help but until the version 1.7.0 the surplus plugin worked.

btw: Thanks for taking the time to fork the plugin and debug it.

**Comment by alidcastano** [comment] 2018-07-01 18:37
@DeMoorJasper I was getting the same error. I was building Parcel for the browser in watch mode but using my own express server to serve app. Parcel leaves this line  `var hostname = process.env.HMR_HOSTNAME || location.hostname;` in the client bundle, I'm guessing because it handles the bundle itself in watch mode. If I build with match mode disabled, error dissapears.

**Comment by DeMoorJasper** [comment] 2018-07-01 19:33
Fixed by #1587 ?

**Comment by alidcastano** [comment] 2018-07-04 20:15
@DeMoorJasper I tried installing and using the branch but got this error `no such file or directory, open 'C:\Users\alidc\Code\rogue\node_modules\parcel-bundler\src\builtins\prelude2.min.js'`

**Comment by DeMoorJasper** [comment] 2018-07-04 20:58
@alidcastano run ‘yarn build’ after cloning

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-07-09 01:17 UTC
Labels: :bug: Bug, :pray: Help Wanted

**Comment by jtenner** [comment] 2018-07-10 15:10
Hey guys, I'm getting an error like this while using the `master` branch.

![image](https://user-images.githubusercontent.com/3761339/42519251-91888296-8431-11e8-8b62-4191f5ca90ad.png)

I have a worker called from a typescript file, and it's literally the first line of the generated file.

![image](https://user-images.githubusercontent.com/3761339/42519294-b87de4f4-8431-11e8-8a34-b540784eb2fb.png)

One of the things I note is that this code is generated for HMR, but I have `--no-hmr` activated.  On top of that, `process` isn't defined in the web worker because `--target=electron` is selected.

Any help for this fix, or should I create a different issue thread?

**Comment by DeMoorJasper** [comment] 2018-07-10 17:11
This has nothing to do with `Parcel` you're probably mis-using webworkers

**Comment by jtenner** [comment] 2018-07-10 17:56
That's really interesting to say. I don't mind if it's my fault, but this is the code I'm using to create a worker.

```ts
// inside /src/browser/index.ts
const worker = new Worker("../worker/index.ts");

worker.addEventListener("message",
  (e) => sm.handle(e.data as IWorkerEvent),
);
```
Is there some way I should be using it other than the way I'm using it?

**Comment by jtenner** [comment] 2018-07-10 18:06
I'll open up another issue.
