### ISSUE TITLE
About  multi-output situation for package

### ISSUE THREAD

**Issue by crsgyj** [parcel-bundler/parcel#3741] opened 2019-11-04 06:50 UTC
Hello, I am a serverless developer.
Today I want to package my aliclound FC project. I tried, not very successful, but almost work.
There are many independent functions in my project. 
the functions don't care about each other, but use same node_modules, and bundle node_modules.
multi-entries and multi-outputs in one project, so what i need is a clear layer in output-dir.

my config is:
![image](https://user-images.githubusercontent.com/49174703/68103053-4729eb80-ff10-11e9-8c12-e762d7a8de27.png)

finally I got what I want:
![image](https://user-images.githubusercontent.com/49174703/68103118-835d4c00-ff10-11e9-8a4d-ad4b1aa745aa.png)

but question is there no clear config to persist it.
and when I decrease my service directorys to one,  the performances are not consistent:
![image](https://user-images.githubusercontent.com/49174703/68103296-1c8c6280-ff11-11e9-87ae-c7ac5b6f9329.png)

I use parcel 1.x,  and tried parcel 2 and give up.
I ask for some solutions.

**Comment by mischnic** [comment] 2019-11-15 23:08
Duplicate of https://github.com/parcel-bundler/parcel/issues/2731

**Closed by mischnic** 2019-11-15 23:08 UTC
Labels: :grey_question:  Question
