### ISSUE TITLE
@parcel/transformer-raw casuses file not to be named as an entry.

### ISSUE THREAD

**Issue by kevincox** [parcel-bundler/parcel#4178] opened 2020-02-19 16:28 UTC
#4001 🐛 bug report

Applying `@parcel/transformer-raw` to a file causes it to be renamed as if it was an asset rather than an entry.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .parcelrc
{
	"extends": ["@parcel/config-default"],
	"transforms": {
		"*.json": ["@parcel/transformer-raw"],
	}
}
```

```js
// entry.json
{}
```

```
$ parcel build entry.json
✨ Built in 583ms

dist/entry.3de02f11.json    3 B    12ms
└── entry.json              3 B    33ms

```

## 🤔 Expected Behavior

Since `entry.json` was passed in as an entry it should not be renamed.

## 😯 Current Behavior

The asset gets renamed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v13.8.0
| npm         | 6.13.6
| Operating System | Linux

**Comment by mischnic** [comment] 2020-02-20 13:25
`bundle.isEntry` is false for the entry in this case...

**Comment by iax2RqPZbq** [comment] 2020-08-01 21:58
I've investigated this, and it's because the transformer (`RawTransformer.js`) sets `asset.isIsolated` to `true`; the default bundler (`DefaultBundler.js`) checks that and if it's true it sets `isEntry` to `false`.

It isn't obvious @mischnic but indirectly it is caused by the transformer.

**Comment by eyskim** [comment] 2020-10-16 14:24
Has this issue been solved? If not, would love to contribute!

**Comment by devongovett** [comment] 2021-07-09 08:56
Appears to be fixed in the latest nightly.

**Closed by devongovett** 2021-07-09 08:56 UTC
Labels: :baby: Good First Issue, :bug: Bug, :heavy_check_mark: Confirmed Bug, ✨ Parcel 2
