### ISSUE TITLE
`@parcel/transformer-svg-react` Unexpected token `}` for SVGs from node_modules

### ISSUE THREAD

**Issue by AndyOGo** [parcel-bundler/parcel#7706] opened 2022-02-14 11:07 UTC
# 🐛 bug report

I can't import an SVG as a React component using [`@parcel/transformer-svg-react` as described in the docs](https://parceljs.org/languages/svg/#importing-as-a-react-component).

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.{js,mjs,jsm,jsx,es6,cjs}": ["@parcel/transformer-js"],
    "*.svg": ["...", "@parcel/transformer-svg-react"]
  }
}
```

`npx parcel src/index.html`

## 🤔 Expected Behavior

No error, an SVG is displayed.

## 😯 Current Behavior

```sh
$ npx parcel src/browser/index.html
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-js: Unexpected token `}`. Expected this, import, async, function, [ for array
literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint,
string, regexp, ` for template literal, (, or an identifier

  /***/node_modules/***/public/svgs/i-check.svg:3:77
```

## 💁 Possible Solution

I tried offered solutions in comments of, without any luck

#7587
#6748
#5206

## 🔦 Context

I'm trying to build an app, which uses icons provided by a design system installed via npm.

## 💻 Code Sample

Sorry, source is closed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | v14.18.1
| npm/Yarn         | 6.14.15
| Operating System | Red Hat Enterprise Linux Server 7.9 (Maipo)

**Comment by mischnic** [comment] 2022-02-14 15:35
As you've said, duplicate of https://github.com/parcel-bundler/parcel/issues/6748

**Closed as completed by mischnic** 2022-02-14 15:35 UTC

**Comment by AndyOGo** [comment] 2022-02-14 19:13
@mischnic 
Its a different error though
