### ISSUE TITLE
🐛 Hot reload mechanism does not update changes in stylesheets

### ISSUE THREAD

**Issue by epsi10n** [parcel-bundler/parcel#284] opened 2017-12-15 12:21 UTC
bug report

**Problem overview**
Assuming I have minimal parcel project setup with simplest possible React App without styling at the first place, 
```
// index.js
import React from 'react';
import { render } from 'react-dom';
import App from './App';

render(
  <App />,
  document.getElementById('root')
);
```
```
// App.js
import React, {Component} from 'react';

export default class App extends Component {
    render() {
        return (<div className="main-div">
                <h1>Hello Parcel!</h1>
            </div>
        );
    }
};
```
```
// index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Showcase</title>
</head>
<body>
  <div id="root"></div>
  <script src="./index.js"></script>
</body>
</html>
```
Some time later I decided to add some styling
```
// App.js
import React, {Component} from 'react';
import './App.css';

export default class App extends Component {
    render() {
        return (<div className="main-div">
                <h1>Hello Parcel!</h1>
            </div>
        );
    }
};
```
```
// App.css
body {
    background: darkmagenta;
}
```

**expected behaviour**
ParcelJS must reload any styles changes

**actual behaviour**
Reload does not happens - I need to restart ParcelJS developmenty server process in order to see styles changes

**Comment by rkmax** [comment] 2017-12-15 17:47
I have the same issue, In order to update the changes I need to save the `.tsx` file  where the `.sass` file is required

**Comment by davidnagli** [comment] 2017-12-17 03:43
Thanks for reporting this 😀 

I'm currently trying to organize all of our open issues. Since this issue seems to be a duplicate of #57, I’m gonna go ahead and close this issue.

If you think I've done so in error, please don't hesitate to re-open the issue or send me a message on slack.

**Closed by davidnagli** 2017-12-17 03:43 UTC
Labels: #Bug

**Comment by rkmax** [comment] 2017-12-17 15:26
@davidnagli in my case I'm not requiring the css from the html, I'm doing from the js. I dont know if might be the same issue

**Comment by DeMoorJasper** [comment] 2017-12-17 15:31
If the HMR emits this update it should also be fixed with the same PR @rkmax , not sure if it is being emitted though, i might look into it later today

**Comment by jdoleary** [comment] 2018-04-26 01:11
Any progress on this?
