### ISSUE TITLE
Is there a way to preserve the resources urls?

### ISSUE THREAD

**Issue by Lcfvs** [parcel-bundler/parcel#2686] opened 2019-02-26 13:59 UTC
# ❔ Question

Is there a way to preserve the resources urls?

## 🔦 Context

I need to preserve the resource urls, like for fonts, images, etc., because I manage them with another tool.

How to ignore them, please? (just don't touch the urls and, if possible, to not copy them too)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 8.5.0
| npm/Yarn         | 6.7.0
| Operating System |

**Comment by mischnic** [comment] 2019-03-05 21:26
Closing as duplicate of #1186

**Closed by mischnic** 2019-03-05 21:26 UTC
Labels: :grey_question:  Question
