### ISSUE TITLE
Babel plugins errors from node_modules

### ISSUE THREAD

**Issue by digitaltopo** [parcel-bundler/parcel#515] opened 2018-01-08 21:25 UTC
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

[package.json](https://github.com/digitaltopo/parceljs-react/blob/master/package.json):
```
{
    "name": "parcel-react-simple",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "scripts": {
        "start": "parcel src/index.html"
    },
    "dependencies": {
        "material-ui": "^0.20.0",
        "react": "^16.2.0",
        "react-dom": "^16.2.0"
    },
    "devDependencies": {
        "babel-preset-env": "^1.6.1",
        "babel-preset-react": "^6.24.1"
    }
}
```

[.babelrc](https://github.com/digitaltopo/parceljs-react/blob/master/.babelrc):

```
{
    "presets": ["env", "react"]
}
```
also tried with:
```
{
    "presets": [
        [
            "env",
            {
                "targets": {
                    "browsers": ["last 2 versions"]
                }
            }
        ],
        "react"
    ]
}
```

[Command](https://github.com/digitaltopo/parceljs-react/blob/master/package.json#L7):

`yarn start` 
(`parcel src/index.html`)

### 🤔 Expected Behavior

Should be able to load the appropriate dependecies

I've setup a [simple react app](https://github.com/digitaltopo/parceljs-react/blob/master/src/index.js) to demonstrate this issue. I am trying to use a button component from the [material-ui](https://github.com/mui-org/material-ui) repository.

```
import React from "react";
import { render } from "react-dom";
import Button from "material-ui/Button";

function App() {
return (<Button>Hello World</Button>);
}

render(<App />, document.querySelector("#root"));
```

### 😯 Current Behavior

Parcel gives the following error in terminal when run: 

`🚨  /path/to/project/node_modules/jss-global/lib/index.js: Unknown plugin "transform-es3-member-expression-literals" specified in "/path/to/project/node_modules/jss-global/.babelrc" at 0, attempted to resolve relative to "/path/to/project/node_modules/jss-global"`

Full error output:
```
yarn start
yarn run v1.3.2
$ parcel src/index.html
```
🚨  /path/to/project/node_modules/jss-global/lib/index.js: Unknown plugin "transform-es3-member-expression-literals" specified in "/path/to/project/node_modules/jss-global/.babelrc" at 0, attempted to resolve relative to "/path/to/project/node_modules/jss-global"
    at /home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/user/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at /home/user/.config/yarn/global/node_modules/parcel-bundler/lib/assets/JSAsset.js:61:22
    at Generator.next (<anonymous>)
    at step (/home/user/.config/yarn/global/node_modules/parcel-bundler/lib/assets/JSAsset.js:3:191)
```
I have experienced this with both NPM and Yarn, and with various Node versions.

### 💁 Possible Solution

Don't transpile node_modules with babel?

### 🔦 Context

Using a component library inside a simple react app built with parcel. 

### 💻 Code Sample

Repository with a sample react project demonstrating issue: [parceljs-react](https://github.com/digitaltopo/parceljs-react)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 9.3.0
| npm/Yarn         | Yarn 1.3.2, Npm 5.5.1
| Operating System | Ubuntu 16.04

**Comment by et** [comment] 2018-01-12 03:58
I'm having the same issue. I was looking at what is a `JSAsset` according to the babel transform:

```js
false,
  contents: 'export * from \'base16\';\nexport { default as nicinabox } from \'./nicinabox\';\n',
  ast: null,
  generated: null,
  hash: null,
  parentDeps: Set {},
  dependencies: Map {},
  depAssets: Map {},
  parentBundle: null,
  bundles: Set {},
  globals: Map {},
  isAstDirty: false,
  isES6Module: false
}
```

Is there something we can query off of to detect that this is a dependency and you probably don't need to compile it?

**Comment by pbrengard** [comment] 2018-01-12 16:37
I fixed that by adding missing dependencies
```

 "dependencies": {
    "async": "^2.6.0",
    "babel-core": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "express": "^4.16.2",
    "material-ui": "^1.0.0-beta.27",
    "material-ui-icons": "^1.0.0-beta.17",
    "parcel-bundler": "^1.4.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "request": "^2.83.0",
    "typeface-roboto": "0.0.50"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es3-member-expression-literals": "^6.22.0",
    "babel-plugin-transform-es3-property-literals": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1"
  }
```

But then, when running the app, I get an error in the console:
`Error: Cannot find module 'babel-runtime/helpers/typeof'`

Is babel-runtime correctly packaged ? Or is it something else ?

**Comment by et** [comment] 2018-01-12 16:54
@pbrengard - one shouldn't have to add a babel dependency for a dev dependency.

**Comment by devongovett** [comment] 2018-01-12 17:25
duplicate of https://github.com/parcel-bundler/parcel/issues/13

**Closed by devongovett** 2018-01-12 17:25 UTC
