### ISSUE TITLE
Support web manifest v3 for web extensions in @parcel/config-webextension

### ISSUE THREAD

**Issue by burhanuday** [parcel-bundler/parcel#7175] opened 2021-10-24 13:04 UTC
# 🙋 feature request
Currently, `"manifest_version": 3,` in `manifest.json` results in error
```shell
🚨 Build failed.

@parcel/transformer-webextension: Invalid Web Extension manifest

  manifest.json:5:23
    4 |   "version": "0.1.2",
  > 5 |   "manifest_version": 3,
  >   |                       ^ Possible values: "2"
    6 |   "background": {
    7 |     "service_worker": "src/js/inject.js"

```

## 🤔 Expected Behavior

Build succesfully without errors

## 😯 Current Behavior
Results in above error

## 🔦 Context

```json
 "@parcel/config-webextension": "^2.0.0",
 "parcel": "^2.0.0"
```

**Comment by burhanuday** [comment] 2021-10-24 13:24
PR here - https://github.com/parcel-bundler/parcel/pull/7050
close issue when PR gets merged

**Comment by mischnic** [comment] 2021-10-24 15:28
Duplicate of https://github.com/parcel-bundler/parcel/issues/6079

**Closed as completed by mischnic** 2021-10-24 15:28 UTC
