### ISSUE TITLE
@parcel/transformer-less: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by PAquaticus** [parcel-bundler/parcel#7806] opened 2022-03-07 20:03 UTC
I use antd and parcel yields the error `@parcel/transformer-less: Inline JavaScript is not enabled. Is it set in your options?`. I read in issue 907 that this is because antd uses javascript in its `less` definition.
I use a .lessrc file:
```
{
    javascriptEnabled: true
}
```

The issue is that in other issues it has been proclaimed several times that this was fixed, but it does still occur in my project with parcel@2.3.2. The .lessrc files is not read and javascript is not enabled, therefore the error.

I found that when I edit `@parcel/transformer-less/lib/loadConfig.js:46` and add the line 
`configContents.javascriptEnabled = true` then it compiles perfectly. 

I use:
|  package | version  |
|---|---|
| @parcel  | 2.3.2  |
| @parcel-transformer | 2.3.2  |
|  antd |  4.16.3 |
| less | 4.1.2 |
| react | 17.0.2|

I already read and tried these two:
- https://github.com/parcel-bundler/parcel/issues/1195
- https://github.com/parcel-bundler/parcel/issues/907
I tried every solution proposed of issue 907. I also tried the plugin `parcel-plugin-less-js-enabled` which worked bzt only for parcel<2.0.0

**Comment by mischnic** [comment] 2022-03-07 21:11
Duplicate of https://github.com/parcel-bundler/parcel/issues/6623

**Closed as completed by mischnic** 2022-03-07 21:11 UTC

**Comment by passby6someone** [comment] 2022-08-08 07:53
I have the same problem.

I also fix it by editing ```@parcel/transformer-less/lib/loadConfig.js:46``` and adding the line ```configContents.javascriptEnabled = true```.

I use:
| package | version |
| ------ | ------ |
| parcel | 2.7.0 |
| @parcel/transformer-less | 2.7.0 |
| antd | 4.22.3 |
| react | 18.2.0 |

I have tried add ```.lessrc```:
```
{
  "javascriptEnabled": true
}
```
that's not work
