### ISSUE TITLE
Issues with peer dependencies found with the package svgo

### ISSUE THREAD

**Issue by navidemad** [parcel-bundler/parcel#8992] opened 2023-05-06 23:33 UTC
## 🔦 Context

```
 WARN  Issues with peer dependencies found
.
└─┬ @parcel/config-default 2.8.3
  └─┬ @parcel/optimizer-htmlnano 2.8.3
    └─┬ htmlnano 2.0.4
      └── ✕ unmet peer svgo@^3.0.2: found 2.8.0 in @parcel/optimizer-htmlnano
```

- htmlnano is using svgo 3
- @parcel/optimizer-htmlnano is still using svgo 2.8.0

There is some breaking changes in the version 3, so i can't just override to make @parcel use the version 3.
Also, the version 2.8.0 trigger a warning:

```
WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. 
See the compatibility table on MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
```

Thanks for the awesome work :)

**Comment by mischnic** [comment] 2023-05-07 08:37
Duplicate of https://github.com/parcel-bundler/parcel/issues/8948

**Closed as not planned by mischnic** 2023-05-07 08:37 UTC
