### ISSUE TITLE
Serve index.html as root

### ISSUE THREAD

**Issue by LandonSchropp** [parcel-bundler/parcel#2215] opened 2018-10-28 23:35 UTC
# 🙋 feature request

I'm not sure if this is a feature request or a bug, but Parcel doesn't seem to route to `index.html` without specifying a route from its development server.

## 🤔 Expected Behavior

Most JavaScript web servers these days will route to `index.html` when you access the root route. For example, if I load [http://localhost:7777](http://localhost:7777), I would expect Parcel to serve `index.html`. I would also expect it to serve subdirectories with `index.html` files, such as [http://localhost:7777/bananas](http://localhost:7777/bananas). Currently, parcel only routes to [http://localhost:7777/index.html](http://localhost:7777/index.html).

## 😯 Current Behavior

Parcel's server currently 404s when loading the root route.

## 💁 Possible Solution

One option is to use an existing server to host the development server, such as [Connect](https://github.com/senchalabs/connect#readme). Alternatively, the current server could be extended to support index.html routes.

## 🔦 Context

I was trying to build a standard static site and I was surprised this wasn't supported.

**Comment by LandonSchropp** [comment] 2018-10-28 23:41
After digging in a little bit, it looks like the `index` options of `serveStatic` is set to false. Would there be a downside to setting this to true?

https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Server.js#L37

**Comment by mrcoles** [comment] 2018-10-30 15:35
This only happens for me when running parcel on multiple entry points. I think this is a dupe of #1315 

It looks like it’s needing of a PR. ANother suggestion in [this comment](https://github.com/parcel-bundler/parcel/issues/1315#issuecomment-407140722).

**Comment by LandonSchropp** [comment] 2018-10-31 04:40
@mrcoles I've confirmed that you're right and this issue is a dup. I'll go ahead and close it. Thanks for the quick reply. 😃

**Closed** 2018-10-31 07:36 UTC
Labels: :raising_hand_woman: Feature
