### ISSUE TITLE
Parcel dev server randomly crashes when trying to unlink a file in the dist directory.

### ISSUE THREAD

**Issue by nneil** [parcel-bundler/parcel#9608] opened 2024-04-02 21:06 UTC
```
> parcel --open

[HPM] Proxy created: /api  -> http://localhost:8787/
Server running at http://localhost:1234
⠏ Packaging index.[hash].css...
node:fs:1874
  binding.unlink(path);
          ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\neil\Projects\cloudflare\dist\index.html.30336.1c'
    at Object.unlinkSync (node:fs:1874:11)
    at WriteStream.<anonymous> (C:\Users\neil\Projects\cloudflare\node_modules\@parcel\fs\lib\index.js:1024:83)
    at Object.onceWrapper (node:events:633:26)
    at WriteStream.emit (node:events:530:35)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\Projects\\cloudflare\\dist\\index.html.30336.1c'
}
```
The dev server randomly crashes. I'm note using the "dist" directory, but it still writes stuff there.

package.json fragment
```
  "files": [],
  "engines": {
    "node": ">=20.0.0"
  },
  "parcel": {},
  "source": [
    "src/index.html",
    "src/login/index.html"
  ],
  "targets": {
    "default": {
      "distDir": "_site"
    }
  }
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.12.0
| Node             |   v20.12.0
| npm/Yarn         | 10.5.0
| Operating System | Win 10

**Comment by mischnic** [comment] 2024-04-05 08:00
Duplicate of https://github.com/parcel-bundler/parcel/issues/8615

**Closed as not planned by mischnic** 2024-04-05 08:00 UTC
