### ISSUE TITLE
Parcel frequently crashes when building simple HTML+SCSS + JS web

### ISSUE THREAD

**Issue by PinkMeNow** [parcel-bundler/parcel#9783] opened 2024-06-10 12:41 UTC
# 🐛 bug report

Parcel frequently crashes when saving during running dev server

## 🎛 Configuration (.babelrc, package.json, cli command)

{
  "name": "test",
  "version": "1.0.0",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel src/**/index.html --open --no-cache --no-source-maps",
    "start": "parcel",
    "build": "parcel build src/**/index.html --no-source-maps"
  },
  "keywords": [],
  "author": "pinkmenow.com",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@parcel/packager-raw-url": "^2.12.0",
    "@parcel/transformer-sass": "^2.12.0",
    "@parcel/transformer-webmanifest": "^2.12.0",
    "parcel": "^2.12.0",
    "posthtml-include": "^2.0.1",
    "sharp": "^0.31.1"
  },
  "dependencies": {
    "@popperjs/core": "^2.11.8",
    "bootstrap": "^5.3.3",
    "gsap": "^3.12.5",
    "jquery": "^3.7.1",
    "normalize.css": "^8.0.1",
    "posthtml-doctype": "^1.1.1",
    "swiper": "^11.1.3"
  }
}

## 🤔 Expected Behavior

even on minor HTML/SCSS change parcel should be runing.

## 😯 Current Behavior

It crashes apparently randomly approximately on every few saves.

Optimizing proizvodi\carShake\lavender\index.[hash].css...
node:fs:1879
  binding.unlink(path);
          ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\kosye\Desktop\shake\dist\proizvodi\carShake\lavender\index.html.2276.6b'
    at Object.unlinkSync (node:fs:1879:11)
    at WriteStream.<anonymous> (C:\Users\kosye\Desktop\shake\node_modules\@parcel\fs\lib\index.js:1024:83)
    at Object.onceWrapper (node:events:635:26)
    at WriteStream.emit (node:events:532:35)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\Users\\kosye\\Desktop\\shake\\dist\\proizvodi\\carShake\\lavender\\index.html.2276.6b'

## 🔦 Context

It makes parcel based workflow almost unusable.

## 🌍 Your Environment

VSCode

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.12.0
| Node             |  22.1.0
| npm/Yarn         | 10.7.0
| Operating System | Windows 11 Home

**Comment by mischnic** [comment] 2024-06-10 13:03
Duplicate of https://github.com/parcel-bundler/parcel/issues/8615

**Closed as not planned by mischnic** 2024-06-10 13:03 UTC
