### ISSUE TITLE
Resolve relative-path font from @use Sass module

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#7641] opened 2022-02-02 15:23 UTC
# 🐛 bug report

When I import a font from a module that is imported by another module (via `@use`), its base path is the same from which source imported the font's parent module. Wait, it's easier to illustrate to understand the problem better.

I've these sources:

`src/a.scss`

```sass
@use './somewhere/else/b.scss' with (
    $foo: #fff,
);
```

`src/somewhere/else/b.scss`

```sass
@font-face {
    font-family: "Roboto";
    font-weight: normal;
    src: url("./roboto-regular.ttf") format("ttf");
}

$foo: #fff !default;
```

Sass thinks `roboto-regular.ttf` is located at `src/roboto-regular.ttf`, but it should be `src/somewhere/else/roboto-regular.ttf`. I'm using Parcel for the build process.

## 🎛 Configuration (.babelrc, package.json, cli command)

[parcel-sass-sample](https://github.com/Klaider/parcel-sass-sample)

## 🤔 Expected Behavior

Font should be resolved at the same path of the containing module.

## 😯 Current Behavior

Font is resolved relative to the path that imported its parent module.

Error:

```plain
Building...
× Build failed.

@parcel/core: Failed to resolve './roboto-regular.ttf' from './src/style.scss'
  C:\Users\hando\Documents\parcel-sass-sample\src\style.scss:4:5
@parcel/resolver-default: Cannot load file './roboto-regular.ttf' in './src'.
```

## 🔦 Context

Import font within application's distribution recipe.

## 💻 Code Sample

[parcel-sass-sample](https://github.com/Klaider/parcel-sass-sample)

Reproduce:

- `npm install`
- `npm run compile`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 14.17.5
| npm/Yarn         | 6.14.14
| Operating System | Windows 11

**Comment by rajsite** [comment] 2022-02-18 07:07
I ran into the same issue trying to switch an application from `@import` to `@use`. Looks like @Klaider gave a good minimal reproduction!

**Comment by basher** [comment] 2022-05-19 09:59
I'm also having an issue with resolving relative paths.
Wasn't sure if I should create a new bug, or add my specific issue here?

Here's my minimal test case:
https://github.com/basher/Parcel-Sass-Modules

If you look at https://github.com/basher/Parcel-Sass-Modules/blob/main/src/scss/globals/_typography.scss, I've had to fully qualify the relative path for my base variables Sass module.

EDIT:
I've raised my issue in Sass Git repo = https://github.com/sass/dart-sass/issues/1696

**Comment by mischnic** [comment] 2022-06-20 07:04
Duplicate of https://github.com/parcel-bundler/parcel/issues/540

**Closed as not planned by mischnic** 2022-06-20 07:04 UTC
