### ISSUE TITLE
How to config less options

### ISSUE THREAD

**Issue by vdfor** [parcel-bundler/parcel#907] opened 2018-02-28 01:21 UTC
When using less3, how to enable inline javaScript?

**Comment by vdfor** [comment] 2018-02-28 01:27
When use less3, how to enable inline javaScript?

**Comment by davidnagli** [comment] 2018-02-28 03:23
Just moved the description from the seperate comment into the issue body...

**Comment by chenshuai2144** [comment] 2018-03-06 07:07
lessrc no working

**Comment by chenshuai2144** [comment] 2018-03-08 06:05
I think it should be able to turn on this function in lessrc

**Comment by BeliefRC** [comment] 2018-03-16 03:11
less3.0.1  no working,but  less2.7.3  is working

**Comment by schtr4jh** [comment] 2018-05-05 13:05
Encountered same problem, all I had to do is add --js flag to lessc command: lessc --js foo.less > bar.css

**Comment by schtr4jh** [comment] 2018-05-23 08:40
@y-takey I landed here because of some other issue, unrelated to parcel. As far as I know this is something that's changed in some of latest versions of lessc compiler. Maybe you can downgrade lessc if it's installed globally? Or prepare pr that fixes it. :P

**Comment by y-takey** [comment] 2018-05-23 08:45
@schtr4jh Thanks for the quick response! I'll try to downgrade lessc.

**Comment by DeMoorJasper** [comment] 2018-05-23 08:47
What about adding:
{
  "inlineJavaScript": true
}
to .lessrc?

According to the less docs this should re-enable the deprecated inlining feature.
As this is deprecated I don't think this should be the default on parcel

**Comment by y-takey** [comment] 2018-05-24 01:45
@DeMoorJasper Thanks for the advice! (and sorry for the delay) I've tried it, but i can't work well :(

> As this is deprecated I don't think this should be the default on parcel
yes, I agree too.

**Comment by viztor** [comment] 2018-07-06 12:06
Is this fixed? I've been trying to use Antd's babel-plugin-import with Parcel, but doesn't seems to be helpful

**Comment by PierrickGT** [comment] 2018-07-10 12:40
I've managed to make it work using almost the same config than the one in the example available here : https://github.com/ant-design/parcel-antd

I've setup HMR so in my case, I needed to have the following `.babelrc` config to make the project work.

```
{
    "presets": [
      "react",
      "env"
    ],
    "plugins": [
        "react-hot-loader/babel",
        "transform-class-properties",
        ["import", {
          "libraryName": "antd",
          "libraryDirectory": "es",
          "style": true
        }]
    ]
}
```

**Comment by viztor** [comment] 2018-07-15 20:01
The problem is primarily with Less v3. I downgraded it and it worked. but it still requires fixing as we won't be able to stay v2.7 forever

**Comment by lxwbr** [comment] 2018-08-20 21:39
Having the same problem, have to stay on 2.7.3 for now. Hopefully this will be fixed soon.

**Comment by DeMoorJasper** [comment] 2018-08-20 23:10
As this is a deprecated feature of less, I don't think parcel should fix this.

If anyone could open a decent issue with an example repo and such someone might have a look at it. Gonna close this for now.

**Closed by DeMoorJasper** 2018-08-20 23:10 UTC
Labels: :bug: Bug

**Comment by fourcolors** [comment] 2019-01-13 20:37
It would be nice if there was a flag that enabled this since there are still a ton of libs out there that have inline js. Antd for instance "should" upgrade but I'm having to downgrade to use their lib. It might be too soon to completely ditch it but it's an edge case that should be supported.

**Comment by wildcookie007** [comment] 2019-02-22 11:40
Solution for webpack:

```
AntdScssThemePlugin.themify({
	loader: 'less-loader',
		options: {
			javascriptEnabled: true
		}
})
```

**Comment by urwork** [comment] 2019-03-14 18:12
seems .lessrc take no effect

**Comment by Phytonmk** [comment] 2019-03-23 07:03
Why issue is closed? The problem still exists

**Comment by djamaile** [comment] 2019-05-12 15:29
v3 still does not work in 2019. Is using version 2.7.1 really the only work around?

**Comment by entrptaher** [comment] 2019-05-22 05:13
Parcel throws this error, "Inline JavaScript is not enabled. Is it set in your options?"

What should we do here? Sit and do nothing? Switch to rollup or webpack?

**Comment by entrptaher** [comment] 2019-05-22 06:19
Apperently the `LessAsset` does not read the .lessrc file at all. I have zero clues at this moment.

However the fix was just one line one file. 
![image](https://user-images.githubusercontent.com/8284972/58151342-27b54400-7c8b-11e9-8a43-890979d32c35.png)

I extracted the code and published as a npm module till they somehow fix it in future.  Steps to follow:

```
yarn add -D parcel-plugin-less-js-enabled
```

I think I'll take down the repo later when everything is fixed.

**Comment by gabrielnoal** [comment] 2019-05-22 23:05
I have fixed this problem just changing ```"style":true``` at  .babelrc antd import for ```"style":true```.
## before
```.babelrc```
```
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["import", { "libraryName": "antd", "style": "css" }],
  ]
}
```
Print screen
![image](https://user-images.githubusercontent.com/18487803/58214521-64555f80-7ccc-11e9-8be2-a97fb4084546.png)

## after
```
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    ["import", { "libraryName": "antd", "style": "css" }],
  ]
}
```
Print screen
![image](https://user-images.githubusercontent.com/18487803/58214556-89e26900-7ccc-11e9-8929-ea2ab0339419.png)

### PS:    I dont't know if this fix will break something later, but it works for now :+1:

**Comment by y-takey** [comment] 2019-06-20 07:34
I got works correctly!

my environment:
```
parcel-bundler: 1.12.3
less: 3.9.0
less-loader: 5.0.0
(antd: 3.19.5)
```

`<project root>/.lessrc`
```json
{
  "javascriptEnabled": true
}
```
**NOT** "inlineJavaScript"

`<project root>/src/index.less`

```less
@import "~antd/dist/antd.less";

@primary-color: #4caf50;
```

**Comment by wangyongf** [comment] 2019-07-13 15:25
> I got works correctly!
> 
> my environment:
> 
> ```
> parcel-bundler: 1.12.3
> less: 3.9.0
> less-loader: 5.0.0
> (antd: 3.19.5)
> ```
> 
> `<project root>/.lessrc`
> 
> ```json
> {
>   "javascriptEnabled": true
> }
> ```
> 
> **NOT** "inlineJavaScript"
> 
> `<project root>/src/index.less`
> 
> ```css-less
> @import "~antd/dist/antd.less";
> 
> @primary-color: #4caf50;
> ```

It workded for me too, thanks~

**Comment by ivanslf** [comment] 2019-07-27 14:25
Same here. It works!

**Comment by Gr8manish** [comment] 2019-09-08 10:54
> Solution for webpack example:
> 
> ```
> 
> 	loader: 'less-loader',
> 		options: {
> 			javascriptEnabled: true
> 		}
> ```

This solution worked for me (y)

**Comment by chengsokdara** [comment] 2019-11-12 06:02
@y-takey your solutions doesn't work for me.

I tried below setup and it works for me. But I don't know if this is correct way, because I want to use the options `style: true` and `libraryDirectory: "es"` in .babelrc

package.json
```javascript
"devDependencies": {
  "babel-plugin-import": "^1.12.2",
  "parcel-bundler": "^1.12.4"
},
"dependencies": {
  "antd": "^3.25.1",
  "react": "^16.11.0",
  "react-dom": "^16.11.0"
}
```

.babelrc
```javascript
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd"
      },
      "antd"
    ]
  ]
}
```

.lessrc
```javascript
{
  "javascriptEnabled": true
}
```

public/index.less
```less
@import "../node_modules/antd/dist/antd.less";
@primary-color: purple;
```

**Comment by entrptaher** [comment] 2019-11-18 10:05
I came back from the future for another project, and parcel-bundler is still not fixed. The only thing works with parcel is the one plugin I created above https://github.com/parcel-bundler/parcel/issues/907#issuecomment-494668029.

@davidnagli @DeMoorJasper, maybe we should re-open this issue and fix this asap. Because lots of new people are starting to use ant-design with parcel and getting a roadblock with less mostly because **parcel does not read the less configuration**.

It's a parcel issue. I vote to re-open this.

**Comment by mischnic** [comment] 2019-11-22 22:21
I tried the setup in https://github.com/parcel-bundler/parcel/issues/907#issuecomment-511130343 and it seemed to build successfully.

Could someone post an updated example and what the expected behaviour is?

**Comment by fredwin-o** [comment] 2020-01-06 15:46
Has anyone found a solution I still can't use less ^3?

**Comment by konsumer** [comment] 2020-03-21 22:52
@entrptaher 's solution above, while totally a hack, works awesome for me. This is what I do in a lot of projects, now. I think the asset-loader should probably read the .lessrc, and also maybe just have a default that enables `javascriptEnabled`. I have this come up with rsuite, ant, and a few others, and it seems to be a reasonable default.

**Comment by pojntfx** [comment] 2020-04-18 07:31
So, #4475 fixes the issue! This allows for Antd etc. to be used:

package.json:

```json
{
  "name": "parcel-ant",
  "devDependencies": {
    "@parcel/transformer-less": "^2.0.0-alpha.3",
    "less": "^3.11.1",
    "parcel": "2.0.0-nightly.225"
  },
  "dependencies": {
    "antd": "^4.1.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "scripts": {
    "start": "parcel index.html"
  }
}
```

.lessrc:

```json
{
  "javascriptEnabled": true
}
```

index.less:

```less
@import "antd/dist/antd.less";
@primary-color: purple;
```

App.js

```js
import React from "react"
import { DatePicker } from "antd"
import "./index.less"

export default (props) => <DatePicker {...props} />
```

This is the result:

<img width="1436" alt="Screen Shot 2020-04-18 at 09 31 04" src="https://user-images.githubusercontent.com/28832235/79631136-55cf2c80-8157-11ea-9756-870169cd9c14.png">

Works as expected!

**Comment by lemondreamtobe** [comment] 2020-06-10 06:43
> Apperently the `LessAsset` does not read the .lessrc file at all. I have zero clues at this moment.
> 
> However the fix was just one line one file.
> ![image](https://user-images.githubusercontent.com/8284972/58151342-27b54400-7c8b-11e9-8a43-890979d32c35.png)
> 
> I extracted the code and published as a npm module till they somehow fix it in future. Steps to follow:
> 
> ```
> yarn add -D parcel-plugin-less-js-enabled
> ```
> 
> Before:
> 
> ```
> ➜  experiment-parcel-antd git:(master) ✗ yarn start
> yarn run v1.13.0
> $ parcel src/index.html
> Server running at http://localhost:1234 
> 🚨  node_modules/antd/lib/form/style/index.less: Inline JavaScript is not enabled. Is it set in your options?
> ```
> 
> Now:
> 
> ```
> ➜  experiment-parcel-antd git:(master) ✗ yarn start
> yarn run v1.13.0
> $ parcel src/index.html
> Server running at http://localhost:1234 
> ✨  Built in 343ms.
> ```

it really works for me ! big thanks!

**Comment by fayismahmood** [comment] 2020-07-09 09:03
> I got works correctly!
> 
> my environment:
> 
> ```
> parcel-bundler: 1.12.3
> less: 3.9.0
> less-loader: 5.0.0
> (antd: 3.19.5)
> ```
> 
> `<project root>/.lessrc`
> 
> ```json
> {
>   "javascriptEnabled": true
> }
> ```
> 
> **NOT** "inlineJavaScript"
> 
> `<project root>/src/index.less`
> 
> ```css-less
> @import "~antd/dist/antd.less";
> 
> @primary-color: #4caf50;
> ```

Thanks alot

**Comment by avalanche1** [comment] 2021-02-27 00:56
Still getting this error for Parcel 2.
Proposed solution doesn't work.

**Comment by vollantre** [comment] 2021-05-10 23:40
same

> Still getting this error for Parcel 2.
> Proposed solution doesn't work.



> Still getting this error for Parcel 2.
> Proposed solution doesn't work.

Same here, please can anyone help

**Comment by joshua-hashimoto** [comment] 2021-08-29 05:00
I still have the same problem too.
In my case it was working just fine like 4 days ago, but after I installed antd icon package it just started throwing errors. samething after uninstalling the package

**Comment by xiemeilong** [comment] 2021-12-09 01:43
This issue is still exist in the latest parcel.  I workaround by  hard code to the `@parcel/transformer-less`.  The .lessrc file is not readed all the time.
```
diff --git a/node_modules/@parcel/transformer-less/lib/loadConfig.js b/node_modules/@parcel/transformer-less/lib/loadConfig.js
index eb1f93e..f6f20f7 100644
--- a/node_modules/@parcel/transformer-less/lib/loadConfig.js
+++ b/node_modules/@parcel/transformer-less/lib/loadConfig.js
@@ -36,6 +36,7 @@ async function load({
 
   configContents.rewriteUrls = 'all';
   configContents.plugins = configContents.plugins || []; // This should enforce the config to be reloaded on every run as it's JS
+  configContents.javascriptEnabled = true;
 
   let isDynamic = configFile && _path().default.extname(configFile.filePath) === '.js';
```

**Comment by avalanche1** [comment] 2021-12-09 12:21
Guess, Antd and Parcel are simply not compatible.
