### ISSUE TITLE
HMR port used in HMRRuntime when using https

### ISSUE THREAD

**Issue by zouloux** [parcel-bundler/parcel#7150] opened 2021-10-21 15:25 UTC
Thanks a lot for Parcel V2.0 release !

# 🐛 bug report

First of all, I'm using Parcel API and not CLI, I also use an Nginx proxy and not the internal Parcel server. My Nginx proxy has an **https** endpoint, so I need to specify `serveOptions` to enable https (wss) feature on hmr. Without it, `hmr-runtime.js` tries to connect from secure to non secure and connexion is refused for security reasons. It may be an edge case.

With this config, it should be working but `hmr-runtime.js` tries to connect to `wss://my-host` without port, which defaults to port 443. Nginx is behind 443 and connexion also fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
hmrOptions: {
   port : 3456,
   host: 'my-host',
},
serveOptions: {
   port: 3456,
   host: 'my-host',
   https: {
      cert : 'path-to-cert',
      key : 'path-to-key',
   }
}
```

## 🤔 Expected Behavior

It should always connect correctly to specified HMR port, with or without usage of internal server.
In fact, we also should be able to have an https hmr server without `serveOption`.

## 💁 Possible Solution

After searching a bit I found that `@parcel/runtime-browser-hmr/lib/HMRRuntime.js` has this statement : 
```
        `var HMR_PORT = ${JSON.stringify(
          port != null &&
            // Default to the HTTP port in the browser, only override
            // in watch mode or if hmr port != serve port
            (!options.serveOptions || options.serveOptions.port !== port)
            ? port
            : null,
        )};`
```
which is what is triggering the issue in my case. When replacing with : 
```
        `var HMR_PORT = ${JSON.stringify(port)};`
```
It's working as expected. `port` is a mandatory parameter for hmr so I skipped the ?: check and it seems to be working.

An other solution should be to add `https` option to `hmrOptions` but it may ask more work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.2
| npm/Yarn         | 7.13
| Operating System | MacOS 10.15.7

Thanks !

**Comment by 101arrowz** [comment] 2021-10-21 15:55
This looks similar to #6061. I think #6005 needs to be reverted to support this.

**Comment by zouloux** [comment] 2021-12-07 14:11
Hi, so, I tried to patch it and taking in consideration #6005.
I replaced the `HMR_PORT` statement by : 
`var HMR_PORT = location.hostname == HMR_HOST ? null : ${JSON.stringify(port)};`
What do you think about it ? It seems to work in HTTP and HTTPs correctly now. Not 100% sure but should also work for #6005 because we do not use port only if current browser's hostname is the same as published hostname by Parcel.
Thanks a lot.

**Comment by mischnic** [comment] 2022-03-04 18:11
Duplicate of https://github.com/parcel-bundler/parcel/issues/6061

**Closed as completed by mischnic** 2022-03-04 18:11 UTC
