### ISSUE TITLE
How to refresh the browser upon file changes

### ISSUE THREAD

**Issue by robbyjm** [parcel-bundler/parcel#3719] opened 2019-10-31 20:28 UTC
# ❔ Question
How can I refresh the browser automatically while watching for file changes? 

`parcel watch index.html` seems promising, but when I do that, it looks like the server doesn't start? 'localhost:1234' no longer starts. 
## 💻 Code Sample
```
<html>
<body>
  Hello world
</body>
</html>
```
So for example if i change `Hello world` to `Goodbye` how do I get the browser to detect that change and refresh. Right now I have been using another npm package but I was wondering if parcel was also capable of doing this. Am I supposed to use hot module replacement for this?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 11.7.0
| npm/Yarn         | npm 6.9.0
| Operating System | Mojave 10.14.6

**Comment by mischnic** [comment] 2019-10-31 20:42
If you run `parcel index.html` (or equivalently: `parcel serve index.html`), Parcel will start a dev server, watch for changes and refresh the page in your browser when modified.

**Comment by robbyjm** [comment] 2019-10-31 22:02
> If you run `parcel index.html` (or equivalently: `parcel serve index.html`), Parcel will start a dev server, watch for changes and refresh the page in your browser when modified.

That doesn't appear to be working for me. I have to manually refresh the browser to see the changes. I am using firefox if that makes any difference

**Comment by mischnic** [comment] 2019-11-01 11:24
Ah, I remember now: the code that Parcel injects into the bundle is added to an existing JS script that is already part of your build. Without any script however, that isn't added:

Duplicate of https://github.com/parcel-bundler/parcel/issues/943

**Closed by mischnic** 2019-11-01 11:24 UTC
Labels: :bug: Bug
