### ISSUE TITLE
Missing stylesheet from multiple entry files building for production 

### ISSUE THREAD

**Issue by Nyoijizai** [parcel-bundler/parcel#4702] opened 2020-06-06 02:31 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"name": "dev.parcel.bianchengquan",
	"version": "1.0.1",
	"description": "",
	"private": true,
	"scripts": {
		"dev": "parcel ./src/pages/**/*.html --open"
	},
	"author": "Nyoijizai",
	"license": "MIT",
	"dependencies": {
		"bootstrap": "^4.5.0",
		"jquery": "^3.5.1",
		"popper.js": "^1.16.1"
	},
	"devDependencies": {
		"node-sass": "^4.14.1",
		"sass": "^1.26.7"
	}
}

```

```js
// My file path

/src
/-- pages
/--/-- down
/--/--/ index.html
/--/--/ column.html
/--/--/ down.js
/--/--/ down.scss
```

## 🤔 Expected Behavior

When I visied `src/pages/down/index.html`,I can got assets like JavaScript, CSS, and HTML files. 
![image](https://user-images.githubusercontent.com/65013145/83933881-17610000-a7df-11ea-99c8-2dc33c302989.png)

But I visied `src/pages/down/[other].html`,the CSS is gone.
![image](https://user-images.githubusercontent.com/65013145/83934015-0664be80-a7e0-11ea-8409-889faff77b36.png)

## 💻 Code Sample

```html
<!-- All HTML use down.js -->
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Home</title>
	</head>
	<body></body>
	<script src="./down.js"></script>
</html>

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |v12.17.0
| npm         |6.14.4 
| Operating System |Windows 10

**Comment by mischnic** [comment] 2020-06-06 14:38
Duplicate of https://github.com/parcel-bundler/parcel/issues/2340

**Closed by mischnic** 2020-06-06 14:38 UTC
