### ISSUE TITLE
Bundle css and js in a single file

### ISSUE THREAD

**Issue by rgehan** [parcel-bundler/parcel#1421] opened 2018-05-22 23:17 UTC
# ❔ Question

Is it possible to bundle CSS and JS in a single file with Parcel?

## 🔦 Context

I'm trying to bundle a small widget (JS + SCSS) in a single file so that it can be imported by other websites easily.

I'd like people to be able to include my widget in a single import:
```html
<script type="text/javascript" src="http://domain.tld/my-widget.js"></script>
```

Parcel generates two files: `index.js` and `index.css`. I'd like the CSS to be embedded in the JS bundle. I've seen this with Webpack, but I didn't manage to find a way to do it with Parcel.

## 💻 Code Sample

My widget could be summed up to:
```js
import React from 'react';
import ReactDOM from 'react-dom';

import './Widget.scss';

const Widget = () => <div className="Widget">Widget</div>;

const container = document.getElementById('container');
ReactDOM.render(<Widget />, container);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.8.1
| Node             | v8.9.4
| npm/Yarn         | Yarn v1.3.2
| Operating System | Mac OS

**Comment by DeMoorJasper** [comment] 2018-05-23 06:28
duplicate of #1370

**Closed by DeMoorJasper** 2018-05-23 06:28 UTC
