### ISSUE TITLE
Error when executing `npx parcel src/index.html`

### ISSUE THREAD

**Issue by MystPi** [parcel-bundler/parcel#7377] opened 2021-11-29 00:36 UTC
When I execute the command `npx parcel src/index.html`, I get this error:

```
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
```

I'm on Debian 10, if that helps.

Any solutions would be appreciated!

**Comment by mischnic** [comment] 2021-11-30 09:07
Duplicate of https://github.com/parcel-bundler/parcel/issues/6735

**Closed as completed by mischnic** 2021-11-30 09:07 UTC
