### ISSUE TITLE
Loading libraries via script src doesn't create the global

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/parcel#2422] opened 2018-12-16 04:35 UTC
# 🐛 bug report

Loading via `script src` a local copy of a library doesn't create the `window` global that it does if the library were loaded from its absolute URL, or if the HTML file were open directly in the browser via `file:///`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero-config.

## 🤔 Expected Behavior

I expect that the code sample below works the same whether it's loaded by the browser via `file:///`, or by `parcel index.html`. The sample simply loads jQuery via `script src` in the HTML and logs `$`.

## 😯 Current Behavior

> (index):6 Uncaught ReferenceError: $ is not defined

## 💁 Possible Solution

Including the full URL in `script src` works:

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" type="text/javascript"></script>

## 🔦 Context

The use case is obviously not jQuery, but loading Pro/paid libraries that need to be downloaded separately and aren't available via npm or CDNs.

## 💻 Code Sample

Download/cURL/wget https://code.jquery.com/jquery-3.3.1.slim.min.js in the same directory as `index.html`.

```html
<html>
<head>
  <script src="jquery-3.3.1.slim.min.js" type="text/javascript"></script>
</head>
<body>
<script>
console.log($);
</script>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | commit 7a540fc4cc2511f749f3a687ce342000953cfcec
| Node             | 11.3.0
| npm/Yarn         | 6.5.0
| Operating System | Ubuntu Linux 16.04

**Comment by mischnic** [comment] 2019-01-07 21:36
Duplicate of #333

**Closed by mischnic** 2019-01-07 21:36 UTC
Labels: :bug: Bug

**Comment by flkx** [comment] 2020-12-03 17:19
pffff Parcel is super light bla bla bla but ... it doesn't work !!
