### ISSUE TITLE
parcel 2 build command may dangerously overwrite source files in workspace folder

### ISSUE THREAD

**Issue by gogiii** [parcel-bundler/parcel#5041] opened 2020-08-19 16:06 UTC
# 🐛 bug report

Parcel 2 drops build result into current (project) folder instead of ./dist by default (comparing to parcel1)!
it also **overwrites** html source file but creates scripts with hashed names.
project example of two files: test.js, test.html
>parcel build test.html
```
√ Built in 6.05s
test.html           167 B    930ms
test.8db25ec3.js     70 B    1.26s
```

Using "dist-dir" flag doesn't work - it's ignored!
>parcel build test.html --dist-dir dist

Same behaviour using both yarn or npm.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "test",
  "version": "1.0.0",
  "main": "test.html",
  "dependencies": {
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  },
  "scripts": {
    "build": "parcel build test.html --dist-dir dist"
  }
}
```

## 🤔 Expected Behavior

Original files not changed by parcel.
Build result appear in ./dist folder.

## 😯 Current Behavior

test.html is **overwritten** by parcel's result in current (project) folder:

```<html><head><meta charset="utf8"><title>Test</title></head><body> <div id="root"></div> <script src="/test.8db25ec3.js" type="text/javascript"></script> </body></html>```

test.js name is hashed correctly as test.8db25ec3.js avoiding being overwritten.

## 💻 Code Sample

test.js
``
console.log("hello world");
``

test.html
```
<html>
    <head>
        <meta charset="utf8"/>
        <title>Test</title>
    </head>
    <body>
        <div id="root"></div>
        <script src="test.js" type="text/javascript"></script>
    </body>
</html>
```

## 🌍 Your Environment

| Software  | Version(s) |
| ------------ | ---------- |
| Parcel       | 2.0.0-beta.1
| Node        | v12.18.3
| Yarn         | yarn v1.22.4
| npm         | 6.14.6
| Operating System | Windows 7 64-bit

**Comment by cameronelliott** [comment] 2020-12-04 03:36
I almost lost hours of work because of this change when I switched from v1 to v2. This really got my attention.

**Comment by devongovett** [comment] 2020-12-04 04:00
Your main field in package.json is pointing to the same html file as your input. Parcel uses this field as the _output_, thus it overwrites it. Removing the main field should fix the issue. It's invalid anyway because only JS files can be referenced from that field.

**Comment by mischnic** [comment] 2020-12-04 09:12
Duplicate of https://github.com/parcel-bundler/parcel/issues/4255.

**Closed by mischnic** 2020-12-04 09:12 UTC
Labels: :bug: Bug, ✨ Parcel 2

**Comment by gogiii** [comment] 2020-12-04 10:29
**devongovett**, specifying .js was a working variant in v1, but in v2 it gives error when building against test.html with "dist-dir" option:
```
> parcel build test.html --dist-dir dist
× Build failed.
@parcel/namer-default: Target "main" declares an output file path of "test.js" which does not match the compiled bundle type "html".
...\package.json:4:11
  3 |   "version": "1.0.0",
> 4 |   "main": "test.js",
>   |           ^^^^^^^^^ Did you mean "test.html"?
```
Removing main field at all gives another error:
```
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (....\node_modules\@parcel\core\lib\PackagerRunner.js:491:47)
    at getBundlesIncludedInHash (....\node_modules\@parcel\core\lib\PackagerRunner.js:495:7)
```
This was running at 2.0.0-beta.1 (I can't test the actual version right now).
So one can only run "parcel build test.html" that puts result into the same folder with overwrites.

**mischnic**, it's not just a matter of overwritting files (as being a duplicated) but also about the usecase with html build and probably non-working --dist-dir parameter (or is ther any other parameter that sets output folder? in newer builds?)
v1 was just putting result into the dist folder by default without any parameters so there were no problem with overwrites.
Putting sources out of execution folder into some subfolder (like src) also doesn't help - it will overwrite files in the subfolder.

**Comment by devongovett** [comment] 2020-12-04 13:56
Removing the main field is the correct solution. The error you got may be related to cache. Try deleting the .parcel-cache folder.

**Comment by gogiii** [comment] 2020-12-04 15:58
**devongovett**, Removing the .parcel-cache did the trick. It also puts the result into the dist folder by default and even --dist-dir parameter works! Thanks!
