### ISSUE TITLE
How to specify output without subfolders? Not to follow the source structure

### ISSUE THREAD

**Issue by radmedov** [parcel-bundler/parcel#3941] opened 2019-12-25 00:51 UTC
# ❔ Question
Hi guys,
I just want to find a way to not follow a source structure and build files from multiple entrypoints into one flattened folder.

## 🔦 Context
Current behavior:
Source `scripts/templates/some.js` output `dist/templates/some.js`

Desired behavior:
Source `scripts/templates/some.js` output `dist/some.js`

Thank you 🙂

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         | Yarn
| Operating System | MacOS

**Comment by mischnic** [comment] 2019-12-29 14:30
This isn't possible because this is not possible in the general case, e.g.: `subpage1/index.html` and `subpage2/index.html` - both entrypoints have the same filename.

**Comment by mischnic** [comment] 2020-01-17 12:05
Closing as duplicate of https://github.com/parcel-bundler/parcel/issues/3941

**Closed by mischnic** 2020-01-17 12:05 UTC
Labels: :grey_question:  Question
