### ISSUE TITLE
tree shaking used in async modules, not found module

### ISSUE THREAD

**Issue by rambo-panda** [parcel-bundler/parcel#2804] opened 2019-03-15 08:09 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// cli command
{
  production: true,
  scopeHoist: true,
  hmr: false,
  minify: !true,
  cache: false,
  watch: false,
  detailedReport: true,
  target: "browser",
  sourceMaps: false
}
```

## 💻 Code Sample

```js

// a.js
const c = () => import('./c.js')
console.log(c);

// b.js
const c = () => import('./c.js')
console.log(c);

// c.js
export default () => {
	console.log(111);
}

// main.js
const a = () => import("./a.js");
const b = () => import("./b.js");

console.log(a);
console.log(b);
```

## 😯 Current Behavior

```js
// generated a.js
var $KX6I$var$c = function c() {
  return ($_$init(), $_$exports)([["c.a92336cc.js", "KQUl"], "KQUl"]);
};

// generated b.js
var $gffB$var$c = function c() {
  return ($_$init(), $_$exports)("KQUl");
};
```
When the js resource is loaded in the browser order `main.js b.js`, then throw **NOT FOUND KQUI module** error.

## 🤔 Expected Behavior

If you are loading modules asynchronously, you should also keep information about their assetsDeps.

## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/blob/parcel-bundler%401.12.1/packages/core/parcel-bundler/src/scope-hoisting/concat.js#L201

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.1
| Node             |  10.15.2
| npm/Yarn         | 5.4.1
| Operating System | mac 10.14

**Comment by mischnic** [comment] 2019-03-16 17:21
Happened for me with this:
`parcel build index.html --experimental-scope-hoisting`

```html
<script src="./index.js"></script>
```
```js
// index.js
import("./a.js").then(() => {});
import("./b.js").then(() => {});


// a.js
import("./c.js").then(v => console.log("a", v.default));


// b.js
import("./c.js").then(v => console.log("b", v.default));


// c.js
export default 123;
```

**Comment by mischnic** [comment] 2019-03-16 18:17
I'd say this is once again caused by Parcel's deduplication of assets.
The bundle of `a.js` does have `c.js` listed as a childBundle, but `b.js` doesn't.

**Comment by rambo-panda** [comment] 2019-03-18 10:47
> I'd say this is once again caused by Parcel's deduplication of assets.
> The bundle of `a.js` does have `c.js` listed as a childBundle, but `b.js` doesn't.

That's it!

https://github.com/parcel-bundler/parcel/blob/cbccd2586b4f67bbac2704036065c853fa2bd780/packages/core/parcel-bundler/src/Bundler.js#L647-L656

**Comment by mischnic** [comment] 2019-03-23 19:04
@devongovett This would require quite a deep change (removing the duplicate assets/bundles only at a later stage). Will this be easier with Parcel 2?

**Comment by mischnic** [comment] 2023-01-03 22:22
Should be fixed with Parcel 2

**Closed by mischnic** 2023-01-03 22:22 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, 🌳 Scope Hoisting
