### ISSUE TITLE
2.4.0: Invalid JavaScript produced (parentheses-wrapped comment within return value)

### ISSUE THREAD

**Issue by lorenzogrv** [parcel-bundler/parcel#7872] opened 2022-03-28 11:33 UTC
# 🐛 bug report

After upgrading to version 2.4.0, building a project which depends on [openlayers](https://openlayers.org/) produces invalid JavaScript code.

> This is unlikely related to the openlayers library as it distributes valid source code.

## 🎛 Configuration (.babelrc, package.json, cli command)

The project uses parcel default config, and `@babel/preset-react` as it's a react-based SPA.

Relevant `package.json` sections

```json
{
  "scripts": {                                                                    
    "start": "parcel serve src/index.html",
    "build": "parcel build --public-url / src/index.html"
  },
  "dependencies": {
    "ol": "^6.14.1"
  },
  "devDependencies": {
    "@babel/preset-react": "^7.16.7",
    "@parcel/transformer-image": "^2.0.1",
    "parcel": "^2.3.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "standard": "^16.0.3"
  },
  "browserslist": [
    "defaults",
    "not ios_saf < 13"
  ]
}
```

## 🤔 Expected Behavior

Valid JavaScript syntax to be produced

## 😯 Current Behavior

Invalid JavaScript syntax was produced after building, without warning or erroring about it.

Relevant error trace isn't applicable, as error is thrown within built bundle.

## 💁 Possible Solution

**Workaround**: Downgrading to parcel `2.3.2`

```shell
npm install parcel@2.3.2
```

## 🔦 Context

After project is built, bundled code will produce an `Uncaught SyntaxError: function statement requires a name` error when interpreted by browser engine.

## 💻 Code Sample

An excerpt of ofending code produced:

```javascript
function createTransformFromCoordinateTransform(coordTransform) {
    return /**
     * @param {Array<number>} input Input.
     * @param {Array<number>} [opt_output] Output.
     * @param {number} [opt_dimension] Dimension.
     * @return {Array<number>} Output.
     */ function(input, opt_output, opt_dimension) {
        // function body which is not relevant here
    };
}
```

**Which in fact isn't valid javascript** - linefeeed after `return` keyword at line 2 will produce an `;` while interpreted by any js engine

---

Original code is [browseable at openlayers/openlayers repository, src/ol/proj#L331](https://github.com/openlayers/openlayers/blob/main/src/ol/proj.js#L331). An excerpt:

```javascript
export function createTransformFromCoordinateTransform(coordTransform) {
  return (
    /**
     * @param {Array<number>} input Input.
     * @param {Array<number>} [opt_output] Output.
     * @param {number} [opt_dimension] Dimension.
     * @return {Array<number>} Output.
     */
    function (input, opt_output, opt_dimension) {
      // function body which is not relevant here
    }
  );
}
```

**Please note that parentheses around function's returned value - containing jsdoc doclets - are removed.**

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0
| Node             | v14.18.2
| npm/Yarn         | npm 7.24.2
| Operating System | GNU/Linux (debian based)

**Comment by puchol** [comment] 2022-03-28 23:32
I have the exact same issue, with the added problem that I'm not able to install any previous version of parcel via npm. All attempts at forcing e.g. 2.0.1 have failed, resulting in a package-lock.json full of dependencies on parcel v2.4.0 modules. Relevant section of package.json:

```
  "dependencies": {
    "@fortawesome/fontawesome-pro": "^5.15.3",
    "assets": "^3.0.1",
    "genversion": "^3.0.2",
    "h3-js": "^3.7.2",
    "jquery": "^3.6.0",
    "node-fetch": "^3.1.0",
    "ol": "^6.9.0",
    "open-location-code-typescript": "^1.5.0",
    "parcel": "2.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router": "^5.2.0"
  },
  "devDependencies": {
    "@parcel/bundler-default": "2.0.1",
    "@parcel/packager-raw-url": "2.0.1",
    "@parcel/transformer-webmanifest": "2.0.1"
  }
```

**Comment by mischnic** [comment] 2022-03-29 09:16
This is a duplicate of https://github.com/parcel-bundler/parcel/issues/7868#issuecomment-1079771029, will be fixed by https://github.com/parcel-bundler/parcel/pull/7870.

> 2.0.1 have failed, resulting in a package-lock.json full of dependencies on parcel v2.4.0 modules.

That is unfortunately true at the moment. I want to make make the `parcel` package pin the versions of the various `@parcel/*` packages but haven't gotten around to it yet.

**Closed as completed by mischnic** 2022-03-29 09:16 UTC

**Comment by lorenzogrv** [comment] 2022-03-31 12:30
Sorry about dupe reporting. Thank you
