### ISSUE TITLE
Parcel v2 fails to reload for relative path imports outside the root directory

### ISSUE THREAD

**Issue by escherlies** [parcel-bundler/parcel#8968] opened 2023-04-28 08:21 UTC
# Description:

I am using Parcel v2 for my web application, and I'm encountering an issue where the bundler fails to reload when I import modules using relative paths that point outside the root directory of my project. This issue is causing development delays, as I am unable to see changes made to the imported modules without manually restarting the bundler.

# Steps to reproduce:

1. Set up a new project with Parcel v2
1. Create a file outside the root directory, e.g., ../external-dir/module.js
1. Import this file in the project using a relative path, e.g., import myModule from '../external-dir/module.js';
1. Start the development server with parcel serve index.html
1. Make changes to the module.js file and save

# Expected behavior:

When I save changes made to module.js, I expect Parcel to automatically reload the development server and reflect the changes in the browser.

# Actual behavior:

Parcel does not reload the development server after saving changes to module.js. I need to manually restart the bundler to see the changes in the browser.

**Comment by mischnic** [comment] 2023-04-28 12:02
Duplicate of https://github.com/parcel-bundler/parcel/issues/4332

**Closed as not planned by mischnic** 2023-04-28 12:02 UTC
