### ISSUE TITLE
🐛Uncaught Error: Cannot find module '21'

### ISSUE THREAD

**Issue by makmm** [parcel-bundler/parcel#879] opened 2018-02-21 15:36 UTC
### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```json
{
  "presets": ["env"],
  "plugins": [
    ["babel-plugin-root-import", {
      "rootPathSuffix": "js",
      "rootPathPrefix": "@"
    }]
  ]
}
```

package.json:
```json
{
  "name": "hwm-parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "makmm",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-root-import": "^5.1.0"
  }
}
```

### 🤔 Expected Behavior

Run `$ parcel index.html`, go to `localhost:1234`, change something in the code and the browser should get the new code and load it

### 😯 Current Behavior

Run `$ parcel index.html`, go to `localhost:1234`, **console shows correct sourcemaps:** 
![image](https://user-images.githubusercontent.com/7550995/36488939-7d59c410-1703-11e8-9c1f-c97905f577bb.png)

change something in the code and this error comes up:
![image](https://user-images.githubusercontent.com/7550995/36488906-5ed4f046-1703-11e8-9ef7-27dcc2e5a701.png)

Refresh, now sourcemaps are broken:
![image](https://user-images.githubusercontent.com/7550995/36488970-8f8b980c-1703-11e8-95cb-2816d7ece75a.png)

### 💁 Possible Solution

No idea! <.<

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2 |
| Node             | 9.5.0 |
| npm         | 5.6.0 |
| Operating System | Debian sid |

**Comment by DeMoorJasper** [comment] 2018-02-21 19:19
Could u provide us with a test repository?

**Comment by makmm** [comment] 2018-02-21 19:21
@DeMoorJasper https://github.com/makmm/test-repo

**Comment by DeMoorJasper** [comment] 2018-02-21 19:39
Tried out your test repo and can confirm this is indeed happening, tried cleaning cache, disabling cache, disabling sourcemaps and going down to parcel v1.5.1 to see if it was not caused by recent changes.

**Comment by davidnagli** [comment] 2018-02-22 16:48
I’ve seen this error message tons of times:
#198
#326
#666
#497 


From looking at the issues the bugs seem totally unrelated, but I suppose maybe we should figure out where that error message is coming from and make it more informative. Or maybe the issues are related somehow... not sure 🤷‍♂️

**Comment by dmitry-vakhnenko** [comment] 2018-02-22 18:23
It will be good if we provide file file mapping moduleId => moduleName

**Comment by makmm** [comment] 2018-02-22 21:36
If there's a workaround I can use, please tell me as this is holding me back from developing my project.

**Comment by YUFENGWANG** [comment] 2018-02-23 07:14
@makmm fallback your node version to 8.9.4 and have a try

**Comment by makmm** [comment] 2018-02-23 12:38
@YUFENGWANG Tried with 8.9.3, same issue

**Comment by davidnagli** [comment] 2018-02-23 13:14
What OS is everybody who sees the issue using?

I’m on MacOS High Sierra (10.13.2), and I don’t get that `Cannot find module` error message. I only get:
```
Uncaught TypeError: Cannot read property 'getState' of undefined
```
Which makes sense, because when I log out `stores` I get:
```
stores: [undefined, GroupStore]
```
I’m not familiar with Angular so I have no clue why it’s undefined, but that doesn’t look like it’s being caused by Parcel.

Am I the only one that’s not getting the `Cannot find module` message?

**Comment by DeMoorJasper** [comment] 2018-02-23 13:34
@davidnagli i'm also using High Sierra

**Comment by makmm** [comment] 2018-02-23 20:12
@davidnagli 1. not Angular 2. yes, the error is normal, I want to fix it but can't because of this issue

**Comment by davidnagli** [comment] 2018-02-24 19:11
@DeMoorJasper That’s really strange... I’ve tried a million times and I can’t reproduce. I’ve tried different browsers, different Node versions (tried both `v9.6.1` and `v8.9.4`), different Parcel versions (`1.6.2` and `master`), and even different terminals (`Mac Terminal` and `iTerm2`).

I’m pretty much at a loss for reproducing this.

Can you guys try to remove parcel and reinstall it? That’s the only thing I can think off... 😕

**Comment by davidnagli** [comment] 2018-02-24 19:25
<details>
<summary>Another unsuccessful attempt to reproduce...</summary>
<br>
As a last ditch effort I just tried to perfectly recreate everything and installed the exact Node version number as @makmm, and verified that npm version numbers also match. Then I ran Parcel without HMR, cache, or sourcemaps, and I still didn’t get the error!
```
> parcel --version
1.6.2
> npm --version
5.6.0
> node --version
v9.5.0
> parcel index.html --no-hmr --no-cache --no-source-maps
Server running at http://localhost:1234
✨  Built in 9.15s.
```

Then I opened `localhost:1234` in Chrome (`64.0.3282.167 (Official Build) (64-bit)`), turned on Verbose logs, and disabled `Group Similar` (I think it’s a new feature). Still nothing...

I also tried in Safari, with the same exact result.

Let’s see if anyone else is able to reproduce...
</details>

**Comment by makmm** [comment] 2018-02-24 19:28
@davidnagli Reproduced on a completly different machine just now, Debian `sid` too, node `8.9.4`, latest parcel, deleted `node_modules` and re-installed (I pushed `node_modules`, whoops :P) and same error, but with 39 now. :/

**Comment by makmm** [comment] 2018-02-24 19:29
Wait @davidnagli , did you try modifying a file? that's when the error comes up.

**Comment by davidnagli** [comment] 2018-02-24 19:32
Oh!!! You mean during HMR?!

**Comment by makmm** [comment] 2018-02-24 19:33
I don't know what HMR is. >.<

**Comment by davidnagli** [comment] 2018-02-24 19:40
HMR is pretty much the “live reload” thing that refreshes your code within your app automatically whenever you make a change. See: [HMR Docs](https://parceljs.org/hmr.html)

So you’re saying that you don’t see an error when you open `localhost:1234` the first time, but then once you make a change and the app get’s automatically refreshed your seeing that error?

Try running parcel with these flag:
```
parcel index.html --no-hmr --no-cache --no-source-maps
```

**Comment by makmm** [comment] 2018-02-24 19:44
@davidnagli HMR is failing (in the way you said it is), but source maps are too, if I run it with the `--no-hmr` flag only, I have the same sourcemap issue after changing a file

**Comment by davidnagli** [comment] 2018-02-24 19:47
Interesting...

**Comment by davidnagli** [comment] 2018-02-24 19:48
Ummm question:

What does `@/` do here?
```javascript
import NavBar from '@/components/NavBar'
import GlobalAlert from '@/components/GlobalAlert'
import RouterView from '@/core/router/RouterView'
```

**Comment by davidnagli** [comment] 2018-02-24 19:56
Ok I’m pretty sure that’s gonna cause issues, because Parcel only runs Babel after resolving imports, meaning that those paths won’t be transformed with babel before we try to resolve them.

Can you try temporarly getting rid of them and seeing if it magically solves the issue?

Just so you know, we just added support for project relative imports built into Parcel, so you won’t even need this whole babel set up soon. The PR has already been merged and should be released to npm pretty soon :)

The PR: #850

**Comment by makmm** [comment] 2018-02-24 19:58
Oh great! let me try that, one second

**Comment by makmm** [comment] 2018-02-24 20:03
Nope, doesn't fix it ://

**Comment by davidnagli** [comment] 2018-02-24 20:11
😡 😠 😡

**Comment by mischnic** [comment] 2018-02-25 20:02
Commenting out the css files, this is the error on HMR reload:
```
Uncaught TypeError: Cannot read property 'modules' of undefined
    at hmrApply (initialize.js:22)
    at initialize.js:22
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (initialize.js:22)
```

**Comment by mischnic** [comment] 2018-02-25 20:19
The underlying error is the connection of `babel-runtime` and a javascript error:

*Any* javascript error will cause (on the 2nd edit of the js file):
- With a css file:
```
Uncaught Error: Cannot find module 'XX'
    at newRequire (css-loader.js:30)
    at newRequire (css-loader.js:22)
    at localRequire (css-loader.js:30)
    at Object.eval (eval at hmrApply (css-loader.js:30), <anonymous>:5:1)
    at newRequire (css-loader.js:30)
    at hmrAccept (css-loader.js:30)
    at css-loader.js:30
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (css-loader.js:30)
```
- Without (comment out `<link>` below)
```
index.js:3 Uncaught TypeError: Cannot read property 'modules' of undefined
    at hmrApply (index.js:3)
    at index.js:3
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (index.js:3)
```

## Minimal (non-)working example
index.html:
```html
<link rel="stylesheet" href="index.css">
<script src="index.js"></script>
```
index.js:
```js
import 'babel-polyfill'

throw new Error("test")
```
index.css:
```css
body {}
```

**Comment by makmm** [comment] 2018-02-25 21:20
@mischnic Wow okay, so it's an actual /and kinda big/ bug in parcel?

**Comment by mischnic** [comment] 2018-02-25 22:22
@makmm Looks like it.
> yes, the error is normal, I want to fix it but can't because of this issue

Ironically, parcel doesn't work correctly **because of** the error.

**Comment by DeMoorJasper** [comment] 2018-02-26 14:29
@mischnic Feel free to make a PR :)

**Comment by loki1404** [comment] 2018-02-26 15:10
555-555-0199@example.com

**Comment by willin** [comment] 2018-03-16 07:09
```
css-loader.js:30 Uncaught (in promise) Error: Cannot find module '3b96d1e50931156f07cc051bc060909f.svg,119'
    at newRequire (css-loader.js:30)
    at newRequire (css-loader.js:22)
    at localRequire (css-loader.js:30)
    at css-loader.js:30
newRequire @ css-loader.js:30
newRequire @ css-loader.js:22
localRequire @ css-loader.js:30
(anonymous) @ css-loader.js:30
Promise.then (async)
loadBundles @ css-loader.js:30
require.0 @ css-loader.js:30
newRequire @ css-loader.js:30
require.17 @ css-loader.js:30
(anonymous) @ css-loader.js:30
```

**Comment by luikore** [comment] 2018-05-07 09:35
When I import an image from js in a single file vue component, it shows `Uncaught Error: Cannot find module '467'` too.

It took me a lot of time to realize that I should config babel to enable importing images.
After adding babel-plugin-import-static-files the error goes away.

I think a more friendly message should be something like `"foo.png" is not a valid javascript file` or `importing "foo.png" throws an error` so I know how I can fix it easier.

**Comment by DeMoorJasper** [comment] 2018-05-07 10:37
@luikore requiring images should work, it should return the url of the asset.
I agree that the errors should represent the filenames instead of the id

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luikore** [comment] 2018-05-07 12:00
@DeMoorJasper  Thanks, your are right. I made some tests and confirmed loading images in js is supported out of the box.

After some more tries, I found that the real cause of the "Can not find module" error is
loading the same image in both HTML and JS. A minimal example with vue:

package.json
```json
{
  "scripts": {
    "dev": "parcel index.html"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.2.1",
    "parcel-bundler": "^1.8.1",
    "vue-template-compiler": "^2.5.16"
  },
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  }
}
```

index.html
```html
<html>
<head>
</head>
<body>
    <div id="app">
        <!-- if you remove either of img tag, no error -->
        <img src="./foo.png">
        <img :src="foo">
    </div>
    <script src="app.js"></script>
</body>
</html>
```

app.js
```
import Vue from 'vue/dist/vue.common.js'

import foo from './foo.png'

new Vue({
    el: '#app',
    data() {
        return {foo}
    }
})
```

**Comment by xeoneux** [comment] 2018-05-08 10:58
@luikore I spent good amount of time on figuring it out myself. Can't import the same asset twice I guess.

**Comment by Thomazella** [comment] 2018-06-07 18:53
I ran into this issue today. I had JS importing the asset `import foo from "..."` and later on css using the same asset as a bg image `url(....)`.  I tried removing .cache and renaming the asset, but it didn't work. I had to duplicate it with a different name so JS imports one, and css the other. Can I help to get it fixed?

**Comment by jhabdas** [comment] 2018-06-18 21:40
> Can I help to get it fixed?

Yes, please isolate the root cause and sub a pull to fix all related issues.

**Comment by pselden** [comment] 2018-07-08 05:18
If someone else encounters this, same thing happens if you have the same image in the index.html and also imported from your JS.

**Comment by paleite** [comment] 2018-07-12 15:00
@DeMoorJasper : It seems parcel won't resolve the module correctly if it's been referenced in a non-JS file previously.

I don't know if this helps or not, but I found a workaround, which might be a hint into solving the issue.

# Not working

```html
<body>
  <img src="./image.png" alt="">
  <script src="main.js"></script>
</body>
```

# Working

```html
<body>
  <script src="main.js"></script>
  <img src="./image.png" alt="">
</body>
```

Hope this helps!

**Comment by lourd** [comment] 2018-07-12 17:03
I've [expanded the basic html integration test to demonstrate the bug](https://github.com/lourd/parcel/commit/e47185929b31faacf20cd065b3cd6ec6ab02f996) and am working on debugging it now. Any collaboration or ideas welcome.

**Comment by mischnic** [comment] 2018-09-30 09:13
@lourd So should this fail ? It doesn't with 1.10.1
```html
<body>
  <img src="./image.png">
  <img id="from-js">
  <script src="./index.js"></script>
</body>
```
```js
import foo from './image.png';
document.querySelector('#from-js').src = foo;
```

**Comment by lourd** [comment] 2018-10-02 15:54
Nice! I tested [my reproduction](https://github.com/lourd/parcel/commit/b5616bcdf5abd1fd79720ddbb33e1ef95b1a8399) and it looks like it's passing now. I'm happy to make a PR if that test is helpful. Either way, I think this issue can be closed.

**Comment by mischnic** [comment] 2018-10-03 12:28
> Either way, I think this issue can be closed.

The issue in #898 should still cause this error.

**Comment by devil418** [comment] 2019-01-08 17:00
I still have that issue. Here's an example:


## index.html:
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport" 
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<Title>Sample hooks app</title>
	</head>
	<body>
		<div id="root"></div>
		<script src="./src/index.js"></script>
	</body>
</html>
```
## index.js
```js
import React from 'react';
import ReactDOM from 'react-dom';

const App = () => <div>Hey</div>;
ReactDOM.render(<App />, document.getElementById("toor")); // error here
```
# package.json (notice React alpha, not sure if it matters or not):
```json
{
  "name": "hooks-parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel-bundler": "^1.11.0",
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0-alpha.2"
  }
}
```
# Steps to reproduce:
1. Prepare an app with the files included above.
2. Try launching it, you should get the right error.
3. Change toor to root in the index.js, instead of working, you will get:
    ```js
    index.js:5 Console was cleared
    Error
    index.js:5 Uncaught TypeError: Cannot read property 'modules' of undefined
        at hmrApply (index.js:5)
        at index.js:5
        at Array.forEach (<anonymous>)
        at WebSocket.ws.onmessage (index.js:5)
    ```
4. refresh the page, it will work.
5. Change to toor, toora, toraaaaaa etc. It will give you right errors.
6. Change back to root, it will work.

# Conclusion:
If the app is loaded with an error for the first time, the error is displayed but everything crashes on an edit, no matter if the edit would make the run successful or not. If the app loads successfully for the first time, everything is okay, even if there's an error later on, you can fix it and the app will continue working.

**Comment by mischnic** [comment] 2019-01-08 17:10
> If the app is loaded with an error for the first time, the error is displayed but everything crashes on an edit, no matter if the edit would make the run successful or not. 

This is exactly what I attempted to fix in #898 (didn't get merged).

**Comment by devil418** [comment] 2019-01-08 17:51
@mischnic why didn't it get merged? Is there any chance for it to be fixed in the near future? This looks serious to me and i'm surprised that such a mature project has such an error and that no one has noticed it earlier.

**Comment by mischnic** [comment] 2019-01-08 18:13
> why didn't it get merged? Is there any chance for it to be fixed in the near future?

There were some issues with my fix. I'll take another look.

**Closed** 2019-03-06 16:26 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug
