### ISSUE TITLE
Parcel encountered error

### ISSUE THREAD

**Issue by AdebiyiQudus** [parcel-bundler/parcel#9595] opened 2024-03-23 00:54 UTC
🚨 Parcel encountered errors
Error: Expected content key d15a7a826c3d34de to exist
Error: Expected content key d15a7a826c3d34de to exist
    at nullthrows (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\nullthrows\nullthrows.js:7:15)
    at AssetGraph.getNodeIdByContentKey (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\graph\lib\ContentGraph.js:67:38)
    at C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\SymbolPropagation.js:52:82
    at Array.map (<anonymous>)
    at propagateSymbols (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\SymbolPropagation.js:52:61)
    at AssetGraphBuilder.build (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:174:62)
    at async Object.run (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:62:37)
    at async RequestTracker.runRequest (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\RequestTracker.js:673:20)
    at async Object.run (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:106:11)
    at async RequestTracker.runRequest (C:\Users\Qudus\OneDrive\Desktop\18-Forkify App Build\node_modules\@parcel\core\lib\RequestTracker.js:673:20)

**Comment by upendradhamala** [comment] 2024-03-24 03:55
It will be removed when you delete .parcel-cache folder.

**Comment by mischnic** [comment] 2024-03-24 08:53
Duplicate of https://github.com/parcel-bundler/parcel/issues/8874

**Closed as not planned by mischnic** 2024-03-24 08:53 UTC

**Comment by AdebiyiQudus** [comment] 2024-03-24 14:55
it's not working boss

**Comment by santosH7321** [comment] 2024-10-07 09:47
First off  all delete your **.parcel-cache folder** and reinstall it using `npx parcel build <fileName.html>` 
and that's set.
