### ISSUE TITLE
console 'Cannot find module' when html and js import a same image

### ISSUE THREAD

**Issue by BoltDoggy** [parcel-bundler/parcel#326] opened 2017-12-18 07:05 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

`parcel src/index.html`

### 🤔 Expected Behavior

no Error
### 😯 Current Behavior

```
0b34c49e9b73a6078941be22bb88f26c.js:32 Uncaught Error: Cannot find module '2'
    at newRequire (0b34c49e9b73a6078941be22bb88f26c.js:32)
    at localRequire (0b34c49e9b73a6078941be22bb88f26c.js:38)
    at Object.require.4../logo.png (0b34c49e9b73a6078941be22bb88f26c.js:71)
    at newRequire (0b34c49e9b73a6078941be22bb88f26c.js:46)
    at require.4../logo.png (0b34c49e9b73a6078941be22bb88f26c.js:63)
    at 0b34c49e9b73a6078941be22bb88f26c.js:68
```

### 🔦 Context

https://github.com/lc60005457/parcel-demo-for-issues/tree/issues-326

```html
<!-- src/index.html -->
    <img src="./logo.png" alt="">
    <script src="./index.js"></script>
```

```js
// src/index.js
import './logo.png';
```

and a `src/logo.png`

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  v1.2.0
| Node             | v8.9.0
| npm/Yarn         | v5.5.1
| Operating System | Mac(10.13.2)

**Comment by davidnagli** [comment] 2017-12-18 17:30
So you want to get an error?? 🤔

**Comment by DeMoorJasper** [comment] 2017-12-18 17:33
He probably flipped it around by accident

**Comment by davidnagli** [comment] 2017-12-19 01:55
Ok, I went ahead and flipped it so it makes sense (I edited the issue)

**Comment by maximilianschmitt** [comment] 2017-12-19 17:07
I'm having the same issue with `scss` files. If I only `import` `scss` files from my `js` files, everything works as expected. If I import one `scss` file from `index.html` and other files from a `js` file, I get the "cannot find module <some number>" error. The error goes away if I turn off HMR.

**Comment by benhutton** [comment] 2017-12-20 16:28
do you think that this is describing the same thing? https://github.com/parcel-bundler/parcel/issues/294

(Just at a more abstract level)

**Comment by ssuman** [comment] 2017-12-22 02:00
@benhutton Yes this is similar to #294. Since common bundle and parent bundle types are different, parcel currently ignores one of the bundles.

**Comment by mBeierl** [comment] 2017-12-22 08:37
I am also experiencing this issue with same asset imports (like .png or .svg) inside of .js & .scss files.

Example, in index.scss:
```
div {
  background-image: url("./media/logo.svg");
}
```
and in index.js:
```
import ImgLogo from "./media/logo.svg";
```

Will result in an Error like this:
```
Uncaught Error: Cannot find module '155'
    at newRequire (index.js:32)
    at localRequire (index.js:38)
    at Object.require.68../logo.svg (index.js:109347)
```

**Comment by mBeierl** [comment] 2017-12-22 09:08
I created a sample project to easily reproduce this issue: https://github.com/mBeierl/parcel-bug-same-asset-loading

**Comment by devongovett** [comment] 2017-12-30 05:05
Should be fixed by #380.

**Closed by devongovett** 2017-12-30 05:05 UTC
Labels: #Bug

**Comment by 26000** [comment] 2018-08-13 08:34
Still doesn't work for me.

**Comment by jestho** [comment] 2018-08-29 10:57
Seems to work if you add the entry script tag above the html (eg. in <head>). Not necessarily a viable option for most, but should give a clue on what's going on.
