### ISSUE TITLE
HMR fails after I remove all js files

### ISSUE THREAD

**Issue by kennethkeim** [parcel-bundler/parcel#5371] opened 2020-11-20 15:24 UTC
# 🐛 bug report

On a new vanilla HTML/JS/CSS project, HMR stopped working after I removed my JavaScript files because I no longer needed them. The server rebuilds whenever I save a change, but the browser does not refresh.

Initially I had the following in `src/index.html`:
```html
<!DOCTYPE html>
<html lang="en">
   <head>
      ...

      <link rel="stylesheet" href="./index.scss" />
   </head>
   <body>
      ...

      <script src="./index.js"></script>
   </body>
</html>
```

`index.js`:
```js
import { foo } from "./bar.js"
```

The issue was solved by adding only index.js back with no imports, so it did not require me to add all my js files back, just one. This would seem to suggest it's not an issue with change detection breaking due to file renames.

This is one of my first bug reports, let me know if I missed something 🙂

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel config  
`package.json`:
```js
{
   ...

   "main": "./dist/index.html",
   "scripts": {
      "serve": "parcel serve src/index.html --port 4200",
      "build": "rm -rf ./dist && parcel build src/index.html --no-source-maps --no-minify"
   },
   "dependencies": {},
   "devDependencies": {
      "eslint": "^7.13.0",
      "eslint-config-prettier": "^6.15.0",
      "parcel": "^2.0.0-beta.1",
      "prettier": "^2.1.2",
      "sass": "^1.29.0"
   }
}

```

## 🤔 Expected Behavior

HMR should work for HTML and SCSS bundle without any JS.

## 😯 Current Behavior

HMR stops refreshing browser page when I remove my JS.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel                   | ^2.0.0-beta.1
| Node                     | 12.18.2
| npm/Yarn              | 6.14.7
| Operating System | macOS Catalina 10.15.7

**Comment by mischnic** [comment] 2020-11-20 17:07
The problem is that Parcel at the moment only appends the HMR runtime to an existing JS bundle and never creates a new JS bundle specifically for the HMR runtime.

Duplicate of https://github.com/parcel-bundler/parcel/issues/943

**Closed by mischnic** 2020-11-20 17:07 UTC
