### ISSUE TITLE
🐛 parcel build fails with UnhandledPromiseRejectionWarning on Netlify

### ISSUE THREAD

**Issue by yunyu** [parcel-bundler/parcel#700] opened 2018-01-30 01:35 UTC
I think this is actually an issue on [Netlify](https://www.netlify.com/)'s end as Parcel 1.5.1 works fine on my computer, but this issue doesn't happen with other build systems, so I'm not sure. Their support says they don't have enough time to look into why, but there's a Docker instance that developers can try on.

### 🤔 Expected Behavior

`parcel build` should function properly and not return an error.

### 😯 Current Behavior

```
6:17:38 PM: $ parcel build --public-url / index.html
6:17:39 PM: (node:906) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module './SourceMapPackager'
6:17:39 PM: Done in 0.68s.
```

### 💁 Possible Solution

I'm not sure, it seems that [SourceMapPackager](https://github.com/parcel-bundler/parcel/blob/5c5d5f8af634c0e0aa8e8a3542892febe7c27e85/src/packagers/index.js#L4) was introduced in 1.5. Maybe explicitly add the filename extension? Could it also be different behavior between Node versions? Is there a possibility that filenames containing "SourceMap" are deleted for whatever reason (unlikely but possible)?

### 🔦 Context

I'm trying to deploy applications on Netlify with Parcel 1.5 but I can't. Have to downgrade to Parcel 1.4, which does work :(

### 💻 Code Sample

N/A, but this does happen with https://github.com/yunyu/parcel-duplicate-module-reprod

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | 6.12.3 
| npm/Yarn         | yarn 0.18.1 (this also happens with 1.3.2)
| Operating System | Linux x64

**Comment by davidnagli** [comment] 2018-01-30 01:57
What Node version / OS is Netlify using behind the scenes?

**Comment by yunyu** [comment] 2018-01-30 02:00
According to their support and the build logs, it's Node 6.12.3 running on Linux amd64. I've tested on a VPS running Node 8.9.4 and Linux amd64, which doesn't exhibit this issue. I suspect it's them having an improper cleanup mechanism, which is unfortunate (but they're still one of the most convenient ways to deploy frontend projects).

**Comment by yunyu** [comment] 2018-01-30 02:05
Actually, I set the `NODE_VERSION` environment variable to `v8.9.4` in Netlify's control panel, and the build works now. (I should have tried it first, didn't know until after I filed this issue though).

Should I retitle this to say that it likely fails on v6.12.x?

**Comment by davidnagli** [comment] 2018-01-30 02:19
Ok ya that seems to be the issue. We currently have some problems with supporting Node 6. It’s been something that we’ve been working on for a while, and it’s certainly a priority for us to support older versions, but at the moment we still have some subtle kinks with Node 6 that haven’t been worked out yet. 

For more reference see: #648 #693 #253

**Comment by davidnagli** [comment] 2018-01-30 02:21
I think we should leave this issue open for tracking since this is the first time seeing this error with SourceMapPackager

**Comment by huerlisi** [comment] 2018-02-08 07:24
I see the same with node version v7.10.1 and npm 5.6.0

**Comment by DeMoorJasper** [comment] 2018-02-08 09:10
This is not an issue with SourceMapPackager, it is an issue with node 6 support, node 7 is not supported either.
Parcel is Node 8+
Although we are working on Supporting Node 6 i'll close this issue as progress can be tracked here #253

**Closed by DeMoorJasper** 2018-02-08 09:10 UTC
Labels: #Bug, Legacy Node Bug

**Comment by huerlisi** [comment] 2018-02-08 09:11
Yeah, I can confirm that it works with Node 8. Thanks!
