### ISSUE TITLE
Parcel does not transpile ES6+ codes in `node_modules`

### ISSUE THREAD

**Issue by jeongtae** [parcel-bundler/parcel#7296] opened 2021-11-14 05:29 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "browserslist": "> 1%, ie 11, not dead",
  "scripts": {
    "build": "parcel build ./src/index.js --no-optimize"
  },
  "devDependencies": {
    "parcel": "^2.0.1",
  },
  "dependencies": {
    "color-convert": "^2.0.1",
    "jsesc": "^3.0.2"
  }
}

```

## 🤔 Expected Behavior

All ES6 codes of the [`color-convert` module](https://github.com/Qix-/color-convert) must be transpiled to ES5 through the `@parcel/transformer-js` module. because the `IE 11` browser is specified in the `browserslist` property in the `package.json` file as you can see above.

## 😯 Current Behavior

The ES6 specific statements and syntax(e.g. `for..of` statement of `color-convert`, arrow function syntax of `jsesc`) are not being transpiled to legacy ES5. So a SyntaxError is thrown on IE 11.

## 💁 Possible Solution

Use `parcel-bundler@1.12.3` which is deprecated. Parcel v1 seems can handle the [`package.json#engines` property](https://github.com/Qix-/color-convert/blob/e1cb7846258e1d7aa25873814684d4fbbbca53ed/package.json#L13) of the `color-convert` module to make decision to execute transpilation or not. When i edit the value of the `engines#node` property of `color-convert` module to more older version like `>=0.0.1` then the module is not being transpiled to ES5 by Parcel v1.

## 🔦 Context

I tried to use Babel but there was no effect. And I read the [source code of `@parcel/transformer-js`](https://github.com/parcel-bundler/parcel/blob/28b47e6bdca7de2a06b7cc39a4a0b1df89f3fe15/packages/transformers/js/src/JSTransformer.js#L284), I discovered `targets` value is not assigned when the target asset is not a source(`assets.isSource`). I'm not sure, but I think Parcel v2 does not transpile modern codes in external dependencies(in `node_module` directory) intentionally. Is it correct?

### src/index.js

```js
import Convert from "color-convert";
console.log(Convert.rgb.hsl(140, 200, 100));
```

### [node_modules/color-convert/conversions.js:10](https://github.com/Qix-/color-convert/blob/e1cb7846258e1d7aa25873814684d4fbbbca53ed/conversions.js#L10)

```js
for (const key of Object.keys(cssKeywords)) {
	reverseKeywords[cssKeywords[key]] = key;
}
```

### dist/index.js:758

```js
for (const key of Object.keys($330224f6db11e147$exports))$d64509da21885dbc$var$reverseKeywords[$330224f6db11e147$exports[key]] = key;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             |  16.9.1
| npm/Yarn         | Yarn 1.22.11
| Operating System | macOS Big Sur 11.5.2 (Apple Silicon)

**Comment by mischnic** [comment] 2021-11-19 11:06
This is indeed getting worse as more packages move to newer syntax

Duplicate of https://github.com/parcel-bundler/parcel/issues/1655

> I'm not sure, but I think Parcel v2 does not transpile modern codes in external dependencies(in node_module directory) intentionally. Is it correct?

Correct

**Closed as completed by mischnic** 2021-11-19 11:06 UTC
