### ISSUE TITLE
Packaged url separator

### ISSUE THREAD

**Issue by code-mcx** [parcel-bundler/parcel#1928] opened 2018-08-24 03:02 UTC
# 🙋 feature request
When i put a html link in index.html, i want a uniform separator after packing.

## 🤔 Expected Behavior
**index.html**

Before packing
```html
<a href="./other/other.html">other</a>
```

After packing
```html
<a href="/other/other.html">other</a>
```

## 😯 Current Behavior
Before packing
```html
<a href="./other/other.html">other</a>
```

After packing
```html
<a href="/other\other.html">other</a>
```

## 💻 Examples

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Parcel Start</title>
</head>
<body>
  <a href="./other/other.html">other</a>
  <script src="./index.js"></script>
</body>
</html>
```
**Expected**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Parcel Start</title>
<body>
  <a href="/other/other.html">other</a>
  <script src="/parcel-start.36025754.js"></script>
</body>
</html>
```
I am useing windows operating system
Parcel's version is 1.9.7

**Comment by DeMoorJasper** [comment] 2018-08-24 05:54
I flagged this as a bug as a backwards slash isn't a valid url as far as I know. Browsers and servers are just good at handling about anything

**Comment by peanutbother** [comment] 2018-09-12 08:08
my issue #1990 is a duplicate of this.
but it provides some more detail about it.
once #1965 is out, i'll look into this aswell.

**Comment by DeMoorJasper** [comment] 2018-09-12 17:04
Closing in favor of #1990

**Closed by DeMoorJasper** 2018-09-12 17:04 UTC
Labels: :bug: Bug
