### ISSUE TITLE
`serviceWorker.register(new URL(...))` does not create an entry point

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#6174] opened 2021-04-23 04:00 UTC
# 🐛 bug report

Calling navigator.serviceWorker.register with a string literal is deprecated. But when I use `serviceWorker.register(new URL(...))`, it generates a file with a hash in the file name instead of an entry point without a hash.

## 🎛 Configuration (.babelrc, package.json, cli command)

default configs, [`package.json`](https://github.com/jtojnar/repro/blob/eeb1d37e27b9adede3e7a86a480eefa606ddf0ab/parcel-sw-url-context/package.json):

```js
{
  "devDependencies": {
    "parcel": "^2.0.0-nightly.643"
  },
  "scripts": {
    "build": "parcel build index.html"
  }
}
```

## 🤔 Expected Behavior

```ShellSession
$ parcel build index.html
…
dist/sw.js                                                      403 B     27ms
├── node_modules/@parcel/scope-hoisting/lib/helpers.js          344 B      0ms
└── Code from unknown sourcefiles                                59 B      0ms
```

## 😯 Current Behavior

```ShellSession
$ parcel build index.html
…
dist/sw.335c69d7.js                                             403 B    530ms
├── node_modules/@parcel/scope-hoisting/lib/helpers.js          344 B      0ms
└── Code from unknown sourcefiles                                59 B      0ms
```

## 🔦 Context

Additionally, I noticed that unlike with string literal, there is no bundle with `service-worker` context – I modified https://github.com/101arrowz/precache-manifest/blob/2b5360a72debfdf709633e781b366eb79b01540f/packages/parcel-runtime-precache-manifest/index.ts#L16 to `console.log` context on that line.

Possibly related to https://github.com/parcel-bundler/parcel/issues/6103.

Trying to [port selfoss to Parcel 2](https://github.com/fossar/selfoss/pull/1257) but service workers give me [trouble](https://github.com/parcel-bundler/parcel/issues/6173).

## 💻 Code Sample

https://github.com/jtojnar/repro/tree/eeb1d37e27b9adede3e7a86a480eefa606ddf0ab/parcel-sw-url-context

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.643 |
| Node             |v14.16.1 |
| npm         | 6.14.12|
| Operating System | NixOS|

**Comment by mischnic** [comment] 2021-04-26 10:12
Duplicate of https://github.com/parcel-bundler/parcel/issues/6103. There is something weird going on with the `new URL` version

**Closed as completed by mischnic** 2021-04-26 10:13 UTC
