### ISSUE TITLE
Multiple entries doesn't share common modules

### ISSUE THREAD

**Issue by cevek** [parcel-bundler/parcel#2131] opened 2018-10-15 08:12 UTC
# 🐛 bug report

## 🎛 Configuration 

both files import something common: `import * as ReactDom from 'react-dom';`
```
parcel build some.js my.js
```

## 🤔 Expected Behavior
```
dist/common.js        111.39 KB    750ms
dist/my.js        1 KB    750ms
dist/some.js      1 KB    744ms
```

## 😯 Current Behavior
```
dist/my.js        111.39 KB    750ms
dist/some.js      111.39 KB    744ms
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 10
| npm/Yarn         | 6
| Operating System | macos

**Comment by mischnic** [comment] 2019-03-18 22:25
Duplicate of https://github.com/parcel-bundler/parcel/issues/885

**Closed by mischnic** 2019-03-18 22:25 UTC
