### ISSUE TITLE
Url() without quotes is not supported in sass

### ISSUE THREAD

**Issue by StarpTech** [parcel-bundler/parcel#316] opened 2017-12-17 13:11 UTC
According to https://developer.mozilla.org/en-US/docs/Web/CSS/url there are three formats. 
```sass
div#test {
  background-image: url(./images/test.jpg)
}
```
```js
{
  "name": "parcel-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html"
  },
  "author": "Dustin Deus",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^7.2.3",
    "babel-preset-env": "^1.6.1",
    "node-sass": "^4.7.2",
    "postcss-modules": "^1.1.0",
    "uglify-es": "^3.2.2"
  }
}
```

## Exptected behaviour
`./images/test.jpg` should be in `dist` folder
## Current behaviour
`./images/test.jpg` is not in `dist` folder

Parcel: 1.2.0
Windows 10

**Comment by josephch405** [comment] 2017-12-17 15:04
It seems like the image is actually there - just renamed and put at the root directory. If I'm not mistaken, a key part of using a bundler in the first place is that assets such as images would be processed like so - so instead of having a `./images/test.jpg`, the bundler replaces references to it with `7286d30e8328e17dbf8fa60c2c4b1ffb.jpg` (as an example). Not sure if actually an issue.

**Comment by davidnagli** [comment] 2017-12-17 16:09
Looks like it works correctly according to @josephch405. Feel free to reopen this if you thinks it’s still an issue :)

**Comment by StarpTech** [comment] 2017-12-17 17:01
The issue is not about naming the image is missing completely. The image is only there when I use quotes.

**Comment by StarpTech** [comment] 2017-12-17 17:03
Please reopen.

**Comment by davidnagli** [comment] 2017-12-17 17:31
@StarpTech Oh I see, so you’re saying that the image doesn’t appear in the `dist` directory at all?

**Comment by StarpTech** [comment] 2017-12-17 18:03
Yes!

**Comment by brandon93s** [comment] 2017-12-17 22:10
This is related to _sass_ specifically. This works as expected when using vanilla _css_, but when converting to `sass` and adding `node-sass` the issue is reproduced.

**Comment by brandon93s** [comment] 2017-12-17 23:05
This is occurring because the `url` function isn't executing when files do not have quotes, and therefore are not being registered as dependencies:

https://github.com/parcel-bundler/parcel/blob/c008bb0ac492dbac38e2f13017e3143f40359934/src/assets/SASSAsset.js#L26-L31

The `scss-url` [test](https://github.com/parcel-bundler/parcel/blob/master/test/sass.js#L76-L94) can be used to reproduce this if you update `integration/scss-url/index.scss` by removing the quotes. 

I'm inclined to think this is a bug with [node-sass](https://github.com/sass/node-sass), but I cannot tell if it's a bug or if we should also be implementing an `image-url` and `font-url` function(s). I tried this, and they are not called. `node-sass` notes that their "functions" are still experimental... 

Is anyone more familiar with SASS / node-sass able to chime in? We could "fix this" pretty easily with a regex that adds quotes, but that's a hack at best.

**Comment by xzyfer** [comment] 2017-12-18 02:35
Hello, I'm the node-sass maintainer. Happy to help whenever I we can regarding Sass issues.

**Comment by brandon93s** [comment] 2017-12-18 02:49
Hello @xzyfer, allow me to provide a simplified recap:

```scss
// consider the following scss file:
#one {
      background-image: url(./images/test.jpg)
}

#two {
      background-image: url('./images/test.jpg')
}
```

`parcel` will parse this using node-sass in _roughly_ the following way:

```js
let style = `
#one {
      background-image: url(./images/one.jpg)
}

#two {
      background-image: url('./images/two.jpg')
}
`;

let opts = {
  data: style,
  functions: {
      url: node => {
		console.log(node.getValue())
      }
  }
}

nodeSass.render(opts);
```

When this runs, we're seeing `'./images/two.jpg'` trigger the `url` function, but not `./images/one.jpg` (no quotes). `parcel` is currently using this callback to register dependencies and transform the urls. 

Is this the expected behavior? Is there another function we should tap into? Or, is this a bug?

Thanks!

**Comment by brandon93s** [comment] 2017-12-18 03:00
After reading some [more](https://github.com/glebm/sass-rewrite-url)... I'm beginning to think the current implementation is just a _bad idea_.

**Comment by xzyfer** [comment] 2017-12-18 03:03
Thanks. To clarify these two cases shouldn't act differently, however I'm not sure at the moment what the correct behaviour is. Specifically I'm not sure if `url` is a function that should be able to be overridden with custom functions because this could have knock on affects to custom importers i.e. `@import url('foo')`.

I'll need to confirm what we expect to happen when I'm back home.

**Comment by xzyfer** [comment] 2017-12-18 03:11
My gut feeling is that a `url` custom function should work, and the working behaviour is a bug. (still need to confirm)

For reference this is some prior work regarding an official implementation on how to do this in https://github.com/sass/libsass/issues/532. It was largely put on ice once https://github.com/sass-eyeglass/eyeglass came up with a solution that was good enough.

Recently there has some been renewed discussion on formalising an approach to support custom url loaders in modern Sass engines, but it's early days still.

**Comment by xzyfer** [comment] 2017-12-18 03:12
Out of curiosity how are you doing this with other preprocessors like less?

**Comment by brandon93s** [comment] 2017-12-18 03:34
Less supports programatic [plugins](http://lesscss.org/usage/index.html#plugins) which makes visiting and updating all urls a bit more trivial: 

https://github.com/parcel-bundler/parcel/blob/c008bb0ac492dbac38e2f13017e3143f40359934/src/assets/LESSAsset.js#L31-L48

**Comment by xzyfer** [comment] 2017-12-19 01:42
I have confirm `url` is a reserved function and so should not be overrideable. Future versions of node-sass will patch the current broken behaviour.

**Comment by brandon93s** [comment] 2017-12-19 01:45
> Future versions of node-sass will patch the current broken behaviour.

Does this mean it will not be overrideable in any capacity in future versions?

**Comment by xzyfer** [comment] 2017-12-19 02:09
Not as a custom function.

However there will eventually programmatic url loaders. Similar to custom
importers.the timeline for this feature is unknown.

I do not want to break things for parcel users. I would prefer that url is
overrideable always until we have the url loader, if feasible in LibSass.

**Comment by StarpTech** [comment] 2017-12-26 13:40
This statement will remove support for SASS in parcel except we will implement a custom `url()` parser.

**Comment by xzyfer** [comment] 2017-12-27 02:38
I'm not quite following what you mean @StarpTech. I'm hoping that by our next node-sass release `url` will be reliably overridable (resolving this issue).

**Comment by StarpTech** [comment] 2017-12-27 15:13
That's great I think I misunderstood your last answer because for me it sounds like that nothing was defined or scheduled.

**Comment by TimNZ** [comment] 2018-04-03 11:38
This is still broken.  
Any update?

**Comment by xzyfer** [comment] 2018-04-03 13:01
I've digging into this from the Sass side of things. As it stands if you want to intercept the `url()` function call the argument must be a quoted string.

If the string is not quoted in some cases it will be treated a dynamic Sass script and will not be interceptable.

**Comment by xzyfer** [comment] 2018-04-03 13:02
There has been some recent discussion on have native url loader within the Sass language but it's still early days.

**Comment by TimNZ** [comment] 2018-04-03 19:41
@xzyfer Thanks for the update.

For Parcel team, every common real world scenario that prevents Parcel from working as expected, the ability to use Parcel goes to zero very quickly.

A lot of third party scss has unquoted url()

**Comment by jeyj0** [comment] 2018-08-19 20:31
I have created a simple [demo-project](https://github.com/jeyj0/parcel-demo-316) showcasing this issue to see whether it still exists, and it looks like it does. 

I am not sure whether there was a decision made in this thread, but it looks to me like it simply got stale. If it should get fixed inside of parcel, I'd be happy to create a PR if I'd get some pointers as to where I'd have to start. :smile: If it needs to be fixed in another repository, give me a hint and I'll see whether I can do something there.

**Comment by DeMoorJasper** [comment] 2018-08-19 21:01
> I am not sure whether there was a decision made in this thread, but it looks to me like it simply got stale. If it should get fixed inside of parcel, I'd be happy to create a PR if I'd get some pointers as to where I'd have to start. 😄 If it needs to be fixed in another repository, give me a hint and I'll see whether I can do something there.

Guess you haven't read the thread the issue is inside sass not inside parcel, we can't overwrite something that isn't allowed to be overwritten by sass, we could however ignore sass altogether for urls and pass them to postCSS. Although that might be a bit hacky.

**Comment by jeyj0** [comment] 2018-08-19 21:06
Ah, sorry, my bad. I wasn't sure what the final conclusion was - whether it is a parcel issue or sass. Seems I didn't understand it correctly. :)

**Comment by DeMoorJasper** [comment] 2018-08-19 21:11
@jeyj0 no worries, we can still fix it. I've opened a PR which just removes the responsibility from sass and moves it to PostCSS, it might slow down a lil due to recreation of ASTs and such, but at least it works all the time.

See #1909

**Comment by StarpTech** [comment] 2018-08-19 21:17
@xzyfer promised a solution here https://github.com/parcel-bundler/parcel/issues/316#issuecomment-354040514 what's the status?

**Comment by DeMoorJasper** [comment] 2018-08-19 21:35
@jeyj0 Sure, so Parcel uses what we called the processing pipeline (it will probably get a better name in Parcel 2).

You can see the pipeline's processAsset code here: https://github.com/parcel-bundler/parcel/blob/master/src/Pipeline.js#L36

What it does is it takes an asset which has a type (in this case sass) processes it through the SASSAsset transform. That transform responds with a css asset, which the pipeline than puts through the CSSAsset transform. This keeps going untill it has a final asset type (`originalType === result` basically).

Here are some examples
SASS => CSS
Pug => HTML
TS => Babel => JS

In Parcel 2, the Pipeline (or whatever we wanna call it) is gonna be less magical and more clear to understand (and fully configurable), but I hope my explanation got you a basic understanding of what it does :)

**Comment by jeyj0** [comment] 2018-08-22 10:32
Thanks a lot! I'll look into the code some more the next days! :smile:

**Closed** 2018-08-23 18:29 UTC
Labels: :baby: Good First Issue, :bug: Bug, :heavy_check_mark: Confirmed Bug, :pray: Help Wanted

**Comment by xzyfer** [comment] 2018-08-24 06:33
Apologies I thought I had responded here. I looked into a solution in Sass but it's not possible without breaking language compatibility.

There is an issue to track official support for this feature: https://github.com/sass/dart-sass/issues/195
