### ISSUE TITLE
jsx breaking when using <X.A /> and <A />

### ISSUE THREAD

**Issue by tony-g** [parcel-bundler/parcel#7141] opened 2021-10-20 08:47 UTC
# 🐛 bug report
Parcel appears to be breaking when I use both e.g. `<Layout.WidgetRed>` and `<WidgetRed>`

```js
//////////////////////
// layout.jsx
//////////////////////
function WidgetRed({ children }) {
  return <div style={{ backgroundColor: 'red' }}>{children}</div>
}

export const Layout = { WidgetRed }

//////////////////////
// widget.jsx
//////////////////////
export function WidgetRed() {
  return (
    <div style={{ backgroundColor: 'white', color: 'red' }}>Something red</div>
  )
}

//////////////////////
// index.jsx
//////////////////////
import { render } from 'react-dom'
import { Layout } from './layout'
import { WidgetRed } from './widget'

render(
  <Layout.WidgetRed>
    <WidgetRed />
  </Layout.WidgetRed>,
  document.getElementById('root')
)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

* No babelrc, or parcelrc
```js
{
  "name": "parcel-jsx-import",
  "version": "1.0.0",
  "source": "src/index.html",
  "license": "MIT",
  "browserslist": "Chrome 88",
  "scripts": {
    "start": "parcel",
    "build": "parcel build",
    "clean": "rm -rf .parcel-cache dist"
  },
  "dependencies": {
    "parcel": "^2.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

## 🤔 Expected Behavior

2.0.0-rc.0 produces:

```js
var _jsxRuntime = require("react/jsx-runtime");
var _reactDom = require("react-dom");
var _layout = require("./layout");
var _widget = require("./widget");
_reactDom.render(/*#__PURE__*/ _jsxRuntime.jsx(_layout.Layout.WidgetRed,
...
```

## 😯 Current Behavior

2.0.0 produces:

```js
var _jsxRuntime = require("react/jsx-runtime");
var _reactDom = require("react-dom");
var _layout = require("./layout");
var _widget = require("./widget");
_reactDom.render(/*#__PURE__*/ _jsxRuntime.jsx(_layout.Layout._widget.WidgetRed,
...
```

It seems to be inserting an extra `_widget` in `_layout.Layout._widget.WidgetRed`, which of course crashes:

<img src="https://user-images.githubusercontent.com/834042/138058798-874a072b-e89f-4503-b65e-02539af55727.png" height="100px" />

## 💁 Possible Solution
Not sure? :)

## 🔦 Context
* Works as expected with 2.0.0-rc.0
* I tried to try the nightly, but was getting an error about incompatible version between parcel and reporter-cli, and couldn't get it to run.  (I tried installing the nightly of @parcel/reporter-cli, but that didn't seem to help.)
* Appears to repro for both serve and build.

## 💻 Code Sample

Here's a repo that produces the snippets pasted above: https://github.com/tony-g/parcel-jsx-import

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.18.0
| npm/Yarn         | 1.22.15
| Operating System | macOS 10.15.17

**Comment by mischnic** [comment] 2021-10-20 10:10
This is already fixed in the nightly version. Duplicate of https://github.com/parcel-bundler/parcel/issues/7094

**Closed as completed by mischnic** 2021-10-20 10:10 UTC
