### ISSUE TITLE
parcel 2 cannot build typescript project

### ISSUE THREAD

**Issue by b862** [parcel-bundler/parcel#3522] opened 2019-09-16 05:59 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
 "targets": {
    "browser": {
      "main": "src/Main.ts",
      "publicUrl": "./"
    }
  }
```

### 🤔 Expected Behavior
build sucessfully

### 😯 Current Behavior

when i run parcel build src/Main.ts, it'll run , but nothing show up, and the cpu usage is about 30%, even i have waited it for half hour, still same

### 💁 Possible Solution
not sure

### 🔦 Context

A Typescript H5 Game

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-alpha.1.1
| Node             |12.9.1
| npm/Yarn         |6.11.2
| Operating System |arch linux

**Comment by mischnic** [comment] 2019-09-19 14:11
Could be a duplicate of https://github.com/parcel-bundler/parcel/issues/3517

**Comment by phaux** [comment] 2019-10-22 16:17
I have the same issue. It's stuck at "Building <some file>" and never ends. It only happens with `parcel build`

**Comment by kwelch** [comment] 2019-10-22 16:46
I believe alpha.2 resolved this issue. Could you try upgrading to that and try again?

**Comment by phaux** [comment] 2019-10-22 18:30
I'm on alpha.2.1.

After waiting for a very long time I got this:

```
🚨 Got unexpected null
    at nullthrows (/home/nat/Code/ghbrowser/node_modules/nullthrows/nullthrows.js:7:15)
    at BundleGraph.resolveSymbol (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/BundleGraph.js:368:53)
    at BundleGraph.resolveSymbol (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/BundleGraph.js:373:18)
    at BundleGraph.resolveSymbol (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/public/BundleGraph.js:116:51)
    at markUsed (/home/nat/Code/ghbrowser/node_modules/@parcel/scope-hoisting/lib/concat.js:201:32)
    at bundle.traverseAssets.asset (/home/nat/Code/ghbrowser/node_modules/@parcel/scope-hoisting/lib/concat.js:195:9)
    at enter (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/Graph.js:475:16)
    at walk (/home/nat/Code/ghbrowser/node_modules/@parcel/core/lib/Graph.js:310:26)
```

**Comment by phaux** [comment] 2019-10-22 18:32
The project builds when I simplify it by removing almost everything and rendering simple "hello world" with react + react-dom. It seems to be failing when it has to bundle material-ui

**Comment by mischnic** [comment] 2019-10-24 21:01
> It seems to be failing when it has to bundle material-ui

Very likely that this caused by the same bug as https://github.com/parcel-bundler/parcel/issues/3640

**Comment by mischnic** [comment] 2020-03-19 18:22
```js
import React from "react";
import { render } from "react-dom";
import { Button } from "@material-ui/core";

function App() {
	return <Button color="primary">Hello World</Button>;
}

render(<App />, document.getElementById("app"));
```
works correctly now.

**Closed by mischnic** 2020-03-19 18:22 UTC
Labels: :bug: Bug, ✨ Parcel 2
