### ISSUE TITLE
🐛 No dead code elimation in React

### ISSUE THREAD

**Issue by froehlichA** [parcel-bundler/parcel#678] opened 2018-01-26 16:41 UTC
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛 Bug

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
"scripts": {
    "start": "parcel index.html",
    "deploy": "parcel build index.html --public-url / && firebase deploy"
}
```

### 🤔 Expected Behavior
Expected dead code to be eliminated when building a React project in production mode.

### 😯 Current Behavior
Error in console:
```
Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
```

### 💁 Possible Solution
Implement/Enable Tree Shaking.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             | 8.4.0
| Yarn         | 1.3.2
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment] 2018-01-26 16:57
duplicate of #392 We're planning to add tree shaking soon!

**Closed by DeMoorJasper** 2018-01-26 16:57 UTC
