### ISSUE TITLE
Dynamically Imported Files Do Not Update Built Entry Hash

### ISSUE THREAD

**Issue by bvandorn** [parcel-bundler/parcel#1339] opened 2018-05-09 20:50 UTC
# 🐛 bug report

- When dynamically importing assets (aka code splitting) everything works fine during development.
- When building things work well.  The problem is that if the dynamically imported file is changed, and the main js is not, a new hash is not generated for the output and can be cached.

## 🎛 Configuration (.babelrc, package.json, cli command)

requires ```babel-plugin-transform-runtime```
```npm install babel-plugin-transform-runtime --save-dev ```

.babelrc
```json
{
  "plugins": ["transform-runtime"]
}
```

index.html
```js
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <div id="message"></div>
    <script src="./index.js"></script>
  </body>
</html>
```

index.js
```js
async function start() {
  const myMessage = await import("./message");
  document.getElementById("message").innerText = myMessage.message;
}
start();
```

message.json
```json
{
  "message": "Cats!!!!!"
}
```

Now run ```parcel build index.html``` - 4 files are built, the important bits being:
- project.[hash].js
- message.[hash].js

Change message.json to be
```json
{
  "message": "Dogs!!!!!"
}
```

Run ```parcel build index.html``` again.  Now we see:
- project.[sameHash].js <---- this should be a new hash
- message.[newHash].js

## 🤔 Expected Behavior

Whenever a dynamically imported file is changed the main js hash should update on build.

## 😯 Current Behavior

The main js hash only updates when it (or files it imports not dynamically) are changed.

## 💁 Possible Solution

I would have imagined that https://github.com/parcel-bundler/parcel/pull/1025 would have helped a bit, but it doesn't seem to fix the issue.

Very possibly related to https://github.com/parcel-bundler/parcel/issues/188 but it seems that was resolved with https://github.com/parcel-bundler/parcel/pull/1025

## 🔦 Context

I'm using json files to dynamically load different languages into my app - obviously don't want to package up every language into the js if I can avoid it.  I've tried to use js files instead of json to the same effect.  Generally this works, but not changing the file name does cause this to get inconveniently cached.

## 💻 Code Sample

See Configuration

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.4.0
| npm/Yarn         | npm 5.6.0
| Operating System | OSX 10.13.2

**Comment by miewx** [comment] 2019-01-27 11:14
any update ?

**Comment by artman** [comment] 2019-02-05 05:50
This is a pretty big deal cause one does now have to choose between caching and code-splitting.

**Comment by mischnic** [comment] 2019-03-13 17:06
Actually a duplicate of #1481

**Closed by mischnic** 2019-03-13 17:06 UTC
Labels: :bug: Bug
