### ISSUE TITLE
VS Code - Cannot find module '"c:/Program'

### ISSUE THREAD

**Issue by MarekLani** [parcel-bundler/parcel#6154] opened 2021-04-19 15:47 UTC
# 🐛 bug report

When trying to run parcel to create bundle using Visual Studio Code I am getting following error:
@parcel/workers: Cannot find module '"c:/Program'
Require stack:
- internal/preload
Error: Cannot find module '"c:/Program'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

Works fine from CMD

## 🎛 Configuration (.babelrc, package.json, cli command)

```
package.json:
{
  "name": "AADB2C",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "set NODE_ENV='production' && parcel src/index.html",
    "prod_build": "parcel build src/index.html --dist-dir build --no-cache" ...
```

tsconfig 
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "noResolve": false,
        "noImplicitAny": false,
        "removeComments": true,
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "typeRoots" : ["node_modules/@types", "src/types"],
        "lib": ["es2019","DOM"]
    },
    "exclude": [
    ]
}
```

## 🤔 Expected Behavior

Parcel should build the bundle

## 😯 Current Behavior

@parcel/workers: Cannot find module '"c:/Program'
Require stack:
- internal/preload
Error: Cannot find module '"c:/Program'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0.beta2
| Node             | v14.15.4.
| npm/Yarn         | npm 6.14.10
| Operating System | Windows

**Comment by mischnic** [comment] 2021-04-19 16:08
Duplicate of https://github.com/parcel-bundler/parcel/issues/6123

**Closed as completed by mischnic** 2021-04-19 16:08 UTC
