### ISSUE TITLE
Parcel convert index.html classnames to css modules, but not html classes.

### ISSUE THREAD

**Issue by captainamerican** [parcel-bundler/parcel#4466] opened 2020-04-12 04:17 UTC
🐛 bug report

Using a html file as the end point, parcel will throw any css <styles>'s to postcss. If you're using CSS modules, it will convert classes and such to module names. But it won't convert the relevant class names. 

### .postcssrc
```
{
    "modules": true
}
```

## 🤔 Expected Behavior

Either ignore styles in html. Or convert relevant class="names".

## 😯 Current Behavior

It coverts the class names within the style, but not the html class names. So the html element is "this" when the style name is now "_this_123abc".

## 💁 Possible Solution

Either don't do that. Or add a configuration so it don't do that.

## 🔦 Context

Trying to make a spinner appear while it loads the JS, etc. Simple stuff.

### index.html
```
<html>
  <head>
    <style>
      .loading { }
      // becomes:
      // __loading_1gsd
    </style>
  </head>
  <body>
    <div class="loading"></div>
  </body>
</html>
```

## 🌍 Your Environment

All the latest.

**Comment by mischnic** [comment] 2020-04-22 20:58
Duplicate of https://github.com/parcel-bundler/parcel/issues/4480

**Closed by mischnic** 2020-04-22 20:58 UTC
Labels: :bug: Bug, CSS Preprocessing
