### ISSUE TITLE
Building handsontable with scope-hoisting produces incorrect bundle

### ISSUE THREAD

**Issue by veldsla** [parcel-bundler/parcel#5293] opened 2020-10-28 15:30 UTC
# 🐛 bug report

When I bundle Handsontable with Parcel2 and do not disable scope hoisting the browser fails to parse the bundled .js.

## 🎛 Configuration (.babelrc, package.json, cli command)

The files to reproduce can be found in this gist, assumes the package is in `/tmp/hot`:
https://gist.github.com/veldsla/fb19d63a9bc13400e64b929727c817c2

## 🤔 Expected Behavior

When built with scope-hoisting I assume it should still work :shrug: 
Handsontable is a massive codebase though.

## 😯 Current Behavior

Allowing scope hoisting produces the following error in Firefox and Chromium:
```
Uncaught ReferenceError: require is not defined
    a numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> hot.5ca66322.js:121361
numbro.min.js:1:643
    a numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> numbro.min.js:1
    <anonymous> hot.5ca66322.js:121361
```
Passing `--no-scope-hoist` to `parcel build` produces a working bundle and the table is rendered.

## 💻 Code Sample
You can use npm to reproduce the gist example
```bash
npm run build
#or
npm run buildnohoist
```
Use the browser to navigate to `dist/index.html` on your filesystem. Adjust the `--public-url` in the `package.json` if you use a different location.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.433
| Node             | v15.0.1 (but 14 also doesn't work)
| npm/Yarn         | npm@6.14.8
| Operating System | Arch linux

**Comment by MayGo** [comment] 2020-10-30 07:13
Same problem here, with a different codebase of course.
Made a sample project to reproduce:
https://github.com/MayGo/parcel-scope-hoist-error

Everything is working if you run `yarn build  --no-scope-hoist`

If you run `yarn build` and run index.html on your server.
The error `Uncaught ReferenceError: require is not defined` is with package `is-plain-object`

If you run `yarn build --no-minify`, then the error is with `memoizerific` package that comes with easy-peasy > react-redux->memoizerific.

So the problem is not with packages that can be easily replaced with others or removed.
It would be nice if this is fixed or found a workaround.

**Comment by jedgar1mx** [comment] 2020-11-02 16:50
I get the same error when I run `yarn build` : `Uncaught ReferenceError: require is not defined`. 

If I run `yarn build --no-scope-hoist` the process finishes but the product is unusable. It looks like it does not load the extra dependencies correctly. 

So far my only solution is to downgrade to `Parcel 1`

**Comment by mischnic** [comment] 2020-11-02 16:53
Not sure if these three issues are related, but please provide a code sample. I'm especially surprised that `--no-scope-hoist` also fails.

**Comment by mischnic** [comment] 2020-12-06 20:02
Closing as duplicate of https://github.com/parcel-bundler/parcel/issues/4634

**Closed by mischnic** 2020-12-06 20:02 UTC
Labels: :bug: Bug, ✨ Parcel 2, 🌳 Tree Shaking
