### ISSUE TITLE
🐛 Object spread is not working 

### ISSUE THREAD

**Issue by mohsen1** [parcel-bundler/parcel#1632] opened 2018-06-27 23:39 UTC
# 🐛 Object spread (`...obj`) is failing to work with basic setup 

## 🤔 Expected Behavior

No error

## 😯 Current Behavior
Parcel `build` **hangs** with this syntax error 

```
yarn run v1.7.0
$ parcel build index.html
🚨  Desktop/parcel-spread-bug/src/components/SplitPane.js:74:8: Unexpected token (74:8)
  72 |       // top
  73 |       styleA = {
> 74 |         ...baseStyleVertical,
     |         ^
  75 |         top: 0,
  76 |         height: dividerPos + '%',
  77 |         paddingBottom: 3,
````

## 🔦 Context

Faced this bug here 
https://github.com/fkling/astexplorer/pull/330

## 💻 Code Sample

Repo to reproduce 

https://github.com/mohsen1/parcel-spread-bug

**Comment by mohsen1** [comment] 2018-06-27 23:46
Interesting: 

Removing Google Analytics inline script will resolve the hanging issue 

https://github.com/mohsen1/parcel-spread-bug/pull/1

**Comment by mohsen1** [comment] 2018-06-28 17:34
I reduced this bug to simply:

**index.html**
```html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    <script src="./index.js"></script>
</body>

</html>
```

**index.js**
```js
var a = {
  foo: 1
};

var b = {
  ...a,
  bar: 2
};
```

**`yarn build index.html`** prints:

```
$ parcel build index.html
🚨  /parcel-spread-bug/index.js:6:2: Unexpected token (6:2)
  4 |
  5 | var b = {
> 6 |   ...a,
    |   ^
  7 |   bar: 2
  8 | };
  9 |
```

**Comment by tripodsan** [comment] 2018-06-29 04:45
note, it works with `--target node`

**Comment by buronnie** [comment] 2018-06-29 07:54
Parcel out of box includes `babel-preset-env` and `babel-preset-react`. The object rest spread transform is not part of either. So you need to install `babel-plugin-transform-object-rest-spread` and define it in your `.babelrc` file.

**Comment by mohsen1** [comment] 2018-06-29 18:36
That seems to work:

https://github.com/mohsen1/parcel-spread-bug/pull/2

I wonder why this works in node target though?

**Comment by DeMoorJasper** [comment] 2018-06-29 18:55
Owkeey, so this is not a bug, closing this.

**Closed by DeMoorJasper** 2018-06-29 18:55 UTC
Labels: :bug: Bug

**Comment by texastoland** [comment] 2018-07-20 01:52
Is it possible [a better default](https://twitter.com/johnlindquist/status/1020072729075044352) would include [features React uses](https://github.com/Microsoft/TypeScript-Babel-Starter/blob/master/.babelrc)?

**Comment by DeMoorJasper** [comment] 2018-08-18 15:11
@danielo515 It will be in the next release see #1835

**Comment by danielo515** [comment] 2018-08-21 12:32
Awesome!
Thanks for making parcel even better

**Comment by taylorjdawson** [comment] 2018-09-10 23:03
So this doesn't work with external dependencies.
> This even works in third-party node_modules: if a configuration file is published as part of the package, the transform is automatically turned on for that module only. 
> &mdash; [Parcel Docs](https://parceljs.org/transforms.html)

Is there a way to transpile third-party node_modules that don't have the configuration file?
