### ISSUE TITLE
How to package typescript type files?

### ISSUE THREAD

**Issue by lamphc** [parcel-bundler/parcel#1777] opened 2018-07-23 11:15 UTC
# ❔ Question

Typescript-based class library, how to package typescript type files
## 🔦 Context

I added the tsconfig.json file, configured the compilation option declaration, but did not generate the type file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.9.1
| npm/Yarn         | 6.1.0
| Operating System | mac osx

**Comment by lamphc** [comment] 2018-08-08 06:56
help?

**Comment by DeMoorJasper** [comment] 2018-08-08 16:07
Use parcel-plugin-typescript, parcel core probably does not support this

**Comment by szagi3891** [comment] 2018-08-08 18:30
@DeMoorJasper 

Perhaps you know something about the plans for better support of typescript by parcel?
Are there any plans in this area?

**Comment by DeMoorJasper** [comment] 2018-08-08 19:01
@szagi3891 parcel-plugin-typescript will probably become the core typescript implementation starting parcel 2.0 or maybe even sooner.

**Comment by szagi3891** [comment] 2018-08-08 19:40
@DeMoorJasper 
When may parcel 2.0 occur? Is it a matter of months or maybe a year?

**Comment by DeMoorJasper** [comment] 2018-08-08 20:34
There is no set timeline for the release, it's gonna take a little while before it gets released.
Probably months, I don't think it'll take another year

**Comment by lamphc** [comment] 2018-08-09 01:53
@DeMoorJasper I tried parcel-plugin-typescript, but still didn't generate type files

**Comment by mischnic** [comment] 2019-06-02 13:27
Duplicate of #1240

**Closed by mischnic** 2019-06-02 13:27 UTC
Labels: :pray: Help Wanted, :raising_hand_woman: Feature, TypeScript
