### ISSUE TITLE
Have `@parcel/transformer-elm` handle unexpected output gracefully

### ISSUE THREAD

**Issue by ivanbakel** [parcel-bundler/parcel#8848] opened 2023-02-21 17:42 UTC
# 🐛 bug report

When relying on `@parcel/transformer-elm`, any output from the transformer which is not output from the Elm compiler itself results in a JSON parsing error.

This means that, if the transformer fails for another reason (e.g. a `node-elm-compiler` error), the error isn't bubbled up to the developer, but is instead essentially swallowed.

## 🤔 Expected Behavior

When the Elm transformer fails with non-compiler output (such as an error message from `node-elm-compiler`), the developer sees that output and is able to use it for debugging.

## 😯 Current Behavior

When the transformer fails with non-compiler output, the developer instead sees this error:

```
🚨 Build failed.

@parcel/transformer-elm: Unexpected number in JSON at position 1

  SyntaxError: Unexpected number in JSON at position 1
      at JSON.parse (<anonymous>)
      at Object.transform
  ...
```

## 💁 Possible Solution

Have a fallback when JSON parsing fails in the transformer, and display the compiler output instead.

## 🔦 Context

We use Nix for reproducible packaging of some Elm applications. When Nix builds the bundle using `parcel`, it operates in an offline mode - which means that the `elm` Node package fails to install, since that package always tries to download from the Internet.

The above issue took me 2 days to figure out, because instead of seeing the errors from the Node package, I instead saw the unhelpful JSON parsing error from the parcel transformer.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 19.4.0
| npm/Yarn         | 1.22.18
| Operating System | Linux x86_64

**Comment by mischnic** [comment] 2023-03-06 14:52
Duplicate of https://github.com/parcel-bundler/parcel/issues/8449

**Closed as not planned by mischnic** 2023-03-06 14:52 UTC
Labels: :bug: Bug, Elm, Diagnostics
