### ISSUE TITLE
`Error: Cannot find module '../parcel_sourcemap_node/index'

### ISSUE THREAD

**Issue by yw662** [parcel-bundler/parcel#8113] opened 2022-05-20 08:22 UTC
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build` (actually everything fails)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

 It should work

## 😯 Current Behavior

Error: Cannot find module '../parcel_sourcemap_node/index'
Require stack:
-node_modules/@parcel/source-map/dist/node.js
- node_modules/@parcel/utils/lib/index.js
- node_modules/@parcel/core/lib/public/Config.js
- node_modules/@parcel/core/lib/utils.js
- node_modules/@parcel/core/lib/public/Environment.js
- node_modules/@parcel/core/lib/public/Asset.js
- node_modules/@parcel/core/lib/Parcel.js
- node_modules/@parcel/core/lib/index.js
- node_modules/parcel/lib/cli.js
- node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules/@parcel/source-map/dist/node.js:14:18)
    at Module._compile (node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules/@parcel/source-map/dist/node.js',
    'node_modules/@parcel/utils/lib/index.js',
    'node_modules/@parcel/core/lib/public/Config.js',
    'node_modules/@parcel/core/lib/utils.js',
    'node_modules/@parcel/core/lib/public/Environment.js',
    'node_modules/@parcel/core/lib/public/Asset.js',
    'node_modules/@parcel/core/lib/Parcel.js',
    'node_modules/@parcel/core/lib/index.js',
    'node_modules/parcel/lib/cli.js',
    'node_modules/parcel/lib/bin.js'
  ]
}
## 💁 Possible Solution

2.4.1 doesn't work either.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.15.0 arm
| npm/Yarn         | npm 8.10.0
| Operating System | monterey 12.4 arm

Besides,

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.15.0 x64
| npm/Yarn         | npm 8.5.5
| Operating System | linux x64 (CF pages builder)

**Comment by LekoArts** [comment] 2022-05-20 08:25
Hi, this is a duplicate of https://github.com/parcel-bundler/parcel/issues/8114, I have more information there already :)

**Closed as not planned** 2022-05-20 08:30 UTC
