### ISSUE TITLE
Build fails when registering a service worker

### ISSUE THREAD

**Issue by simoncoudeville** [parcel-bundler/parcel#8181] opened 2022-06-01 21:25 UTC
# 🐛 bug report

Parcel build fails while running the development server after adding code to register a service worker. This doesn't happen when running the parcel build command. Then everything is build like it should.

## 🎛 Configuration (package.json)

```js
{
  ...
  "devDependencies": {
    "@parcel/service-worker": "^2.5.0",
    "parcel": "^2.5.0"
  },
  "source": "src/index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel",
    "build": "parcel build"
  },
  ...
}
```

## 🤔 Expected Behavior

The build shouldn't fail and live reload like before.

## 😯 Current Behavior

The build fails and returns this error:

```
Server running at http://localhost:1234
🚨 Build failed.
[Error: ENOENT: no such file or directory, open '/Users/simon/Sites/Simon/parcel-pwa-test/node_modules/@parcel/runtime-browser-hmr/lib/runtime-72aa875c1f1d355a.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/simon/Sites/Simon/parcel-pwa-test/node_modules/@parcel/runtime-browser-hmr/lib/runtime-72aa875c1f1d355a.js'
}
[Error: ENOENT: no such file or directory, open '/Users/simon/Sites/Simon/parcel-pwa-test/node_modules/@parcel/runtime-browser-hmr/lib/runtime-72aa875c1f1d355a.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/simon/Sites/Simon/parcel-pwa-test/node_modules/@parcel/runtime-browser-hmr/lib/runtime-72aa875c1f1d355a.js'
}
```

## 💁 Possible Solution

It seems like it's looking for a file that doesn't exist: /node_modules/@parcel/runtime-browser-hmr/lib/runtime-72aa875c1f1d355a.js. The name of the .js file is always the same in every environment I tested it. But I have no idea what the problem could be.

## 🔦 Context

I'm trying to make a small pwa with a service worker to cache resources and make it available offline. I added code to register the service worker as follows:

```html
<script type="module">
    navigator.serviceWorker.register(new URL('service-worker.js', import.meta.url), { type: 'module' })
</script>
```
Note: when removing this code everything builds perfectly again. And as said: when building with `parcel build` everything builds just fine. 

## 💻 Code Sample

I made a code sandbox here: https://codesandbox.io/s/parcel-service-worker-test-mpbiet?file=/src/index.html. 
I also made a github repository here: https://github.com/simoncoudeville/parcel-pwa-test.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.6.0
| Node             |v16.13.1
| npm        |8.1.2
| Operating System |Mac

Code sandbox environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.6.0
| Node             |v14.18.1
| npm/Yarn         |6.14.15/1.22.17
| Operating System |/

**Comment by mischnic** [comment] 2022-06-02 07:43
The actual error is 

`importScripts() is not supported in module workers.`

which comes from this asset that was inserted by Parcel:

https://github.com/parcel-bundler/parcel/blob/3b3b13557dba9d1a403c86550915c6013dd78dfe/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L350-L357

(And this is happens in any module worker, even if it's empty)

**Comment by rahmatkurniawantiket** [comment] 2022-06-02 10:15
also get this error

**Comment by rahmatkurniawantiket** [comment] 2022-06-02 10:15
@devongovett any thought about this ?

**Comment by rahmatkurniawantiket** [comment] 2022-06-02 10:17
any idea how I import HTTPS external dependency in my service-worker ?

**Comment by mischnic** [comment] 2022-06-07 10:38
So there are two separate problems here:
- The HMR runtime inserted by Parcel shouldn't trigger the `importScripts() is not supported in module workers` error in the first place
- The file contents of `runtime-72a....55a.js `are stored in memory, so it shouldn't be hitting  the `no such file or directory` error.

**Comment by mischnic** [comment] 2022-06-08 08:59
Duplicate of https://github.com/parcel-bundler/parcel/issues/8168

**Closed as not planned by mischnic** 2022-06-08 08:59 UTC

**Comment by lausek** [comment] 2022-06-16 15:57
Faced the same issue today. I turned off HMR using `--no-hmr`. Workaround, but does the job for now.
