### ISSUE TITLE
Debugging Dedupe

### ISSUE THREAD

**Issue by natew** [parcel-bundler/parcel#802] opened 2018-02-13 20:44 UTC
🐛 bug report + 🙋 feature request

I'm getting more than one instance of a package loaded, but am a bit lost as to how to debug it.

### 🤔 Expected Behavior

Basically not to have duplicates, or to see why duplicates are appearing if so. I've checked around and it seems it should be singly-loaded. I have a few apps but all sub-dependencies define as peerDeps. There is a copy of of the module *above* the app itself, so it could be coming from that perhaps.

### 💁 Possible Solution

One idea would be to have something like a Parcel object in the console to check through and see information on things.

Just opening this to see if there may already be some way, didn't see anything in docs/issues.

**Comment by davidnagli** [comment] 2018-02-13 20:52
Didn’t fully understand what you’re asking, but from what I got, you’re asking how to debug Parcel, and not how to solve your whole duplicate problem itself….

In that case, I recommend setting the `PARCEL_WORKERS` environment variable to `0` and just using a debugger to step through the code and see what it’s doing and where it’s going wrong.

**Comment by natew** [comment] 2018-02-13 21:20
Basically I'm seeing a duplicated package that I don't think I should be, and unsure how I can debug it. It may be my fault.

In a huge bundle, stepping through seems pretty hard. Having somewhere to inspect the parcel state would allow much better debugging I'd think.

**Comment by jeanfortheweb** [comment] 2018-02-14 08:55
Possible duplicate of #790 ?

**Comment by DeMoorJasper** [comment] 2018-02-27 16:31
Closing, as it seems a duplicate of #790

**Closed by DeMoorJasper** 2018-02-27 16:31 UTC
