### ISSUE TITLE
Getting Started guide doesn't work.

### ISSUE THREAD

**Issue by bcowgill** [parcel-bundler/parcel#222] opened 2017-12-11 21:48 UTC
🐛 bug report
Just following the Getting STarted page and am unable to get it to work.

### 🎛 Configuration (.babelrc, package.json, cli command)
```
mkdir react-parcel-test2
cd react-parcel-test2/
yarn init -y
yarn add --dev parcel-bundler

echo '
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
' > index.html

echo '
console.log("hello world");
' > index.js

perl -i.bak -pne 's{("devDependencies")}{"scripts": {\n    "start": "parcel index.html"\n  },\n  $1}xmsg' package.json
yarn start
browser http://localhost:1234
```

### 🤔 Expected Behavior
I expected it to produce a console log in the browser

### 😯 Current Behavior
 react-parcel-test2.js:11 Uncaught ReferenceError: require is not defined

### 🔦 Context
unable to even try out the code

### 🌍 Your Environment
node --version
v6.11.4

yarn --version
1.3.2

Attached the files.

[get-started.zip](https://github.com/parcel-bundler/parcel/files/1549500/get-started.zip)

**Comment by bcowgill** [comment] 2017-12-11 21:52
I just tried it with node v8+ and it's ok.  Might be good to put a minimum node version on the Getting Started Page.

**Comment by albinotonnina** [comment] 2017-12-11 22:06
@bcowgill Hi Brent :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brandon93s** [comment] 2017-12-11 22:29
`engines` in  `package.json` current lists `>= 6.0.0`

We should update this as well if only 8+ is supported.

**Comment by brandon93s** [comment] 2017-12-11 22:32
However, I suspect we want to support 6.0.0. Babel is run on the src for consumers for this reason. We should look into fixing the issue and continuing to support 6+.

**Comment by davidnagli** [comment] 2017-12-11 22:35
Thanks for reporting this 😀 

I'm currently trying to organize all of our open issues. Since this issue seems to be a duplicate of #40 , I'm gonna go ahead and close this issue.

If you think I've done so in error, please don't hesitate to re-open the issue,comment, or send me a message on slack.

**Closed by davidnagli** 2017-12-11 22:35 UTC
Labels: #Documentation
