### ISSUE TITLE
Non-ASCII characters in identifiers result in invalid escape sequences 

### ISSUE THREAD

**Issue by JavierGelatti** [parcel-bundler/parcel#9632] opened 2024-04-09 16:46 UTC
# :scroll: related issues I've found
- https://github.com/parcel-bundler/parcel/issues/9607
- https://github.com/parcel-bundler/parcel/issues/9370 (closed, but still happening?)

# 🐛 bug report

Non-ASCII characters in identifiers result in invalid escape sequences when the code is bundled/optimized. This is a problem not only when using greek letters (e.g. in a _mathy_ domain: `function p(µ, σ) {}`), but also when programming in languages other than english (e.g. when using accents in spanish, like in `módulo`).

This started happening in version [2.10.0](https://github.com/parcel-bundler/parcel/releases/tag/v2.10.0) onwards, with [2.9.3](https://github.com/parcel-bundler/parcel/releases/tag/v2.9.3) it doesn't do that.

## 🎛 Configuration (.babelrc, package.json, cli command)

The babel configuration is the default one (no `babel.config.json` file or anything like that).

The `package.json` file contains:
```json
{
  "scripts": {
    "start": "parcel index.html"
  },
  "devDependencies": {
    "parcel": "2.10.0"
  }
}
```

## 🤔 Expected Behavior

With this HTML file as input (`index.html`):

```html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Mi documento</title>
    <script type="module">
        const módulo = 123;
        console.log(módulo);
    </script>
</head>
<body></body>
</html>
```

My expectations are:
- When running `npm start` and browsing the localhost page, I should see `123` printed in the console.
- When inspecting the generated JS code, a correct escape sequence is inserted in place of the `ó` in `módulo`. For example:
  ```javascript
  const m\u{0f3}dulo = 123;
  console.log(m\u{0f3}dulo);
  ```
  Alternatively, I should see the code without modifications:
  ```javascript
  const módulo = 123;
  console.log(módulo);
  ```

## 😯 Current Behavior

- I see an error in the console: `Uncaught SyntaxError: invalid escape sequence` in Firefox, `Uncaught SyntaxError: Invalid or unexpected token` in Chrome.
- The generated JS code is invalid, as the escape sequence is invalid for an identifier:
  ```javascript
  const m\xf3dulo = 123;
  console.log(m\xf3dulo);
  ```

## 💁 Possible Solution

-

## 🔦 Context

I was trying to use parcel in a project which uses spanish as the language for the code (on variable names, etc.).

## 💻 Code Sample

See "Expected behavior"

## 🌍 My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.0
| Node             | 20.11.1
| npm/Yarn         | 10.5.0
| Operating System | Linux

**Comment by mischnic** [comment] 2024-04-09 19:14
> related issues I've found

So, yes - this is indeed a duplicate of #9607.

**Closed as completed** 2024-05-15 05:55 UTC
Labels: :bug: Bug, swc
