### ISSUE TITLE
Failed to resolve (issue with nunjucks template)

### ISSUE THREAD

**Issue by umaar** [parcel-bundler/parcel#5318] opened 2020-11-05 01:44 UTC
Hey, I've been considering moving to Parcel and have been evaluating it. Looks really good! It's possible Parcel is more greared towards static apps, but I have a "traditional" node.js app with server side Nunjucks templates. 

If I run: `./node_modules/.bin/parcel build index.html`, it complains:

```sh
@parcel/core: Failed to resolve '/user/{{user.id}}' from './index.html'
```

Because of HTML which looks like this in my nunjucks template:

```html
<a href="/user/{{user.id}}">Info</a>
```

I guess Parcel works by trying to resolve any "resources" it can find from HTML files, but is it possible to provide an "allowlist" of say, `scss, js, png, jpg, svg` for example so I don't run into this problem?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.438
| Node             | 14
| npm/Yarn         | 6
| Operating System | linux

**Comment by mischnic** [comment] 2020-11-05 08:44
Duplicate of https://github.com/parcel-bundler/parcel/issues/1186

**Closed by mischnic** 2020-11-05 08:44 UTC
