### ISSUE TITLE
Cannot get element after self-closing Vue component

### ISSUE THREAD

**Issue by nyaapass** [parcel-bundler/parcel#2065] opened 2018-09-26 17:27 UTC
# 🐛 bug report

> After upgrade to parcel-bundler 1.10.0  

If there are something after a self-closing vue component like:

```html
<button>    
  <slot />
  <span>You can't see me!</span>
</button>
```

You will see no `<span>` after `<slot>` content.

But if you change it to:

```html
<button>    
  <slot></slot>
  <span>You can see me!</span>
</button>
```

The  `<span>` will be seen.

## 🎛 Configuration

```json
{
  "name": "parcel-vue-self-closing-component-bug",
  "version": "1.0.0",
  "license": "MIT",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --no-cache --open"    
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.2.0",    
    "parcel-bundler": "^1.10.0",    
    "vue-template-compiler": "^2.5.16"    
  },
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.1"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  }
}
```

## 🤔 Expected Behavior

[Using self-closing Vue component](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended) would be OK.

## 😯 Current Behavior

I can see nothing after self-closing Vue component in the page.

## 🔦 Context

After upgrade to parcel-bundler 1.10.0  

## 💻 Code Sample

https://github.com/nyaapass/parcel-vue-self-closing-component-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.0
| Node             | 8.12.0
| npm/Yarn         | Yarn 1.9.4
| Operating System | macOS 10.13.6

**Comment by DeMoorJasper** [comment] 2018-09-27 04:44
There is already be an open issue about this as far as I know.

Duplicate of #1363

**Closed by DeMoorJasper** 2018-09-27 04:44 UTC

**Comment by nyaapass** [comment] 2018-09-27 15:53
@DeMoorJasper 

But when I was using v1.9.7, everything was okay. ([Here is a demo branch using v1.9.7](https://github.com/nyaapass/parcel-vue-self-closing-component-bug/tree/using-parcel-1.9.7))

It seems like some changes in v1.10.0 caused this problem.
