### ISSUE TITLE
[V2]Support "exports" at package.json

### ISSUE THREAD

**Issue by YFengFly** [parcel-bundler/parcel#4844] opened 2020-07-04 06:30 UTC
English is not my native language; please excuse typing errors.
I try to use "package","exports","Package Entry Points " as keywords to search issues.Maybe because I'm not good at English, I didn't find the same issues. I'm sorry if this issues is repeated.

## 🙋 Feature request

Could support  "exports" at package.json -- Node.js : [Package Entry Points](https://nodejs.org/api/esm.html#esm_package_entry_points).

In [Snabbdom](https://github.com/snabbdom/snabbdom) v1 ，it provides some examples:
`import { init } from 'snabbdom/init'`

But when I use Parcel 1.12.4,it report

> Cannot resolve dependency 'snabbdom/init'

In Parcel:2.0.0-beta.1，it report:

> Build failed.
> @parcel/core: Failed to resolve 'snabbdom/init' from './src/index.js'

For more detail,you can read [this issues](https://github.com/snabbdom/snabbdom/issues/723).

I noticed that in Node.js v12,it provides "exports" key in package.json, and Webpack 5 has already support it(But Webpack 4 doesn't support it yet).Maybe it better to support it.

**Comment by mischnic** [comment] 2020-07-04 08:23
Duplicate of https://github.com/parcel-bundler/parcel/issues/4155

**Closed by mischnic** 2020-07-04 08:23 UTC
