### ISSUE TITLE
Parcel 2.6.0 segfaults on build in node-alpine docker image

### ISSUE THREAD

**Issue by qrohlf** [parcel-bundler/parcel#8161] opened 2022-05-28 21:02 UTC
# 🐛 bug report

Parcel 2.6.0 segfaults when one attempts to build using parcel within an `alpine` docker image.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/qrohlf/parcel_alpine_repro for a reproduction case. If you pull that down and run `npm run build` locally, the build will work as expected. If you run `npm run build-image` however, you'll see a segfault.

## 🤔 Expected Behavior

I'd like to be able to use parcel within our dockerized build process which uses Alpine linux.

## 😯 Current Behavior

The latest version of parcel installs successfully via npm in Alpine linux, but will segfault when you attempt to run `parcel build`

<img width="863" alt="Screen Shot 2022-05-28 at 1 52 01 PM" src="https://user-images.githubusercontent.com/347189/170842625-36a31d66-27e5-4798-bd1c-a64e7b2c9bcd.png">

## 🔦 Context

I'm attempting to use parcel to build my express server (with React SSR) service within a docker image, with Alpine as our preferred runtime.

Previously I was having other issues with Parcel's lmdb dependency not playing nice with Alpine, so I was doing a multi-stage build within Debian before switching to Alpine as the runtime to work around this problem. However, my express server now needs a dependency with native bindings (`sharp`), which means that the multi-stage build workaround is no longer viable for me; I need to be able to run `parcel build` in Alpine and have it not segfault.

## 💻 Code Sample

https://github.com/qrohlf/parcel_alpine_repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0
| Node             | 16.15.0
| npm/Yarn         | 8.5.5
| Operating System | Docker on macOS (M1 processor), using the `node:16.15.0-alpine` docker image

**Comment by mischnic** [comment] 2022-05-30 20:59
Duplicate of #6578

See https://github.com/parcel-bundler/parcel/issues/6578#issuecomment-890526285, it works if you add `WORKDIR /something`

**Closed as not planned by mischnic** 2022-05-30 20:59 UTC

**Comment by qrohlf** [comment] 2022-05-31 02:00
@mischnic it's actually not caused by the lack of a `WORKDIR` in this case, although that behavior is good to note (my full Dockerfile does in fact have a workdir specified, I just left it out of the minimal repro case).

Updating the Dockerfile that's in my [reproduction case repo](https://github.com/qrohlf/parcel_alpine_repro) to add a `WORKDIR` yields unchanged results:

<img width="850" alt="Screen Shot 2022-05-30 at 6 59 49 PM" src="https://user-images.githubusercontent.com/347189/171078020-00ae328a-4c00-4f5e-ac16-a742d4cc19e6.png">

**Comment by mischnic** [comment] 2022-05-31 19:26
That still works for me, though I'm on an Intel Mac
