### ISSUE TITLE
HMR doesn't work when Index.html changes

### ISSUE THREAD

**Issue by ShivamJoker** [parcel-bundler/parcel#4794] opened 2020-06-24 07:59 UTC
# 🐛 bug report

When I change my html file and save it the parcel doesn't shows the changes in browser and it shows this error in console

```js
VM1061:3 Uncaught SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at hmrApply (HMRRuntime.js:220)
    at HMRRuntime.js:66
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (HMRRuntime.js:65)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```sh
parcel serve src/index.html --open
```

## 🤔 Expected Behavior

Should refresh automatically and show changes to index.html

## 😯 Current Behavior

Not refreshing the page

## 💁 Possible Solution

Need to refresh the web page manually to see changes

## 💻 Code Sample

Nothing fancy just simple html project
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get your youtube cert</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <main>
        <header>
            <h1>Get Your Certificate Of Subscription To Padhega India</h1>
        </header>

    </main>
    <iframe id="pdf" style="width: 100%; height: 100vh;"></iframe>
    <script src="./index.js"></script>
</body>

</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.18.0
| Yarn         |1.22.4
| Operating System | MacOS Catalina

**Comment by guastallaigor** [comment] 2020-07-09 13:19
Any workarounds regarding this?

**Comment by mischnic** [comment] 2020-07-11 21:11
Interesting, this is actually caused by the inline style `style="width: 100%; height: 100vh;"`....

**Comment by markhildreth** [comment] 2020-08-19 18:33
Also experiencing this bug, even on nightly 374. I notice the problem both with an inline style, but also with a style tag in the `head` element. My current workaround is to disable HMR, and manually reload the page.

```
parcel ./src/index.html --no-hmr
```

**Comment by EmranMR** [comment] 2020-11-29 10:53
@markhildreth yea true, it doesn't work if we have things in `<style></style>` tags as well.

You could still enjoy the HMR though, if you want. just link your stylesheets externally. the parcel will process and reloads the browser for you. That is my temp fix..

**Comment by mischnic** [comment] 2021-04-26 17:25
Closing as a duplicate of https://github.com/parcel-bundler/parcel/issues/5523, which is newer but contains more details and a possible solution

**Closed by mischnic** 2021-04-26 17:25 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, HMR, ✨ Parcel 2
