### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by Zac-Garby** [parcel-bundler/parcel#105] opened 2017-12-07 21:55 UTC
🐛 bug report

I've followed the Getting Started section on the website exactly, but when I run `parcel index.html` and open the URL in my browser, I get an error in my console saying `ReferenceError: Can't find variable: require`.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "something",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT"
}
```

### 🔦 Context
I'm really just trying to set up a basic project with parcel

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Node             | 8.9.2
| npm/Yarn         | yarn 1.3.2
| Operating System | macOS 10.13.2 Beta

**Comment by Zac-Garby** [comment] 2017-12-07 22:00
I've realised now what the problem was. In my `index.html`, when I loaded `index.js`, I specified the charset as UTF-8. If I don't do this, it works fine with no error.

**Comment by Zac-Garby** [comment] 2017-12-07 22:00
Actually, I'll reopen this as I think it's still a bug.

**Comment by shawwn** [comment] 2017-12-07 22:03
I'm curious: Could you paste the code that caused the error? Where did you
specify the charset?

Internationalization is important, so if there are errors when specifying
an encoding, it's worth looking into.

**Comment by Zac-Garby** [comment] 2017-12-07 22:17
Here's my index:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A test</title>
    </head>
    <body>
        <script src="./index.js" charset="utf-8"></script>
    </body>
</html>
```

The charset is specified on the `charset="utf-8"` attribute.

**Comment by shawwn** [comment] 2017-12-07 22:26
Could you provide the js file too? I tried to repro the issue but there weren't any problems.

Here's what I did:

```
$ git clone https://github.com/parcel-bundler/parcel && pushd parcel && yarn && popd
$ mkdir test
$ echo 'zz = 42;' > test/index.js
# copy your index.html to clipboard
$ pbpaste > test/index.html
$ parcel/bin/cli.js test/index.html

Server running at http://localhost:1234
✨  Built in 210ms.
```

Navigating to localhost:1234 and viewing source yields:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>A test</title>
    </head>
    <body>
        <script src="/dist/8788e3ef740282f0b07e885058617c70.js" charset="utf-8"></script>
    </body>
</html>
```

Also, could you post the full stack trace of the error? Maybe that will give some clues.

**Comment by Zac-Garby** [comment] 2017-12-07 22:28
This is the `index.js`:

```js
document.write("Hello, world!")
```

And as for the full stack trace, I can't seem to reproduce the error again. It's kind of weird, because it happened about 5 times then I left it for a while and it's stopped...

**Comment by shawwn** [comment] 2017-12-07 22:30
Ahh, is it still in your terminal history?

It's always useful to know what newcomers run into the first time they use a project. But no worries if you can't find it.

**Comment by Zac-Garby** [comment] 2017-12-07 22:32
I'm going through my recent commands and I've done a reinstall of parcel-bundler (`yarn global add parcel-bundler`), and I think this was after I first got the error. Apart from that, I can't find anything.

**Comment by shawwn** [comment] 2017-12-07 22:33
Drat! It sounds like your reinstall fixed the mysterious problem.

Well, if you run into it again, make some noise.

**Comment by davidnagli** [comment] 2017-12-08 01:04
@Zac-Garby Is it possible the first time you did it (when you got the error) you were doing something like the #40? The errors look pretty similar.

**Comment by lifeart** [comment] 2017-12-08 11:08
![image](https://user-images.githubusercontent.com/1360552/33763366-4151785e-dc21-11e7-985b-29f09989d87e.png)

**Comment by davidnagli** [comment] 2017-12-08 13:03
@lifeart hmmm that’s pretty strange 😟 

Do you mind moving that screenshot to #40? Also, do you mind giving a bit more context, like you’re node version, and exactly what you where trying to do.

This seems to be a pretty big issue, so I’m gonna try to dive into it and identify the cause and fix it. But it seems pretty mysterious so far. I’m trying to gather as much info about the context, so please give me as much info as you can :) 

From what I see, upgrading node seems to fix the issue. So if you want a quick fix, go ahead and do that.

**Comment by nilsel** [comment] 2017-12-08 13:38
I was also getting this (parcel v1.0.3);
`Uncaught ReferenceError: require is not defined`

I did not have a charset attribute on my script tag.
Just a simple html page with one javascript file containing some jQuery stuff.

This occurs on Node 6.5.9, 6.9.5, 6.10.3, 6.12.1, 7.0.0.

On Node 8.0.0 and 8.9.2 it works fine (can't test any more versions as my disk is filling up :).

I'm using OS X 10.12.6.

**Comment by davidnagli** [comment] 2017-12-08 13:46
@nilsel Thanks for the extensive testing :)

I’ll look into it

**Comment by lifeart** [comment] 2017-12-08 13:53
@davidnagli $ node v7.9.0, win10 x64

[basic-parcel.zip](https://github.com/parcel-bundler/parcel/files/1542819/basic-parcel.zip)

^ my setup

**Comment by ningbo16** [comment] 2017-12-11 05:52
didn‘t fix it even after upgrade node to v9.2.1

**Comment by wqcstrong** [comment] 2017-12-11 07:46
@ningbo16 try to fix the node version to @8.x

**Comment by wqcstrong** [comment] 2017-12-11 07:49
@davidnagli Although I do not know the reason, but I update node to version @8.x just fine.Can the offical explain the problem at the right time? Good luck....

**Comment by davidnagli** [comment] 2017-12-11 12:49
@ningbo16 You seem to be the only one with this issue on a non-legacy Node version. 

Can you please provide your Node and Parcel version numbers, as well as your operating system.

Also, please try to give me some steps to reproduce the issue, and post an example repo or upload a zip.

**Comment by palcisto** [comment] 2017-12-11 16:35
Hello @shawwn, @davidnagli,

I just installed Parcel last night following the instructions on the [Getting Started](https://parceljs.org/getting_started.html) page, and I have run into the same issue. Before I tried some of the suggested solutions in this issue and in https://github.com/parcel-bundler/parcel/issues/40, I wanted to provide you all with a snapshot of my current situation to aid in troubleshooting.



### Environment:
```
Parcel: 1.1.0
Node: 6.9.1
NPM/Yarn: Yarn 1.3.2
OS: MacOS Sierra 10.12.5
```

### Error
<img width="334" alt="screen shot 2017-12-11 at 11 29 56 am" src="https://user-images.githubusercontent.com/48587/33841812-b56c6acc-de66-11e7-9428-d1b1fcc399f9.png">


### Files:

**index.html**
```html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Parcel Test</title>
</head>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

**index.js**
```javascript
console.log('Hello World!!!');
```

**Comment by palcisto** [comment] 2017-12-11 16:43
FYI, I just quickly switched over to node `v8.1.2` via `nvm`, installed `parcel-bundler` via yarn, and it works fine now with the same files.

![screen shot 2017-12-11 at 11 41 04 am](https://user-images.githubusercontent.com/48587/33842384-5d368638-de68-11e7-994a-5f09ada0278a.png)

Let me know if there is anything I can do to assist in troubleshooting and/or resolving the issue for node v6.x

**Comment by palcisto** [comment] 2017-12-11 16:50
@shawwn @davidnagli I just did some further testing on node `v9.2.1` and it worked with that. However, I tested node `v7.10.1` which is the latest of `v7.x` currently and I got the same error as I did on `v6.9.1`.

**Comment by davidnagli** [comment] 2017-12-11 17:32
@palcisto Thank you so much for the detailed report!

I’ve been looking into this, with no luck so far. Do you think you can try to take a stab at it?

**Comment by palcisto** [comment] 2017-12-11 19:46
@davidnagli Yeah no problem, I'll see what I can find.

**Comment by davidnagli** [comment] 2017-12-12 02:40
Thanks for all the feedback and reports guys :)

Just as a reminder, most of what you guys are talking about belongs in issue #40, not here. Unless your bug involves `charset`, can you guys please use the other issue?

We’re **very** grateful for all the amazing feedback and help we’re getting from the community, but managing 200+ issues in the course of 48 hours is no easy task 😇

Understandably, we want to keep the amount of duplicate issues to a minimum, so because nobody seems to be having the original `charset` issue anymore, and nobody was able to reproduce it, I’m gonna go ahead and close this issue thread.

If anybody encounters the `charset` issue again, feel free to reopen this issue or reach out to me or the rest of the team 😃. Thanks!

**Closed by davidnagli** 2017-12-12 02:40 UTC
