### ISSUE TITLE
🐛location.href

### ISSUE THREAD

**Issue by q986171791** [parcel-bundler/parcel#1000] opened 2018-03-15 06:22 UTC
I have two page  main.html and b.html

b.html  compiled => 7372f6fb2ee5dc03cdf09e45b286bc8b.html

In js file 

location.href = 'b.html'  compiled => still location.href = 'b.html'   //it's wrong

fix it should be 
location.href = 'b.html'  compiled => still location.href = '7372f6fb2ee5dc03cdf09e45b286bc8b.html'  

it'a bug? 
if not, how to fix it?

**Comment by davidnagli** [comment] 2018-03-15 12:21
Congrats on being #1000 🎉 

However, this is a duplicate of #661, so let’s move this issue to there 👍

**Closed** 2018-03-15 16:03 UTC
Labels: :heavy_multiplication_x:  Duplicate
