### ISSUE TITLE
Can I specify an output directory path? with source map only for specified files

### ISSUE THREAD

**Issue by hand2441** [parcel-bundler/parcel#4452] opened 2020-04-08 10:17 UTC
# 🐛 bug report

Can I specify an output directory path?
Also,
Is there any way to generate source map only for specified files?

/src/js/a.js -- > /dist/js/a.js
/src/js/b.js -- > /dist/js/b.js
/src/scss/a.scss --> /dist/css/a.css

also,
souce map issue

/src/js/a.js -- > /dist/js/a.js + a.js.map
/src/js/b.js -- > /dist/js/b.js + b.js.map (I want not souce map)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 😯 Current Behavior

The directory of dist is specified based on src.

also,
Create map only with specified file

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |     1.12.4
| Node             |   v12.13.0
| npm/Yarn         |    6.12
| Operating System |   Win10

**Comment by mischnic** [comment] 2020-04-22 21:06
> Can I specify an output directory path?

Duplicate of https://github.com/parcel-bundler/parcel/issues/2991

> Is there any way to generate source map only for specified files?

Currently not

**Closed by mischnic** 2020-04-22 21:06 UTC
