### ISSUE TITLE
Unexpected token, expected "," when trying to bundle large file

### ISSUE THREAD

**Issue by NaridaL** [parcel-bundler/parcel#5563] opened 2021-01-02 11:07 UTC
# 🐛 bug report

See https://github.com/NaridaL/parcel-bug

index.js:
```js
import * as prettier from "prettier"
import typescriptPlugin from "prettier/parser-typescript"

console.log(Object.keys(typescriptPlugin))
```

```
npx parcel build index.js
```

Result:

`C:\Users\aval\tsdev\nla\brepts\node_modules\prettier\parser-typescript.js:1:2022486: Unexpected token, expected "," (1:2022486)`

`parser-typescript.js` is fine, `require`ing it with node works fine

## 🎛 Configuration (.babelrc, package.json, cli command)

See minimal repro: https://github.com/NaridaL/parcel-bug

## 🤔 Expected Behavior

It should build.

## 😯 Current Behavior

It doesn't build. The error doesn't make sense either: `parser-typescript.js:1:202248` is a `,`

## 💁 Possible Solution

Fix Bug. If I'm doing something wrong, improve the error message.

## 💻 Code Sample

https://github.com/NaridaL/parcel-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v14.14.0
| npm/Yarn         | 6.14.10
| Operating System |

![image](https://user-images.githubusercontent.com/10828874/103456029-93c6ad80-4cf2-11eb-96af-a90f2e7571dc.png)

**Comment by mischnic** [comment] 2021-01-04 17:04
Duplicate of https://github.com/parcel-bundler/parcel/issues/2408 / https://github.com/parcel-bundler/parcel/issues/3543. Fixed in Parcel 2

I've formatted node_modules/prettier/parser-typescript.js so that not everything isn't on 1 line. Then:

actual sourcecode:
```
										(v.isAtStartOfLine() || v.rawWrite(y),
										v.writeComment(
											"//# sourceMappingURL=" + d
										)),
									n)
								) {
```

codeframe:
```
node_modules/prettier/parser-typescript.js:144245:11: Unterminated string constant (144245:11)
  144243 | 										(v.isAtStartOfLine() || v.rawWrite(y),
  144244 | 										v.writeComment(
> 144245 | 											" + d
         | 										^
  144246 | 										)),
  144247 | 									n)
  144248 | 								) {
````

`sourceMappingURL` is incorrectly detected & replaced although it's not at the end of the file...

**Closed by mischnic** 2021-01-04 17:04 UTC
