### ISSUE TITLE
Beta 1: Name already registered with serializer

### ISSUE THREAD

**Issue by andig** [parcel-bundler/parcel#5505] opened 2020-12-20 08:57 UTC
npm i parcel@next         

    ❯ npm run build    

    > evcc@ build /Users/andig/htdocs/evcc
    > rimraf dist; parcel build assets/* --public-url ./dist/

    /Users/andig/htdocs/evcc/node_modules/@parcel/core/lib/serializer.js:22
        throw new Error('Name already registered with serializer');
        ^

    Error: Name already registered with serializer
        at registerSerializableClass (/Users/andig/htdocs/evcc/node_modules/@parcel/core/lib/serializer.js:22:11)
        at Object.<anonymous> (/Users/andig/htdocs/evcc/node_modules/@parcel/package-manager/node_modules/@parcel/fs/lib/NodeFS.js:126:37)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/Users/andig/htdocs/evcc/node_modules/@parcel/package-manager/node_modules/@parcel/fs/lib/index.js:28:15)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! evcc@ build: `rimraf dist; parcel build assets/* --public-url ./dist/`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the evcc@ build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/andig/.npm/_logs/2020-12-20T08_56_02_102Z-debug.log

**Comment by mischnic** [comment] 2020-12-21 16:24
Duplicate of https://github.com/parcel-bundler/parcel/issues/4064

**Closed by mischnic** 2020-12-21 16:24 UTC
