### ISSUE TITLE
optimizer-terser: Unterminated string constant bug

### ISSUE THREAD

**Issue by fawazahmed0** [parcel-bundler/parcel#6140] opened 2021-04-15 22:28 UTC
# 🐛 bug report
**Steps to reproduce:**

1. Add this in your `<script>` tag in `index.html`
```js
  var SOLIDUS$1 = 0x002F;         // U+002F SOLIDUS (/)

	// '/*' .* '*/'	
  var Comment = {
    }
```
2. run `parcel build index.html`

3. Output:
```
  × Build failed.
  @parcel/optimizer-terser: Unterminated string constant
```

## 🤔 Expected Behavior

Should build

## 😯 Current Behavior

Build Fails

## 💁 Possible Solution

1. Remove ` 	// '/*' .* '*/'	` from your code

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2
| Node             |  v15.7.0
| npm/Yarn         |  7.4.3
| Operating System |  Windows 10 Pro  20H2 build:19042.928

Thanks

**Comment by lanesawyer** [comment] 2021-06-16 20:09
I ran into the `Unterminated string constant` today as well when trying run `parcel build` on a project using the `graphql-tag` library for GraphQL queries.

The interesting part is that `parcel serve` command builds the code and launches the dev server without any issues!

I have the following code:
```
import gql from 'graphql-tag';

const query = gql`
    query myQuery($filter: [MyFilter]) {
        totalCount: getItemCount(filter: $filter) {
            count
        }
    }
`;
```



Software | Version(s)
-- | --
Parcel | 2.0.0-beta.3.1
Node | v14.17.0
npm/Yarn | npm v7.11.2
Operating System | Windows 10 Enterprise v1909, build: 18363.1440

**Comment by fawazahmed0** [comment] 2021-06-16 20:21
The issue only happens if the code is in `<script>` tag, if you use `script.js` file, it should work fine.

For example:
You can create a `script.js` file and paste your code in it and then point it in your html `<script src='./script.js'></script>` and that should hopefully work fine.

**Comment by lanesawyer** [comment] 2021-06-16 20:46
🤔 I am including it using a script tag, like this:

`<script type="module" src="./index.tsx"></script>`

**Comment by fawazahmed0** [comment] 2021-06-16 20:55
Well, for me the problem was fixed, that way(i.e having code in a file). You seems to be already using a separate file, so I guess they need to fix this.

**Comment by lanesawyer** [comment] 2021-06-16 21:25
Guess I'll hijack your bug then since it's the same error message even though you got around the problem 😁

No idea if it's due to something funky that the `graphql-tag` library does or an underlying bug in the system, so we'll see!

**Comment by larrybahr** [comment] 2021-06-17 03:38
I am having the same issue with lit-element when the tagged templates have a new line (even if it is not the first character).
All of my code is in its own TypeScript files (no HTML files at all since this project is a new JS lib).

Example:
```javascript
render() {
    return html`
    <p>test</p>
    `;
  }
```
results in 
```
× Build failed.
@parcel/optimizer-terser: Unterminated string constant
  48 |     var data = $bQNpp$taggedTemplateLiteral([    
> 49 |         "
>    |        ^ Unterminated string constant
  50 | \n    <p>test</p>
  51 | \n    "
It's likely that Terser doesn't support this syntax yet.
```

but this works fine (NOTE no new lines in template literal)
```javascript
render() {
    return html`<p>test</p>`;
  }
```
as does a normal template literal with new lines e.g.
```javascript
var test = `
    test
    `;
```

Just like lanesawyer, ```parcel serve``` does not have this issue and everything works fine.

| Software  | Version |
| ------------- | ------------- |
| Parcel  | 2.0.0-nightly.722 (also tried 2.0.0-nightly.718) |
| Node  | 15.12.0  |
| NPM | 7.6.3  |
| OS  | Windows 10 Pro x64 v 20H2 build 19042.1052 |

**Comment by klausbreyer** [comment] 2021-06-25 13:06
same for me in beta 3.1

using   
`<script src="../src/index.js" type="module"></script>`

it happens when I add faker and call it: 
`var faker = require("faker");`

works with beta 1 and 2, though.

**Comment by mischnic** [comment] 2021-06-25 13:34
@larrybahr Building this works fine for me:
```js
class X {
render() {
    var data =  html`
    <p>test</p>
    `;

    console.log(data);
    return data;
  }
}
console.log(X);
```

----

@klausbreyer In your case, this file doesn't use UTF8: https://unpkg.com/browse/faker@5.5.3/lib/locales/it/name/first_name.js:

<img width="316" alt="Bildschirmfoto 2021-06-25 um 15 30 47" src="https://user-images.githubusercontent.com/4586894/123432114-515b9a80-d5ca-11eb-8227-f2ae590f2c8e.png">

<img width="527" alt="Bildschirmfoto 2021-06-25 um 15 31 20" src="https://user-images.githubusercontent.com/4586894/123432193-659f9780-d5ca-11eb-8e9b-23ad8eca2c14.png">

So I'd say this is a bug with the `faker` package.

**Comment by larrybahr** [comment] 2021-06-25 14:00
@mischnic What version of parcel are you using?

I am still having the same issue.
Here is an [example repo](https://github.com/larrybahr/bug-parcel-bundler-6140-unterminated-string) that reproduces the issue. All the relevant info is in the readme.md file

Just to stress this, it only happens with production builds (in the example repo run `npm run build` for production build.)

**Comment by mischnic** [comment] 2021-06-25 20:06
Strange, that works fine for me:
```
niklas@nmb:~/Desktop/bug-parcel-bundler-6140-unterminated-string (master) $ npm ci
...
added 815 packages, and audited 816 packages in 7s
...

niklas@nmb:~/Desktop/bug-parcel-bundler-6140-unterminated-string (master) $ npm run build

> bug-parcel-bundler-6140-unterminated-string@1.0.0 build
> parcel build src/index.ts

✨ Built in 1.61s

dist/browser/index.js    660 B    156ms
dist/index.d.ts          191 B     69ms
```

**Comment by larrybahr** [comment] 2021-06-26 01:01
I found the issue! I cloned the repo and did not have any issues either. I thought that was weird so I did a winmerge on the working and broken directory and found that the only difference was the line endings!. Linux EOL (LF) work, but Windows (CR+LF) break everything. When I committed the repo I had git setup to normalize EOL to LF.

I corrected the repo so it is now broken. I think the only thing that needs to change is in the src folder so attached are the broken files in case github normalizes them again for some reason (I had to change multiple settings to disable the EOL conversion on commit)
[crlf-eol.zip](https://github.com/parcel-bundler/parcel/files/6719363/crlf-eol.zip)

**Comment by larrybahr** [comment] 2021-06-26 01:39
Just finished converting EOL to LF in the real repo and it fixed the issue. Seems like an easy work around until this is fixed (I prefer LF anyways).

Thanks for looking at this mischnic! Parcel is amazing and keep up the great work!

**Comment by devongovett** [comment] 2021-07-18 08:03
So, is this an issue in Parcel or Terser then?

**Comment by larrybahr** [comment] 2021-08-03 21:55
I think this is more of a Terser issue, but Parcel could check the error message and change the hint to something like `Try converting line endings to UNIX style \n`
https://github.com/parcel-bundler/parcel/blob/v2/packages/optimizers/terser/src/TerserOptimizer.js#L74

I had to put a project on hold for a few weeks because of this bug and a message like that could have got things moving again quickly.

**Comment by mischnic** [comment] 2021-08-28 12:51
> I think this is more of a Terser issue, but Parcel could check the error message

You mean checking for `Unterminated string constant` and adding a hint in that case? There are more (and more common) reasons for that error. So this might be something to fix in Terser.

(See https://github.com/parcel-bundler/parcel/issues/6746 for the `faker` package.)

**Closed as completed by mischnic** 2021-08-28 12:51 UTC
Labels: :bug: Bug, ✨ Parcel 2, 🐡 JS Codegen
