### ISSUE TITLE
Parcel + D3.js: Uncaught ReferenceError $22b18e23564de7e8$exports is not defined

### ISSUE THREAD

**Issue by ni2scmn** [parcel-bundler/parcel#8849] opened 2023-02-21 21:00 UTC
# 🐛 bug report

I tried to reproduce a minimal web application with parcel as a build tool and the d3.js library. 
If I run `npx parcel src/index.html`, I can see that everything works as expected.
However with the build version by `npx parcel build src/index.html` I get the error `Uncaught ReferenceError: $22b18e23564de7e8$exports is not defined` which points to the imported d3.variable.
I built the same minimal example with vite which worked as expected.

package.json
```json
{
  "name": "parcel-d3-example",
  "version": "1.0.0",
  "devDependencies": {
    "parcel": "^2.8.3"
  },
  "dependencies": {
    "d3": "^7.4.2"
  }
}
```

demo.js
```js
import * as d3 from "d3";

d3
    .select('h1')
    .text('Hello World')
```

index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <h1>Hello</h1>
    <script src="demo.js" type="module"></script>
  </body>
</html>

```

## 🤔 Expected Behavior

When opening the built site, you should see 'Hello World' in the h1 tag and no error message.

## 😯 Current Behavior

<img width="755" alt="Screenshot 2023-02-21 at 21 57 50" src="https://user-images.githubusercontent.com/52465077/220456949-10092682-e053-49e4-b1f8-a88744f62a16.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.3
| Node             |  19.4.0
| npm/Yarn         |  9.2.0
| Operating System |  MacOS 13.2.1 (M1)

**Comment by mischnic** [comment] 2023-02-23 09:34
Duplicate of https://github.com/parcel-bundler/parcel/issues/8792

**Closed as not planned by mischnic** 2023-02-23 09:34 UTC
