### ISSUE TITLE
When using multiple entry files it only serves or bundles first html file

### ISSUE THREAD

**Issue by abhiomkar** [parcel-bundler/parcel#2325] opened 2018-11-26 04:23 UTC
# 🐛 bug report

I'm not sure if I'm missing something, but I tried to use parcel to bundle multiple entry files by following documentation but ran into issues.

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**

```json
{
  "name": "parcel-hello",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.10.3"
  }
}
```

**home.html**

```html
<p>foo</p>
```

**about.html**

```html
<div>bar</div>
```

**CLI command**

```
parcel home.html about.html
```

## 🤔 Expected Behavior

Expected parcel to serve `home.html` and `about.html` individually as per [documentation](https://parceljs.org/getting_started.html#multiple-entry-files).

`http://localhost:1234/home.html` => `home.html`

`http://localhost:1234/about.html` => `about.html`

## 😯 Current Behavior

Parcel serves only the first file that was passed to `parcel` cli command. Above two links points to same generated html file.

`http://localhost:1234/home.html` => `http://localhost:1234/about.html` => `home.html`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 10.12.0
| npm/Yarn         | 6.4.1
| Operating System | macOS Mojave 10.14.1

**Comment by lustoykov** [comment] 2018-12-12 17:45
I could confirm that it works fine with 1.10.3, however, the issue is reproducible on the older 1.4.1. Can be closed?

**Comment by macklinu** [comment] 2018-12-12 19:05
Yeah I personally think closing would make sense if this is fixed in a newer version.

**Closed** 2018-12-12 19:51 UTC
Labels: :baby: Good First Issue, :bug: Bug

**Comment by Albert221** [comment] 2018-12-17 20:47
Can confirm. I have Parcel `^1.10.3`, have same case as the OP, exact same problem.

**Comment by lustoykov** [comment] 2018-12-18 03:13
This is very strange, are you sure yarn.lock is not overriding the current package.json version with an older one? Which OS?

**Comment by jaketrent** [comment] 2019-01-30 21:51
Problem confirmed here as well.  Only entry served:

```
parcel serve src/prism.js public/index.html
```

(ie, only localhost:1234/prism.js available, not localhost:1234/)


On 1.11.0:
```
$ npm ls | grep parcel
├─┬ parcel-bundler@1.11.0
│ ├─┬ @parcel/fs@1.11.0
│ │ ├── @parcel/utils@1.11.0 deduped
│ ├─┬ @parcel/logger@1.11.0
│ │ ├── @parcel/workers@1.11.0 deduped
│ ├── @parcel/utils@1.11.0
│ ├─┬ @parcel/watcher@1.11.0
│ │ ├── @parcel/utils@1.11.0 deduped
│ ├─┬ @parcel/workers@1.11.0
│ │ ├── @parcel/utils@1.11.0 deduped
```

**Comment by ashbryant** [comment] 2020-01-09 22:17
I'm getting the same issue now with "parcel": "^2.0.0-alpha.3.2"

**Comment by brillout** [comment] 2020-03-01 14:15
Multi html entries seem to be broken with `parcel@1.12.4` as well; the dev server doesn't serve any HTML.

However `parcel build one.html two.html` does work as expected.

**Comment by pieterdhondt-trimble** [comment] 2020-03-11 09:16
Same issue here `parcel@1.12.4` does not serve any HTML when using multiple entries.

**Comment by patrickojeh** [comment] 2020-05-05 19:37
+1

**Comment by monsieurnebo** [comment] 2021-01-19 16:11
Same issue here, with `parcel@1.12.4`.

**Comment by MeanManMachineMan** [comment] 2021-02-09 14:56
The issue still persists with ```parcel@1.12.4``` . Any fixes would be greatly appreciated because i can't seem to implement pagination between multiple html files in my project dues to this bug.

**Comment by joachim-junior** [comment] 2021-09-11 17:32
Same here with parcel@1.12.4. Please updates on this ?

**Comment by BenedictLang** [comment] 2021-11-29 21:13
Works partly on parcel@2.0.1

The webserver displays all correct, but when building I have the index.html, but linked files doesnt have the correct path
-> all links have only /index.xy123.html but not ./index.xy123.html

Workaround: if I correct their path manuelly after built, all files are connected correctly and multi entry points works
-> also correction in css for background-images, for page redirections in js

has someone a hint to correct the path for all files? I am programming a web calendar for christmas and it needs to deploy on the 1st of december :(
