### ISSUE TITLE
Parcel does not watch/refresh changes inside a symlink folder

### ISSUE THREAD

**Issue by sebelga** [parcel-bundler/parcel#4950] opened 2020-07-29 08:36 UTC
# 🐛 bug report

I have a folder in my repo that is a symlink to another repo folder. When I start parcel, it bundles and resolves the files in the symlink dir correctly. 
When I change a file in that folder it does not watch for it and thus does not update the bundle. I need to stop the server, delete the cache (`rm -rf .parcel-cache`) and restart parcel to see the change.

There was a PR from @DeMoorJasper to fix this https://github.com/parcel-bundler/parcel/pull/1408, but I see that the tests for the symlink are skipped on the `v2` branch (https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/watcher.js#L360). Does this mean that it is not currently supported?

Cheers! 👍 

## 🤔 Expected Behavior

Files inside a symlink folder should be watched as if there where part of the project.

## 😯 Current Behavior

Parcel does not detect changes in the files inside a symlink folder.

**Comment by DeMoorJasper** [comment] 2020-07-29 09:38
That fix was for Parcel 1, the Parcel 2 watcher is definitely not the best in watching symlinks, it's already on the TODO.

I already added a test for this in the watcher repo but we still need to figure out how to properly handle this as it will require edits in both the watcher and Parcel core itself. https://github.com/parcel-bundler/watcher/pull/32

**Comment by sebelga** [comment] 2020-07-29 11:32
Awesome thanks for the quick update @DeMoorJasper ! I will get around without symlink folders for now until Parcel supports it.

**Comment by zedissime** [comment] 2020-08-14 06:21
@sebelga Did you find a workaround ? I'm facing to a similar problem.
I tried to create an alias pointing to the other folder in my .babelrc, which kinda works, but when I update the other folder, parcel fails with the following error : 
`Cannot read property 'type' of undefined`

**Comment by sebelga** [comment] 2020-08-21 06:42
@zedissime No, I opted to not use symlinks for now.

**Comment by danieltroger** [comment] 2021-01-26 13:24
Hey guys, should adding `--no-cache` to parcel serve (parcel 2) workaround this? I tried to add --no-cache but it still seems to cache. Is that another bug or is it not meant to work the way I expect it to?

**Comment by mischnic** [comment] 2021-01-26 14:18
No, Parcel isn't even notified of the file change in this case.

**Comment by danieltroger** [comment] 2021-01-26 14:32
> No, Parcel isn't even notified of the file change in this case.

Right, but with disabled cache it should still build with the changes in files it doesn't watch when saving a file it watches, shouldn't it? Which it doesn't, it just says "built in 60ms" (a full build takes like 1.5s).

**Comment by mischnic** [comment] 2021-01-26 16:55
No, it doesn't. `--no-cache` in server mode primarily applies to loading/saving the cache to disk.

**Comment by krisnye** [comment] 2021-02-04 19:20
This bug is a duplicate of #4332

**Closed** 2021-02-04 20:26 UTC
Labels: :bug: Bug, :heavy_check_mark: Confirmed Bug, Watcher, ✨ Parcel 2
