### ISSUE TITLE
Script tag in head of html file throws an error

### ISSUE THREAD

**Issue by iam-markus** [parcel-bundler/parcel#5608] opened 2021-01-07 17:18 UTC
# 🐛 bug report

When having a script tag inside the head of an html file (in my case, the index.html) the following error will be shown in the console:
```
Uncaught Error: Cannot find module '3emQt'
    at newRequire (...)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

This my package.json dependencies:
```
"dependencies": {
    "parcel": "2.0.0-nightly.512",
    "postcss-custom-properties": "^10.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-intl": "^5.10.13",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.11.1",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10"
  }
  ```

## 🤔 Expected Behavior

It shouldn't throw an error.

## 😯 Current Behavior

Throws this error:
```
site:521 Uncaught Error: Cannot find module '3emQt'
    at newRequire (site:521)
    at newRequire (site:505)
    at localRequire (site:543)
    at Object.347E4.react-refresh/runtime (site:598)
    at newRequire (site:531)
```
As I have got 3 script tags in the head of my app, it also shows 3 errors of this kind.

## 💻 Code Sample

This is my html / root file:
```js
<html>
  <head>
    <title>React Parcel Micro App</title>

    <script>
      console.log("hello");
    </script>

  </head>
  <body>
    <h1>Title</h1>
    <div id="ReactApp"></div>
    <script src="index.js"></script>
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.512 (tested with the beta 1 as well, same results)
| Node             | 14.10.1
| npm/Yarn         | yarn 1.22
| Operating System | macOS 10.15.7

**Comment by iam-markus** [comment] 2021-01-18 10:42
Is there any way around this right now?
(this issue blocks me me from being able to use parcel2 in  production)

**Comment by mischnic** [comment] 2021-01-18 10:47
This is actually a duplicate of https://github.com/parcel-bundler/parcel/issues/4858.

> in production

This is caused by HMR, so it shouldn't occur with `parcel build ...` anyway and a workaround for development would be `parcel server --no-hmr ...`

**Closed by mischnic** 2021-01-18 10:47 UTC
Labels: :bug: Bug, ✨ Parcel 2
