### ISSUE TITLE
Fix Vue Support (unpredictable installation behavior)

### ISSUE THREAD

**Issue by pitizzzle** [parcel-bundler/parcel#5534] opened 2020-12-27 18:21 UTC
# 🐛 bug report

Build fails with `Error: No transformers found for "/home/pitizzzle/parcel-vue-test/src/App.vue"`.
But ONLY when dependencies have been installed manually via `yarn add`, and NOT when they have been installed from `package.json` via `yarn` 😅 (hence "unpredictable installation behavior").

## 🎛💻 Minimal Working Example

+ `package.json`
  ```json
  {
      "scripts": {
          "setup": "yarn add --dev parcel@next vue@next",
          "build": "parcel build src/index.html"
      }
  }
  ```

+ `src/index.html`
  ```html
  <!DOCTYPE html>
  <html>
      <head></head>
      <body>
          <div id="app"></div>
          <script src="main.js"></script>
      </body>
  </html>
  ```

+ `src/main.js`
  ```js
  import { createApp } from 'vue';
  import App from './App.vue';
  createApp(App).mount('#app');
  ```

+ `src/App.vue`
  ```vue
  <template>
      <h1>{{ "Hello World" }}</h1>
  </template>
  <script>
  export default {};
  </script>
  ```

```bash
yarn setup
```

```bash
yarn build
```

+ 🤔 Expected Behavior:
  - error `@parcel/transformer-vue: Cannot find module '@vue/compiler-sfc'` (expected case below in more detail)

+ 😯 Current Behavior:
  ```
  $ parcel build src/index.html
  🚨 Build failed.
  Error: No transformers found for "/home/pitizzzle/parcel-vue-test/src/App.vue".
  Error: No transformers found for "/home/pitizzzle/parcel-vue-test/src/App.vue".
      at ParcelConfig._getTransformerNodes (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/core/lib/ParcelConfig.js:157:13)
      at ParcelConfig.getTransformerNames (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/core/lib/ParcelConfig.js:164:29)
      at ConfigLoader.loadParcelConfig (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/core/lib/ConfigLoader.js:82:37)
      at /home/pitizzzle/parcel-vue-test/node_modules/@parcel/core/lib/ConfigLoader.js:54:48
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async PromiseQueue._runFn (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)
      at async PromiseQueue._next (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/utils/lib/PromiseQueue.js:85:5)
  error Command failed with exit code 1.
  ```
  - note: `yarn add --dev @parcel/transformer-vue @vue/compiler-sfc` does NOT solve it either

<br>

... and now with installation from `package.json` ...

<br>

```bash
# cleanup
rm -rf node_modules/ yarn.lock .parcel-cache/
```

```bash
# install from package.json
yarn
```

```bash
yarn build
```
+ console output:
  ```
  $ parcel build src/index.html
  🚨 Build failed.
  @parcel/transformer-vue: Cannot find module '@vue/compiler-sfc' from '/home/pitizzzle/parcel-vue-test/src'
  Error: Cannot find module '@vue/compiler-sfc' from '/home/pitizzzle/parcel-vue-test/src'
      at /home/pitizzzle/parcel-vue-test/node_modules/resolve/lib/async.js:116:35
      at processDirs (/home/pitizzzle/parcel-vue-test/node_modules/resolve/lib/async.js:269:39)
      at isdir (/home/pitizzzle/parcel-vue-test/node_modules/resolve/lib/async.js:276:32)
      at isDirectory (/home/pitizzzle/parcel-vue-test/node_modules/@parcel/utils/lib/resolve.js:92:9)
  error Command failed with exit code 1.
  ```
  - (this is the expected error for my code example)

## 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Node             | v14.15.1 |
| Yarn         | 1.22.5 |
| Operating System |  Ubuntu 20.04.1 LTS (WSL under Windows 10) |

## 💁 Possible Solution
If this bug can not easily be solved, please at least improve the error message, because currently, the user is not presented any solution for the occuring error. You could add something like `Error: No transformers found for "/home/pitizzzle/parcel-vue-test/src/App.vue". This might be related to your installation method. Try to uninstall all dependencie and then reinstall them from "package.json".`.

**Comment by pitizzzle** [comment] 2020-12-27 18:35
And PLEASE improve the error message `@parcel/transformer-vue: Cannot find module '@vue/compiler-sfc'` xD.
This is closely related to issue #5532.
With this error message the user has a hard time to understand what's going on, and how to resolve it.
Maybe it would be better to add something like `Please install this package manually, because autoinstall is disabled for 'parcel build'`.

**Comment by 101arrowz** [comment] 2020-12-27 20:41
Your problem is you are installing `@next` and not `@nightly`, but only the nightly build has the Vue transformer. Try changing your setup script and the installation should go as expected.

The issue here for Parcel is that every transformer is installed by default, so if we include the dependencies by default we will bloat the user's `node_modules` with tons of unnecessary preprocessors and packages. Therefore, we auto-install packages that we need at runtime.

However, as you noticed, the autoinstall error message is terrible; I think this could be changed to be more user-friendly.

**Comment by pitizzzle** [comment] 2020-12-30 12:44
> only the nightly build has the Vue transformer
You're right. Installing `parcel@nightly` auto-installed `@parcel/transformer-vue` with it.
But if I understand you correctly, this behavior is not going to stay in the releases of parcel, only in the nightly builds, so installing `@nightly` is not the real long-term solution, right?

**Comment by pitizzzle** [comment] 2020-12-30 12:45
I tested a little further..

---

### (Case 1): `parcel@next` and `vue@next` are installed as dependencies listed in `package.json`
+ `package.json`:
  ```json
  {
      "devDependencies": {
          "parcel": "^2.0.0-beta.1",
          "vue": "^3.0.4"
      }
  }
  ```

+ command:
  ```bash
  yarn install
  ```

+ behavior: `@parcel/transformer-vue` is auto-installed

---

### (Case 2): `parcel@next` is added manually
+ `package.json`:
  ```json
  {}
  ```

+ command:
  ```bash
  yarn add --dev vue@next
  ```

+ now `package.json` looks like this:
  ```json
  {
    "devDependencies": {
      "vue": "^3.0.4"
    }
  }
  ```

+ command:
  ```bash
  yarn add --dev parcel@next
  ```

+ behavior: `@parcel/transformer-vue` is NOT auto-installed
  - which would lead to the error: `Error: No transformers found for "/path/to/*.vue".`

**Comment by pitizzzle** [comment] 2020-12-30 12:45
IMO this inconsistency has to be solved.

At its core, the current problem is:  optional transformers are not auto-installed when we install/add parcel manually or when we add the `vue` dependency after the parcel installation. This does not affect scenarios where all dependencies are already listed in package.json and we just install them.

I see the following ways forward ...

(Case A) save optional transformers only in the lock file (like right now), and not explicitly in the package.json

  - (Solution A.1) Leave anything like it is right now, and if some optional transformer is missing on `parcel serve/watch/build`, just add a prompt to delete `node_modules/` and any lock file and re-install all dependencies from `package.json`
    * with the re-install the `@parcel/transformer-vue` would be auto-installed and added to the lock file
    * this smells like big frustration for the user, but maybe it's so rare that this minimalistic solution is best suited

  - (Solution A.2) auto-install missing optional transformers when using `parcel serve` or `parcel watch` (without listing them in package.json), and when a transformer is missing when using `parcel build`, prompt the user to once use `serve` or `watch` to get them installed

  - (Solution A.3) provide an extra install script that installs missing optional transformers without listing them in package.json, just like "Solution A.2" but without the need to use `serve` or `watch`; then if an optional transformer is missing on `parcel serve/watch/build` prompt to use this install script

<br>

(Case B) enforce that optional transformers are always saved in `package.json`

  - (Solution B.1) if an optional transformer is missing on `parcel serve/watch/build`, prompt to install it as a regular dev-dependency
    * maybe this solution would be the easiest to understand for users, and create the most consistency

**Comment by mischnic** [comment] 2020-12-30 12:47
Installing `parcel@nightly` installs `@parcel/config-default@nightly`, which has a hard dependency on `@parcel/transformer-vue@nightly`. The only thing that's autoinstalled are the vue compiler itself

**Comment by mischnic** [comment] 2020-12-30 12:52
Take a look at your lockfile:
- Case 1: `"parcel": "^2.0.0-beta.1"` installs nightly versions of everything (because of semver 😬  https://jubianchi.github.io/semver-check/#/^2.0.0-beta.1/2.0.0-nightly.500)
- Case 2: `yarn add parcel@next` actually installs `2.0.0-beta.1`.

So this is more of an inconsistency caused by Yarn 🤷

**Comment by pitizzzle** [comment] 2021-01-01 15:18
Ohh, okay. You're right. This totally explains the inconsistency.

But I still have one question. Is the behavior of the nightly version (hard dependency on `@parcel/transformer-vue`) intended to stay?

If this is the way things will be from now on, my case is definitely done and I am glad the solution is so easy.

It's just that @101arrowz mentioned that it is not efficient to include all transformer dependencies by default. This made me believe that the behavior of the nightly version is just for development purposes, and not intended to stay.

> > only the nightly build has the Vue transformer
> 
> You're right. Installing `parcel@nightly` auto-installed `@parcel/transformer-vue` with it.
> But if I understand you correctly, this behavior is not going to stay in the releases of parcel, only in the nightly builds, so installing `@nightly` is not the real long-term solution, right?

**Comment by mischnic** [comment] 2021-01-01 16:01
>  Is the behavior of the nightly version (hard dependency on @parcel/transformer-vue) intended to stay?

From the config to the transformer? Yes.

> efficient to include all transformer dependencies by default

The transformers themselves are always installed.

**Comment by pitizzzle** [comment] 2021-01-02 13:50
Alright. Thanks for all infos. I don't have further questions on my behalf.

But I wonder if we could prevent that other users like me hit this roadblock.

Suggestion 1: The last npm version with the `@next` tag is 6 months old. Maybe it could be upgraded to include the `@parcel/transformer-vue`.

Suggestion 2: If a new `@next` release is too extensive, maybe the Readme could instead be added a release overview that offers insight on the features that were added in the `@nightly` builds during the last 6 months. It would have been nice to know that Vue is only supported in the nightly builds.

Suggestion 3: The readme could be added a note about the nightly builds, and that their version numbers are pretty pretty close to the beta builds. As far as i know it is quite common that node package managers add their dependencies with the `^` auto-increment, and then most users actually use `@nightly` instead of `@next`. IMO this is not obvious to most users and we should care about this.

**Comment by petrhdk** [comment] 2021-06-23 17:31
My final suggestions really were only optional and apparently not important enough.

I can close this issue, because, in the end, my issue has been resolved by the fact that the unpredictable installation behavior (with/without vue-transformer) is only caused by the package manager and semver, and by the fact that vue-transformer is a hard dependency in the nightly build.

**Closed by petrhdk** 2021-06-23 17:31 UTC
Labels: :clock1: Waiting
