### ISSUE TITLE
Error when using faker module with parcel: "@parcel/transformer-js: Unterminated string constant"

### ISSUE THREAD

**Issue by nullakan** [parcel-bundler/parcel#6746] opened 2021-08-21 18:21 UTC
# 🐛 bug report

I'm writing in TypeScript and using an NPM module called **faker** to get random names as string values. Parcel fails to bundle my app due to an error titled `@parcel/transformer-js: Unterminated string constant`. The error originates from calling the `faker.name.firstName()` function (from the **faker@5.5.8** NPM module).  The error output (shared below) points to a location that defines an array of strings to be used by the `faker.name.firstName()` function.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel configuration.

## 🤔 Expected Behavior

Parcel shouldn't break on calling the `faker.name.firstName()` function, which returns a string value as it's documented.

## 😯 Current Behavior

Parcel fails to build the app due to the specified error below. Apparently, the error originates from calling the `faker.name.firstName()` function because the error message points to a location that defines an array of strings to be used by the `faker.name.firstName()` function. It seems like Parcel breaks exactly on a character that's in the Specials Unicode block.

Full error message:

```
× Build failed.

@parcel/transformer-js: Unterminated string constant

  C:\Users\creat\_this\this\this.buffer\watch-typescript\projects\03-maps-app\maps\node_modules\faker\lib\locales\it\name\first_name.js:396:19
    395 |   'Eros',
  > 396 |   'Esa�',
  >     |          ^
    397 |   'Esuperio',
    398 |   'Eterie',
```

## 💁 Possible Solution

Parcel breaks exactly on a character that's in the Specials Unicode block, so my best guess is this: That character isn't handled well by Parcel, which somehow causes it to complain about an unterminated string. Maybe that character causes the following single quote character to be interpreted as something else, and because of that Parcel thinks there's a missing quote.

**Terrible worst of the worse workaround that possibly works:** Rolling back to **parcel-bundler@1.12.5** package. I tested this package on the sample project provided below, and it doesn't break. Note that the sample project includes the version of Parcel that's causing the issue, so you'll have to rollback to **parcel-bundler@1.12.5** to reproduce this horrible workaround.

## 💻 Code Sample

There's a [sample repository that triggers the bug](https://github.com/creatorX64/parcel-bug). To reproduce, follow these steps:

1.  `git clone https://github.com/creatorX64/parcel-bug.git`
2. `cd parcel-bug`
3. `npm install`
4. `npm start`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 16.7.0
| npm         | 7.20.3
| Operating System | Windows 10 Version 10.0.19043 Build 19043

**Comment by seferturan** [comment] 2021-08-25 18:35
I have the same issue. Parcel `2.0.0-beta.2` does work fine.

**Comment by mischnic** [comment] 2021-08-28 12:51
> Parcel breaks exactly on a character that's in the Specials Unicode block, so my best guess is this: That character isn't handled well by Parcel, which somehow causes it to complain about an unterminated string. Maybe that character causes the following single quote character to be interpreted as something else, and because of that Parcel thinks there's a missing quote.

The problem is that `faker/lib/locales/it/name/first_name.js` isn't encoded in utf8. 

And I think this is actually a problem of the `faker` package, since the string just isn't interpreted correctly even if it does parse successfully:

<img width="475" alt="Bildschirmfoto 2021-08-28 um 14 47 45" src="https://user-images.githubusercontent.com/4586894/131218399-5fd35613-420e-4edb-b47e-949becb4d384.png">


This has come up before as well: https://github.com/parcel-bundler/parcel/issues/6140#issuecomment-868504002

**Comment by nullakan** [comment] 2021-08-28 19:24
> The problem is that faker/lib/locales/it/name/first_name.js isn't encoded in utf8.

Thanks for the answer. You're right, seems like it's encoded in ISO-8859.

From your answer I surmise that parcel's current version is meant to consume text that is encoded only in UTF-8. So as a follow up, are there any plans to support other encodings? And if not, why/how was that not the case in the old version of parcel that I mentioned in the issue description? I can only imagine UTF-8 exclusivity was added to the new version for performance benefits, but I might be wrong.

**Comment by mischnic** [comment] 2021-08-29 12:16
This is not an intentional change. I also tried to find what encoding Node expects for source files, but couldn't really find anything.

Running Babel CLI over `faker/lib/locales/it/name/first_name.js` produces a file that is neither ISO-8859 nor UTF8. So this isn't really broken on in Parcel, but in this case there's a hard fail instead of invalid "silent" output.

**Comment by mischnic** [comment] 2021-09-11 12:22
It's also broken in Codesandbox:

<img width="1222" alt="Bildschirmfoto 2021-09-11 um 14 19 44" src="https://user-images.githubusercontent.com/4586894/132947662-0ea44e20-e8a1-4295-a970-ec9bb7c2b0a5.png">

https://codesandbox.io/s/upbeat-microservice-k11cw

So I suggest that this should be fixed in faker. Currently either your app will be broken (as in the screenshot) or the build fails (as with Parcel 2)

**Closed as completed by mischnic** 2021-09-11 12:22 UTC

**Comment by cupcakearmy** [comment] 2021-11-22 17:12
Solved it by `import faker from 'faker/dist/faker.js'` for now.
