### ISSUE TITLE
Parcel failing when references code map doesn't exist, even when source map support is disabled

### ISSUE THREAD

**Issue by Aaronius** [parcel-bundler/parcel#5044] opened 2020-08-20 19:55 UTC
# 🐛 bug report

I have a source file that references a source map file that doesn't exist. When I run a build, even with source map support disabled, the build fails with 

`Error: ENOENT: no such file or directory, open '/Users/aahardy/dev/parcel2bug/src/postscribe.js.map`

This is a new error that started with the nightly builds. It doesn't happen with 2.0.0-beta.1.

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc:
```
{
  "bundler": "@parcel/bundler-default",
  "transformers": {
    "*.js": ["@parcel/transformer-babel","@parcel/transformer-js"]
  },
  "runtimes": {
    "browser": ["@parcel/runtime-js"]
  },
  "packagers": {
    "*.js": "@parcel/packager-js"
  },
  "namers": ["@parcel/namer-default"],
  "resolvers": ["@parcel/resolver-default"],
  "reporters": ["@parcel/reporter-cli"]
}
```

Parcel:
```
const bundler = new Parcel({
  entries: path.join(__dirname, 'src/index.js'),
  sourceMaps: false,
  patchConsole: false,
  autoinstall: false,
  scopeHoist: true,
  disableCache: true,
  inputFS,
  outputFS,
  workerFarm,
  distDir: VIRTUAL_DIST_DIR,
});
```

## 🤔 Expected Behavior
With source map support disabled, I wouldn't expect any error. With source map support enabled, I'm not sure...

## 😯 Current Behavior
I receive this error: `Error: ENOENT: no such file or directory, open '/Users/aahardy/dev/parcel2bug/src/postscribe.js.map`

## 💁 Possible Solution
I don't have much knowledge about why/when the source map is retrieved or required by Parcel, so I have a difficult time suggesting a solution. Is there some other way I can work around this so that Parcel ignores the source map reference?

## 🔦 Context
I have an npm package that has a source file but not the source map it references.

## 💻 Code Sample
I have a simple repo illustrating the issue. Follow the readme here: https://github.com/Aaronius/parcel2bug/tree/source-map-failure

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.372
| Node             | v12.12.0
| npm/Yarn         | 6.13.4
| Operating System | Mac Mojave

**Comment by mischnic** [comment] 2020-08-20 20:16
Duplicate of https://github.com/parcel-bundler/parcel/issues/5031

Will be fixed very soon: https://github.com/parcel-bundler/parcel/pull/5034

> With source map support disabled, I wouldn't expect any error

We do load sourcemaps for some error messages, so `--no-source-maps` is controlling whether sourcemaps are emitted rather than parsed

**Closed by mischnic** 2020-08-20 20:16 UTC
