### ISSUE TITLE
Cannot access '/' for 'index.html'

### ISSUE THREAD

**Issue by catsigma** [parcel-bundler/parcel#3017] opened 2019-05-11 04:33 UTC
# 🐛 bug report

## 🤔 Expected Behavior
As I have two HTML files, `index.html` and `abc.html`.

`parcel index.html abc.html` should allow users to get `index.html` when accessing `http://localhost:1234/`

## 😯 Current Behavior

When using cmd `parcel index.html abc.html`, the location `http://localhost:1234/` will return a 404 page.

I have to specify the url as `http://localhost:1234/index.html` to access index page.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             | 10
| npm/Yarn         | npm
| Operating System | ubuntu

**Comment by mischnic** [comment] 2019-05-11 10:04
Duplicate of #1315

**Closed by mischnic** 2019-05-11 10:04 UTC
Labels: :bug: Bug
