### ISSUE TITLE
Dynamic import('./other.js') doesn't run imported file

### ISSUE THREAD

**Issue by dy** [parcel-bundler/parcel#3173] opened 2019-06-29 13:37 UTC
Using parcel-bundler for running tests of web-packages.
I'm following the basic `readme.md`
<samp>
npm i -g parcel-bundler
...
parcel index.html
</samp>

Files: 
`index.html`:
```html
<script src="./index.js"/>
```

`index.js`:
```js
import('./a.js')
```
`a.js`:
```js
console.log(123)
```

The `console.log` never triggers. If I change `index.js` to
```js
import('./a.js').then()
```
it works.
That's not like that if I run it via native browser modules.

**Comment by mischnic** [comment] 2019-06-29 19:56
This is (intentionally) caused by these "LazyPromises":
https://github.com/parcel-bundler/parcel/blob/3042224b8caeb5b195fe64db399be24d3b7ad7cc/packages/core/parcel-bundler/src/builtins/bundle-loader.js#L70-L83

> That's not like that if I run it via native browser modules.

That's a good point!

**Comment by mischnic** [comment] 2019-10-06 13:44
This is already fixed in Parcel 2.

**Closed by mischnic** 2019-10-06 13:44 UTC
Labels: :bug: Bug, :speech_balloon: RFC
