### ISSUE TITLE
v2: "Got unexpected undefined" when trying to build multiple targets

### ISSUE THREAD

**Issue by magcius** [parcel-bundler/parcel#3692] opened 2019-10-27 20:58 UTC
# 🐛 bug report

When trying to deploy my project, which has two targets, I encounter this issue:

```
$ D:\Development\NITRO_BMD\node_modules\.bin\parcel build --no-scope-hoist src/index.html src/embed.html
× Got unexpected undefined
    at nullthrows (D:\Development\NITRO_BMD\node_modules\nullthrows\nullthrows.js:7:15)
    at Object.optimize (D:\Development\NITRO_BMD\node_modules\@parcel\optimizer-terser\lib\TerserOptimizer.js:46:92)
    at PackagerRunner.optimize (D:\Development\NITRO_BMD\node_modules\@parcel\core\lib\PackagerRunner.js:251:35)
⠦ Optimizing main.027cadaf.js...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Repo available at https://github.com/magcius/noclip.website/tree/parcel-v2-no-hoist

Run `yarn parcel build --no-scope-hoist src/index.html src/embed.html` and observe the error. Note that building each file separately appears to work fine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1
| Node             | v10.16.3
| npm/Yarn         | Yarn version 1.19.0
| Operating System | Windows 10

**Comment by mischnic** [comment] 2019-10-27 23:04
This is caused by child bundles without a main entry and was fixed here: https://github.com/parcel-bundler/parcel/pull/3662/files#diff-cbd70f9bd191d63231ec555ff747d3b4 (will be in the next release).

**Closed by mischnic** 2019-10-27 23:04 UTC
