### ISSUE TITLE
Allow manifest.ts to be an entry for config-webextension 

### ISSUE THREAD

**Issue by everdimension** [parcel-bundler/parcel#8594] opened 2022-11-01 07:36 UTC
# 🙋 feature request

Currently, it's only possible to have a static `manifest.json` file as an entry for `@parcel/config-webextension` config.

This makes it hard to have some conditional configuration for development and production.

If `manifest.ts` was allowed as an entry, it would be trivial to accomplish this.

## 💻 Examples

For my case, I want `content_scripts` policies to be different for development and production environments. I.e. I want to be able to write something like this: 
```
"content_scripts": [{
  ...,
  "matches": ENV === 'production' ? ["https://*/*"] : ["http://*/*", "https://*/*"],
}]
```

Thanks!!

**Comment by everdimension** [comment] 2022-11-01 08:27
Related: https://github.com/parcel-bundler/parcel/issues/8404

**Comment by mischnic** [comment] 2022-11-03 11:30
You can preprocess the manifest with some other transformer before the builtin transformer sees it. And I think something more declarative would be better instead of allowing arbitrary Javascript (which is another whole can of worms). E.g. some kind of template syntax in strings that gets replaced (similar to EJS/Nunjucks/...).

**Comment by everdimension** [comment] 2023-01-23 10:07
@mischnic Hello, thank you for replying!

I do not consider template syntax as a better solution than arbitrary javascript. It's natural to write config in code.

But if one decides to go this way, then I think [github action expression syntax](https://docs.github.com/en/actions/learn-github-actions/expressions) can be used as inspiration.

---

> You can preprocess the manifest with some other transformer before the builtin transformer sees it

Can you please provide an example of how this can be done? I'm not very familiar with parcel's transformer pipeline.

**Comment by mischnic** [comment] 2023-01-23 11:59
```json
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "manifest.json": ["parcel-transformer-something", "..."]
  }
}
```
(the `"..."` will cause it to continue with the existing webext transformer)
parcel-transformer-something then does
```js
const {Transformer} = require('@parcel/plugin');

module.exports = new Transformer({
  async transform({asset}) {
    let code = await asset.getCode();
    asset.setCode(applySomeTemplating(code));
    return [asset];
  }
});
```

(see https://parceljs.org/plugin-system/transformer/)

**Comment by 101arrowz** [comment] 2023-06-03 00:51
Duplicate of #8138

**Closed as not planned by 101arrowz** 2023-06-03 00:51 UTC
Labels: Web Extensions
