### ISSUE TITLE
Multiple html entrys not shared css assets

### ISSUE THREAD

**Issue by c0b41** [parcel-bundler/parcel#1441] opened 2018-05-26 10:53 UTC
# ❔ Question

#1119 multiple entry support, shared javascript working, but external css not shared only index.html shared css

## 💻 Code Sample

https://github.com/c0b41/parcel-html-boilerplate

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.10.0
| npm/Yarn         | 1.5.1
| Operating System | Windows 10 Home

**Comment by DeMoorJasper** [comment] 2018-05-26 11:02
Please fill in the issue template.

**Comment by c0b41** [comment] 2018-05-28 10:22
@DeMoorJasper updated.

**Comment by elsheepo** [comment] 2018-09-22 04:46
when I bundle multiple entry points, I get my SCSS converted to CSS and bundled with bootstrap.css  as expected and jquery.js/bootstrap.js/custom.js bundled on the first html file in alphabetical order, and the rest only HTML & JavaScript, it is not adding the <link href="{name}{hash}.css"> to subsequent pages.
I have tried these...
`parcel *.html` and `parcel index.html about.html contact.html documentation.html repository.html` 

fyi: each page (index.html, about.html, etc) links to index.js like so...
`<script src="./index.js"></script>`

and the contents of index.js are...
    import './vendor/bootstrap/css/bootstrap.min.css'
    import './vendor/fontawesome-free/css/all.min.css'
    import './scss/custom.scss'
    import './vendor/jquery/jquery.min.js'
    import './vendor/bootstrap/js/bootstrap.bundle.min.js'
    import './js/custom.js'

So to reiterate, the first entry point (in alphabetical order, in my case it chooses about.html) gets links to both the bundled css & javascript, but the rest of the pages only get a link to the bundled javascript.

Here are the resulting about.html and index.html after having executed `parcel *.html`
notice how on line 16 of [about.html](http://dpaste.com/098R0CA) a link is inserted into the <head> referring to the bundled css. Where as in subsequent html files, such as [index.html](http://dpaste.com/2VMFXXA) there is not.

**Comment by lowtrux** [comment] 2018-11-13 06:59
Have anyone solved this problem, I have the same issue and i haven't been able to find a solution. Can't believe that parcel can't actually work with multiple entry points when comes to inject the same css to multiple html files. Any help will be really appreciated.

**Comment by mischnic** [comment] 2019-01-18 14:10
Closing as duplicate of #2340

**Closed by mischnic** 2019-01-18 14:10 UTC
Labels: :grey_question:  Question

**Comment by ikennobunga** [comment] 2019-09-21 04:56
Facing the same issue css only shows on the first index.html file and not on the following html files. Is there a solution to this?

**Comment by shasherazi** [comment] 2023-02-22 18:53
Still not solved.

**Comment by devongovett** [comment] 2023-02-22 19:13
Do you have a reproduction?

**Comment by shasherazi** [comment] 2023-02-22 19:29
> Do you have a reproduction?

My bad. I thought this issue was related to my problem.

I shared my problem [here](https://github.com/parcel-bundler/parcel/issues/2786#issuecomment-1440677380) in another issue.
