### ISSUE TITLE
Is parcel JS made for single page apps only? because static html files don't work

### ISSUE THREAD

**Issue by codingphasedotcom** [parcel-bundler/parcel#512] opened 2018-01-08 03:13 UTC
BUG REPORT
Is parcel JS made for single page apps only? because static html files don't work...
I've been working on a site that has 4 static pages so I decided to use parcel. Now everything works just fine as long as I don't link each file to each other.. and what I mean by that is if I add the same menu to all html files link to each page. the index.html file breaks and for what ever reason includes all 4 html files including their link tags and script tags in the body of the index.html which is the entry file. This makes no sense?

why would it be including all 4 html files inside the body tag of the index.html?    

I have no settings, no babel, just the current parcel version. On a mac..

**Comment by DeMoorJasper** [comment] 2018-01-08 08:05
Duplicate of #463

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-01-08 08:06 UTC
