### ISSUE TITLE
Importing html files does not work

### ISSUE THREAD

**Issue by otoinsa** [parcel-bundler/parcel#1082] opened 2018-03-28 12:27 UTC
🐛 bug report

```
{
  "name": "parcel-html-import-issue",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "parcel-bundler": "^1.6.2"
  }
}

```

index.html
```
<html>
	<head>
		<script src="index.js"></script>
	</head>
</html>
```

test.html
```
<div>
	test
</div>
```

index.js
```
import testHtml from './test.html'

console.log(testHtml)
```

### 🤔 Expected Behavior
Should be URI to html file, but produces module error:
![image](https://user-images.githubusercontent.com/7381482/38028660-436059ae-329c-11e8-8e45-28a1e86d6e7e.png)

Here's the project for good measure:
[parcel-html-import-issue.zip](https://github.com/parcel-bundler/parcel/files/1855933/parcel-html-import-issue.zip)

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.9.4
| npm/Yarn         | 5.6.0
| Operating System | Mac OS X

**Comment by teabyii** [comment] 2018-03-30 02:09
I think it is not a bug, but feature request. Maybe you can take a look at this PR: [Import/require html from js](https://github.com/parcel-bundler/parcel/pull/926). @otoinsa

**Comment by devongovett** [comment] 2019-01-06 02:33
Closing. An HTML bundler loader was added to Parcel a while ago.

**Closed by devongovett** 2019-01-06 02:33 UTC
Labels: :raising_hand_woman: Feature
