### ISSUE TITLE
Build not updating when "yarn link"ed module is updated

### ISSUE THREAD

**Issue by dawsonc623** [parcel-bundler/parcel#7967] opened 2022-04-17 16:27 UTC
I am developing a module alongside a Parcel-bundled app. The app has the module imported via `yarn link`. When updating the module, Parcel does not emit the app with the new module code. Instead, I have to kill Parcel, nuke `.parcel-cache`, restart Parcel, and refresh the page to get the new code.

This is not an ideal workflow, so I am wondering if there is some way to get Parcel to detect changes in the module code on its own.

**Comment by devongovett** [comment] 2022-04-17 18:41
Duplicate of #4332.

**Closed as completed by devongovett** 2022-04-17 18:41 UTC
